### ISSUE TITLE
When I simulated multiple sessions submitting data simultaneously, an exception occurred

### ISSUE THREAD

**Issue by ConanChan2012** [sqlalchemy/sqlalchemy#10017]
### Describe the bug

When I send `3` as the `loop_time` into `gather_insert_objects`, it is OK.   
But When I send `4` or more, It raise an exception.
  
And then , I tried `aiomysql`, get an exception, too. 
```python
    # the code at aiomysql.connection, line 629. 
    # packet_number = 1 
    # self._next_seq_id = 2
    raise InternalError(
        "Packet sequence number wrong - got %d expected %d" %
        (packet_number, self._next_seq_id))
```

### SQLAlchemy Version in Use

2.0.17

### DBAPI (i.e. the database driver)

asyncmy, aiomysql

### Database Vendor and Major Version

MySQL 8

### Python Version

3.11

### Operating system

macOS

### To Reproduce

```python
import asyncio
from datetime import datetime
from typing import List
from typing import Optional
from sqlalchemy import ForeignKey, BigInteger
from sqlalchemy import String, Date
from sqlalchemy.ext.asyncio import AsyncAttrs, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from random import randint
from uuid import uuid4
from sqlalchemy.ext.asyncio import create_async_engine


class MyBase(AsyncAttrs, DeclarativeBase):
    # pass
    __table_args__ = {
        "mysql_engine": 'InnoDB',
        "mysql_charset": 'utf8mb4'
    }


class TableMaster(MyBase):
    __tablename__ = "t_masters"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(100))

    details: Mapped[List["TableDetail"]] = relationship(back_populates="master")


class TableDetail(MyBase):
    __tablename__ = "t_details"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    master_id: Mapped[int] = mapped_column(ForeignKey("t_masters.id"))
    num: Mapped[Optional[int]]

    master: Mapped[TableMaster] = relationship(back_populates="details")


def append_master():
    m_list = []
    for _ in range(100):
        m = TableMaster(uuid=str(uuid4()))
        children_len = randint(1000, 2000)
        # print(m.uuid, "有", children_len, "个子项")

        for _ in range(children_len):
            m.details.append(
                TableDetail(num=randint(100, 999))
            )
        m_list.append(m)
    return m_list


async def async_insert_objects(async_session):
    async with async_session() as session:
        session_id = id(session)

        master_list = append_master()
        session.add_all(master_list)

        await session.commit()

    print("Over Once", session_id, datetime.now())


async def gather_insert_objects(loop_time):
    async_s_time = datetime.now()
    async_engine = create_async_engine("mysql+asyncmy://uname:pwd@127.0.0.1/j4t?charset=utf8mb4")
    async_session = async_sessionmaker(async_engine, expire_on_commit=False, autoflush=True)
    tasks = []
    for _ in range(loop_time):
        tasks.append(async_insert_objects(async_session))

    await asyncio.gather(*tasks)
    await async_engine.dispose()
    async_e_time = datetime.now()

    print(loop_time, "次异步循环全部完成:", async_e_time - async_s_time)
    print("\t", async_s_time)
    print("\t", async_e_time)

if __name__ == '__main__':
    asyncio.run(gather_insert_objects(4))
```

### Error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncmy/connection.pyx", line 521, in asyncmy.connection.Connection.connect
  File "asyncmy/connection.pyx", line 512, in asyncmy.connection.Connection.connect
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 279, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "asyncmy/connection.pyx", line 1299, in _connect
  File "asyncmy/connection.pyx", line 544, in connect
asyncmy.errors.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ()")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/j4t/sql/models.py", line 172, in <module>
    asyncio.run(gather_insert_objects())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/j4t/sql/models.py", line 128, in gather_insert_objects
    await asyncio.gather(*tasks)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/j4t/sql/models.py", line 92, in async_insert_objects
    await session.commit()
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 944, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1726, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in connection
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 975, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1109, in _connection_for_bind
    conn = self._parent._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1123, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 279, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conan/Documents/BK_Projects/mms/bk_crm_v2/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "asyncmy/connection.pyx", line 1299, in _connect
  File "asyncmy/connection.pyx", line 544, in connect
sqlalchemy.exc.OperationalError: (asyncmy.errors.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ()")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by oorjaa-sagar** [comment]
sidenote: the documentation is currently down, isn't it?

**Comment by CaselIT** [comment]
Hi,

The error seems to be an issue when connecting to the database.
Can you verify that your mysql config accepts more that 3 connections from the same client?

**Comment by ConanChan2012** [comment]
> Hi,
> 
> The error seems to be an issue when connecting to the database. Can you verify that your mysql config accepts more that 3 connections from the same client?

Yes, if I just read data, it works OK.
