### ISSUE TITLE
support Enum objects that have no elements...somehow....this is technically a regression even though ive never seen an enum like this

### ISSUE THREAD

**Issue by Daverball** [sqlalchemy/sqlalchemy#10030]
### Describe the bug

It looks like Enums that map to Callable objects and overwrite `__call__` will not map automatically with their proper name anymore.

I suppose it's possible that this a different error that was previously shadowed by the faulty behavior. But in the production database the enum type exists with the correct members. So at some point this definitely worked correctly.

### SQLAlchemy Version in Use

2.0.17

### DBAPI (i.e. the database driver)

psycopg2/psycopg

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

import enum

import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

DSN = "postgresql://test:test@localhost/test"


class Transform(enum.Enum):
    upper = str.upper
    lower = str.lower
    title = str.title

    def __call__(self, text: str) -> str:
        return self.value(text)


class Base(DeclarativeBase):
    pass


class SomeClass(Base):
    __tablename__ = "some_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    transform: Mapped[Transform]


e = create_engine(DSN, echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5792, in create_all
    bind._run_ddl_visitor(
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 912, in visit_metadata
    with self.with_ddl_events(
  File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 826, in with_ddl_events
    target.dispatch.before_create(
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 848, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1171, in _on_metadata_create
    t._on_metadata_create(target, bind, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/named_types.py", line 110, in _on_metadata_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/named_types.py", line 339, in create
    super().create(bind, checkfirst=checkfirst)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/named_types.py", line 51, in create
    bind._run_ddl_visitor(self.DDLGenerator, self, checkfirst=checkfirst)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/named_types.py", line 153, in visit_enum
    self.connection.execute(CreateEnumType(enum))
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1521, in _execute_ddl
    compiled = ddl.compile(
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 69, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 866, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 911, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2178, in visit_create_enum_type
    self.preparer.format_type(type_),
  File "/home/david/git/certificateclaim/env/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2661, in format_type
    raise exc.CompileError(
sqlalchemy.exc.CompileError: PostgreSQL ENUM type requires a name.
```

**Comment by zzzeek** [comment]
oh.  You are using a kind of `Enum` that I have never seen before.  it has no elements!   how does this work?

**Comment by zzzeek** [comment]
If I run this on MySQL, the ENUM is invalid, it has no members:

```
1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') NOT NULL, \n\tPRIMARY KEY (id)\n)' at line 3")
[SQL: 
CREATE TABLE some_table (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	transform ENUM() NOT NULL, 
	PRIMARY KEY (id)
)

]

```

can I understand the use case here?

**Comment by Daverball** [comment]
@zzzeek Wow, you are correct. I forgot that I ran into this before somewhere else and I just ended up wrapping the function in a tuple in that case. This part of the code hasn't been exercised super well yet, although I was pretty sure I tested the text transformations and they worked.

Let me make sure this actually ever worked.

**Comment by zzzeek** [comment]
so the change in #9963 made the assumption that if the enum type we are using has no members, assume it's not a "real" enum to be made into a SQL type.   but that causes the error condition here to be about the name for PG and not the missing members.

**Comment by Daverball** [comment]
Alright I think it never worked in the SQLAlchemy model case. The reason I thought it did work, is because there's also a static dataclass version of the Model without an ORM, and it just so happens that mypy doesn't catch this error: `reveal_type(Transform.upper)` will yield `Literal[Transform.upper]` even though it should be `def (self: builtins.str) -> builtins.str`

The way I was using it made no difference, since a dataclass can store a function just as well, and it's still callable in the same way and `is` checks still work. But for SQLAlchemy it obviously does make a difference.

**Comment by Daverball** [comment]
So it looks like it's an unfortunate case of where both SQLAlchemy and mypy shadowed the error and it also happened to be a code path that just wasn't exercised very well yet, so it never popped up in Sentry either.

I've created an issue in mypy. SQLAlchemy is fine, it does the correct thing.

**Comment by Daverball** [comment]
@zzzeek The only thing I would consider improvising is maybe raising a `ValueError` with a helpful message for an enum without any members. This should always be an error probably. It just so happens, that Postgres allows an empty enum type.

**Comment by CaselIT** [comment]
@Daverball this is a better version of what you wanted to do.
Works also with mypy and sqlalchemy
```py
import enum


class Transform(enum.Enum):
    upper = enum.auto()
    lower = enum.auto()
    title = enum.auto()

    def __call__(self, text: str) -> str:
        return getattr(str, self.name)(text)


print(Transform.upper("fOo"))
print(Transform.lower("fOo"))
print(Transform.title("fOo"))

```
