### ISSUE TITLE
url.make_url returning not URL instances 

### ISSUE THREAD

**Issue by grigoriev-semyon** [sqlalchemy/sqlalchemy#10079]
### Describe the bug

If you pass an object to `create_engine`, for example, of the type `<class 'pydantic_core._pydantic_core.MultiHostUrl'>`
that sqlalchemy will fall with an error, since the `url.make_url` function takes as an argument either a string, or an object of the URL type, or Mock for testing.

I believe that the SQLAlchemy should warn that an invalid type has been passed.

### SQLAlchemy Version in Use

2.0.18

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
from pydantic import PostgresDsn
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Application settings"""
    DB_DSN: PostgresDsn = 'postgresql://postgres@localhost:5432/postgres'

create_engine(Settings().DB_DSN)
```

### Error

```
Traceback (most recent call last):
  File ".../venv/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File ".../venv/lib/python3.11/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File ".../venv/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File ".../venv/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File ".../venv/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File ".../venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File ".../venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".../migrations/env.py", line 82, in <module>
    run_migrations_online()
  File ".../migrations/env.py", line 66, in run_migrations_online
    connectable = engine_from_config(
                  ^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 806, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File ".../venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'pydantic_core._pydantic_core.MultiHostUrl' object has no attribute '_instantiate_plugins'

```

**Comment by sqla-tester** [comment]
**Grigoriev Semyon** has proposed a fix for this issue in the **main** branch:

**Fix url.make_url** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4740
