### ISSUE TITLE
Missing selected aggregation function columns in results

### ISSUE THREAD

**Issue by BaaaZen** [sqlalchemy/sqlalchemy#10165]
### Describe the bug

I was trying to create statistics (number of vulnerabilities and the maximum risk for three different score types) for some ports. So I'm doing an outter join from `SQL_Port` to `SQL_Vulnerability` and using aggregation functions for `count` and `max`.

When getting the results from the query, instead of getting a tuple with 5 elements, I only get the first element. The values from the aggregation functions are missing.

### SQLAlchemy Version in Use

2.0.19

### DBAPI (i.e. the database driver)

mysqlconnector

### Database Vendor and Major Version

MariaDB 10.11.4

### Python Version

3.11.4

### Operating system

Windows

### To Reproduce

```python
from __future__ import annotations
from contextlib import contextmanager
from typing import Generator
from sqlalchemy import create_engine, func, or_, select
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm.session import Session
from typing import Annotated
from sqlalchemy.orm import Mapped, relationship, DeclarativeBase, mapped_column, MappedAsDataclass
from sqlalchemy.sql.schema import ForeignKey

MY_CONNECTION_STRING = 'mysql+mysqlconnector://username:password@host/db'

_engine = create_engine(MY_CONNECTION_STRING, pool_recycle=600)
_sessionmaker = sessionmaker(bind=_engine, autocommit=False)

@contextmanager
def sql_session() -> Generator[Session, None, None]:
    session = _sessionmaker()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()

class Base(MappedAsDataclass, DeclarativeBase):
    pass

fk_port = Annotated[int, mapped_column(ForeignKey('port.port_id'))]
pk_int = Annotated[int, mapped_column(primary_key=True)]

class SQL_Port(Base):
    __tablename__ = 'port'
    port_id: Mapped[pk_int] = mapped_column(init=False)
    is_stats_dirty: Mapped[bool] = mapped_column(default=True)
    score_cvss_v2: Mapped[int|None] = mapped_column(default=None)
    score_cvss_v3: Mapped[int|None] = mapped_column(default=None)
    score_risk: Mapped[int|None] = mapped_column(default=None)
    num_vulnerabilities: Mapped[int|None] = mapped_column(default=None)
    ref_vulnerabilities: Mapped[list[SQL_Vulnerability]] = relationship(back_populates='ref_port', passive_deletes=True, default_factory=list)

class SQL_Vulnerability(Base):
    __tablename__ = 'vulnerability'
    vulnerability_id: Mapped[pk_int] = mapped_column(init=False)
    port_id: Mapped[fk_port|None] = mapped_column(init=False)
    is_active: Mapped[bool]
    bucket: Mapped[int]
    score_risk: Mapped[int]
    score_cvss_v2: Mapped[int|None] = mapped_column(default=None)
    score_cvss_v3: Mapped[int|None] = mapped_column(default=None)
    ref_port: Mapped[SQL_Port|None] = relationship(back_populates='ref_vulnerabilities', passive_deletes=True, default=None)


def get_statistics() -> None:
    with sql_session() as sql:
        query = select(SQL_Port, func.count(SQL_Vulnerability.vulnerability_id), func.max(SQL_Vulnerability.score_cvss_v2), func.max(SQL_Vulnerability.score_cvss_v3), func.max(SQL_Vulnerability.score_risk)) \
            .filter(SQL_Port.is_stats_dirty == True) \
            .join(SQL_Port.ref_vulnerabilities.and_(
                    SQL_Vulnerability.is_active == True,
                    or_(
                        SQL_Vulnerability.bucket == 3,
                        SQL_Vulnerability.bucket == 10
                    )
                ), 
                isouter=True
            ) \
            .group_by(SQL_Port.port_id)

        results = sql.scalars(query).all()

        # this line prints "<class 'SQL_Port'>" instead of "<class 'tuple'>"
        print(type(results[0]))
        # this line prints "False" instead of "True"
        print(isinstance(results[0], tuple))

        for result in results:
            # this line fails with "TypeError: cannot unpack non-iterable SQL_Port object"
            sql_port, vulns_count, score_cvss_v2, score_cvss_v3, score_risk = result
                        
            # ... process results ...

if __name__ == '__main__':
    get_statistics()
```

### Error

```
Traceback (most recent call last):
  File "C:\Users\hansen\Git\vuma\vuma-server\tmp_test\sqlalchemy-test.py", line 85, in <module>
    get_statistics()
  File "C:\Users\hansen\Git\vuma\vuma-server\tmp_test\sqlalchemy-test.py", line 80, in get_statistics
    sql_port, vulns_count, score_cvss_v2, score_cvss_v3, score_risk = result
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable SQL_Port object
```

**Comment by zzzeek** [comment]
hi there -

this line:

    results = sql.scalars(query).all()

returns a [ScalarResult](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.ScalarResult) set that contains only the first column of each row, which in this case is the `SQL_Port` object.   You want to use `session.execute()`.

closing as no bug is illustrated here
