### ISSUE TITLE
implement RETURNING * for new ORM enabled DML INSERT/UPDATE/DELETE

### ISSUE THREAD

**Issue by laricko** [sqlalchemy/sqlalchemy#10192]
### Describe the bug

`NotImplementedError` with `.returning(literal_column("*"))`

but with `.returning(Table)` works

This is unexpected behavior because in a previous versions it works

### SQLAlchemy Version in Use

2.0.15

### DBAPI (i.e. the database driver)

psycopg2-binary

### Database Vendor and Major Version

postgresql 15

### Python Version

3.11.4

### Operating system

linux (wsl)

### To Reproduce

```python
query_work = update(Table).values(data).where(Table.id == id).returning(Table)
query_not_work = update(Table).where(Table.id == id).values(data).returning(literal_column("*")
print(query_not_work) # even when you print this query it crashes
```

### Error

```
Traceback (most recent call last):
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/src/middleware.py", line 14, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/src/middleware.py", line 32, in __call__
    return self.app(environ, new_start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/src/auth.py", line 17, in check_user
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/src/api/task.py", line 36, in patch_task
    task = crud.patch_task(id, request.form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/src/crud_task.py", line 46, in patch_task
    print(query1)
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 291, in __str__
    return str(self.compile())
               ^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 6002, in visit_update
    compile_state = update_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 678, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1413, in create_for_statement
    self._setup_for_orm_update(statement, compiler)
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1505, in _setup_for_orm_update
    new_stmt = self._setup_orm_returning(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 536, in _setup_orm_returning
    fsc.setup_dml_returning_compile_state(dml_mapper)
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 846, in setup_dml_returning_compile_state
    entity.setup_dml_returning_compile_state(self, adapter)
  File "/home/lari/projects/time-manager/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 2501, in setup_dml_returning_compile_state
    raise NotImplementedError()
NotImplementedError
```

**Comment by zzzeek** [comment]
INSERT/UPDATE/DELETE in 2.0 are [all new](https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html) and in many cases "RETURNING *" is not usable by the ORM, in particular for bulk statements, so special logic must be added to block for all the unsupported scenarios while allowing other scenarios through
