### ISSUE TITLE
Using default timestamp leads to error

### ISSUE THREAD

**Issue by Krzmbrzl** [sqlalchemy/sqlalchemy#10196]
### Describe the bug

Trying to use a default timestamp for one of my columns, will lead to an error due to an invalid date format in the produced string.

### SQLAlchemy Version in Use

2.0.19

### DBAPI (i.e. the database driver)

stock sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
import datetime

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import sessionmaker
from sqlalchemy import func
from sqlalchemy import create_engine


class Base(DeclarativeBase):
    pass


class MyThing(Base):
    __tablename__ = "mythings"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime.date] = mapped_column(server_default=func.now())


def main():
    engine = create_engine("sqlite:///sampleDB.sqlite", echo=True)

    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)

    with Session() as session:
        thing = MyThing()

        session.add(thing)

        session.commit()


if __name__ == "__main__":
    main()
```

### Error

```2023-08-07 16:57:00,891 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-08-07 16:57:00,892 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("mythings")
2023-08-07 16:57:00,892 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-08-07 16:57:00,892 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("mythings")
2023-08-07 16:57:00,892 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-08-07 16:57:00,893 INFO sqlalchemy.engine.Engine 
CREATE TABLE mythings (
        id INTEGER NOT NULL, 
        timestamp DATE DEFAULT (CURRENT_TIMESTAMP) NOT NULL, 
        PRIMARY KEY (id)
)


2023-08-07 16:57:00,893 INFO sqlalchemy.engine.Engine [no key 0.00010s] ()
2023-08-07 16:57:00,900 INFO sqlalchemy.engine.Engine COMMIT
2023-08-07 16:57:00,902 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-08-07 16:57:00,904 INFO sqlalchemy.engine.Engine INSERT INTO mythings DEFAULT VALUES RETURNING id, timestamp
2023-08-07 16:57:00,904 INFO sqlalchemy.engine.Engine [generated in 0.00022s] ()
2023-08-07 16:57:00,904 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/tmp/repro.py", line 38, in <module>
    main()
  File "/tmp/repro.py", line 34, in main
    session.commit()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2342, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1981, in _exec_single_context
    result = context._setup_result_proxy()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1781, in _setup_result_proxy
    result = self._setup_dml_or_text_result()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1895, in _setup_dml_or_text_result
    rows = result.all()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1390, in all
    return self._allrows()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 557, in _allrows
    made_rows = [make_row(row) for row in rows]
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 557, in <listcomp>
    made_rows = [make_row(row) for row in rows]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 16, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 73, in sqlalchemy.cyextension.resultproxy._apply_processors
  File "lib/sqlalchemy/cyextension/processors.pyx", line 45, in sqlalchemy.cyextension.processors.str_to_date
ValueError: Invalid isoformat string: '2023-08-07 14:57:00'
``` 

### Additional context

Note that the error only occurs if the corresponding object is created explicitly within Python code. If the entry is instead created implicitly (due to a secondary (indirect) relation), the error does not occur. This makes me suspect that when the processing of the date string is done by the database rather than within Python, the parsing routine is less strict about the ISO format.

**Comment by zzzeek** [comment]
this is expected since it is attempting to INSERT a timestamp value into a date column, which is not covered.

correct code should use datetime:

    timestamp: Mapped[datetime.datetime] = mapped_column(server_default=func.now())

**Comment by Krzmbrzl** [comment]
Thanks for the clarification. I explicitly want a _date_ and not a _datetime_ though. But I have found a workaround that suits my needs.

**Comment by zzzeek** [comment]
OK, for general help please open discussions so that we can assign the right people

**Comment by CaselIT** [comment]
You probably need to use a different default function insead of now
