### ISSUE TITLE
decl_api.py  `@compat_typing.dataclass_transform(     field_descriptors=(` issue

### ISSUE THREAD

**Issue by lewis-morris** [sqlalchemy/sqlalchemy#10191]
### Describe the bug

Running 32bit python on windows 10. Version 2.0.19

in my version the below is field_specifiers. I've changed it manually and works fine, but there is an issue somewhere. 

On my linux box, 2.0.19 is fine, on windows 32bit, the same version has a invalid parameter `field specifiers` 

2.0.19 linux 64bit python 3.10
```
@compat_typing.dataclass_transform(
    field_descriptors=(....)
)

```

2.0.19 windows 32bit python 3.9 
```
@compat_typing.dataclass_transform(
    field_specifiers=(....)
)

```

### SQLAlchemy Version in Use

2.0.19

### DBAPI (i.e. the database driver)

n/a

### Database Vendor and Major Version

n/a

### Python Version

3.9

### Operating system

windows

### To Reproduce

```python
conda 32bit 3.9 python
pip install the version 2.0.19
try to import anything pretty much from sqlalchemny.orm
```

### Error

Connected to pydev debugger (build 232.8660.197)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\warehouse.LBS\Miniconda3\envs\label_printer\lib\site-packages\sqlalchemy\orm\__init__.py", line 57, in <module>
    from .decl_api import add_mapped_attribute as add_mapped_attribute
  File "C:\Users\warehouse.LBS\Miniconda3\envs\label_printer\lib\site-packages\sqlalchemy\orm\decl_api.py", line 152, in <module>
    @compat_typing.dataclass_transform(
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
python-BaseException

Process finished with exit code 1

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
This is most likely a too old version of typing extension.

Can you post what version you have on the two installs?

**Comment by CaselIT** [comment]
Sorry I wasn't clear. I meant of the package `typing_extension`
