### ISSUE TITLE
Mypy: @declared_attr crash mypy when using "--follow-imports=silent"

### ISSUE THREAD

**Issue by k4nar** [sqlalchemy/sqlalchemy#10282]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

When mypy is configured to [follow import but suppress error messages](https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports) (eg: with `--follow-imports=silent`), any `@declared_attr` in a module imported will crash mypy >= 1.4.0.

### To Reproduce

```python
# example.py

from sqlalchemy import Column, String
from sqlalchemy.orm import Mapped, declared_attr, declarative_mixin


@declarative_mixin
class Foo:
    @declared_attr
    def bar(cls) -> Mapped[str]:
        return Column(String)


# example2.py
from example import Foo
```

### Error

```
example.py:-1: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.5.1
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 5141, in accept
  File "mypy/nodes.py", line 2207, in accept
  File "mypy/checkexpr.py", line 4633, in visit_lambda_expr
  File "mypy/nodes.py", line 2200, in expr
IndexError: list index out of range
example.py:-1: : note: use --pdb to drop into pdb
``` 

### Versions

- OS: linux
- Python: 3.11.3
- SQLAlchemy: 2.0.20 & 1.4.49
- Type checker: mypy >= 1.4.0 (for some reason, it works with mypy 1.3.1)

### Additional context

The error happens in mypy [at this line](https://github.com/python/mypy/blob/v1.5.1/mypy/nodes.py#L2200). This is because the `Block` passed when creating the `LambdaExpr` [here](https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_20/lib/sqlalchemy/ext/mypy/decl_class.py#L340-L342) is empty.

**Comment by zzzeek** [comment]
hi -

we unfortunately don't have resources to keep tracking these down as mypy keeps changing but we do accept pull requests with tests.

**Comment by k4nar** [comment]
Ok, thanks, I understand :slightly_smiling_face: . I'll try to submit a fix.

**Comment by zzzeek** [comment]
thanks for tracking that down!

**Comment by Hnasar** [comment]
I'm getting a similar failure, even without `--follow-imports=silent` and with a smaller failing example

```ini
# mypy.ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
show_traceback = true
```

```py
# foo.py
from sqlalchemy import orm

@orm.declarative_mixin
class Item:

    @orm.declared_attr
    def info_map(cls) -> orm.MapperProperty[int]:
        ...
```

```
/usr/bin/python -m mypy --config-file atl/src/make/mypy_v2.ini foo.py
foo.py:-1: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.7.1
Traceback (most recent call last):
  File "lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "mypy/checkexpr.py", line 5727, in accept
  File "mypy/nodes.py", line 2211, in accept
  File "mypy/checkexpr.py", line 5202, in visit_lambda_expr
  File "mypy/nodes.py", line 2205, in expr
AssertionError:
foo.py:-1: : note: use --pdb to drop into pdb
```

and if i run from mypy master

```
$ ~/sources/mypy/venv/bin/mypy foo.py
foo.py:-1: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.9.0+dev.b956e6a57c4dd36d670097a3eccf7dc092348fec
Traceback (most recent call last):
  File "/home/hashem/sources/mypy/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/hashem/sources/mypy/mypy/__main__.py", line 15, in console_entry
    main()
  File "/home/hashem/sources/mypy/mypy/main.py", line 100, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/hashem/sources/mypy/mypy/main.py", line 182, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/hashem/sources/mypy/mypy/build.py", line 192, in build
    result = _build(
  File "/home/hashem/sources/mypy/mypy/build.py", line 266, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/hashem/sources/mypy/mypy/build.py", line 2942, in dispatch
    process_graph(graph, manager)
  File "/home/hashem/sources/mypy/mypy/build.py", line 3340, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/hashem/sources/mypy/mypy/build.py", line 3441, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/hashem/sources/mypy/mypy/build.py", line 2310, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/hashem/sources/mypy/mypy/checker.py", line 481, in check_first_pass
    self.accept(d)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 595, in accept
    stmt.accept(self)
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 1142, in accept
    return visitor.visit_class_def(self)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 2313, in visit_class_def
    self.accept(defn.defs)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 595, in accept
    stmt.accept(self)
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 1223, in accept
    return visitor.visit_block(self)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 2775, in visit_block
    self.accept(s)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 595, in accept
    stmt.accept(self)
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 1310, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 2823, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 3000, in check_assignment
    rvalue_type = self.check_simple_assignment(lvalue_type, rvalue, context=rvalue)
  File "/home/hashem/sources/mypy/mypy/checker.py", line 4157, in check_simple_assignment
    rvalue_type = self.expr_checker.accept(
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 5742, in accept
    typ = node.accept(self)
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 1904, in accept
    return visitor.visit_call_expr(self)
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 476, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 605, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 1443, in check_call_expr_with_callee_type
    ret_type, callee_type = self.check_call(
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 1553, in check_call
    return self.check_any_type_call(args, callee)
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 3200, in check_any_type_call
    self.infer_arg_types_in_empty_context(args)
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 1871, in infer_arg_types_in_empty_context
    arg_type = self.accept(arg)
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 5742, in accept
    typ = node.accept(self)
          ^^^^^^^^^^^^^^^^^
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 2213, in accept
    return visitor.visit_lambda_expr(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hashem/sources/mypy/mypy/checkexpr.py", line 5217, in visit_lambda_expr
    ret_type = self.accept(e.expr(), allow_none_return=True)
                           ^^^^^^^^
  File "/home/hashem/sources/mypy/mypy/nodes.py", line 2207, in expr
    assert isinstance(ret, ReturnStmt)
AssertionError:
foo.py:-1: : note: use --pdb to drop into pdb
```

**Comment by zzzeek** [comment]
the mypy plugin is removed as of SQLAlchemy 2.1 and support for newer mypy versions was also ended, so trying to fix things here is no longer feasible
