### ISSUE TITLE
sqlAlchemy Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by faganchalabizada** [sqlalchemy/sqlalchemy#10327]
### Describe the bug

I'm getting an error after a few hours of db inactivity. 
mysql has timeout (8 hours) that disconnects the connection. To get around this error, I added all these parameters in order:

     engine = create_engine(url, pool_timeout=7, pool_recycle=60, pool_pre_ping=True, isolation_level="AUTOCOMMIT")

But none of them helped.

First the connection is reset and gives an error sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') then exception=PendingRollbackError("Can't reconnect until invalid transaction is rolled back. Please rollback() fully before proceeding")

### SQLAlchemy Version in Use

2.0.17

### DBAPI (i.e. the database driver)

mysql+pymysql

### Database Vendor and Major Version

MySQL 8

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
import traceback
from asyncio import get_event_loop

# Initialize the bot and dispatcher
from sqlalchemy import create_engine, URL, text
from sqlalchemy.exc import OperationalError, PendingRollbackError
from sqlalchemy.orm import sessionmaker, declarative_base, scoped_session

from config import DB_DRIVER_NAME, DB_USERNAME, DB_HOST, DB_PASSWORD, DB_DATABASE

loop = get_event_loop()

Base = declarative_base()

url = URL.create(
    drivername=DB_DRIVER_NAME,
    username=DB_USERNAME,
    host=DB_HOST,
    password=DB_PASSWORD,
    database=DB_DATABASE
)

engine = create_engine(url, pool_recycle=3, pool_pre_ping=True, isolation_level="AUTOCOMMIT")

connection = engine.connect()

connection.execute(text("SET wait_timeout=5"))  # Short timeout for testing pool_recycle.
connection.execute(text("SELECT 1"))

print("Create new session")
Session = scoped_session(sessionmaker(bind=engine))
session = Session()


def run():
    input("Press enter for sending SELECT 1 query")
    print("sql execution start")
    connection.execute(text("SELECT 1"))  # This throws the error.
    connection.commit()
    print("sql commit end")
    run()


if __name__ == '__main__':
    try:
        run()
    except OperationalError or PendingRollbackError:
        print("OperationalError PendingRollbackError manual rollback")
        traceback.print_exc()
        session.rollback()
        session.close()
        run()
```

### Error

```
Traceback (most recent call last):
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 748, in _read_packet
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kama/CommonImageRates/test.py", line 47, in <module>
    run()
  File "/home/kama/CommonImageRates/test.py", line 42, in run
    run()
  File "/home/kama/CommonImageRates/test.py", line 42, in run
    run()
  File "/home/kama/CommonImageRates/test.py", line 39, in run
    connection.execute(text("SELECT 1"))  # This throws the error.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 748, in _read_packet
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Press enter for sending SELECT 1 query
sql execution start
Traceback (most recent call last):
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 748, in _read_packet
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kama/CommonImageRates/test.py", line 47, in <module>
    run()
  File "/home/kama/CommonImageRates/test.py", line 42, in run
    run()
  File "/home/kama/CommonImageRates/test.py", line 42, in run
    run()
  File "/home/kama/CommonImageRates/test.py", line 39, in run
    connection.execute(text("SELECT 1"))  # This throws the error.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/pymysql/connections.py", line 748, in _read_packet
    raise err.OperationalError(
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kama/CommonImageRates/test.py", line 53, in <module>
    run()
  File "/home/kama/CommonImageRates/test.py", line 39, in run
    connection.execute(text("SELECT 1"))  # This throws the error.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    conn = self._revalidate_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 665, in _revalidate_connection
    self._invalid_transaction()
  File "/home/kama/CommonImageRates/venv/lib64/python3.11/site-packages/sqlalchemy/engine/base.py", line 655, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
``` 

### Additional context

Reproduce error:

run script
is has 5 seconds timeout. Press enter for sending query.
if wait 5 seconds then press enter again it will gives Lost connection error.
press enter again, it will give PendingRollbackError error.

**Comment by CaselIT** [comment]
Hi,

That's expected. You are creating a connection at module level and then keep using that. How can any of the pool parameters take effect if you never return the connection to the pool?

Create a new connection inside run using `with engine.connect() as conn:`
