### ISSUE TITLE
selectin_polymorphic raises AttributeError _path_registry

### ISSUE THREAD

**Issue by commonism** [sqlalchemy/sqlalchemy#10330]
### Describe the bug

When creating the MRE I've found another one - FIXME 1, so this is currently 2 issues, will split the ticket if required.

### FIXME 1 
A backref does not exist for use in  selectin_polymorphic before the model was used otherwise and the backref got initialized.
Here: Change.entities does not exist.

I can workaround this.

### FIXME 2
selectin_polymorphic raises 
`Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Change.entity has an attribute '_path_registry'`

##

Problem exists independent of database, came from postgres, fails for sqlite as well.

### SQLAlchemy Version in Use

2.0.20

### DBAPI (i.e. the database driver)

sqlite+aiosqlite

### Database Vendor and Major Version

sqlite3

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
from pathlib import Path
import asyncio
import uuid

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy.orm import declarative_base, selectin_polymorphic
from sqlalchemy.orm import relationship
from sqlalchemy import DateTime, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession

Base = declarative_base()

JSONB = INET = UUID = String

class Entity(Base):
    __tablename__ = "entities"

    entity = Column(Integer, primary_key=True, index=True)
    identity = Column(String(50), index=True)
    changes = relationship("Change", backref="entity", lazy="select")

    __mapper_args__ = {"polymorphic_identity": "entity", "polymorphic_on": identity}


class Change(Base):
    __tablename__ = "changes"

    change = Column(Integer, primary_key=True, index=True)
    _entity = Column(Integer, ForeignKey("entities.entity"), nullable=False, index=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    remote_host = Column(INET, index=True)
    data = Column(JSONB, nullable=False)


class Account(Entity):
    __tablename__ = "accounts"
    __mapper_args__ = {
        "polymorphic_identity": "account",
    }

    _entity = Column(Integer, ForeignKey("entities.entity"), nullable=False, index=True)

    account_id = Column(
        UUID,
        primary_key=True,
        default=uuid.uuid4,
        index=True,
        unique=True,
    )

async def create_db():
    engine = create_async_engine("sqlite+aiosqlite://")#, echo='debug')
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    sm = sessionmaker(engine, class_=AsyncSession)
    return engine, sm

async def main():
    engine, sm = await create_db()
    import sqlalchemy

    try:
        async with sm() as session:
            q = select(Change).options(
                selectin_polymorphic(Change.entity, [Account]))
            await session.execute(q)
    except Exception as e:
        # FIXME 1
        assert e.args[0] == "type object 'Change' has no attribute 'entity'"
        print(e)

    try:
        async with sm() as session:
            # 'touching' the model before use initializes the backref
            q = select(sqlalchemy.func.count(Change.change))
            total = (await session.execute(q)).scalars().first()

            q = select(Change).options(
                selectin_polymorphic(Change.entity, [Account]))

            await session.execute(q)
    except AttributeError as e:
        # FIXME 2
        assert e.args[0] == """Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Change.entity has an attribute '_path_registry'"""
        print(e)
        raise e

asyncio.run(main())
```

### Error

```
Traceback (most recent call last):
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 471, in __getattr__
    return getattr(self.comparator, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1331, in __getattr__
    return self._fallback_getattr(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1300, in _fallback_getattr
    raise AttributeError(key)
AttributeError: _path_registry

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.config/JetBrains/PyCharm2023.2/scratches/scratch_113.py", line 92, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "~/.config/JetBrains/PyCharm2023.2/scratches/scratch_113.py", line 90, in main
    raise e
  File "~/.config/JetBrains/PyCharm2023.2/scratches/scratch_113.py", line 83, in main
    selectin_polymorphic(Change.entity, [Account]))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 2430, in selectin_polymorphic
    ul = Load(base_cls)
         ^^^^^^^^^^^^^^
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 999, in __init__
    self.path = insp._path_registry
                ^^^^^^^^^^^^^^^^^^^
  File "~/venv/acmetk/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 473, in __getattr__
    raise AttributeError(
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Change.entity has an attribute '_path_registry'
```

### Additional context

Works with 1.4.49, ceased working with 2.0.0

**Comment by CaselIT** [comment]
Hi

Regarding point 1, version 2 initializes more of the orm lazily. It means that backref does not work reliably until this initialization is done. This is usually on the first query. You can use [`configure_mappers`](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.configure_mappers) to manually initialized them

Regarding point 2, this syntax `selectin_polymorphic(Change.entity, [Account])` is not supported in any sqlalchemy version. The proper way of doing that documented here https://docs.sqlalchemy.org/en/20/orm/queryguide/inheritance.html#applying-selectin-polymorphic-to-an-existing-eager-load
