### ISSUE TITLE
NoSuchColumnError: "Could not locate column in row for column 'host_mappings.id'"

### ISSUE THREAD

**Issue by Huihuihh** [sqlalchemy/sqlalchemy#10345]
### Describe the bug

When a instance evacuate，there is a error NoSuchColumnError

### SQLAlchemy Version in Use

1.1.11

### DBAPI (i.e. the database driver)

PyMySQL

### Database Vendor and Major Version

mariadb 10.1.30

### Python Version

2.7.5

### Operating system

linux

### To Reproduce

```python
Cannot reproduce
```

### Error

2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server [None req-2b2c3921-32cc-4aa2-97c4-b379f24e110c a9553af0f7e54bfca9b9aa2f871e5b81 0d9152afc69b422c82f634b8120bc44f - default default] Exception during message handling: NoSuchColumnError: "Could not locate column in row for column 'host_mappings.id'"
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 163, in _process_incoming
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 226, in inner
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     return func(*args, **kwargs)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 159, in select_destinations
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     alloc_reqs_by_rp_uuid, provider_summaries)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 93, in select_destinations
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     alloc_reqs_by_rp_uuid, provider_summaries)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 226, in _schedule
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     provider_summaries, num_inst=num_instances)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 473, in _get_all_host_states
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     num_inst=num_inst)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/host_manager.py", line 694, in get_host_states_by_uuids
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     num_inst=num_inst, utctime=utctime)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/host_manager.py", line 742, in _get_host_states
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     self._get_instance_info(context, compute),
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/host_manager.py", line 789, in _get_instance_info
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     return self._get_instances_by_host(context, compute.host)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/scheduler/host_manager.py", line 766, in _get_instances_by_host
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     hm = objects.HostMapping.get_by_host(context, host_name)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_versionedobjects/base.py", line 184, in wrapper
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     result = fn(cls, context, *args, **kwargs)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/objects/host_mapping.py", line 100, in get_by_host
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     db_mapping = cls._get_by_host_from_db(context, host)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 984, in wrapper
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     return fn(*args, **kwargs)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/objects/host_mapping.py", line 93, in _get_by_host_from_db
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     .filter(api_models.HostMapping.host == host)).first()
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     ret = list(self[0:1])
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     return list(res)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     util.raise_from_cause(err)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     rows = [proc(row) for row in fetch]
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 382, in _instance
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     tuple([row[column] for column in pk_cols])
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 563, in _key_fallback
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server     expression._string_or_unprintable(key))
2023-09-09 00:12:10.868 529841 ERROR oslo_messaging.rpc.server NoSuchColumnError: "Could not locate column in row for column 'host_mappings.id'"

**Comment by CaselIT** [comment]
Hi,

There is no reproduction code, so its unlikely much help can be given.
Sqlalchemy 1.1 is also no longer supported, by more than 6 years.

Since the error indicates that a column is missing, check the db or the query to verify that it has said column
