### ISSUE TITLE
Adding Composite Column Types to base unmapped class fails migration script generation

### ISSUE THREAD

**Issue by anil-enable** [sqlalchemy/sqlalchemy#10378]
**Describe the bug**
I was going through the tutorial for adding composite column types where sets of columns can be associated with a single user-defined datatype (FYR https://docs.sqlalchemy.org/en/20/orm/composites.html#composite-column-types).

I followed the example and added the classes. Post this I ran the `alembic revision --autogenerate` to auto generate the migration scripts. This generated the migration scripts.

I tweaked the example a bit and moved this composite column definition to a base unmapped class and had a concrete mapped class extend this class. Post this the auto-generation fails.

**Expected behavior**
I expect the auto generation to work when I define a composite column on a base unmapped class. 

**To Reproduce**

Example 1 works, example 2 doesn't work.

```py
import dataclasses
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, composite, mapped_column

class Base(MappedAsDataclass, DeclarativeBase):
    pass

@dataclasses.dataclass
class Point:
    x: int
    y: int

# Example 1 
# as per tutorial in https://docs.sqlalchemy.org/en/20/orm/composites.html#composite-column-types
# added composite columns start and end
# auto-generation works for this

class Vertex(Base):
    __tablename__ = "vertices"

    id: Mapped[int] = mapped_column(primary_key=True)

    start: Mapped[Point] = composite(mapped_column("x1"), mapped_column("y1"))
    end: Mapped[Point] = composite(mapped_column("x2"), mapped_column("y2"))

# Example 2
# moved composite columns start, end to base unmapped class
# added a concrete mapped class that extends this class
# auto-generation fails for this

class BaseVertex(Base):
    __abstract__ = True

    id: Mapped[int] = mapped_column(primary_key=True)

    start: Mapped[Point] = composite(mapped_column("x1"), mapped_column("y1"))
    end: Mapped[Point] = composite(mapped_column("x2"), mapped_column("y2"))


class NamedVertex(BaseVertex):
    __tablename__ = "named_vertex"
    name: Mapped[str] = mapped_column()

```

**Error**

```
Traceback (most recent call last):
  File "/example/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/example/.venv/lib/python3.11/site-packages/alembic/config.py", line 630, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/example/.venv/lib/python3.11/site-packages/alembic/config.py", line 624, in main
    self.run_cmd(cfg, options)
  File "/example/.venv/lib/python3.11/site-packages/alembic/config.py", line 601, in run_cmd
    fn(
  File "/example/.venv/lib/python3.11/site-packages/alembic/command.py", line 233, in revision
    script_directory.run_env()
  File "/example/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/example/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/example/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/example/src/app/migrations/env.py", line 7, in <module>
    from app.models import Base
  File "/example/src/app/models.py", line 12, in <module>
    from .models.vertex import NamedVertex, Vertex
  File "/example/src/app/models/vertex.py", line 40, in <module>
    class NamedVertex(BaseVertex):
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 625, in __init_subclass__
    super().__init_subclass__()
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 847, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/example/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 884, in _scan_attributes
    raise exc.InvalidRequestError(
**sqlalchemy.exc.InvalidRequestError: Mapper properties (i.e. deferred,column_property(), relationship(), etc.) must be declared as @declared_attr callables on declarative mixin classes.  For dataclass field() objects, use a lambda:**
```

**Versions.**
 - OS: macOS Ventura
 - Python: 3.11.4
 - Alembic: 1.12.0
 - SQLAlchemy: 2.0.21
 - Database: PostgreSQL 15
 - DBAPI: psycopg2-binary@2.9.7

**Additional context**
Not sure if this is a bug or a miss from my side. If not, any reference to related documentation will be helpful.

**Have a nice day!**

**Comment by CaselIT** [comment]
I've moved to sqlalchemy since alembic is not involved in the error
