### ISSUE TITLE
__allow_unmapped__ mode is somehow tripping over builtin `list`, others ?

### ISSUE THREAD

**Issue by pcorpet** [sqlalchemy/sqlalchemy#10385]
### Describe the bug

When trying to make sense of type annotations written as strings, SQLAlchemy looks only for imported generic types (e.g. `typing.List`). After Python 3.10, the builtin types are now generic as well (e.g. `dict` or `list`).

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
import sqlalchemy
import sqlalchemy.orm

Base = sqlalchemy.orm.declarative_base()


class User(Base):
    __tablename__ = "user"
    __allow_unmapped__ = True

    id: int = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)


class Group(Base):
    __tablename__ = "group"
    __allow_unmapped__ = True

    id: int = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)

    users: "list[User]" = sqlalchemy.orm.relationship(
        User,
        uselist=True,
    )
```

### Error

```
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 250, in eval_name_only
    return base_globals[name]
KeyError: 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2229, in _cleanup_mapped_str_annotation
    obj = eval_name_only(mm.group(1), originating_module)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 252, in eval_name_only
    raise NameError(
NameError: Could not locate name list in module __main__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2321, in _extract_mapped_subtype
    annotated = de_stringify_annotation(
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 154, in de_stringify_annotation
    annotation = str_cleanup_fn(annotation, originating_module)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2231, in _cleanup_mapped_str_annotation
    raise _CleanupError(
sqlalchemy.orm.util._CleanupError: For annotation "list[User]", could not resolve container type "list".  Please ensure this type is imported at the module level outside of TYPE_CHECKING blocks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/me/myproject/myproject/test_sqlalchemy.py", line 14, in <module>
    class Group(Base):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1006, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1277, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myproject-1teD3aNO-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2328, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not interpret annotation list[User].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.
``` 

### Additional context

The example looks a bit easy to fix here, however I'm facing it against a large codebase while trying to migrate to SQLAlchemy v2.0 which already enforces the use of `list` instead of `typing.List`.

Happy to provide a PR that checks on `__builtins__` in `sqlalchemy.util.typing.eval_name_only`.

**Comment by CaselIT** [comment]
Hi,

Strange that the annotations play a role at all here, since you are not using `Mapped`. The fix is likely to ensure the annotations are ignored in these cases

**Comment by zzzeek** [comment]
ok this is allow_unmapped mode that explicitly allows these technically mis-typed entries in, and it somehow knows about `List` and not `list`,  and indeed it's eval_name_only needs to know about builtins.

the other thing confusing me, why do the "ints" work, mmmm those are mapped to `Column` which is going down a different codepath but it looks like if `mapped_column()` is used, a different codepath is still used, no error is produced, but we get the column with no type in a similar way as #10380

anyway yes, PR for eval_name_only would be fine, thanks

**Comment by pcorpet** [comment]
Thanks @zzzeek , I've started a PR. I have trouble testing as we don't have mypy tests that is restricted on a Python version (post 3.9). Can you provide some guidance please? otherwise I'll coin something

**Comment by zzzeek** [comment]
the tests here aren't really for mypy, they're for SQLAlchemy's runtime interpretation of annotations.  the test would be right around here: https://github.com/sqlalchemy/sqlalchemy/blob/5b60145d31f3332fc843698461e058ebbafab38c/test/orm/declarative/test_typed_mapping.py#L2161 where we really just need to expand out that existing test to work against `list` and maybe others like `set`, `typing.Set` etc.     this can be done with `testing.variations` as you see in examples like https://github.com/sqlalchemy/sqlalchemy/blob/5b60145d31f3332fc843698461e058ebbafab38c/test/orm/declarative/test_typed_mapping.py#L2926 .


There's more that has to go on for a full CI pass but dont worry about that yet.

**Comment by sqla-tester** [comment]
**Pascal Corpet** has proposed a fix for this issue in the **main** branch:

**handle builtins types in annotations with __allow_unmapped__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4874
