### ISSUE TITLE
Pandas to_sql error with sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s)

### ISSUE THREAD

**Issue by djpirra** [sqlalchemy/sqlalchemy#10386]
### Describe the bug

I am currently running a parallel set of functions that write data into different tables in Oracle database.
Those tables should be dropped and recreated in every run.

When I am executing the pandas dataframe to_sql using below statement:

`
dtyp = {c:types.VARCHAR(200) for c in df.columns.tolist()}
df.to_sql(table_name, engine, if_exists='replace', dtype = dtyp, index=False, method='multi')
`

I am getting the below error:

`sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(oracle+oracledb://:***@)...`

I want my table names to be in upper case.

### SQLAlchemy Version in Use

2.0,21

### DBAPI (i.e. the database driver)

oracledb

### Database Vendor and Major Version

Oracle 19c

### Python Version

3.8.13

### Operating system

Debian

### To Reproduce

```python
With a pandas dataframe:

dtyp = {c:types.VARCHAR(200) for c in df.columns.tolist()}
df.to_sql(table_name, engine, if_exists='replace', dtype = dtyp, index=False, method='multi')
```

### Error

sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(oracle+oracledb://:***@): (TABLE_NAME)

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:555)
        at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:713)
        at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:695)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:508)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1030)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2254)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

**Comment by djpirra** [comment]
As additional information, the table is created successfully but apparently when data is to be copied it gives the mentioned error.

Also tried specifying the schema instead of default and same issue.

**Comment by CaselIT** [comment]
Hi,

there is nothing actionable in the provided description, so moving to discussion.

Regarding pandas I know thy have taken a bit to update to fully support sqlalchemy2, so try one of the latest versions
