### ISSUE TITLE
raw query with parameter not working on DDL query

### ISSUE THREAD

**Issue by BimaAdi** [sqlalchemy/sqlalchemy#10401]
### Describe the bug

I try to switch database driver from psycopg2 to psycopg but I found some odd error behavior when performing raw DDL query with parameter.

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import Boolean, Column, Integer, String, create_engine, text
from sqlalchemy.orm import sessionmaker, scoped_session, declarative_base

# Create sqlalchemy session
username = "postgres"
password = "password"
host = "127.0.0.1"
port = 5432
database = "postgres"

engine_psycopg2 = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}",
    pool_size=20,
    max_overflow=0,
    pool_timeout=300,
)
Session_psycopg2 = sessionmaker(engine_psycopg2, future=True)
db_session_psycopg2 = scoped_session(Session_psycopg2)

engine_psycopg3 = create_engine(
    f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}",
    pool_size=20,
    max_overflow=0,
    pool_timeout=300,
)
Session_psycopg3 = sessionmaker(engine_psycopg3, future=True)
db_session_psycopg3 = scoped_session(Session_psycopg3)

# base for model
Base = declarative_base()


class Todo(Base):
    __tablename__ = "todo"

    id = Column("id", Integer, primary_key=True, nullable=False, index=True)
    todo = Column("todo", String, nullable=False)
    is_done = Column("is_done", Boolean, default=False)


def create_all_table():
    Base.metadata.create_all(engine_psycopg3)


def delete_all_table():
    Base.metadata.drop_all(engine_psycopg3)


create_all_table()

with db_session_psycopg2() as db:
    db.execute(
        text("ALTER SEQUENCE public.todo_id_seq RESTART :x"),
        {"x": 3},
    )  # working on psycopg2

with db_session_psycopg3() as db:
    db.execute(
        text("ALTER SEQUENCE public.todo_id_seq RESTART :x"),
        {"x": 5},
    )  # not working on psycopg, produce error on stacktrace

delete_all_table()
```

### Error

Traceback (most recent call last):
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File ".../env/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.SyntaxError: syntax error at or near "$1"
LINE 1: ALTER SEQUENCE public.todo_id_seq RESTART $1
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../main.py", line 58, in <module>
    db.execute(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2153, in _execute_internal
    result = conn.execute(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File ".../env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File ".../env/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.ProgrammingError: (psycopg.errors.SyntaxError) syntax error at or near "$1"
LINE 1: ALTER SEQUENCE public.todo_id_seq RESTART $1
                                                  ^
[SQL: ALTER SEQUENCE public.todo_id_seq RESTART %(x)s]
[parameters: {'x': 5}]
(Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by CaselIT** [comment]
Hi,

Since you are using a text query this isn't a behaviour that sqlalchemy controls.

DDL statements don't support parameters in general but it depends on the driver if they do allow them or not.

You should either use literal binds in sqlalchemy or look of psycopg supports doing the same
