### ISSUE TITLE
Cannot interpret WriteOnlyMapped[TestItem]: NameError raised

### ISSUE THREAD

**Issue by francipvb** [sqlalchemy/sqlalchemy#10412]
### Describe the bug

When writing a relationship without quotes, a `NameError` is raised, but with quotes it works.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/large_collections.html

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

not applicable

### Database Vendor and Major Version

not applicable

### Python Version

3.11

### Operating system

linux

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import orm


class Base(orm.DeclarativeBase):
    pass


class Parent2(Base):
    __tablename__ = "item2"

    item_id: orm.Mapped[int] = orm.mapped_column(primary_key=True, autoincrement=True)

    # This does not work
    subitems: "orm.WriteOnlyMapped[Subitem]" = orm.relationship()

    # This does not work
    subitems2: orm.WriteOnlyMapped[Subitem2] = orm.relationship()


class Parent(orm.MappedAsDataclass, Base):
    __tablename__ = "item"

    item_id: orm.Mapped[int] = orm.mapped_column(primary_key=True, autoincrement=True)

    # This works
    subitems: "orm.WriteOnlyMapped[Subitem]" = orm.relationship()

    # This does not work
    subitems2: orm.WriteOnlyMapped[Subitem2] = orm.relationship()


class Subitem(Base):
    __tablename__ = "subitem"

    item_id: orm.Mapped[int] = orm.mapped_column(primary_key=True, autoincrement=True)
    name: orm.Mapped[str] = orm.mapped_column()


class Subitem2(Base):
    __tablename__ = "subitem2"

    item_id: orm.Mapped[int] = orm.mapped_column(primary_key=True, autoincrement=True)
    name: orm.Mapped[str] = orm.mapped_column()
```

### Error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/francipvb/vectman/workers/testsa.py", line 10, in <module>
    class Parent2(Base):
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 847, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1006, in _scan_attributes
    collected_annotation = self._collect_annotation(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1277, in _collect_annotation
    extracted = _extract_mapped_subtype(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francipvb/vectman/workers/.venv/lib/python3.11/site-packages/sqlalchemy/orm/util.py", line 2364, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "Parent2.subitems" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)

``` 

### Additional context

I found these conclusions:

- Works with mapped as dataclass and quoted.
- Does not work with mapped as dataclass unquoted.
- In either mode, does not work for quoted nor unquoted.

Not tested for already defined classes, but these cases should work equally.

**Comment by francipvb** [comment]
In the title I said `NameError` is raised. Not the provided case, but found in some other.

**Comment by zzzeek** [comment]
you can import WriteOnlyMapped directly to work around

```
from sqlalchemy.orm import WriteOnlyMapped
```

**Comment by zzzeek** [comment]
also using a string annotation `"orm.Mapped[int]"` with `from __future__ import annotations` mode does not seem to work at all for any flavor of `Mapped`.

**Comment by zzzeek** [comment]
so...that would be a separate issue.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include WriteOnlyMapped, DynamicMapped in abs import lookup** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4894

**Comment by francipvb** [comment]
> also using a string annotation `"orm.Mapped[int]"` with `from __future__ import annotations` mode does not seem to work at all for any flavor of `Mapped`.

Very strange. After I've started to use future annotations I've stopped using quoted type hints at all.
