### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dbapi_connection' 

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10414]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10413

we can show the error with this demo

```py
from sqlalchemy import create_engine



e = create_engine("postgresql://scott:tiger@localhost/test", echo_pool='debug')


conn = e.connect()

conn.connection._connection_record.invalidate()
del conn



```

```
]$ python test3.py 
\2023-10-04 09:09:37,106 DEBUG sqlalchemy.pool.impl.QueuePool Created new connection <connection object at 0x7fe0e9d81940; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
2023-10-04 09:09:37,110 DEBUG sqlalchemy.pool.impl.QueuePool Connection <connection object at 0x7fe0e9d81940; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0> checked out from pool
2023-10-04 09:09:37,111 INFO sqlalchemy.pool.impl.QueuePool Invalidate connection <connection object at 0x7fe0e9d81940; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
2023-10-04 09:09:37,111 DEBUG sqlalchemy.pool.impl.QueuePool Hard-closing connection <connection object at 0x7fe0e9d81940; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7fe0e96cd6c0>
Traceback (most recent call last):
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/pool/base.py", line 732, in <lambda>
    lambda ref: _finalize_fairy(
                ^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/pool/base.py", line 1043, in _finalize_fairy
    fairy.dbapi_connection = fairy._connection_record = None  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dbapi_connection'

```

should just check for that

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**check fairy for None in pool cleanup** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4895
