### ISSUE TITLE
DDL.__repr__ raises exception

### ISSUE THREAD

**Issue by iurisilvio** [sqlalchemy/sqlalchemy#10443]
### Describe the bug

It raises exception because `DDL.on` is not defined.

Looks like `DDL.on` was removed in 57877461c1bd3b43a9d833fbca873d59db36b6f7.

We have some probably outdated docstrings talking about `DDL.on`.
https://github.com/sqlalchemy/sqlalchemy/blob/c5d89aad3634a40e5d067c8df97bb7f775983e02/lib/sqlalchemy/sql/ddl.py#L525
https://github.com/sqlalchemy/sqlalchemy/blob/c5d89aad3634a40e5d067c8df97bb7f775983e02/lib/sqlalchemy/sql/ddl.py#L677

```python
>>> from sqlalchemy import DDL
>>> DDL("SELECT 1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/biq13w2a1hyjhpza36msff5b55n9wb2j-python3-3.11.4-env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 411, in __repr__
    + [
      ^
  File "/nix/store/biq13w2a1hyjhpza36msff5b55n9wb2j-python3-3.11.4-env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 414, in <listcomp>
    if getattr(self, key)
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'DDL' object has no attribute 'on'
```

### SQLAlchemy Version in Use

2.0.19

### DBAPI (i.e. the database driver)

sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import DDL
DDL("SELECT 1")
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/biq13w2a1hyjhpza36msff5b55n9wb2j-python3-3.11.4-env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 411, in __repr__
    + [
      ^
  File "/nix/store/biq13w2a1hyjhpza36msff5b55n9wb2j-python3-3.11.4-env/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 414, in <listcomp>
    if getattr(self, key)
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'DDL' object has no attribute 'on'
```

**Comment by sqla-tester** [comment]
**Iuri de Silvio** has proposed a fix for this issue in the **main** branch:

**repair / test repr() for DDL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4902
