### ISSUE TITLE
Setting implicit_returning causes multiple inserts to fail

### ISSUE THREAD

**Issue by tomflannaghan** [sqlalchemy/sqlalchemy#10453]
### Describe the bug

I've found that setting `implicit_returning` to False on a table causes multiple inserts into that table to fail with a FlushError.

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

SQL Server 12

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
import logging

import pyodbc
from sqlalchemy import BigInteger, Column, Numeric, create_engine
from sqlalchemy.orm import sessionmaker, scoped_session, declarative_base

Base = declarative_base()


class Testing(Base):
    __tablename__ = "testing"
    __table_args__ = {
        'implicit_returning': False,
        'schema': 'pos'
    }

    id = Column(BigInteger, primary_key=True, nullable=False)
    quantity = Column(Numeric(28, 8), nullable=False)


logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

connection_info = "...."  # I've removed my connection string
connection = pyodbc.connect(connection_info, autocommit=False)
engine = create_engine("mssql://" + connection_info, creator=lambda: connection)
session = scoped_session(sessionmaker(bind=engine, autoflush=False))

session.add_all([Testing(quantity=1) for i in range(10)])
session.flush()
session.rollback()
```

### Error

```
(python_upgrade) E:\dev\greshamquant\datamanagement\scripts\consolidated>python E:\dev\greshamquant\sqlalchemy_bug.py
INFO:sqlalchemy.engine.Engine:SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:SELECT schema_name()
INFO:sqlalchemy.engine.Engine:[generated in 0.00025s] ()
INFO:sqlalchemy.engine.Engine:SELECT CAST('test max support' AS NVARCHAR(max))
INFO:sqlalchemy.engine.Engine:[generated in 0.00026s] ()
INFO:sqlalchemy.engine.Engine:SELECT 1 FROM fn_listextendedproperty(default, default, default, default, default, default, default)
INFO:sqlalchemy.engine.Engine:[generated in 0.00025s] ()
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:INSERT INTO pos.testing (quantity) VALUES (?), (?), (?), (?), (?), (?), (?), (?), (?), (?)
INFO:sqlalchemy.engine.Engine:[generated in 0.00016s (insertmanyvalues) 1/1 (unordered)] (1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
INFO:sqlalchemy.engine.Engine:ROLLBACK
Traceback (most recent call last):
  File "E:\dev\greshamquant\sqlalchemy_bug.py", line 32, in <module>
    session.flush()
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\scoping.py", line 897, in flush
    return self._proxied.flush(objects=objects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\session.py", line 4179, in flush
    self._flush(objects)
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\session.py", line 4314, in _flush
    with util.safe_reraise():
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\session.py", line 4275, in _flush
    flush_context.execute()
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "E:\envs\python_upgrade\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1174, in _emit_insert_statements
    raise orm_exc.FlushError(
sqlalchemy.orm.exc.FlushError: Multi-row INSERT statement for Mapper[Testing(testing)] did not produce the correct number of INSERTed rows for RETURNING.  Ensure there are no triggers or special driver issues preventing INSERT from functioning properly.
``` 

### Additional context

The table doesn't need to have any triggers for the error. The DDL for the table in the example script is as follows:

```
create table pos.testing
(
    id       bigint identity
        primary key,
    quantity numeric(28, 8) not null
)
go
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont enter do_executemany if implicit_returning is False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4897

**Comment by zzzeek** [comment]
thanks for reporting
