### ISSUE TITLE
no warning emitted when non-hashable column value used in result.unique()

### ISSUE THREAD

**Issue by floan** [sqlalchemy/sqlalchemy#10459]
### Describe the bug

When using chained joinedloads on a query that contains subqueries that use `group_by`, deduplication fails. More comments / edgecases commented in the testcase! 

Note: This is using 1.4.46, NOT 2.0.x 

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#joined-eager-loading

### SQLAlchemy Version in Use

1.4.46

### DBAPI (i.e. the database driver)

pg8000

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.9/3.11

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Account(Base):
    __tablename__ = "account"
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    name = sa.Column(sa.String)
    provider_id = sa.Column(
        sa.Integer,
        sa.ForeignKey("provider.id"),
        nullable=True,
    )
    # If I use a secondary table for this, the duplication
    # does not occur, I'm not sure why...
    provider = sa.orm.relationship(
        "Provider",
        back_populates="provider_accounts",
        uselist=False
    )
    symptoms = sa.orm.relationship("Symptom", backref="account")


class Provider(Base):
    __tablename__ = "provider"
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    name = sa.Column(sa.String, nullable=False)
    practices = sa.orm.relationship(
        "Practice",
        secondary="provider_practice",
        back_populates="providers",
    )
    provider_accounts = sa.orm.relationship(
        "Account", back_populates="provider"
    )

class Practice(Base):
    __tablename__ = "practice"
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    name = sa.Column(sa.String, nullable=False)
    providers = sa.orm.relationship(
        "Provider", secondary="provider_practice", back_populates="practices"
    )

class Symptom(Base):
    __tablename__ = "symptom"
    id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
    account_id = sa.Column(
        sa.Integer, sa.ForeignKey("account.id"), primary_key=True, index=True
    )
    value = sa.Column(sa.String)

provider_practice = sa.Table(
    "provider_practice",
    Base.metadata,
    sa.Column(
        "provider_id",
        sa.ForeignKey("provider.id"),
        primary_key=True,
    ),
    sa.Column(
        "practice_id",
        sa.ForeignKey("practice.id"),
        primary_key=True,
        index=True,
    ),
)


def run_test():
    # Create postgres database "test" before running
    engine = sa.create_engine('postgresql+pg8000://fayezloan:abcd1234@localhost:5432/test')
    asessionmaker = sa.orm.sessionmaker(autocommit=False, autoflush=False, future=True)
    asessionmaker.configure(bind=engine)
    session = asessionmaker()

    # Delete stale data
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    account = Account(name="Albert")
    session.add(account)
    provider = Provider(name="Bob")
    session.add(provider)
    practice_1 = Practice(name="Practice1")
    practice_2 = Practice(name="Practice2")
    session.add(practice_1)
    session.add(practice_2)
    session.commit()

    provider.practices.append(practice_1)
    provider.practices.append(practice_2)
    account.provider_id = provider.id
    session.commit()

    symptom = Symptom(value="symptom1", account_id=account.id)
    session.add(symptom)
    session.commit()

    symptom_subquery = (
        session.query(
            Symptom.account_id,
            sa.func.json_agg(
                sa.func.json_build_object(
                    "id",
                    Symptom.id,
                    "value",
                    Symptom.value,
                )
            ).label("symptoms"),
        )
        .group_by(Symptom.account_id)
        .subquery()
    )

    query = (
        session.query(
            Account, 
            symptom_subquery.c.symptoms
        )
        .options(sa.orm.joinedload(Account.provider).joinedload(Provider.practices))
        .join(
            symptom_subquery,
            Account.id == symptom_subquery.c.account_id,
            isouter=True
        )
        .filter(Account.id == account.id)
    )

    result = query.all()

    # This should be 1, but is actually 2
    # Behavior only occurs when subqueries (symptom_subquery)
    # Have a group_by statement.
    # Number of duplications == number of provider.practices, not sure why
    print(f"Total number of results={len(result)}")
    
    # Both the results are identical
    print(result[0] == result[1])


    # Using selectinload or removing joinedload 
    # returns expected result

    query = (
        session.query(
            Account, 
            symptom_subquery.c.symptoms
        )
        .options(sa.orm.selectinload(Account.provider).selectinload(Provider.practices))
        .join(
            symptom_subquery,
            Account.id == symptom_subquery.c.account_id,
            isouter=True
        )
        .filter(Account.id == account.id)
    )

    result = query.all()
    # 1 Account as expected 
    print(f"Total number of results={len(result)}")



if __name__ == "__main__":
    run_test()
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 
No error, incorrect runtime behavior

### Additional context

I've added important details / edge cases that mitigate this problem as comments in the code where it's relevant! Thank you!

**Comment by zzzeek** [comment]
OK not much we can do here, this is legacy.

using 2.0 style queries with a datatype:

```py
    symptom_subquery = (
        sa.select(
            Symptom.account_id,
            sa.func.json_agg(
                sa.func.json_build_object(
                    "id",
                    Symptom.id,
                    "value",
                    Symptom.value,
                ), type_=sa.JSON
            ).label("symptoms"),
        )
        .group_by(Symptom.account_id)
        .subquery()
    )

    query = (
        sa.select(
            Account,
            symptom_subquery.c.symptoms
        )
        .options(sa.orm.joinedload(Account.provider).joinedload(Provider.practices))
        .join(
            symptom_subquery,
            Account.id == symptom_subquery.c.account_id,
            isouter=True
        )
        .filter(Account.id == account.id)
    )

    result = session.execute(query).unique().all()

```

we get a nice error:


```
sqlalchemy.exc.InvalidRequestError: Can't apply uniqueness to row tuple containing value of type JSON(); this datatype produces non-hashable values
```

without the type, things break in a less good way

```
  Base = declarative_base()
Traceback (most recent call last):
  File "/mnt/photon_home/classic/dev/sqlalchemy/test3.py", line 141, in <module>
    run_test()
  File "/mnt/photon_home/classic/dev/sqlalchemy/test3.py", line 131, in run_test
    result = session.execute(query).unique().all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1390, in all
    return self._allrows()
           ^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 566, in _allrows
    interim_rows = [
                   ^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 575, in <listcomp>
    if sig_row not in uniques and not uniques.add(sig_row)  # type: ignore # noqa: E501
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/_py_row.py", line 83, in __hash__
    return hash(self._data)
           ^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'

```

so will look to see if that can be improved.   doesnt change much for the end result here

**Comment by floan** [comment]
Thanks so much for the quick response and investigation!! I really appreciate it! Do you have any idea why selectinload doesn't contain duplicates as compared to joinedload?

**Comment by CaselIT** [comment]
Because there is no join that creates duplicate rows of the main table

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**informative warnings/ errors for all types of unknown / non-hashability** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4900
