### ISSUE TITLE
Issue with relationship typing when using Declarative-Imparative Mapping

### ISSUE THREAD

**Issue by halbow** [sqlalchemy/sqlalchemy#10531]
### Describe the bug

Hi

First of all thank you for the huge amount of work done on SQLAlchemy, I really enjoy this library :rocket: 

I'm trying to implement a many-to-many relationship (like explained [here](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#setting-bi-directional-many-to-many), this example works perfectly fine) with SQLAlchemy using Declarative “Imperative Table” such as described [here](https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#mapping-attrs-with-declarative-imperative-table).

I cannot get it working due to to the type hint being dependent on each other: `children: Mapped[List[Child]]` in `Parents`  depends on `Child` class which has annotation `parents: Mapped[List[Parent]]` which depends on Parents as well.

Note that I tried to start from [this example from the documentation](https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#mapping-attrs-with-declarative-imperative-table) and it has the same issue, it raises the same error: `NameError: Could not de-stringify annotation 'Address'`

Is this a limitation of the Declarative-imperative mode ?

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#mapping-attrs-with-declarative-imperative-table

### SQLAlchemy Version in Use

2.0.20

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

Mysql

### Python Version

3.10.7

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import Column
from sqlalchemy import Table
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import relationship


class Base(DeclarativeBase):
    pass


association_table = Table(
    "association_table",
    Base.metadata,
    Column("left_id", ForeignKey("left_table.id"), primary_key=True),
    Column("right_id", ForeignKey("right_table.id"), primary_key=True),
)


class Parent(Base):
    __tablename__ = "left_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    children: Mapped[List[Child]] = relationship(
        secondary=association_table, back_populates="parents"
    )


class Child(Base):
    __tablename__ = "right_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    parents: Mapped[List[Parent]] = relationship(
        secondary=association_table, back_populates="children"
    )
```

### Error

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 220, in eval_expression
    annotation = eval(expression, base_globals, locals_)
  File "<string>", line 1, in <module>
NameError: name 'Address' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/dev/my_project/mre.py", line 22, in <module>
    class User:
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 1690, in mapped
    _as_declarative(self, cls, cls.__dict__)
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1006, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1300, in _collect_annotation
    elem = de_stringify_annotation(
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 156, in de_stringify_annotation
    annotation = eval_expression(
  File "/home/user/.pyenv/versions/my_project/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 222, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'Address'
``` 

### Additional context

This is a copy paste from the documentation example [here](https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#mapping-attrs-with-declarative-imperative-table)

**Comment by CaselIT** [comment]
Hi,

The provided example works without issue for me. Can you check if it's the correct version that gives you the error?

The linked example https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#mapping-attrs-with-declarative-imperative-table does indeed have an issue, so thanks for reporting.
@zzzeek I think the call to `mapper_registry.mapped` runs the full annotation scan, instead of delaying it like then using the inheritance

**Comment by LeonxLJX** [comment]
I'd like to take this one.

Thanks for the report — the `2.0.20` version context is useful. Before changing anything I'd like to reproduce this against current `main` first, since the surrounding code may have moved since this was filed.

Plan: trace the path, reproduce it, then make the smallest change that addresses it, plus a regression test if this area has coverage. If the root cause turns out to live somewhere other than where the report points, I'll report back here before forcing a change.

Anything already known about this that I should read first? (relevant PRs, existing tests, known constraints)

(claiming via @LeonxLJX)
