### ISSUE TITLE
Committing two or more ORM objects with BIT columns causes DBAPIError

### ISSUE THREAD

**Issue by soldag** [sqlalchemy/sqlalchemy#10532]
### Describe the bug

I have a model with a column using the `BIT` postgresql type. When creating a single object, everything is working fine, but as soon as I create multiple objects and commit, I get a `sqlalchemy.exc.DBAPIError` exception.

This seems to be related to #9808 and #9739.

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 13

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import asyncio

from asyncpg import BitString
from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import BIT


async_engine = create_async_engine(
    "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/test",
    pool_pre_ping=True,
    echo=True,
)

AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
)


class Base(DeclarativeBase):
    __abstract__ = True
    metadata = MetaData()


class Test(Base):
    __tablename__ = "tests"

    id: Mapped[int] = mapped_column(
        autoincrement=True,
        nullable=False,
        unique=True,
        primary_key=True,
    )

    data: Mapped[BitString] = mapped_column(BIT(2))


async def main():
    async with async_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    models = [
        Test(data=BitString.from_int(1, length=2)),
    ]

    async with AsyncSessionLocal() as session:
        for m in models:
            session.add(m)
        await session.commit()  # no errors

    content = [
        Test(data=BitString.from_int(1, length=2)),
        Test(data=BitString.from_int(2, length=2)),
    ]

    async with AsyncSessionLocal() as session:
        for m in content:
            session.add(m)

        try:
            await session.commit()
        except Exception:
            await session.rollback()
            raise


if __name__ == "__main__":
    asyncio.run(main())
```

### Error
```
2023-10-24 13:27:40,768 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-10-24 13:27:40,768 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-10-24 13:27:40,770 INFO sqlalchemy.engine.Engine select current_schema()
2023-10-24 13:27:40,770 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-10-24 13:27:40,772 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-10-24 13:27:40,772 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-10-24 13:27:40,774 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-10-24 13:27:40,779 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2023-10-24 13:27:40,779 INFO sqlalchemy.engine.Engine [generated in 0.00029s] ('tests', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-10-24 13:27:40,785 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2023-10-24 13:27:40,785 INFO sqlalchemy.engine.Engine [cached since 0.006268s ago] ('tests', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-10-24 13:27:40,786 INFO sqlalchemy.engine.Engine 
CREATE TABLE tests (
	id SERIAL NOT NULL, 
	data BIT(2) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (id)
)


2023-10-24 13:27:40,786 INFO sqlalchemy.engine.Engine [no key 0.00010s] ()
2023-10-24 13:27:40,802 INFO sqlalchemy.engine.Engine COMMIT
2023-10-24 13:27:40,807 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-10-24 13:27:40,809 INFO sqlalchemy.engine.Engine INSERT INTO tests (data) VALUES ($1) RETURNING tests.id
2023-10-24 13:27:40,809 INFO sqlalchemy.engine.Engine [generated in 0.00028s] (<BitString 01>,)
2023-10-24 13:27:40,812 INFO sqlalchemy.engine.Engine COMMIT
2023-10-24 13:27:40,817 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-10-24 13:27:40,818 INFO sqlalchemy.engine.Engine INSERT INTO tests (data) SELECT p0::BIT(2) FROM (VALUES ($1, 0), ($2, 1)) AS imp_sen(p0, sen_counter) ORDER BY sen_counter RETURNING tests.id, tests.id AS id__1
2023-10-24 13:27:40,819 INFO sqlalchemy.engine.Engine [generated in 0.00014s (insertmanyvalues) 1/1 (ordered)] (<BitString 01>, <BitString 10>)
2023-10-24 13:27:40,821 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "asyncpg/protocol/prepared_stmt.pyx", line 168, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg/protocol/codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg/protocol/codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg/pgproto/./codecs/text.pyx", line 29, in asyncpg.pgproto.pgproto.text_encode
  File "asyncpg/pgproto/./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got BitString

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 552, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: <BitString 01> (expected str, got BitString)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 586, in execute
    self._adapt_connection.await_(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 564, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 803, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <BitString 01> (expected str, got BitString)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/soldag/Downloads/example.py", line 70, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/soldag/Downloads/example.py", line 63, in main
    await session.commit()
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 1004, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1967, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4310, in flush
    self._flush(objects)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4445, in _flush
    with util.safe_reraise():
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4406, in _flush
    flush_context.execute()
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 586, in execute
    self._adapt_connection.await_(
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 564, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/soldag/.cache/pypoetry/virtualenvs/test-guOS-Etp-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 803, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <BitString 01> (expected str, got BitString)
[SQL: INSERT INTO tests (data) SELECT p0::BIT(2) FROM (VALUES ($1, 0), ($2, 1)) AS imp_sen(p0, sen_counter) ORDER BY sen_counter RETURNING tests.id, tests.id AS id__1]
[parameters: (<BitString 01>, <BitString 10>)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
```

**Comment by zzzeek** [comment]
I see you have a PR coming up, great :)

**Comment by sqla-tester** [comment]
**Sören Oldag** has proposed a fix for this issue in the **main** branch:

**Add bind casts for BIT on asyncpg** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4916
