### ISSUE TITLE
pysqlcipher open fail with err: TypeError: function takes at most 3 arguments (4 given) in dbapi_connection.create_function

### ISSUE THREAD

**Issue by WoolenWang** [sqlalchemy/sqlalchemy#10544]
### Describe the bug

using windows and pysqlcipher  in python 3.11 get error to create engine with very basic usage

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

pysqlcipher 

### Database Vendor and Major Version

pysqlcipher3

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import create_engine
e = create_engine(
    'sqlite+pysqlcipher://:some_passphrase@/db1.sqlite'
)
with e.connect() as conn:
    conn.exec_driver_sql("create table if not exists foo(id integer)")
    print("Existing rows: %s" % (conn.exec_driver_sql("select * from foo").all(), ))
    conn.exec_driver_sql("insert into foo (id) values (1)")
    print(conn.scalar("SELECT 1"))
```

### Error

```

Traceback (most recent call last):
  File "D:\running\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 7, in <module>
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\engine\base.py", line 3268, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\engine\base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\impl.py", line 421, in connect
    return _ConnectionFairy._checkout(self, self._fairy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\impl.py", line 403, in _do_get
    c = self._create_connection()
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\pool\base.py", line 916, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\event\attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\event\attr.py", line 487, in __call__
    fn(*args, **kw)
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\engine\create.py", line 704, in on_connect
    do_on_connect(dbapi_connection)
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\dialects\sqlite\pysqlcipher.py", line 145, in on_connect
    super_on_connect(conn)
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 574, in connect
    fn(conn)
  File "E:\git\python-3.11.6\Lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 557, in set_regexp
    dbapi_connection.create_function(
TypeError: function takes at most 3 arguments (4 given)

``` 

### Additional context

https://github.com/rigglemania/pysqlcipher3/blob/master/src/python3/connection.c#L833

the create_function only accept 3 params and the kwargs 
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L552

make this error

**Comment by WoolenWang** [comment]
try this pr to fix https://github.com/sqlalchemy/sqlalchemy/pull/10545
