### ISSUE TITLE
The process_result_value of a column is not overridden when overridding a column type when extending an existing table.

### ISSUE THREAD

**Issue by GuilhermeReda** [sqlalchemy/sqlalchemy#10629]
### Describe the bug

The process_result_value of a column is not overridden when overridding a column type when extending an existing table.

In the repro script, I have defined a custom column type that will always raise an exception when processing a result value, regardless of what it's given.
Then, I mapped a table, where a column is using that custom type.
After, I'm overriding the original table mapping, and changing the column type from my custom type to a simple integer.

In versions > 1.3, this will always raise the custom type's exception, even though the field no longer has that type.

### SQLAlchemy Version in Use

1.4.50

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, Column, Integer, TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


engine = create_engine('postgresql://user:password@localhost/postgres')
Base = declarative_base()


# This custom type will always raise an exception when processing a result value
class CustomType(TypeDecorator):
    impl = Integer

    def process_result_value(self, value, dialect):
        raise ValueError("CustomType result processing raised an exception for value: {}".format(value))


class FirstTable(Base):
    __tablename__ = 'test_table'

    id = Column(Integer, primary_key=True)
    # this field will always raise an exception when queried
    custom_column = Column(CustomType)


# extend the first table, overriding the custom_column type
class OverriddenFirstTable(FirstTable):
    __tablename__ = 'test_table'
    __table_args__ = {'extend_existing': True}

    # override the type CustomType.
    # This should return values without raising an exception
    custom_column = Column(Integer)


if __name__ == '__main__':
    # Create tables in the database
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    row = session.add(OverriddenFirstTable(custom_column=42))
    fetched_row = session.query(OverriddenFirstTable).first()
    print(f"custom_column value: {fetched_row.custom_column}")
```

### Error

```
Traceback (most recent call last):
  File "/app.py", line 43, in <module>
    fetched_row = session.query(OverriddenFirstTable).first()
  File "/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1498, in first
    return self._only_one_row(
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 559, in _only_one_row
    row = onerow(hard_close=True)
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1386, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1801, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/lib/python3.11/site-packages/sqlalchemy/sql/type_api.py", line 1721, in process
    return process_value(value, dialect)
  File "/app.py", line 15, in process_result_value
    raise ValueError("CustomType result processing raised an exception for value: {}".format(value))
ValueError: CustomType result processing raised an exception for value: 42

``` 

### Additional context
I have only tested this on a postgres DB, but it could possibly be a problem with other engines too.

The above example is just a reproduction of a problem we're having with Celery Task table.
Celery Task's has a column result defined as

**Comment by zzzeek** [comment]
in all SQLAlchemy versions including 1.3, your code emits a warning that what you're doing is not correct, here is 1.3:

```
/home/classic/tmp/sqlalchemy/lib/sqlalchemy/orm/mapper.py:1899: SAWarning: Implicitly combining column test_table.custom_column with column test_table.custom_column under attribute 'custom_column'.  Please configure one or more attributes for these same-named columns explicitly.
  util.warn(msg)
```

your column is not overridden in the mapping, they are **added together**:

```

# all SQLAlchemy versions
>>> print(OverriddenFirstTable.custom_column.property.columns)
[Column('custom_column', Integer(), table=<test_table>), Column('custom_column', CustomType(), table=<test_table>)]
```



version 1.4 and above is correctly querying *both* columns which is why you see your type taking effect:

```sql
-- note custom_column is twice
SELECT test_table.id AS test_table_id, test_table.custom_column AS test_table_custom_column, test_table.custom_column AS test_table_custom_column_1 
FROM test_table
 LIMIT ? OFFSET ?

```


this pattern is not supported and has never been expected so no bug here.l

**Comment by zzzeek** [comment]
since you gave a thumbs up, here's how you can use core table args without sending messages to declarative

```
class OverriddenFirstTable(FirstTable):
    __tablename__ = 'test_table'
    __table_args__ = (
        Column('custom_column', Integer),
        {'extend_existing': True}
    )

```

**Comment by GuilhermeReda** [comment]
Thank you for your response.

Passing the new column type to the `__table_args__` excludes it from my select. Not sure if I missed something.

```python


# extend the first table, overriding the custom_column type
class OverriddenFirstTable(FirstTable):
    __tablename__ = 'test_table'
    __table_args__ = (
        Column('custom_column', Integer),
        {'extend_existing': True},
    )


if __name__ == '__main__':
    # Create tables in the database
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    row = session.add(OverriddenFirstTable(custom_column=42))
    session.flush()
    fetched_row = session.query(OverriddenFirstTable).first()
    print(f"sql: {str(session.query(OverriddenFirstTable))}")
    print(f"custom_column: {fetched_row.custom_column}")

```

Prints the following:

```
sql: SELECT test_table.id AS test_table_id FROM test_table
custom_column: None
```

**Comment by zzzeek** [comment]
no, the fact that the column is replaced is causing it to not take effect for the original mapping.

What you are trying to do is not supported right now.  you would need to define this column in the way you want up front and it cannot change on a per-declarative mapping basis.  You would need to write some other kind of accessor here.

**Comment by GuilhermeReda** [comment]
That's what I thought.
Thanks for your help.

**Comment by zzzeek** [comment]
here is a way to access the column but it is named differently

```py
class FirstTable(Base):
    __tablename__ = 'test_table'

    id = Column(Integer, primary_key=True)
    # this field will always raise an exception when queried
    custom_column = Column(CustomType)

class OverriddenFirstTable(FirstTable):

    custom_column = deferred(FirstTable.custom_column)

    new_custom_column = column_property(type_coerce(FirstTable.custom_column, Integer))


if __name__ == '__main__':
    # Create tables in the database
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    row = session.add(OverriddenFirstTable(custom_column=42))
    fetched_row = session.query(OverriddenFirstTable).first()
    print(f"custom_column value: {fetched_row.new_custom_column}")

```
