### ISSUE TITLE
Import-time caching can cause problems with pytest and Coverage.py

### ISSUE THREAD

**Issue by inglesp** [sqlalchemy/sqlalchemy#10748]
### Describe the bug

There's a nasty interaction between the following:

* some import-time caching in SQLAlchemy (in [`sqlalchemy.inspection._registrars`](https://github.com/sqlalchemy/sqlalchemy/blob/66be1482db06adb908432b2e3b41d9393d1319f7/lib/sqlalchemy/inspection.py#L53)),
* the way Coverage.py handles editable installs, and
* the way pytest handles warnings.

I've put together [a small repo](https://github.com/inglesp/pytest-warnings-coverage-sqlalchemy) to demonstrate the problem.

I'll submit a PR proposing a fix.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

n/a

### Database Vendor and Major Version

n/a

### Python Version

3.11

### Operating system

n/a

### To Reproduce

```python
See https://github.com/inglesp/pytest-warnings-coverage-sqlalchemy
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/orm/__init__.py", line 21, in <module>
    from . import mapper as mapperlib
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 47, in <module>
    from . import attributes
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 39, in <module>
    from . import collections
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/orm/collections.py", line 128, in <module>
    from .base import NO_KEY
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/orm/base.py", line 432, in <module>
    @inspection._inspects(object)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inglesp/tmp/pytest-warnings-coverage-sqlalchemy/.venv-2/lib/python3.11/site-packages/sqlalchemy/inspection.py", line 165, in decorate
    raise AssertionError(
AssertionError: Type <class 'object'> is already registered
```

**Comment by CaselIT** [comment]
Hi,

Looking at the description in the repo you linked, I think the bug is the coverage package.
SQLAlchemy is not doing anything strange here, it's just setting up a module level cache. That's a very common pattern in python.

**Comment by inglesp** [comment]
>  SQLAlchemy is not doing anything strange here, it's just setting up a module level cache. That's a very common pattern in python.

Agree.

> I think the bug is the coverage package.

You might be right -- but I don't think that it's likely that it's a bug that's fixable without significant changes to the behaviour of the coverage packet.

> I don't think the solution here is to remove the assertion error

Agree.

In https://github.com/sqlalchemy/sqlalchemy/commit/99a571ae6e6cf4ba2eac2c809cb580736126c390, I've tightened the condition guarding the assert, so that it only fires if the key is present and a different object is being added to the cache.  All tests pass when I run `tox`.

I haven't yet had the chance to put together a new test, but could do so if the maintainers indicated they would be willing to consider the patch.

**Comment by CaselIT** [comment]
Thanks for looking into it. If that additional check makes it work I think it would be fine.

I'm not sure if there is a place where that function is explicitly tested, but maybe we could add a test here: https://github.com/sqlalchemy/sqlalchemy/blob/main/test/base/test_misc_py3k.py It should be easy to move if we find a better spot. Just be sure to either mock the registry or clean it up after the test.

**Comment by zzzeek** [comment]
I have changed the title to make this more general, because originally when it was coverage.py, it didnt seem like our problem.

The general idea of unloading and reloading a module is not unheard of so I tend to agree that we shouldn't put up large roadblocks to that.     The assert that we have here can possibly check the incoming contents and compare things like function name, `__module__` to determine this was a reload.

**Comment by zzzeek** [comment]
```py
>>> import sys
>>> import sqlalchemy.exc
>>> old_modules = set(sys.modules)
>>> import sqlalchemy.orm
>>> new_modules = set(sys.modules) - old_modules
>>> for m in new_modules: del sys.modules[m]
... 
>>> import sqlalchemy.orm

```

**Comment by CaselIT** [comment]
seems that an `==` is working on the fn to fix the issue. That should be ok

**Comment by zzzeek** [comment]
this is how I would do this:

```diff
diff --git a/lib/sqlalchemy/inspection.py b/lib/sqlalchemy/inspection.py
index 1fe37d925..aef2cab9c 100644
--- a/lib/sqlalchemy/inspection.py
+++ b/lib/sqlalchemy/inspection.py
@@ -162,9 +162,17 @@ def _inspects(
     def decorate(fn_or_cls: _F) -> _F:
         for type_ in types:
             if type_ in _registrars:
-                raise AssertionError(
-                    "Type %s is already " "registered" % type_
-                )
+                existing = _registrars[type_]
+
+                # see if this is a new version of the same fn or class,
+                # that is, a module reload
+                if (
+                    existing.__name__ != fn_or_cls.__name__
+                    or existing.__module__ != fn_or_cls.__module__
+                ):
+                    raise AssertionError(
+                        f"Type {type_} is already registered to {fn_or_cls}"
+                    )
             _registrars[type_] = fn_or_cls
         return fn_or_cls
 

```

**Comment by CaselIT** [comment]
wouldn't a equality check be better? On either fn or cls it should check if they are the same object.

**Comment by zzzeek** [comment]
> wouldn't a equality check be better? On either fn or cls it should check if they are the same object.

eq checks for classes have always felt wrong, I vaguely recall code linters might not like it either.   A metaclass that overriddes `__eq__()` can provide for alternate behaviors and we really want to see "this is the same name from the same module".

**Comment by CaselIT** [comment]
shame that there does not seem to be a `__code__` equivalent for classes

**Comment by sqla-tester** [comment]
**w-Jessamine** has proposed a fix for this issue in the **main** branch:

**Allow inspection registrations from module reloads** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6787
