### ISSUE TITLE
bundle is not supported in returning

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10776]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10774

<div type='discussions-op-text'>

<sup>Originally posted by **myrix** December 19, 2023</sup>
Unlike when querying, bundles in the `.returning()` clauses of updates are not bundled into tuples.

Test case:
```python

import sqlalchemy
from sqlalchemy import Column, create_engine, insert, select, update
import sqlalchemy.orm as orm
from sqlalchemy.types import Integer

#
# Set up.
#

engine = create_engine('postgresql+psycopg2://postgres@/postgres')

c = engine.connect()
c = c.execution_options(autocommit = False)
c.exec_driver_sql('ROLLBACK')

try:
    c.exec_driver_sql('CREATE DATABASE test_bundle')
except:
    c.exec_driver_sql('ROLLBACK')
else:
    c.exec_driver_sql('COMMIT')

c.close()
engine.dispose()

Base = orm.declarative_base()

class R1(Base):

    __tablename__ = 'r1'

    k1 = Column(Integer, primary_key = True)
    k2 = Column(Integer, primary_key = True)

    a = Column(Integer)
    b = Column(Integer)

class R2(Base):

    __tablename__ = 'r2'

    __table_args__ = (
        sqlalchemy.ForeignKeyConstraint(
            ['k1', 'k2'],
            ['r1.k1', 'r1.k2']),)

    k1 = Column(Integer, primary_key = True)
    k2 = Column(Integer, primary_key = True)

    c = Column(Integer)

engine = create_engine('postgresql+psycopg2://postgres@/test_bundle')

Base.metadata.drop_all(bind = engine)
Base.metadata.create_all(bind = engine)

session = orm.scoped_session(orm.sessionmaker())
session.configure(bind = engine)

session.execute(R1.__table__.insert().values((1, 2, 3, 4)))
session.execute(R2.__table__.insert().values((1, 2, 5)))

session.commit()

#
# Test case, expecting:
#
# [((1, 2), 3)]
# [(1, 2, 3)]
# [((1, 2), 3)]
# [(1, 2, 3)]
# [((1, 2), 3)]
# [(1, 2, 3)]
#

k_bundle = orm.Bundle('k_bundle', R1.k1, R1.k2)

print(list(
    session.execute(
        select(k_bundle, R1.a)
            .where(R1.b == 4))))

print(list(
    session.execute(
        select(R1.k1, R1.k2, R1.a)
            .where(R1.b == 4))))

print(list(
    session.execute(
        R2.__table__.update()
            .where(R1.b == 4, R2.k1 == R1.k1, R2.k2 == R1.k2)
            .values(c = 5)
            .returning(k_bundle, R1.a))))

print(list(
    session.execute(
        R2.__table__.update()
            .where(R1.b == 4, R2.k1 == R1.k1, R2.k2 == R1.k2)
            .values(c = 5)
            .returning(R1.k1, R1.k2, R1.a))))

print(list(
    session.execute(
        update(R2)
            .where(R1.b == 4, R2.k1 == R1.k1, R2.k2 == R1.k2)
            .values(c = 5)
            .returning(k_bundle, R1.a)
            .execution_options(synchronize_session = False))))

print(list(
    session.execute(
        update(R2)
            .where(R1.b == 4, R2.k1 == R1.k1, R2.k2 == R1.k2)
            .values(c = 5)
            .returning(R1.k1, R1.k2, R1.a)
            .execution_options(synchronize_session = False))))
```

Expected output:
```
[((1, 2), 3)]
[(1, 2, 3)]
[((1, 2), 3)]
[(1, 2, 3)]
[((1, 2), 3)]
[(1, 2, 3)]
```

Output with SQLAlchemy 1.4.50:
```
[((1, 2), 3)]
[(1, 2, 3)]
[(1, 2, 3)]
[(1, 2, 3)]
[(1, 2, 3)]
[(1, 2, 3)]
```

Output with SQLAlchemy 2.0.23 (just in case, yeah, I know it's bad practice to do things under the root):
```
[((1, 2), 3)]
[(1, 2, 3)]
[(1, 2, 3)]
[(1, 2, 3)]
Traceback (most recent call last):
  File "test_bundle.py", line 104, in <module>
    session.execute(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 782, in execute
    return self._proxied.execute(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1617, in orm_execute_statement
    return super().orm_execute_statement(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 704, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/annotation.py", line 351, in _compiler_dispatch
    return self.__element.__class__._compiler_dispatch(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 5994, in visit_update
    compile_state = update_stmt._compile_state_factory(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 687, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1415, in create_for_statement
    self._setup_for_orm_update(statement, compiler)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1504, in _setup_for_orm_update
    new_stmt = self._setup_orm_returning(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 534, in _setup_orm_returning
    fsc.setup_dml_returning_compile_state(dml_mapper)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 857, in setup_dml_returning_compile_state
    entity.setup_dml_returning_compile_state(self, adapter)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2512, in setup_dml_returning_compile_state
    raise NotImplementedError()
NotImplementedError
```

The last example,
```
print(list(
    session.execute(
        update(R2)
            .where(R1.b == 4, R2.k1 == R1.k1, R2.k2 == R1.k2)
            .values(c = 5)
            .returning(R1.k1, R1.k2, R1.a)
            .execution_options(synchronize_session = False))))
```
gives with SQLAlchemy 2.0.23 following exception:
```
Traceback (most recent call last):
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 843, in _index_for_key
    rec = self._keymap[key]
KeyError: Column('k1', Integer(), table=<r1>, primary_key=True, nullable=False)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_bundle.py", line 112, in <module>
    session.execute(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 782, in execute
    return self._proxied.execute(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1617, in orm_execute_statement
    return super().orm_execute_statement(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 296, in orm_execute_statement
    return cls.orm_setup_cursor_result(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 786, in orm_setup_cursor_result
    return cls._return_orm_returning(
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/bulk_persistence.py", line 599, in _return_orm_returning
    return loading.instances(result, querycontext)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 133, in instances
    cursor.close()
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 113, in instances
    *[
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 114, in <listcomp>
    query_entity.row_processor(context, cursor)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2986, in row_processor
    getter = result._getter(column)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1184, in _getter
    return self._metadata._getter(key, raiseerr)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 172, in _getter
    index = self._index_for_key(key, raiseerr)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 845, in _index_for_key
    x = self._key_fallback(key, ke, raiseerr)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 823, in _key_fallback
    raise exc.NoSuchColumnError(
sqlalchemy.exc.NoSuchColumnError: Could not locate column in row for column 'r1.k1'
```</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure Bundle / DML RETURNING has test support, full impl** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5019

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**ensure Bundle / DML RETURNING has test support, full impl** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5020
