### ISSUE TITLE
Error when adding model with datetime and UUID

### ISSUE THREAD

**Issue by KyloEntro** [sqlalchemy/sqlalchemy#10787]
### Describe the bug

In my code, I have 3 models which are linked.

By executing the script in `To Reproduce` part, I have an error when I call `session.commit()`. But if I delete the `TimestampMixin`, I don't have the issue. It is like it is not possible to have `UUID` and Timestamp column in the same model.
But if I change the `TimestampMixin` by 
```python

class TimestampMixin:
    added = sa.Column(
        "added",
        sa.DateTime,
        nullable=False,
        index=True,
        default=datetime.datetime.now(),
        # server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc')"),  <- DO NOT USE THIS METHOD, REPLACED BY default
    )
    updated = sa.Column(
        "updated",
        sa.DateTime,
        nullable=False,
        index=True,
        default=datetime.datetime.now(),
        # server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc')"),  <- DO NOT USE THIS METHOD, REPLACED BY default
        onupdate=sa.sql.func.timezone("utc", sa.sql.functions.now()),
    )

```

I don't have the issue ... 

Is `server_default` the root cause? 

### SQLAlchemy Version in Use

2.0.33

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 11

### Python Version

3.8.17

### Operating system

OSX, Linux

### To Reproduce

```python
import uuid
import datetime

import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, declarative_base, sessionmaker
from sqlalchemy_utils import UUIDType


engine = create_engine("postgresql://root:root@localhost/test_lji")

Base = declarative_base()


class TimestampMixin:
    added = sa.Column(
        "added",
        sa.DateTime,
        nullable=False,
        index=True,
        # default=datetime.datetime.now(),
        server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc')"),
    )
    updated = sa.Column(
        "updated",
        sa.DateTime,
        nullable=False,
        index=True,
        # default=datetime.datetime.now(),
        server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc')"),
        onupdate=sa.sql.func.timezone("utc", sa.sql.functions.now()),
    )


class ClassA(Base, TimestampMixin):
    __tablename__ = "classA"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    instancesB = sa.orm.relationship("ClassB", back_populates="instanceA")


class ClassB(Base, TimestampMixin):
    __tablename__ = "classB"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    id_instanceA = sa.Column(
        sa.Integer,
        sa.ForeignKey("classA.id"),
        nullable=True,
        index=True,
    )
    instanceC_ref = sa.Column(
        UUIDType,
        sa.ForeignKey("classC.ref"),
        nullable=True,
        index=True,
    )
    instanceA = sa.orm.relationship("ClassA", back_populates="instancesB")
    instanceC = sa.orm.relationship("ClassC", back_populates="instancesB")


class ClassC(Base, TimestampMixin):
    __tablename__ = "classC"

    ref = sa.Column(UUIDType, primary_key=True, default=uuid.uuid4)

    instancesB = sa.orm.relationship("ClassB", back_populates="instanceC")


######################


Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

a1 = ClassA()

b1 = ClassB()
b2 = ClassB()
b3 = ClassB()

c1 = ClassC()
c2 = ClassC()

b1.instanceC = c1
b2.instanceC = c2

b1.remittance = a1

session.add_all([b1, b2, b3])
session.commit()
```

### Error

```
Traceback (most recent call last):
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 890, in _deliver_insertmanyvalues_batches
    ordered_rows = [
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 891, in <listcomp>
    rows_by_sentinel[
KeyError: '0ca7ff14-2c23-4fb2-894e-4d40e5a769f7'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lji/PycharmProjects/test_sqlalchemy/main.py", line 93, in <module>
    session.commit()
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = connection.execute(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2030, in _exec_insertmany_context
    for imv_batch in dialect._deliver_insertmanyvalues_batches(
  File "/Users/lji/PycharmProjects/test_sqlalchemy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 900, in _deliver_insertmanyvalues_batches
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't match sentinel values in result set to parameter sets; key '0ca7ff14-2c23-4fb2-894e-4d40e5a769f7' was not found. There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row.  Ensure the given Python value matches the expected result type *exactly*, taking care to not rely upon implicit conversions which may occur such as when using strings in place of UUID or integer values, etc. 

``` 

### Additional context

This code runs well with `SQLAlchemy 1.4.x`, I discovered this problem when upgraing SQLAlchemy to 2.x.x

**Comment by KyloEntro** [comment]
Looks similar to: https://github.com/sqlalchemy/sqlalchemy/issues/9822

**Comment by CaselIT** [comment]
Hi,

This issue here seems to be the uuid type you are using.. please retry with the internal version

**Comment by KyloEntro** [comment]
Hi, thank you for your answer
When you said internal version, do you mean python version ? 

from uuid import UUID ?

**Comment by CaselIT** [comment]
No, you need to use db types, not python ones as column types.
I meant the sqlalchemy provided ones either from the postgresql dialect or in v2 the common one:
- https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Uuid
- https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.TSVECTOR (just below this one)

**Comment by KyloEntro** [comment]
Thank you, it works :)
