### ISSUE TITLE
`typing.TypeAliasType` object has no attribute `__mro__`

### ISSUE THREAD

**Issue by rijenkii** [sqlalchemy/sqlalchemy#10807]
### Describe the bug

When trying to pass PEP 695 type alias as a type parameter in `Mapped`, script crashes at runtime.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.12

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

from typing import Any
from typing import ClassVar
from typing import Literal
from typing import TypedDict

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import MappedAsDataclass
from sqlalchemy.orm import mapped_column
from sqlalchemy.types import JSON


class _Union1(TypedDict):
    type: Literal["1"]


class _Union2(TypedDict):
    type: Literal["2"]


type _Union = _Union1 | _Union2


class Base(MappedAsDataclass, DeclarativeBase):
    type_annotation_map: ClassVar[Any] = {_Union: JSON}


class Test(Base):
    __tablename__ = "test"
    id: Mapped[int] = mapped_column(primary_key=True)
    structure: Mapped[_Union]
```

### Error

```
Traceback (most recent call last):
  File "/tmp/test.py", line 30, in <module>
    class Test(Base):
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_api.py", line 625, in __init_subclass__
    super().__init_subclass__()
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_api.py", line 847, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 574, in __init__
    self._extract_mappable_attributes()
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 1544, in _extract_mappable_attributes
    value.declarative_scan(
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/properties.py", line 707, in declarative_scan
    self._init_column_for_annotation(
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/properties.py", line 859, in _init_column_for_annotation
    new_sqltype = registry._resolve_type(check_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rijenkii/.local/share/hatch/env/virtual/atrocity/PL8lPIKK/atrocity/lib64/python3.12/site-packages/sqlalchemy/orm/decl_api.py", line 1268, in _resolve_type
    search = ((pt, pt) for pt in python_type_type.__mro__)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'typing.TypeAliasType' object has no attribute '__mro__'. Did you mean: '__or__'?
``` 

### Additional context

After replacing `type _Union` with regular `_Union`, script runs without exceptions.

**Comment by CaselIT** [comment]
Hi,

Not sure why this is also a discussion. Please avoid opening duplicates...

Honestly it seems that `type x = ` is completely broken compared to the rest of typing.
```py
import typing as T
type x=int|str
print(T.get_origin(x))
print(T.get_args(x))
```

it seems that the alias is store in the `__value__` attribute but there is no way of getting that using one of the other method. I really don't understand why every time python dev add something to typing they have to reinvent the wheel every time...

**Comment by rijenkii** [comment]
&lt;offtopic&gt;
> Not sure why this is also a discussion. Please avoid opening duplicates...

I've opened a discussion because I've thought that I'm doing something wrong, then as you were answering in that discussion I have concluded that this is indeed a bug, closed the discussion and opened this ticket.

&lt;/offtopic&gt;

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**support pep695 when resolving type map types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5048

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**support pep695 when resolving type map types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5049
