### ISSUE TITLE
deprecate and remove ancient "objects" parameter on session.flush()

### ISSUE THREAD

**Issue by sekrause** [sqlalchemy/sqlalchemy#10816]
### Describe the bug

In SQLAlchemy >= 2.0.19 a query-invoked autoflush might try to create a row which has already been created by a manual flush, triggering a `psycopg2.errors.UniqueViolation`.

My test script works just fine up to SQLAlchemy 2.0.18, but raises the exception in 2.0.19 and later. As you can see in the SQL log output the `INSERT INTO roles_users` is called twice.

Flushing the whole session instead of just the two objects fixes the problem, but since it worked up to 2.0.18 it might be an unintended regression.

### SQLAlchemy Version in Use

2.0.24

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import Column, Integer, Table, ForeignKey, create_engine, select
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import declarative_base

Base = declarative_base()

roles_users = Table(
    "roles_users",
    Base.metadata,
    Column("user_id", Integer, ForeignKey("users.id"), primary_key=True),
    Column("role_id", Integer, ForeignKey("roles.id"), primary_key=True),
)


class User(Base):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(primary_key=True)
    roles: Mapped[list["Role"]] = relationship(
        "Role", secondary=roles_users, back_populates="users"
    )


class Role(Base):
    __tablename__ = "roles"
    id: Mapped[int] = mapped_column(primary_key=True)
    users: Mapped[list["User"]] = relationship(
        "User", secondary=roles_users, back_populates="roles"
    )

engine = create_engine("postgresql+psycopg2://localhost/bugtest", echo=True)
Base.metadata.create_all(engine)

with Session(engine) as session:
    role = Role(id=1)
    session.add(role)
    session.flush([role])

    user = User(id=1)
    user.roles.append(role)
    session.add(user)
    session.flush([user])

    # Triggers psycopg2.errors.UniqueViolation from query-invoked autoflush
    session.execute(select(User)).all()

    session.rollback()
```

### Error

```
INFO sqlalchemy.engine.Engine select pg_catalog.version()
INFO sqlalchemy.engine.Engine [raw sql] {}
INFO sqlalchemy.engine.Engine select current_schema()
INFO sqlalchemy.engine.Engine [raw sql] {}
INFO sqlalchemy.engine.Engine show standard_conforming_strings
INFO sqlalchemy.engine.Engine [raw sql] {}
INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
 JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
s.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO sqlalchemy.engine.Engine [generated in 0.00047s] {'table_name': 'roles_users', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
 JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
s.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO sqlalchemy.engine.Engine [cached since 0.003659s ago] {'table_name': 'users', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
 JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
s.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO sqlalchemy.engine.Engine [cached since 0.005058s ago] {'table_name': 'roles', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
INFO sqlalchemy.engine.Engine COMMIT
INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO sqlalchemy.engine.Engine INSERT INTO roles (id) VALUES (%(id)s)
INFO sqlalchemy.engine.Engine [generated in 0.00038s] {'id': 1}
INFO sqlalchemy.engine.Engine INSERT INTO users (id) VALUES (%(id)s)
INFO sqlalchemy.engine.Engine [generated in 0.00038s] {'id': 1}
INFO sqlalchemy.engine.Engine INSERT INTO roles_users (user_id, role_id) VALUES (%(user_id)s, %(role_id)s)
INFO sqlalchemy.engine.Engine [generated in 0.00031s] {'user_id': 1, 'role_id': 1}
INFO sqlalchemy.engine.Engine INSERT INTO roles_users (user_id, role_id) VALUES (%(user_id)s, %(role_id)s)
INFO sqlalchemy.engine.Engine [cached since 0.004401s ago] {'user_id': 1, 'role_id': 1}
INFO sqlalchemy.engine.Engine ROLLBACK

Traceback (most recent call last):
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "venv\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "roles_users_pkey"
DETAIL:  Key (user_id, role_id)=(1, 1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bugtest.py", line 47, in <module>
    session.execute(select(User)).all()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2169, in _execute_internal
    ) = compile_state_cls.orm_pre_session_exec(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\orm\context.py", line 551, in orm_pre_session_exec
    session._autoflush()
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3021, in _autoflush
    raise e.with_traceback(sys.exc_info()[2])
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3010, in _autoflush
    self.flush()
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4312, in flush
    self._flush(objects)
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4447, in _flush
    with util.safe_reraise():
  File "venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4408, in _flush
    flush_context.execute()
  File "venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 591, in execute
    self.dependency_processor.process_saves(uow, states)
  File "venv\Lib\site-packages\sqlalchemy\orm\dependency.py", line 1195, in process_saves
    self._run_crud(
  File "venv\Lib\site-packages\sqlalchemy\orm\dependency.py", line 1258, in _run_crud
    connection.execute(statement, secondary_insert)
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "venv\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "roles_users_pkey"
DETAIL:  Key (user_id, role_id)=(1, 1) already exists.

[SQL: INSERT INTO roles_users (user_id, role_id) VALUES (%(user_id)s, %(role_id)s)]
[parameters: {'user_id': 1, 'role_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by zzzeek** [comment]
hi - 

please don't use this parameter, it's not supported.    We will remove it in SQLAlchemy 2.2.

**Comment by zzzeek** [comment]
law of twos with #10869

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Deprecate objects param of flush** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5678

**Comment by CaselIT** [comment]
Why you have many objects to flush in the session?
Also since they need to be flushed, I don't see how `session.flush([user])` solves the performance problem, since the session will need to flush the other objects too
