### ISSUE TITLE
Extending lambda statements with non-lambda expressions creates bad bind parameters

### ISSUE THREAD

**Issue by lonvia** [sqlalchemy/sqlalchemy#10827]
### Describe the bug

When a lambda statement is extended with a non-lambda statement, the bind parameters derived from closure variables have the wrong value. The extended statement uses the bind parameter from the cached lambda expression including its value instead of replacing it with the value from the current call.

For a simple executable example explaining the issue, please see #10819.

### SQLAlchemy Version in Use

1.4.46, 2.0.24

### DBAPI (i.e. the database driver)

all

### Database Vendor and Major Version

all

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
def test_stmt_lambda_w_additional_non_lambda_and_closure_var(self):
        def go(q):
            stmt = lambdas.lambda_stmt(
                lambda: select(column("x")).where(column("x") == q))
            stmt = stmt.where(column("y") == column("z"))

            return stmt

        s1 = go(5)
        s2 = go(10)

        self.assert_compile(
            s1, "SELECT x WHERE x = :q_1 AND y = z", checkparams={"q_1": 5}
        )
        self.assert_compile(
            s2, "SELECT x WHERE x = :q_1 AND y = z", checkparams={"q_1": 10}
        )

        s1key = s1._generate_cache_key()
        s2key = s2._generate_cache_key()

        eq_(s1key[0], s2key[0])
```

### Error

The above test is a slight variation of [test_stmt_lambda_w_additional_hascachekey_variants](https://github.com/sqlalchemy/sqlalchemy/blob/4871a2f72f5f0e514fe81a8caa17a14f9fc51300/test/sql/test_lambdas.py#L312) and when dropped into `test/sql/test_lambdas.py`, it fails with a bad value for `q`:

```
me@machine:~/dev/src/sqlalchemy$ python3 -m pytest test/sql/test_lambdas.py -k test_stmt_lambda_w_additional_non_lambda_and_closure_var
===================================================================================== sqlalchemy installation ======================================================================================
SQLAlchemy 2.1.0b1 (user site loaded)
Path: /home/suzuki/dev/src/sqlalchemy/lib/sqlalchemy/__init__.py
compiled extension not enabled; cannot import name 'collections' from 'sqlalchemy.cyextension' (/home/suzuki/dev/src/sqlalchemy/lib/sqlalchemy/cyextension/__init__.py)
======================================================================================= test session starts ========================================================================================
platform linux -- Python 3.11.2, pytest-7.2.1, pluggy-1.0.0+repack -- /home/suzuki/dev/src/sqlalchemy/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/suzuki/dev/src/sqlalchemy, configfile: pyproject.toml
plugins: cov-4.0.0, httpserver-1.0.6, anyio-3.6.2, asyncio-0.20.3
asyncio: mode=Mode.STRICT
collected 92 items / 91 deselected / 1 selected                                                                                                                                                    

test/sql/test_lambdas.py::LambdaElementTest::test_stmt_lambda_w_additional_non_lambda_and_closure_var FAILED                                                                                 [100%]

============================================================================================= FAILURES =============================================================================================
____________________________________________________________ LambdaElementTest.test_stmt_lambda_w_additional_non_lambda_and_closure_var ____________________________________________________________
Traceback (most recent call last):
  File "/home/suzuki/dev/src/sqlalchemy/test/sql/test_lambdas.py", line 363, in test_stmt_lambda_w_additional_non_lambda_and_closure_var
    self.assert_compile(
  File "/home/suzuki/dev/src/sqlalchemy/lib/sqlalchemy/testing/assertions.py", line 674, in assert_compile
    eq_(c.construct_params(params), checkparams)
  File "/home/suzuki/dev/src/sqlalchemy/lib/sqlalchemy/testing/assertions.py", line 283, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: {'q_1': 5} != {'q_1': 10}
assert {'q_1': 5} == {'q_1': 10}
  Differing items:
  {'q_1': 5} != {'q_1': 10}
  Full diff:
  - {'q_1': 10}
  ?         ^^
  + {'q_1': 5}
  ?         ^
--------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------
b"\nSQL String:\nSELECT x \nWHERE x = :q_1 AND y = z{'q_1': 5}"
b"\nSQL String:\nSELECT x \nWHERE x = :q_1 AND y = z{'q_1': 5}"
===================================================================================== short test summary info ======================================================================================
FAILED test/sql/test_lambdas.py::LambdaElementTest::test_stmt_lambda_w_additional_non_lambda_and_closure_var - AssertionError: {'q_1': 5} != {'q_1': 10}
================================================================================= 1 failed, 91 deselected in 0.05s =================================================================================
```

**Comment by sqla-tester** [comment]
**cjc0013** has proposed a fix for this issue in the **main** branch:

**Fix lambda statements with non-lambda criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6707

**Comment by sqla-tester** [comment]
**cjc0013** has proposed a fix for this issue in the **main** branch:

**Fix lambda statements with non-lambda criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6707

**Comment by sqla-tester** [comment]
**cjc0013** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix lambda statements with non-lambda criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6711
