### ISSUE TITLE
Query with enable_eagerloads(False) and yield_per() raises InvalidRequestError

### ISSUE THREAD

**Issue by james-emerton** [sqlalchemy/sqlalchemy#10834]
### Describe the bug

(Legacy) queries against a mapper with an eagerly loaded relation using `yield_per(n)` will fail with an `InvalidRequestError` because the result requires `unique()` to be called. According to the [documentation](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query.enable_eagerloads) using `enable_eagerloads(False)` should disable eager loads and allow `yield_per()` to function correctly. Unfortunately, the exception is still raised in this case.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query.enable_eagerloads

### SQLAlchemy Version in Use

main

### DBAPI (i.e. the database driver)

psycopg2, pysqlite

### Database Vendor and Major Version

postgres 14, sqlite

### Python Version

3.11

### Operating system

Windows, OSX

### To Reproduce

```python
from sqlalchemy import create_engine, Column, Integer, String, ForeignKey
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

engine = create_engine('sqlite://')
Session = sessionmaker(bind=engine)

Base = declarative_base()


class JoinedParent(Base):
    __tablename__ = 'relationship_eager_parent'

    id = Column(Integer, primary_key=True)
    text = Column(String)

    children = relationship('JoinedChild', backref='parent',
                            order_by='JoinedChild.id',
                            lazy='joined')


class JoinedChild(Base):
    __tablename__ = 'relationship_eager_child'

    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('relationship_eager_parent.id'))
    text = Column(String)


Base.metadata.create_all(engine)


session = Session()
for rec in session.query(JoinedParent).enable_eagerloads(False).yield_per(10):
    pass
```

### Error

```
Traceback (most recent call last):
  File "/Users/james/dev/spire/sqlalchemy/test.py", line 34, in <module>
    for rec in session.query(JoinedParent).enable_eagerloads(False).yield_per(10):
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2840, in __iter__
    result = self._iter()
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2854, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/context.py", line 296, in orm_execute_statement
    return cls.orm_setup_cursor_result(
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/context.py", line 589, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 133, in instances
    cursor.close()
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/james/dev/spire/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 124, in instances
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't use yield_per with eager loaders that require uniquing or row buffering, e.g. joinedload() against collections or subqueryload().  Consider the selectinload() strategy for better flexibility in loading objects.``` 

### Additional context

First discovered in 1.4.50, confirmed against a recent checkout from `main`.

**Comment by zzzeek** [comment]
Hi -

I can fix this for the 2.0 series but 1.4 might not have a release for awhile as it is near EOL.

You can work around this issue by turning off eager loaders directly using `lazyload('*')`:

     session.query(JoinedParent).options(lazyload('*')).yield_per(10):

patch for 2.0 is

```diff
diff --git a/lib/sqlalchemy/orm/strategies.py b/lib/sqlalchemy/orm/strategies.py
index d7671e079..c6fb0ffc6 100644
--- a/lib/sqlalchemy/orm/strategies.py
+++ b/lib/sqlalchemy/orm/strategies.py
@@ -2675,6 +2675,11 @@ class JoinedLoader(AbstractRelationshipLoader):
         adapter,
         populators,
     ):
+
+        if (
+            not context.compile_state.compile_options._enable_eagerloads):
+            return
+
         if not self.parent.class_manager[self.key].impl.supports_population:
             raise sa_exc.InvalidRequestError(
                 "'%s' does not support object "

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**skip joined eager row processor for enable_eagerloads=False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5433

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**skip joined eager row processor for enable_eagerloads=False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5434
