### ISSUE TITLE
connection_lost for asyncpg now leaves idle connections open

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10863]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10862

<div type='discussions-op-text'>

<sup>Originally posted by **chamini2** January 10, 2024</sup>
https://github.com/sqlalchemy/sqlalchemy/commit/e70a0b0a0e52945e5b588b5cffec619a3f3e78a1 introduced a change where we would start seeing this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 377, in _close_connection
    self._dialect.do_terminate(connection)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1109, in do_terminate
    dbapi_connection.terminate()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 892, in terminate
    self.await_(self._connection.close(timeout=2))
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 130, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 195, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1467, in close
    await self._protocol.close(timeout)
  File "asyncpg/protocol/protocol.pyx", line 618, in close
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1584, in _cancel
    await connect_utils._cancel(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1040, in _cancel
    tr, pr = await _create_ssl_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 752, in _create_ssl_connection
    do_ssl_upgrade = await pr.on_data
                     ^^^^^^^^^^^^^^^^
ConnectionError: unexpected connection_lost() call
```

and that left connections open but idle, which would eventually make the PostgreSQL database reject connections becuase max was reached.

I think maybe the `terminate` could be called for any exception, not just time out:
https://github.com/sqlalchemy/sqlalchemy/blob/e70a0b0a0e52945e5b588b5cffec619a3f3e78a1/lib/sqlalchemy/dialects/postgresql/asyncpg.py#L952-L958

*****

Stuff from issue creation, but did not have a reproducible example:

sqlalchemy 2.0.25
PostgreSQL 14.9
Python 3.11
Linux
</div>

**Comment by zzzeek** [comment]
I guess you mean it would catch any exception.   it certainly should

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**catch OSError (base of ConnectionError) and asyncpg errors for terminate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5123

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**catch OSError (base of ConnectionError) and asyncpg errors for terminate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5124
