### ISSUE TITLE
OrderingList typing incorrect / incomplete and implementation doesn't accept non-int indices

### ISSUE THREAD

**Issue by mjpieters** [sqlalchemy/sqlalchemy#10888]
### Describe the bug

There are a number of issues with the sqlalchemy.ext.orderinglist:OrderingList type hints and implementation:

1. The ordering function is documented as being allowed to return any type of object, and the tests demonstrate this by returning strings. The type annotation requires it to return integers, only, however.
2. The `OrderingList` signature marks the `ordering_attr` as optional, but accepting `None` here would lead to a type error when `getattr(entity, self.ordering_attr)` is called. 
3. List objects accept any `SupportsIndex` type object, one that implements the [`.__index__()` method](https://docs.python.org/3/reference/datamodel.html#object.__index__). The codebase assumes it is always an integer (`count_from_1()` and `count_from_n_factory()` use addition with the value, which `SupportsIndex` objects don't need to support). It's probably best to use `operator.index()` on the value before passing it to the ordering function.
4. The `ordering_list()` ignores the `_T` type variable in the `OrderingFunc` and `OrderingList` signatures
5. The `OrderingFunc.ordering_func` annotation ignores the `_T` type variable in the `OrderingFunc` signature
6. List objects accept setting values via a slice and any iterable, e.g. `listobj[start:stop] = values_generator()`, but `OrderingList.__setitem__` with a slice object assumes the value is a sequence (supporting indexing), where a list accepts any iterable, plus it doesn't adjust the list length when the slice is being assigned fewer or more elements or handle slices with stride other than 1. This issue is mostly mitigated by the SQLAlchemy collections instrumentation (which wraps `OrderingList.__setitem__` with an implementation that handles slices *almost* correctly, only assuming a sequence when slices with a stride are used). But, there may be situations where `OrderingList` is used without this instrumentation. The internal implementation of `list.__setitem__()` converts the passed-in object to a list first, consuming the iterable; `OrderingList.__setitem__()` should do the same, plus it should handle slice strides.
7. There are no type annotations for the `count_from_*` utility functions or the overridden list methods.

### SQLAlchemy Version in Use

2.0.25

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
# point 2, ordering_attr is not optional

from sqlalchemy.ext.orderinglist import OrderingList
class Item:
    position = None

ol = OrderingList()
ol.append(Item())
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sqlalchemy/lib/sqlalchemy/ext/orderinglist.py", line 339, in append
    self._order_entity(len(self) - 1, entity, self.reorder_on_append)
  File "...//sqlalchemy/lib/sqlalchemy/ext/orderinglist.py", line 327, in _order_entity
    have = self._get_order_value(entity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...//sqlalchemy/lib/sqlalchemy/ext/orderinglist.py", line 308, in _get_order_value
    return getattr(entity, self.ordering_attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'NoneType'
"""

# point 6, slice assigment of iterable items
ol = OrderingList('position')
ol[:] = (Item() for _ in range(3))
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...//sqlalchemy/lib/sqlalchemy/ext/orderinglist.py", line 375, in __setitem__
    self.__setitem__(i, entity[i])
                        ~~~~~~^^^
TypeError: 'generator' object is not subscriptable
"""

# point 6, slice assigment length not matching item length
ol = OrderingList('position')
ol.append(Item())

# assign 1 item to a slice of length 0
ol[:0] = [Item()]
assert len(ol) == 2  # assertion error, length is 1

# assign 0 items to a slice of length 1
ol[:] = []
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sqlalchemy/lib/sqlalchemy/ext/orderinglist.py", line 375, in __setitem__
    self.__setitem__(i, entity[i])
                        ~~~~~~^^^
IndexError: list index out of range
"""
```

### Additional context

I'll be providing a PR that addresses all these issues.

The slice issues are handled by just calling `super().__setitem__(slice, values)` and then `self._reorder()`. It's a cop-out but one that only applies to cases where `OrderedList` is not used as instrumented attribute, which is very much not the common case.

**Comment by zzzeek** [comment]
thanks!

**Comment by CaselIT** [comment]
checked it off from this list https://github.com/sqlalchemy/sqlalchemy/issues/6810

**Comment by sqla-tester** [comment]
**Martijn Pieters** has proposed a fix for this issue in the **main** branch:

**Update orderinglist annotations, list compatibity** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5118
