### ISSUE TITLE
Not able to resolve type annotation defined within the same class

### ISSUE THREAD

**Issue by twiddli** [sqlalchemy/sqlalchemy#10899]
### Describe the bug

Hi, it seems that when `from __future__ import annotations` is in use, it's not possible to use `Mapped[...]` with a type defined within the same mapped class.
The reason why I think this is a bug is because I've understood that sqlalchemy should be able to support forwarded refs.
My proposed fix would be to postpone the extraction, or just evaluation, of type annotations until `Base.metadata.create_all` as is already the case for what makes forwarded mapped class references possible in column definitions.

Thanks!

### SQLAlchemy Version in Use

2.0.25

### DBAPI (i.e. the database driver)

Generic

### Database Vendor and Major Version

Generic

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
from __future__ import annotations

import typing
import enum

import sqlalchemy.orm as sa_orm
from sqlalchemy.orm import Mapped, mapped_column


class Base(sa_orm.DeclarativeBase):
    ...

class User(Base):
    __tablename__ = 'user'

    class Role(enum.Enum):
        admin = 'admin'
        user = 'user'

    id: Mapped[int] =  mapped_column(primary_key=True)
    role: Mapped[Role] = mapped_column(nullable=False, default=Role.user)
    # None of these work either:
    # role: Mapped['Role'] = mapped_column(nullable=False, default=Role.user)
    # role: Mapped['User.Role'] = mapped_column(nullable=False, default=Role.user)
```

### Error

```
Traceback (most recent call last):
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\util\typing.py", line 222, in eval_expression
    annotation = eval(expression, base_globals, locals_)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Role' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 1544, in _extract_mappable_attributes
    value.declarative_scan(
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\properties.py", line 707, in declarative_scan
    self._init_column_for_annotation(
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\properties.py", line 743, in _init_column_for_annotation
    argument = de_stringify_annotation(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\util\typing.py", line 158, in de_stringify_annotation
    annotation = eval_expression(
                 ^^^^^^^^^^^^^^^^
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\util\typing.py", line 224, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'Role'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Pew\AppData\Roaming\JetBrains\PyCharm2023.3\scratches\sqlalchemy_bug.py", line 13, in <module>
    class User(Base):
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 849, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 574, in __init__
    self._extract_mappable_attributes()
  File "X:\dev\code\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 1556, in _extract_mappable_attributes
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not resolve all types within mapped annotation: "Mapped[Role]".  Ensure all types are written correctly and are imported within the module in use.
```

### Additional context

I am aware that the workaround would be to move Role out of User. Just, typing-wise, with type checkers, the code is sound.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include cls locals in annotation evaluate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5130

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**include cls locals in annotation evaluate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5131

**Comment by zzzeek** [comment]
hi  -

re: delayed evaluation, we do this for relationships where this kind of thing is typical within the registry.configure() step.  for mapped columns this would not be possible, this would require pretty much rewriting all of declarative from scratch.

The workaround for now would only be using TYPE_CHECKING:

```py
class User(Base):
    __tablename__ = 'user'

    class Role(enum.Enum):
        admin = 'admin'
        user = 'user'

    id: Mapped[int] =  mapped_column(primary_key=True)

    if typing.TYPE_CHECKING:
        role: Mapped[Role]
    else:
        role = mapped_column(Enum(Role), nullable=False, default=Role.user)

```

the main question is, how does Python interpreter know about Role but we dont?   We must be using an insufficient namespace when we evaluate.   Do we have that namespace?  we do!  from the class itself.   see linked patch will be in next release.
