### ISSUE TITLE
Update to JSON object key doesn't work

### ISSUE THREAD

**Issue by iurisilvio** [sqlalchemy/sqlalchemy#10927]
### Describe the bug

I don't know if it is an intentional unsupported feature or a bug.

I'm trying to copy a value from a key to another key and it fails on Postgres.

For Postgres 16, the SQL generated is:

```sql
UPDATE table SET column -> %(column_1)s=(column -> %(column_2)s)
[parameters: {'column_1': 'foo', 'column_2': 'bar'}]
```

The update fails with:

```
(psycopg2.errors.SyntaxError) syntax error at or near "->"
LINE 1: UPDATE table SET column -> 'foo'...
```

The expected syntax is `UPDATE table SET column['foo']=column -> 'bar'`.

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 16

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
I changed a test and ran it for sqlite and it fails with another error.


    def test_extract_subobject(self, connection, metadata):
        sqlite_json = Table("json_test", metadata, Column("foo", sqlite.JSON))

        metadata.create_all(connection)

        value = {"json": {"foo": "bar"}}

        connection.execute(sqlite_json.insert(), dict(foo=value))

        eq_(
            connection.scalar(select(sqlite_json.c.foo["json"])), value["json"]
        )
+       connection.execute(
+           sqlite_json.update().values({sqlite_json.c.foo["otherjson"]: sqlite_json.c.foo["json"]})
+       )


I don't know the expected syntax for sqlite.
```

### Error

```
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "(": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "pluggy/_callers.py", line 181, in _multicall
    return outcome.get_result()
  File "pluggy/_result.py", line 99, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "sqlalchemy/test/dialect/test_sqlite.py", line 317, in test_extract_subobject
    connection.execute(sqlite_json.update().values({sqlite_json.c.foo["newkey"]: sqlite_json.c.foo["json"]}))
  File "sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: UPDATE json_test SET JSON_QUOTE(JSON_EXTRACT(foo, ?))=(JSON_QUOTE(JSON_EXTRACT(json_test.foo, ?)))]
[parameters: ('$."newkey"', '$."json"')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

```

**Comment by CaselIT** [comment]
Hi,

You are mentioning postgresql but the example is using sqlite.
Aslo the code provided is not runnable as is

**Comment by iurisilvio** [comment]
Sorry, you can reproduce it with:

```python
from sqlalchemy import Column, MetaData, Table, create_engine
from sqlalchemy.dialects.sqlite import base as sqlite

engine = create_engine("sqlite://")
metadata = MetaData()


with engine.connect() as connection:
    sqlite_json = Table("json_test", metadata, Column("foo", sqlite.JSON))

    metadata.create_all(connection)

    value = {"json": {"foo": "bar"}}

    connection.execute(sqlite_json.insert(), dict(foo=value))

    connection.execute(
        sqlite_json.update().values({sqlite_json.c.foo["otherjson"]: sqlite_json.c.foo["json"]})
    )
```

It fails for Postgres too.

**Comment by CaselIT** [comment]
But they are you using `sqlite.JSON` in postgresql? That's a custom sqlite type

**Comment by iurisilvio** [comment]
For Postgres, I has able to use `func.jsonb_set` to make it work.

```python
sqlite_json.update().values({sqlite_json.c.foo: sa.func.jsonb_set(sqlite_json.c.foo, '{"otherjson"}', sqlite_json.c.foo["json"])})
```

Works for me now, but I think the performance is not the same of writing only an attribute to the column.

**Comment by iurisilvio** [comment]
> But they are you using sqlite.JSON in postgresql? That's a custom sqlite type

I'm using proper `jsonb` for postgres, I just wrote an example for sqlite now, reusing some test code.

**Comment by CaselIT** [comment]
Using postgresql json seems to work as expected.
```py
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

t = sa.table('foo', sa.column('bar', pg.JSON))
u = t.update().values({t.c.bar['foo']: t.c.bar['src']})

print(u.compile(dialect=pg.dialect()).string)
```
this prints that looks fine
```
'UPDATE foo SET bar -> %(bar_1)s=(foo.bar -> %(bar_2)s)'
```

**Comment by iurisilvio** [comment]
This SQL fails on Postgres 16 (at least for JSONB). I think it should be

```sql
UPDATE table SET bar[%(bar_1)s]=(foo.bar -> %(bar_2)s)
```

**Comment by CaselIT** [comment]
Ok I though you wanted to generate something like `'UPDATE foo SET bar -> %(bar_1)s=(foo.bar -> %(bar_2)s)'`.

Your proposed syntax will error too:

> ERROR: cannot subscript type json because it does not support subscripting

**Comment by iurisilvio** [comment]
Here the SQL statements:

```sql
=> create table foo (
   id       integer primary key, 
   bar  jsonb not null default '{}'::jsonb
);
CREATE TABLE

=> update foo set bar -> 'a' = bar -> 'b';
ERROR:  syntax error at or near "->"
LINE 1: update foo set bar -> 'a' = bar -> 'b';
                           ^
=> update foo set bar['a'] = bar -> 'b';
UPDATE 0

**Comment by CaselIT** [comment]
Transformed this in to an use case, since it's not something that's currently implemented.

Do you know if the `[]` syntax is equivalent to the `->` one and can be used instead of it in all places `->` was used (plus the new ones?)

**Comment by iurisilvio** [comment]
I think for `JSONB`, they're equivalent. https://www.postgresql.org/docs/current/datatype-json.html#JSONB-SUBSCRIPTING

For `JSON`, I did some tests here and subscription doesn't work.

```sql
create table foo
(
   id       integer primary key, 
   bar  json not null default '{}'::json 
);
insert into foo values (1, '{"foo": "bar"}');
feedscrubber=> select bar['foo'] from foo;
ERROR:  cannot subscript type json because it does not support subscripting
```

**Comment by CaselIT** [comment]
If so then 2.1 could maybe use this syntax in place of the current one for jsonb types.
I'm not sure if adding something like `t.c.a_jsonb_col['some-key'].subscript_notation()` or `t.c.a_jsonb_col['some-key'].as_subscript()` is a good option here.

@zzzeek do you have other ideas?

**Comment by zzzeek** [comment]
assuming I am seeing what's needed here, we only need the new syntax for the left hand side in an UPDATE SET clause, and on prior versions of PostgreSQL, nothing is supported anyway.   

if that's all accurate then I'd seek to get the postgresql compiler to use this new syntax only for left hand side SET variables.

**Comment by CaselIT** [comment]
Any particular reason for not changing it in all cases, other than the current way works fine?

**Comment by zzzeek** [comment]
I like to keep changes minimal and backend agnostic if possible

**Comment by iurisilvio** [comment]
> If that's all accurate

JSONB exists from Postgres 12, but JSONB subscripting is documented from Postgres 14, probably doesn't work before that. https://www.postgresql.org/docs/14/datatype-json.html#JSONB-SUBSCRIPTING

Needs some research to understand the details. Changing all cases may be problematic.

**Comment by CaselIT** [comment]
Ok. I'll update the initial issue and target 2.0

**Comment by rasca** [comment]
Hi! Do you know any workaround to use array subscripting in the keys of `update.values()` until this is implemented?

**Comment by CaselIT** [comment]
you can probably use `literal_column()` to provide a sql snippet

**Comment by rasca** [comment]
We are discussing this in https://github.com/sqlalchemy/sqlalchemy/discussions/12033#discussioncomment-11062653

The latest is that by using `literal_comun()`  I get

    sqlalchemy.exc.CompileError: Unconsumed column names: state['_status'],

**Comment by garyvdm** [comment]
Here is a minimal testcase for the issue @rasca got:

```python
from sqlalchemy import column, literal_column, table, update
from sqlalchemy.dialects.postgresql import JSONB

update(
    table("my_table", column("my_col", JSONB)),
).ordered_values(
    (literal_column("my_col['bar']"), "foo"),
).compile()
```

Result:

```
Traceback (most recent call last):
  File "/tmp/jsonb-subscript.py", line 8, in <module>
    ).compile()
      ~~~~~~~^^
  File "sqlalchemy/sql/elements.py", line 308, in compile
    return self._compiler(dialect, **kw)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "sqlalchemy/sql/elements.py", line 320, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "sqlalchemy/sql/compiler.py", line 1446, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sqlalchemy/sql/compiler.py", line 886, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sqlalchemy/sql/compiler.py", line 932, in process
    return obj._compiler_dispatch(self, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "sqlalchemy/sql/compiler.py", line 6269, in visit_update
    crud_params_struct = crud._get_crud_params(
        self, update_stmt, compile_state, toplevel, **kw
    )
  File "sqlalchemy/sql/crud.py", line 335, in _get_crud_params
    raise exc.CompileError(
    ...<2 lines>...
    )
sqlalchemy.exc.CompileError: Unconsumed column names: my_col['bar']
```

**Comment by zzzeek** [comment]
> > If that's all accurate
> 
> JSONB exists from Postgres 12, but JSONB subscripting is documented from Postgres 14, probably doesn't work before that. https://www.postgresql.org/docs/14/datatype-json.html#JSONB-SUBSCRIPTING
> 
> Needs some research to understand the details. Changing all cases may be problematic.

we can make the change for JSONB across the board if the dialect assumes PG version 14 or greater.  if PG version 13 was detected then we use the -> operator.   Since we're up to PG17 now I'd default an uninitialized dialect to the bracket syntax.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**support JSONB subscripting syntax** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6009

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**support JSONB subscripting syntax** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6010

**Comment by garyvdm** [comment]
Tested with version from git, and it's working great.  Much thanks @zzzeek ❤️

**Comment by CaselIT** [comment]
Just noticed that this is the default also in 2.0. it may cause some regression in tests if people are asserting sql generation.

Not sure how probable that is, thought

**Comment by zzzeek** [comment]
> Just noticed that this is the default also in 2.0. it may cause some regression in tests if people are asserting sql generation.
> 
> Not sure how probable that is, thought

yeah i think this was requested enough to get it in 2.0, I'm not too worried about SQL generation tests, that's not really a guaranteed invariant

**Comment by CaselIT** [comment]
yes, and making this optional is not great, since we would then have a pg dialect flag laying around for the next few releases

**Comment by garyvdm** [comment]
As someone who really want's this, I'm happy if this only makes it for 2.1.
