### ISSUE TITLE
with_expression relying on positive cache key present, doesnt work w/ custom type that has no cache key

### ISSUE THREAD

**Issue by cziebuhr** [sqlalchemy/sqlalchemy#10990]
### Describe the bug

I'm using a model with a custom TypeDecorator, where cache_ok is not set. When doing a query where this custom typed column is filtered AND using a query_expression on another column, the assertion mentioned above is raised.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/custom_types.html

### SQLAlchemy Version in Use

2.0.25

### DBAPI (i.e. the database driver)

mysqlclient

### Database Vendor and Major Version

MariaDB 10.11.4

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
from datetime import datetime, timezone
from sqlalchemy import create_engine, Column, Integer, Text, DateTime, func
from sqlalchemy.orm import DeclarativeBase, Session, with_expression, query_expression
from sqlalchemy.types import TypeDecorator


class Base(DeclarativeBase):
    pass


class TimeStamp(TypeDecorator):
    impl = DateTime

    def process_bind_param(self, value, dialect):
        return value.astimezone(timezone.utc)

    def process_result_value(self, value, dialect):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class AuditEvent(Base):
    __tablename__ = "audit_event"

    id = Column(Integer, primary_key=True)
    created_utc = Column(TimeStamp, nullable=False, default=datetime.now, index=True)
    msg = Column(Text, nullable=False)
    msg_translated = query_expression()


engine = create_engine("mysql://localhost/testdb")
with Session(engine) as session:

    # simplified
    msg_expr = func.coalesce(AuditEvent.msg)

    query = (
        session.query(AuditEvent)
        .filter(AuditEvent.created_utc > datetime(2023, 12, 12))
        .options(with_expression(AuditEvent.msg_translated, msg_expr))
    )

    event = query.first()
```

### Error

```
/opt/sql.py:44: SAWarning: TypeDecorator TimeStamp() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this warning at: https://sqlalche.me/e/20/cprf)
  event = query.first()
Traceback (most recent call last):
  File "/opt/sql.py", line 44, in <module>
    event = query.first()
            ^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2748, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 296, in orm_execute_statement
    return cls.orm_setup_cursor_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 580, in orm_setup_cursor_result
    querycontext = QueryContext(
                   ^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 185, in __init__
    self.propagated_loader_options = tuple(
                                     ^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 186, in <genexpr>
    opt._adapt_cached_option_to_uncached_option(self, uncached_opt)
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 1037, in _adapt_cached_option_to_uncached_option
    return self._adjust_for_extra_criteria(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 1082, in _adjust_for_extra_criteria
    new_context = tuple(
                  ^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 1083, in <genexpr>
    process(value._clone()) if value._extra_criteria else value
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/sqlalchemy/orm/strategy_options.py", line 1067, in process
    assert orig_cache_key is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Additional context

Issue found while upgrading from sqlalchemy 1.4. 
It works when omitting the `with_expression` part.

**Comment by zzzeek** [comment]
hi - 

noting the warning emitted, please apply cache_ok to your type

```py
class TimeStamp(TypeDecorator):
    cache_ok = True
    impl = DateTime

    def process_bind_param(self, value, dialect):
        return value.astimezone(timezone.utc)

    def process_result_value(self, value, dialect):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

```

will fix the non-cache case for 2.0.26

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**handle case where neither side has a cache key** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5162

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**handle case where neither side has a cache key** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5163
