### ISSUE TITLE
"Could not locate SQLAlchemy Core type for Python type" with Mapped Annotated Columns

### ISSUE THREAD

**Issue by imacat** [sqlalchemy/sqlalchemy#11130]
### Describe the bug

The Python 3.12 `type` syntax (TypeAliasType) does not work with mapped annotated columns.  Both

```
type str_pk = Annotated[str, mapped_column(primary_key=True)]
```

or

```
type str_pk = Mapped[Annotated[str, mapped_column(primary_key=True)]]
```

do not work.  However, the old type alias syntax works. 

```
str_pk = Annotated[str, mapped_column(primary_key=True)]
```

or

```
str_pk = Mapped[Annotated[str, mapped_column(primary_key=True)]]
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html

### SQLAlchemy Version in Use

2.0.28

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.12

### Operating system

Linux

### To Reproduce

```python
#! env python3
from typing import TypeAlias, Annotated
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass

str_pk_b: TypeAlias = Annotated[str, mapped_column(primary_key=True)]
type str_pk_c = Annotated[str, mapped_column(primary_key=True)]

class ModelA(Base):
    column_a: Mapped[Annotated[str, mapped_column(primary_key=True)]]
    column_b: Mapped[str_pk_b]
    column_c: Mapped[str_pk_c]

print("OK")
```

### Error

```
(test) user@host src/test % ./test.py
Traceback (most recent call last):
  File "/home/user/src/test/./test.py", line 11, in <module>
    class ModelA(Base):
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/decl_api.py", line 836, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 571, in __init__
    self._extract_mappable_attributes()
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 1541, in _extract_mappable_attributes
    value.declarative_scan(
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/properties.py", line 708, in declarative_scan
    self._init_column_for_annotation(
  File "/home/user/venv/test/lib/python3.12/site-packages/sqlalchemy/orm/properties.py", line 874, in _init_column_for_annotation
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not locate SQLAlchemy Core type for Python type str_pk_c inside the 'column_c' attribute Mapped annotation
(test) user@host src/test % 
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add extra pep695 conversion step** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5203

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**add extra pep695 conversion step** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5204
