### ISSUE TITLE
KeyError on query parameters when using schema_translate_map

### ISSUE THREAD

**Issue by JoeKellyRVA** [sqlalchemy/sqlalchemy#11157]
### Describe the bug

When using the `schema_translate_map` execution option on a SQLAlchemy ORM session, combined with the `insertmanyvalues` (default) option, the query produced raises a `KeyError`. The parameters passed to the query are numbered (i.e., `hour__1`, `hour__2`) but the query template itself only contains a non-numbered parameter name (i.e., `hour`).

### SQLAlchemy Version in Use

2.0.28

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.11.4

### Operating system

OSX

### To Reproduce

```python
from testcontainers.postgres import PostgresContainer # testcontainers==3.7.1

import sqlalchemy # SQLAlchemy==2.0.28
from sqlalchemy import (
    BigInteger,
    Integer,
    Numeric,
    Sequence,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session # sqlalchemy-orm==1.2.10


# Base class for all ORM classes
class Base(DeclarativeBase):
    pass

# Dummy object class
class BaseObjTest(Base):
    __tablename__ = "base_obj"
    __table_args__ = (
        UniqueConstraint("hour"),
        {
            "schema": "test",
        },
    )

    id: Mapped[int] = mapped_column(
        BigInteger, Sequence("base_obj_seq", schema="test"), primary_key=True
    )

    hour: Mapped[int] = mapped_column(Integer, nullable=False)
    value: Mapped[float] = mapped_column(Numeric, nullable=False)


if __name__ == "__main__":
    # Succeeds
    with PostgresContainer(image="postgres:15.3") as postgres:
        engine = sqlalchemy.create_engine(postgres.get_connection_url())
        with engine.connect() as conn:
            conn.execute(sqlalchemy.schema.CreateSchema("test"))
            conn.execute(sqlalchemy.text("COMMIT"))
            BaseObjTest.metadata.create_all(engine)

        with Session(engine) as session:
            session.add(BaseObjTest(hour=1, value=1.0))
            session.add(BaseObjTest(hour=2, value=2.0))
            session.add(BaseObjTest(hour=3, value=3.0))
            session.commit()

    # Succeeds
    with PostgresContainer(image="postgres:15.3") as postgres:
        engine = sqlalchemy.create_engine(postgres.get_connection_url()).execution_options(schema_translate_map={"abc": "abcd"})
        with engine.connect() as conn:
            conn.execute(sqlalchemy.schema.CreateSchema("test"))
            conn.execute(sqlalchemy.text("COMMIT"))
            BaseObjTest.metadata.create_all(engine)

        with Session(engine) as session:
            session.add(BaseObjTest(hour=1, value=1.0))
            session.commit()

    # Succeeds
    with PostgresContainer(image="postgres:15.3") as postgres:
        engine = sqlalchemy.create_engine(postgres.get_connection_url(), use_insertmanyvalues=False).execution_options(schema_translate_map={"abc": "abcd"})
        with engine.connect() as conn:
            conn.execute(sqlalchemy.schema.CreateSchema("test"))
            conn.execute(sqlalchemy.text("COMMIT"))
            BaseObjTest.metadata.create_all(engine)

        with Session(engine) as session:
            session.add(BaseObjTest(hour=1, value=1.0))
            session.add(BaseObjTest(hour=2, value=2.0))
            session.commit()

    # Fails with `KeyError: 'hour'`
    with PostgresContainer(image="postgres:15.3") as postgres:
        engine = sqlalchemy.create_engine(postgres.get_connection_url()).execution_options(schema_translate_map={"abc": "abcd"})
        with engine.connect() as conn:
            conn.execute(sqlalchemy.schema.CreateSchema("test"))
            conn.execute(sqlalchemy.text("COMMIT"))
            BaseObjTest.metadata.create_all(engine)

        with Session(engine) as session:
            session.add(BaseObjTest(hour=1, value=1.0))
            session.add(BaseObjTest(hour=2, value=2.0))
            session.commit()
```

### Error

```
2024-03-13 14:36:03,597 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-13 14:36:03,597 INFO sqlalchemy.engine.Engine INSERT INTO test.base_obj (id, hour, value) SELECT p0::BIGINT, p1::INTEGER, p2::NUMERIC FROM (VALUES (nextval('test.base_obj_seq'), %(hour)s, %(value)s)) AS imp_sen(p0, p1, p2, sen_counter) ORDER BY sen_counter RETURNING test.base_obj.id, test.base_obj.id AS id__1
2024-03-13 14:36:03,597 INFO sqlalchemy.engine.Engine [generated in 0.00003s (insertmanyvalues) 1/1 (ordered)] {'value__0': 1.0, 'hour__0': 1, 'value__1': 2.0, 'hour__1': 2}
2024-03-13 14:36:03,597 INFO sqlalchemy.engine.Engine ROLLBACK
``` 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "base_script_dir/tests/unit/example.py", line 73, in <module>
    session.commit()
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1143, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1847, in _execute_context
    return self._exec_insertmany_context(dialect, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2127, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2359, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2119, in _exec_insertmany_context
    dialect.do_execute(
  File "base_script_dir/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
KeyError: 'hour'
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**accommodate schema_translate_map in _deliver_insertmanyvalues_batches** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5206

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**accommodate schema_translate_map in _deliver_insertmanyvalues_batches** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5207

**Comment by zzzeek** [comment]
great, thanks for reporting

**Comment by JoeKellyRVA** [comment]
Thanks for the extremely quick response/fix!
