### ISSUE TITLE
Why is the query result of the SQLAlchemy hive tool different from that of the hive tool ?

### ISSUE THREAD

**Issue by zhangke-zhangke** [sqlalchemy/sqlalchemy#11222]
### Describe the bug

Hello,Ask a question: Symptom When you connect to hive using python, the query result is inconsistent with the database result

### SQLAlchemy Version in Use

2.0.29

### DBAPI (i.e. the database driver)

hive

### Database Vendor and Major Version

hive 2.1.1

### Python Version

python 3.9

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy.orm import sessionmaker,scoped_session
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    String,
    Enum,
    DECIMAL,
    DateTime,
    Boolean,
    UniqueConstraint,
    Index
)

Session = sessionmaker(bind=hive_engine)
session = scoped_session(Session)

engine = create_engine(
    f"hive://{hive_username}:{hive_password}@{hive_host}:{hive_port}/{hive_database}?auth={hive_auth}",
    max_overflow=0,
    pool_size=5,
    pool_timeout=10,
    pool_recycle=1,
    echo=True
)


Base = declarative_base()
class hivedata(Base):
    """ 必须继承Base """
    # 数据库中存储的表名
    __tablename__ = "zqy_transflow_info"

    # hive columns
    cust_name = Column(String(32),comment='cust_name')
    card_no = Column('card_no',String(32))
    cnter_cust_name = Column(String(32))

    __mapper_args__ = {
        'primary_key':[cust_name]
    }




if __name__ == '__main__':

  result = session.query(
      hive_data.hivedata.cust_name,
      hive_data.hivedata.card_no,
  ).all()
  
  print(result)
  print(pd.DataFrame(result))
```

### Error
```
2024-04-02 09:58:06,605 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-04-02 09:58:06,606 INFO sqlalchemy.engine.Engine SELECT `zqy_transflow_info`.`cust_name` AS `zqy_transflow_info_cust_name`, `zqy_transflow_info`.`card_no` AS `zqy_transflow_info_card_no` 
FROM `zqy_transflow_info`
2024-04-02 09:58:06,607 INFO sqlalchemy.engine.Engine [dialect hive+thrift does not support caching 0.00011s] {}
Traceback (most recent call last):
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\pyhive\hive.py", line 481, in execute
    _check_status(response)
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\pyhive\hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException [Error 10002]: Line 1:96 Invalid column reference 'card_no':28:27", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:329', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:207', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:260', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:504', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:479', 'sun.reflect.GeneratedMethodAccessor96:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:498', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:422', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1875', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy35:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:270', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:508', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:96 Invalid column reference 'card_no':42:15", 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genAllExprNodeDesc:SemanticAnalyzer.java:11402', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11350', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genSelectPlan:SemanticAnalyzer.java:4286', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genSelectPlan:SemanticAnalyzer.java:4060', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPostGroupByBodyPlan:SemanticAnalyzer.java:9558', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genBodyPlan:SemanticAnalyzer.java:9497', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10381', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10259', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genOPTree:SemanticAnalyzer.java:10942', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:10953', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:10638', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:250', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:603', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1425', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1398', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:205'], sqlState='42000', errorCode=10002, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10002]: Line 1:96 Invalid column reference 'card_no'"), operationHandle=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\python-graph\createGraph\test_db_orm.py", line 24, in <module>
    result = models.session.query(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\orm\session.py", line 2306, in execute
    return self._execute_internal(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\orm\session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1422, in execute
    return meth(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1850, in _execute_context
    return self._exec_single_context(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\sqlalchemy\engine\default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\pyhive\hive.py", line 481, in execute
    _check_status(response)
  File "D:\Anaconda3\envs\network_3.9\lib\site-packages\pyhive\hive.py", line 611, in _check_status
    raise OperationalError(response)
sqlalchemy.exc.OperationalError: (pyhive.exc.OperationalError) TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException [Error 10002]: Line 1:96 Invalid column reference 'card_no':28:27", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:329', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:207', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:260', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:504', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:479', 'sun.reflect.GeneratedMethodAccessor96:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:498', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:422', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1875', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy35:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:270', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:508', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:96 Invalid column reference 'card_no':42:15", 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genAllExprNodeDesc:SemanticAnalyzer.java:11402', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genExprNodeDesc:SemanticAnalyzer.java:11350', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genSelectPlan:SemanticAnalyzer.java:4286', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genSelectPlan:SemanticAnalyzer.java:4060', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPostGroupByBodyPlan:SemanticAnalyzer.java:9558', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genBodyPlan:SemanticAnalyzer.java:9497', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10381', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genPlan:SemanticAnalyzer.java:10259', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:genOPTree:SemanticAnalyzer.java:10942', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:10953', 'org.apache.hadoop.hive.ql.parse.SemanticAnalyzer:analyzeInternal:SemanticAnalyzer.java:10638', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:250', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:603', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1425', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1398', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:205'], sqlState='42000', errorCode=10002, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10002]: Line 1:96 Invalid column reference 'card_no'"), operationHandle=None)
[SQL: SELECT `zqy_transflow_info`.`cust_name` AS `zqy_transflow_info_cust_name`, `zqy_transflow_info`.`card_no` AS `zqy_transflow_info_card_no` 
FROM `zqy_transflow_info`]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Additional context

The native SQLAlchemy printed using sql can be run in the hive tool to query results. In addition, when I use session.query().count(), the amount of data is not consistent with the execution in the tool. I'm not sure what the question is. Thank you for your answer.

The following is the result of using the hive tool :

![微信图片_20240402101628](https://github.com/sqlalchemy/sqlalchemy/assets/80733236/04cb5c47-16f2-43d2-ba54-6884eaf301e5)

**Comment by CaselIT** [comment]
Hi,

The hive dialect is not maintained here. I would suggest asking their maintainers for suggestions.
