### ISSUE TITLE
URL corrupted if '@' character present in password

### ISSUE THREAD

**Issue by jchouinard-dimonoff** [sqlalchemy/sqlalchemy#11262]
### Describe the bug

# Description

When using a `@` character in the password of a connection URL string, the password is truncated at the `@` and the URL becomes mangled, causing connection issues. The expected behavior is for the password to be correctly parsed, even when it contains special characters like '@'.

# Example

```python
import sqlalchemy

url = "mysql+pymysql://username:p@ssword@mydb.com"
engine = sqlalchemy.create_engine(url)
with engine.connect() as connection:
    pass
```

Raises:

```bash
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ssword@mydb.com' ([Errno -2] Name or service not known)")
```

As you can see, the client attempts to connect to `ssword@mydb.com` instead of `mydb.com`.

# Solution

I believe this is because the regex defined in the `_parse_url()` function (`lib/sqlalchemy/engine/url.py`) ignores any `@` present in the password, thus assuming the password ends at the first `@` encountered:

> url.py, line 855 
> ```python
> (?::(?P<password>[^@]*))?
> ```

Instead, the regex could capture any characters greedily using `.*`:

> url.py, line 855 
> ```python
> (?::(?P<password>.*))?
> ```

This fix should work correctly, as demonstrated here: <https://regex101.com/r/0b8SUr/1>

### SQLAlchemy Version in Use

2.0.29

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

MySQL

### Python Version

3.10.12

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy

url = "mysql+pymysql://username:p@ssword@mydb.com"
engine = sqlalchemy.create_engine(url)
with engine.connect() as connection:
    pass
```

### Error

```
Traceback (most recent call last):
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 644, in connect
    sock = socket.create_connection(
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'ssword@mydb.com' ([Errno -2] Name or service not known)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/test.py", line 5, in <module>
    with engine.connect() as connection:
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/home/jchouinard/Work/Lighting/Tools/doo-firmware-upgrade-multi/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ssword@mydb.com' ([Errno -2] Name or service not known)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by CaselIT** [comment]
Hi,

As documented you need to escape special characters
See also https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22%40+%28or+other+chars%29+in+password%22+

**Comment by CaselIT** [comment]
should proposed solution btw would not work, since it database names can have @ in the name. With your solution it would break when doing something like `mysql+pymysql://username:p@ssword@mydb.com/foo@bar`

**Comment by jchouinard-dimonoff** [comment]
Ok I see, sorry for the duplicated issue.
Thank you!
