### ISSUE TITLE
`orm.composite` with polymorphic "selectin" loading raises `AttributeError: _wildcard_token`

### ISSUE THREAD

**Issue by kkroening** [sqlalchemy/sqlalchemy#11291]
### Describe the bug

If a composite property (`sqlalchemy.orm.composite` ) is defined in a polymorphic base model and inherited by subclass(es) via joined-table inheritance, attempting to query against the base model using "selectin" loading fails with `AttributeError: _wildcard_token`.

### SQLAlchemy Version in Use

2.0.29

### DBAPI (i.e. the database driver)

sqlite, aiosqlite, aiomysql

### Database Vendor and Major Version

SQLite, MySQL 8

### Python Version

3.11, 3.12

### Operating system

OSX

### To Reproduce

```python
import dataclasses
import sqlalchemy
from sqlalchemy import ForeignKey
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import Session
from sqlalchemy.orm import composite
from sqlalchemy.orm import mapped_column


@dataclasses.dataclass
class Point:
    x: int
    y: int


class Base(DeclarativeBase):
    pass


class Vertex(Base):
    __tablename__ = 'vertices'
    __mapper_args__ = {
        'polymorphic_abstract': True,
        'polymorphic_identity': __tablename__,
        'polymorphic_on': 'typename',
    }

    id: Mapped[int] = mapped_column(primary_key=True)
    typename: Mapped[str]
    position: Mapped[Point] = composite(mapped_column('x1'), mapped_column('y1'))


class BigVertex(Vertex):
    __tablename__ = 'bigvertices'
    __mapper_args__ = {
        'polymorphic_identity': __tablename__,
        'polymorphic_load': 'selectin',
        # 'polymorphic_load': 'inline',  # (workaround)
    }

    id: Mapped[int] = mapped_column(ForeignKey('vertices.id'), primary_key=True)
    size: Mapped[int] = mapped_column(default=10)


engine = create_engine('sqlite://', echo=True)
Base.metadata.create_all(engine)

with Session(engine) as session:
    big_vert = BigVertex(
        position=Point(x=42, y=43),
        size=100,
    )
    session.add(big_vert)
    session.commit()

with Session(engine) as session:
    # NOTE: This works fine (query by subclass), with or without "selectin" loading:
    print(session.scalars(sqlalchemy.select(BigVertex)).all())

    # NOTE: When using "selectin" loading, querying by the baseclass blows up with
    # `AttributeError: _wildcard_token`:
    print(session.scalars(sqlalchemy.select(Vertex)).all())
```

### Error

```
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("vertices")
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("vertices")
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("bigvertices")
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("bigvertices")
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine 
CREATE TABLE vertices (
	id INTEGER NOT NULL, 
	typename VARCHAR NOT NULL, 
	x1 INTEGER NOT NULL, 
	y1 INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [no key 0.00003s] ()
2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine 
CREATE TABLE bigvertices (
	id INTEGER NOT NULL, 
	size INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES vertices (id)
)


2024-04-18 12:59:13,735 INFO sqlalchemy.engine.Engine [no key 0.00002s] ()
2024-04-18 12:59:13,736 INFO sqlalchemy.engine.Engine COMMIT
2024-04-18 12:59:13,736 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-04-18 12:59:13,736 INFO sqlalchemy.engine.Engine INSERT INTO vertices (typename, x1, y1) VALUES (?, ?, ?)
2024-04-18 12:59:13,736 INFO sqlalchemy.engine.Engine [generated in 0.00006s] ('bigvertices', 42, 43)
2024-04-18 12:59:13,737 INFO sqlalchemy.engine.Engine INSERT INTO bigvertices (id, size) VALUES (?, ?)
2024-04-18 12:59:13,737 INFO sqlalchemy.engine.Engine [generated in 0.00004s] (1, 100)
2024-04-18 12:59:13,737 INFO sqlalchemy.engine.Engine COMMIT
2024-04-18 12:59:13,737 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-04-18 12:59:13,738 INFO sqlalchemy.engine.Engine SELECT bigvertices.id, vertices.id AS id_1, vertices.typename, vertices.x1, vertices.y1, bigvertices.size 
FROM vertices JOIN bigvertices ON vertices.id = bigvertices.id
2024-04-18 12:59:13,738 INFO sqlalchemy.engine.Engine [generated in 0.00005s] ()
[<__main__.BigVertex object at 0x10696e6f0>]
2024-04-18 12:59:13,739 INFO sqlalchemy.engine.Engine SELECT vertices.id, vertices.typename, vertices.x1, vertices.y1 
FROM vertices
2024-04-18 12:59:13,739 INFO sqlalchemy.engine.Engine [generated in 0.00004s] ()
2024-04-18 12:59:13,739 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/Users/me/example.py", line 64, in <module>
    print(session.scalars(sqlalchemy.select(Vertex)).all())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1769, in all
    return self._allrows()
           ^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 548, in _allrows
    rows = self._fetchall_impl()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1676, in _fetchall_impl
    return self._real_result._fetchall_impl()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 2270, in _fetchall_impl
    return list(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 223, in chunks
    rows = [proc(row) for row in fetch]
            ^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1470, in polymorphic_instance
    _instance = polymorphic_instances[discriminator]
                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/util/_collections.py", line 344, in __missing__
    self[key] = val = self.creator(key)
                      ^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1453, in configure_subclass_mapper
    return _instance_processor(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1013, in _instance_processor
    callable_ = _load_subclass_via_in(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1257, in _load_subclass_via_in
    q, enable_opt, disable_opt = mapper._subclass_load_via_in_mapper
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3902, in _subclass_load_via_in_mapper
    return self._subclass_load_via_in(self, self.base_mapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3856, in _subclass_load_via_in
    disable_opt = disable_opt._set_generic_strategy(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _set_generic_strategy
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 280, in _generative
    x = fn(self, *args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/strategy_options.py", line 864, in _set_generic_strategy
    self._clone_for_bind_strategy(
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/strategy_options.py", line 1308, in _clone_for_bind_strategy
    load_element = _AttributeStrategyLoad.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/strategy_options.py", line 1769, in create
    path = opt._init_path(
           ^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/strategy_options.py", line 1977, in _init_path
    path = path[prop]
           ~~~~^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/path_registry.py", line 792, in _getitem
    return self._cache[entity]
           ~~~~~~~~~~~^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/path_registry.py", line 762, in __missing__
    self[key] = item = PropRegistry(self.registry, key)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/orm/path_registry.py", line 622, in __init__
    parent.natural_path + self.prop._wildcard_token,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1328, in __getattr__
    return self._fallback_getattr(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1297, in _fallback_getattr
    raise AttributeError(key)
AttributeError: _wildcard_token
``` 

### Additional context

Notes:
* The `Point` class is taken from the [usual example](https://docs.sqlalchemy.org/en/20/orm/composites.html) as-is.
* The `Vertex` class is stripped down and becomes a polymorphic base model here.
* `BigVertex` is a (contrived) example subclass that inherits the composite property.
* Querying against the subclass (`BigVertex`) table works fine, but querying against the base (`Vertex`) fails when using "selectin" loading.
* Switching to "inline" loading acts as a workaround - but misses out on the benefits of selectin loading.
* The database driver doesn't seem to matter, and this happens with both async and non-async.
* (FWIW, the snippet passes `mypy --strict`)

Possibly related issue(s):
* https://github.com/sqlalchemy/sqlalchemy/issues/7801 : Looks like a very similar issue on the surface, but was fixed in 2022, whereas this is happening with SQLAlchemy 2.0.29 even with that fix (presumably).

**Comment by kkroening** [comment]
I think I see the problem:

`Mapper._subclass_load_via_in` loops through all the mapper attributes and attempts to use `disable_opt._set_generic_strategy` to set a "do_nothing" strategy option:

```python
        # ... in `Mapper._subclass_load_via_in(...)` - trimmed for brevity:

        for prop in self.attrs:
            if prop.key not in self.class_manager:
                continue

            if prop.parent in classes_to_include or prop in keep_props:
                if not isinstance(prop, StrategizedProperty):
                    continue

                enable_opt = enable_opt._set_generic_strategy(
                    (getattr(entity.entity_namespace, prop.key),),
                    dict(prop.strategy_key),
                    _reconcile_to_other=True,
                )
            else:
                disable_opt = disable_opt._set_generic_strategy(
                    (getattr(entity.entity_namespace, prop.key),),
                    {"do_nothing": True},
                    _reconcile_to_other=False,
                )
```

The `else` case is where it's blowing up, deep down in `PropRegistry` where it tries to access `prop._wildcard_token` which comes from `StrategizedProperty`.

Note: The `PropRegistry` annotation shows `prop: MapperProperty[Any]`, but apparently it _actually_ expects it to be a `StrategizedProperty`, which is a more specialized subclass of `MapperProperty`, which can be seen in the following SQLAlchemy class hierarchy diagram:

![class_hierarchy](https://github.com/sqlalchemy/sqlalchemy/assets/2035953/5f9f95df-1d3d-4821-beb3-78e03eb998a8)

The code path in question above (`disable_opt._set_generic_strategy(...)`) apparently works fine as long as it's dealing with a `RelationshipProperty` - e.g. `ColumnProperty` or `RelationshipProperty` - but if it trips over a `CompositeProperty`, the `_set_generic_strategy` blows up downstream with the `AttributeError: _wildcard_token`.

It seems that in the `if` case, there's already a check to skip over non-`StrategizedProperty` attributes (which would avoid tripping over `CompositeProperty`), so maybe that check just needs to be moved up a level so that it applies more broadly.

```diff
         for prop in self.attrs:
             if prop.key not in self.class_manager:
                 continue

+            if not isinstance(prop, StrategizedProperty):
+                continue
+
             if prop.parent in classes_to_include or prop in keep_props:
-                if not isinstance(prop, StrategizedProperty):
-                    continue
-
                 enable_opt = enable_opt._set_generic_strategy(
                     (getattr(entity.entity_namespace, prop.key),),
                     dict(prop.strategy_key),
                     _reconcile_to_other=True,
                 )
             else:
                 disable_opt = disable_opt._set_generic_strategy(
                     (getattr(entity.entity_namespace, prop.key),),
                     {"do_nothing": True},
                     _reconcile_to_other=False,
                 )
```

The change indeed fixes the issue shown in the "To Reproduce" example script above.

Not sure if there are any other gotchas with the proposed fix, but hopefully this info helps.

**Comment by zzzeek** [comment]
Hi, thanks for that research.  I havent had time to look at this one yet but it was clear based on use of relatively new features in sqlalchemy this was some kind of bug.   Usually I can turn these around in half a day but am traveling this week, which is adding to delay on this end.

**Comment by kkroening** [comment]
No worries, @zzzeek . FWIW, we're unblocked by using the inline polymorphic loader pattern for now, so mainly just surfacing the issue in case anyone else runs into it. Thanks for all your hard work and dedication over the years with SQLAlchemy.

**Comment by CaselIT** [comment]
thanks for the analysis.

@kkroening that graph is interesting, did you use a particular tool or was it done manually?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**try the proposed patch** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5253

**Comment by CaselIT** [comment]
Uploaded the proposed patch to see if it breaks the ci

**Comment by kkroening** [comment]
> @kkroening that graph is interesting, did you use a particular tool or was it done manually?

It was just a quick one-off script using graphviz:

```python
import graphviz  # type: ignore
import importlib
from collections.abc import Iterable
from typing import Any


def _should_visit_class(cls: type[Any]) -> bool:
    # TBD: customize as desired to skip uninteresting classes.
    return cls is not object and cls.__module__ not in {'typing', 'abc'}


def _get_base_classes(cls: type[Any]) -> Iterable[type[Any]]:
    return filter(_should_visit_class, cls.__bases__)


def _find_classes(
    subclasses: set[type[Any]],
) -> set[type[Any]]:
    classes = set()

    def visit(cls: type[Any]) -> None:
        classes.add(cls)
        for base_class in _get_base_classes(cls):
            visit(base_class)

    for cls in filter(_should_visit_class, subclasses):
        visit(cls)
    return classes


def _get_class_label(
    cls: type[Any],
) -> str:
    return f'{cls.__module__}.{cls.__qualname__}'


def visualize_class_hierarchy(
    subclasses: set[type[Any]],
) -> graphviz.Digraph:
    classes = _find_classes(subclasses)
    module_names = {x.__module__ for x in classes}

    graph = graphviz.Digraph(
        comment='Class Hierarchy',
        format='svg',
        engine='dot',
        graph_attr=dict(
            rankdir='BT',
            nodesep='0.4',
            ranksep='1.5',
        ),
        node_attr=dict(
            fillcolor='snow',
            fontname='Input',
            shape='box',
            style='filled',
        ),
    )

    for module_name in module_names:
        with graph.subgraph(
            name='cluster_' + module_name.replace('.', '_'),
        ) as subgraph:
            subgraph.attr(
                'graph',
                penwidth='2',
                fillcolor='lightsteelblue1',
                fontname='Input Bold',
                fontsize='18',
                label=module_name,
                labelloc='b',
                style='filled',
            )
            module_classes = {x for x in classes if x.__module__ == module_name}
            for cls in module_classes:
                cls_label = _get_class_label(cls)
                node_kwargs: dict[str, Any] = {}
                if cls in subclasses:
                    node_kwargs.update(fillcolor='lightgreen')
                subgraph.node(
                    cls_label,
                    label=cls.__name__,
                    **node_kwargs,
                )

    for cls in classes:
        cls_label = _get_class_label(cls)
        for parent_class in _get_base_classes(cls):
            parent_label = _get_class_label(parent_class)
            graph.edge(cls_label, parent_label)

    return graph
```

Example usage:
```python
import sqlalchemy.orm

visualize_class_hierarchy(
    {
        sqlalchemy.orm.ColumnProperty,
        sqlalchemy.orm.Composite,
        sqlalchemy.orm.RelationshipProperty,
        sqlalchemy.orm.interfaces.StrategizedProperty,
    }
)
```

**Comment by CaselIT** [comment]
interesting, thanks for sharing!

**Comment by zzzeek** [comment]
pretty strange we have a unit test for this exact case.   sometihng clearly different here

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**only consider column / relationship attrs for subclass IN** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5271

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**only consider column / relationship attrs for subclass IN** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5272
