### ISSUE TITLE
IndexError in Query with string literal + repeated ORM attribute

### ISSUE THREAD

**Issue by Fredrik-M** [sqlalchemy/sqlalchemy#11306]
### Describe the bug

`IndexError: tuple index out of range` is raised when executing a query for a string literal and a repeated ORM attribute.

### SQLAlchemy Version in Use

2.0.28

### DBAPI (i.e. the database driver)

pyodbc 5.0.1

### Database Vendor and Major Version

MS SQL Server 15 (2019)

### Python Version

3.9

### Operating system

Ubuntu 20.04

### To Reproduce

```python
import sqlalchemy as sqla
import sqlalchemy.orm
import sqlalchemy_utils as sqla_utils


host = 'localhost'
database = 'test'
user = 'sa'
password = input(f'Password for {user} at {host}:')

eng = sqla.create_engine(
    sqla.engine.URL.create(
        drivername='mssql+pyodbc',
        username=user,
        password=password,
        host=host,
        database=database,
        query={'driver': 'ODBC Driver 17 for SQL Server'}
    )
)

_Base = sqla.orm.declarative_base()


class Record(_Base):

    __tablename__ = 'record'

    id = sqla.Column(sqla.Integer, primary_key=True)


def test(query):

    print()
    print(query)
    print(query.first())


if __name__ == '__main__':

    if not sqla_utils.database_exists(eng.url):
        sqla_utils.create_database(eng.url)

    Record.__table__.create(eng, checkfirst=True)

    sess = sqla.orm.Session(eng)

    for _ in range(10):
        sess.add(Record())
    sess.commit()

    # no issues
    test(sess.query(Record.id, Record.id))
    test(sess.query(Record.id, Record.id, Record.id))
    test(sess.query(sqla.text("'foobar'"), Record.id))
    test(sess.query(Record.id, sqla.text("'foobar'")))

    # fails
    test(sess.query(sqla.text("'foobar'"), Record.id, Record.id))
    test(sess.query(Record.id, sqla.text("'foobar'"), Record.id))
    test(sess.query(Record.id, Record.id, sqla.text("'foobar'")))
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/fredrik/testing/sqla_text.py", line 86, in main
    test(sess.query(sqla.text("'foobar'"), Record.id, Record.id))
  File "/data/fredrik/testing/sqla_text.py", line 68, in test
    print(query.first())
  File ".../sqlalchemy/orm/query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
  File ".../sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File ".../sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File ".../sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File ".../sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File ".../sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File ".../sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File ".../sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File ".../sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File ".../sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File ".../sqlalchemy/engine/base.py", line 2359, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File ".../sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    result = context._setup_result_proxy()
  File ".../sqlalchemy/engine/default.py", line 1830, in _setup_result_proxy
    result = _cursor.CursorResult(self, strategy, cursor_description)
  File ".../sqlalchemy/engine/cursor.py", line 1439, in __init__
    metadata = self._init_metadata(context, cursor_description)
  File ".../sqlalchemy/engine/cursor.py", line 1489, in _init_metadata
    metadata = CursorResultMetaData(self, cursor_description)
  File ".../sqlalchemy/engine/cursor.py", line 375, in __init__
    raw = self._merge_cursor_description(
  File ".../sqlalchemy/engine/cursor.py", line 625, in _merge_cursor_description
    return [
  File ".../sqlalchemy/engine/cursor.py", line 625, in <listcomp>
    return [
  File ".../sqlalchemy/engine/cursor.py", line 702, in _merge_textual_cols_by_position
    if obj[0] in seen:
IndexError: tuple index out of range
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure result_map objects collection is non-empty** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5274

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**ensure result_map objects collection is non-empty** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5275
