### ISSUE TITLE
Combining "within group" and "filter" doesn't seem to be possible

### ISSUE THREAD

**Issue by willnewton** [sqlalchemy/sqlalchemy#11423]
### Describe the bug

I'd like to be able to combine the within group and filter syntax on the same aggregate function, e.g.:

```
select percentile_cont(0.9) within group (order by value) filter (where id > 10) from test_table;
```

However the method I tried to achieve this fails:

```
from sqlalchemy import Column, Integer, Float, Table, MetaData, func

metadata_obj = MetaData()

table = Table(
    "test_table",
    metadata_obj,
    Column("id", Integer, primary_key=True),
    Column("value", Float),
)

f = func.percentile_cont(0.9).within_group(table.c.value).filter(table.c.value > 10)
```

with the following error:

```
AttributeError: Neither 'WithinGroup' object nor 'Comparator' object has an attribute 'filter'
```

Is there a way to achieve the desired result above?

Thanks!

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 16

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
from sqlalchemy import Column, Integer, Float, Table, MetaData, func

metadata_obj = MetaData()

table = Table(
    "test_table",
    metadata_obj,
    Column("id", Integer, primary_key=True),
    Column("value", Float),
)

f = func.percentile_cont(0.9).within_group(table.c.value).filter(table.c.value > 10)
```

### Error

```
AttributeError: Neither 'WithinGroup' object nor 'Comparator' object has an attribute 'filter'
```

**Comment by zzzeek** [comment]
if you can confirm this works

```py
from sqlalchemy.sql.functions import FunctionFilter


f = func.percentile_cont(0.9).within_group(table.c.value)
expr = FunctionFilter(f, table.c.value > 10)

```

this would be a short PR (with a test in test/sql/test_functions.py) to add `filter()` to `WithinGroup`

**Comment by zzzeek** [comment]
(and probably also add `within_group()` to `FunctionFilter`, and test that way also)

**Comment by willnewton** [comment]
> if you can confirm this works
> 
> ```python
> from sqlalchemy.sql.functions import FunctionFilter
> 
> 
> f = func.percentile_cont(0.9).within_group(table.c.value)
> expr = FunctionFilter(f, table.c.value > 10)
> ```
> 
> this would be a short PR (with a test in test/sql/test_functions.py) to add `filter()` to `WithinGroup`

Yes, I can confirm this generates the correct SQL. Thanks!

**Comment by CaselIT** [comment]
@zzzeek I think there is also a bug in `FunctionFilter.filter`: should be generative but isn't https://github.com/sqlalchemy/sqlalchemy/blob/deb285550a26f37c4bc3a0289df370691e25843c/lib/sqlalchemy/sql/elements.py#L4404-L4424

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Reorganize function element** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5324

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add missing function element methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5329

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Add missing function element methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5330

**Comment by Soulbadguy54** [comment]
Interesting that this fragment of code:
`func.mode().within_group(LolUserResult.stats["champion_id"].cast(String)).label('fav_champ')`
works perfect on windows, while failed on ubuntu with such traceback:
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 1496, in __getattr__
    return getattr(self.comparator, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Comparator' object has no attribute 'filter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/tusaV2/main.py", line 82, in main
    await DataUpdater.update_ratings()
  File "/root/tusaV2/other/data_updater.py", line 31, in update_ratings
    func.mode().within_group(CsDBMatch.map).filter(CSUserResult.is_win == True).label('fav_map'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 1498, in __getattr__
    raise AttributeError(
AttributeError: Neither 'WithinGroup' object nor 'Comparator' object has an attribute 'filter'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.12/contextlib.py", line 737, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |                   ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/tusaV2/main.py", line 82, in main
    |     await DataUpdater.update_ratings()
    |   File "/root/tusaV2/other/data_updater.py", line 31, in update_ratings
    |     func.mode().within_group(CsDBMatch.map).filter(CSUserResult.is_win == True).label('fav_map'),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 1498, in __getattr__
    |     raise AttributeError(
    | AttributeError: Neither 'WithinGroup' object nor 'Comparator' object has an attribute 'filter'
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/root/tusaV2/main.py", line 64, in main
  |     async with SCHEDULER as scheduler, LOL_CLIENT, PYRO_BOT, BOT:
  |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/apscheduler/_schedulers/async_.py", line 178, in __aexit__
  |     await self._exit_stack.__aexit__(exc_type, exc_val, exc_tb)
  |   File "/usr/lib/python3.12/contextlib.py", line 754, in __aexit__
  |     raise exc_details[1]
  |   File "/usr/lib/python3.12/contextlib.py", line 737, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |                   ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/usr/lib/python3.12/contextlib.py", line 737, in __aexit__
    |     cb_suppress = await cb(*exc_details)
    |                   ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
    |     raise BaseExceptionGroup(
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/root/tusaV2/main.py", line 82, in main
      |     await DataUpdater.update_ratings()
      |   File "/root/tusaV2/other/data_updater.py", line 31, in update_ratings
      |     func.mode().within_group(CsDBMatch.map).filter(CSUserResult.is_win == True).label('fav_map'),
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/root/.cache/pypoetry/virtualenvs/tusadaunovv2-XWcM8NJQ-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 1498, in __getattr__
      |     raise AttributeError(
      | AttributeError: Neither 'WithinGroup' object nor 'Comparator' object has an attribute 'filter'
      +------------------------------------

```

**Comment by CaselIT** [comment]
I think you are using an old version of sqlalchemy there. Can you ensure that the correct version is used in both cases?

**Comment by Soulbadguy54** [comment]
> I think you are using an old version of sqlalchemy there. Can you ensure that the correct version is used in both cases?

Yes! 20.0.31 on both venvs

**Comment by CaselIT** [comment]
It seems very strange honestly, since the python code is exactly the same.
Can you try installing using pip instead of poetry, that does wired things at times?

**Comment by CaselIT** [comment]
works perfectly fine on linux
```py
[federico@linux ~]$ pip install sqlalchemy
Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Obtaining dependency information for sqlalchemy from https://files.pythonhosted.org/packages/60/f8/7794f3055d50e96cee04c19c7faeedacb323c7762f334660ba03bed95485/SQLAlchemy-2.0.31-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading SQLAlchemy-2.0.31-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Obtaining dependency information for typing-extensions>=4.6.0 from https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl.metadata
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Obtaining dependency information for greenlet!=0.4.17 from https://files.pythonhosted.org/packages/bd/37/56b0da468a85e7704f3b2bc045015301bdf4be2184a44868c71f6dca6fe2/greenlet-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata
  Using cached greenlet-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading SQLAlchemy-2.0.31-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 3.4 MB/s eta 0:00:00
Using cached greenlet-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (625 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.31 typing-extensions-4.12.2
[federico@linux ~]$ python
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> sa.func.mode().within_group(sa.column('map')).filter(sa.column('is_win') == True).label('fav_map')
<sqlalchemy.sql.elements.Label at 0x7fe2b6fd2f90; fav_map>
>>>
```
