### ISSUE TITLE
sqlalchemy can't distinguish starrocks biginter 

### ISSUE THREAD

**Issue by wochicheng** [sqlalchemy/sqlalchemy#11421]
### Describe the bug

my db is starrocks,my table have a column which type is "bigint(20) unsigned"
<img width="365" alt="image" src="https://github.com/sqlalchemy/sqlalchemy/assets/62383904/22053569-badf-4a1e-bd7b-92165334b156">
so i want to use sqlalchemy, when i try to get metadata,the scripts receive a error
" SAWarning: Did not recognize type 'largeint' of column 'value'"
![image](https://github.com/sqlalchemy/sqlalchemy/assets/62383904/8148c78e-ce00-493f-8718-e431da32affe)
 

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

starrocks 

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DATABASE_URL = 'mysql+pymysql://******:*******@dbserver:9030/db'

engine = create_engine(DATABASE_URL)
metadata = MetaData()
metadata.reflect(bind=engine, only=['db'])
```

### Error

```
/Users/******/Desktop/pyscripts/******.py:9: SAWarning: Did not recognize type 'largeint' of column 'value'
  metadata.reflect(bind=engine, only=['db'])
Traceback (most recent call last):
  File "/Users/******/Desktop/pyscripts/******.py", line 9, in <module>
    metadata.reflect(bind=engine, only=['db'])
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5817, in reflect
    _reflect_info = insp._get_reflection_info(
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 2006, in _get_reflection_info
    columns=run(
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 1992, in run
    res = meth(filter_names=_fn, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 921, in get_multi_columns
    table_col_defs = dict(
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1101, in _default_multi_reflect
    single_tbl_method(
  File "<string>", line 2, in get_columns
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 2964, in get_columns
    parsed_state = self._parsed_state_or_create(
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 3224, in _parsed_state_or_create
    return self._setup_parser(
  File "<string>", line 2, in _setup_parser
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 3260, in _setup_parser
    return parser.parse(sql, charset)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/reflection.py", line 48, in parse
    self._parse_column(line, state)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/reflection.py", line 284, in _parse_column
    type_instance = col_type(*type_args, **type_kw)
TypeError: NullType() takes no arguments
```

**Comment by CaselIT** [comment]
Hi,

The internal mysql supports only mysql and mariadb, not 3rd party implementation.
A quick google search found this external dialect https://pypi.org/project/starrocks/.

**Comment by wochicheng** [comment]
![image](https://github.com/sqlalchemy/sqlalchemy/assets/62383904/1c469ead-004c-468d-8d8b-1b80d6606a2a)
i have change to starrocks，it also be error

**Comment by CaselIT** [comment]
Please report it to the starrocks dialect developers, since there seems to be an issue there

**Comment by zzzeek** [comment]
interesting tho that the MySQL dialect is trying to send the int arguments to the NullType().  If we get the "can't recognize type" warning, which is normal, we should not be erroring out - it should be discarding the additional type arguments

**Comment by CaselIT** [comment]
> interesting tho that the MySQL dialect is trying to send the int arguments to the NullType(). If we get the "can't recognize type" warning, which is normal, we should not be erroring out - it should be discarding the additional type arguments

yes, I noticed it too. That may warrant an specific issue
