### ISSUE TITLE
 cannot find api in sqlalchemy.ext.declarative.api  

### ISSUE THREAD

**Issue by avss27** [sqlalchemy/sqlalchemy#11451]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

I want to import DeclarativeMeta from sqlalchemy.ext.declarative.api but there is no api and because of that I'm getting the following error.
I want to use the Pathme package and for that I have to download and populate bio2bel_chebi and for that I need the sqlalchemz

### To Reproduce

```python
bio2bel_chebi populate
```

### Error

```
# Copy the complete text of any errors received by the type checker(s).
``` PS C:\Users\abhat\Documents\Alz\PathMe> bio2bel_chebi populate
testttt ['Canonicalizer', 'DEFAULT_PRIORITY_LIST', 'RAW_DIRECTORY', '_ORDERING_TEXT', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'apps_main', 'aws_main', 'cache', 'clean', 'click', 'database_main', 'get_priority_curie', 'get_writer', 'has_nomenclature_plugin', 'humanize', 'itemgetter', 'iter_cached_obo', 'iter_nomenclature_plugins', 'logger', 'logging', 'lookup', 'ls', 'main', 'os', 'prioritize', 'recurify', 'remap_file_stream', 'remapping', 'sys', 'tabulate', 'verbose_option']Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\abhat\Documents\Alz\.venv\Scripts\bio2bel_chebi.exe\__main__.py", line 4, in <module>
  File "c:\Users\abhat\Documents\Alz\.venv\Lib\site-packages\bio2bel_chebi\__init__.py", line 41, in <module>
    from .manager import *
  File "c:\Users\abhat\Documents\Alz\.venv\Lib\site-packages\bio2bel_chebi\manager.py", line 13, in <module>
    from bio2bel import AbstractManager
  File "c:\Users\abhat\Documents\Alz\.venv\Lib\site-packages\bio2bel\__init__.py", line 45, in <module>
    from .manager import AbstractManager, get_bio2bel_manager_classes  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\abhat\Documents\Alz\.venv\Lib\site-packages\bio2bel\manager\__init__.py", line 5, in <module>
    from .abstract_manager import AbstractManager, get_bio2bel_manager_classes
  File "c:\Users\abhat\Documents\Alz\.venv\Lib\site-packages\bio2bel\manager\abstract_manager.py", line 16, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'
PS C:\Users\abhat\Documents\Alz\PathMe> 

### Versions

- OS:
- Python:
- SQLAlchemy:
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc):


### Additional context

_No response_

**Comment by CaselIT** [comment]
Hi,

That module was never public and it's no longer available.
It's likely that the 3rd party library you are using needs to be updated or you sqlalchemy version needs to be downgraded
