### ISSUE TITLE
pool_pre_ping fails to reconnect on psycopg2 "SSL SYSCALL error: Success"

### ISSUE THREAD

**Issue by dhirving** [sqlalchemy/sqlalchemy#11522]
### Describe the bug

When a psycopg2 SSL connection to Postgres terminates abnormally, the error message returned by libpq will be sometimes be `SSL SYSCALL error: Success`.  This is a [known issue with OpenSSL 1](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html#BUGS), and anecdotally we still see it with recent versions of OpenSSL 3 on Linux when misbehaving network equipment causes the connection to terminate unexpectedly.  [According to the OpenSSL documentation](https://www.openssl.org/docs/man3.3/man3/SSL_get_error.html#SSL_ERROR_SYSCALL), any SSL_ERROR_SYSCALL is non-recoverable.

We are using `pool_pre_ping` to verify connections prior to check-out.  However, when a connection has failed with this error, no reconnect is attempted because this error is not [in the list of exceptions that are considered a "disconnect" event.](https://github.com/sqlalchemy/sqlalchemy/blob/2607262110bdc5c5dc96fc19ddca895a15a58e4e/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L865).  We are attempting to use `pool_pre_ping` to work around an issue where a firewall between our service and the database will silently drop connections that have been idle for some time, so the desired behavior would be for it to re-connect when the ping fails, instead of throwing an exception.

### SQLAlchemy Version in Use

2.0.25

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Postgres 13

### Python Version

3.12

### Operating system

Linux

### To Reproduce

```python
uri = "postgresql://..."
engine = sqlalchemy.engine.create_engine(uri, pool_pre_ping=True)
with engine.connect() as connection:
    connection.execute(...)

# Wait around for a while until misbehaving network equipment
# abnormally terminates the idle connection...

with engine.connect() as connection: # exception raised when pinging connection here
    ...
```

### Error

```
Traceback (most recent call last):
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1368, in _checkout
    with util.safe_reraise():
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1306, in _checkout
    result = pool._dialect._do_ping_w_event(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 709, in _do_ping_w_event
    return self.do_ping(dbapi_connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/_psycopg_common.py", line 180, in do_ping
    cursor.execute(self._dialect_specific_select_one)
psycopg2.DatabaseError: SSL SYSCALL error: Success
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/repos/rubintv_production/scripts/summit/LSSTComCamSim/runHeadNode.py", line 52, in <module>
    controller.run()
  File "/repos/rubintv_production/python/lsst/rubintv/production/processingControl.py", line 612, in run
    expRecord = self.getNewExposureAndDefineVisit()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repos/rubintv_production/python/lsst/rubintv/production/processingControl.py", line 426, in getNewExposureAndDefineVisit
    defineVisit(self.butler, expRecord)
  File "/repos/rubintv_production/python/lsst/rubintv/production/processingControl.py", line 146, in defineVisit
    ids = list(butler.registry.queryDimensionRecords("visit", dataId=expRecord.dataId))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/_registry_shim.py", line 377, in queryDimensionRecords
    return self._registry.queryDimensionRecords(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/registry/sql_registry.py", line 2399, in queryDimensionRecords
    data_id = self._standardize_query_data_id_args(dataId, doomed_by=doomed_by, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/registry/sql_registry.py", line 1902, in _standardize_query_data_id_args
    return self.expandDataId(data_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/registry/sql_registry.py", line 1584, in expandDataId
    record = self._managers.dimensions.fetch_one(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/registry/dimensions/static.py", line 311, in fetch_one
    with self._db.query(sql) as results:
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-8.0.0/Linux64/daf_butler/g2aa77f3748+c91288422c/python/lsst/daf/butler/registry/interfaces/_database.py", line 1863, in query
    connection = self._engine.connect()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1368, in _checkout
    with util.safe_reraise():
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1306, in _checkout
    result = pool._dialect._do_ping_w_event(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 709, in _do_ping_w_event
    return self.do_ping(dbapi_connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/_psycopg_common.py", line 180, in do_ping
    cursor.execute(self._dialect_specific_select_one)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: Success
(Background on this error at: https://sqlalche.me/e/20/4xp6)
``` 

### Additional context

We are tracking this issue for [our project](https://github.com/lsst/daf_butler) here: https://rubinobs.atlassian.net/browse/DM-44939

**Comment by dhirving** [comment]
Opened PR #11523 as a possible solution to this issue.  The last time a similar problem came up in #5387, the preference was to keep the scope of the change narrow by adding just the one error message instead of extending it to cover all SSL SYSCALL errors.

**Comment by CaselIT** [comment]
Thanks for reporting.

**Comment by sqla-tester** [comment]
**David H. Irving** has proposed a fix for this issue in the **main** branch:

**Handle "SSL SYSCALL error: Success" in psycopg2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5340

**Comment by sqla-tester** [comment]
**David H. Irving** has proposed a fix for this issue in the **rel_2_0** branch:

**Handle "SSL SYSCALL error: Success" in psycopg2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5405
