### ISSUE TITLE
pyodbc integrity error not wrapped by sqlalchemy during bulk inserts

### ISSUE THREAD

**Issue by winwinashwin** [sqlalchemy/sqlalchemy#11532]
### Describe the bug

During a bulk insert, integrity error raised by pyodbc is not wrapped by sqlalchemy exceptions.

**Database service**
```yaml
version: '3.0'
services:
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql_1433
    environment:
      MSSQL_SA_PASSWORD: sqla123
      ACCEPT_EULA: N
    ports:
      - 1433:1433
    volumes:
      - db_mssql:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U $DB_USER -P $SA_PASSWORD -Q 'select 1' -b -o /dev/null
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  db_mssql:
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://sqlalche.me/e/20/gkpj

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

MSSQL 2017

### Python Version

3.8.18

### Operating system

Ubuntu 22.04 LTS in WSL

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import DeclarativeBase, sessionmaker


engine = create_engine(
    "mssql+pyodbc://sa:sqla123@localhost:1433/test_db?driver=ODBC+Driver+17+for+SQL+Server"
)


class Base(DeclarativeBase):
    pass


class Author(Base):
    __tablename__ = "author"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), unique=True)


Base.metadata.create_all(engine)

factory = sessionmaker(bind=engine)
session = factory()

author1 = Author(name="rowling")
session.add(author1)
# session.flush()  # Not flushing now to trigger bulk insert

author2 = Author(name="rowling")
session.add(author2)

try:
    session.flush()

except IntegrityError as err:
    print("ERROR IS CAUGHT")
    print(type(err), str(err))
    raise

except Exception as err:
    print("ERROR NOT CAUGHT")
    print(type(err), str(err))
    raise
```

### Error

```
ERROR NOT CAUGHT
<class 'pyodbc.IntegrityError'> ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__author__72E12F1B836EC3EE'. Cannot insert duplicate key in object 'dbo.author'. The duplicate key value is (rowling). (2627) (SQLFetch)")
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    session.flush()
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1143, in _emit_insert_statements
    result = connection.execute(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_insertmany_context(dialect, context)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2033, in _exec_insertmany_context
    for imv_batch in dialect._deliver_insertmanyvalues_batches(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 816, in _deliver_insertmanyvalues_batches
    rows = context.fetchall_for_returning(cursor)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1738, in fetchall_for_returning
    return cursor.fetchall()
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__author__72E12F1B836EC3EE'. Cannot insert duplicate key in object 'dbo.author'. The duplicate key value is (rowling). (2627) (SQLFetch)")
``` 

### Additional context

With the intermediate flush, the db-api error is wrapped as expected by sqlalchemy.

Example
```python
from __future__ import annotations

from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import DeclarativeBase, sessionmaker


engine = create_engine(
    "mssql+pyodbc://sa:sqla123@localhost:1433/test_db?driver=ODBC+Driver+17+for+SQL+Server"
)


class Base(DeclarativeBase):
    pass


class Author(Base):
    __tablename__ = "author"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), unique=True)


Base.metadata.create_all(engine)

factory = sessionmaker(bind=engine)
session = factory()

author1 = Author(name="rowling")
session.add(author1)
session.flush()

author2 = Author(name="rowling")
session.add(author2)

try:
    session.flush()

except IntegrityError as err:
    print("ERROR IS CAUGHT")
    print(type(err), str(err))
    raise

except Exception as err:
    print("ERROR NOT CAUGHT")
    print(type(err), str(err))
    raise
```

Traceback
```
ERROR IS CAUGHT
<class 'sqlalchemy.exc.IntegrityError'> (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__author__72E12F1B836EC3EE'. Cannot insert duplicate key in object 'dbo.author'. The duplicate key value is (rowling). (2627) (SQLExecDirectW)")
[SQL: INSERT INTO author (name) OUTPUT inserted.id VALUES (?)]
[parameters: ('rowling',)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__author__72E12F1B836EC3EE'. Cannot insert duplicate key in object 'dbo.author'. The duplicate key value is (rowling). (2627) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    session.flush()
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ashwin/github.com/corridor-platforms/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__author__72E12F1B836EC3EE'. Cannot insert duplicate key in object 'dbo.author'. The duplicate key value is (rowling). (2627) (SQLExecDirectW)")
[SQL: INSERT INTO author (name) OUTPUT inserted.id VALUES (?)]
[parameters: ('rowling',)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
The re-raise logic is completely missing from https://github.com/sqlalchemy/sqlalchemy/blob/da9c87306dee45e8e25fe651c0c8d3623b210fdc/lib/sqlalchemy/engine/base.py#L2031-L2037

**Comment by zzzeek** [comment]
how strange it raises in the fetch?    I've struggled to find test cases where drivers raise in the fetch in other areas.

anyway pretty easy fix thanks for reporting

**Comment by CaselIT** [comment]
indeed it's very strange, since the exception is of the insert.
But considering other fun features of pyodbc it kinda does not surprise me https://github.com/sqlalchemy/sqlalchemy/discussions/11444#discussioncomment-9817498

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**handle DBAPI error for fetchall()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5388

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**handle DBAPI error for fetchall()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5389
