### ISSUE TITLE
(2003, "Can't connect to MySQL server on '2018A1@192.168.1.206' ([Errno 8] nodename nor servname provided, or not known)")

### ISSUE THREAD

**Issue by cunzhang521** [sqlalchemy/sqlalchemy#11615]
### Describe the bug

from sqlalchemy import create_engine, text

engine_str = 'mysql+pymysql://root:sdai@2018A1@192.168.1.206:50012/sd_data?charset=utf8'

engine = create_engine(engine_str)

with engine.connect() as conn:
    result = conn.execute(text("select ts_code from tu_stock_basic limit 10"))
    for row in result:
        print("ts_code:" + row.ts_code)

# sdai@2018A1 special '@' char problem

### SQLAlchemy Version in Use

2.0.31

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

mysql8

### Python Version

3.9.6

### Operating system

OSX,Linux

### To Reproduce

```python
from sqlalchemy import create_engine, text

engine_str = 'mysql+pymysql://root:sdai@2018A1@192.168.1.206:50012/sd_data?charset=utf8'

engine = create_engine(engine_str)

with engine.connect() as conn:
    result = conn.execute(text("select ts_code from tu_stock_basic limit 10"))
    for row in result:
        print("ts_code:" + row.ts_code)
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 
Traceback (most recent call last):
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/pymysql/connections.py", line 644, in connect
    sock = socket.create_connection(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '2018A1@192.168.1.206' ([Errno 8] nodename nor servname provided, or not known)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liuzhicun/PycharmProjects/sync_data/TuShare/test001.py", line 11, in <module>
    with engine.connect() as conn:
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/Users/liuzhicun/PycharmProjects/sync_data/venv/lib/python3.9/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '2018A1@192.168.1.206' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by zzzeek** [comment]
hi 

please read: https://docs.sqlalchemy.org/en/20/core/engines.html#escaping-special-characters-such-as-signs-in-passwords

thanks!

**Comment by Lyndon-prequel** [comment]
Recently ran into this issue too.  To make it easier for others to figure out if they're affected, I created a common reliability enumeration (CRE). You can preview the rule [here](https://play.prequel.dev/?data=EwBmFYFoQFm8AqwDMAuG5XgGwDoCMKG2AWgAQCiASlQPJVkDOAjgDYCGrAxgBYCmAWwCeuPgDsA5gEsxfXACN2jORUky%2BZAMIB7AK6sAJmTHaALmQAO7AE7Ky1gGZd8AdmQAOMgFUqAGTIO1toCTKbWMhJkAOQW2oymEtZ8LKyoAPRpusrWqFYAAoyMAO7a1gZ5BvKiAB7sAhasclzBWDDIwGnClVEAUAjW7Fx8ilwA1mQAFAJx5klDYuZcnKxkHPEAlKg9ZGQAYlKNZABEuKdHADSr6mSnuJcyN6fbO2Ti0rJkALxkXEnspnwAPpvdQTI6xeKJZJsdKZbK5dgFYqlcqVGp1BpNFrgNodLryI7rZ77Q4nU4pTi8QRCNIg2RpX58f5yCxCC5XD63e5iH5-AHAtSyZ47AZSOx8apcXAAQWsEl0AnEpgo1iC1jBOn0RhM5istg0jmcbk8Pn8gWCoXCkmiAFJGFEjmQbWRdNZWESKdx%2BMIalLZfLFQsVWrUFo9IZjGZLDY7IbXB5vH4AkEQvErZEYjMoSlYVk%2BDl8oUSmUKlUJRjGrhmgJWu1OkJukA&rule=E4VwNgpgzgXAUAWgAQGNgXkrSCWATGJAYQCUBRBAJgAZKBWBa6gZmrmySggDcJgcALgE9CldtgGDIhAMoBFADIBBMCgAWEALZDU6AIYCIAfQgA7AOY5TEJADM9OMFCQB3DaaQAHPVCguA9sB4qP6mAg6mzlCeECg4emCoanrAeiiGwM5gOADWNgAC4lgoBhDmgSJIgZoInsD%2BAEaQmkVIeiACaoGEAAroAI4gEGCteNBoOJ6SoYQAPkitWMjyyqoa2m2entkl05FIIFBW5kgABmgQpSYWVhAAFACUp0iaejr2jkgC-iGm1ulfH56JB4Ax6Bo%2BGw4WxfDQHLjAUx6TQ2QJeHx%2BQLBFChcJWKIxOIJJIpNIZZx3CAAOnMVIANGd8qcGacYMyzgB6dmnADEpweVKQABUNFwSal0nxnJpDgIkA0bABVEgKBBmHFjYJuMy4UwoMAgTW62E2UHhCFinF-WJ7TgCfgWQUAMQcBvQgKQ6v8YxNmiQkD0eGc33RmWOnuA9UyVWAupxkZtuggYzC8UShz05mprRKhwwSHmiyQy0JafFZKlxrN4MhSZTkgSFKgIHUbWcpyZD1%2Bth2cpcgjUSHQCN4wWVCnLkujeeCIbG2U0gnhfF1tn8DK6UAEDL0pmCnkCAkFAEkYSBrHrvcmGSsVOotDpF0cwnw6hABMG4Vb-ratw7zAyAZ4OGIYfJAwTtJ0ZiSLsOChDGLwJGuwAomOJDHlAVKtOE5iwEWyBQP0YAJPe2j4d2ODmCAqR7OR3i%2BAEQTkdRODkeMeieMc5HfjacGmOROSmP4LimAgOC%2BEMrSLpI5gGHxczkeOaqXj60SxGW6iklOzhWMuiLItAbR7uiDFYs42oeFaf4tpIFgmr8P58Xa-5YRwSxIE6aIQAAHsi2wQAy6DbGkNgds8-adGcACkAAs1DcmyrgDtFzBKNyXJJZFpxRZQTrsu%2BKCuW5yAqBkSKSLwYBCAyeb2cB6R8SkQgIFuQiQGcFxXGYljWHc45Up1hh3FSI0PE8mx1P4aSDiGejcP4%2BCIaYIDEn%2B4ZesBjrkTIECorYtg4ESiR4P4KCwEgagCAIniwByHInWdVKEcRawPlSgTmByZgcjQHLxhAX03NYmGXZoYA8uxnEWC1pYJAgmkSuSLUtmoCA%2BC1lGRGJon0ZiQRQK06C2Hw6rQJgxUXVdN0wHdlidCADQDf4mgcs9JHrEIrNEezD4cuJzbQAA-P0AC8xEKmAUWpTllCxdQADUOUAByBPL-hQcA8sI1AOUAJzy1Y8u44xeAy-L5GXddt33admFs692jvcAn3fb9-2Az10BUqD4OQ8cMPqXDCMVpkyPqGjUAY%2BYWNWLUGImwTHAcdsh1yaEeFucWSBIiihD26RQhFlgvBhjMSAADxIJQVLUFSrBF78eLWMAAByBmEMnrQ4Jo3jpLIfDcIdNhbikAggJ4diutREBdz3ZIyP9hAAGxSYIlFp6YC%2BBPmYgcEFh7nQAjIf4gouE1bk1gORWAQXgDEMIwcPghB0AAQgAmmQEKcSAcgyIqlAlAAC9-BCjICQAQh8ABqrRkhQDUIQZgAAtAAsuYMgmgFDMG4Iqd%2B789wQAABK2EVAAEWAKQqBpgyBChILrNQAApCAio6DAGYN5WwUBX5yAOgAcSXonbAWZTCEBPlgUA0hWhcAEJfbAPBoKyI4FAfw1EUD5guFSMA-haT5w5kWV4Ah1CKOwMgdAWZvKEAAORUgAFS6Lej5QqShnYgBRGEMgkZujEBUWAYIQk5TeEyDYYAtgUCHwAOzMCVkgccdh6h%2BjWo6GxligA) or run it against your logs [here](https://github.com/prequel-dev/preq).
