### ISSUE TITLE
SQLITE: SQLiteDialect.get_check_constraints incorrectly reflects multiline check constraints

### ISSUE THREAD

**Issue by Student1-vFinance** [sqlalchemy/sqlalchemy#11677]
### Describe the bug

The `get_check_constraints` method of SQLiteDialect, does not correctly handle multi line CHECK constraints in SQLAlchemy reflection. When performing a alembic batch_op for example, multi line check constraints will not be or wrongly reflected and can result in SQL errors.

### SQLAlchemy Version in Use

1.3.18

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.8.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, CheckConstraint
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Example(Base):
    __tablename__ = 'example'
    id = Column(Integer, primary_key=True)
    value = Column(Integer)

    __table_args__ = (
        CheckConstraint("""((value > 0) AND
             (value < 100))"""),
    )


# Create an in-memory SQLite database and create the table
engine = create_engine('sqlite:///:memory:')
Base.metadata.create_all(engine)

# Reflect the metadata to get the table object
metadata = MetaData()
metadata.reflect(bind=engine)
example_table = Table('example', metadata, autoload_with=engine)

# Print the CheckConstraints before deletion
print("Constraints before deletion:")
for constraint in example_table.constraints:
    if isinstance(constraint, CheckConstraint):
        print(f"CheckConstraint: {constraint.sqltext}")

# Drop the existing table
Base.metadata.drop_all(engine)

# Recreate the table based on reflected metadata
metadata.create_all(engine)
```

### Error

```
Traceback (most recent call last):
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: incomplete input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/student1/vortex-workspace/vfinance/src/tmp.py", line 37, in <module>
    metadata.create_all(engine)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/schema.py", line 4546, in create_all
    bind._run_visitor(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 2098, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1657, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
    self.traverse_single(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1071, in _execute_ddl
    ret = self._execute_context(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/home/student1/vortex-workspace/vfinance/src/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) incomplete input
[SQL: 
CREATE TABLE example (
	id INTEGER NOT NULL, 
	value INTEGER, 
	PRIMARY KEY (id), 
	CHECK (((value > 0)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
python interpreter exited with an exception
``` 

### Additional context

The solution to this problem is editing the regex to match check constraints:

```py
@reflection.cache
def get_check_constraints(self, connection, table_name, schema=None, **kw):
    table_data = self._get_table_sql(
        connection, table_name, schema=schema, **kw
    )
    if not table_data:
        return []

    CHECK_PATTERN = r"(?:CONSTRAINT (\w+) +)?" r"CHECK *\( *((.|\n)+?) *\)(, ?\n|\n) *" # new
    check_constraints = []
    # NOTE: we aren't using re.S here because we actually are
    # taking advantage of each CHECK constraint being all on one
    # line in the table definition in order to delineate. This
    # necessarily makes assumptions as to how the CREATE TABLE
    # was emitted.
    for match in re.finditer(CHECK_PATTERN, table_data, re.I):
        check_constraints.append(
            {"sqltext": match.group(2), "name": match.group(1)}
        )

    return check_constraints
```

https://github.com/sqlalchemy/sqlalchemy/blob/881be0a21633b3fee101cb34cc611904b8cba618/lib/sqlalchemy/dialects/sqlite/base.py#L2620C1-L2620C77

This line is not changed in the latest version

**Comment by zzzeek** [comment]
please provide PRs against the main branch if you plan to submit this, thanks!

**Comment by Student1-vFinance** [comment]
I openend a PR to fix this issue https://github.com/sqlalchemy/sqlalchemy/pull/11678

**Comment by sqla-tester** [comment]
**Jeff Horemans** has proposed a fix for this issue in the **main** branch:

**Reflect broader range of check constraints for SQLite.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5447

**Comment by sqla-tester** [comment]
**Jeff Horemans** has proposed a fix for this issue in the **rel_2_0** branch:

**Reflect broader range of check constraints for SQLite.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5471

**Comment by zzzeek** [comment]
we're having to revert here so this is a more long term issue
