### ISSUE TITLE
I am getting File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute pymssql._pymssql.OperationalError: (3971, b'The server failed to resume the transaction. Desc:4900000003.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

### ISSUE THREAD

**Issue by manmayaray** [sqlalchemy/sqlalchemy#11808]
### Describe the use case

File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (3971, b'The server failed to resume the transaction. Desc:4900000003.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

### Databases / Backends / Drivers targeted

mssql server 16, SQL Alchemy 1.4, Python 3.8 and pymysql 2.27 

### Example Use

Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (3971, b'The server failed to resume the transaction. Desc:4900000003.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 699, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (3971, b'The server failed to resume the transaction. Desc:4900000003.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/home/op_general/icici_medical_api_V2/portal/routes/file_upload/controller.py", line 150, in post
    header = APIHeader.query.filter_by(claim_header_id=header_id).first()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3210, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3289, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3259, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2106, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
  File "/home/op_general/miniconda/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 699, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) (3971, b'The server failed to resume the transaction. Desc:4900000003.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

### Additional context

rom flask_sqlalchemy import SQLAlchemy
from sqlalchemy.pool import QueuePool
from portal import create_app
db = SQLAlchemy()

def init_app(app):
    db_connection_string = app.config["DB_CONNECTION_STRING"]
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_BINDS'] = {
        'db': db_connection_string
    }
    app.config['SQLALCHEMY_DATABASE_URI']=db_connection_string
    app.config['SQLALCHEMY_POOL_RECYCLE'] = 299
    app.config['SQLALCHEMY_ENGINE_OPTIONS'] = {
        "poolclass": QueuePool,
        "pool_size": 1000,
        "pool_pre_ping": True,
        "pool_recycle": 300,
        "max_overflow": 1000,

**Comment by manmayaray** [comment]
I am really struggling for past few days with this
