### ISSUE TITLE
dict[x, y] vs Dict[x,y] in annotated map

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11814]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11812

seems to work with `typing.Dict` but not `dict`

<div type='discussions-op-text'>

<sup>Originally posted by **kreathon** August 31, 2024</sup>
It is very common ([see](https://stackoverflow.com/questions/75379948/what-is-correct-mapped-annotation-for-json-in-sqlalchemy-2-x-version)) to use `dict[str, Any]` as JSON type. 

However, it seems that this is currently not possible with `from __future__ import annotations` (without the example works perfectly fine).

Consider the following code example:

```
from __future__ import annotations

from typing import Any

import sqlalchemy as sa
from sqlalchemy import orm


class Base(orm.DeclarativeBase):
    type_annotation_map = {dict[str, Any]: sa.JSON}


class MyTable(Base):
    __tablename__ = "my_table"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    data: orm.Mapped[dict[str, Any]]

```

```
Traceback (most recent call last):
  File "/home/xxx/sqlalchemy/test.py", line 13, in <module>
    class MyTable(Base):
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/decl_api.py", line 836, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 572, in __init__
    self._extract_mappable_attributes()
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 1560, in _extract_mappable_attributes
    value.declarative_scan(
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/properties.py", line 709, in declarative_scan
    self._init_column_for_annotation(
  File "/home/xxx/sqlalchemy/lib/sqlalchemy/orm/properties.py", line 880, in _init_column_for_annotation
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not locate SQLAlchemy Core type for Python type dict['str', 'Any'] inside the 'data' attribute Mapped annotation

```
Environment:

Python 3.12.5
2e12ce74b0a4b78bb9268da2b84fc5c52d4299b3 (current master)

</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**re-process args for builtin generic types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5475

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**re-process args for builtin generic types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5476
