### ISSUE TITLE
Literal annotation is not detected on Python 3.8-3.9

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#11820]
### Describe the bug

Using `typing.Literal` in `type_annotation_map` raises an exception at import time on Python 3.8 and 3.9, but works on 3.10-3.12

### SQLAlchemy Version in Use

2.0.32

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.8,3.9

### Operating system

N/A

### To Reproduce

```python
from typing import Literal
from typing_extensions import TypeAlias

from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import types, create_engine


Shape: TypeAlias = Literal["CUBE", "SPHERE"]
shape = types.Enum("CUBE", "SPHERE", name="shape")


class Base(DeclarativeBase):
    type_annotation_map = {
        Shape: shape,
    }


class Model(Base):
    __tablename__ = "model"

    id: Mapped[int] = mapped_column(primary_key=True)
    shape: Mapped[Shape]
```

### Error

```
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/typing.py", line 230, in eval_expression
    annotation = eval(expression, cls_namespace, locals_)
  File "<string>", line 1, in <module>
NameError: name 'CUBE' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scratch_216.py", line 18, in <module>
    class Model(Base):
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 836, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 561, in __init__
    self._scan_attributes()
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1021, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1316, in _collect_annotation
    elem = de_stringify_annotation(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/typing.py", line 156, in de_stringify_annotation
    annotation = eval_expression(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/typing.py", line 234, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'CUBE'
``` 

### Additional context

SQLAlchemy seems to be doing an identity check for `typing_extensions.Literal` which is different than `typing.Literal`:

https://github.com/sqlalchemy/sqlalchemy/blob/f746fd78e303352d426a15c1f76ee835ce399d44/lib/sqlalchemy/util/typing.py#L359-L360

```python
>>> import typing as t
>>> import typing_extensions as te
>>> t.Literal is te.Literal
False
```

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **main** branch:

** Fix use of typing.Literal on Python 3.8 and 3.9** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5457

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix use of typing.Literal on Python 3.8 and 3.9** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5504
