### ISSUE TITLE
[psycopg3] MAC address comparison fails due to incorrect type casting

### ISSUE THREAD

**Issue by yoch** [sqlalchemy/sqlalchemy#12060]
### Describe the bug

When querying devices by MAC address using SQLAlchemy with PostgreSQL's `MACADDR8` type, an unexpected type casting causes comparison failures after migrating from psycopg2 to psycopg3.

### Schema

```py
from typing import Optional
from sqlalchemy import create_engine, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import MACADDR8

class Device(Base):
    __tablename__ = 'device'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[Optional[str]] = mapped_column(String)
    mac: Mapped[Optional[str]] = mapped_column(MACADDR8)
```

### Error
```
sqlalchemy.exc.ProgrammingError: (psycopg.errors.UndefinedFunction) operator does not exist: macaddr8 = character varying
LINE 3: WHERE device.mac = $1::VARCHAR
```

### Analysis
The error occurs because SQLAlchemy is explicitly casting the input parameter to VARCHAR when comparing against the MACADDR8 column. Apparently, this type casting doesn't occur with psycopg2.

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

psycopg-binary 3.2.3

### Database Vendor and Major Version

PostgreSQL 15.8

### Python Version

3.10.12

### Operating system

Linux

### To Reproduce

```python
engine = create_engine(f'postgresql+psycopg://{user}:{pwd}@localhost/mydb')
with Session(engine) as sess:
    device = sess.query(Device).filter_by(mac=macaddr).one_or_none()
```

### Error

```
Traceback (most recent call last):
  File "/home/ubuntu/api/mqtt_zigbee_listener.py", line 38, in handle_report
    device = sess.query(Device).filter_by(mac=macaddr).one_or_none()
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2754, in one_or_none
    return self._iter().one_or_none()  # type: ignore
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/api/env/lib/python3.10/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.ProgrammingError: (psycopg.errors.UndefinedFunction) operator does not exist: macaddr8 = character varying
LINE 3: WHERE device.mac = $1::VARCHAR
                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT device.id AS device_id, device.model AS device_model, device.name AS device_name, device.mac AS device_mac, device.idgateway AS device_idgateway 
FROM device 
WHERE device.mac = %(mac_1)s::VARCHAR]
[parameters: {'mac_1': '0cae5ffffeb3decf'}]
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. This is very similar to https://github.com/sqlalchemy/sqlalchemy/issues/10096 so maybe the better option is to extend that fix to most types

**Comment by yoch** [comment]
I noticed in the source code that `String` is defined for `psycopg` with : https://github.com/sqlalchemy/sqlalchemy/blob/21ea01eebe0350ad1185c7288dca61f363ebd2fe/lib/sqlalchemy/dialects/postgresql/psycopg.py#L120-L121

When I change the `render_bind_cast` attribute to `False`, my code works as expected.

Could you clarify for me the purpose of this attribute and why it needs to be set to `True` ?

**Comment by CaselIT** [comment]
it's used with postgresql drivers that do server side variable binding. Postgresql is extremely picky about types, so to avoid requiring users to add type casts in most queries sqlalchemy will add the type casts.

The solution here is to instruct mac to render the correct type on the right side, like in the linked issue

**Comment by zzzeek** [comment]
psycopg and asyncpg both use prepared statements which in PostgreSQL more often than not requires placeholders include casts, so that the database knows how to prepare the statement, otherwise errors are raised.      we didnt have this problem with psycopg2.

for strings specifically, it's not clear what types this is helping with for psycopg, if i take the bind cast out, there are lots of failures but they are all reflection queries which we have control over.    but in any case it's best that individual datatypes that expect compared strings to be interpreted in a certain way send a coercion over for that string to be in the exact type wanted.

**Comment by yoch** [comment]
Thank you all for the responses, it's very clear.

**Comment by yoch** [comment]
As a workaround, I used `type_coerce` everywhere in my code : 

```python
device = sess.query(Device).filter_by(mac=type_coerce(macaddr, MACADDR8)).one_or_none()
```

**Comment by sqla-tester** [comment]
**Denis Laxalde** has proposed a fix for this issue in the **main** branch:

**Ensure PostgreSQL network address types are not cast as VARCHAR** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5781

**Comment by sqla-tester** [comment]
**Denis Laxalde** has proposed a fix for this issue in the **rel_2_0** branch:

**Ensure PostgreSQL network address types are not cast as VARCHAR** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5803
