### ISSUE TITLE
can't adapt type for enum in case()

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#12097]
### Describe the bug

I can't use an enum type as part of a `case()` without casting.

Looks very similar to https://github.com/sqlalchemy/sqlalchemy/issues/6515

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.11

### Operating system

macOS

### To Reproduce

```python
import enum

from sqlalchemy import case, create_engine, update, types as sqltypes
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker

Session = sessionmaker()


class Base(DeclarativeBase):
    pass


class State(enum.Enum):
    PENDING = enum.auto()
    RUNNING = enum.auto()
    CANCELLING = enum.auto()
    CANCELLED = enum.auto()
    
    
StateType = sqltypes.Enum(State)


class Job(Base):
    __tablename__ = "jobs"

    id: Mapped[int] = mapped_column(primary_key=True)
    state: Mapped[State] = mapped_column(StateType, server_default=State.PENDING.name)


def main(engine):
    with engine.connect() as conn:
        conn.execute(
            update(Job).values(
                state=case(
                    (
                        Job.state == State.PENDING,
                        State.CANCELLED,
                    ),
                    else_=State.CANCELLING,
                )
            )
        )


if __name__ == "__main__":
    engine = create_engine("postgresql:///issue12097", echo=True)
    Session.configure(bind=engine)
    Base.metadata.create_all(engine)
    try:
        main(engine)
    finally:
        Base.metadata.drop_all(engine)
```

### Error

```
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'State'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue12096.py", line 50, in <module>
    main(engine)
  File "issue12096.py", line 32, in main
    conn.execute(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'State'
[SQL: UPDATE jobs SET state=CASE WHEN (jobs.state = %(state_1)s) THEN %(param_1)s ELSE %(param_2)s END]
[parameters: {'state_1': 'PENDING', 'param_1': <State.CANCELLED: 4>, 'param_2': <State.CANCELLING: 3>}]
(Background on this error at: https://sqlalche.me/e/20/f405)
``` 

It works if I add casts:
```python
            update(Job).values(
                state=case(
                    (
                        Job.state == cast(State.PENDING, StateType),
                        cast(State.CANCELLED, StateType),
                    ),
                    else_=cast(State.CANCELLING, StateType),
                )
            )
```

### Additional context

mcve requires you to run `createdb issue12097` first.

**Comment by CaselIT** [comment]
Hi,

This seems like expected behaviour. Note that the cast here `Job.state == State.PENDING` is not needed.
You can use `literal(State.CANCELLED, StateType)` instead of casting too

**Comment by RazerM** [comment]
ok so this version works:

```
update(Job).values(
    state=case(
        (
            Job.state == State.PENDING,
            literal(State.CANCELLED, StateType),
        ),
        else_=cast(State.CANCELLING, StateType),
    )
)
```

> This seems like expected behaviour.

So I know that `select(State.PENDING)` wouldn't work and `select(literal(State.PENDING, StateType))` would, but I thought this update would work because it is part of `.values(state=...)`. E.g. `.values(state=State.PENDING)` works fine.

**Comment by CaselIT** [comment]
I think the main issue is the complexity. while `.values(state=<literal>)` is easy to hard-code to say that the literal takes the type from the column, doing the same for an arbitrary expression is not really possible at the moment, since that expression may have any number of literals, only some of which need to be given the type of the column.

This is complicated by the fact that the sqlalchemy enum datatype does not store the python enum class (IIRC) so it's not possible to do an hypothetical `isinstance(value, the_python_enum)`.

@zzzeek not sure if my analysis is correct

**Comment by zzzeek** [comment]
it's correct, the right-hand-side coercion is only when a python literal is passed.  when a SQL construct is sent, it already has a type.   i am not completely sure there's nowhere in SQLAlchemy where, if the type of that SQL construct is NullType as would be the case here, that we still coerce it, but I dont think there is.

**Comment by CaselIT** [comment]
so the proposal would be to run a coerce on the expression to find all the nulltype literals and assign to them the col type?

I guess it could work (at least in this case) but it may be expensive

**Comment by CaselIT** [comment]
that would need to take into consideration cast/typecast etc though. Overall it seems like something that may break in some exotic cases.

**Comment by zzzeek** [comment]
yah i dont want to do it

**Comment by CaselIT** [comment]
any place were we could document this? (maybe it already is?)

**Comment by zzzeek** [comment]
it would be such a minor little esoteric documentation that most people would never see, or if they did, they wouldn't understqand its significance

**Comment by CaselIT** [comment]
not sure if there is anything left to do here then

**Comment by CaselIT** [comment]
In second thought we can probably document this better on the enum class. Let's reopen to do that

**Comment by laurentS** [comment]
Coming here from [this question](https://github.com/sqlalchemy/sqlalchemy/discussions/12115) I am confused by the following:

This works:
```python
case(
    (
        Job.state == State.PENDING,
        literal(State.CANCELLED, StateType),
    ),
    else_=cast(State.CANCELLING, StateType),
)
```
but this version (note the difference on the `else_` line) causes an error:
```python
case(
    (
        Job.state == State.PENDING,
        literal(State.CANCELLED, StateType),
    ),
    else_=literal(State.CANCELLING, StateType),
)
```

```
psycopg2.errors.DatatypeMismatch: column "state" is of type state but expression is of type text
LINE 1: UPDATE jobs SET state=CASE WHEN (jobs.state = CAST('PENDING'...
                              ^
HINT:  You will need to rewrite or cast the expression.
[traceback]
[SQL: UPDATE jobs SET state=CASE WHEN (jobs.state = CAST(%(param_1)s AS state)) THEN %(param_2)s ELSE %(param_3)s END]
[parameters: {'param_1': 'PENDING', 'param_2': 'CANCELLED', 'param_3': 'CANCELLING'}]
```

Why is the `else_` part treated differently from the rest of the whens? (both `cast` and `literal` work in the actual `whens` argument)

**Comment by CaselIT** [comment]
I think if you invert it you also get it working:

```py
case(
    (
        Job.state == State.PENDING,
        Cast(State.CANCELLED, StateType),
    ),
    else_=literal(State.CANCELLING, StateType),
)
```
I'm guessing that the db can figure out the type if there us one cast
