### ISSUE TITLE
Missing greenlet error with on_update attribute in SQLAlchemy 2.0.36

### ISSUE THREAD

**Issue by Leenamgyo** [sqlalchemy/sqlalchemy#12125]
### Describe the bug

I'm encountering a `Missing greenlet` error in SQLAlchemy 2.0.36 when using the `on_update` attribute on a column. It seems like a recent change might have introduced this bug. The error occurs during the following sequence:

1. Retrieve an object using `obj=session.get()`.
2. Execute an `UPDATE` statement via `session.execute()` that affects the retrieved object's `on_update` column.

**Expected behavior**
The `UPDATE` statement should execute successfully without raising a `Missing greenlet` error. The `on_update` functionality should work as expected, updating the column value accordingly.

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.9. 3.10

### Operating system

OSX 

### To Reproduce

```python
import asyncio
import time 

from sqlalchemy import Column, Integer, String, DateTime, func, text, select, update
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker, declarative_base

# Asynchronous engine and base setup
DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/test_db"

# Create asynchronous database engine
engine = create_async_engine(DATABASE_URL, echo=True)

# ORM Base class
Base = declarative_base()

# Asynchronous session maker
AsyncSessionLocal = sessionmaker(
    bind=engine, class_=AsyncSession
    # , expire_on_commit=False
)

# SQLAlchemy model definition
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), nullable=False)
    age = Column(Integer)
    created_at = Column(DateTime, nullable=False, default=func.now())
    updated_at = Column(DateTime, nullable=False, default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<User(id={self.id}, name={self.name}, age={self.age}, created_at={self.created_at}, updated_at={self.updated_at})>"

# Database initialization function
async def init_db():
    async with engine.begin() as conn:
        # Drop all tables and create them
        await conn.run_sync(Base.metadata.drop_all)        
        await conn.run_sync(Base.metadata.create_all)

        print("Database initialization complete")
    
# Function to add test data
async def add_sample_user(session: AsyncSession):
    user = User(name="Alice", age=25)
    session.add(user)
    print(f"User added: {user}")

async def update_user(session: AsyncSession, user_id: int, new_name: str, new_age: int):
    stmt = (
        update(User)
        .where(User.id == user_id)
        .values(name=new_name, age=new_age)
        # .execution_options(synchronize_session="fetch")
    )
    await session.execute(stmt)
    print(f"User updated: ID={user_id}, Name={new_name}, Age={new_age}")


# Main execution function
async def main():
    async with AsyncSessionLocal() as session:
        # Inject the same session
        await init_db()
        await add_sample_user(session)
        print("\n--- Initial user retrieval ---")
        user = await session.get(User, 1)

        # After executing the logic, an unusual value was assigned to `user.updated_at`.
        await update_user(
            session, 
            user_id=1, 
            new_name="Bob", 
            new_age=30
        )

        print("\n--- User retrieval after update ---")
        user = await session.get(User, 1)

        # Error: Missing greenlet. When assigning a variable with get and 
        # then performing an update, the on_update field is assigned a 'missing greenlet' value, 
        # causing an error.
        update_at = user.updated_at
        return user 


# Run the asyncio event loop
if __name__ == "__main__":
    asyncio.run(main())
```

### Error

Traceback (most recent call last):
  File "/Users/macbookairm1/.pyenv/versions/3.11.4/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/.pyenv/versions/3.11.4/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/Users/macbookairm1/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/Users/macbookairm1/Documents/projects/git/blog/python/sqlalchemy/main.py", line 86, in <module>
    asyncio.run(main())
  File "/Users/macbookairm1/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/.pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/blog/python/sqlalchemy/main.py", line 80, in main
    update_at = user.updated_at
                ^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
    result = load_on_ident(
             ^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
    return load_on_pk_identity(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/Users/macbookairm1/Documents/projects/git/fastapi-test/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 123, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)

### Additional context

* I have verified that the `greenlet` library is installed correctly.
* This code worked without errors in versions 2.0.15 and 2.0.35

**Comment by zzzeek** [comment]
likely #11917.   the UPDATE here should have a RETURNING that is fetching that column otherwise I dont see how #11917 works here (it's expiring the value for now).   I would guess that prior to 2.0.36 you were getting a stale value

**Comment by zzzeek** [comment]
whether or not the behavior is planned here it should not be adding a new expiration when RETURNING is available it should be fetching it

**Comment by zzzeek** [comment]
OK, back to the same comment which is that we currently dont synchrnoize server defaults with RETURNING

```py
        if synchronize_session == "fetch" and can_use_returning:
            use_supplemental_cols = True
            # NOTE: we might want to RETURNING the actual columns to be
            # synchronized also.  however this is complicated and difficult
            # to align against the behavior of "evaluate".  Additionally,
            # in a large number (if not the majority) of cases, we have the
            # "evaluate" answer, usually a fixed value, in memory already and
            # there's no need to re-fetch the same value
            # over and over again.   so perhaps if it could be RETURNING just
            # the elements that were based on a SQL expression and not
            # a constant.   For now it doesn't quite seem worth it
            new_stmt = new_stmt.return_defaults(*new_stmt.table.primary_key)

```

so this might be a wontfix

@Leenamgyo the value of `.updated_at` in older versions is stale.   why do you not want it to be refreshed with the correct data?
