### ISSUE TITLE
all PG domain reflection tests failing for pg17

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#12174]
im not able to see what's happening here, pg_getconstraintdef on pg17 is having some internal issue

```
test/dialect/postgresql/test_reflection.py::DomainReflectionTest_postgresql+pg8000_17_2::test_array_domain_is_reflected INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:CREATE SCHEMA IF NOT EXISTS "SomeSchema"
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN testdomain INTEGER NOT NULL DEFAULT 42
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN test_schema.testdomain INTEGER DEFAULT 0
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TYPE testtype AS ENUM ('test')
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN enumdomain AS testtype
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN arraydomain AS INTEGER[]
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN arraydomain_2d AS INTEGER[][]
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN arraydomain_3d AS  INTEGER[][][]
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN "SomeSchema"."Quoted.Domain" INTEGER DEFAULT 0
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN nullable_domain AS TEXT COLLATE "C" CHECK (VALUE IN('FOO', 'BAR'))
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN not_nullable_domain AS TEXT NOT NULL
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE DOMAIN my_int AS int CONSTRAINT b_my_int_one CHECK (VALUE > 1) CONSTRAINT a_my_int_two CHECK (VALUE < 42) CHECK(VALUE != 22)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE testtable (question integer, answer testdomain)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE test_schema.testtable(question integer, answer test_schema.testdomain, anything integer)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE crosschema (question integer, answer test_schema.testdomain)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE enum_test (id integer, data enumdomain)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE array_test (id integer, datas arraydomain, datass arraydomain_2d, datasss arraydomain_3d)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE quote_test (id integer, data "SomeSchema"."Quoted.Domain")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:CREATE TABLE nullable_domain_test (not_nullable_domain_col nullable_domain not null,nullable_local not_nullable_domain)
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_attribute.attname AS name, pg_catalog.format_type(pg_catalog.pg_attribute.atttypid, pg_catalog.pg_attribute.atttypmod) AS format_type, (SELECT pg_catalog.pg_get_expr(pg_catalog.pg_attrdef.adbin, pg_catalog.pg_attrdef.adrelid) AS pg_get_expr_1 
FROM pg_catalog.pg_attrdef 
WHERE pg_catalog.pg_attrdef.adrelid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attrdef.adnum = pg_catalog.pg_attribute.attnum AND pg_catalog.pg_attribute.atthasdef) AS "default", pg_catalog.pg_attribute.attnotnull AS not_null, pg_catalog.pg_class.relname AS table_name, pg_catalog.pg_description.description AS comment, pg_catalog.pg_attribute.attgenerated AS generated, (SELECT json_build_object(%s::VARCHAR, pg_catalog.pg_attribute.attidentity = %s::VARCHAR, %s::VARCHAR, pg_catalog.pg_sequence.seqstart, %s::VARCHAR, pg_catalog.pg_sequence.seqincrement, %s::VARCHAR, pg_catalog.pg_sequence.seqmin, %s::VARCHAR, pg_catalog.pg_sequence.seqmax, %s::VARCHAR, pg_catalog.pg_sequence.seqcache, %s::VARCHAR, pg_catalog.pg_sequence.seqcycle) AS json_build_object_1 
FROM pg_catalog.pg_sequence 
WHERE pg_catalog.pg_attribute.attidentity != %s::VARCHAR AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(pg_catalog.pg_attribute.attrelid AS REGCLASS) AS TEXT), pg_catalog.pg_attribute.attname) AS REGCLASS) AS OID)) AS identity_options 
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_class.oid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attribute.attnum > %s::SMALLINT AND NOT pg_catalog.pg_attribute.attisdropped LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_description.objsubid = pg_catalog.pg_attribute.attnum JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %s::VARCHAR AND pg_catalog.pg_class.relname IN (%s::VARCHAR) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_attribute.attnum
INFO:sqlalchemy.engine.Engine:[generated in 0.00027s] ('always', 'a', 'start', 'increment', 'minvalue', 'maxvalue', 'cache', 'cycle', '', 0, 'r', 'p', 'f', 'v', 'm', 'pg_catalog', 'array_test')
DEBUG:sqlalchemy.engine.Engine:Col ('name', 'format_type', 'default', 'not_null', 'table_name', 'comment', 'generated', 'identity_options')
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname 
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %s::BOOLEAN)) AS condefs, array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != %s::INTEGER GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = %s::VARCHAR ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
INFO:sqlalchemy.engine.Engine:[generated in 0.00015s] (True, 0, 'd')
FAILEDINFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:select pid, state, wait_event_type, query from pg_stat_activity where usename=current_user and datname=current_database() and state='idle in transaction' and pid != pg_backend_pid()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('pid', 'state', 'wait_event_type', 'query')
INFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:DROP TABLE testtable
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE test_schema.testtable
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE crosschema
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE quote_test
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN testdomain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN test_schema.testdomain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE enum_test
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN enumdomain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TYPE testtype
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE array_test
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN arraydomain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN arraydomain_2d
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN arraydomain_3d
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN "SomeSchema"."Quoted.Domain"
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP SCHEMA "SomeSchema"
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP TABLE nullable_domain_test
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN nullable_domain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN not_nullable_domain
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:DROP DOMAIN my_int
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT


====================================================================================== FAILURES ======================================================================================
_____________________________________________________ DomainReflectionTest_postgresql+pg8000_17_2.test_array_domain_is_reflected _____________________________________________________
Traceback (most recent call last):
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pg8000/legacy.py", line 254, in execute
    self._context = self._c.execute_unnamed(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pg8000/core.py", line 707, in execute_unnamed
    self.handle_messages(context)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pg8000/core.py", line 827, in handle_messages
    raise context.error
pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'V': 'ERROR', 'C': 'XX000', 'M': 'invalid constraint type "n"', 'F': 'ruleutils.c', 'L': '2547', 'R': 'pg_get_constraintdef_worker'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pg8000/legacy.py", line 281, in execute
    raise cls(msg)
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': 'XX000', 'M': 'invalid constraint type "n"', 'F': 'ruleutils.c', 'L': '2547', 'R': 'pg_get_constraintdef_worker'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/python.py", line 1769, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/.venv3/lib64/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/test/dialect/postgresql/test_reflection.py", line 531, in test_array_domain_is_reflected
    table = Table("array_test", metadata, autoload_with=connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __new__
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 428, in __new__
    return cls._new(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 482, in _new
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 478, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 860, in __init__
    self._autoload(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 892, in _autoload
    conn_insp.reflect_table(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py", line 1536, in reflect_table
    _reflect_info = self._get_reflection_info(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py", line 2016, in _get_reflection_info
    columns=run(
            ^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py", line 2002, in run
    res = meth(filter_names=_fn, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py", line 932, in get_multi_columns
    self.dialect.get_multi_columns(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py", line 3714, in get_multi_columns
    for d in self._load_domains(
             ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _load_domains
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py", line 106, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py", line 4996, in _load_domains
    result = connection.execute(self._domain_query(schema))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/classic/.venv3/lib64/python3.12/site-packages/pg8000/legacy.py", line 281, in execute
    raise cls(msg)
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': 'XX000', 'M': 'invalid constraint type "n"', 'F': 'ruleutils.c', 'L': '2547', 'R': 'pg_get_constraintdef_worker'}
[SQL: SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname 
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %s::BOOLEAN)) AS condefs, array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != %s::INTEGER GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = %s::VARCHAR ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname]
[parameters: (True, 0, 'd')]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by zzzeek** [comment]
this error is in the PostgreSQL database directly:

```
test=> CREATE SCHEMA IF NOT EXISTS "SomeSchema";
CREATE DOMAIN testdomain INTEGER NOT NULL DEFAULT 42;
CREATE DOMAIN test_schema.testdomain INTEGER DEFAULT 0;
CREATE TYPE testtype AS ENUM ('test');
CREATE DOMAIN enumdomain AS testtype;
CREATE DOMAIN arraydomain AS INTEGER[];
CREATE DOMAIN arraydomain_2d AS INTEGER[][];
CREATE DOMAIN arraydomain_3d AS  INTEGER[][][];
CREATE DOMAIN "SomeSchema"."Quoted.Domain" INTEGER DEFAULT 0;
CREATE DOMAIN nullable_domain AS TEXT COLLATE "C" CHECK (VALUE IN('FOO', 'BAR'));
CREATE DOMAIN not_nullable_domain AS TEXT NOT NULL;
CREATE DOMAIN my_int AS int CONSTRAINT b_my_int_one CHECK (VALUE > 1) CONSTRAINT a_my_int_two CHECK (VALUE < 42) CHECK(VALUE != 22);
CREATE TABLE testtable (question integer, answer testdomain);
CREATE TABLE test_schema.testtable(question integer, answer test_schema.testdomain, anything integer);
CREATE TABLE crosschema (question integer, answer test_schema.testdomain);
CREATE TABLE enum_test (id integer, data enumdomain);
CREATE TABLE array_test (id integer, datas arraydomain, datass arraydomain_2d, datasss arraydomain_3d);
CREATE TABLE quote_test (id integer, data "SomeSchema"."Quoted.Domain");
CREATE TABLE nullable_domain_test (not_nullable_domain_col nullable_domain not null,nullable_local not_nullable_domain);
CREATE SCHEMA
CREATE DOMAIN
CREATE DOMAIN
CREATE TYPE
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE DOMAIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
test=> SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, 
    pg_catalog.pg_type.typtypmod) AS attype, 
    NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", 
    pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, 
    domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname 
FROM pg_catalog.pg_type 
    JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace 
    LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid 
    LEFT OUTER JOIN 
        (SELECT pg_catalog.pg_constraint.contypid AS contypid, 
            array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, true)) AS condefs, 
            array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != 0 
GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = 'd' ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
test-> ;
ERROR:  invalid constraint type "n"

```

**Comment by zzzeek** [comment]
reduced:

```

CREATE DOMAIN not_nullable_domain AS TEXT NOT NULL;

SELECT 
    pg_catalog.pg_constraint.contypid AS contypid, 
    array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, true)) AS condefs, 
    array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != 0 
GROUP BY pg_catalog.pg_constraint.contypid


```

**Comment by zzzeek** [comment]
correction

```

CREATE DOMAIN not_nullable_domain AS TEXT NOT NULL;


SELECT 
    domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname 
FROM pg_catalog.pg_type 
    JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace 
    LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid 
    LEFT OUTER JOIN 
        (SELECT pg_catalog.pg_constraint.contypid AS contypid, 
            array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, true)) AS condefs, 
            array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != 0 
GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = 'd' ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname;
```

**Comment by zzzeek** [comment]
here's the thread

https://www.postgresql.org/message-id/a90f53c4-56f3-4b07-aefc-49afdc67dba6%40app.fastmail.com

**Comment by zzzeek** [comment]
it was fixed a few weeks ago https://git.postgresql.org/cgit/postgresql.git/commit/?h=REL_17_STABLE&id=6e793582bc663fb7652834170be8902b982b7bcb

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**modernize PG domain reflection test and skip for pg17.2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5625

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**modernize PG domain reflection test and skip for pg17.2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5626
