### ISSUE TITLE
composed unions in Mapped[] as used in new doc examples do not parse correctly with future annotations

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#12207]
I was concerned this was a regression introduced in a4e38d119913ca18462f2e9c6448c6e24d369df3 but this seems to have been there all along

you can work around this using newtype / type where the complex expression is not present in `Mapped[]`, but this is literally the example we have in the [new docs](https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#union-types-inside-the-type-map)

```py
from __future__ import annotations

from typing import Union

from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.schema import CreateTable

json_list_union = Union[list[int], list[str]]

class Base(DeclarativeBase):
    type_annotation_map = {
        json_list_union: postgresql.JSONB,
    }


class SomeClass(Base):
    __tablename__ = "some_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    list_col_pipe: Mapped[list[int] | list[str]]   # fails to parse
    list_col_union: Mapped[Union[list[int], list[str]]]  # fails to parse

print(CreateTable(SomeClass.__table__).compile(dialect=postgresql.dialect()))
```

```
Traceback (most recent call last):
  File "/usr/lib64/python3.12/typing.py", line 904, in __init__
    code = compile(arg_to_compile, '<string>', 'eval')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    int] | list[str
       ^
SyntaxError: unmatched ']'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 16, in <module>
    class SomeClass(Base):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_api.py", line 842, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 561, in __init__
    self._scan_attributes()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 1021, in _scan_attributes
    collected_annotation = self._collect_annotation(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 1303, in _collect_annotation
    extracted = _extract_mapped_subtype(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/util.py", line 2407, in _extract_mapped_subtype
    fixup_container_fwd_refs(annotated.__args__[0]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/typing.py", line 234, in fixup_container_fwd_refs
    ForwardRef(elem) if isinstance(elem, str) else elem
    ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/typing.py", line 906, in __init__
    raise SyntaxError(f"Forward reference must be an expression -- got {arg!r}")
SyntaxError: Forward reference must be an expression -- got 'int] | list[str'

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**further fixes for _cleanup_mapped_str_annotation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5643

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**further fixes for _cleanup_mapped_str_annotation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5644
