### ISSUE TITLE
load_only child column on polymorphic relationship

### ISSUE THREAD

**Issue by dima-starosud** [sqlalchemy/sqlalchemy#4400]
This is using sqlalchemy==1.2.14.
Following code snippet fails with en error. Did I misuse query options again?

```
from sqlalchemy import Column, ForeignKey, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Query, aliased, contains_eager, relationship
from sqlalchemy.pool import NullPool

engine = create_engine('postgresql://***', poolclass=NullPool)
connection = engine.connect()
connection.begin()

Base = declarative_base()


class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    type = Column(String, nullable=False)
    __mapper_args__ = {'polymorphic_on': type}
    other_id = Column(Integer, ForeignKey('main.id'), nullable=False)


class Child1(Parent):
    __mapper_args__ = {'polymorphic_identity': 'child1'}
    ext = Column(String)


class Main(Base):
    __tablename__ = 'main'
    id = Column(Integer, primary_key=True)
    parents = relationship(Parent)
    child1 = relationship(Child1)


Base.metadata.create_all(connection)

child1 = aliased(Child1)
q = Query(Main).outerjoin(child1, Main.child1).options(
    contains_eager(Main.child1.of_type(child1), alias=child1).load_only('ext')
)

print(q)
```

```
root@ac36af00d6f9:/service# python main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategy_options.py", line 194, in _generate_path
    attr = getattr(path.entity.class_, attr)
AttributeError: type object 'Parent' has no attribute 'ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 57, in <module>
    contains_eager(Main.child1.of_type(child1), alias=child1).load_only('ext')
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1449, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1468, in _options
    opt.process_query(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategy_options.py", line 151, in process_query
    self._process(query, True)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategy_options.py", line 484, in _process
    query._current_path, query._attributes, raiseerr)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategy_options.py", line 655, in _bind_loader
    loader.path, token, None, raiseerr):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategy_options.py", line 200, in _generate_path
    attr, path.entity)
sqlalchemy.exc.ArgumentError: Can't find property named 'ext' on the mapped entity Mapper|Parent|parent in this Query.
```

**Comment by zzzeek** [comment]
wow we are going to fix every bug ever in the loader options huh?   will look soon

**Comment by zzzeek** [comment]
as is usually the case sending the exact attribute resolves:
```

q = Query(Main).outerjoin(child1, Main.child1).options(
    contains_eager(Main.child1.of_type(child1), alias=child1).load_only(Child1.ext)
)

```
