### ISSUE TITLE
`self._connections[conn]` is being set even though it is `None`

### ISSUE THREAD

**Issue by pranav93** [sqlalchemy/sqlalchemy#4417]
Whenever I'm querying like this 
```python
user_obj = session.query(SuperUser).filter(SuperUser.id == user_id).first()
```
Sometimes I am getting this error, `TypeError: 'NoneType' object does not support item assignment`. It seems that, the `self._connections` is set to `None` sometimes (Tbh, there is no pattern to this).

Full traceback is,
```
Traceback (most recent call last):
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/pranav/projects/fusion-api/api/utils/exception/handler.py", line 18, in wrapped
    return fn(*args, **kwargs)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 101, in wrapper
    return fn(*args, **kwargs)
  File "/home/pranav/projects/fusion-api/api/utils/identity.py", line 46, in wrapped
    http_origin, *args, **kwargs)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/webargs/core.py", line 443, in wrapper
    return func(*args, **kwargs)
  File "/home/pranav/projects/fusion-api/api/utils/serialize.py", line 8, in wrapped
    response = fn(*args, **kwargs)
  File "/home/pranav/projects/fusion-api/api/utils/identity.py", line 60, in wrapped
    return fn(*args, **kwargs)
  File "/home/pranav/projects/fusion-api/api/resources/mappings/composite.py", line 136, in get
    grid, composite_rules, composite_mapping_attributes
  File "/home/pranav/projects/fusion-api/api/utils/transform/mappings/composite.py", line 32, in transform_composite_mapping_attributes
    composite_mapping_attribute.pop('modified_by'))
  File "/home/pranav/projects/fusion-api/api/functionality/user.py", line 8, in get_user_by_id
    user = get_superuser_by_id(user_id)
  File "/home/pranav/projects/fusion-api/api/functionality/superusers.py", line 18, in get_superuser_by_id
    user_obj = session.query(SuperUser).filter(SuperUser.id == user_id).first()
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
    close_with_result=True)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
    **kw
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1046, in connection
    execution_options=execution_options)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
    engine, execution_options)
  File "/home/pranav/.virtualenvs/fusion-api/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 422, in _connection_for_bind
    (conn, transaction, conn is not bind)
TypeError: 'NoneType' object does not support item assignment

```

atm, I am checking whether `self._connections` is `None` in `_connection_for_bind` function. I do not know whether it's correct approach. Something like,
```
self._connections = self._connections if self._connections else {}
```

**Comment by zzzeek** [comment]
the only way that could be happening is if your application is sharing the same `Session` object among multiple concurrent threads or greenlets.    The `._connections` attribute is set to `None` only when the `SessionTransaction` object is closed, and within the only method that does this, `session.transaction` is unset, so it is not possible for this to occur unless concurrent threads/greenlets are continuing to use the same `SessionTransaction`.

It's actually quite easy to reproduce with a threadsafe DBAPI (with a non-threadsafe API I get other errors first):

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
import time
import threading
import random


Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String(30))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.create_all(e)

s = Session(e)


def go():
    while True:
        s.query(A).all()
        time.sleep(random.random())
        s.close()

s.add(A())
s.commit()


threads = [threading.Thread(target=go) for i in range(50)]
for t in threads:
    t.start()


```

running this I get the same trace many times a second, and I don't even have to use greenlets (which tend to introduce concurrency races at a much higher rate than threads):

```

Exception in thread Thread-32:
Traceback (most recent call last):
  File "/opt/python-3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/python-3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 26, in go
    s.query(A).all()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2995, in all
    return list(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3147, in __iter__
    return self._execute_and_instances(context)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3168, in _execute_and_instances
    close_with_result=True)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3183, in _get_bind_args
    **kw
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3159, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 1046, in connection
    execution_options=execution_options)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind
    engine, execution_options)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 422, in _connection_for_bind
    (conn, transaction, conn is not bind)
TypeError: 'NoneType' object does not support item assignment

```


I would say it's very likely you need to review your Session creational patterns to ensure you have a unique Session per thread/greenlet with no concurrent access.

**Comment by zzzeek** [comment]
submitter will review session concurrency patterns and confirm this fixes the issue

**Comment by zzzeek** [comment]
hypothetically we could move the active assertion down until after the transaction has been opened, if we can determine why the race is most likely at this point and not earlier, best would be if we could assert in both places .  it's interesting that the race seems to only occur after the conn.begin() in _connection_for_bind



```diff

diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index b1993118dd..47b9832aab 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -418,8 +418,13 @@ class SessionTransaction(object):
         else:
             transaction = conn.begin()
 
-        self._connections[conn] = self._connections[conn.engine] = \
-            (conn, transaction, conn is not bind)
+        try:
+            self._connections[conn] = self._connections[conn.engine] = \
+                (conn, transaction, conn is not bind)
+        except TypeError:
+            # warn etc
+            raise
+
         self.session.dispatch.after_begin(self.session, self, conn)
         return conn
 

```

**Comment by pranav93** [comment]
I am using sqlalchemy sessionmaker with flask. 
My current code for creating session is,
```python
engine = create_engine(SQLALCHEMY_DATABASE_URI, echo=SQLALCHEMY_ECHO)
Session = sessionmaker(bind=engine)
session = Session()
```
I suppose the issue will go away, if I use scoped_session, it will take care of thread safety.
```python
engine = create_engine(SQLALCHEMY_DATABASE_URI, echo=SQLALCHEMY_ECHO)
Session = scoped_session(sessionmaker(bind=engine))
session = Session()
```
I am currently testing my app with second block of code.
