### ISSUE TITLE
SqlAlchemy DataError strangely crashes interactive console

### ISSUE THREAD

**Issue by gizmo93** [sqlalchemy/sqlalchemy#4418]
In our productive environment we notice some strange problems with DbAPI Exceptions reraised by SqlAlchemy causing python.exe to crash (with a negative error code).

Environment:

- OS: Windows 10 64 Bit
- Python: 3.5.5 and 3.7.1 64-Bit
- SqlAlchemy 1.2.15
- pyodbc 4.0.25 with ODBC Driver 17 for SQL Server on SQL Server 2017
- pandas 0.23.4

The problem occurs, if the database returns errors while executing insert statements, e.g. if you try to insert datetime values with too high precision or if you violate unique / primary key constraints.

Test table:
```
CREATE TABLE TestTable
(
	IntValue INT NOT NULL PRIMARY KEY,
	TooShortDatetimeValue DATETIME2(4) NULL,
	LongDatetimeValue DATETIME2(7) NULL,
	VeryShortDatetimeValue DATETIME2(0) NULL,
)
```

And try the following script in the interactive python console:

```
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine, event
import traceback

connection_string = 'mssql+pyodbc://localhost/Test?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)


# activate cursor.fast_executemany for sqlalchemy
# according to: https://bitbucket.org/zzzeek/sqlalchemy/issues/4158/pyodbc-sql-server-cursorfast_executemany
@event.listens_for(engine, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, parameters,
                                  context, executemany):
    if executemany:
        cursor.fast_executemany = True


sql = """
INSERT INTO TestTable (IntValue, TooShortDatetimeValue, LongDateTimeValue, VeryShortDatetimeValue) VALUES (?, ?, ?, ?)
"""

cols = ['IntValue', 'TooShortDatetimeValue', 'LongDateTimeValue', 'VeryShortDatetimeValue']
data = [
    [1, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [2, datetime.now(), datetime.now(), datetime.now().replace(microsecond=0)],
    [3, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [4, datetime.now().replace(microsecond=0), datetime.now(), datetime.now()],
]


df = pd.DataFrame([dict(zip(cols, entry)) for entry in data])
df.to_sql('TestTable', con=engine, if_exists='append', index=False)
```

It will cause the whole process to crash. 
Problem here is: We try to insert a too precise datetime value into a table and the SQL Server returns an error, which should pop up as an exception.

Inserting the same data directly while using pyodbc does not crash python.exe

If you wrap the df.to_sql part inside try: ... except Exception: pass it will not crash the console. But if you try to reraise the catched Exception it will crash the console, also if you try to print the ex, e.g. like this:
```
try:
    df = pd.DataFrame([dict(zip(cols, entry)) for entry in data])
    df.to_sql('TestTable', con=engine, if_exists='append', index=False)
except Exception:
    raise
```

or this:

```
try:
    df = pd.DataFrame([dict(zip(cols, entry)) for entry in data])
    df.to_sql('TestTable', con=engine, if_exists='append', index=False)
except Exception as ex:
    print(ex)
```

It's really strange and i can't really find the exact reason for it.

**Comment by zzzeek** [comment]
did you try not using fast_executemany ?  that would be the most immediate thing to turn off.    next how about using a different driver like pymssql?   crashes are not really within SQLAlchemy's realm these are driver issues.  When you say "inserting the same data directly" that is by itself not enough information.  are you binding the data to the statement using bound parameters, are you using cursor.executemany() and using the fast_executemany flag in that case as well?

**Comment by zzzeek** [comment]
does the program fail if you don't use pandas?  that is, run engine.execute() with an insert() construct.     what does SQL logging (e.g. echo=True) show?

**Comment by zzzeek** [comment]
so to sum up:

1. reproduce without using fast_executemany

2. reproduce without using pandas

3. get SQL echo=True output to see if pandas is doing something interesting

4. try pymssql just to see if behavior is different

5. illustrate test script that shows exactly how "inserting same data directly with pyodbc" is being done

**Comment by gizmo93** [comment]
Hey @zzzeek 
Thanks for your quick reply!
You were right with your guess that it's a driver problem:

I tested around the last 2 hours and it seems indeed to be a problem with fast_executemany = True.

If I try the following code:

```
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine, event
import traceback
import pyodbc

sql = """
INSERT INTO TestTable (IntValue, TooShortDatetimeValue, LongDateTimeValue, VeryShortDatetimeValue) VALUES (?, ?, ?, ?)
"""

cols = ['IntValue', 'TooShortDatetimeValue', 'LongDateTimeValue', 'VeryShortDatetimeValue']
data = [
    [1, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [2, datetime.now(), datetime.now(), datetime.now().replace(microsecond=0)],
    [3, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [4, datetime.now().replace(microsecond=0), datetime.now(), datetime.now()],
]


with pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=test;'
                    'Trusted_Connection=yes;') as con:
    with con.cursor() as cur:
        cur.fast_executemany = True
        cur.executemany(sql, data)
        con.commit()
```

or the following code:

```
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine, event
import traceback
import pyodbc

connection_string = 'mssql+pyodbc://localhost/Test?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)


# activate cursor.fast_executemany for sqlalchemy
# according to: https://bitbucket.org/zzzeek/sqlalchemy/issues/4158/pyodbc-sql-server-cursorfast_executemany
@event.listens_for(engine, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, parameters,
                                  context, executemany):
    if executemany:
        cursor.fast_executemany = True


sql = """
INSERT INTO TestTable (IntValue, TooShortDatetimeValue, LongDateTimeValue, VeryShortDatetimeValue) VALUES (?, ?, ?, ?)
"""

cols = ['IntValue', 'TooShortDatetimeValue', 'LongDateTimeValue', 'VeryShortDatetimeValue']
data = [
    [1, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [2, datetime.now(), datetime.now(), datetime.now().replace(microsecond=0)],
    [3, datetime.now().replace(microsecond=0), datetime.now(), datetime.now().replace(microsecond=0)],
    [4, datetime.now().replace(microsecond=0), datetime.now(), datetime.now()],
]

engine.execute(sql, data)
```

It does raise an exception (DataError) but if I repeat and execute the same code again and again, python.exe crashes about the 2nd or 3rd time with:

```
Traceback (most recent call last):
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1170, in _execute_context
    context)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 506, in do_executemany
    cursor.executemany(statement, parameters)
pyodbc.DataError: ('22008', '[22008] [Microsoft][ODBC Driver 17 for SQL Server]Datetime field overflow. Fractional second precision exceeds the scale specified in the parameter binding. (0) (SQLExecute)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 32, in <module>
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 2075, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1104, in _execute_text
    statement, parameters
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1170, in _execute_context
    context)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 506, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DataError: <exception str() failed>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\_pydev_bundle\pydev_code_executor.py", line 106, in add_exec
    more = self.do_add_exec(code_fragment)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\pydevconsole.py", line 84, in do_add_exec
    command.run()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\_pydev_bundle\pydev_console_types.py", line 35, in run
    self.more = self.interpreter.runsource(text, '<input>', symbol)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\code.py", line 94, in runcode
    self.showtraceback()
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\code.py", line 142, in showtraceback
    lines = traceback.format_exception(ei[0], ei[1], last_tb.tb_next)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 359, in extract
    linecache.checkcache(filename)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\linecache.py", line 74, in checkcache
    stat = os.stat(fullname)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not datetime.datetime
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\pydevconsole.py", line 174, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\_pydev_bundle\pydev_code_executor.py", line 128, in add_exec
    traceback.print_exc()
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 497, in __init__
    _seen=_seen)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 485, in __init__
    _seen=_seen)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\traceback.py", line 359, in extract
    linecache.checkcache(filename)
  File "C:\Users\holmo\AppData\Local\Programs\Python\Python37\lib\linecache.py", line 74, in checkcache
    stat = os.stat(fullname)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not datetime.datetime
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\pydevconsole.py", line 386, in <module>
    pydevconsole.start_client(host, port)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\pydevconsole.py", line 327, in start_client
    process_exec_queue(interpreter)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\pydevconsole.py", line 182, in process_exec_queue
    traceback.print_exception(type, value, tb, file=sys.__stderr__)
UnboundLocalError: local variable 'traceback' referenced before assignment
Process finished with exit code -1073741819 (0xC0000005)
```

If I turn fast_executemany off, its raising an **IntegrityError** and does not crash.

So it seems like I need to open an issue at pyodbc.

I am sorry, but I never had the idea to try the same code a second and a third time in the same console instance. Otherwise I would have noticed the crashes when using pyodbc executemany directly.

**Comment by zzzeek** [comment]
plus it looks like you're using a pycharm intepreter.  is the whole pycharm what's crashing?  maybe that's where the problem is as far as the crashes?
anyway it seems like no issue on our end here, reopen if you think there is.
