### ISSUE TITLE
dbapi() silently emit ImportError when pymysql package does not exist.

### ISSUE THREAD

**Issue by Xeite** [sqlalchemy/sqlalchemy#4424]
```
Traceback (most recent call last):
  File "/opt/openstack/src/keystone/keystone/cmd/manage.py", line 45, in main
    cli.main(argv=sys.argv, config_files=config_files)
  File "/opt/openstack/src/keystone/keystone/cmd/cli.py", line 1312, in main
    CONF.command.cmd_class.main()
  File "/opt/openstack/src/keystone/keystone/cmd/cli.py", line 489, in main
    print(upgrades.get_db_version())
  File "/opt/openstack/src/keystone/keystone/common/sql/upgrades.py", line 257, in get_db_version
    with sql.session_for_read() as session:
  File "/opt/pyenv/versions/2.7.12/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 944, in _transaction_scope
    allow_async=self._allow_async) as resource:
  File "/opt/pyenv/versions/2.7.12/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 558, in _session
    bind=self.connection, mode=self.mode)
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 317, in _create_session
    self._start()
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 403, in _start
    engine_args, maker_args)
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 427, in _setup_for_connection
    sql_connection=sql_connection, **engine_kwargs)
  File "/opt/openstack/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py", line 134, in create_engine
    engine = sqlalchemy.create_engine(url, **engine_args)
  File "/opt/openstack/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/openstack/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/openstack/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 49, in dbapi
    return __import__('pymysql')
  ImportError: No module named pymsql
```

When `pymysql` package is not available in system, currently dbapi() raise ImportError without any warnings. I think there should be any messages for the operators.

Thanks.

**Comment by zzzeek** [comment]
Hi there -

I'm not sure what this is asking?    why would it emit a warning *and* raise an error ?  what is the code you are invoking for which you would like this warning to emit?  there is no code sample here or demonstration of anything "silent" so I have no idea what you are asking.

**Comment by zzzeek** [comment]
additionally, this is against oslo.db and I have a feeling you want to be posting the issue at https://bugs.launchpad.net/oslo.db/

**Comment by Xeite** [comment]
@zzzeek  Hi, mike. Thanks for the reply. I'm sorry I told you so short.

Here is background. 

When I tried to OpenStack keystone-manage command with pymysql connection, the command exits without any message. I wonder why it happens and find out the root cause (ImportError that I said)

Actually I report the bug at keystone side (https://review.openstack.org/627374) first, but it seems not to be right place since it does not expect the libraries exception.

I'm not sure this API is intentional which means raise ImportError when pymysql package is not available. If then, I think oslo.db should catch the ImportError as you said.

So this is what I happened and I thought there should be any warning message at least if the API spec is not fixed at sqlalchemy.

Thanks!

**Comment by zzzeek** [comment]
if keystone is exiting without telling the user that the operation didn't work, that bug is in keystone.    it absolutely should be reporting exceptions when a library it is using raises.

> I think oslo.db should catch the ImportError as you said.

What should oslo.db do *after* it catches the error?   how will it connect to the database without a driver?

**Comment by Xeite** [comment]
> What should oslo.db do _after_ it catches the error? how will it connect to the database without a driver?

I thought oslo.db should print warning message after catching ImportError, since sqlalchemy create_engine() can raise ImportError depending on the API spec.

From keystone side, it does not know exception of library (oslo.db), so I thought oslo.db should catch the exception from library (sqlalchemy). I'm not sure where the right place is though..

**Comment by zzzeek** [comment]
well I dont know oslo.db should be wrapping ImportError because that's not a database error, it's a regular Python thing, but ultimately your issue is with keystone silently failing so you should be posting an issue on their launchpad, and if that means oslo.db needs something that can be suggested in openstack .     on this end it doesn't make sense to emit a warning if you're about to raise anyway.
