### ISSUE TITLE
elementtree example doesn't work, uses classical mappers

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4426]
multiple issues with this example:

1. can't be run as python examples/elementtree/optimized_ai.py becuase it has a file named "pickle" which gets in the way of SQLAlchemy "import pickle"

2. run as a module, has a unicode error on both py3k *and* py2k:

```
Traceback (most recent call last):
  File "/opt/python-3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python-3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/classic/dev/sqlalchemy/examples/elementtree/optimized_al.py", line 223, in <module>
    print(document)
  File "/home/classic/dev/sqlalchemy/examples/elementtree/optimized_al.py", line 87, in __str__
    self.element.write(buf)
  File "/opt/python-3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 777, in write
    short_empty_elements=short_empty_elements)
  File "/opt/python-3.7.0/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/opt/python-3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 836, in _get_writer
    yield file.write
  File "/opt/python-3.7.0/lib/python3.7/contextlib.py", line 511, in __exit__
    raise exc_details[1]
  File "/opt/python-3.7.0/lib/python3.7/contextlib.py", line 496, in __exit__
    if cb(*exc_details):
  File "/opt/python-3.7.0/lib/python3.7/contextlib.py", line 383, in _exit_wrapper
    callback(*args, **kwds)
TypeError: string argument expected, got 'bytes'

```

3. uses classical mappings which will be going away

4. also uses query.join(..., aliased=True) which would be nice to get rid of, but this is actually a demo of what that flag was intended for.   might be nice though to use aliased() explicitly in any case.

**Comment by zzzeek** [comment]
OK we need to put non-classical mappings here, and possibly try to see if we can come up with a more modern pattern than using aliased=True.  but at least the thing runs now.

**Comment by sqla-tester** [comment]
**jonathan vanasco** referenced this issue:

**References: #4426** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3110

**Comment by zzzeek** [comment]
this example is removed from 2.0, it's antiquated and doesn't show any practices that we want to encourage these days.
