### ISSUE TITLE
dictlike examples broken in 1.3

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4446]
we still dont' have examples/ in the test suite, which is getting to be a problem, but anyway, examples/vertical/dictlike-polymorphic is broken likely due to #3423.

```
$ PYTHONPATH=~/dev/sqlalchemy/lib/ python -m examples.vertical.dictlike-polymorphic
2019-01-14 17:17:13,297 INFO

2019-01-14 17:17:13,303 INFO sqlalchemy.engine.base.Engine ()
2019-01-14 17:17:13,303 INFO sqlalchemy.engine.base.Engine COMMIT
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 241, in _as_instance
    inst = class_.__dict__[self.key + "_inst"]
KeyError: '_AssociationProxy_facts_139851016114016_inst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 355, in __getattr__
    return getattr(descriptor, attribute)
AttributeError: 'hybrid_property' object has no attribute 'impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 358, in __getattr__
    return getattr(self.comparator, attribute)
AttributeError: 'value' object has no attribute 'impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python-3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/classic/dev/sqlalchemy/examples/vertical/dictlike-polymorphic.py", line 191, in <module>
    stoat["color"] = "red"
  File "/home/classic/dev/sqlalchemy/examples/vertical/dictlike.py", line 58, in __setitem__
    self._proxied[key] = value
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 187, in __get__
    inst = self._as_instance(class_, obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 245, in _as_instance
    inst = AssociationProxyInstance.for_proxy(self, owner, obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 371, in for_proxy
    target_assoc, parent, owning_class, target_class, value_attr
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 383, in _construct_for_assoc
    is_object = getattr(target_class, value_attr).impl.uses_objects
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 367, in __getattr__
    attribute,
AttributeError: Neither 'hybrid_property' object nor 'value' object associated with AnimalFact.value has an attribute 'impl'

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Relax "ambiguous" association proxy restrictions, support Proxy** https://gerrit.sqlalchemy.org/1098
