### ISSUE TITLE
SingletonThreadPoolTest.test_cleanup Fails on openSUSE on 1.3.0 release

### ISSUE THREAD

**Issue by scarabeusiv** [sqlalchemy/sqlalchemy#4527]
```
[  384s] _____________________ SingletonThreadPoolTest.test_cleanup _____________________
[  384s] Traceback (most recent call last):
[  384s]   File "/home/abuild/rpmbuild/BUILD/SQLAlchemy-1.3.0/test/engine/test_pool.py", line 1757, in test_cleanup
[  384s]     self._test_cleanup(False)
[  384s]   File "/home/abuild/rpmbuild/BUILD/SQLAlchemy-1.3.0/test/engine/test_pool.py", line 1813, in _test_cleanup
[  384s]     eq_(len(p._all_conns), 3)
[  384s]   File "/home/abuild/rpmbuild/BUILD/SQLAlchemy-1.3.0/test/../lib/sqlalchemy/testing/assertions.py", line 237, in eq_
[  384s]     assert a == b, msg or "%r != %r" % (a, b)
[  384s] AssertionError: 4 != 3
```

The test passes fine with the 1.2.18 release.

**Comment by zzzeek** [comment]
can you show me how you run the tests ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Loosen SingletonThreadPoolTest** https://gerrit.sqlalchemy.org/1157

**Comment by scarabeusiv** [comment]
With the patch above added to the build it passes. Attaching build log: 
[alchemy.txt](https://github.com/sqlalchemy/sqlalchemy/files/2936464/alchemy.txt)
