### ISSUE TITLE
large_resultsets performance example fails due to incorrect parameter name on SimpleCustomer

### ISSUE THREAD

**Issue by Shookit** [sqlalchemy/sqlalchemy#4528]
Executing the performance test yields the following:
```
python -m examples.performance large_resultsets
Running setup once...
Tests to run: test_orm_full_objects_list, test_orm_full_objects_chunks, test_orm_bundles, test_orm_columns, test_core_fetchall, test_core_fetchmany_w_streaming, test_core_fetchmany, test_dbapi_fetchall_plus_append_objects, test_dbapi_fetchall_no_object
test_orm_full_objects_list : Load fully tracked ORM objects into one big list(). (500000 iterations); total time 22.261599 sec
test_orm_full_objects_chunks : Load fully tracked ORM objects a chunk at a time using yield_per(). (500000 iterations); total time 15.405262 sec
test_orm_bundles : Load lightweight "bundle" objects using the ORM. (500000 iterations); total time 5.298612 sec
test_orm_columns : Load individual columns into named tuples using the ORM. (500000 iterations); total time 3.983049 sec
test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total time 2.986297 sec
test_core_fetchmany_w_streaming : Load Core result rows using fetchmany/streaming. (500000 iterations); total time 2.523552 sec
test_core_fetchmany : Load Core result rows using Core / fetchmany. (500000 iterations); total time 2.550616 sec
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sqlalchemy/examples/performance/__main__.py", line 7, in <module>
    Profiler.main()
  File "examples/performance/__init__.py", line 387, in main
    Profiler(args).run()
  File "examples/performance/__init__.py", line 292, in run
    self._run_test(test)
  File "examples/performance/__init__.py", line 322, in _run_test
    self._run_with_time(fn)
  File "examples/performance/__init__.py", line 311, in _run_with_time
    return fn(self.num)
  File "examples/performance/large_resultsets.py", line 148, in test_dbapi_fetchall_plus_append_objects
    _test_dbapi_raw(n, True)
  File "examples/performance/large_resultsets.py", line 187, in _test_dbapi_raw
    id=row[0], name=row[1], description=row[2]
  File "examples/performance/large_resultsets.py", line 173, in __init__
    self.id = id_
NameError: global name 'id_' is not defined
```

**Comment by zzzeek** [comment]
oh that's due to the black reformatting, OK

**Comment by sqla-tester** [comment]
**Matt Schuchhardt** has proposed a fix for this issue in the **master** branch:

**Fix large_resultsets performance example field name** https://gerrit.sqlalchemy.org/1159

**Comment by sqla-tester** [comment]
**Matt Schuchhardt** has proposed a fix for this issue in the **master** branch:

**Fix large_resultsets performance example field name** https://gerrit.sqlalchemy.org/1159

**Comment by sqla-tester** [comment]
**Matt Schuchhardt** has proposed a fix for this issue in the **rel_1_2** branch:

**Fix large_resultsets performance example field name** https://gerrit.sqlalchemy.org/1160
