### ISSUE TITLE
Snapshot isolation - MSSQL Server fails

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#4536]
When using pyodbc, and MS ODBC DRIVER FOR WINDOWS 17, the sqlalchemy implementation for changing isolation level to SNAPSHOT fails.

This fails:
```
from sqlalchemy import create_engine 
>>> engine= create_engine("ConnectionUrl")
>>> conn = engine.connect()
>>> conn = engine.connect()
>>> conn.execution_options(
...                     isolation_level="SNAPSHOT")
<sqlalchemy.engine.base.Connection object at 0x000002269FE28F28>
>>> conn.execute("SELECT TOP 10 * FROM Staging.CoreRespdet")
Traceback (most recent call last):
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction failed in database 'ETL' because the statement was run under snapshot isolation but the transaction did not start in snapshot isolation. You cannot change the isolation level of the transaction to snapshot after the transaction has started unless the transaction was originally started under snapshot isolation level. (3951) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 974, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 1147, in _execute_text
    parameters,
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\util\compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\util\compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\*****\source\repos\*****\ETLApp_Dev\ETLApp\ETLAppEnv_3_7\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction failed in database 'ETL' because the statement was run under snapshot isolation but the transaction did not start in snapshot isolation. You cannot change the isolation level of the transaction to snapshot after the transaction has started unless the transaction was originally started under snapshot isolation level. (3951) (SQLExecDirectW)") [SQL: 'SELECT TOP 10 * FROM Staging.CoreRespdet'] (Background on this error at: http://sqlalche.me/e/f405)
>>> 
```

This however works:
```
>>> engine = create_engine(connString)
>>> conn = engine.connect()
>>> conn.execute("SET TRANSACTION ISOLATION LEVEL SNAPSHOT "
...              "COMMIT")
<sqlalchemy.engine.result.ResultProxy object at 0x00000226AFD179E8>
>>> conn.execute("SELECT TOP 10 * FROM Staging.CoreRespdet")
<sqlalchemy.engine.result.ResultProxy object at 0x00000226AFEA26D8>
>>> 
```

I've got an issue posted [here](https://github.com/mkleehammer/pyodbc/issues/524) with pyodbc discussing the underlying cause of this. 

My SQLAlchemy version:
```
>>> sqlalchemy.__version__
'1.2.18'
```

**Comment by jmarshall9120** [comment]
It looks like it can also be done like this. 

>>> engine= create_engine("ConnectionUrl")
>>> conn = engine.connect()
>>> conn = engine.connect()
>>> conn.execution_options(
...                     isolation_level="SNAPSHOT")
<sqlalchemy.engine.base.Connection object at 0x000002269FE28F28>
>>> conn.begin().commit()
>>> conn.execute("SELECT TOP 10 * FROM Staging.CoreRespdet")

**Comment by zzzeek** [comment]
not ideal but we can add the commit.    Test case for pyodbc shows that it does maintain the new isolation level after the commit:


```
import pyodbc

conn = pyodbc.connect("DRIVER={ODBC Driver 13 for SQL Server};Server=mssql2017,1433;Database=test;UID=scott;PWD=tiger^5HHH")

#conn.autocommit = False
cursor = conn.cursor()
cursor.execute("SET TRANSACTION ISOLATION LEVEL %s" % "SNAPSHOT")
cursor.close()
conn.commit()

cursor = conn.cursor()
cursor.execute("""
SELECT CASE transaction_isolation_level
WHEN 0 THEN 'Unspecified'
WHEN 1 THEN 'ReadUncommitted'
WHEN 2 THEN 'ReadCommitted'
WHEN 3 THEN 'Repeatable'
WHEN 4 THEN 'Serializable'
WHEN 5 THEN 'Snapshot' END AS TRANSACTION_ISOLATION_LEVEL
FROM sys.dm_exec_sessions
where session_id = @@SPID
""")
print(cursor.fetchall())

cursor.execute("SELECT TOP 10 * FROM test")
```

**Comment by zzzeek** [comment]
good news, pymssql has the same problem so we can apply the fix to both

**Comment by zzzeek** [comment]
im having very strange difficulty reproducing it in the test suite however for unknown reasons

**Comment by jmarshall9120** [comment]
have you looked at my post on the pyodbc [issue](https://github.com/mkleehammer/pyodbc/issues/524)?

I would expect from your test that the first query shows that your transaction level is okay and that the second query throws the error.  (This issue doesn't seem to affect sys views.  I'd guess they probably don't support snapshot isolation anyway since we don't write to those as devs.)

Also it looks like your using the ODBC Driver:
     `ODBC Driver 13 for SQL Server`

The current driver is:
     `ODBC Driver 17 for SQL Server
`
Is any of this helping you reproduce?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Commit transaction after SNAPSHOT isolation change** https://gerrit.sqlalchemy.org/1162

**Comment by zzzeek** [comment]
it's not related to ODBC as it also reproduces with pymssql.   I was confusing SNAPSHOT for SERIALIZABLE.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Commit transaction after SNAPSHOT isolation change** https://gerrit.sqlalchemy.org/1163
