### ISSUE TITLE
LargeBinary column does not work in python3.7 with mysql

### ISSUE THREAD

**Issue by mklassen** [sqlalchemy/sqlalchemy#4541]
Records with a `LargeBinary` type column throw ```TypeError: string argument without an encoding``` when queried from mysql engine in python3.7.2 using SQLAlchemy==1.3.1

```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, create_engine, Integer, LargeBinary
from sqlalchemy.orm import sessionmaker
Base = declarative_base()
class MyTable(Base):
    __tablename__ = 'test'
    id = Column('table_id', Integer, primary_key=True)
    field = Column('field', LargeBinary())
engine = create_engine('mysql+mysqlconnector://user:password@localhost/scratch?charset=utf8')
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()
session.add(MyTable(field=b'test'))
session.commit()
session.query(MyTable).all()
```

Traceback (most recent call last):
  File "/tmp/tester.py", line 51, in <module>
    session.query(MyTable).all()
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 572, in _instance
    populators,
  File "/tmp/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 693, in _populate_full
    dict_[key] = getter(row)
  File "/tmp/python/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 943, in process
    value = bytes(value)
TypeError: string argument without an encoding

**Comment by zzzeek** [comment]
hi there -

this is a mysql-connector bug.  Please use mysqlclient or pymysql and let me know that solves your issue.  thanks!

**Comment by mklassen** [comment]
Yes the issue goes away with `pymysql`.
