### ISSUE TITLE
In 1.3.x: Loader options can't handle aliases anymore

### ISSUE THREAD

**Issue by kolypto** [sqlalchemy/sqlalchemy#4566]
Brief: `Query.options()` can't handle loader options that reference columns of an aliased model.

Used to work fine in every version of SqlAlchemy 1.2.x.
Is broken in every version of SqlAlchemy 1.3.x, including the current master branch.
Python: 3.7, SqlAlchemy: 1.3.1

Test case (no DB needed, pure Python):

```python
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship, aliased, defaultload, contains_eager, Query
from sqlalchemy.ext.declarative import declarative_base

# Define some models
Base = declarative_base()

class User(Base):
    __tablename__ = 'u'

    id = Column(Integer, primary_key=True)
    name = Column(String)

class Article(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    # Here comes the relationship
    uid = Column(Integer, ForeignKey(User.id))
    user = relationship(User)

# Query Article
q = Query([Article])

# Join User model, aliased()
# This bug only works with aliases
User_alias = aliased(User)
q = q.join((Article.user, User_alias))
q = q.options(contains_eager(Article.user, alias=User_alias))

print(q)
# The query is correct:
# SELECT u_1.id AS u_1_id, u_1.name AS u_1_name, a.id AS a_id, a.uid AS a_uid
# FROM a JOIN u AS u_1 ON u_1.id = a.uid

# Here comes the bug!
# Try to load just one field of that aliased user
opt = defaultload(Article.user).load_only(User_alias.name)
q = q.options(opt)  # Exception
```

Gives the following exception (Python 3.7, SqlAlchemy 1.3.1):

```
Traceback (most recent call last):
  File "bug.py", line 32, in <module>
    q = q.options(opt)
  File "./sqlalchemy/orm/query.py", line 1523, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "./sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "./sqlalchemy/orm/query.py", line 1542, in _options
    opt.process_query(self)
  File "./sqlalchemy/orm/strategy_options.py", line 168, in process_query
    self._process(query, True)
  File "./sqlalchemy/orm/strategy_options.py", line 526, in _process
    raiseerr,
  File "./sqlalchemy/orm/strategy_options.py", line 704, in _bind_loader
    raiseerr,
  File "./sqlalchemy/orm/strategy_options.py", line 253, in _generate_path
    attr.parent, path[-1]
  File "./sqlalchemy/orm/util.py", line 1269, in _entity_corresponds_to_use_path_impl
    or given in entity._with_polymorphic_entities
AttributeError: 'Mapper' object has no attribute '_with_polymorphic_entities'
```

**Comment by zzzeek** [comment]
So I think, here is what it expects:

    opt = defaultload(Article.user.of_type(User_alias)).load_only(User_alias.name)

and if I fix the bug, which I think so far is:

```
diff --git a/lib/sqlalchemy/orm/util.py b/lib/sqlalchemy/orm/util.py
index f9258895d3..7b8edd3493 100644
--- a/lib/sqlalchemy/orm/util.py
+++ b/lib/sqlalchemy/orm/util.py
@@ -1265,8 +1265,10 @@ def _entity_corresponds_to_use_path_impl(given, entity):
         return (
             entity.is_aliased_class
             and not entity._use_mapper_path
-            and given is entity
-            or given in entity._with_polymorphic_entities
+            and (
+                given is entity
+                or given in entity._with_polymorphic_entities
+            )
         )
     elif not entity.is_aliased_class:
         return given.common_parent(entity.mapper)


```

you get the error message:

`sqlalchemy.exc.ArgumentError: Attribute "AliasedClass_User.name" does not link from element "mapped class User->u"`

which I think also should have a clue, "did you mean to use of_type() ?" but that has to be worded carefully.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fix boolean check in new path comparison logic** https://gerrit.sqlalchemy.org/1175

**Comment by zzzeek** [comment]
it's probably worth it to see if this loader option actually works.  it does not seem to work for a lazy load, for example (that is without your contains_eager).

**Comment by zzzeek** [comment]
here's two suites of tests to test that it loads only the attributes we expect and also that it applies only to the Article.user path and not that of another Article that's under an alias.  works in all cases for 1.2 and 1.3 with the exception of this error case in 1.3

```
import unittest

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased
from sqlalchemy.orm import contains_eager
from sqlalchemy.orm import defaultload
from sqlalchemy.orm import Query
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

# Define some models
Base = declarative_base()


class User(Base):
    __tablename__ = "u"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    not_name = Column(String)


class Article(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    # Here comes the relationship
    uid = Column(Integer, ForeignKey(User.id))
    user = relationship(User)


class SinglePathTestCase(unittest.TestCase):
    def setUp(self):
        e = create_engine("sqlite://", echo=True)
        Base.metadata.create_all(e)

        self.s = s = Session(e)

        u1 = User(name="u1", not_name="u2")
        s.add(Article(user=u1))
        s.commit()

    def test_one(self):
        s = self.s
        # Query Article
        q = Query([Article])

        User_alias = aliased(User)
        q = q.join(Article.user.of_type(User_alias))
        q = q.options(contains_eager(Article.user, alias=User_alias))

        # dont use alias at all in load_only
        opt = defaultload(Article.user).load_only(User.name)
        q = q.options(opt)

        a1 = q.with_session(s).one()
        assert "not_name" not in a1.user.__dict__

    def test_two(self):
        s = self.s
        # Query Article
        q = Query([Article])

        # Join User model, aliased()
        # This bug only works with aliases
        User_alias = aliased(User)
        q = q.join(Article.user.of_type(User_alias))
        q = q.options(contains_eager(Article.user, alias=User_alias))

        # use alias in load_only but dont put it in path; only works in 1.2
        opt = defaultload(Article.user).load_only(User_alias.name)
        q = q.options(opt)  # Exception

        a1 = q.with_session(s).one()
        assert "not_name" not in a1.user.__dict__

    def test_three(self):
        s = self.s
        # Query Article
        q = Query([Article])

        # Join User model, aliased()
        # This bug only works with aliases
        User_alias = aliased(User)
        q = q.join(Article.user.of_type(User_alias))
        q = q.options(contains_eager(Article.user, alias=User_alias))

        # use alias fully
        opt = defaultload(Article.user.of_type(User_alias)).load_only(
            User_alias.name
        )
        q = q.options(opt)

        a1 = q.with_session(s).one()
        assert "not_name" not in a1.user.__dict__


class MultiplePathTestCase(unittest.TestCase):
    def setUp(self):
        e = create_engine("sqlite://", echo=True)
        Base.metadata.create_all(e)

        self.s = s = Session(e)

        u1 = User(name="u1", not_name="u2")
        s.add(Article(id=1, user=u1))

        u2 = User(name="u3", not_name="u4")
        s.add(Article(id=2, user=u2))

        s.commit()

    def _fixture(self):
        s = self.s

        article_alias = aliased(Article)
        user_alias = aliased(User)

        q = (
            (
                s.query(Article, article_alias)
                .join(Article.user.of_type(user_alias))
                .join(article_alias.user.of_type(User))
            )
            .filter(Article.id == 1)
            .filter(article_alias.id == 2)
        )

        q = q.options(
            contains_eager(Article.user, alias=user_alias),
            contains_eager(article_alias.user),
        )

        return q, user_alias

    def test_one(self):
        q, user_alias = self._fixture()

        opt = defaultload(Article.user).load_only(User.name)
        q = q.options(opt)

        a1, a2 = q.one()
        assert "not_name" not in a1.user.__dict__
        assert a2.user.__dict__["not_name"] == "u4"

    def test_two(self):
        q, user_alias = self._fixture()

        # use alias in load_only but dont put it in path; only works in 1.2
        opt = defaultload(Article.user).load_only(user_alias.name)
        q = q.options(opt)

        a1, a2 = q.one()
        assert "not_name" not in a1.user.__dict__
        assert a2.user.__dict__["not_name"] == "u4"

    def test_three(self):
        q, user_alias = self._fixture()

        # use alias fully
        opt = defaultload(Article.user.of_type(user_alias)).load_only(
            user_alias.name
        )
        q = q.options(opt)

        a1, a2 = q.one()
        assert "not_name" not in a1.user.__dict__
        assert a2.user.__dict__["not_name"] == "u4"


unittest.main()

```

**Comment by kolypto** [comment]
@zzzeek , thank you for sqlalchemy, you're amazing! :)
