### ISSUE TITLE
bind-level processors can only be applied to DB-specific type when subclassing, otherwise use typedecorator

### ISSUE THREAD

**Issue by diogobaeder** [sqlalchemy/sqlalchemy#4580]
Hi guys,

Starting on 1.3.0 (also tested on 1.3.1), SQLAlchemy ORM suddenly stopped casting fields defined with ARRAY of Enum values. This works fine on 1.2.18, but as soon as I update to the next version it breaks, leading to a situation where I can't add an instance to a session by setting this kind of field to a list of enum values.

I'm not sure if this is a bug or if the library was changed in a way that this behavior is intended, but is anybody else aware of this?

Please let me know if you want me to provide more details, or a test case perhaps for regression testing - I just wanted to be sure if this is really a bug and not an expected change in behavior first.

Cheers,
Diogo

**Comment by zzzeek** [comment]
hi there -

please provide a succinct example of what kind of Table / ORM model you have, datatypes, what operation you are doing, and stack trace, thanks.

**Comment by diogobaeder** [comment]
Hey there Mike! Thanks for the quick reply :-)

So, this is a test script that runs fine on `1.2.18`, but doesn't on `1.3.1`:

```python
#!/usr/bin/env python

import re
from enum import Enum

from sqlalchemy import (
    ARRAY,
    Enum as EnumType,
    cast,
    Column,
    Integer,
    String,
    create_engine,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DSN = 'postgresql+psycopg2://postgres:@localhost/arrayofenum'

Base = declarative_base()


class ArrayOfEnum(ARRAY):
    def bind_expression(self, bindvalue):
        return cast(bindvalue, self)

    def result_processor(self, dialect, coltype):
        super_rp = super(ArrayOfEnum, self).result_processor(
            dialect, coltype)

        def handle_raw_string(value):
            inner = re.match(r"^{(.*)}$", value).group(1)
            return inner.split(",") if inner else []

        def process(value):
            if value is None:
                return None
            return super_rp(handle_raw_string(value))
        return process


class StringEnum(Enum):
    @staticmethod
    def get_values(cls):
        return [a.value for a in cls]


class Action(StringEnum):
    CAN_USE = 'can_use'
    CAN_CREATE = 'can_create'
    CAN_CHANGE = 'can_change'
    CAN_DELETE = 'can_delete'
    CAN_SHARE = 'can_share'


class Permission(Base):
    __tablename__ = 'permissions'

    id = Column(Integer, primary_key=True)
    actions = Column(ArrayOfEnum(EnumType(
        Action, values_callable=Action.get_values)), nullable=False)
    resource = Column(String, nullable=False)

    def __repr__(self):
        return 'Permission(action={!r}, resource={!r})'.format(
            self.action, self.resource)


def main():
    engine = create_engine(DSN, echo=True)
    Session = sessionmaker(bind=engine)
    Base.metadata.create_all(engine)
    session = Session()

    permission = Permission(
        actions=[
            Action.CAN_USE,
            Action.CAN_CHANGE,
            Action.CAN_DELETE,
        ],
        resource='some-page',
    )
    session.add(permission)
    session.flush()

    assert permission.id is not None


if __name__ == '__main__':
    main()
```

On `1.3.1`, this is the traceback I get:

```
/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-03-29 00:56:36,579 INFO sqlalchemy.engine.base.Engine select version()
2019-03-29 00:56:36,579 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,581 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-03-29 00:56:36,581 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,582 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-03-29 00:56:36,582 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,582 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-03-29 00:56:36,583 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,583 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-03-29 00:56:36,583 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,584 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2019-03-29 00:56:36,584 INFO sqlalchemy.engine.base.Engine {'name': 'permissions'}
2019-03-29 00:56:36,586 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:56:36,586 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:56:36,587 INFO sqlalchemy.engine.base.Engine CREATE TYPE action AS ENUM ('can_use', 'can_create', 'can_change', 'can_delete', 'can_share')
2019-03-29 00:56:36,587 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,589 INFO sqlalchemy.engine.base.Engine COMMIT
2019-03-29 00:56:36,591 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:56:36,591 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:56:36,592 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:56:36,592 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:56:36,593 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE permissions (
	id SERIAL NOT NULL, 
	actions action[] NOT NULL, 
	resource VARCHAR NOT NULL, 
	PRIMARY KEY (id)
)


2019-03-29 00:56:36,593 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:56:36,607 INFO sqlalchemy.engine.base.Engine COMMIT
2019-03-29 00:56:36,609 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-03-29 00:56:36,610 INFO sqlalchemy.engine.base.Engine INSERT INTO permissions (actions, resource) VALUES (%(actions)s, %(resource)s) RETURNING permissions.id
2019-03-29 00:56:36,610 INFO sqlalchemy.engine.base.Engine {'actions': ['can_use', 'can_change', 'can_delete'], 'resource': 'some-page'}
2019-03-29 00:56:36,611 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "actions" is of type action[] but expression is of type text[]
LINE 1: ...SERT INTO permissions (actions, resource) VALUES (ARRAY['can...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./arrayofenum.py", line 90, in <module>
    main()
  File "./arrayofenum.py", line 84, in main
    session.flush()
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "actions" is of type action[] but expression is of type text[]
LINE 1: ...SERT INTO permissions (actions, resource) VALUES (ARRAY['can...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO permissions (actions, resource) VALUES (%(actions)s, %(resource)s) RETURNING permissions.id]
[parameters: {'actions': ['can_use', 'can_change', 'can_delete'], 'resource': 'some-page'}]
(Background on this error at: http://sqlalche.me/e/f405)
```

Notice how in the above traceback there's no casting on the array of enums; if I run it on `1.2.18`, I can see the casting happening there:

```
/home/diogobaeder/Envs/arrayofenum/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-03-29 00:55:02,485 INFO sqlalchemy.engine.base.Engine select version()
2019-03-29 00:55:02,485 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,487 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-03-29 00:55:02,487 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,488 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-03-29 00:55:02,488 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,489 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-03-29 00:55:02,489 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,489 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-03-29 00:55:02,489 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,491 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2019-03-29 00:55:02,491 INFO sqlalchemy.engine.base.Engine {'name': 'permissions'}
2019-03-29 00:55:02,492 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:55:02,493 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:55:02,493 INFO sqlalchemy.engine.base.Engine CREATE TYPE action AS ENUM ('can_use', 'can_create', 'can_change', 'can_delete', 'can_share')
2019-03-29 00:55:02,494 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,495 INFO sqlalchemy.engine.base.Engine COMMIT
2019-03-29 00:55:02,497 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:55:02,497 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:55:02,497 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2019-03-29 00:55:02,498 INFO sqlalchemy.engine.base.Engine {'typname': 'action'}
2019-03-29 00:55:02,499 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE permissions (
	id SERIAL NOT NULL, 
	actions action[] NOT NULL, 
	resource VARCHAR NOT NULL, 
	PRIMARY KEY (id)
)


2019-03-29 00:55:02,499 INFO sqlalchemy.engine.base.Engine {}
2019-03-29 00:55:02,510 INFO sqlalchemy.engine.base.Engine COMMIT
2019-03-29 00:55:02,513 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-03-29 00:55:02,514 INFO sqlalchemy.engine.base.Engine INSERT INTO permissions (actions, resource) VALUES (CAST(%(actions)s AS action[]), %(resource)s) RETURNING permissions.id
2019-03-29 00:55:02,514 INFO sqlalchemy.engine.base.Engine {'actions': ['can_use', 'can_change', 'can_delete'], 'resource': 'some-page'}
```

Thanks!

**Comment by diogobaeder** [comment]
Sorry, forgot to mention: that implementation of `ArrayOfEnum` I got from here: https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#using-enum-with-array

**Comment by lbolla** [comment]
A quick bisect points to this specific commit: https://github.com/sqlalchemy/sqlalchemy/commit/f03c7918796e1080d971a9c03943962478be4caf

In particular, this line: https://github.com/sqlalchemy/sqlalchemy/commit/f03c7918796e1080d971a9c03943962478be4caf#diff-9deda8c7c10c7034cd9463f530ca81f0L1241

It seems to me that in new version of SqlAlchemy `bindparam.type.dialect_impl` is used (which is `ARRAY` in the example above), rather than the subtype defined in the example above. As a result the user-defined `bind_expression` method is not used, so the "cast" is not done.

**Comment by zzzeek** [comment]
so if I run the example in the docs as is I get the CAST:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.dialects.postgresql import ARRAY, ENUM
import re

Base = declarative_base()


class ArrayOfEnum(ARRAY):

    def bind_expression(self, bindvalue):
        return cast(bindvalue, self)

    def result_processor(self, dialect, coltype):
        super_rp = super(ArrayOfEnum, self).result_processor(
            dialect, coltype)

        def handle_raw_string(value):
            inner = re.match(r"^{(.*)}$", value).group(1)
            return inner.split(",") if inner else []

        def process(value):
            if value is None:
                return None
            return super_rp(handle_raw_string(value))
        return process

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(ArrayOfEnum(ENUM('a', 'b', 'c', name='myenum')))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data=["a", "b", "a", "c"]))
s.commit()

s.query(A.data).first()
```

let's see what happens in your example

**Comment by zzzeek** [comment]
oh nm, if I import ARRAY from base then I get it.   but this may be normal let me check

**Comment by zzzeek** [comment]
yeah this is normal.   if you want to use sqlalchemy.ARRAY you need to use TypeDecorator, so I can see a lot of doc examples where this is not clear or outright incorrect (like https://docs.sqlalchemy.org/en/latest/core/custom_types.html#replacing-processors) so thats the bug.

**Comment by diogobaeder** [comment]
Dude, thanks a lot! Indeed, I just changed my script to:
```
from sqlalchemy.dialects.postgresql import ARRAY
```
instead of importing from the library's `__init__`, and it works! :-)

Do you plan to update the docs for "using enum with array" ( https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#using-enum-with-array ) to using the `TypeDecorator`? I'll use that approach when you have that updated, as I'm a bit confused to how that should be approached when mixing ARRAY and ENUM.

**Comment by zzzeek** [comment]
> Dude, thanks a lot! Indeed, I just changed my script to:
> 
> ```
> from sqlalchemy.dialects.postgresql import ARRAY
> ```
> 
> instead of importing from the library's `__init__`, and it works! :-)
> 
> Do you plan to update the docs for "using enum with array" ( https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#using-enum-with-array ) to using the `TypeDecorator`? I'll use that approach when you have that updated, as I'm a bit confused to how that should be approached when mixing ARRAY and ENUM.

yes I'm going to make using TypeDecorator against whatever type you want as the One True Way.

**Comment by diogobaeder** [comment]
Thanks a lot, man, you're fast! :-)

I'm already using TypeDecorator now. Cool!

**Comment by zzzeek** [comment]
sometimes! that one was pretty bad.
