### ISSUE TITLE
pip install sqlalchemy==1.3.1 on Ubuntu 18.04 has zipfile.BadZipFile exception

### ISSUE THREAD

**Issue by sailorfred** [sqlalchemy/sqlalchemy#4582]
1.3.0 is OK, and 1.3.1 on 16.04 is OK.

With 18.04, Python is 3.6.  16.04 is 3.5.

(x) vagrant@ubuntu-bionic:~$ pip install sqlalchemy==1.3.1
Collecting sqlalchemy==1.3.1
Exception:
Traceback (most recent call last):
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/download.py", line 865, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/download.py", line 763, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 626, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/vagrant/x/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 503, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by zzzeek** [comment]
I doubt there's anything wrong with SQLAlchemy's zipfile, that would be a lot more noticeable.  it sounds like you need to clear your pip cache:  https://stackoverflow.com/questions/34889056/trying-to-install-pycuda-getting-zip-error/41916324#41916324

**Comment by sailorfred** [comment]
Hmm, so a bug in pip, then?

**Comment by zzzeek** [comment]
perhaps, did you try the linked solution ?

**Comment by zzzeek** [comment]
there's no bug on the SQLAlchemy side here so closing
