### ISSUE TITLE
Using AliasedClass in model module causes NameError/InvalidRequestError

### ISSUE THREAD

**Issue by grant-humphries** [sqlalchemy/sqlalchemy#4660]
I have relationship that requires a complex join and have used this [non-primary mapper approach](https://docs.sqlalchemy.org/en/12/orm/join_conditions.html#relationship-to-non-primary-mapper) in the past to achieve it.  Since the `non_primary` mapper setting is deprecated in `1.3` I'm attempting to migrate to using an `AliasedClass` per this [guide](https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#relationship-to-aliasedclass-replaces-the-need-for-non-primary-mappers).  However creating an instance of AliasedClass in any of the files that contain models is causing an error to be thrown, I believe, when the declarative base is loaded.  Here is the stacktrace and some environment specs:

Python: 2.7 & 3.6
SQLAlchemy: 1.3.3

```
Traceback (most recent call last):
  File "C:\Users\humphrig\projects\yard-map\trimet.yardmap\bin\serve-script.py", line 86, in <module>
    import trimet.webapp.scripts.development
  File "c:\users\humphrig\projects\yard-map\trimet.webapp\trimet\webapp\scripts\development.py", line 16, in <module>
    from trimet.webapp import util
  File "c:\users\humphrig\projects\yard-map\trimet.webapp\trimet\webapp\util.py", line 15, in <module>
    from trimet.webapp.model.schema import Mapping
  File "c:\users\humphrig\projects\yard-map\trimet.webapp\trimet\webapp\model\__init__.py", line 4, in <module>
    from trimet.webapp.model.collection_proxy import PowerBuilderCollectionProxy
  File "c:\users\humphrig\projects\yard-map\trimet.webapp\trimet\webapp\model\collection_proxy.py", line 9, in <module>
    from trimet.model.oracle.base import Base
  File "c:\users\humphrig\projects\yard-map\trimet.model.oracle\trimet\model\oracle\__init__.py", line 3, in <module>
    from trimet.model.oracle.acid import *
  File "c:\users\humphrig\projects\yard-map\trimet.model.oracle\trimet\model\oracle\acid\__init__.py", line 46, in <module>
    from .service_restoration import ServiceRestoration
  File "c:\users\humphrig\projects\yard-map\trimet.model.oracle\trimet\model\oracle\acid\service_restoration.py", line 6, in <module>
    from trimet.model.oracle.trans import Garage
  File "c:\users\humphrig\projects\yard-map\trimet.model.oracle\trimet\model\oracle\trans\__init__.py", line 123, in <module>
    from .vehicle_info import VehicleInfo
  File "c:\users\humphrig\projects\yard-map\trimet.model.oracle\trimet\model\oracle\trans\vehicle_info.py", line 200, in <module>
    **activity_coupling = aliased(TrainActivity, j, flat=True)**
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\util.py", line 836, in aliased
    adapt_on_names=adapt_on_names,
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\util.py", line 480, in __init__
    else mapper.with_polymorphic_mappers,
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\util\langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\mapper.py", line 2135, in _with_polymorphic_mappers
    configure_mappers()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\mapper.py", line 3229, in configure_mappers
    mapper._post_configure_properties()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\interfaces.py", line 196, in init
    self.do_init()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\relationships.py", line 1860, in do_init
    self._process_dependent_arguments()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\relationships.py", line 1922, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\util\langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\orm\relationships.py", line 1827, in entity
    argument = self.argument()
  File "c:\users\humphrig\projects\yard-map\trimet.yardmap\eggs\sqlalchemy-1.3.3-py2.7-win-amd64.egg\sqlalchemy\ext\declarative\clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Incident->incident, expression 'ServiceRestoration'
 failed to locate a name ("name 'ServiceRestoration' is not defined"). If this is a class name, consider adding this relation
ship() to the <class 'trimet.model.oracle.acid.incident.Incident'> class after both dependent classes have been defined.
```

The ORM my company uses is quite large and the basic structure is this:  All model classes extend a single declarative base and there is a package for each database schema and a module for each model.  Imports are used in package `__init__.py` files to import all models to the top level package which is where the declarative base is defined.  Here is a basic example of what will cause this error when the base is imported (which triggers the loading of all of the model classes):

```py

class VehicleInfo(Base):
    __tablename__ = 'vehicle_info'

...

vehicle_info_alias = aliased(VehicleInfo)
```

Thanks in advance if you get a chance to take a look at this and am glad to provide any more info that is needed.

**Comment by zzzeek** [comment]
OK, because per the stack trace, AliasedClass forces the mappers to be configured.   no change I make doesn't have some huge caveat I couldn't think of.  the only way to work around this now is to use an event handler for "after_configured" with a global variable; declarative gives you a shortcut using the `__declare_last__` hook:


```python

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased
from sqlalchemy.orm import configure_mappers
from sqlalchemy.orm import relationship

Base = declarative_base()


aliased_b = None

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")

    @classmethod
    def __declare_last__(cls):
        global aliased_b
        aliased_b = aliased(B)
        cls.b_non_primary = relationship(aliased_b)

class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


configure_mappers()

print(A.b_non_primary)

```


some other pattern might have to be devised to make this easier.   the non_primary mapper() had the one advantage that it could still make use of the whole deferred configuration system, but building that into `AliasedClass` would be a huge undertaking.  so this is very frustrating.

**Comment by zzzeek** [comment]
Well you likely don't need the `AliasedClass` to be global in this case, so it can be simplified:

```python
class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")

    @classmethod
    def __declare_last__(cls):
        aliased_b = aliased(B)
        cls.b_non_primary = relationship(aliased_b)

```

would you be satisfied if I documented the above approach in the [docs](https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#relationship-aliased-class) as the approach to take if mappers are being configured too soon?

**Comment by grant-humphries** [comment]
So with respect to the relationship I described in my initial post I've converted this:

```py
activity_coupling = mapper(
    TrainActivity,
    join(
        TrainActivity,
        VehicleCoupling,
        TrainActivity.vehicle_number == VehicleCoupling.lead_vehicle_number,
        isouter=True
    ),
    non_primary=True
)

VehicleInfo.current_train_activity = relationship(
    activity_coupling,
    primaryjoin=(
        (VehicleInfo.vehicle_number == activity_coupling.c.vehicle_number)
        | (VehicleInfo.vehicle_number == activity_coupling.c.tail_vehicle_number)
    ),
    foreign_keys=VehicleInfo.vehicle_number,
    order_by=activity_coupling.c.scheduled_start_datetime.desc(),
    viewonly=True
)
```

to this:

```py
@classmethod
def __declare_last__(cls):
    ac_join = join(
        TrainActivity,
        VehicleCoupling,
        TrainActivity.vehicle_number == VehicleCoupling.lead_vehicle_number,
        isouter=True
    )

    ac_alias = aliased(
        TrainActivity,
        ac_join,
        'activity_coupling'
    )

    cls.current_train_activity = relationship(
        ac_alias,
        primaryjoin=(
            (cls.vehicle_number == ac_join.c.train_activity_vehicle_number)
            | (cls.vehicle_number == ac_join.c.vehicle_coupling_tail_vehicle_number)
        ),
        foreign_keys=cls.vehicle_number,
        order_by=ac_join.c.train_activity_scheduled_start_datetime.desc(),
        viewonly=True
    )
```

and it appears to work.  One thing that isn't clear in [this example](https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#relationship-to-aliasedclass-replaces-the-need-for-non-primary-mappers) is that the column names that are referenced in the `primaryjoin` on the `Join` object are an underscore separated concatenation of the table and column names.  It would be nice if you could reference columns on the aliased class directly (but I have no idea what the implications of that would be).

Was also curious if you think passing `flat=True` would have any benefit for this alias; read the docs on that flag a couple of times, but was still having trouble getting my head around it.

With respect to whether I'm satisfied with this approach, it works so that's good enough for me, and I'll  defer you as to whether this is viable permanent solution for implementing relationships of this type.  Thanks again for helping me out with this and the for all the work you do on SQLAlchemy.

**Comment by grant-humphries** [comment]
Actually I just noticed that I get this warning when using the `__declare_last__` approach:

```
c:\users\humphrig\projects\trimet.model.oracle-py3\eggs\sqlalchemy-1.3.3-py3.6-win-amd64.egg\sqlalchemy\orm\mapper.py:1826: 
SAWarning: Property VehicleInfo.current_train_activity on mapped class VehicleInfo->vehicle_info being replaced with new property VehicleInfo.current_train_activity; the old property will be discarded
  % (self._props[key], self, prop)
```

**Comment by zzzeek** [comment]
The `__declare_last__` can potentially be called more than once so try checking with hasattr() first.

**Comment by grant-humphries** [comment]
that resolved it, thanks

**Comment by jekel** [comment]
I have almost same issue, 
with polymorphic self related hierarchy with many to many relationship:

```    
model_poly = with_polymorphic(ModelA, "*", flat=True, aliased=True)
  File "lib/python3.10/site-packages/sqlalchemy/orm/_orm_constructors.py", line 2395, in with_polymorphic
    return AliasedInsp._with_polymorphic_factory(
  File "lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 1079, in _with_polymorphic_factory
    return AliasedClass(
  File "lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 744, in __init__
    self._aliased_insp = AliasedInsp(
  File "lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 981, in __init__
    ent = AliasedClass(
  File "lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 751, in __init__
    else mapper.with_polymorphic_mappers,
  File "lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1256, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2681, in _with_polymorphic_mappers
    self._check_configure()
  File "lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2377, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 4189, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 4230, in _do_configure_registries
    mapper._post_configure_properties()
  File "lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2394, in _post_configure_properties
    prop.init()
  File "lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 559, in init
    self.do_init()
  File "lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1631, in do_init
    self._process_dependent_arguments()
  File "lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1672, in _process_dependent_arguments
    rel_arg._resolve_against_registry(self._clsregistry_resolvers[1])
  File "lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 263, in _resolve_against_registry
    self.resolved = clsregistry_resolver(
  File "lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 539, in __call__
    self._raise_for_name(n.args[0], n)
  File "lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 500, in _raise_for_name
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[ModelA(modela)], expression 'ModelB' failed to locate a name ("name 'ModelB' is not defined"). If this is a class name, consider adding this relationship() to the <class 'models.ModelB'> class after both dependent classes have been defined.
```

`ModelA` - is base class for other modes with pollymorph option. 
`ModelB` is many-to-many intermediate table (from `ModelA` to `ModelA` and is defined before `ModelA`.
So, when i have defined relationship in `ModelA` for child models:

```python
    children = relationship("ModelA",
                          secondary="ModelB",
                          primaryjoin=lambda: remote(ModelA.id) == foreign(ModelB.c.dest),
                          secondaryjoin=lambda: remote(ModelA.id) == foreign(ModelB.c.source),
                          join_depth=0,
                          viewonly=True,
                          uselist=True,

                          )
   ```
i have got error like above.
If i write joins inside relationship using quotes - i got error raised in that line
sqlalchemy version is 2.0.16

**Comment by CaselIT** [comment]
@jekel this does not seem connected to this issue.

It seems you are using the model name in secondary instead of the table name. See docs https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#combining-association-object-with-many-to-many-access-patterns

**Comment by jekel** [comment]
@CaselIT sorry for misunderstanding, i have updated my post with `ModelB` definition. 
btw, workaround with aliased class and relationship inside classmethod works:
```python
    @classmethod
    def __declare_last__(cls):
        j = aliased(ModelB)

        cls.children = relationship(cls,
                                  secondary=j,
                                  primaryjoin=cls.id == j.c.source,
                                  secondaryjoin=cls.id == j.c.dest
                                  foreign_keys=[j.c.dest, j.c.source],
                                  join_depth=0,
                                  viewonly=True,
                                  uselist=True,
                                  )
```

**Comment by CaselIT** [comment]
the name of the table is `"modelb"` not `"ModelB"`. That's the variable name you assigned the table to
