### ISSUE TITLE
Versioning example from docs doesn't work

### ISSUE THREAD

**Issue by antgel** [sqlalchemy/sqlalchemy#4697]
I'm trying to parse the [versioning docs](https://docs.sqlalchemy.org/en/13/orm/examples.html#versioning-objects). They state:

![image](https://user-images.githubusercontent.com/295571/58367397-5a5b7880-7ee7-11e9-898e-8c197ae4dab2.png)

Firstly, I think the correct directory is `examples/versioned_history`. Secondly, the command doesn't work:

```
$ nosetests -v
ERROR

======================================================================
ERROR: test suite for <module 'examples.versioned_history.test_versioning' from '/home/antony/src/git/sqlalchemy-antgel/examples/versioned_history/test_versioning.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antony/.local/lib/python3.6/site-packages/nose/suite.py", line 210, in run                                 
    self.setUp()                    
  File "/home/antony/.local/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp                              
    self.setupContext(ancestor)    
  File "/home/antony/.local/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext                          
    try_run(context, names)         
  File "/home/antony/.local/lib/python3.6/site-packages/nose/util.py", line 453, in try_run    
    inspect.getargspec(func)                                                
  File "/usr/lib/python3.6/inspect.py", line 1076, in getargspec
    DeprecationWarning, stacklevel=2)   
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()

----------------------------------------------------------------------
Ran 0 tests in 0.001s                                                 
                                                                          
FAILED (errors=1)
```

Any clues?

**Comment by zzzeek** [comment]
nose doesn't really run anymore due to Python 3 deprecation warnings.   use py.test test_versioning.py
