### ISSUE TITLE
elementtree examples totally broken for multiple reasons

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4703]
First off, "pickle.py" is being imported as "import pickle" due to relative module imports in Python 3.  so that has to move.

Next, in 1.2, neither python 2 nor python 3 can print the XML:

```
Traceback (most recent call last):
  File "optimized_al.py", line 223, in <module>
    print(document)
  File "optimized_al.py", line 87, in __str__
    self.element.write(buf)
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 777, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 836, in _get_writer
    yield file.write
  File "/usr/lib64/python3.7/contextlib.py", line 511, in __exit__
    raise exc_details[1]
  File "/usr/lib64/python3.7/contextlib.py", line 496, in __exit__
    if cb(*exc_details):
  File "/usr/lib64/python3.7/contextlib.py", line 383, in _exit_wrapper
    callback(*args, **kwds)
TypeError: string argument expected, got 'bytes'

```

in 1.3, we get no results back:

```
Traceback (most recent call last):
  File "optimized_al.py", line 233, in <module>
    .filter(and_(_Node.tag == "field1", _Node.text == "hi"))
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3288, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

```

**Comment by zzzeek** [comment]
OK reason #1 was #4426 so that should be fixed

reason #2 is #4704.  with that, the examples work in 1.3
