### ISSUE TITLE
optimized statement in load_scalar_attributes needs to cancel with_polymorphic settings

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4718]
We are falling back to name-based column matching when load_scalar_attribubtes() makes use of from_statement() and there is a with_polymorphic on the mapper.

What does it mean if someone has with_polymorphic on an aliased query, and then they use query.from_statement()?   should we assume from_statement is always local table columns, and we cancel query._polymorpic_adapters entirely? or do we need to put a new adapter in the adapter chain?   since "statement" is a non aliased SELECT it doesn't seem like we can use _from_obj_alias here,  or at least the wrap() thing does not seem to be working.

**Comment by zzzeek** [comment]
this is likely for 1.4 but seeing if it can be a safer change for 1.3

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use RowProxy for ORM keyed tuple** https://gerrit.sqlalchemy.org/1300

**Comment by zzzeek** [comment]
to demonstrate:

```
diff --git a/lib/sqlalchemy/engine/result.py b/lib/sqlalchemy/engine/result.py
index 480d086ff..b531bbbce 100644
--- a/lib/sqlalchemy/engine/result.py
+++ b/lib/sqlalchemy/engine/result.py
@@ -620,6 +620,9 @@ class ResultMetaData(object):
                         break
                 else:
                     result = None
+            if result is not None:
+                assert False
+
         if result is None:
             if raiseerr:
                 raise exc.NoSuchColumnError(

```

meaning, we fell back to key lookup, and the column we wanted is there.   our column should already be in the keymap.
then run:

    py.test test/orm/inheritance/test_polymorphic_rel.py

failures are shown in load_scalar_attributes:

```
__________________________________ PolymorphicAliasedJoinsTest_sqlite+pysqlite_3_26_0.test_with_polymorphic_three ___________________________________
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/inheritance/test_polymorphic_rel.py", line 723, in test_with_polymorphic_three
    self.assert_sql_count(testing.db, go, 3)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 567, in assert_sql_count
    db, callable_, assertsql.CountStatements(count)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 547, in assert_sql_execution
    result = callable_()
  File "/home/classic/dev/sqlalchemy/test/orm/inheritance/test_polymorphic_rel.py", line 720, in go
    self._emps_wo_relationships_fixture(),
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 237, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/entities.py", line 89, in __eq__
    battr = getattr(b, attr)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 278, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 709, in get
    value = state._load_expired(state, passive)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/state.py", line 675, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 966, in load_scalar_attributes
    refresh_state=state,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 208, in load_on_ident
    identity_token=identity_token,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3247, in one
    ret = self.one_or_none()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3216, in one_or_none
    ret = list(self)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 392, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 65, in instances
    for query_entity in query._entities
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 65, in <listcomp>
    for query_entity in query._entities
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 4195, in row_processor
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 421, in _instance_processor
    context, path, mapper, result, adapter, populators
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/interfaces.py", line 573, in create_row_processor
    context, path, loader, mapper, result, adapter, populators
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/strategies.py", line 223, in create_row_processor
    getter = result._getter(col, False)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/result.py", line 731, in _getter
    return getter(key, raiseerr)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/result.py", line 648, in _getter
    ret = self._key_fallback(key, raiseerr)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/result.py", line 624, in _key_fallback
    assert False
AssertionError

```


the changes for this need to be pulled out of https://gerrit.sqlalchemy.org/1300 and isolated.

**Comment by zzzeek** [comment]
so in the real world, with_polymorphic with aliased statements is not a real use case for joined inheritance mappers.  we have lots of tests for this but this is not something generally useful.   in this case, we will cancel out the with polymorphic selectable, if any, so that the optimized select doesn't have to work around it.   this also introduces that the Query or whatever replaces it in 2.0 needs to be able to cancel out polymorphic selectables in some way at least as private API.

**Comment by zzzeek** [comment]
OK it works with regular aliased(), we can go with that.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Cancel polymorphic loading in optimized get** https://gerrit.sqlalchemy.org/1485

**Comment by zzzeek** [comment]
interestingly, the patch does not work in 1.3.   so will keep this on just 1.4, although it might be nice to identify what in 1.4 allows it to work.
