### ISSUE TITLE
mysql+pymysql in connection string doesn't work but mysql:// works

### ISSUE THREAD

**Issue by sagarun** [sqlalchemy/sqlalchemy#4721]
This could be something stupid i am missing, When my connection string has "pymysql" driver i get operational error, when i just use "mysql" driver the connection works.
```
python 2.7.12 (default, Nov  8 2016, 23:50:52) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as db
>>> engine = db.create_engine('mysql+pymysql://root:<passwordhidden>@localhost:3306/keystone')
>>> engine.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2193, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2293, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/saga/migration-scripts/test/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)


>>> import sqlalchemy as db
>>> engine = db.create_engine('mysql://root:<passwordhidden>@localhost:3306/keystone')
>>> engine.connect()
<sqlalchemy.engine.base.Connection object at 0x7f7327d25bd0>
```
I am using 
SQLAlchemy==1.3.4
MySQL-python==1.2.5
PyMySQL==0.9.3

Perconda-server-57 is my mysql server

rpm -qa|grep Percona
Percona-Server-client-57-5.7.26-29.1.el7.x86_64
Percona-Server-devel-57-5.7.26-29.1.el7.x86_64
Percona-Server-shared-57-5.7.26-29.1.el7.x86_64
Percona-Server-server-57-5.7.26-29.1.el7.x86_64
Percona-Server-shared-compat-57-5.7.26-29.1.el7.x86_64

**Comment by zzzeek** [comment]
so this is not related to SQLAlchemy, it has to do with the mysqlclient driver vs. pymysql.   if i had to guess, mysqlclient is likely looking at a .my.cnf file in your home directory because it uses the native drivers.  can you check that out?

**Comment by zzzeek** [comment]
that is:```


import MySQLdb
MySQLdb.connect(user='root', passwd='password', host="localhost", port=3306, dbname="keystone")

```
then the same thing for "import pymysql"

**Comment by sagarun** [comment]
@zzzeek  Thanks, i think it has do with me using "localhost" vs "127.0.0.1" When i used 127.0.0.1 both seems to work. Totally weird. Thanks for the help!

**Comment by zzzeek** [comment]
seems like you're good for now

**Comment by zzzeek** [comment]
oh i even know what the problem is, you have an auth entry that's against 'root'@'127.0.0.1', mysqlclient is doing the name resolution and pymysql isn't.    *or*, maybe this has to do with mysqlclient making a unix socket and pymysql isn't, something like that.
