### ISSUE TITLE
SQL Alchemy and MySQL Type Error when Updating Object

### ISSUE THREAD

**Issue by zerox1212** [sqlalchemy/sqlalchemy#4749]
I have a Flask web app using SQL Alchemy. Everything works great except for one strange instance that I can't figure out.

I update many object attributes throughout my code, but in this case I get a `TypeError`.

Code:
```python
    if user.subscription:
        # subscription is existing
        # update the details locally
        user.subscription.project_limit = limit
        user.subscription.expiration = _ts_to_dt(subscription.current_period_end)
        user.subscription.trial_expiration = _ts_to_dt(subscription.trial_end)
        user.subscription.sub_plan_id = subscription.plan.id
        user.subscription.sub_plan_name = subscription.plan.name
        user.subscription.sub_status = subscription.status
        user.subscription.sub_trial_end = subscription.trial_end

        db.session.commit()
```
When `db.session.commit()` is called I get this stack trace:
`2019-07-02 22:41:18,676:   File "/home/foobar/site/mysite/mywebapp/sub_utils.py", line 177, in _update_local_sub
2019-07-02 22:41:18,676:     db.session.commit()
2019-07-02 22:41:18,677:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
2019-07-02 22:41:18,677:     return getattr(self.registry(), name)(*args, **kwargs)
2019-07-02 22:41:18,677:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
2019-07-02 22:41:18,677:     self.transaction.commit()
2019-07-02 22:41:18,677:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
2019-07-02 22:41:18,677:     self._prepare_impl()
2019-07-02 22:41:18,677:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
2019-07-02 22:41:18,677:     self.session.flush()
2019-07-02 22:41:18,677:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
2019-07-02 22:41:18,678:     self._flush(objects)
2019-07-02 22:41:18,678:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
2019-07-02 22:41:18,678:     transaction.rollback(_capture_exception=True)
2019-07-02 22:41:18,678:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
2019-07-02 22:41:18,678:     compat.reraise(exc_type, exc_value, exc_tb)
2019-07-02 22:41:18,678:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
2019-07-02 22:41:18,678:     raise value
2019-07-02 22:41:18,678:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
2019-07-02 22:41:18,678:     flush_context.execute()
2019-07-02 22:41:18,679:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
2019-07-02 22:41:18,679:     rec.execute(self)
2019-07-02 22:41:18,679:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
2019-07-02 22:41:18,679:     uow
2019-07-02 22:41:18,679:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
2019-07-02 22:41:18,679:     mapper, table, update)
2019-07-02 22:41:18,679:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
2019-07-02 22:41:18,679:     execute(statement, multiparams)
2019-07-02 22:41:18,680:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
2019-07-02 22:41:18,680:     return meth(self, multiparams, params)
2019-07-02 22:41:18,680:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
2019-07-02 22:41:18,680:     return connection._execute_clauseelement(self, multiparams, params)
2019-07-02 22:41:18,680:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
2019-07-02 22:41:18,680:     compiled_sql, distilled_params
2019-07-02 22:41:18,680:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
2019-07-02 22:41:18,680:     context)
2019-07-02 22:41:18,681:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
2019-07-02 22:41:18,681:     util.reraise(*exc_info)
2019-07-02 22:41:18,681:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
2019-07-02 22:41:18,681:     raise value
2019-07-02 22:41:18,681:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
2019-07-02 22:41:18,681:     context)
2019-07-02 22:41:18,681:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
2019-07-02 22:41:18,681:     cursor.execute(statement, parameters)
2019-07-02 22:41:18,682:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/MySQLdb/cursors.py", line 234, in execute
2019-07-02 22:41:18,682:     args = tuple(map(db.literal, args))
2019-07-02 22:41:18,682:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/MySQLdb/connections.py", line 316, in literal
2019-07-02 22:41:18,682:     s = self.escape(o, self.encoders)
2019-07-02 22:41:18,682:   File "/home/foobar/.virtualenvs/cvirt2/lib/python3.6/site-packages/MySQLdb/converters.py", line 90, in quote_tuple
2019-07-02 22:41:18,682:     return "(%s)" % (','.join(escape_sequence(t, d)))
2019-07-02 22:41:18,682: TypeError: sequence item 0: expected str instance, bytes found
`

Normally I wouldn't ask for help on something like this, but it's triggered by a Webhook that only works on a live system so it's very difficult to debug.

While researching this I found the source of the issue here: https://github.com/PyMySQL/mysqlclient-python/issues/145

How can I use SQL Alchemy so as not to hit this `mysqlclient` bug mentioned above?

**Comment by zzzeek** [comment]
hi - 

please turn on echo=True in your create_engine(), or otherwise [configure logging](https://docs.sqlalchemy.org/en/13/core/engines.html#configuring-logging) so that all SQL statements and their parameters are shown when the error occurs.  Then look at the parameters preceding this stack trace, it is likely that one of them is in the wrong format, such as a tuple where a string is expected, or something like that.

I cannot reproduce this issue and it is possible some part of your program is using MySQLdb directly perhaps, not really sure.

**Comment by zerox1212** [comment]
I will try echo and logging. However I do not think it's the data format, because the below code with the exact same object (from the Webhook) is working.

```python
        # store a few of the subscription details locally
        user.subscription = Subscription(active=True,
                                         expiration=_ts_to_dt(subscription.current_period_end),
                                         trial_expiration=_ts_to_dt(subscription.trial_end),
                                         project_limit=limit,
                                         sub_sub_id=subscription.id,
                                         sub_plan_id=subscription.plan.id,
                                         sub_plan_name=subscription.plan.name,
                                         sub_status=subscription.status,
                                         sub_cur_period_end=subscription.current_period_end,
                                         sub_ended_at=subscription.ended_at,
                                         sub_cancel_at_period_end=subscription.cancel_at_period_end,
                                         sub_trial_end=subscription.trial_end)
```

**Comment by zzzeek** [comment]
I dont  understand the nature of the mysqlclient bug because there are no examples of how to reproduce it with cursor.execute() in that issue but the logic looks to be dealing directly with the parameters passed to cursor.execute().

**Comment by zzzeek** [comment]
Oh you have to show me how to reproduce this at least

**Comment by zerox1212** [comment]
Make a typo and put a comma at the end like this:
`user.subscription.expiration = _ts_to_dt(subscription.current_period_end),`

**Comment by zzzeek** [comment]
I can't reproduce the issue, it accepts it regardless.  I got it to illustrate a bug in SQLAlchemy's logging, though:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
import datetime

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(DateTime)

#e = create_engine("sqlite://", echo=True)
e = create_engine("mysql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

a1 = A(id=1, data=(datetime.datetime.today(), ))
a2 = A(id=2, data=(datetime.datetime.today(), ))
s.add_all([a1, a2])
s.flush()


a2.data = (datetime.datetime.today(), )

s.flush()
```

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/util.py", line 507, in __repr__
    return self._repr_multi(self.params, typ)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/util.py", line 525, in _repr_multi
    self._repr_params(params, elem_type) for params in multi_params
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/util.py", line 525, in <genexpr>
    self._repr_params(params, elem_type) for params in multi_params
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/util.py", line 546, in _repr_params
    ", ".join(trunc(value) for value in params),
TypeError: 'int' object is not iterable

```

**Comment by zerox1212** [comment]
You are doing it a lot different than I did, so I'm not sure if what you are doing is equivalent.

My code is more like this:
```python
class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key=True)
  
    # add one-to-one relationships
    subscription = db.relationship('Subscription', backref='user', uselist=False)


class Subscription(db.Model):
    __tablename__ = 'subscriptions'
    id = db.Column(db.Integer(), primary_key=True)
    expiration = db.Column(db.DateTime())
    trial_expiration = db.Column(db.DateTime())


u = User()
db.session.add(u)
db.session.commit()

user = User.query.filter_by(id=1).first()
user.subscription = Subscription(expiration=datetime.datetime.today(), trial_expiration=datetime.datetime.today())

db.session.commit()

user.subscription.expiration = datetime.datetime.today(),  # typo comma
user.subscription.trial_expiration = datetime.datetime.today()

db.session.commit()
```

In this example I would get the error in the final calling of `db.session.commit()`.

**Comment by zzzeek** [comment]
OK have you upgraded mysqlclient?  I don't get an error on that either if I turn off SQLAlchemy's logging, tested w/ mysqlclient 1.4.1 and 1.4.2.post1
