### ISSUE TITLE
detect key switch doesn't accommodate uselist=True; dynamic not raising for manytoone

### ISSUE THREAD

**Issue by ElfenSterben** [sqlalchemy/sqlalchemy#4772]
```python
class TestDeclaredAttr(BaseModel):
    """
    In response to more and more comment types, add new comment table
    """
    __tablename__ = 'test_declared_attr'

    id = db.Column(db.Integer, primary_key=True)
    message = db.Column(db.Text)

    parent_id = db.Column(db.Integer, nullable=True)
    parent_type = db.Column(db.Text, nullable=True)

    @declared_attr
    def children(cls):
        parent_id = 'TestDeclaredAttr.parent_id'
        parent_type = 'TestDeclaredAttr.parent_type'
        if cls.__name__ == 'TestDeclaredAttr':
            # Comment.comments: we're self-joining
            # we need to mark the remote side of the join
            parent_id = 'remote({})'.format(parent_id)
            parent_type = 'remote({})'.format(parent_type)
        return db.relationship(
            'TestDeclaredAttr',
            primaryjoin=(
                "and_({parent_id} == foreign({cls}.id), {parent_type} == '{cls}')"  # noqa
            ).format(
                parent_id=parent_id, parent_type=parent_type, cls=cls.__name__
            ),
            uselist=True,
            single_parent=True,
            cascade='all, delete-orphan',
            lazy='dynamic',
        )


if __name__ == '__main__':
    BaseModel.metadata.drop_all(engine)
    BaseModel.metadata.create_all(engine)
    a = TestDeclaredAttr(message='1')
    session.add(a)
    session.commit()
    b = TestDeclaredAttr(message='2')
    session.add(b)
    session.commit()
    c = TestDeclaredAttr(message='3')
    session.add(c)
    session.commit()
    b.parent_id = c.id
    b.parent_type = c.__class__.__name__
    session.commit()
    print(b.parent_id, b.parent_type)
    b.parent_id = a.id
    b.parent_type = a.__class__.__name__
    session.commit()
    print(b.parent_id, b.parent_type)
```

Traceback
```python
(3, u'TestDeclaredAttr')
Traceback (most recent call last):
  File "/Users/hpz/Projects/Web/website/test/test_declared_attr.py", line 72, in <module>
    session.commit()
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 540, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 909, in process_saves
    self._process_key_switches(states, uowcommit)
  File "/Users/hpz/.pyenv/versions/Web/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 941, in _process_key_switches
    related_state = attributes.instance_state(dict_[self.key])
KeyError: 'children'

```

**Comment by zzzeek** [comment]
so far it looks like this is a relationship that possibly doesn't make sense and the ORM is not being graceful about letting you know, for example, it never makes sense to put foreign() on a primary key column.

shorter test:

```
from sqlalchemy import and_
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import foreign
from sqlalchemy.orm import relationship
from sqlalchemy.orm import remote
from sqlalchemy.orm import Session

Base = declarative_base()


class TestDeclaredAttr(Base):
    __tablename__ = "test_declared_attr"

    id = Column(Integer, primary_key=True)
    message = Column(Text)

    parent_id = Column(Integer, nullable=True)
    parent_type = Column(Text, nullable=True)


TestDeclaredAttr.children = relationship(
    TestDeclaredAttr,
    primaryjoin=and_(
        remote(TestDeclaredAttr.parent_id) == foreign(TestDeclaredAttr.id),
        remote(TestDeclaredAttr.parent_type) == "TestDeclaredAttr",
    ),
    uselist=True,
    single_parent=True,
    cascade="all, delete-orphan",
    lazy="dynamic",
)


e = engine = create_engine("sqlite://", echo=True)

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

session = Session(e)

a = TestDeclaredAttr(message="1")
b = TestDeclaredAttr(message="2")
c = TestDeclaredAttr(message="3")
session.add_all([a, b, c])
session.commit()

b.parent_id = c.id
b.parent_type = c.__class__.__name__
session.flush()
b.parent_id = a.id
session.commit()

```

**Comment by zzzeek** [comment]
> for example, it never makes sense to put foreign() on a primary key column.
> 
alrighty, I'm wrong on that, the challenge remains, this is not a many-to-one relationship and the ORM thinks it is.

Short of that the relationship here isn't correct, you probably want this:

```

TestDeclaredAttr.children = relationship(
    TestDeclaredAttr,
    primaryjoin=and_(
        remote(foreign(TestDeclaredAttr.parent_id)) == TestDeclaredAttr.id,
        remote(TestDeclaredAttr.parent_type) == "TestDeclaredAttr",
    ),
    single_parent=True,
    cascade="all, delete-orphan",
    lazy="dynamic",
)

```

but I have to think of this as a bug for now because it mis-interpreted the direction of the relationship that conflicted with assumptions about it so these need to be checked.

**Comment by zzzeek** [comment]
the exception will be fixed.  However it's not valid to use "lazy='dynamic'" with a many-to-one relationship, that will now emit a warning which should be a raise ultimately.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fixes for uselist=True with m2o relationships** https://gerrit.sqlalchemy.org/1361

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Fixes for uselist=True with m2o relationships** https://gerrit.sqlalchemy.org/1362

**Comment by ElfenSterben** [comment]
ok，thanks
