### ISSUE TITLE
cx_Oracle 7.2.0 driver with sqlalchemy MemoryError

### ISSUE THREAD

**Issue by mf908** [sqlalchemy/sqlalchemy#4779]
Database: Oracle DB
SQLAlchemy Version: 1.3.6
cx_Oracle Version: 7.2.0

from sqlalchemy import create_engine

engine = create_engine('oracle+cx_oracle://user:password@host:port/?service_name=service')
engine.connect()

Noticeably by downgrading the cx_Oracle version to 7.1.3 or 7.1.2 fixes the issue.

The script returns this trace:

Traceback (most recent call last):
  File "outage_extractor.py", line 88, in <module>
    main()
  File "outage_extractor.py", line 82, in main
    conn = engine.connect()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 2196, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 103, in __init__
    else engine.raw_connection()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 2296, in raw_connection
    self.pool.unique_connection, _connection
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 2265, in _wrap_pool_connect
    return fn()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 649, in __connect
    ).exec_once(self.connection, self)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\event\attr.py", line 287, in exec_once
    self(*args, **kw)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\event\attr.py", line 297, in __call__
    fn(*args, **kw)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1443, in go
    return once_fn(*arg, **kw)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\dialects\oracle\cx_oracle.py", line 832, in initialize
    super(OracleDialect_cx_oracle, self).initialize(connection)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\dialects\oracle\base.py", line 1140, in initialize
    super(OracleDialect, self).initialize(connection)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 297, in initialize
    connection
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\dialects\oracle\base.py", line 1239, in _get_default_schema_name
    connection.execute("SELECT USER FROM DUAL").scalar()
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\mfung\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
MemoryError

**Comment by zzzeek** [comment]
Hi there -

The cx_Oracle DBAPI is a separate project from SQLAlchemy itself, if you are experiencing a system-level error based on an upgrade from 7.1.x to 7.2, that seems like an issue in cx_Oracle which may be reported at https://github.com/oracle/python-cx_Oracle/issues/, however in this case it appears to already have been reported in https://github.com/oracle/python-cx_Oracle/issues/330

**Comment by zzzeek** [comment]
as I see you are also using windows this is likely to be the same issue.

**Comment by anthony-tuininga** [comment]
@mf908, the fix mentioned by @zzzeek has been released with cx_Oracle 7.2.1.
