### ISSUE TITLE
KeyError: 'partition_by' 

### ISSUE THREAD

**Issue by delijati** [sqlalchemy/sqlalchemy#4788]
I have a script that creates  a dump of an existing DB (csv for data and pickle metadata) The dumping works but if i load the data i get an error [1]. I don't have this problem when i use `SQLAlchemy==1.1.18`.

[1] 

```
2019-07-30 11:34:42.079 | INFO     | app.tools.local_dump:import_data:104 - Creating table (dim_apps)
Traceback (most recent call last):
  File "env/bin/redhsift-local", line 11, in <module>
    load_entry_point('svc-sensor-kpi', 'console_scripts', 'redhsift-local')()
  File "/app/tools/local_dump.py", line 174, in main
    import_data(args.dsn, args.path)
  File "/app/tools/local_dump.py", line 106, in import_data
    table.create()
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 860, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1043, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2858, in visit_create_table
    text += "\n)%s\n\n" % self.post_create_table(table)
  File "/env/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2017, in post_create_table
    if pg_opts["partition_by"]:
  File "/env/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 131, in __getitem__
    return self._defaults[key]
KeyError: 'partition_by'
```

**Comment by zzzeek** [comment]
hi there -

Unfortunately you can't unpickle metadata that was created in one SQLAlchemy major version with another.   you will need to unpickle the metadata under SQLAlhcemy 1.1 , then re-pickle it under a new version.   It is not recommended to use pickle as a format to store table metadata; Python code is the best approach.

**Comment by delijati** [comment]
@zzzeek hi i don't use different versions of `SQLAlchemy` for dump and load. The problem is that only with `SQLAlchemy<=1.1.18` it works.

My usecase:
Dump (from redshift):
1.) Reflect tables
2.) Dump tables -> csv
3.) Dump metadata -> pickle
Load (to postgres):
1.) Load metadata -> pickle
2.) Create tables + schema
3.) Load data -> csv

**Comment by zzzeek** [comment]
Hi again -

The KeyError you refer towards is not possible because the dictionary is a special dictionary called a _DialectArgDict which does not throw KeyError for that particular key because it is guaranteed to have "partition_by" within it as used within the Postgresql dialect, so I cannot reproduce your error.

Here is a demonstration script illustrating the same logical operation you are doing against MySQL and then Postgresql:

```

import pickle

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table


m = MetaData()

t = Table(
    't', m, Column('q', Integer)
)
e1 = create_engine("mysql://scott:tiger@localhost/test", echo=True)
m.create_all(e1)

m2 = MetaData()
t2 = Table('t', m2, autoload_with=e1)


m3 = pickle.loads(pickle.dumps(m2))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
m3.drop_all(e)
m3.create_all(e)

```

you haven't provided any test case so I have very little to go on, can you please try the above code against redshift and see if it produces a problem?  also need exact version of SQLAlchemy in use, Python interpreter version, type of pickling, etc.

**Comment by zzzeek** [comment]
also if you can send me the pickled data which produces this problem as an attachment, also very helpful.  thanks!

**Comment by zzzeek** [comment]
preferably a pickle of just one small table that reproduces the problem.

**Comment by delijati** [comment]
Args sorry that was my fault i was using different `SQLAlchemy` versions. Sorry for the noise.

**Comment by zzzeek** [comment]
OK , great, I spent a bunch of time seeing how you could otherwise be getting that KeyError and couldn't see it.    likely in 1.1 that dictionary is just a plain dictionary and it got pickled.   pickle is really not very good.
