### ISSUE TITLE
session.commit() causing TypeError: NoneType object is not callable

### ISSUE THREAD

**Issue by matthiasunt** [sqlalchemy/sqlalchemy#4818]
I'm getting a `TypeError: NoneType object is not callable` when I'm committing changes to my SQLAlchemy (1.3.6) session.

My Python version: 3.7

**My code:**
```
engine = create_engine(
    os.getenv('DB_ADAPTERS') + '://' +
    os.getenv('DB_USER') + ':' +
    os.getenv('DB_PASSWORD') + '@' +
    os.getenv('DB_HOST') + '/' +
    os.getenv('DB_NAME') + '?charset=utf8mb4'
)
Session = sessionmaker(autoflush=False)
Session.configure(bind=engine)
session = Session()

try:
  posts_soup = BeautifulSoup(fech_posts(), "html.parser")
  posts = posts_soup.find_all('div', class_='uk-width-1-1 zebra')
  for post in posts:
    data = parse_post_data(post)
    session.add(data)
  session.commit()
except:
  session.rollback()
  raise
finally:
  session.close()
```
**The full stack trace:**
```
    Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1178, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/matthias/Dev/Git/sn-spider/src/main.py", line 13, in fetch_latest_posts
    count = fetch_new_posts()
  File "/Users/matthias/Dev/Git/sn-spider/src/posts_scraper.py", line 62, in fetch_new_posts
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/usr/local/lib/python3.7/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/usr/local/lib/python3.7/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/usr/local/lib/python3.7/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
TypeError: 'NoneType' object is not callable
```

**Comment by zzzeek** [comment]
hi there -

This looks like a bug in [pymysql](https://github.com/pymysql/pymysql), however I can't know for sure without:

1. table definition
2. actual data being inserted into this table
3. version of pymysql in use
4. version of MySQL / MariaDB in use
5. operating system
6. issue appears in a certain SQLAlchemy version or always happens?

otherwise maybe over at pymysql they know what causes this.

**Comment by matthiasunt** [comment]
You can close this issue, I managed to fix it. I tried to insert a value that mismatched my models' data type (forgot to cast it to a string).
Thank you for your time anyways :)
