### ISSUE TITLE
MetaData.reflect() fails on FTS5 db

### ISSUE THREAD

**Issue by abitrolly** [sqlalchemy/sqlalchemy#4867]
I can not debug this further. The error below occurs when trying to reflect on `sqlite:////home/anatoli/.cache/tracker/meta.db` which seems to use https://sqlite.org/fts5.html extension.

```
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such tokenizer: TrackerTokenizer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqlalchemy_schemadisplay.py", line 278, in <module>
    sys.exit(main(arg_dburl, arg_outpng))
  File "sqlalchemy_schemadisplay.py", line 250, in main
    concentrate=False # Don't try to join the relation lines together
  File "sqlalchemy_schemadisplay.py", line 170, in create_schema_graph
    metadata.reflect()
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4249, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 496, in __new__
    metadata._remove_table(name, schema)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 491, in __new__
    table._init(name, metadata, *args, **kw)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 585, in _init
    resolve_fks=resolve_fks,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 609, in _autoload
    _extend_on=_extend_on,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1612, in run_callable
    return callable_(self, *args, **kwargs)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 431, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 646, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 373, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 56, in cache
    ret = fn(self, con, *args, **kw)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1638, in get_columns
    connection, "table_info", table_name, schema=schema
  File "/venv/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2050, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1155, in _execute_text
    parameters,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such tokenizer: TrackerTokenizer
[SQL: PRAGMA main.table_info("fts5")]
(Background on this error at: http://sqlalche.me/e/e3q8)
```
```

**Comment by zzzeek** [comment]
hi there -

this is not a SQLAlchemy error, there is no 'TrackerTokenizer' object in SQLAlchemy.  

it looks like you're somehow using this functionality https://www.sqlite.org/fts3.html#tokenizer but after 5 minutes of googling I can't find any background on this error message. I would suggest writing to the sqlite mailing list: http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

**Comment by abitrolly** [comment]
`sqlite3 /home/anatoli/.cache/tracker/meta.db .dump` shows only one reference to `TrackerTokenizer`.
```
INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)VALUES('table','fts5','fts5',0,'CREATE VIRTUAL TABLE fts5 USING fts5(content="fts_view", "nfo:fileName", "nco:title", "nfo:genre", "nmm:genre", "mtp:creator", "nco:nameFamily", "nco:nameGiven", "nco:nameAdditional", "nco:phoneNumber", "nao:prefLabel", "nao:description", "nco:fullname", "nco:nickname", "nco:contactGroupName", "nfo:tableOfContents", "ncal:comment", "ncal:location", "ncal:summary", "ncal:contact", "ncal:description", "nmo:messageSubject", "nmm:albumTitle", "nmm:artistName", "nco:department", "nco:role", "nco:note", "nie:keyword", "nco:imID", "nco:imNickname", "nco:emailAddress", "nmm:category", "nfo:fontFamily", "nco:region", "nco:country", "nco:extendedAddress", "nco:streetAddress", "nco:postalcode", "nco:locality", "nco:county", "nco:district", "nco:pobox", "nie:title", "nie:subject", "nie:plainTextContent", "nie:description", "nie:comment", "nid3:title", "nid3:albumTitle", "nid3:contentType", tokenize=TrackerTokenizer)');
```
I am sure this DB is using custom tokenizer described in https://sqlite.org/fts5.html#extending_fts5 and still I don't see the reason to fail on `.reflect()`. In the end `sqlite3 .dump` works correcly.

**Comment by zzzeek** [comment]
> and still I don't see the reason to fail on .reflect(). In the end sqlite3 .dump works correcly.

I don't either, because again, I know nothing about this SQLite feature or error message.

Your stack trace illustrates that cursor.execute() fails when it runs the command `PRAGMA main.table_info("fts5")`.      Try this script:

```
import sqlite3 
conn = sqlite3.connect("/path/to/my/database")
cursor = conn.cursor()
cursor.execute('PRAGMA main.table_info("fts5")')

```

you should get the same error.  Then report it to the SQLite mailing list or the Python bug tracker.

**Comment by abitrolly** [comment]
```
Your mail to 'sqlite-users' with the subject

    PRAGMA table_info fails with "no such tokenizer"

Is being held until the list moderator can review it for approval.
```

**Comment by zzzeek** [comment]
hey great, you got the same error message with plain sqlite.    if you want to set up tokenizers and such on the pysqlite connection when you connect, take a look at the connect event:   https://docs.sqlalchemy.org/en/13/core/events.html?highlight=connect#sqlalchemy.events.PoolEvents.connect

**Comment by abitrolly** [comment]
I don't see any example of setting up tokenizers with the link provided.

**Comment by zzzeek** [comment]
oh!  you got a reply quite a while ago.  you need to subscribe to that list to be able to get replies.    even their archive is members only which is quite ridiculous however I can show you the thread on a mirror here: http://sqlite.1065341.n5.nabble.com/PRAGMA-table-info-fails-with-quot-no-such-tokenizer-quot-td108742.html

**Comment by abitrolly** [comment]
Thanks. It is strange that I got no reply at all. Not even in spam folder.

Is there a way to know that DB needs tokenizers of other extensions without failing with the error?

**Comment by zzzeek** [comment]
yes I know, i've emailed the sqlite list to complain about their closed list practices.

as mentioned before I don't know anything about this tokenizer feature or how it works.

**Comment by abitrolly** [comment]
Fair enough. Still I think that `.reflect()` should not fail here. It could mention that SQLite is using extensions or custom Tokenizers which are not loaded.

**Comment by zzzeek** [comment]
how would it do that?

**Comment by zzzeek** [comment]
i mean, the error you are getting already tells you exactly that, "sqlite is using extensions or custom tokenizers which are not loaded".   It's on them that they have not documented what this means.

**Comment by abitrolly** [comment]
I guess it is okay for now.

**Comment by zzzeek** [comment]
sorry this is difficult.  sqlite is really a much more rough database than people realize.    handy for sure but its issue and development process is a bit opaque.
