### ISSUE TITLE
mysql+pyodbc character set sniffing query now throws TypeError 

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4869]
Using SQLAlchemy built from current master (2c34d25), this code

```python
import sys

from sqlalchemy import __version__ as sa_version, create_engine, text

print(sys.version)
# 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

print(f'SQLAlchemy {sa_version}, pandas {pd.__version__}, pyodbc {pyodbc.version}')
# SQLAlchemy 1.4.0b1, pandas 0.25.1, pyodbc 4.0.27

sqlalchemy_url = 'mysql+pyodbc://@hpMySQL'
engine = create_engine(sqlalchemy_url, echo=False)
result = engine.execute(text("SELECT 1 AS foo")).fetchone()
print(result)
```

results in

```
Traceback (most recent call last):
  File "C:/Users/Gord/PycharmProjects/py3pandas_test/main.py", line 36, in <module>
    result = engine.execute("SELECT 1 AS foo").fetchone()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2238, in execute
    connection = self.connect(close_with_result=True)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2266, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 100, in __init__
    else engine.raw_connection()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2340, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2310, in _wrap_pool_connect
    return fn()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 336, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 718, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 450, in checkout
    rec = pool._do_get()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 282, in _create_connection
    return _ConnectionRecord(self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 395, in __init__
    self.__connect(first_connect_check=True)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 607, in __connect
    ).exec_once_unless_exception(self.connection, self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 322, in __call__
    fn(*args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\langhelpers.py", line 1506, in go
    return once_fn(*arg, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\create.py", line 535, in first_connect
    dialect.initialize(c)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\base.py", line 2376, in initialize
    self._connection_charset = self._detect_charset(connection)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\pyodbc.py", line 62, in _detect_charset
    rs = connection.execute("SHOW VARIABLES LIKE 'character_set%%'")
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 986, in execute
    return self._execute_text(object_, multiparams, params)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1159, in _execute_text
    parameters,
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1268, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1490, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\default.py", line 545, in do_execute
    cursor.execute(statement, parameters)
TypeError: The first argument to execute must be a string or unicode query.

Process finished with exit code 1
```

**Comment by zzzeek** [comment]
Hi Gord -

the mysql+pyodbc dialect is never tested and pyodbc itself works very poorly with it. however, what does pdb say if you see what kind of object "statement" is? Run py.test with --pdb and it will drop you into a pdb shell when the test fails. i use this feature heavily.



On Sun, Sep 29, 2019, at 10:41 AM, Gord Thompson wrote:

> Using SQLAlchemy built from current master (2c34d25), this code

> import sys

> from sqlalchemy import __version__ as sa_version, create_engine, text

> print(sys.version)
> # 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

> print(f'SQLAlchemy {sa_version}, pandas {pd.__version__}, pyodbc {pyodbc.version}')
> # SQLAlchemy 1.4.0b1, pandas 0.25.1, pyodbc 4.0.27

sqlalchemy_url = 'mysql+pyodbc://@hpMySQL'
engine = create_engine(sqlalchemy_url, echo=False)
result = engine.execute(text("SELECT 1 AS foo")).fetchone()
> print(result)
> results in

> `Traceback (most recent call last):
  File "C:/Users/Gord/PycharmProjects/py3pandas_test/main.py", line 36, in <module>
    result = engine.execute("SELECT 1 AS foo").fetchone()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2238, in execute
    connection = self.connect(close_with_result=True)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2266, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 100, in __init__
    else engine.raw_connection()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2340, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 2310, in _wrap_pool_connect
    return fn()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 336, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 718, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 450, in checkout
    rec = pool._do_get()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 282, in _create_connection
    return _ConnectionRecord(self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 395, in __init__
    self.__connect(first_connect_check=True)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\pool\base.py", line 607, in __connect
    ).exec_once_unless_exception(self.connection, self)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\event\attr.py", line 322, in __call__
    fn(*args, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\langhelpers.py", line 1506, in go
    return once_fn(*arg, **kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\create.py", line 535, in first_connect
    dialect.initialize(c)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\base.py", line 2376, in initialize
    self._connection_charset = self._detect_charset(connection)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\pyodbc.py", line 62, in _detect_charset
    rs = connection.execute("SHOW VARIABLES LIKE 'character_set%%'")
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 986, in execute
    return self._execute_text(object_, multiparams, params)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1159, in _execute_text
    parameters,
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1268, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1490, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\default.py", line 545, in do_execute
    cursor.execute(statement, parameters)
TypeError: The first argument to execute must be a string or unicode query.

Process finished with exit code 1
`

**Comment by gordthompson** [comment]
As I suspected, `statement` is a `bytes` object

```
E   TypeError: The first argument to execute must be a string or unicode query.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>
> c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\default.py(545)do_execute()
-> cursor.execute(statement, parameters)
(Pdb) type(statement)
<class 'bytes'>
```

pyodbc running under Python_3 doesn't accept those.

**Comment by gordthompson** [comment]
I get the impression that the mysql+pyodbc dialect tried valiantly to work around the (admitted) deficiencies in pyodbc's Unicode handling prior to version 4. Now, if the dialect could simply do the equivalent of

```python
cnxn = pyodbc.connect(connection_string)
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setencoding(encoding='utf-8')
```

(as documented [here](https://github.com/mkleehammer/pyodbc/wiki/Unicode#mysql-and-postgresql)) then that might simplify things considerably, at least for Python_3.

**Comment by sqla-tester** [comment]
OK if it's getting bytes in py3k there's a flag to set:

supports_unicode_statements = True

looks like the mysql driver is hardcoding to false. likely can just set it to true as it is hardcoded to true in the base, meaning that works on py2k also.


On Sun, Sep 29, 2019, at 1:19 PM, Gord Thompson wrote:
> I get the impression that the mysql+pyodbc dialect tried valiantly to work around the (admitted) deficiencies in pyodbc's Unicode handling prior to version 4. Now, if the dialect could simply do the equivalent of

> cnxn = pyodbc.connect(connection_string)
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setencoding(encoding='utf-8')

**Comment by zzzeek** [comment]
i was answering emails and just realzied this is a GH issue :)

**Comment by zzzeek** [comment]
is there any modern use case for mysql + pyodbc ?

**Comment by gordthompson** [comment]
> looks like the mysql driver is hardcoding to false

Yes, indeed. After I changed

https://github.com/sqlalchemy/sqlalchemy/blob/2c34d2503a17316cae3282192405b9b9d60df6fe/lib/sqlalchemy/dialects/mysql/pyodbc.py#L43

to

```python
    supports_unicode_statements = True
```

the error went away.

> is there any modern use case for mysql + pyodbc ?

Clearly there is not an overwhelming demand for it. I was just curious to see if it could be a viable alternative given that comments in the SQLAlchemy user documentation and code refer to

http://code.google.com/p/pyodbc/issues/detail?id=25

which is an issue from over ten years ago.

The other potential source of interest is from people who already work with MySQL via ODBC and would prefer to use pyodbc instead of installing a "whole other thing" (for DB-API) when they already have pyodbc and MySQL Connector/ODBC installed.

**Comment by gordthompson** [comment]
After making the above code change I tried running the dialect test suite just for fun. I get "4 passed, 9 skipped, 25 error", but the errors all seem to be of the form:

```
test setup failed
Traceback (most recent call last):
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\testing\suite\test_reflection.py", line 150, in setup_bind
    options=dict(poolclass=pool.StaticPool)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\testing\engines.py", line 261, in testing_engine
    engine = create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\create.py", line 434, in create_engine
    dialect = dialect_cls(**dialect_args)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\pyodbc.py", line 51, in __init__
    super(MySQLDialect_pyodbc, self).__init__(**kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\connectors\pyodbc.py", line 31, in __init__
    super(PyODBCConnector, self).__init__(**kw)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\base.py", line 2146, in __init__
    default.DefaultDialect.__init__(self, **kwargs)
  File "<string>", line 2, in __init__
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\util\deprecations.py", line 120, in warned
    messages[m], exc.SADeprecationWarning, stacklevel=3
sqlalchemy.exc.SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
```

Is there a bit I can flip to prevent the warnings from erroring out the tests?

**Comment by zzzeek** [comment]
just one more line to change, remove the line :

  kw.setdefault("convert_unicode", True)

really the whole __init__ method of MySQLDialect_pyodbc.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**remove __init__ from MySQLDialect_pyodbc** https://gerrit.sqlalchemy.org/1490
