### ISSUE TITLE
test suite: test_round_trip in TimeTest fails for mysql+pyodbc

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4879]
When running the test suite under the mysql+pyodbc dialect, `test_round_trip` under `TimeTest` in test_types.py is failing:

```
FAILED [ 95%]
..\..\git\sqlalchemy\lib\sqlalchemy\testing\suite\test_types.py:269 (TimeTest_mysql+pyodbc_5_7_27_0ubuntu0_18_4_1.test_round_trip)
Traceback (most recent call last):
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\testing\suite\test_types.py", line 278, in test_round_trip
    eq_(row, (compare,))
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\testing\assertions.py", line 237, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\result.py", line 164, in __eq__
    return self._op(other, operator.eq)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\result.py", line 148, in _op
    else op(tuple(self), other)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\engine\result.py", line 78, in __iter__
    yield processor(value)
  File "c:\users\gord\git\sqlalchemy\lib\sqlalchemy\dialects\mysql\types.py", line 427, in process
    microseconds = value.microseconds
AttributeError: 'datetime.time' object has no attribute 'microseconds'
```

`def process(value):` ...

https://github.com/sqlalchemy/sqlalchemy/blob/60e64a2c35e7e5a0125c5fefbf0caf531eeb2eda/lib/sqlalchemy/dialects/mysql/types.py#L424

... assumes that it is being passed a `datetime.timedelta` object so when it receives a `datetime.time` object the code fails.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**fix error in test_round_trip for TimeTest with mysql+pyodbc** https://gerrit.sqlalchemy.org/1491
