### ISSUE TITLE
guessing of parameter style in logging / exceptions fails for positional params plus array parameter

### ISSUE THREAD

**Issue by jekka-ua** [sqlalchemy/sqlalchemy#4902]
sqlalchemy/sql/util.py#478
---------
    def __repr__(self):
        if isinstance(self.params, list):
            typ = self._LIST
            ismulti = self.params and isinstance(
                self.params[0], (list, dict, tuple)
            )
        elif isinstance(self.params, tuple):
            typ = self._TUPLE
            ismulti = self.params and isinstance(
                self.params[0], (list, dict, tuple)
            )
-------------
I'm not sure but as I suppose `ismulti ` is used to make a difference between usual single queries and "multiple" inserts or replaces etc to log that "multiple" data correctly.

But `ismulti==True ` also in case when the first parameter of the usual single query is a list. And in that case sqlalchemy throws `TypeError: '...' object is not iterable ` when logging next non-iterable parameters of the that query.

The simple example to reproduce the bug is a query like 
> select * from smth where id in :set and created>:yesterday

As I'm olny trying this ORM, not sure how to fix it :( . May be there are other attributes to determine "multiple" queries ?

**Comment by zzzeek** [comment]
hi there -

I don't have a case where the first entry of that list would not be list/dict/tuple.  can you please provide a complete runnable example that illustrates the failure you are seeing ?  at least share complete stack trace and what the contents of your .params collection is.

**Comment by zzzeek** [comment]
sorry I'm tyring to come up with what you might have, like:

```
class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(ARRAY(String))



e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
#Base.metadata.create_all(e)

stmt = select([A.__table__]).where(A.data == ['a', 'b', 'c'])

e.execute(stmt)

```

need to know what you are doing.

**Comment by jekka-ua** [comment]
in your case try to add one more parameter to
`stmt = select([A.__table__]).where(A.data == ['a', 'b', 'c'])`
smth like this:
`stmt = select([A.__table__]).where(A.data == ['a', 'b', 'c'] and A.another_data==777)`
where `777 `something non-iterable. As it crashes on the first not-iterable parameter

BTW what I am doing:
```
e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
e.connect() as con:
    # this works
    con.execute(text("select * from A where another_data=:x and data in :set"), set=['a', 'b', 'c'], x=777)  
    # this crashes during logging (only the order of parameters in where statement is changed)
    con.execute(text("select * from A where data in :set and another_data=:x"), set=['a', 'b', 'c'], x=777)  
```

**Comment by jekka-ua** [comment]
the full-stack
```
2019-10-09 17:06:09,890 INFO sqlalchemy.engine.base.Engine
INFO:sqlalchemy.engine.base.Engine:
        SELECT *
        FROM pricelist w1
        WHERE w1.src IN %s and w1.day BETWEEN %s AND %s     
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 507, in __repr__
    return self._repr_multi(self.params, typ)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 525, in _repr_multi
    self._repr_params(params, elem_type) for params in multi_params
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 525, in <genexpr>
    self._repr_params(params, elem_type) for params in multi_params
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 550, in _repr_params
    return "[%s]" % (", ".join(trunc(value) for value in params))
TypeError: 'datetime.date' object is not iterable
Call stack:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/miser-data/crawler/test.py", line 79, in <module>
    get_actual_offers(request)
  File "/var/www/miser-data/crawler/lib/pricerequests.py", line 187, in get_actual_offers
    results = [unflatten_dict(dict(row)) for row in con.execute(direct_flights_oneway_select, **request)]
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1212, in _execute_context
    "%r", sql_util._repr_params(parameters, batches=10)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/log.py", line 110, in info
    self.log(logging.INFO, msg, *args, **kwargs)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/log.py", line 156, in log
    self.logger._log(level, msg, args, **kwargs)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 507, in __repr__
    return self._repr_multi(self.params, typ)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 525, in _repr_multi
    self._repr_params(params, elem_type) for params in multi_params
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 525, in <genexpr>
    self._repr_params(params, elem_type) for params in multi_params
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/util.py", line 550, in _repr_params
    return "[%s]" % (", ".join(trunc(value) for value in params))
TypeError: 'datetime.date' object is not iterable
Call stack:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/miser-data/crawler/test.py", line 79, in <module>
    get_actual_offers(request)
  File "/var/www/miser-data/crawler/lib/pricerequests.py", line 187, in get_actual_offers
    results = [unflatten_dict(dict(row)) for row in con.execute(direct_flights_oneway_select, **request)]
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1212, in _execute_context
    "%r", sql_util._repr_params(parameters, batches=10)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/log.py", line 110, in info
    self.log(logging.INFO, msg, *args, **kwargs)
  File "/var/www/miser-data/venv-crawler/lib/python3.6/site-packages/sqlalchemy/log.py", line 156, in log
    self.logger._log(level, msg, args, **kwargs)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
```

**Comment by zzzeek** [comment]
not in this case becasue psycopg2 takes dictionary arguments, here's the error:
```

[SQL: SELECT a.id, a.data 
FROM a 
WHERE a.data = %(data_1)s AND a.id = %(id_1)s]
[parameters: {'data_1': ['a', 'b', 'c'], 'id_1': 5}]

```

**Comment by zzzeek** [comment]
the test you gave me also doesn't fail, here's the log first:

```
2019-10-09 13:09:51,643 INFO sqlalchemy.engine.base.Engine select * from A where data in %(set)s and another_data=%(x)s
2019-10-09 13:09:51,643 INFO sqlalchemy.engine.base.Engine {'set': ['a', 'b', 'c'], 'x': 777}

```

then it errors out and also reprs there too:

```
[SQL: select * from A where data in %(set)s and another_data=%(x)s]
[parameters: {'set': ['a', 'b', 'c'], 'x': 777}]

```

what version of SQLAlchemy are you running ?

**Comment by jekka-ua** [comment]
SQLAlchemy==1.3.9

and i'm using mysql just in case =).. but i guess it's not important

**Comment by zzzeek** [comment]
that is completely important because mysql uses positional parameters.

**Comment by jekka-ua** [comment]
> that is completely important because mysql uses positional parameters.
sorry =)

**Comment by zzzeek** [comment]
it's just, mysql and sqlite have no ARRAY datatype so there is no case where there would be a list passed as a bound parameter.

**Comment by zzzeek** [comment]
so...I'm still guessing.  you are relying on the mysql driver expanding out a list into a set of IN parameters ? because that doesn't normally work that way.   there's a way it can work in all cases but that's not what you're doing there.

**Comment by jekka-ua** [comment]
in my case it still works..
so will wait until the next problem or will forget about sqlalchemy and live without it like before

thanx for consultation =)

**Comment by zzzeek** [comment]
it's an issue i just needed to know enough context

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**pass executemany context to _repr_params** https://gerrit.sqlalchemy.org/1508

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**pass executemany context to _repr_params** https://gerrit.sqlalchemy.org/1509

**Comment by jekka-ua** [comment]
i'm not sure again but .. =)
i checked your fix you made in your repo
```
        ismulti = self.executemany

        if isinstance(self.params, list):
            typ = self._LIST
            if ismulti is None:
                ismulti = self.params and isinstance(
                    self.params[0], (list, dict, tuple)
                )

        elif isinstance(self.params, tuple):
            typ = self._TUPLE
            if ismulti is None:
                ismulti = self.params and isinstance(
                    self.params[0], (list, dict, tuple)
                )
```
Are you sure that after that fix non-"multi" query will not be processed as "multi" like before ?

As I see after this fix `multi` will earlier set to `True` for "executemany" query only.
In case `self.executemany==False` nothing changed with the previous changeset

**Comment by zzzeek** [comment]
what it's doing is being passed whether or not the query is an "executemany" or not from the outside.  since this is not always known, it still does the "guess" if executemany wasn't passed in, but ideally it would always be passed in and that whole guessing logic can be removed.     once it knows true/false for that, then it can repr appropriately.   your test case is one where it detects "executemany" style when it's not.

**Comment by zzzeek** [comment]
i might make the change more aggressive in 1.4.  for 1.3 just looking to not break things

**Comment by zzzeek** [comment]
all of the guessing in that code turns out to be silly, if you run the parameters through trunc() without determining anything about them it looks 99% the same as if we did all the checking.
