### ISSUE TITLE
Unconsumed column names in spite of reflection.Inspector.from_engine.get_columns showing the presence of the columns

### ISSUE THREAD

**Issue by santhoshnumberone** [sqlalchemy/sqlalchemy#4910]
> SQLAlchemy            1.3.6 

I'm using `sqlalchemy` ORM

I have `four tables` in the `database`

`['eventtable', 'locationTable', 'activityTable', 'usernameTable']`

when i check column names using [sqlalchemy.engine.reflection.Inspector.get_columns](https://docs.sqlalchemy.org/en/13/core/reflection.html?#sqlalchemy.engine.reflection.Inspector.get_columns) 

I get the list of column names of `activityTable`, I get all the names 

> [{'name': 'campaignid', 'type': INTEGER(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'username', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'campaignname', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'device', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'mediaid', 'type': INTEGER(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'fromdate', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'todate', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'popupid', 'type': INTEGER(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'gender', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': 'isactive', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}, {'name': "'isdeleted'", 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}]

but when i try to insert values 

```
def loadDatabaseExtractTable(dbFileLoaction,tableName):

	# Load the exisiting db onto engine
	engine = create_engine(dbFileLoaction,connect_args={'check_same_thread': False})
	# call MetaData
	metadata = MetaData()
	# Extract a specific table from db
	extractedTable = Table(tableName, metadata, autoload=True, autoload_with=engine)
	# connect to the engine
	connection = engine.connect()
	# Session to perform CRUD operations
	Session = sessionmaker(bind=engine)
	session = Session()

	return session,extractedTable,engine

activityTableName = 'activityTable'
activityTableSession,activityTable,activityTableEngine = loadDatabaseExtractTable(c1_database_file,activityTableName)

current_campaign_id = 0
campaignName= 'ahjs'
deviceName= 'assd'
selected_media_id = 1
fromDate = 'jkhdsf'
toDate = 'lksdf'
selected_popup_id = 1
gender ='jkh'
campaign_active = True

activity_details = {'campaignid':current_campaign_id+1,'username':'test1','campaignname':campaignName\
					,'device':deviceName,'mediaid':selected_media_id,'fromdate':fromDate,'todate':toDate\
					,'popupid':selected_popup_id,'gender':gender,'isactive':str(campaign_active),'isdeleted':'False'}

i = insert(activityTable).values(activity_details)
activityTableSession.execute(i)
activityTableSession.commit()
```

I get this error

> Traceback (most recent call last):

>  File "server_v0.1.py", line 112, in <module>
    activityTableSession.execute(i)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1269, in execute
    clause, params or {}

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1098, in _execute_clauseelement
    else None,

>  File "<string>", line 1, in <lambda>
  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 468, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 562, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2387, in visit_insert
    self, insert_stmt, crud.ISINSERT, **kw

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/crud.py", line 62, in _setup_crud_params
    return _get_crud_params(compiler, stmt, **kw)

>  File "/home/ffffff/.virtualenvs/flask-app/lib/python3.6/site-packages/sqlalchemy/sql/crud.py", line 177, in _get_crud_params
    % (", ".join("%s" % c for c in check))
sqlalchemy.exc.CompileError: Unconsumed column names: popupid, mediaid, todate, campaignid, isactive, isdeleted, campaignname, fromdate

Finding hard to resolve this issue?
column exists but still getting `sqlalchemy.exc.CompileError: Unconsumed column names`

please guide, don't know what is happening

**Comment by zzzeek** [comment]
hi there -

need more information:

1. what database backend is this?  Also what OS (e.g. linux, windows) if this is MySQL

2. can you share the CREATE TABLE statement for the "activityTable"?

3. is there more than one table named "activityTable" with different casing, is that the exact lowercase/uppercase name of the table?

4. can you print out the keys of the columns from the "activityTable" object?  like:

    print(activityTable.c.keys())

5. or show its create :

    from sqlalchemy.schema import CreateTable
    print(CreateTable(activityTable).compile(engine)

**Comment by zzzeek** [comment]
no activity, closing
