### ISSUE TITLE
ORM and DictCursor cursor class

### ISSUE THREAD

**Issue by destroy** [sqlalchemy/sqlalchemy#4912]
Got an error when trying to use cursorclass=DictCursor in ORM query (Cursor works fine):

Traceback (most recent call last):
  File "C:\Work\Sources\steam\test.py", line 46, in <module>
    r = ItemsInfo.search_by_name('b')
  File "C:\Work\Sources\steam\steam\models\items_info.py", line 19, in search_by_name
    return common.session.query(ItemsInfo).first()
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3240, in first
    ret = list(self[0:1])
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3018, in __getitem__
    return list(res)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3364, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3379, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\query.py", line 3357, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\session.py", line 1124, in connection
    execution_options=execution_options,
  File "C:\Work\python27\lib\site-packages\sqlalchemy\orm\session.py", line 1133, in _connection_for_bind
    conn = engine._contextual_connect(**kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\engine\base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Work\python27\lib\site-packages\sqlalchemy\engine\base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Work\python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\pool\base.py", line 649, in __connect
    ).exec_once_unless_exception(self.connection, self)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\event\attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\event\attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\event\attr.py", line 322, in __call__
    fn(*args, **kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1485, in go
    return once_fn(*arg, **kw)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\engine\strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2375, in initialize
    self._detect_sql_mode(connection)
  File "C:\Work\python27\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2843, in _detect_sql_mode
    self._sql_mode = row[1] or ""
  File "C:\Work\python27\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2943, in __getitem__
    item = self.rowproxy[index]
  File "C:\Work\python27\lib\site-packages\sqlalchemy\engine\result.py", line 109, in __getitem__
    return self._row[index]
KeyError: 1

**Comment by zzzeek** [comment]
hi there -

I'm not familiar with DictCursor.  Can you please provide accurate detail in what exactly it is you are doing ?    SQLAlchemy does not support alternate "cursor" classes at the DBAPI level and there is no need to use them.

**Comment by destroy** [comment]
I had already implemented few QueuePool's in my application where I used "raw sql" queries like connection.cursor().execute()/fetch(). With "Cursor" class fetch returns a tuple of values and I used DictCursor to get dictionary results. Also I wanted to reuse these pools for some new ORM classes, but that error occuried. What are the options? Not sure I want to refactor all code to ORM models, but also want to reuse these pools.. One of idea is: I have a 2 functions that get connection from the pool and return it back to pool. Is it possible to somehow change cursor class to DictCursor there for my internal raw queries? So ORM classes will have their Cursor class.

**Comment by destroy** [comment]
Welp, I just noticed that cursorclass is a pymysql.connect feature. Not sure what to do now...

**Comment by zzzeek** [comment]
SQLAlchemy's RowProxy (will be called Row in 1.4) already gives you dictionary access.   See https://docs.sqlalchemy.org/en/13/core/tutorial.html#selecting

**Comment by destroy** [comment]
Exactly, I used Pools that way. But now I need to add ORM classes and want to REuse that pool. I ended up on making engine for my old code (and so for a ORM classes) and refactoring
cursor.execute(sql)
cursor.fetch()
to
result = engine.execute(sql)
result.fetch()
And use default Cursor class.

**Comment by zzzeek** [comment]
great
