### ISSUE TITLE
Attribute error in engine/result.py - Nonetype

### ISSUE THREAD

**Issue by swartzd** [sqlalchemy/sqlalchemy#4916]
In my application, queries randomly fail with the following exception.  I believe it is the mySQL server doing something funky but sqlalchemy not handling it well, as well.
It's not reproducible readily however I end up with 10-20 occurrences of this per day (over roughly a few hundred queries).
Python 3.6.5
Amazon Aurora mySQL (`5.7.mysql_aurora.2.03.2`)
sqlalchemy 1.3.9 (has been occurring on many versions up to and including this one)

My code is `result = session.query(Table).filter_by(column_name=variable_name).scalar()` (my actual names redacted) - I use this sort of query a few times in my code and it randomly fails with this exception at any one of them (with different tables).

```Traceback (most recent call last):
  File "redacted", line 81, in redacted
    result = session.query(Table).filter_by(column_name=variable_name).scalar()
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3330, in scalar
    ret = self.one()
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3300, in one
    ret = self.one_or_none()
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3269, in one_or_none
    ret = list(self)
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 65, in instances
    for query_entity in query._entities
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 65, in <listcomp>
    for query_entity in query._entities
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4226, in row_processor
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 405, in _instance_processor
    getter = result._getter(col, False)
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 726, in _getter
    return self._non_result(None)
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1168, in _non_result
    "This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
"
Traceback (most recent call last):
  File "/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 724, in _getter
    getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'
```

Please let me know if there is anything else I can do to assist!

**Comment by zzzeek** [comment]
no acvtivity
