### ISSUE TITLE
Two tests break with SQLite 3.30

### ISSUE THREAD

**Issue by nphilipp** [sqlalchemy/sqlalchemy#4920]
I recently tried to build SQLAlchemy 1.3.10 on Fedora and it failed to build on Rawhide which has SQLite 3.30.1, other releases built fine. Here's the pertinent part of the [build log](https://kojipkgs.fedoraproject.org//work/tasks/9324/38329324/build.log):

````
=================================== FAILURES ===================================
_____________ QueryTest_sqlite+pysqlite_3_30_1.test_order_by_nulls _____________
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/testing/exclusions.py", line 96, in decorate
    return self._do(config._current, fn, *args, **kw)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/testing/exclusions.py", line 125, in _do
    self._expect_success(cfg, name=fn.__name__)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/testing/exclusions.py", line 153, in _expect_success
    fail._as_string(config) for fail in self.fails
AssertionError: Unexpected success for 'test_order_by_nulls' (not postgresql and not oracle and not firebird)
_________________ SessionBindTest.test_column_property_select __________________
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/orm/test_query.py", line 5586, in test_column_property_select
    session.query(func.max(User.score)).scalar()
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/orm/query.py", line 3330, in scalar
    ret = self.one()
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/orm/query.py", line 3300, in one
    ret = self.one_or_none()
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/orm/query.py", line 3269, in one_or_none
    ret = list(self)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/builddir/build/BUILD/SQLAlchemy-1.3.10/test/../lib/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) misuse of aggregate: max()
[SQL: SELECT max((SELECT sum(addresses.id) AS sum_1 
FROM addresses, users 
WHERE addresses.user_id = users.id)) AS max_1]
(Background on this error at: http://sqlalche.me/e/e3q8)
=========================== short test summary info ============================
...
FAILED test/sql/test_query.py::QueryTest_sqlite+pysqlite_3_30_1::test_order_by_nulls
FAILED test/orm/test_query.py::SessionBindTest::test_column_property_select
````

The first one (`test_order_by_nulls`) is easy to fix, I'll submit a PR with it shortly, but I don't know how to fix the `test_column_property_select` one.

**Comment by zzzeek** [comment]
for the second test, this should work, can you try this and add it to your PR ?

```
diff --git a/test/requirements.py b/test/requirements.py
index a0d984ef4..39fac8f7a 100644
--- a/test/requirements.py
+++ b/test/requirements.py
@@ -787,7 +787,7 @@ class DefaultRequirements(SuiteRequirements):
         """target database can select an aggregate from a subquery that's
         also using an aggregate"""
 
-        return skip_if(["mssql"])
+        return skip_if(["mssql", "sqlite"])
 
     @property
     def array_type(self):

```

**Comment by nphilipp** [comment]
> for the second test, this should work, can you try this and add it to your PR ?

I've done so, but also wonder if it was only by accident that this (seemingly) worked in previous SQLite versions.

**Comment by sqla-tester** [comment]
**Nils Philippsen** has proposed a fix for this issue in the **master** branch:

**Expect ordering NULLs to work and skip nested aggregate tests on sqlite >= 3.30.** https://gerrit.sqlalchemy.org/1557

**Comment by sqla-tester** [comment]
**Nils Philippsen** has proposed a fix for this issue in the **rel_1_3** branch:

**Expect ordering NULLs to work and skip nested aggregate tests on sqlite >= 3.30.** https://gerrit.sqlalchemy.org/1558
