### ISSUE TITLE
Reading object attributes can raise DetachedInstanceError

### ISSUE THREAD

**Issue by hhowe29** [sqlalchemy/sqlalchemy#4941]
* sqlalchemy 1.3.9
* python 3.7.3

Reading a column attribute of an object can raise an exception if the object is in a detached state because the session was closed. 

Sample code:
```
from sqlalchemy import Column, String, Integer, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

class Foo(Base):
    __tablename__ = 'foo'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)

engine = create_engine('sqlite:///foo.db', echo=False)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

f = Foo(name='foo1')
print('state=transient : name=', f.name)
session.add(f)
print('state=pending : name=', f.name)
session.commit()
session.close()
print('state=detached : name=', f.name)
```

```
state=transient : name= foo1
state=pending : name= foo1
Traceback (most recent call last):
  File "scratch_46.py", line 23, in <module>
    print('state=detached : name=', f.name)
  File "lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 913, in load_scalar_attributes
    "attribute refresh operation cannot proceed" % (state_str(state))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Foo at 0x7f266c758ac8> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```

I read the suggested link. I don't understand why lazy loading is involved when I fabricated the object entirely in memory.

The exception does not occur if the code is tweaked in any of the following ways
* The `name` atribute is accessed between the `commit` and `close` calls while the object is in the persistent state
* The object is expunges from the session, and the session is left open. Still detached state, but I can access the attribute.

**Comment by hhowe29** [comment]
Closing this. I have it working now that I understand what `expire_on_commit` does. Setting it to false resolves my problem.
