### ISSUE TITLE
sqlalchemy redshift TypeError: unhashable type: 'list' version 1.3.11

### ISSUE THREAD

**Issue by ameier38** [sqlalchemy/sqlalchemy#4984]
After upgrading to 1.3.11, I am getting the following error when trying to reflect a AWS Redshift table: `TypeError: unhashable type: 'list'`. I am using the sqlalchemy-redshift dialect.

```python
from sqlalchemy import create_engine, Table, MetaData
connect_args = dict(sslmode="verify-ca", keepalives_idle=200)
uri = 'redshift+psycopg2://<user>:<pass>@redshift-cluster:5439/my-db'
engine = create_engine(uri, connect_args=connect_args)
meta = MetaData()
t = Table('my_table', meta, schema='my_schema', autoload=True, autoload_with=engine)
```
If I downgrade to 1.3.10 then it works fine. The only data types in the table I am trying to reflect are bigint, timestamp, date, and varchar.

**Comment by zzzeek** [comment]
hi -

can you please supply the complete stack trace, the code above does not indicate anything about the nature of this error

**Comment by vvolkov** [comment]
I had the same today with Python 3.7.4, SQLAlchemy 1.3.11, sqlalchemy-redshift 0.7.5, here is my stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/spectrify", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/spectrify/main.py", line 59, in convert
    sa_table = SqlAlchemySchemaReader(engine).get_table_schema(table)
  File "/usr/local/lib/python3.7/site-packages/spectrify/utils/schema.py", line 38, in get_table_schema
    schema=schema_name
  File "<string>", line 2, in __new__
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/schema.py", line 506, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/schema.py", line 501, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/schema.py", line 595, in _init
    resolve_fks=resolve_fks,
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/schema.py", line 636, in _autoload
    _extend_on=_extend_on,
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2163, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1615, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 460, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 642, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 369, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 50, in cache
    ret = info_cache.get(key)
TypeError: unhashable type: 'list'
```

**Comment by ameier38** [comment]
@zzzeek I added a repo to reproduce: https://github.com/ameier38/sqlalchemy-issue. The reflection works fine with postgres so I am thinking it may be an issue with sqlalchemy-redshift.

**Comment by zzzeek** [comment]
they (sqlalchemy-redshift) are hitting a hard change I had to make to fix #4955.   so what is happening is that they have options like "sortkey" which they are reflecting at https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L583 .   these options get passed back into methods like get_coulmns(), for them it is at https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L418, and the `@reflection.cache` they are using, which is optional, now caches on all the keyword arguments, including the list-based "sortkey" and others we see coming from table arguments.

so redshift has to either a. ensure table kwargs like sortkey and others are hashable, usually by making them into tuples or b. don't use `@reflection.cache`.      

they also should look into having a CI build that tests against the latest SQLAlchemy version.

**Comment by zzzeek** [comment]
https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/180

**Comment by zzzeek** [comment]
hopefully someone can fix this for redshift.   i can in theory try to ignore lists here but then that would persist the original bug in #4955 for redshift.  it's a one-liner on their end.

**Comment by anthnyprschka** [comment]
hi @zzzeek i have similar issue with mysql where it returns `unhashable type: 'bytearray'` when i try to reflect a table. any ideas how to solve that?
