### ISSUE TITLE
UnmappedColumnError on delete cascading when using composite “secondary” joins.

### ISSUE THREAD

**Issue by AdrianVandierAst** [sqlalchemy/sqlalchemy#4992]
I found something that looks like a bug when the deletion of objects is cascading and there is a composite "secondary" join on a child object. An UnmappedColumnError arises during the cascading but if we remove the composite "secondary" join everything works fine. The  UnmappedColumnError is on a column that is not the composite join.  The code below exposes the simplest condition i found to reproduce the bug.

The models:

```python
import sqlalchemy as db
from sqlalchemy.orm import relationship, backref
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class DocumentType(Base):
    __tablename__ = "document_type"
    id = db.Column(
        db.Integer,
        primary_key=True
    )

class PartType(Base):
    __tablename__ = "part_type"
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    document_type_id = db.Column(
        db.Integer,
        db.ForeignKey('document_type.id')
    )
    document_type = relationship(
        'DocumentType',
        backref=backref('part_types', cascade="all")
    )

class Document(Base):
    __tablename__ = "document"
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    type_id = db.Column(
        db.Integer,
        db.ForeignKey('document_type.id')
    )
    type = relationship(
        'DocumentType',
    )

class Part(Base):
    __tablename__ = "part"
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    document_id = db.Column(
        db.Integer,
        db.ForeignKey('document.id')
    )
    document = relationship(
        'Document',
        backref=backref('parts', cascade="all")
    )
    type_id = db.Column(
        db.Integer,
        db.ForeignKey('part_type.id')
    )
    type = relationship(
        'PartType',
    )
    available_types = relationship(
        'PartType',
        secondary=(
            "join("
                "DocumentType,"
                "PartType,"
                "DocumentType.id == PartType.document_type_id"
            ").join("
                "Document,"
                "DocumentType.id == Document.type_id"
            ")"
        ),
        primaryjoin="Part.document_id == Document.id")
```

The code to reproduce:
```python
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

engine = create_engine('sqlite:///:memory:')
Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

session.add(DocumentType(id=1))
session.add(Document(id=1, type_id=1))
session.add(PartType(id=1, document_type_id=1))
session.add(PartType(id=2, document_type_id=1))
session.add(Part(id=1, document_id=1, type_id=1))
session.commit()

doc = session.query(Document).filter_by(id=1).one()
session.delete(doc)
session.commit()
```

The exception:
```
Traceback (most recent call last):
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/sync.py", line 114, in populate_dict
    source, source.dict, l, passive=attributes.PASSIVE_OFF
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 2794, in _get_state_attr_by_column
    prop = self._columntoproperty[column]
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 3398, in __missing__
    % (column, self.mapper)
sqlalchemy.orm.exc.UnmappedColumnError: No column document.id is configured on mapper mapped class Part->part...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug_cascade_complex_join.py", line 111, in <module>
    session.commit()
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "..../lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "..../lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 538, in execute
    self.dependency_processor.process_deletes(uow, states)
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1094, in process_deletes
    "delete",
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1263, in _synchronize
    state, self.parent, associationrow, self.prop.synchronize_pairs
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/sync.py", line 117, in populate_dict
    _raise_col_to_prop(False, source_mapper, l, None, r)
  File "..../lib/python3.6/site-packages/sqlalchemy/orm/sync.py", line 159, in _raise_col_to_prop
    % (source_column, source_mapper, dest_column)
sqlalchemy.orm.exc.UnmappedColumnError: Can't execute sync rule for source column 'document.id'; mapper 'mapped class Part->part' does not map this column.  Try using an explicit `foreign_keys` collection which does not include destination column 'part.document_id' (or use a viewonly=True relation).
```

If we don't create enough data for the available_types to have a value, the deletion works fine.
In the real code, I use a hybrid property for the composite join and it works fine :)
```python
@hybrid_property
def available_types(self):
     return self.document.type.part_types
```

sqlalchemy 1.3.11
python 3.6.9

**Comment by zzzeek** [comment]
hi there -

I haven't looked deeply but it is highly unusual to attempt an exotic "secondary" case without using viewonly=True and the presence of "Document.id" in the primaryjoin would appear to be leading to the issue.

I notice there is no viewonly=True in https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#composite-secondary-joins can I confirm that's how you got to this case?

**Comment by zzzeek** [comment]
the case in the docs has the same issue.   so we just add a viewonly.

**Comment by AdrianVandierAst** [comment]
The way the doc is written now is perfect, I think I wouldn't have ran into that problem :)
