### ISSUE TITLE
test_tzname failures - appear to be related to Python 3.6

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5016]
Just FYI, using the current master (4d6fefa) I get two test failures under Python 3.6.8 on Xubuntu 18.04:

```
(venv) gord@xubuntu64-nbk1:~/git/sqlalchemy$ py.test -k test_tzname --db mssql
========================================================= test session starts =========================================================
platform linux -- Python 3.6.8, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /home/gord/git/sqlalchemy/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/gord/git/sqlalchemy, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.30.0
collected 11081 items / 11075 deselected / 6 selected                                                                                 

test/base/test_utils.py::TimezoneTest::test_tzname[td0-UTC] PASSED                                                              [ 16%]
test/base/test_utils.py::TimezoneTest::test_tzname[td1-UTC+05:00] PASSED                                                        [ 33%]
test/base/test_utils.py::TimezoneTest::test_tzname[td2-UTC+05:10] PASSED                                                        [ 50%]
test/base/test_utils.py::TimezoneTest::test_tzname[td3-UTC+05:10:27] FAILED                                                     [ 66%]
test/base/test_utils.py::TimezoneTest::test_tzname[td4-UTC-02:50] PASSED                                                        [ 83%]
test/base/test_utils.py::TimezoneTest::test_tzname[td5-UTC+05:10:27.000550] FAILED                                              [100%]

============================================================== FAILURES ===============================================================
_____________________________________________ TimezoneTest.test_tzname[td3-UTC+05:10:27] ______________________________________________
Traceback (most recent call last):
  File "/home/gord/git/sqlalchemy/test/base/test_utils.py", line 3154, in test_tzname
    eq_(timezone(td).tzname(None), expected)
ValueError: offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 18627).
__________________________________________ TimezoneTest.test_tzname[td5-UTC+05:10:27.000550] __________________________________________
Traceback (most recent call last):
  File "/home/gord/git/sqlalchemy/test/base/test_utils.py", line 3154, in test_tzname
    eq_(timezone(td).tzname(None), expected)
ValueError: offset must be a timedelta representing a whole number of minutes, not datetime.timedelta(0, 18627, 550).
======================================================= short test summary info =======================================================
FAILED test/base/test_utils.py::TimezoneTest::test_tzname[td3-UTC+05:10:27] - ValueError: offset must be a timedelta representing a ...
FAILED test/base/test_utils.py::TimezoneTest::test_tzname[td5-UTC+05:10:27.000550] - ValueError: offset must be a timedelta represen...
====================================== 2 failed, 4 passed, 11075 deselected in 172.70s (0:02:52) ======================================
```

All the same tests pass under Python 3.8.0 on Windows ...

```
(venv) C:\Users\Gord\git\sqlalchemy>py.test -k test_tzname --db mssql
======================================================= test session starts =======================================================
platform win32 -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- c:\users\gord\git\sqlalchemy\venv\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\Gord\git\sqlalchemy, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.30.0
collected 11081 items / 11075 deselected / 6 selected

test/base/test_utils.py::TimezoneTest::test_tzname[td0-UTC] PASSED                                                           [ 16%]
test/base/test_utils.py::TimezoneTest::test_tzname[td1-UTC+05:00] PASSED                                                     [ 33%]
test/base/test_utils.py::TimezoneTest::test_tzname[td2-UTC+05:10] PASSED                                                     [ 50%]
test/base/test_utils.py::TimezoneTest::test_tzname[td3-UTC+05:10:27] PASSED                                                  [ 66%]
test/base/test_utils.py::TimezoneTest::test_tzname[td4-UTC-02:50] PASSED                                                     [ 83%]
test/base/test_utils.py::TimezoneTest::test_tzname[td5-UTC+05:10:27.000550] PASSED                                           [100%]

========================================= 6 passed, 11075 deselected in 199.19s (0:03:19) =========================================
```

... and also under Python 3.7.5rc1 on Xubuntu 19.10:

```
(venv) gord@Xubu1910-dv7:~/git/sqlalchemy$ py.test -k test_tzname --db mysql
======================================================= test session starts ========================================================
platform linux -- Python 3.7.5rc1, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /home/gord/git/sqlalchemy/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/gord/git/sqlalchemy, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.30.0
collected 11081 items / 11075 deselected / 6 selected                                                                              

test/base/test_utils.py::TimezoneTest::test_tzname[td0-UTC] PASSED                                                           [ 16%]
test/base/test_utils.py::TimezoneTest::test_tzname[td1-UTC+05:00] PASSED                                                     [ 33%]
test/base/test_utils.py::TimezoneTest::test_tzname[td2-UTC+05:10] PASSED                                                     [ 50%]
test/base/test_utils.py::TimezoneTest::test_tzname[td3-UTC+05:10:27] PASSED                                                  [ 66%]
test/base/test_utils.py::TimezoneTest::test_tzname[td4-UTC-02:50] PASSED                                                     [ 83%]
test/base/test_utils.py::TimezoneTest::test_tzname[td5-UTC+05:10:27.000550] PASSED                                           [100%]

========================================= 6 passed, 11075 deselected in 168.68s (0:02:48) ==========================================
```

**Comment by zzzeek** [comment]
adding py36 to jenkins master job and running

**Comment by zzzeek** [comment]
and kaboom, so  let's fix
