### ISSUE TITLE
implement single inheritance discriminator for bulk update/delete and update docs

### ISSUE THREAD

**Issue by pswanston** [sqlalchemy/sqlalchemy#5018]
I ran into an issue where classes that make use of 'polymorphic_on' and 'polymorphic_identity' mapper arguments are not properly specifying their polymorphic_identity column value in the delete operations where clause.
I encountered this issue after upgrading to 1.3.8 from 0.9.8, so it's hard to know when exactly it became an issue.

I've created a unit test that exposes the issue "test/orm/test_update_delete.py::DeletePolymorphicTest::test_delete_with_fetch_polymorphic".
https://github.com/pswanston/sqlalchemy/commit/39e8c16e3fb5848ae71ced7b01ed223209416cd2

I've also attempted to make an example fix of the issue, but it appears to have caused two other test cases to start failing, but I'm not too certain what the failure is due to. (more details below)
https://github.com/pswanston/sqlalchemy/commit/2edf36b43b5a2b20e21d7da04a7ed499b10296bf

With regard to the newly added test I've included the debug output showing the different SQL that is executed against the database with the current code base and my potential fix.
```DELETE FROM staff WHERE name = ?``` vs ```DELETE FROM staff WHERE name = ? AND staff.position IN (?)```

Current failing debug logs
```
pydev test runner error: imported unittest before running pytest.main
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Created new connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200>
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:()
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.1
rootdir: /home/pswanston/workspace/sqlalchemy, inifile: setup.cfg
collected 1 item

test/orm/test_update_delete.py DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:PRAGMA temp.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:
CREATE TABLE staff (
	position VARCHAR(50) NOT NULL, 
	id INTEGER NOT NULL, 
	name VARCHAR(50), 
	sales_stats VARCHAR(50), 
	support_stats VARCHAR(50), 
	PRIMARY KEY (id)
)


INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, sales_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('sales', 'n1', '1')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, sales_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('sales', 'n2', '2')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, support_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('support', 'n1', '3')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, support_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('support', 'n2', '4')
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.sales_stats AS staff_sales_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.sales_stats
INFO:sqlalchemy.engine.base.Engine:('sales',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.support_stats AS staff_support_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.support_stats
INFO:sqlalchemy.engine.base.Engine:('support',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.id AS staff_id 
FROM staff 
WHERE name = ? AND staff.position IN (?)
INFO:sqlalchemy.engine.base.Engine:('n1', 'sales')
INFO:sqlalchemy.engine.base.Engine:DELETE FROM staff WHERE name = ?
INFO:sqlalchemy.engine.base.Engine:('n1',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.sales_stats AS staff_sales_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.sales_stats
INFO:sqlalchemy.engine.base.Engine:('sales',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.support_stats AS staff_support_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.support_stats
INFO:sqlalchemy.engine.base.Engine:('support',)
FDEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return, via agent
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:DELETE FROM staff
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:
DROP TABLE staff
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f83b8545200> rollback-on-return
INFO:sqlalchemy.pool.impl.SingletonThreadPool:Pool recreating
INFO:sqlalchemy.pool.impl.SingletonThreadPool:Pool recreating


=================================== FAILURES ===================================
_ DeletePolymorphicTest_sqlite+pysqlite_3_11_0.test_delete_with_fetch_polymorphic _
Traceback (most recent call last):
  File "/home/pswanston/workspace/sqlalchemy/test/orm/test_update_delete.py", line 1283, in test_delete_with_fetch_polymorphic
    mn1_, mn2_ = sess.query(Support).order_by(Support.support_stats).all()
ValueError: need more than 1 value to unpack
=========================== short test summary info ============================
FAILED test/orm/test_update_delete.py::DeletePolymorphicTest_sqlite+pysqlite_3_11_0::test_delete_with_fetch_polymorphic
=========================== 1 failed in 0.08 seconds ===========================
```

Updated successful debug logs
```
pydev test runner error: imported unittest before running pytest.main
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Created new connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200>
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:()
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.6.6, py-1.8.0, pluggy-0.13.1
rootdir: /home/pswanston/workspace/sqlalchemy, inifile: setup.cfg
collected 1 item

test/orm/test_update_delete.py DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:PRAGMA temp.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:
CREATE TABLE staff (
	position VARCHAR(50) NOT NULL, 
	id INTEGER NOT NULL, 
	name VARCHAR(50), 
	sales_stats VARCHAR(50), 
	support_stats VARCHAR(50), 
	PRIMARY KEY (id)
)


INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, sales_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('sales', 'n1', '1')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, sales_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('sales', 'n2', '2')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, support_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('support', 'n1', '3')
INFO:sqlalchemy.engine.base.Engine:INSERT INTO staff (position, name, support_stats) VALUES (?, ?, ?)
INFO:sqlalchemy.engine.base.Engine:('support', 'n2', '4')
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.sales_stats AS staff_sales_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.sales_stats
INFO:sqlalchemy.engine.base.Engine:('sales',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.support_stats AS staff_support_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.support_stats
INFO:sqlalchemy.engine.base.Engine:('support',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.id AS staff_id 
FROM staff 
WHERE name = ? AND staff.position IN (?)
INFO:sqlalchemy.engine.base.Engine:('n1', 'sales')
INFO:sqlalchemy.engine.base.Engine:DELETE FROM staff WHERE name = ? AND staff.position IN (?)
INFO:sqlalchemy.engine.base.Engine:('n1', 'sales')
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.sales_stats AS staff_sales_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.sales_stats
INFO:sqlalchemy.engine.base.Engine:('sales',)
INFO:sqlalchemy.engine.base.Engine:SELECT staff.position AS staff_position, staff.id AS staff_id, staff.name AS staff_name, staff.support_stats AS staff_support_stats 
FROM staff 
WHERE staff.position IN (?) ORDER BY staff.support_stats
INFO:sqlalchemy.engine.base.Engine:('support',)
.DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return, via agent
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:DELETE FROM staff
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> checked out from pool
INFO:sqlalchemy.engine.base.Engine:PRAGMA main.table_info("staff")
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:
DROP TABLE staff
INFO:sqlalchemy.engine.base.Engine:()
INFO:sqlalchemy.engine.base.Engine:COMMIT
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> being returned to pool
DEBUG:sqlalchemy.pool.impl.SingletonThreadPool:Connection <pysqlite2.dbapi2.Connection object at 0x7f96898ba200> rollback-on-return
INFO:sqlalchemy.pool.impl.SingletonThreadPool:Pool recreating
INFO:sqlalchemy.pool.impl.SingletonThreadPool:Pool recreating


=========================== 1 passed in 0.05 seconds ===========================
```

Regarding the potential fix, I've run the SQLAlchemy regression test suite both with and without my change and found that two additional test cases fail.

Failing tests before change 
```
FAILED test/aaa_profiling/test_misc.py::EnumTest::test_create_enum_from_pep_435_w_expensive_members - AssertionError: Adjusted function call count 1325 not within 5.0% of expected 4638, platform 2.7_sq...
FAILED test/dialect/test_sqlite.py::JSONTest::test_extract_subobject - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_int_basic - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_int_coerce_type - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_string_basic - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_string_coerce_type - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_mixed_path - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_simple_int - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_spaces_in_key - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_string_path - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/orm/test_update_delete.py::DeletePolymorphicTest_sqlite+pysqlite_3_11_0::test_delete_with_fetch_polymorphic - ValueError: need more than 1 value to unpack
========================================================================== 11 failed, 8509 passed, 986 skipped in 468.05 seconds ===========================================================================
```

Failing tests after change
```
FAILED test/ext/test_horizontal_shard.py::AttachedFileShardTest::test_bulk_delete - AttributeError: 'NoneType' object has no attribute 'location'
FAILED test/ext/test_horizontal_shard.py::DistinctEngineShardTest::test_bulk_delete - AttributeError: 'NoneType' object has no attribute 'location'
FAILED test/aaa_profiling/test_misc.py::EnumTest::test_create_enum_from_pep_435_w_expensive_members - AssertionError: Adjusted function call count 1325 not within 5.0% of expected 4638, platform 2.7_sq...
FAILED test/dialect/test_sqlite.py::JSONTest::test_extract_subobject - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_int_basic - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_int_coerce_type - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_string_basic - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_against_string_coerce_type - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_mixed_path - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_simple_int - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_spaces_in_key - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
FAILED test/dialect/test_suite.py::JSONTest_sqlite+pysqlite_3_11_0::test_crit_string_path - OperationalError: (pysqlite2.dbapi2.OperationalError) no such function: JSON_QUOTE
========================================================================== 12 failed, 8508 passed, 986 skipped in 477.66 seconds ===========================================================================
```

Failing test case stack traces
```
=================================== FAILURES ===================================
____________________ AttachedFileShardTest.test_bulk_delete ____________________
Traceback (most recent call last):
  File "/home/pswanston/workspace/sqlalchemy/test/ext/test_horizontal_shard.py", line 399, in test_bulk_delete
    sess.query(Report).filter(Report.temperature >= 80).delete()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3700, in delete
    delete_op.exec_()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 1694, in exec_
    self._do_exec()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 1929, in _do_exec
    delete_stmt, mapper=self.mapper, params=query._params
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 1266, in execute
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/ext/horizontal_shard.py", line 252, in get_bind
    mapper, instance, clause=clause
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/ext/horizontal_shard.py", line 231, in _choose_shard_and_assign
    shard_id = self.shard_chooser(mapper, instance, **kw)
  File "/home/pswanston/workspace/sqlalchemy/test/ext/test_horizontal_shard.py", line 100, in shard_chooser
    return shard_chooser(mapper, instance.location)
AttributeError: 'NoneType' object has no attribute 'location'
=========================== short test summary info ============================
FAILED test/ext/test_horizontal_shard.py::AttachedFileShardTest::test_bulk_delete

=================================== FAILURES ===================================
___________________ DistinctEngineShardTest.test_bulk_delete ___________________
Traceback (most recent call last):
  File "/home/pswanston/workspace/sqlalchemy/test/ext/test_horizontal_shard.py", line 399, in test_bulk_delete
    sess.query(Report).filter(Report.temperature >= 80).delete()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3700, in delete
    delete_op.exec_()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 1694, in exec_
    self._do_exec()
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 1929, in _do_exec
    delete_stmt, mapper=self.mapper, params=query._params
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 1266, in execute
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/ext/horizontal_shard.py", line 252, in get_bind
    mapper, instance, clause=clause
  File "/home/pswanston/workspace/sqlalchemy/test/../lib/sqlalchemy/ext/horizontal_shard.py", line 231, in _choose_shard_and_assign
    shard_id = self.shard_chooser(mapper, instance, **kw)
  File "/home/pswanston/workspace/sqlalchemy/test/ext/test_horizontal_shard.py", line 100, in shard_chooser
    return shard_chooser(mapper, instance.location)
AttributeError: 'NoneType' object has no attribute 'location'
=========================== short test summary info ============================
FAILED test/ext/test_horizontal_shard.py::DistinctEngineShardTest::test_bulk_delete
```

I've looked into the error and it appears to me like some other totally unrelated code is also broken, and that by passing the mapper down as part of the delete operation it exposes this error.
The part I'm not sure about is is location missing from the shard instances due to the test suite bootstrapping or is it actually a real issue. 
If it's just a test suite bootstrapping thing then perhaps another ticket could be opened to fix that issue.
The reason this looks like an unrelated issue to me is because _choose_shard_and_assign which calls shard_chooser appears to understand that instance can be None.

```
    def _choose_shard_and_assign(self, mapper, instance, **kw):
        if instance is not None:
            state = inspect(instance)
            if state.key:
                token = state.key[2]
                assert token is not None
                return token
            elif state.identity_token:
                return state.identity_token

        shard_id = self.shard_chooser(mapper, instance, **kw)
        if instance is not None:
            state.identity_token = shard_id
        return shard_id
```

However shard_chooser supplied by test_horizontal_shard.py appears to assume it is not None.

```
        def shard_chooser(mapper, instance, clause=None):
            if isinstance(instance, WeatherLocation):
                return shard_lookup[instance.continent]
            else:
                return shard_chooser(mapper, instance.location)
```

My only reservation is that perhaps I need to be passing "instance=some_instance" to session.execute when I make the call from BulkDelete._do_exec. 
However I'm not familiar enough to know if that is the case and if it is where I would obtain that value from. 
It seems like it might create a large performance overhead if we needed to detect if a mapper was using a shard_chooser and pre-fetch all the instances before calling a delete just so we could pass an instance value.
Also I don't know how it would work if multiple instances were matched as get_bind can only receive one instance value and we could be deleting multiple instances (potentially on different shards?)

```
        self.result = session.execute(
            delete_stmt, mapper=self.mapper, params=query._params
        )
```

If anyone could take a look at this issue as well as my proposed fix I would appreciate it.
I expect there will need to be other changes to supplement those suggested in my fix for the sharded data case, however I don't know precisely what they will need to be, any advice would be welcome.

Peter

**Comment by zzzeek** [comment]
hi there -

I appreciate your efforts towards assembling a fix for this issue.   the tests that are failing regardless of your change can be ignored, it looks mostly like you have a version of SQLite installed that is of an unanticipated configuration; version 3.11 is only a few points ahead of the lowest supported version of SQLite JSON which is currently set to 3.9 so perhaps that value isn't accurate for the level of features that are being used.

as for the horizontal shard tests, this is likely due to the way in which the context of the statement is being modified by going up and out to call session.execute() again, this is on the "outside" of the delete operation.   

The fix is simple in that there has to date been no support for bulk update or delete against single-table inheritance classes, even though unlike joined inheritance, this case is fairly simple.

However, this is [documented](https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=query%20update#sqlalchemy.orm.query.Query.update) as not being supported right now, so we can't change it mid-1.3 and for the time being you will need to add this criteria manually.    

While the reason this doesn't work for joined inheritance is clear to me, it's not so clear why it doesn't work for single inheritance, the likely reason is that it still won't work for inheritance mappings that mix joined and single inheritance, and also possibly as a means of emphasizing that these optimizing methods were not intended for inheritance cases in general.

But because it is so simple to get single inheritance to work it is likely worthwhile to add this as an enhancement in 1.4 where the documentation caveat can be adjusted.   The fix to make update/delete work for all single inheritance is:

```
diff --git a/lib/sqlalchemy/orm/persistence.py b/lib/sqlalchemy/orm/persistence.py
index b503d3ad1..0a59df89d 100644
--- a/lib/sqlalchemy/orm/persistence.py
+++ b/lib/sqlalchemy/orm/persistence.py
@@ -1706,6 +1706,8 @@ class BulkUD(object):
         query = self.query
 
         self.context = querylib.QueryContext(query)
+        if query._enable_single_crit:
+            query._adjust_for_single_inheritance(self.context)
 
         if isinstance(query._entities[0], querylib._ColumnEntity):
             # check for special case of query(table)

```

however, at best I can target this for 1.4 as it is a backwards incompatible change because we're very far into 1.3.x and this has been a long documented expectation that this doesnt work right now.

right now, emit your delete() as:

```
sess.query(Sales).filter(text("name = :name")).filter(Sales.position == 'sales').params(
            name="n1"
        ).delete("fetch")
```

I would ask if you were interested in implementing some more tests for 1.4 but seeing as this would not benefit you in the near term I can just add this to the queue, and i will make use of your excellent test case already written in order to finish it up.

**Comment by pswanston** [comment]
Hey @zzzeek , Thanks so much for the fast reply. I wasn't aware this is a known behavior. It had been working previously for us with SQLAlchemy in 0.9.8 (from ions ago) and we caught this issue during an update. Given that it's an expected behavior I think it's totally fine, I just wanted to make your team aware of the issue primarily. We've instrumented all our code with the additional filter clauses on the polymorphic_identity columns already. 

I can definitely add afew more test cases when I have a chance. Given this issue also effects update as well as a delete I probably need to add a test for that as well. There are a great number of test cases for bulk update and delete already, I'm not sure how many additional tests would be useful / beneficial specifically for polymorphic/single table inheritance entities. If you can give me some idea of what you're looking for specifically just let me know and I can add afew more test cases on my fork for you to pull in later for your 1.4 work.

Also it's nice to see the actual fix to get update / delete work with polymorphic/single table inheritance entities is so elegant.
```
+        if query._enable_single_crit:
+            query._adjust_for_single_inheritance(self.context)
```

**Comment by pswanston** [comment]
Hey @zzzeeek, just as an added note making the change you suggested alone was not sufficient to fix the issue for delete.
It seems that BulkUD's self.context does not get "_compile_context()"  called on it.
Because of this self.context.single_inh_entities is never populated with the entity types.

The minor workaround I found was to do the following.

```
        if query._enable_single_crit:
            self.context = query._compile_context()
            query._adjust_for_single_inheritance(self.context)
        else:
            self.context = querylib.QueryContext(query
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support extra / single inh criteria with ORM update/delete** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2201
