### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by wensenz** [sqlalchemy/sqlalchemy#5073]
https://github.com/sqlalchemy/sqlalchemy/blob/5881fd274015af3de37f2ff0f91ff6a7c61c1540/lib/sqlalchemy/sql/sqltypes.py#L945
value = bytes(value)
改为
value = bytes(value, 'utf8')

fix

**Comment by zzzeek** [comment]
hi there -

I apologize if there is a language or other issue that is in play which impacts how this bug report was written, but we would appreciate if proper bug reports are filed, which include descriptions of the issue, platform details, a test case or at least a stack trace. Guidelines to follow for this are at https://www.sqlalchemy.org/participate.html#bugs .    It's also preferable if a bug report does not include terse, one word commands like "fix", that's not the nature of an open source software project.  If there is an issue in SQLAlchemy or any open source project, the issue tracker is where people come together to discuss and work out a resolution together in a polite and collaborative fashion.

For the moment, no bug is illustrated here because the variable in question is not a string, it's a bytestring.   no encoding is necessary.

**Comment by jvanasco** [comment]
Restating a bit of what @zzzeek wrote above:

That line of code is in the `_Binary` base class, which corresponds to Binary datatypes in the backing datastore, which essentially deal with raw bytes.  

This handles situatinos where you might be using a LargeBinary (https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.LargeBinary) column for a binary storage in PostgreSQL (https://www.postgresql.org/docs/9.0/datatype-binary.html) or Blob in MySQL (https://dev.mysql.com/doc/refman/8.0/en/blob.html)

Based on what you shared, I think you may want to define the column as one of SqlAlchemy's text types, like `String`/`Unicode`, `Text`, `UnicodeText`.

**Comment by edupo** [comment]
I stumble upon this issue today in the same line only on python3.

I have a sqlite database file. The column is `LargeBinary` indeed but sometimes we store there pickled data and sometimes is just a byte array. In this case when we query the database there are times where the `value` is passed is a string and some other times we receive bytes.

I did this modification and it works now, but as I'm not aware of all details I'm probably breaking something else...

```
                if value is not None:
                    if isinstance(value, str):
                        value = bytes(value, 'utf-9')
                    else:
                        value = bytes(value)
                return value
```

@zzzeek I think this may be a fair bug.

**Comment by zzzeek** [comment]
hi @edupo -

bug reports require [MCVE](http://stackoverflow.com/help/mcve) test cases that illustrate how you are getting this result.   We have lots of tests for SQLite w/ binary and none of them fail.  if we were to make this code change, it would require a unit test that would fail without the change; otherwise the change will someday be reverted without it indicating any problem.  So without a demo script I can't fix this.    reopen when you can provide one.

**Comment by zzzeek** [comment]
I can confirm that if you take a SQLite database and insert some data as plain string, and then later try to SELECT it with interpretation as bytes, then you get this error.  If OTOH you ensure that you inserted the value as a b'' bytes, then you don't get this issue.   It does not matter what the content of the bytes are, that is, plain ASCII, there is something about how the value is stored in the SQLite database itself that flags it as a bytes or a string value.  

Reading https://www.sqlite.org/datatype3.html, I'm not exactly sure what the mechanism is.  It states that strings are stored in the database encoding, meaning, they are stored in a binary format as well.  But somehow I'm able to get one SQlite database return the string "foo", which is ascii only, as a string, and the other as a bytes.

Anyway, assuming all the above is correct, this would indicate here a SQLite database where data was inserted inconsistently, and to retrieve data from such a table you would not want to use LargeBinary, because your data is not binary, it's "mixed".  you need to make your own type as follows::

```
class MixedBinary(TypeDecorator):
    impl = String

    def process_result_value(self, value, dialect):
        if isinstance(value, str):
            value = bytes(value, 'utf-8')
        elif value is not None:
            value = bytes(value)

        return value


```

I will add this to the docs now.

**Comment by edupo** [comment]
@zzzeek Thank you for the documentation. I will try it out.

The thing is that with Python 2.7 the issue did not happen probably because is processed with `str`. I'm using the same declarations for 2.7 and 3 and there is where I found the issue.

> you need to make your own type as follows::

Now you mention that solution... that seems the right approach for databases found in the wilderness so I will stick to that. 

Thank you again for your help.

**Comment by fordguo** [comment]
I have the TypeError with superset(python3.6 psycopg2-binary=2.8.5):

`RROR:superset.app:Exception on /databaseview/list/ [GET]
Traceback (most recent call last):
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask_appbuilder/views.py", line 551, in list
    widgets = self._list()
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask_appbuilder/baseviews.py", line 1127, in _list
    page_size=page_size,
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask_appbuilder/baseviews.py", line 1026, in _get_list_widget
    page_size=page_size,
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 234, in query
    return count, query.all()
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3319, in all
    return list(self)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 589, in _instance
    populators,
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 726, in _populate_full
    dict_[key] = getter(row)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 1281, in process
    return process_value(impl_processor(value), dialect)
  File "/home/sapreport/report_run/lib64/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 945, in process
    value = bytes(value)
TypeError: string argument without an encoding`
