### ISSUE TITLE
Facing issue by using yield_per

### ISSUE THREAD

**Issue by vimiPonyai** [sqlalchemy/sqlalchemy#5102]
DB: mysql:5.7.0
```
instances = session.query(Model.id, Model.some_value).yield_per(magic_number).enable_eagerloads(false)
```
Base on diff magic_number such as 81 or 101 and so on, will raise.
```
Traceback (most recent call last):
  File "sqlalchemy_py/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "sqlalchemy_py/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 189, in execute
    while self.nextset():
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 142, in nextset
    nr = db.next_result()
_mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```
any idea?
thanks.

**Comment by vimiPonyai** [comment]
NOTE, 
I using for row in Model.yield_per(), and update the row in the for loop, does it`s a wrong way here?

**Comment by zzzeek** [comment]
hi there -

As mentioned elsewhere, nothing can be done without an [MCVE](http://stackoverflow.com/help/mcve) as well as complete information about drivers in use, etc. that I can run locally illustrating exactly how you are getting this result.

**Comment by zzzeek** [comment]
for example, if that is python-mysql you're using, you need to be using mysqlclient instead.

**Comment by vimiPonyai** [comment]
> for example, if that is python-mysql you're using, you need to be using mysqlclient instead.

very sorry for the inconvenient, i am using mysqldb as the mysql-driver.
and the engine config will be:
```
            mysql+mysqldb://username:password@host:port/database?charset=utf8mb4,
            convert_unicode=False,
            pool_recycle=3600,
            pool_size=20,
            max_overflow=20,
            encoding='utf8',
```

**Comment by zzzeek** [comment]
To facilitate, here is a proper MCVE below.  It run without error.  Please alter this script to illustrate the issue you are having.

Note that "mysqldb" is **not** the name of the project which produces the driver in this case, the name "mysqldb" is shared by both mysql-python and mysqlclient, please see https://docs.sqlalchemy.org/en/13/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqldb.



```


from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import false
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class Model(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    some_value = Column(String(50))


e = create_engine("mysql://scott:tiger@mysql57/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([Model(id=i, some_value="%d" % i) for i in range(1, 1000)])
s.commit()


instances = (
    s.query(Model.id, Model.some_value).yield_per(10).enable_eagerloads(false)
)
print(len(instances.all()))


```

partial output:

```

BEGIN (implicit)
2020-01-16 13:15:29,605 INFO sqlalchemy.engine.base.Engine INSERT INTO a (id, some_value) VALUES (%s, %s)
2020-01-16 13:15:29,605 INFO sqlalchemy.engine.base.Engine ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')  ... displaying 10 of 999 total bound parameter sets ...  (998, '998'), (999, '999'))
2020-01-16 13:15:29,649 INFO sqlalchemy.engine.base.Engine COMMIT
2020-01-16 13:15:29,693 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-01-16 13:15:29,694 INFO sqlalchemy.engine.base.Engine SELECT a.id AS a_id, a.some_value AS a_some_value 
FROM a
2020-01-16 13:15:29,695 INFO sqlalchemy.engine.base.Engine ()
999

```

**Comment by vimiPonyai** [comment]
Ok, thanks, I am not good at database and sqlalchemy, thanks your patiently reply.

I try the following step:

apt-get install python3-mysqldb
```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import false
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

MYSQL_URI_PATTERN = ('mysql+mysqldb://{username}:{password}@{hostname}:{port}/'
                     '{database}?charset={charset}')

Base = declarative_base()


class Model(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    depend_value = Column(Integer)
    some_value = Column(Integer)


e = create_engine(
    MYSQL_URI_PATTERN.format(
        username="adc",
        password="efg",
        hostname="ip",
        database="hij",
        port=3306,
        charset='utf8mb4'
    ),
    convert_unicode=False,
    pool_recycle=3600,
    pool_size=20,
    max_overflow=20,
    encoding='utf8',
    echo=True,
)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([Model(id=i, some_value=i, depend_value=i) for i in range(1, 153)]) # 152
s.commit()


instances = (
    s.query(Model.id, Model.depend_value, Model.some_value).yield_per(81).enable_eagerloads(False)
)

for model_id, depend_value, some_value in instances:
    # here are some logic what i need, just to backfill the data.
    new_value = some_value
    if depend_value % 5 == 0:
        new_value = 0
    # here are some logic what i need, just to backfill the data.
    s.query(Model).filter(Model.id == model_id).update({
        'some_value': new_value,
    })

s.commit()

print(len(instances.all()))
```

and will raise:
```
2020-01-17 11:59:09,595 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2020-01-17 11:59:09,595 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,597 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2020-01-17 11:59:09,597 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,600 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2020-01-17 11:59:09,600 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,601 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
2020-01-17 11:59:09,601 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,603 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2020-01-17 11:59:09,603 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,604 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2020-01-17 11:59:09,605 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,605 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
2020-01-17 11:59:09,606 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,607 INFO sqlalchemy.engine.base.Engine DESCRIBE `a`
2020-01-17 11:59:09,607 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,609 INFO sqlalchemy.engine.base.Engine
DROP TABLE a
2020-01-17 11:59:09,609 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,618 INFO sqlalchemy.engine.base.Engine COMMIT
2020-01-17 11:59:09,619 INFO sqlalchemy.engine.base.Engine DESCRIBE `a`
2020-01-17 11:59:09,619 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,620 INFO sqlalchemy.engine.base.Engine ROLLBACK
2020-01-17 11:59:09,621 INFO sqlalchemy.engine.base.Engine
CREATE TABLE a (
        id INTEGER NOT NULL AUTO_INCREMENT,
        depend_value INTEGER,
        some_value INTEGER,
        PRIMARY KEY (id)
)


2020-01-17 11:59:09,621 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,635 INFO sqlalchemy.engine.base.Engine COMMIT
2020-01-17 11:59:09,647 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-01-17 11:59:09,652 INFO sqlalchemy.engine.base.Engine INSERT INTO a (id, depend_value, some_value) VALUES (%s, %s, %s)
2020-01-17 11:59:09,652 INFO sqlalchemy.engine.base.Engine ((1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 4), (5, 5, 5), (6, 6, 6), (7, 7, 7), (8, 8, 8)  ... displaying 10 of 152 total bound parameter sets ...  (151, 151, 151), (152, 152, 152))
2020-01-17 11:59:09,660 INFO sqlalchemy.engine.base.Engine COMMIT
2020-01-17 11:59:09,663 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-01-17 11:59:09,664 INFO sqlalchemy.engine.base.Engine SELECT a.id AS a_id, a.depend_value AS a_depend_value, a.some_value AS a_some_value
FROM a
2020-01-17 11:59:09,664 INFO sqlalchemy.engine.base.Engine ()
2020-01-17 11:59:09,666 INFO sqlalchemy.engine.base.Engine UPDATE a SET some_value=%s WHERE a.id = %s
2020-01-17 11:59:09,666 INFO sqlalchemy.engine.base.Engine (1, 1)
Traceback (most recent call last):
  File "/home/vimi/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/vimi/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 183, in execute
    while self.nextset():
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 136, in nextset
    nr = db.next_result()
MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```

Maybe something i miss and maybe i am using in a wrong way (rather sqlalchemy or sql). 
Thanks in advance.

**Comment by zzzeek** [comment]
OK so I thought perhaps your model code was emitting a lazyload or something in there but in fact you're just trying to do an UPDATE.    

So the bad news is that the documentation noted at #4786 would appear to be correct.   mysql drivers, for which I just tested mysqlclient 1.4.4 and pymysql, still don't support a new SQL operation while an existing unbuffered result set is in progress.

to page through a result set you should use a more traditional approach, since MySQL does not support window functions, here's a way to do it using LIMIT and ORDER BY:

```
def get_data():
    q = s.query(Model.id, Model.depend_value, Model.some_value).order_by(Model.id)
    last_id = None

    while True:
        subq = q
        if last_id is not None:
            subq = subq.filter(Model.id > last_id)
        chunk = subq.limit(81).all()
        if not chunk:
            break
        last_id = chunk[-1][-1]
        for row in chunk:
            yield row

instances = get_data()

for model_id, depend_value, some_value in instances:
    # here are some logic what i need, just to backfill the data.
    new_value = some_value
    if depend_value % 5 == 0:
        new_value = 0
    # here are some logic what i need, just to backfill the data.
    s.query(Model).filter(Model.id == model_id).update({
        'some_value': new_value,
    })

s.commit()

```

**Comment by zzzeek** [comment]
here's a util function you can add in your application and use anywhere:

```
def paginate_query(q, col, window_size):
    q = q.order_by(col)
    last_id = None

    while True:
        subq = q
        if last_id is not None:
            subq = subq.filter(col > last_id)
        chunk = subq.limit(window_size).all()
        if not chunk:
            break
        last_id = chunk[-1][-1]
        for row in chunk:
            yield row


instances = paginate_query(
    s.query(Model.id, Model.depend_value, Model.some_value),
    Model.id,
    81
)

```

**Comment by zzzeek** [comment]
I've created https://github.com/sqlalchemy/sqlalchemy/wiki/RangeQuery-and-WindowedRangeQuery which updates the previous "WindowedRangeQuery" entry to include this much simpler approach using LIMIT.

**Comment by zzzeek** [comment]
since this is now tested and understood, a workaround is posted on the wiki, thanks for your patience.

**Comment by vimiPonyai** [comment]
@zzzeek Thanks your explain and your util function.
