### ISSUE TITLE
apply informative re-raise if a result processor function fails

### ISSUE THREAD

**Issue by huntfx** [sqlalchemy/sqlalchemy#5123]
I have a `Session` model with a `hash` column of the `Binary` type, and a `User` model with a relationship of `sessions`. If I get attributes through `inspect(user).attrs`, calling `attr.load_history()` on the `sessions` attribute will cause this [string argument without an encoding](https://github.com/sqlalchemy/sqlalchemy/issues/3692) error.

I've realised that hash column is also storing strings due to a mistake I made earlier (it's an sqlite database so doesn't error with other datatypes), which leads me onto my suggestion.

I don't think a generic uncaught exception should be left in `load_history` (or other similar cases) if something is not as expected, as it's a genuine thing that can happen. I'm not sure if ignoring it would be possible, but even catching the error and re-raising with a custom message would be very useful.

It's not very relevant, but to generate the traceback I'm using this code.

    user = session.query(User).first()
    for attr in inspect(user).attrs:
        attr.load_history()

Full traceback:

    Traceback (most recent call last):
      File "<path>/test.py", line 11, in <module>
        attr.load_history()
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\state.py", line 932, in load_history
        return self.state.get_history(self.key, PASSIVE_OFF ^ INIT_OK)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\state.py", line 444, in get_history
        return self.manager[key].impl.get_history(self, self.dict, passive)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\attributes.py", line 1103, in get_history
        current = self.get(state, dict_, passive=passive)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\attributes.py", line 699, in get
        value = self.callable_(state, passive)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\strategies.py", line 723, in _load_for_state
        session, state, primary_key_identity, passive
      File "<string>", line 1, in <lambda>
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\strategies.py", line 865, in _emit_lazyload
        .with_post_criteria(set_default_params)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\ext\baked.py", line 531, in all
        return list(self)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\loading.py", line 105, in instances
        util.raise_from_cause(err)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\compat.py", line 399, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\compat.py", line 154, in reraise
        raise value
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\loading.py", line 85, in instances
        rows = [proc(row) for row in fetch]
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\loading.py", line 85, in <listcomp>
        rows = [proc(row) for row in fetch]
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\loading.py", line 572, in _instance
        populators,
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\loading.py", line 693, in _populate_full
        dict_[key] = getter(row)
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\result.py", line 107, in __getitem__
        return processor(self._row[index])
      File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\sqltypes.py", line 943, in process
        value = bytes(value)
    TypeError: string argument without an encoding

**Comment by zzzeek** [comment]
hi there -

without an [MCVE](http://stackoverflow.com/help/mcve) I have to guess what's happening here, I guess it's this? has nothing to do with the ORM, just using the wrong type and it's raising a TypeError.  The result logic here has been reimplemented in 1.4 and also is in C so adding a re-raise would have to be done extremely carefully and only for the 1.4 series at best.

```
from sqlalchemy import Binary
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine("postgresql://scott:tiger@localhost/test", echo="debug")

Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data="some string"))
s.commit()


Base = declarative_base()


class AWrong(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(Binary)


s.query(AWrong).all()

```

**Comment by zzzeek** [comment]
here's a patch which does it, but it's going to add call overhead even with the C extensions on.  we don't appear to have a profiling test that is exercising this however which is also unusual, even though this is because we no longer use processors for strings in most cases which used to be the most common case.

```
diff --git a/lib/sqlalchemy/engine/result.py b/lib/sqlalchemy/engine/result.py
index c2f976aa0..73089e107 100644
--- a/lib/sqlalchemy/engine/result.py
+++ b/lib/sqlalchemy/engine/result.py
@@ -299,8 +299,15 @@ class ResultMetaData(object):
 
         # processors in key order for certain per-row
         # views like __iter__ and slices
+
+        proc_wrapper = self._processor_wrapper
+
         self._processors = [
-            metadata_entry[MD_PROCESSOR] for metadata_entry in raw
+            proc_wrapper(
+                metadata_entry[MD_PROCESSOR],
+                metadata_entry[MD_RENDERED_NAME],
+            )
+            for metadata_entry in raw
         ]
 
         # keymap by primary string...
@@ -385,6 +392,25 @@ class ResultMetaData(object):
                 ]
             )
 
+    def _processor_wrapper(self, processor, colname):
+        if not processor:
+            return None
+
+        def process(value):
+            try:
+                return processor(value)
+            except:
+                util.raise_from_cause(
+                    TypeError(
+                        "Result processor for column '%s' failed; "
+                        "see above cause for details."
+                        % colname
+                    ),
+                    exc_info=None,
+                )
+
+        return process
+
     def _merge_cursor_description(
         self,
         context,

```    

The user has to be a little more savvy about the stack trace though, some people don't know how to scroll up:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 401, in process
    return processor(value)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/sqltypes.py", line 929, in process
    value = bytes(value)
TypeError: string argument without an encoding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test3.py", line 40, in <module>
    s.query(AWrong).all()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3191, in all
    return list(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 103, in instances
    util.raise_from_cause(err)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 401, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 156, in reraise
    raise value
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 79, in instances
    fetch = cursor.fetchall()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1399, in fetchall
    e, None, None, self.cursor, self.context
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1496, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 156, in reraise
    raise value
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1394, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1369, in process_rows
    l.append(process_row(metadata, processors, keymap, row))
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 409, in process
    exc_info=None,
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 401, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 155, in reraise
    raise value.with_traceback(tb)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 401, in process
    return processor(value)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/sqltypes.py", line 929, in process
    value = bytes(value)
TypeError: Result processor for column 'a_data' failed; see above cause for details.

```

**Comment by zzzeek** [comment]
for the C extensions, it is possible to put the error re-raise logic directly into resultprocessors.c currently right here: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/cextension/resultproxy.c#L125  which would save us the function call overhead.    Or the wrapper itself could be generated from the C code but this would be more elaborate.      either way it's complicated if we want to avoid that extra function call per-column-per-row (for columns that have processors).   the other approach would be to say that per-column processors are not as common as they used to be and the small wrapper overhead is not a big deal.

**Comment by Peter92** [comment]
Thanks for taking the time to look at it. I was running out of time at work so was hoping I'd get my point across, however I think you have the right idea.

To be honest I wouldn't be surprised if `load_history` on a relationship runs the exact same code as the query, it doesn't hurt to demonstrate what I'd originally posted about at least so I adapted your example.

    from sqlalchemy import create_engine, inspect, Column, Integer, Binary, ForeignKey
    from sqlalchemy.orm import Session, relationship
    from sqlalchemy.ext.declarative import declarative_base

    Base = declarative_base()

    class Parent(Base):
        __tablename__ = 'Parent'
        id = Column(Integer, primary_key=True)
        children = relationship('Child')

    class Child(Base):
        __tablename__ = 'Child'
        id = Column(Integer, primary_key=True)
        parent_id = Column(Integer, ForeignKey('Parent.id'))
        name = Column(Binary)  # because we have binary names

        parent = relationship('Parent')

    engine = create_engine("sqlite:///", echo="debug")
    Base.metadata.create_all(engine)
    s = Session(engine)
    s.add(Parent())
    s.commit()

    # Mimic data being the wrong type
    with engine.connect() as con:
        con.execute('INSERT INTO "Child" (parent_id, name) VALUES (1, "mike")')

    # Error caused from child relationship, this is what I posted about
    parent = s.query(Parent).first()
    for i in inspect(parent).attrs:
        i.load_history()

    # Error is also caused by querying child directly
    s.query(Child).first()

The internals of SQLAlchemy are completely foreign to me, and I'm not quite savvy enough for patches (Github Desktop is my entire knowledge of git), so I shall leave this for the experts :)
