### ISSUE TITLE
`Engine.connect()` returns stale connection, leading to TCP Provider: Error code 0x20 (32)

### ISSUE THREAD

**Issue by DomKennedy** [sqlalchemy/sqlalchemy#5148]
```python
from sqlalchemy.engine import create_engine
from sqlalchemy.engine.url import URL
import sys

def run_test(host):

    url = URL(
        drivername="mssql+pyodbc",
        host=host,
        database="master",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )
    engine = create_engine(url)

    with engine.connect() as conn:
        conn.execute("select dbid from sysdatabases").fetchall()

    # literally just disconnect from Wi-Fi or unplug the ethernet cable here, 
    # then wait ~10s, reconnect, wait another 10s, continue
    input("Disconnect and reconnect to the network before continuing")

    with engine.connect() as conn:
        conn.execute("select dbid from sysdatabases").fetchall()


if __name__ == "__main__":
    host = sys.argv[1]
    run_test(host)
```

Running the above code with any non-localhost leads to the following exception on the second `execute` call:

```
Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x274C (10060) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sql_bug.py", line 35, in <module>
  File "sql_bug.py", line 30, in run_test
    run_test(host)
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    parameters,
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File ".venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File ".venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File ".venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x274C (10060) (SQLExecDirectW)')
[SQL: select dbid from sysdatabases]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

This problem came up in the real world as I have an application which maintains a long-running object with an `engine` instance attribute. Around four times a day, it makes a database query using a short-lived context-managed connection via `with self.engine.connect()`. This query consistently raises the above problem every time - presumably as the connection has been sitting dormant for hours in between and at some point experienced a disconnection (or just timed out?), leading to the above scenario.

The problem is resolved by immediately retrying, so my particular problem is solved simply by wrapping the problem call in a retry loop. However, it is certainly not expected behaviour for a fresh `with engine.connect()` call to return a dead connection.

I gather from the docs that the connections returned by `engine.connect()` are cached in a pool for later reuse, which seems sensible, but the above suggests that some kind of staleness check is necessary when reusing a cached connection.

I have only tested this with MSSQL, I'm not sure if other dialects will experience something similar.

**Comment by zzzeek** [comment]
hi there - 

please use the [pool_pre_ping](https://docs.sqlalchemy.org/en/13/core/pooling.html#disconnect-handling-pessimistic) option which will ensure that the liveness-check plus reconnect is performed transparently each time you call ``engine.connect()``.

**Comment by zzzeek** [comment]
reopen if further questions.
