### ISSUE TITLE
improve left-hand side error message for query join(); use detrerministic ordering for ColumnEntity.actual_froms

### ISSUE THREAD

**Issue by mahenzon** [sqlalchemy/sqlalchemy#5194]
When I try to join CTEs ([Common Table Expressions](https://www.postgresql.org/docs/9.1/queries-with.html)) I have randomly appearing error `sqlalchemy.exc.InvalidRequestError: Don't know how to join to ; please use an ON clause to more clearly establish the left side of this join` (yes, the `right` is not even formatted). It happens from time to time without changing the code. It's like 2/3 times OK and then there's an error:

```
...
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2590, in _join_determine_implicit_left_side
    "side of this join" % (right,)
sqlalchemy.exc.InvalidRequestError: Don't know how to join to ; please use an ON clause to more clearly establish the left side of this join
```

Here's the full working code. Just run it several times, and the error will happen:
```python
from itertools import cycle
from typing import Sequence

from sqlalchemy import Column, Integer, String, create_engine, func, and_
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, scoped_session

#### Creating connection
engine = create_engine('postgres://user:password@localhost:5432/db')
# Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Session = scoped_session(
    sessionmaker(autocommit=False, autoflush=False, bind=engine)
)
Base = declarative_base()
Base.metadata.bind = engine

sess = Session()
##

## Helping util
from sqlalchemy.dialects.postgresql.psycopg2 import PGDialect_psycopg2

psycopg_dialect = PGDialect_psycopg2()

def compile_query(q):
    compiled = q.statement.compile(dialect=psycopg_dialect)
    return str(compiled) % compiled.params

##

# Models

class Country(Base):
    __tablename__ = 'countries'

    id = Column(Integer, primary_key=True)
    code = Column(String, nullable=False, unique=True)
    name = Column(String, nullable=False, unique=True)

    def __repr__(self):
        return f'Country(id={self.id}, code={self.code!r}, name={self.name!r})'


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, unique=True)

    def __repr__(self):
        return f'User(id={self.id}, name={self.name!r})'


class Order(Base):
    __tablename__ = 'orders'

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, nullable=False)
    country_id = Column(Integer, nullable=False)
    # more info for this object that does not matter now

    def __repr__(self):
        return f'Order(id={self.id}, user_id={self.user_id}, country_id={self.country_id})'


class Lead(Base):
    __tablename__ = 'leads'

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, nullable=False)
    country_id = Column(Integer, nullable=False)
    # more info for this object that does not matter now

    def __repr__(self):
        return f'Lead(id={self.id}, user_id={self.user_id}, country_id={self.country_id})'

#


def create_tables():
    print('[Re]Creating tables')
    Base.metadata.drop_all()
    print('Dropped DB')
    Base.metadata.create_all()
    print('Created tables')


# Create objects

def create_countries() -> Sequence[Country]:
    """
    Creating countries

    :return:
    """
    print('Gonna create countries')
    country_il = Country(code='IL', name='Israel')
    country_am = Country(code='AM', name='Armenia')
    country_ru = Country(code='RU', name='Russian Federation')
    sess.add(country_il)
    sess.add(country_am)
    sess.add(country_ru)
    sess.flush()
    print('Created countries')
    return country_il, country_am, country_ru


def create_users() -> Sequence[User]:
    """
    Create users

    :return:
    """
    print('Gonna create users')
    u1 = User(name='user1')
    u2 = User(name='user2')
    sess.add(u1)
    sess.add(u2)
    sess.flush()
    print('Created users')
    return u1, u2


def create_orders_and_leads(countries: Sequence[Country], users: Sequence[User]) -> Sequence[Order]:
    """
    Creating orders and leads

    :return:
    """
    print('Gonna create leads and orders')
    orders = []
    countries_cycle = cycle(countries)
    for user in users:
        # creating some orders and leads for each user
        for _ in range(10):
            country = next(countries_cycle)
            order = Order(user_id=user.id, country_id=country.id)
            lead = Lead(user_id=user.id, country_id=country.id)
            sess.add(order)
            sess.add(lead)

    sess.flush()
    print('Created orders and leads')
    return orders


def create_entities():
    print('Creating entities')
    countries = create_countries()
    users = create_users()
    create_orders_and_leads(countries, users)
    sess.commit()
    print('Created entities')

#


def print_all_of_model(model):
    print()
    print('Querying', model.__name__, 'from', model.__tablename__)
    items = sess.query(model).all()
    print('The result is:')
    print(items)


def show_whats_inside():
    """
    Outputs

    Querying Country from countries
    The result is:
    [Country(id=1, code='IL', name='Israel'), Country(id=2, code='AM', name='Armenia'), Country(id=3, code='RU', name='Russian Federation')]

    Querying User from users
    The result is:
    [User(id=1, name='user1'), User(id=2, name='user2')]

    Querying Order from orders
    The result is:
    [Order(id=1, user_id=1, country_id=1), Order(id=2, user_id=1, country_id=2), Order(id=3, user_id=1, country_id=3), Order(id=4, user_id=1, country_id=1), Order(id=5, user_id=1, country_id=2), Order(id=6, user_id=1, country_id=3), Order(id=7, user_id=1, country_id=1), Order(id=8, user_id=1, country_id=2), Order(id=9, user_id=1, country_id=3), Order(id=10, user_id=1, country_id=1), Order(id=11, user_id=2, country_id=2), Order(id=12, user_id=2, country_id=3), Order(id=13, user_id=2, country_id=1), Order(id=14, user_id=2, country_id=2), Order(id=15, user_id=2, country_id=3), Order(id=16, user_id=2, country_id=1), Order(id=17, user_id=2, country_id=2), Order(id=18, user_id=2, country_id=3), Order(id=19, user_id=2, country_id=1), Order(id=20, user_id=2, country_id=2)]

    Querying Lead from leads
    The result is:
    [Lead(id=1, user_id=1, country_id=1), Lead(id=2, user_id=1, country_id=2), Lead(id=3, user_id=1, country_id=3), Lead(id=4, user_id=1, country_id=1), Lead(id=5, user_id=1, country_id=2), Lead(id=6, user_id=1, country_id=3), Lead(id=7, user_id=1, country_id=1), Lead(id=8, user_id=1, country_id=2), Lead(id=9, user_id=1, country_id=3), Lead(id=10, user_id=1, country_id=1), Lead(id=11, user_id=2, country_id=2), Lead(id=12, user_id=2, country_id=3), Lead(id=13, user_id=2, country_id=1), Lead(id=14, user_id=2, country_id=2), Lead(id=15, user_id=2, country_id=3), Lead(id=16, user_id=2, country_id=1), Lead(id=17, user_id=2, country_id=2), Lead(id=18, user_id=2, country_id=3), Lead(id=19, user_id=2, country_id=1), Lead(id=20, user_id=2, country_id=2)]
    -----
    :return:
    """
    for model in (Country, User, Order, Lead):
        print_all_of_model(model)

    print('-----')


def check_if_need_to_fill_table():
    """
    If cannot execute query, create tables
    :return:
    """
    try:
        sess.query(Country, User, Order, Lead).first()
    except Exception:
        sess.rollback()
        print('Have to create tables')
    else:
        print('Tables exist')
        return

    create_tables()
    create_entities()


def create_cte_query():
    common_query_params = (
        User.id.label('user_id'),
        Country.code.label('country_code'),
        func.count().label('total_conversions'),
    )
    common_group_by = (
        User.id,
        Country.code,
    )

    orders_query = sess.query(
        *common_query_params,
    ).filter(
        Order.user_id == User.id,
        Order.country_id == Country.id,
    ).group_by(
        *common_group_by,
    )
    orders_cte = orders_query.cte('orders_cte')

    leads_query = sess.query(
        *common_query_params,
    ).filter(
        Lead.user_id == User.id,
        Lead.country_id == Country.id,
    ).group_by(
        *common_group_by,
    )
    leads_cte = leads_query.cte('leads_cte')

    query = sess.query(
        func.coalesce(orders_cte.c.user_id, leads_cte.c.user_id).label('user_id'),
        func.coalesce(orders_cte.c.country_code, leads_cte.c.country_code).label('country_code'),
        (
            func.coalesce(orders_cte.c.total_conversions, 0)
            + func.coalesce(leads_cte.c.total_conversions, 0)
        ).label('total_conversions'),
    ).join(
        leads_cte,
        and_(
            orders_cte.c.country_code == leads_cte.c.country_code,
            orders_cte.c.user_id == leads_cte.c.user_id,
        ),
        isouter=True,
        full=True,
    )
    return query


def run_cte_query():
    """
    Run it several times. Sometimes it succeeds, sometimes fails

    :return:
    """
    query = create_cte_query()
    print('Got query. Compiled:')
    print(compile_query(query))
    print('Result:')
    print(query.all())


def main():
    check_if_need_to_fill_table()
    show_whats_inside()
    run_cte_query()


if __name__ == '__main__':
    main()
```

When the run succeeds, the output looks something like this:
```
Got query. Compiled:
WITH orders_cte AS 
(SELECT users.id AS user_id, countries.code AS country_code, count(*) AS total_conversions 
FROM users, countries, orders 
WHERE orders.user_id = users.id AND orders.country_id = countries.id GROUP BY users.id, countries.code), 
leads_cte AS 
(SELECT users.id AS user_id, countries.code AS country_code, count(*) AS total_conversions 
FROM users, countries, leads 
WHERE leads.user_id = users.id AND leads.country_id = countries.id GROUP BY users.id, countries.code)
 SELECT coalesce(orders_cte.user_id, leads_cte.user_id) AS user_id, coalesce(orders_cte.country_code, leads_cte.country_code) AS country_code, coalesce(orders_cte.total_conversions, 0) + coalesce(leads_cte.total_conversions, 0) AS total_conversions 
FROM orders_cte FULL OUTER JOIN leads_cte ON orders_cte.country_code = leads_cte.country_code AND orders_cte.user_id = leads_cte.user_id
Result:
[(1, 'AM', 6), (2, 'AM', 8), (1, 'IL', 8), (2, 'IL', 6), (1, 'RU', 6), (2, 'RU', 6)]
```

When the run fails, it shows this error:
```
Traceback (most recent call last):
  File "/home/mahenzon/.PyCharm2019.2/config/scratches/scratch_32.py", line 283, in <module>
    main()
  File "/home/mahenzon/.PyCharm2019.2/config/scratches/scratch_32.py", line 279, in main
    run_cte_query()
  File "/home/mahenzon/.PyCharm2019.2/config/scratches/scratch_32.py", line 269, in run_cte_query
    query = create_cte_query()
  File "/home/mahenzon/.PyCharm2019.2/config/scratches/scratch_32.py", line 258, in create_cte_query
    full=True,
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2246, in join
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2425, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2448, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/home/mahenzon/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2590, in _join_determine_implicit_left_side
    "side of this join" % (right,)
sqlalchemy.exc.InvalidRequestError: Don't know how to join to ; please use an ON clause to more clearly establish the left side of this join
```
___

The compiled query is:
```SQL
WITH orders_cte AS
         (SELECT users.id AS user_id, countries.code AS country_code, count(*) AS total_conversions
          FROM users,
               countries,
               orders
          WHERE orders.user_id = users.id
            AND orders.country_id = countries.id
          GROUP BY users.id, countries.code),
     leads_cte AS
         (SELECT users.id AS user_id, countries.code AS country_code, count(*) AS total_conversions
          FROM users,
               countries,
               leads
          WHERE leads.user_id = users.id
            AND leads.country_id = countries.id
          GROUP BY users.id, countries.code)
SELECT coalesce(orders_cte.user_id, leads_cte.user_id)                                      AS user_id,
       coalesce(orders_cte.country_code, leads_cte.country_code)                            AS country_code,
       coalesce(orders_cte.total_conversions, 0) + coalesce(leads_cte.total_conversions, 0) AS total_conversions
FROM orders_cte
         FULL OUTER JOIN leads_cte
                         ON orders_cte.country_code = leads_cte.country_code AND orders_cte.user_id = leads_cte.user_id
```

I'm not sure why this happens, because the SQL query is fully-functional, it's compiled properly, but the error sometimes happens on the `.join`

___
`sqlalchemy.__version__ = '1.3.10'`

**Comment by zzzeek** [comment]
the error message here is not well written.    what it should say is:

"Don't know how to join to %s from current auto-detected left hand side; please use "
"the select_from() method to establish an explicit left side, as well as "
"an explicit ON clause, to more clearly establish the left "
"side of this join" % (right,)


the reason it sometimes knows the left side and sometimes not is because the expressions you are giving it each have both orders_cte and leads_cte in each column expression; the logic that extracts the fact that we are joining "from" one of these uses a set() around the FROM elements for each column expression, so sometimes it guesses that "orders_cte" is the left side, and sometimes "leads_cte".  

your query :
```

    query = sess.query(
        func.coalesce(orders_cte.c.user_id, leads_cte.c.user_id).label('user_id'),
        func.coalesce(orders_cte.c.country_code, leads_cte.c.country_code).label('country_code'),
        (
            func.coalesce(orders_cte.c.total_conversions, 0)
            + func.coalesce(leads_cte.c.total_conversions, 0)
        ).label('total_conversions'),
    ).select_from(orders_cte).join(
        leads_cte,
        and_(
            orders_cte.c.country_code == leads_cte.c.country_code,
            orders_cte.c.user_id == leads_cte.c.user_id,
        ),
        isouter=True,
        full=True,
    )

```

i can update the error message here and forego the use of set() above.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Reword implicit left join error; ensure deterministic FROM for columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1780

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Reword implicit left join error; ensure deterministic FROM for columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1781

**Comment by mahenzon** [comment]
Cool, thanks a lot! Now the error does not occur.
