### ISSUE TITLE
Occur installation error because of enum.IntFlag 

### ISSUE THREAD

**Issue by mcauto** [sqlalchemy/sqlalchemy#5195]
python 3.7
sqlalchemy 1.3.14
```
'ERROR: Command errored out with exit status 1:',
"   command: /root/projects/py/custom-api/.venv/bin/python /root/projects/py/custom-api/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8yd681ix/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel",
'       cwd: None',
'  Complete output (14 lines):',
'  Traceback (most recent call last):',
'    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main',
'      "__main__", mod_spec)',
'    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code',
'      exec(code, run_globals)',
'    File "/root/projects/py/custom-api/.venv/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>',
'      from pip._internal.cli.main import main as _main  # isort:skip # noqa',
'    File "/root/projects/py/custom-api/.venv/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>',
'      import locale',
'    File "/usr/lib/python3.7/locale.py", line 16, in <module>',
'      import re',
'    File "/usr/lib/python3.7/re.py", line 143, in <module>',
'      class RegexFlag(enum.IntFlag):',
"  AttributeError: module 'enum' has no attribute 'IntFlag'",
'  ----------------------------------------',
"ERROR: Command errored out with exit status 1: /root/projects/py/custom-api/.venv/bin/python /root/projects/py/custom-api/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8yd681ix/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output."
```

**Comment by mcauto** [comment]
If install enum34, occur this error. 

`pip uninstall enum34`

**Comment by CaselIT** [comment]
I've also had this problem. enum34 is not compatible with python 3.7+.

**Comment by CaselIT** [comment]
I've opened an issue in enum34 https://bitbucket.org/stoneleaf/enum34/issues/31/make-the-install-a-noop-on-python36
