### ISSUE TITLE
test suite breaks w/ pytest 5.4.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5201]
causes a different error w xdist but i think this is the source of it

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/python.py", line 216, in pytest_pycollect_makeitem
    res = outcome.get_result()
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 193, in pytest_pycollect_makeitem
    for parametrize_cls in _parametrize_cls(collector.module, obj)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 193, in <listcomp>
    for parametrize_cls in _parametrize_cls(collector.module, obj)
  File "/home/classic/dev/sqlalchemy/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/nodes.py", line 83, in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
pytest.PytestDeprecationWarning: direct construction of Class has been deprecated, please use Class.from_parent

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Dont raise on pytest deprecation warnings** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1788

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Dont raise on pytest deprecation warnings** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1789
