### ISSUE TITLE
PyPy test failure

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5223]
Once https://github.com/sqlalchemy/sqlalchemy/pull/5222 is merged, it will be easy to add to the github actions workflow tests for pypy.

Currently some tests fail on pypy: ` 6 failed, 10186 passed, 1245 skipped`

<details>
<summary>List of failed tests:</summary>

```
=============================================================================================================================================================================== FAILURES ===============================================================================================================================================================================
_________________________________________________________________________________________________________________________________________________________________ DeclarativeTest.test_difficult_class _________________________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/ext/declarative/test_basic.py", line 454, in test_difficult_class
    decl.instrument_declarative(User, {}, Base.metadata)
  File "/home/test/../lib/sqlalchemy/ext/declarative/api.py", line 50, in instrument_declarative
    _as_declarative(cls, cls.__name__, cls.__dict__)
  File "/home/test/../lib/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/test/../lib/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/test/../lib/sqlalchemy/ext/declarative/base.py", line 193, in __init__
    self._early_mapping()
  File "/home/test/../lib/sqlalchemy/ext/declarative/base.py", line 196, in _early_mapping
    self.map()
  File "/home/test/../lib/sqlalchemy/ext/declarative/base.py", line 693, in map
    self.cls, self.local_table, **self.mapper_args
  File "<string>", line 2, in mapper
  File "<string>", line 2, in __init__
  File "/home/test/../lib/sqlalchemy/util/deprecations.py", line 171, in warned
    return fn(*args, **kwargs)
  File "/home/test/../lib/sqlalchemy/orm/mapper.py", line 704, in __init__
    self._configure_class_instrumentation()
  File "/home/test/../lib/sqlalchemy/orm/mapper.py", line 1267, in _configure_class_instrumentation
    method = method.im_func
AttributeError: 'function' object has no attribute 'im_func'
_________________________________________________________________________________________________________________________________________________________________ PoolLoggingTest.test_queuepool_echo __________________________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/engine/test_logging.py", line 479, in test_queuepool_echo
    self._test_queuepool(q)
  File "/home/test/engine/test_logging.py", line 466, in _test_queuepool
    + (["Pool disposed. %s"] if dispose else []),
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 200, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: ['Created new connection %r', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Pool disposed. %s'] != ['Created new connection %r', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Closing connection %r', 'Pool disposed. %s']
assert ['Created new...to pool', ...] == ['Created new...to pool', ...]
  At index 8 diff: 'Pool disposed. %s' != 'Connection %r being returned to pool'
  Right contains 3 more items, first extra item: 'Connection %s rollback-on-return%s'
  Full diff:
    [
     'Created new connection %r',
     'Connection %r checked out from pool',
     'Connection %r being returned to pool',...

  ...Full output truncated (11 lines hidden), use '-vv' to show
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2020-03-30 18:34:08,655 DEBUG sqlalchemy.pool.impl.QueuePool Created new connection <Mock name='mock()' id='414114104'>
2020-03-30 18:34:08,657 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> checked out from pool
2020-03-30 18:34:08,658 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> being returned to pool
2020-03-30 18:34:08,658 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> rollback-on-return
2020-03-30 18:34:08,659 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> checked out from pool
2020-03-30 18:34:08,659 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> being returned to pool
2020-03-30 18:34:08,660 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> rollback-on-return
2020-03-30 18:34:08,660 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414114104'> checked out from pool
2020-03-30 18:34:09,274 INFO sqlalchemy.pool.impl.QueuePool Pool disposed. Pool size: 5  Connections in pool: 0 Current Overflow: -5 Current Checked out connections: 0
________________________________________________________________________________________________________________________________________________________________ PoolLoggingTest.test_queuepool_logging ________________________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/engine/test_logging.py", line 483, in test_queuepool_logging
    self._test_queuepool(q)
  File "/home/test/engine/test_logging.py", line 466, in _test_queuepool
    + (["Pool disposed. %s"] if dispose else []),
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 200, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: ['Created new connection %r', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Pool disposed. %s'] != ['Created new connection %r', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Connection %r checked out from pool', 'Connection %r being returned to pool', 'Connection %s rollback-on-return%s', 'Closing connection %r', 'Pool disposed. %s']
assert ['Created new...to pool', ...] == ['Created new...to pool', ...]
  At index 8 diff: 'Pool disposed. %s' != 'Connection %r being returned to pool'
  Right contains 3 more items, first extra item: 'Connection %s rollback-on-return%s'
  Full diff:
    [
     'Created new connection %r',
     'Connection %r checked out from pool',
     'Connection %r being returned to pool',...

  ...Full output truncated (11 lines hidden), use '-vv' to show
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2020-03-30 18:34:09,286 DEBUG sqlalchemy.pool.impl.QueuePool Created new connection <Mock name='mock()' id='414231200'>
2020-03-30 18:34:09,288 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> checked out from pool
2020-03-30 18:34:09,289 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> being returned to pool
2020-03-30 18:34:09,289 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> rollback-on-return
2020-03-30 18:34:09,290 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> checked out from pool
2020-03-30 18:34:09,290 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> being returned to pool
2020-03-30 18:34:09,290 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> rollback-on-return
2020-03-30 18:34:09,290 DEBUG sqlalchemy.pool.impl.QueuePool Connection <Mock name='mock()' id='414231200'> checked out from pool
2020-03-30 18:34:09,873 INFO sqlalchemy.pool.impl.QueuePool Pool disposed. Pool size: 5  Connections in pool: 0 Current Overflow: -5 Current Checked out connections: 0
_________________________________________________________________________________________________________________________________________________________________ PoolEventsTest.test_checkin_event_gc _________________________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/engine/test_pool.py", line 563, in test_checkin_event_gc
    eq_(canary, ["checkin"])
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 200, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: [] != ['checkin']
assert [] == ['checkin']
  Right contains one more item: 'checkin'
  Full diff:
  - ['checkin']
  + []
______________________________________________________________________________________________________________________________ SessionTransactionTest_sqlite+pysqlite_3_29_0.test_failed_rollback_deactivates_transaction_ctx_integration ______________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/orm/test_transaction.py", line 692, in test_failed_rollback_deactivates_transaction_ctx_integration
    evented_exceptions[0], testing.db.dialect.dbapi.IntegrityError
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 218, in is_true
    is_(a, True, msg=msg)
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 227, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: False is not True
assert False is True
____________________________________________________________________________________________________________________________________________________ WrapCallableTest.test_wrapping_update_wrapper_functools_parial ____________________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/test/base/test_utils.py", line 433, in test_wrapping_update_wrapper_functools_parial
    eq_(c.__doc__, my_functools_default.__call__.__doc__)
  File "/home/test/../lib/sqlalchemy/testing/assertions.py", line 200, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: '\n    partial(func, *args, **keywords) - new function with partial application\n    of the given arguments and keywords.\n    ' != None
assert '\n    partia...ywords.\n    ' == None
  +'\n    partial(func, *args, **keywords) - new function with partial application\n    of the given arguments and keywords.\n    '
  -None
```

</details>

We also need to change this line
https://github.com/sqlalchemy/sqlalchemy/blob/e82e04324b8b45367cd53fe9bafeff39a83de3a9/lib/sqlalchemy/testing/replay_fixture.py#L109
since `__builtins__` seems  to reference the module in pypy and not the dict

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Enable pypy tests on github workflow and fix some test errors on them** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1898
