### ISSUE TITLE
v1.3.16 has backwards-incompatible change in Airflow and Flask-Admin

### ISSUE THREAD

**Issue by ashb** [sqlalchemy/sqlalchemy#5242]
Running Airflow's Flask-Admin based webserver worked fine in 1.3.15 but is broken with 1.3.16. The following stack trace is given on start up:

```
Traceback (most recent call last):
  File "/home/ash/.virtualenvs/clean/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/airflow/bin/cli.py", line 900, in webserver
    app = cached_app_rbac(None) if settings.RBAC else cached_app(None)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/airflow/www/app.py", line 232, in cached_app
    app = create_app(config, testing)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/airflow/www/app.py", line 102, in create_app
    models.Chart, Session, name="Charts", category="Data Profiling"))
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 330, in __init__
    menu_icon_value=menu_icon_value)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/model/base.py", line 913, in _refresh_cache
    self._search_supported = self.init_search()
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 581, in init_search
    if tools.is_hybrid_property(self.model, name):
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 209, in is_hybrid_property
    return last_name in get_hybrid_properties(last_model)
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 190, in get_hybrid_properties
    for key, prop in inspect(model).all_orm_descriptors.items()
  File "/home/ash/.virtualenvs/clean/lib/python3.7/site-packages/sqlalchemy/inspection.py", line 72, in inspect
    "available for object of type %s" % type_
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'method'>
```

The problem appears to be caused by defining a relationship with a string, instead of a class.

The current code breaks:

```python
    owner = relationship(
        "User", cascade=False, cascade_backrefs=False, backref='charts')
```

But if it is changed to this it works and doesn't error:

```python
    owner = relationship(
        User, cascade=False, cascade_backrefs=False, backref='charts')
```

This was been reported upstream as apache/airflow#8211 and flask-admin/flask-admin#1976.

This looks like an un-intended breaking change somewhere?

**Comment by CaselIT** [comment]
This regression is because of this https://github.com/sqlalchemy/sqlalchemy/issues/5238 security issue. Pinging @zzzeek 
In in this case it should work correctly, so it may be a bug of the current implementation.

In the meantime you can use the wrok around you proposed, or, if you have cyclic import issues, you can also pass a function to import the model later

**Comment by zzzeek** [comment]
Hi there -

The string that states "User" does not do anything differently than it does before, assuming that "User" is in fact a mapped class.    The string is merely looked up in the symbol dictionary directly, rather than calling eval() on the string first.     

Here is an [MCVE](http://stackoverflow.com/help/mcve) that illustrates the code fragment you have, which proceeds without issue.  Please provide an MCVE which illustrates how to reproduce this failure, thanks!
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class Chart(Base):
    __tablename__ = "chart"

    id = Column(Integer, primary_key=True)
    user_id = Column(ForeignKey("user.id"))
    owner = relationship(
        "User", cascade=False, cascade_backrefs=False, backref="charts"
    )


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

u1 = User(charts=[Chart(), Chart()])
s.add(u1)
s.commit()


c1 = s.query(Chart).first()

assert c1.owner is u1

```

**Comment by zzzeek** [comment]
if I could be more specific, the stack trace shown does not appear to have any direct relationship to the point at which the class name in a relationship is resolved.   So I would hypothesize that the failure seen in flask-admin has something to do with errors being silently ignored and that the fewer calls to eval() is somehow changing that calculus.

**Comment by zzzeek** [comment]
OK great the MCVE is at https://github.com/flask-admin/flask-admin/issues/1976 looking at that now.

**Comment by zzzeek** [comment]
This is a bug in flask-admin.  They are using private API calls right here:  https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/tools.py#L204

**Comment by CaselIT** [comment]
I think this can be closed, since flask-admin has already fixed it and published a new version

**Comment by ashb** [comment]
Gotcha, thanks all!
