### ISSUE TITLE
connection fixture causing failures for sequence tests

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5250]
Against the current master (43bcb0d), `pytest --db postgresql -k HasSequenceTest` produces no failures. After making the following change ...

```diff
Index: lib/sqlalchemy/testing/suite/test_sequence.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/sqlalchemy/testing/suite/test_sequence.py	(revision 43bcb0de1ecc1dc2abd7e7c3eb0c39f3eab9adc0)
+++ lib/sqlalchemy/testing/suite/test_sequence.py	(date 1586651346099)
@@ -92,16 +92,16 @@
     __requires__ = ("sequences",)
     __backend__ = True
 
-    def test_has_sequence(self):
+    def test_has_sequence(self, connection):
         s1 = Sequence("user_id_seq")
-        testing.db.execute(schema.CreateSequence(s1))
+        connection.execute(schema.CreateSequence(s1))
         try:
             eq_(
-                testing.db.dialect.has_sequence(testing.db, "user_id_seq"),
+                connection.engine.dialect.has_sequence(connection.engine, "user_id_seq"),
                 True,
             )
         finally:
-            testing.db.execute(schema.DropSequence(s1))
+            connection.execute(schema.DropSequence(s1))
 
     @testing.requires.schemas
     def test_has_sequence_schema(self):
```

... the test fails with

```
AssertionError: False != True
False != True

Expected :True
Actual   :False
<Click to see difference>

Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\suite\test_sequence.py", line 101, in test_has_sequence
    True,
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\assertions.py", line 201, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: False != True
assert False == True
```

Why?

**Comment by zzzeek** [comment]
postgresql has transactional DDL so when you CREATE SEQUENCE on a connection and don't commit the transaction, this sequence is not yet visible on other connections as is the case when you work with connection.engine and procure other, independent connections.

**Comment by zzzeek** [comment]
so, the test works if you do it like this:

```
diff --git a/lib/sqlalchemy/testing/suite/test_sequence.py b/lib/sqlalchemy/testing/suite/test_sequence.py
index 22ae7d43c..e36f0a8f0 100644
--- a/lib/sqlalchemy/testing/suite/test_sequence.py
+++ b/lib/sqlalchemy/testing/suite/test_sequence.py
@@ -92,16 +92,16 @@ class HasSequenceTest(fixtures.TestBase):
     __requires__ = ("sequences",)
     __backend__ = True
 
-    def test_has_sequence(self):
+    def test_has_sequence(self, connection):
         s1 = Sequence("user_id_seq")
-        testing.db.execute(schema.CreateSequence(s1))
+        connection.execute(schema.CreateSequence(s1))
         try:
             eq_(
-                testing.db.dialect.has_sequence(testing.db, "user_id_seq"),
+                connection.dialect.has_sequence(connection, "user_id_seq"),
                 True,
             )
         finally:
-            testing.db.execute(schema.DropSequence(s1))
+            connection.execute(schema.DropSequence(s1))
 
     @testing.requires.schemas
     def test_has_sequence_schema(self):

```

**Comment by gordthompson** [comment]
Aha! Thanks.
