### ISSUE TITLE
note that Postgresql ARRAY with Enum that is non-native can't use the check constraint option in documentation, or perhaps emit a warning

### ISSUE THREAD

**Issue by HamishLacmane** [sqlalchemy/sqlalchemy#5266]
minor bug discovered when creating a postgres table column of type array, with the type for the array being Enum. See below for MVCE and error:

MVCE
```python
from flask_sqlalchemy import SQLAlchemy
from marshmallow import Schema, fields
from marshmallow_enum import EnumField
import enum

# ensure to connect it to a postgresdb

db = SQLAlchemy()
Column = db.Column

class CustomCreateMixin:

    @classmethod
    def create(cls, **kwargs):
        """Create a new record and save it the database."""
        instance = cls(**kwargs)
        return instance.save()

    def save(self, commit=True):
        """Save the record."""
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

class GroceryEnum(enum.Enum):
    APPLE = 'APPLE'
    BANANA = 'BANANA'
    PEAR = 'PEAR'
    def __str__(self):
        return self.values

class ExampleModel(CustomCreateMixin, db.Model):
    id = Column(db.Integer, primary_key=True)
    selected_groceries = Column(db.ARRAY(db.Enum(GroceryEnum, native_enum=False)))

class ExampleModelSchema(Schema):
    id = fields.Int(dump_only=True)
    selected_groceries = fields.List(EnumField(GroceryEnum))
```

Error
```
Creating tables Boasy Phone Deals Service...
Traceback (most recent call last):
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: malformed array literal: "APPLE"
DETAIL:  Array value must start with "{" or dimension information.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\hamis.desktop-u1seum7.000\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hamis.desktop-u1seum7.000\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\cygwin64\home\hamis\microservices\microservices\exampleapp\venv\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
```

versions:
```
python 3.8.2
Flask==1.1.1
flask-restx==0.1.1
Flask-SQLAlchemy==2.4.1
marshmallow==3.5.1
marshmallow-enum==1.5.1
psycopg2==2.8.4
psycopg2-binary==2.8.4
SQLAlchemy==1.3.16
SQLAlchemy-Utils==0.36.1
```

reference to stackoverflow:
https://stackoverflow.com/questions/61224799/sqlalchemy-raises-error-when-inserting-postgres-array-of-enum-column

**Comment by zzzeek** [comment]
this is a side effect of attempting to create the CHECK constraint for the enumerated value, which is not supported when using an ARRAY.  We can add a documentation note for this.   Simply turn it off:
```


class ExampleModel(Base):
    __tablename__ = "example"
    id = Column(Integer, primary_key=True)
    selected_groceries = Column(
        ARRAY(Enum(GroceryEnum, create_constraint=False, native_enum=False))
    )


```

**Comment by zzzeek** [comment]
note ARRAY with ENUM is handled using the custom type described at:

https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#using-enum-with-array

So I think both #5265 and #5266 are the "same" issue in that the ARRAY of ENUM case is not directly implemented in SQLAlchemy and we should perhaps look to have PG dialect emit a warning to encourage users to consult the documentation for the current supported use.

**Comment by CaselIT** [comment]
we could maybe have a warning for both.

ARRAY is only supported by pg (I think), so the warning should go in the pg dialect or in the general ARRAY class?

**Comment by zzzeek** [comment]
there's not any way to detect this combination right now, however.   that is, an ARRAY type with an Enum type that happens to be used on PostgreSQL.   There's no API point at which such a warning could be emitted without adding new features to ARRAY such that it notifies its internal type object with a clue that its being embedded inside of an ARRAY.

if this mechanism could be created however, then we'd just fix the whole bug overall and add a "run inside of ARRAY mode" for the Postgresql ENUM datatype.

**Comment by zzzeek** [comment]
Ok there's a way to intercept this, ,moment

**Comment by CaselIT** [comment]
@zzzeek take a look at https://github.com/sqlalchemy/sqlalchemy/issues/5265#issuecomment-616150143

**Comment by zzzeek** [comment]
the patch is added to #5265

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support `ARRAY` of `Enum`, `JSON` or `JSONB`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1902

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Support `ARRAY` of `Enum`, `JSON` or `JSONB`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1905
