### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by cepcema** [sqlalchemy/sqlalchemy#5305]
Every time I flask run any application on my windows 10 machine I am getting that error.

```
`C:\Users\qvor_\Desktop\cs50w-project1-master\cs50w-project1-master\cs50-project1>setx FLASK_APP application.py

SUCCESS: Specified value was saved.

C:\Users\qvor_\Desktop\cs50w-project1-master\cs50w-project1-master\cs50-project1>flask run
 * Serving Flask app "application.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\python\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\python\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\python\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\python\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\python\lib\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "c:\python\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\python\lib\site-packages\flask\cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "c:\python\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "C:\Users\qvor_\Desktop\cs50w-project1-master\cs50w-project1-master\cs50-project1\application.py", line 5, in <module>
    from sqlalchemy import create_engine
  File "c:\python\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "c:\python\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "c:\python\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "c:\python\lib\site-packages\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'`
```

**Versions.**
 - OS: win 10
 - Python: 3.8.2

**Comment by zzzeek** [comment]
this function was removed in #4731, please upgrade to a recent version of SQLAlchemy.
