### ISSUE TITLE
sql-queries fail with a "Can't reconnect until invalid transaction is rolled back" for certain query parameter values

### ISSUE THREAD

**Issue by knutj42** [sqlalchemy/sqlalchemy#5359]
**Describe the bug**
Queries sometimes fail with a "Can't reconnect until invalid transaction is rolled back" error when talking to a MS SQL Server database using pyodbc. This only happens for certain sql query parameter values.

**Expected behavior**
Sql queries should work for all valid parameter values.

**To Reproduce**
This problem occurs when a sql query fails and the string-representation of the resulting exception contains a substring that matches the error-codes that the "sqlalchemy.dialects.mssql.MSDialect_pyodbc.is_disconnect()" method checks for. 

In some cases, the string-representation of the exception contains the parameter-values to the failing sql query, so it is possible to reproduce this bug by first making a failing sql-query that includes one of the error-codes.

```py

import sqlalchemy

# Note: The sqlserver database backend used in this test was started using docker-compose, with the following
# docker-compose.yml file:
#
# version: '2.2'
#
# services:
#   mssql:
#     image: microsoft/mssql-server-linux
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Sesam1234
#     ports:
#      - "1433:1433"
#
database_url = 'mssql+pyodbc://sa:Sesam1234@localhost:1433/tempdb?driver=ODBC+Driver+17+for+SQL+Server'

metadata = sqlalchemy.MetaData()
test_table = sqlalchemy.Table("test_table", metadata,
    sqlalchemy.Column("id", sqlalchemy.NVARCHAR(50), primary_key=True)
)

engine = sqlalchemy.create_engine(database_url)
metadata.drop_all(engine)
metadata.create_all(engine)

test_id = "01002"  # use a value that includes one of the error-codes that
                   # sqlalchemy.dialects.mssql.MSDialect_pyodbc.is_disconnect() checks for.
with engine.begin() as conn:
    values = {
        "id": test_id,
    }
    statement = test_table.insert().values(values)
    conn.execute(statement)

    # The second insert will fail with a primary key constraint violation.
    try:
        conn.execute(statement)
    except sqlalchemy.exc.IntegrityError:
        pass

    # The select query will fail, since sqlalchemy.dialects.mssql.MSDialect_pyodbc.is_disconnect() will
    # now erronously return True.
    r = conn.execute(sqlalchemy.select([test_table.c.id]).where(test_table.c.id == test_id))

```

**Error**

```
Traceback (most recent call last):
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1209, in _execute_context
    conn = self._revalidate_connection()
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 473, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/knutj/.config/JetBrains/PyCharmCE2020.1/scratches/scratch_3.py", line 45, in <module>
    r = conn.execute(sqlalchemy.select([test_table.c.id]).where(test_table.c.id == test_id))
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1214, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1209, in _execute_context
    conn = self._revalidate_connection()
  File "/home/knutj/python_venvs/notifier/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 473, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
[SQL: SELECT test_table.id 
FROM test_table 
WHERE test_table.id = ?]
```

**Versions.**
 - OS: Ubuntu 18.04.4 LTS
 - Python: 3.6.9
 - SQLAlchemy: 1.3.17
 - Database: Microsoft SQL Server (from the "microsoft/mssql-server-linux" docker image)
 - DBAPI:pyodbc

**Have a nice day!**

**Comment by gordthompson** [comment]
Thanks for reporting this. I am able to reproduce the issue and will investigate.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix is_disconnect false positive for mssql+pyodbc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2013
