### ISSUE TITLE
ModuleNotFoundError: No module named 'user'

### ISSUE THREAD

**Issue by bendog** [sqlalchemy/sqlalchemy#5383]
**Describe the bug**
`ModuleNotFoundError: No module named 'user'` unable to import sqlalchemy

**Expected behavior**
SQLAlchemy should import 

**To Reproduce**
Try and use Alembic 
**Error**

```
$ alembic init . 
Traceback (most recent call last):
  File "/Users/bendog/dev/tracer-api/.venv/bin/alembic", line 5, in <module>
    from alembic.config import main
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 5, in <module>
    from sqlalchemy import Column
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/sql/__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/sql/expression.py", line 146, in <module>
    from .functions import func  # noqa
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/sql/functions.py", line 13, in <module>
    from . import schema
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 37, in <module>
    from . import ddl
  File "/Users/bendog/dev/tracer-api/.venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 12, in <module>
    import user.user_functions
ModuleNotFoundError: No module named 'user'
```

**Versions.**
 - OS: MacOS 10.15.5
 - Python: 3.8.0
 - SQLAlchemy: 1.3.17
 - Database:
 - DBAPI:

**Comment by bendog** [comment]
pip freeze
```
alembic==1.4.2
appnope==0.1.0
arrow==0.15.6
attrs==19.3.0
aws-lambda-builders==0.9.0
aws-sam-cli==0.52.0
aws-sam-translator==1.24.0
aws-xray-sdk==2.5.0
backcall==0.1.0
binaryornot==0.4.4
boto==2.49.0
boto3==1.13.24
botocore==1.16.24
certifi==2020.4.5.1
cffi==1.14.0
cfn-flip==1.2.3
cfn-lint==0.32.1
chalice==1.14.1
chardet==3.0.4
chevron==0.13.1
click==7.1.2
cookiecutter==1.6.0
coverage==5.1
cryptography==2.9.2
dateparser==0.7.4
decorator==4.4.2
dnspython==1.16.0
docker==4.2.0
docutils==0.15.2
ecdsa==0.15
email-validator==1.1.1
enum-compat==0.0.3
Flask==1.0.4
future==0.18.2
GeoAlchemy2==0.8.3
httpie==2.1.0
idna==2.9
importlib-metadata==1.6.1
inflect==4.1.0
ipython==7.14.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.11.2
jinja2-time==0.2.0
jmespath==0.10.0
jsondiff==1.1.2
jsonpatch==1.25
jsonpickle==1.4.1
jsonpointer==2.0
jsonschema==3.2.0
junit-xml==1.9
Mako==1.1.3
MarkupSafe==1.1.1
mock==4.0.2
more-itertools==8.3.0
moto==1.3.14
networkx==2.4
packaging==20.4
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
poyo==0.5.0
prompt-toolkit==3.0.5
psycopg2-binary==2.8.5
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pycparser==2.20
pydantic==1.5.1
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
pytest==5.4.2
pytest-chalice==0.0.4
pytest-cov==2.9.0
pytest-docker==0.7.2
pytest-mock==3.1.0
pytest-pythonpath==0.7.3
python-dateutil==2.8.1
python-editor==1.0.4
python-jose==3.1.0
pytz==2020.1
PyYAML==5.3.1
regex==2020.5.14
requests==2.23.0
responses==0.10.14
rsa==4.0
s3transfer==0.3.3
serverlessrepo==0.1.9
six==1.15.0
sqlacodegen==2.1.0
SQLAlchemy==1.3.17
sshpubkeys==3.1.0
tomlkit==0.5.8
traitlets==4.3.3
tzlocal==2.1
urllib3==1.25.9
wcwidth==0.1.9
websocket-client==0.57.0
Werkzeug==1.0.1
whichcraft==0.6.1
wrapt==1.12.1
xmltodict==0.12.0
zipp==3.1.0
```

**Comment by CaselIT** [comment]
I'm not sure which sqlalchemy version you have installed, but there is not `import user` in `ddl.py`

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_17/lib/sqlalchemy/sql/ddl.py

**Comment by bendog** [comment]
well that's very unusual isn't it

**Comment by bendog** [comment]
pip is telling me it certainly is version 1.3.17 and my ddl.py definitely has that line in it
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/894916/84004991-fc3cee80-a99e-11ea-939a-2ef193d115ba.png">

**Comment by CaselIT** [comment]
I guess that you or some program added that line in your installed `ddl.py` file in you previous venv.

Glad you resolved it.
