### ISSUE TITLE
MariaDB server restart on create index query

### ISSUE THREAD

**Issue by slodobane** [sqlalchemy/sqlalchemy#5391]
**Describe the bug**
Executing [create_all](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=create_all#sqlalchemy.schema.MetaData.create_all) method causing mariadb v10.4.13 server restart.
The problem appear when "create index" executes.

Linux kernel 5.4.44 (or 5.6.15)
mariadb 10.4.13
SQLAlchemy 1.3.17
mysqlclient 1.4.6

The same thing (it is how we got this problem at first) happens with alembic (v 1.4.2).

**Expected behavior**
It should create a table with index.
```
+------------+-------------+------+-----+---------+-------+
| Field      | Type        | Null | Key | Default | Extra |
+------------+-------------+------+-----+---------+-------+
| id         | char(10)    | NO   | PRI | NULL    |       |
| username   | varchar(64) | NO   |     | NULL    |       |
| password   | varchar(64) | NO   |     | NULL    |       |
| role_flags | int(11)     | NO   |     | NULL    |       |
| active     | tinyint(1)  | NO   | MUL | NULL    |       |
| created    | datetime    | NO   |     | NULL    |       |
+------------+-------------+------+-----+---------+-------+
```

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example. 
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

Create user 'new_test' in mariadb and new database 'new_test_db' with that user.
Put those two python files in the sam directory and execute the run.py.
After the error, next run goes without the problem. Table is there.
Every time after drop/create the error appear again.

- models.py
```py
# coding= utf-8
import datetime
from sqlalchemy import Column, String, Integer, ForeignKey, Boolean, DateTime, Text, CHAR
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

_base = declarative_base()


class AuthUser(_base):

    __tablename__ = 'auth_users'

    id = Column(CHAR(10), primary_key=True)
    username = Column(String(64), index=True, nullable=False, unique=True)
    password = Column(String(64), nullable=False)
    role_flags = Column(Integer, index=True, nullable=False)
    active = Column(Boolean, index=True, nullable=False, default=False)
    created = Column(DateTime, nullable=False, default=datetime.datetime.now)
    user = relationship('User', uselist=False, back_populates='auth_user')

    def __init__(self, _id, username, password, role_flags=1, active=False):

        self.id = _id
        self.username = username
        self.password = password
        self.role_flags = role_flags
        self.active = active

    def load_data_from_dict(self, _data):

        _first_name = _data['fname'] if 'fname' in _data else None
        _last_name = _data['lname'] if 'lname' in _data else None
        _user_data = _data['data'] if 'data' in _data else None

```

- run.py
```py
# coding= utf-8
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.engine.url import URL


from models import _base


_db_user = "new_test"
_db_pass = "123"
_db_name = "new_test_db"
_url = "mysql+mysqldb://{}:{}@localhost:3306/{}?charset=utf8".format(_db_user, _db_pass, _db_name)
#_url = "mysql+pymysql://{}:{}@localhost:3306/{}?charset=utf8".format(_db_user, _db_pass, _db_name)
_engine = create_engine(_url)#, pool_recycle=3600)#, echo=False)

_session_factory = sessionmaker(bind=_engine)
_scoped_session = scoped_session(_session_factory)
_session = _scoped_session()

print('CREATING ALL TABLES')
_base.metadata.create_all(_engine)
print('COMMITING')
_session.commit()


```

**Error**

- execution
```
python3 run.py 
started at 2020-06-10 11:25:00
CREATING ALL TABLES
Traceback (most recent call last):
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 24, in <module>
    _base.metadata.create_all(_engine)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4464, in create_all
    bind._run_visitor(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2104, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1663, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
    self.traverse_single(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 839, in visit_table
    self.traverse_single(index)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 868, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1077, in _execute_ddl
    ret = self._execute_context(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/bobane/work/bemapps/tmp/bug_report/.venv/lib64/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: CREATE INDEX ix_auth_users_role_flags ON auth_users (role_flags)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

- mariadb log (/var/lib/mysql/__host__.err)
```
200610 11:25:00 [ERROR] mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

Server version: 10.4.13-MariaDB
key_buffer_size=1048576
read_buffer_size=131072
max_used_connections=2
max_threads=153
thread_count=8
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 337708 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7f271c000c48
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7f2784852e68 thread_stack 0x49000
/usr/libexec/mysqld(my_print_stacktrace+0x2e)[0x563ce57f823e]
/usr/libexec/mysqld(handle_fatal_signal+0x54d)[0x563ce52a037d]
/lib64/libpthread.so.0(+0x13690)[0x7f278950c690]
/usr/libexec/mysqld(_ZN12Item_func_in7cleanupEv+0x36)[0x563ce53dcae6]
/usr/libexec/mysqld(_ZN11Query_arena10free_itemsEv+0x31)[0x563ce503b3a1]
/usr/libexec/mysqld(_ZN3THD19cleanup_after_queryEv+0x109)[0x563ce503d219]
/usr/libexec/mysqld(_Z11mysql_parseP3THDPcjP12Parser_statebb+0x28d)[0x563ce508ec5d]
/usr/libexec/mysqld(_Z16dispatch_command19enum_server_commandP3THDPcjbb+0x1d91)[0x563ce5091b41]
/usr/libexec/mysqld(_Z10do_commandP3THD+0x10e)[0x563ce509338e]
/usr/libexec/mysqld(_Z24do_handle_one_connectionP7CONNECT+0x21e)[0x563ce51811ee]
/usr/libexec/mysqld(handle_one_connection+0x3b)[0x563ce518130b]
/lib64/libpthread.so.0(+0x806b)[0x7f278950106b]
/lib64/libc.so.6(clone+0x3f)[0x7f27888cb72f]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7f271c010090): is an invalid pointer
Connection ID (thread ID): 10
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.

We think the query pointer is invalid, but we will try to print it anyway. 
Query: CREATE INDEX ix_auth_users_role_flags ON auth_users (role_flags)

Writing a core file...
Working directory at /var/lib/mysql
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             127769               127769               processes 
Max open files            32190                32190                files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       127769               127769               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
Core pattern: co...
2020-06-10 11:25:00 0 [Note] InnoDB: Using Linux native AIO
2020-06-10 11:25:00 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-06-10 11:25:00 0 [Note] InnoDB: Uses event mutexes
2020-06-10 11:25:00 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-06-10 11:25:00 0 [Note] InnoDB: Number of pools: 1
2020-06-10 11:25:00 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-06-10 11:25:00 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2020-06-10 11:25:00 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-06-10 11:25:00 0 [Note] InnoDB: Completed initialization of buffer pool
2020-06-10 11:25:00 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-06-10 11:25:00 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=401524
2020-06-10 11:25:00 0 [Note] InnoDB: Starting final batch to recover 14 pages from redo log.
2020-06-10 11:25:01 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-06-10 11:25:01 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-06-10 11:25:01 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-06-10 11:25:01 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-06-10 11:25:01 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-06-10 11:25:01 0 [Note] InnoDB: Waiting for purge to start
2020-06-10 11:25:01 0 [Note] InnoDB: 10.4.13 started; log sequence number 409736; transaction id 1004
2020-06-10 11:25:01 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-06-10 11:25:01 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-06-10 11:25:01 0 [Note] InnoDB: Buffer pool(s) load completed at 200610 11:25:01
2020-06-10 11:25:01 0 [Note] Reading of all Master_info entries succeeded
2020-06-10 11:25:01 0 [Note] Added new Master_info '' to hash table
2020-06-10 11:25:01 0 [Note] /usr/libexec/mysqld: ready for connections.
Version: '10.4.13-MariaDB'  socket: '/var/run/mysql/mysql.sock'  port: 0  MariaDB Server

```

**Versions.**
 - OS: Slacware 14.2+ (Linux kernel 5.4.44) or Arch (Linux kernel 5.6.15)
 - Python: 3.8
 - SQLAlchemy: 1.3.17
 - Database: MariaDB 10.4.13
 - DBAPI: mysqlclient 1.4.6 or PyMySQL 0.9.3

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
heya -

it was not my intention to be disrespectful and I apologize if my response came off in a bad way.    it is certainly a strange issue you are having and I hope you have success in tracking it down.
