### ISSUE TITLE
AttributeError: 'CreateTable' object has no attribute '_prefixes'

### ISSUE THREAD

**Issue by iwxfer** [sqlalchemy/sqlalchemy#5394]
**Describe the bug**
When trying to create a table got the error, using Model based:
AttributeError: 'CreateTable' object has no attribute '_prefixes'

**Expected behavior**
Generate CREATE TABLE script

**To Reproduce**

```py
class Order(Base):
    __tablename__ = 'SHOPIFY_AEC_ORDERS_LINE_ITEMS_XREF'
    id = Column(Integer, primary_key=True)
    sku = Column(String)
    order_id = Column(String)
    line_item_id = Column(String)
    ack = Column(String, nullable=True)
   
    def __repr__(self):
        return "<SKU(sku='%s', OrderId='%s', LineItemId='%s')>" % (
            self.sku, self.order_id, self.line_item_id)

```

**Error**

```
Traceback (most recent call last):
  File "c:\bin\python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\bin\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bin\python\Scripts\alembic.exe\__main__.py", line 9, in <module>
  File "c:\bin\python\lib\site-packages\alembic\config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "c:\bin\python\lib\site-packages\alembic\config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "c:\bin\python\lib\site-packages\alembic\config.py", line 548, in run_cmd
    fn(
  File "c:\bin\python\lib\site-packages\alembic\command.py", line 214, in revision
    script_directory.run_env()
  File "c:\bin\python\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\bin\python\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\bin\python\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic\env.py", line 23, in <module>
    from shopify_aec_library import Base
  File "C:\dev\interfaces\shopify_aec_library.py", line 325, in <module>
    print(CreateTable(CreateTable(ShopifyOrder.__table__)))
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\elements.py", line 478, in __str__
    return str(self.compile())
  File "<string>", line 1, in <lambda>
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\elements.py", line 468, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\bin\python\lib\site-packages\sqlalchemy\sql\compiler.py", line 2872, in visit_create_table
    if table._prefixes:
AttributeError: 'CreateTable' object has no attribute '_prefixes'
```

**Versions.**
 - OS: Windows
 - Python: 3.8
 - SQLAlchemy: 1.3.13
 - Database: Postgres
 - DBAPI: psycopg2

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

that example is just a single model and doesn't show how exactly you are emiting this create table.

The stack trace however seems to suggest Alembic is being used with some kind of custom extension that's doing this:

File "C:\dev\interfaces\shopify_aec_library.py", line 325, in <module>
    print(CreateTable(CreateTable(ShopifyOrder.__table__)))

That part is causing your error because it is passing a CreateTable() object into another CreateTable object.   it's a print statement so looks like some kind of debugging code.

**Comment by zzzeek** [comment]
the issue here is in a third party library as shown in the stack trace.
