### ISSUE TITLE
util.symbol() interferes with @util.deprecated decorator

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5426]
**Describe the bug**
Adding an `@util.deprecated` decorator as shown at

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2060/3/lib/sqlalchemy/sql/schema.py#872

causes pytest to crash with 

``` text
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\_pytest\main.py", line 189, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\plugin\pytestplugin.py", line 106, in pytest_sessionstart
INTERNALERROR>     plugin_base.post_begin()
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\plugin\plugin_base.py", line 259, in post_begin
INTERNALERROR>     fn(options, file_config)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\plugin\plugin_base.py", line 341, in _init_symbols
INTERNALERROR>     from sqlalchemy.testing import config
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\__init__.py", line 9, in <module>
INTERNALERROR>     from .engine import create_engine  # noqa
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\__init__.py", line 18, in <module>
INTERNALERROR>     from . import events  # noqa
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\events.py", line 9, in <module>
INTERNALERROR>     from .base import Engine
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 12, in <module>
INTERNALERROR>     from .interfaces import Connectable
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\interfaces.py", line 11, in <module>
INTERNALERROR>     from ..sql.compiler import Compiled  # noqa
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\__init__.py", line 8, in <module>
INTERNALERROR>     from .compiler import COLLECT_CARTESIAN_PRODUCTS  # noqa
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\compiler.py", line 36, in <module>
INTERNALERROR>     from . import functions
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\functions.py", line 15, in <module>
INTERNALERROR>     from . import schema
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\schema.py", line 145, in <module>
INTERNALERROR>     class Table(DialectKWArgs, SchemaItem, TableClause):
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\schema.py", line 878, in Table
INTERNALERROR>     name=None,
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\deprecations.py", line 126, in decorate
INTERNALERROR>     fn, warning, message % dict(func=fn.__name__), version, header
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\deprecations.py", line 314, in _decorate_with_warning
INTERNALERROR>     decorated = warned(func)
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\langhelpers.py", line 161, in decorate
INTERNALERROR>     code, {targ_name: target, fn_name: fn}, fn.__name__
INTERNALERROR>   File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\langhelpers.py", line 171, in _exec_code_in_env
INTERNALERROR>     exec(code, env)
INTERNALERROR>   File "<string>", line 1, in <module>
INTERNALERROR> NameError: name 'symbol' is not defined
```

**Expected behavior**
No crash.

**Error**
Using pdb I found that the issue is related to `schema=RETAIN_SCHEMA` in the arguments list for the `tometadata` function, where RETAIN_SCHEMA is

``` python
RETAIN_SCHEMA = util.symbol("retain_schema")
```

When pdb kicks in we can see that

``` text
> <string>(1)<module>()
(Pdb) u
> c:\users\gord\git\sqla-gerrit\lib\sqlalchemy\util\langhelpers.py(171)_exec_code_in_env()
-> exec(code, env)
(Pdb) code
"def tometadata(self, metadata, schema=symbol('retain_schema'), referred_schema_fn=None, name=None):\n    return target(fn, self, metadata, schema=schema, referred_schema_fn=referred_schema_fn, name=name)\n"
(Pdb)
```

**Versions.**
 - OS: Windows 8.1
 - Python: 3.7.5 x64
 - SQLAlchemy: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2060
 - Database: mssql
 - DBAPI: pyodbc

**Comment by zzzeek** [comment]
so usually I would say, just change the signature of tometadata() to have **kw instead of that symbol() directly present, so that the decorator doesn't see it.  it's calling down into to_metadata() in any case.

you can do that here.   but alternatively, here is an enhancement to the `@decorator` function that will pull out those function defaults and allow them to be evaluatable when we make the decorator, this works at least for the tometadata() function which is enough for the moment:

```diff
diff --git a/lib/sqlalchemy/util/langhelpers.py b/lib/sqlalchemy/util/langhelpers.py
index 52debc517..57d3be83b 100644
--- a/lib/sqlalchemy/util/langhelpers.py
+++ b/lib/sqlalchemy/util/langhelpers.py
@@ -144,6 +144,10 @@ def decorator(target):
             raise Exception("not a decoratable function")
 
         spec = compat.inspect_getfullargspec(fn)
+        env = {}
+
+        spec = _update_argspec_defaults_into_env(spec, env)
+
         names = tuple(spec[0]) + spec[1:3] + (fn.__name__,)
         targ_name, fn_name = _unique_symbols(names, "target", "fn")
 
@@ -157,9 +161,9 @@ def %(name)s(%(args)s):
 """
             % metadata
         )
-        decorated = _exec_code_in_env(
-            code, {targ_name: target, fn_name: fn}, fn.__name__
-        )
+        env.update({targ_name: target, fn_name: fn})
+
+        decorated = _exec_code_in_env(code, env, fn.__name__)
         decorated.__defaults__ = getattr(fn, "im_func", fn).__defaults__
         decorated.__wrapped__ = fn
         return update_wrapper(decorated, fn)
@@ -167,6 +171,27 @@ def %(name)s(%(args)s):
     return update_wrapper(decorate, target)
 
 
+def _update_argspec_defaults_into_env(spec, env):
+    """given a FullArgSpec, convert defaults to be symbol names in an env."""
+
+    if spec.defaults:
+        new_defaults = []
+        i = 0
+        for arg in spec.defaults:
+            if type(arg).__module__ not in ("builtins", "__builtin__"):
+                name = "x%d" % i
+                env[name] = arg
+                new_defaults.append(name)
+                i += 1
+            else:
+                new_defaults.append(arg)
+        elem = list(spec)
+        elem[3] = tuple(new_defaults)
+        return compat.FullArgSpec(*elem)
+    else:
+        return spec
+
+
 def _exec_code_in_env(code, env, fn_name):
     exec(code, env)
     return env[fn_name]

```

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Rename Table.tometadata to to_metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2060
