### ISSUE TITLE
Ordering of classes will cause assoxiation_proxy assess in mapper_configured event listener to fail for versions >=1.3

### ISSUE THREAD

**Issue by Erich-e** [sqlalchemy/sqlalchemy#5430]
If a class with an association_proxy is configured before the class it is related to, accessing the association_proxy attribute will fail and throw `AttributeError: 'NoneType' object has no attribute 'uses_objects'`.
I found that this would work for `1.2.19` but not for `1.3.0` onwards.

With 1.3 this will throw:
```py
from sqlalchemy import Column, Integer, ForeignKey, event
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, mapper


Base = declarative_base()


@event.listens_for(mapper, "mapper_configured")
def f(mapper, cls):

    # Try to access the association proxy
    print(cls, Foo.bar_data)


class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    bar = relationship("Bar")
    bar_id = Column(Integer, ForeignKey("bar.id"))
    bar_data = association_proxy("bar", "data")


class Bar(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)
    data = Column(Integer)


bar = Bar(data=9)
```

With this stack trace:
```
Traceback (most recent call last):
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 241, in _as_instance
    inst = class_.__dict__[self.key + "_inst"]
KeyError: '_AssociationProxy_bar_4351340048_inst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 106, in <module>
    bar = Bar(data=9)
  File "<string>", line 2, in __init__
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 373, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 199, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 297, in __call__
    fn(*args, **kw)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3341, in _event_on_first_init
    configure_mappers()
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3232, in configure_mappers
    mapper, mapper.class_
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/orm/events.py", line 639, in wrap
    fn(*arg, **kw)
  File "example.py", line 89, in f
    print(cls, Foo.bar_data)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 187, in __get__
    inst = self._as_instance(class_, obj)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 245, in _as_instance
    inst = AssociationProxyInstance.for_proxy(self, owner, obj)
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 371, in for_proxy
    target_assoc, parent, owning_class, target_class, value_attr
  File "/Users/erich/code/nuffsaid/venv/lib/python3.7/site-packages/sqlalchemy/ext/associationproxy.py", line 388, in _construct_for_assoc
    is_object = attr.impl.uses_objects
AttributeError: 'NoneType' object has no attribute 'uses_objects'
```

However, this ordering will succeed:

```py

from sqlalchemy import Column, Integer, ForeignKey, event
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, mapper


Base = declarative_base()


@event.listens_for(mapper, "mapper_configured")
def f(mapper, cls):

    # Try to access the association proxy
    print(cls, Foo.bar_data)


class Bar(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)
    data = Column(Integer)


class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    bar = relationship("Bar")
    bar_id = Column(Integer, ForeignKey("bar.id"))
    bar_data = association_proxy("bar", "data")


bar = Bar(data=9)
```

and outputs 
```
<class '__main__.Bar'> <sqlalchemy.ext.associationproxy.ColumnAssociationProxyInstance object at 0x105d4e320>
<class '__main__.Foo'> <sqlalchemy.ext.associationproxy.ColumnAssociationProxyInstance object at 0x105d4e320>
```

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there - 

thanks for the great test.

this behavior is expected because the mapper_configured event only applies to the single mapper that is the subject of the event.  other mappers may not be configured yet.  therefore you can't do things that require those other mappers to be present without expecting exceptions.   the docs at https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=mapper_configured#sqlalchemy.orm.events.MapperEvents.mapper_configured don't (yet) have a dragon for this but the docs seem to make it fairly clear that this event occurs as mappers are configured.

the notes at https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#association-proxy-improvements describe a large number of improvements to association proxy for 1.3 which involved rearchitecting its internals to be much more aware of how related classes are actually mapped.  so in this case, attempting to use an association proxy against a not-yet-configured class won't work.   however, there's no bug becase the state of the association proxy is not corrupted and it appears to work fine afterwards.  I've modified your example to show the state that causes the problem and to also demonstrate that if the exception is caught, the mappings work fine after the exception has been thrown.

```
from sqlalchemy import Column
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import mapper
from sqlalchemy.orm import relationship


Base = declarative_base()


@event.listens_for(mapper, "mapper_configured")
def f(mapper, cls):

    # Try to access the association proxy
    try:
        print(cls, Foo.bar_data)
    except Exception as err:
        assert Foo.__mapper__.configured
        assert not Bar.__mapper__.configured
        print(
            "we got exception %s, but that's only because "
            "mapper %s is not configured yet."
            % (err, Bar.__mapper__)
        )


class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    bar = relationship("Bar")
    bar_id = Column(Integer, ForeignKey("bar.id"))
    bar_data = association_proxy("bar", "data")


class Bar(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)
    data = Column(Integer)


bar = Bar(data=9)

# works
f1 = Foo(bar = bar)

# works
assert f1.bar_data == 9

# works
print(Foo.bar_data == 10)

```

**Comment by Erich-e** [comment]
Ah, ok I think I understand.  I was probably a bit quick to assume that this was a regression, and not that I was trying to do something undefined.

Thanks for the great explanation + quick response :)
