### ISSUE TITLE
MySQL requires double parentheses for index expressions

### ISSUE THREAD

**Issue by lpsinger** [sqlalchemy/sqlalchemy#5462]
**Describe the bug**
Creating a [functional index](https://docs.sqlalchemy.org/en/13/core/constraints.html#functional-indexes) in SQLAlchemy causes an SQL syntax error for MySQL. According to the [MySQL documentation on the `CREATE INDEX` statement](https://dev.mysql.com/doc/refman/8.0/en/create-index.html), functional indices require double parentheses, like this:

```sql
CREATE INDEX idx1 ON t1 ((col1 + col2));  -- syntax ok
CREATE INDEX idx1 ON t1 (col1 + col2);  -- syntax error
```

On the other hand, there must be only a *single* set of parentheses if the index is on a column rather than on an expression:

```sql
CREATE INDEX idx1 ON t1 (col1);  -- syntax ok
CREATE INDEX idx1 ON t1 ((col1));  -- syntax error
```

Note that according to [PostgreSQL's documentation](https://www.postgresql.org/docs/12/indexes-expressional.html), it too requires double parentheses ("The syntax of the CREATE INDEX command normally requires writing parentheses around index expressions"), but in practice PostgreSQL is much more forgiving about this than PostgreSQL.

**Expected behavior**
A syntactically valid `CREATE INDEX` statement should be executed. In the example below, the generated SQL should be this:

```sql
CREATE INDEX ix_foobar_xyzzy_plugh ON foobar ((xyzzy + plugh))
```

and not this:

```sql
CREATE INDEX ix_foobar_xyzzy_plugh ON foobar (xyzzy + plugh)
```

**To Reproduce**

See Python code and stack trace below. See also [this gist](https://gist.github.com/lpsinger/d8332ffc7d8bb5bb4fc4c0534fa9bcf7) which includes a docker-compose file for spinning up the MySQL server.

```py
#!/usr/bin/env python3
from sqlalchemy import create_engine, Column, Integer, Index, func
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Foobar(Base):

    foobar_id = Column(Integer, primary_key=True)
    xyzzy = Column(Integer)
    plugh = Column(Integer)

    __tablename__ = 'foobar'

    __table_args__ = (
        Index('ix_foobar_xyzzy_plugh', xyzzy + plugh),
    )


engine = create_engine('mysql+pymysql://user:password@mysql/mysql')
Base.metadata.create_all(engine)
```

**Error**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '+ plugh)' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/test.py", line 22, in <module>
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4546, in create_all
    bind._run_visitor(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2098, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1657, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 839, in visit_table
    self.traverse_single(index)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 868, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '+ plugh)' at line 1")
[SQL: CREATE INDEX ix_foobar_xyzzy_plugh ON foobar (xyzzy + plugh)]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: GNU/Linux (Debian buster)
 - Python: 3.8.3
 - SQLAlchemy: 1.3.18
 - Database: MariaDB 10.4.12-MariaDB-1:10.4.12+maria~bionic (but also MySQL)
 - DBAPI: MySQL 8.0.21 (MySQL Community Server - GPL)

**Comment by zzzeek** [comment]
per the docs you linked this is a new feature in MySQL 8.0.13 and higher, and I guess from your second comment MariaDB 10.4.12 and higher.    SQLAlchemy's MySQL dialect would need to detect these conditions and add the parenthesis.  

this is very easy to work around, simply apply self_group(),works on this end mysql8:

```
class Foobar(Base):

    foobar_id = Column(Integer, primary_key=True)
    xyzzy = Column(Integer)
    plugh = Column(Integer)

    __tablename__ = 'foobar'

    __table_args__ = (
        Index('ix_foobar_xyzzy_plugh', (xyzzy + plugh).self_group()),
    )

```

**Comment by lpsinger** [comment]
@zzzeek, thanks for the workaround. But it doesn't work for all expressions. For example, this fails, because `radians(xyzzy)` does not get parenthesized:

```
class Foobar(Base):

    foobar_id = Column(Integer, primary_key=True)
    xyzzy = Column(Integer)
    plugh = Column(Integer)

    __tablename__ = 'foobar'

    __table_args__ = (
        Index('ix_foobar_xyzzy_plugh', (xyzzy + plugh).self_group()),
        Index('ix_foobar_xyzzy', (func.radians(xyzzy)).self_group()),
    )
```

**Comment by zzzeek** [comment]
alrighty, turn it up to 11 by using `Grouping` directly, that will get you the parens for sure

```
from sqlalchemy.sql.elements import Grouping

class Foobar(Base):

    foobar_id = Column(Integer, primary_key=True)
    xyzzy = Column(Integer)
    plugh = Column(Integer)

    __tablename__ = 'foobar'

    __table_args__ = (
        Index('ix_foobar_xyzzy_plugh', Grouping(xyzzy + plugh)),
        Index('ix_foobar_xyzzy', Grouping(func.radians(xyzzy))),
    )

```

**Comment by RamonWill** [comment]
Hey @zzzeek ,

As discussed I'll look into this. I believe i have a resolution and I will create a PR very soon.

Kind Regards,
Ramon

**Comment by zzzeek** [comment]
OK I saw some code going by, I'll try to have a look soon thanks!

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**support indexing expressions and functions for the MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2237

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **rel_1_3** branch:

**Support indexing on expressions and functions for the MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2304
