### ISSUE TITLE
Invalid SQL code is generated when combining DISTINCT ON with UNION (Postgres)

### ISSUE THREAD

**Issue by theosotr** [sqlalchemy/sqlalchemy#5469]
**Describe the bug**

I have the following models

```python
class Fixated(Base):
    __tablename__ = 'fixated'

    id = Column(Integer, primary_key=True)
    tailpipe = Column(Integer)
    joshua = Column(String(50))
    grittiest = Column(String(50))
    baltic = Column(String(50))

class Trait(Base):
    __tablename__ = 'trait'

    id = Column(Integer, primary_key=True)
    chambray_id = Column(ForeignKey('chambray.id'))
    nancy = Column(String(50))
    repairs = Column(String(50))
    nymph = Column(String(50))
```

When I run the following query on postgres

```python
q1 = session.query(Trait.repairs.label('column1')).select_from(Trait)
q1 = q1.filter(Trait.nancy.startswith('ste_', autoescape=True)).distinct(Trait.nancy)

q2 = session.query(Fixated.joshua).select_from(Fixated)
q1.union(q2)
```

SQLAlchemy crashes with

```bash
Traceback (most recent call last):
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1510, in _execute_context
    cursor, statement, parameters, context
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 586, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "trait"
LINE 1: SELECT DISTINCT ON (trait.nancy) anon_1.column1 AS anon_1_co...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tmp.py", line 34, in <module>
    for r in ret:
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2690, in __iter__
    return self._iter().__iter__()
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2700, in _iter
    future=True,
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1621, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1333, in _execute_20
    return meth(self, multiparams, params, execution_options)
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 310, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1232, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1553, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1734, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 172, in raise_
    raise exception
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1510, in _execute_context
    cursor, statement, parameters, context
  File "/home/.env/lib/python3.6/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 586, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) missing FROM-clause entry for table "trait"
LINE 1: SELECT DISTINCT ON (trait.nancy) anon_1.column1 AS anon_1_co...
                            ^

[SQL: SELECT DISTINCT ON (trait.nancy) anon_1.column1 AS anon_1_column1
FROM (SELECT DISTINCT ON (trait.nancy) trait.repairs AS column1
FROM trait
WHERE (trait.nancy LIKE %(nancy_1)s || '%%' ESCAPE '/') UNION SELECT fixated.joshua AS fixated_joshua
FROM fixated) AS anon_1]
[parameters: {'nancy_1': 'ste/_'}]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

because the generated query is wrong! That is

```sql
SELECT DISTINCT ON (trait.nancy) anon_1.column1 AS anon_1_column1
FROM (SELECT DISTINCT ON (trait.nancy) trait.repairs AS column1
FROM trait
WHERE (trait.nancy LIKE %(nancy_1)s || '%%' ESCAPE '/') UNION SELECT fixated.joshua AS fixated_joshua
FROM fixated) AS anon_1
```

**Expected behavior**

The right query should be

```sql
SELECT anon_1.column1 AS anon_1_column1
FROM (SELECT DISTINCT ON (trait.nancy) trait.repairs AS column1
FROM trait
WHERE (trait.nancy LIKE %(nancy_1)s || '%%' ESCAPE '/') UNION SELECT fixated.joshua AS fixated_joshua
FROM fixated) AS anon_1
```

**NOTE**:  I ran the expected SQL query above on Postgres, and returned the desired records!

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

thanks for this test.

any reason you are running on the un-released github master?    current master is extremely unstable, though it's very useful if you are in fact alpha testing it.

**Comment by zzzeek** [comment]
e.g. this works fine in the current 1.3 release.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure _distinct_on removed within from_selectable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2102
