### ISSUE TITLE
DeferredReflection with postgres (materialized) views

### ISSUE THREAD

**Issue by ibot3** [sqlalchemy/sqlalchemy#5499]
I want to reflect a view by using the declarative way with DeferredReflection:

```
class ViewName(DeferredReflection, ModelBase):
    __tablename__ = 'view_name'

    id = Column(Integer, primary_key=True)
```

However, when executing the reflections with

```
DeferredReflection.prepare(engine)
```
I get the error `sqlalchemy.exc.NoSuchTableError: view_name`, although the view exists in the database.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/pycroft/app/helpers/interactive.py", line 31, in <module>
    DeferredReflection.prepare(engine)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/api.py", line 755, in prepare
    cls._sa_decl_prepare(thingy.local_table, engine)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/api.py", line 787, in _sa_decl_prepare
    cls._reflect_table(local_table, engine)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/api.py", line 808, in _reflect_table
    schema=table.schema,
  File "<string>", line 2, in __new__
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 545, in __new__
    table._init_existing(*args, **kw)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 762, in _init_existing
    _extend_on=_extend_on,
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 672, in _autoload
    _extend_on=_extend_on,
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2215, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1654, in run_callable
    return callable_(self, *args, **kwargs)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 666, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 392, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2936, in get_columns
    connection, table_name, schema, info_cache=kw.get("info_cache")
  File "<string>", line 2, in get_table_oid
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/opt/pycroft/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2850, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: view_name
```

Is there some option somewhere that needs to be enabled to support views or is it not possible at all to use `DeferredReflection` with views?

**Versions**
 - OS: Debian 9
 - Python: 3.7
 - SQLAlchemy: 1.3.18
 - Database: Postgres 12
 - DBAPI: psycopg2

**Comment by zzzeek** [comment]
hi there -

using the [MCVE](http://stackoverflow.com/help/mcve) below I cannot reproduce.  Please run the program below and try to see what is different about your application vs. the example below.


```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import DeferredReflection
from sqlalchemy.orm import Session

Base = declarative_base()


class ViewName(DeferredReflection, Base):
    __tablename__ = "view_name"

    id = Column(Integer, primary_key=True)


e = create_engine("postgresql://scott:tiger@localhost/test", echo="debug")

with e.connect() as conn:
    t = conn.begin()
    conn.execute("create table foo (id integer)")
    conn.execute("insert into foo (id) values (1)")
    conn.execute("create materialized view view_name as (select id from foo)")

    DeferredReflection.prepare(conn)

    s = Session(conn)
    print(s.query(ViewName).all())

```

**Comment by ibot3** [comment]
Okay, it seems to be a problem with one specific environment of our software, where the database seems to be empty (which is strange because the connection string is the same).

**Comment by nickspeal** [comment]
@zzzeek this issue seems to have resurfaced with SQLAlchemy 2.0.15. I've updated your sample code to be compatible with the SQLAlchemy 2.0 syntax, and I'm seeing an error:

```
Traceback (most recent call last):
  File "sample_view_reflection.py", line 27, in <module>
    DeferredReflection.prepare(e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/extensions.py", line 437, in prepare
    metadata.reflect(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 5745, in reflect
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql://scott:****@localhost/test): (view_name)
```

Sample code:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import text
from sqlalchemy.ext.declarative import DeferredReflection
from sqlalchemy.orm import Session, declarative_base

Base = declarative_base()


class ViewName(DeferredReflection, Base):
    __tablename__ = "view_name"

    id = Column(Integer, primary_key=True)

e = create_engine("postgresql://scott:tiger@localhost/test", echo="debug")

with e.connect() as conn:
    t = conn.begin()
    conn.execute(text("create table foo (id integer)"))
    conn.execute(text("insert into foo (id) values (1)"))
    conn.execute(text("create materialized view view_name as (select id from foo)"))

    DeferredReflection.prepare(e)

    s = Session(conn)
    print(s.query(ViewName).all())
```

I suspect that this could be because `views=True` is not being passed into the call to`reflect` [here](https://github.com/sqlalchemy/sqlalchemy/blame/main/lib/sqlalchemy/ext/declarative/extensions.py#L437), introduced with [this change](https://github.com/sqlalchemy/sqlalchemy/commit/6cc063f4a217fd2c2831eb3a76a1fe237c42867f).

**Comment by zzzeek** [comment]
I would add arguments to the prepare() method here that you can pass through.   See #9828 will be in 2.0.16.

**Comment by nickspeal** [comment]
Thank you for such quick response! This is my last blocker to upgrading to 2.0. I appreciate it!!
