### ISSUE TITLE
Invalid Query is generated on MS Server (distinct) 

### ISSUE THREAD

**Issue by theosotr** [sqlalchemy/sqlalchemy#5511]
**Describe the bug**

SQLAlchemy produces an invalid MSSQL query.

Specifically, I have the following simple query run on MS Server.

```python
expr = Table.col+ literal(1) 
session.query(expr).select_from(Yangon).order_by(asc(expr)).distinct()
```

this causes the following exception

```
Traceback (most recent call last):
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified. (145) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "driver_mssql.py", line 34, in <module>
    for r in ret2:
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified. (145) (SQLExecDirectW)')
[SQL: SELECT DISTINCT table.col + ? AS anon_1
FROM table ORDER BY table.col + ? ASC]
[parameters: (1, 1)]
(Background on this error at: http://sqlalche.me/e/f405)
````

**Expected behavior**

```sql
SELECT DISTINCT table.col + 1 AS anon_1
FROM table ORDER BY anon_1 ASC
```

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

you have already reported #5470 which appears to be the same issue and has already been fixed, though not released yet.  Can you please test with the current rel_1_3 branch and ensure your code is working, thanks:

    git clone -b rel_1_3 https://github.com/sqlalchemy/sqlalchemy.git
    cd sqlalchemy
    pip install .

**Comment by theosotr** [comment]
Hi

I followed your instructions, but the code still crashes.

**Comment by zzzeek** [comment]
ok then we reopen #5470 which was not fixed correctly, which is already tracking this issue.

**Comment by zzzeek** [comment]
The recommended approach to this problem in all cases is to name the label explicitly in your ORDER BY.  this will work on all versions, please use this approach:

    expr = (Yangon.col + literal(1)).label("foo")
    q = s.query(expr).select_from(Yangon).order_by(asc("foo")).distinct()
    q.all()
