### ISSUE TITLE
allow polymorphic_union column name to be customized

### ISSUE THREAD

**Issue by Jesse-Bakker** [sqlalchemy/sqlalchemy#5513]
**Describe the bug**
When using AbstractConcreteBase to define a concrete inheritance hierarchy, sqlalchemy uses a column named `type` as discriminator. If sublcass has a column named `type`, this causes an error when querying polymorphically because there are then two columns named `type`.

**Expected behavior**
Polymorphic query gives results from all subclasses.

**To Reproduce**

```py
from sqlalchemy import create_engine, Column, Integer, ForeignKey, String
from sqlalchemy.ext.declarative import declarative_base, AbstractConcreteBase, declared_attr, ConcreteBase
from sqlalchemy.orm import configure_mappers, relationship
from sqlalchemy.orm import Session

Base = declarative_base()

class Employee(AbstractConcreteBase, Base):
    employee_id = Column(Integer, primary_key=True)

class Manager(Employee):
    __tablename__ = 'manager'

    name = Column(String(50))
    manager_data = Column(String(40))

    type = Column(String(20))

    __mapper_args__ = {
        'polymorphic_identity':'manager',
        'concrete':True}

class Engineer(Employee):
    __tablename__ = 'engineer'

    name = Column(String(50))

    type = Column(String(30))

    __mapper_args__ = {
        'polymorphic_identity':'engineer',
        'concrete':True}

engine = create_engine("<connection string>", echo=True)

session = Session(bind=engine)
session.add_all([
    Manager(name="A", manager_data="ABC", type="Z"),
    Engineer(name="B", type="W"),
    ])

session.commit()
session.query(Employee).all()

```

**Error**

```
Traceback (most recent call last):
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AmbiguousColumn: column reference "type" is ambiguous
LINE 1: ...d AS pjoin_employee_id, pjoin.name AS pjoin_name, pjoin.type...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "models.py", line 45, in <module>
    session.query(Employee).all()
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/home/jesse/.local/share/virtualenvs/sqla-XdCa15U5/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.AmbiguousColumn) column reference "type" is ambiguous
LINE 1: ...d AS pjoin_employee_id, pjoin.name AS pjoin_name, pjoin.type...
                                                             ^

[SQL: SELECT pjoin.employee_id AS pjoin_employee_id, pjoin.name AS pjoin_name, pjoin.type AS pjoin_type, pjoin.manager_data AS pjoin_manager_data
FROM (SELECT grunt.employee_id AS employee_id, grunt.name AS name, grunt.type AS type, CAST(NULL AS VARCHAR(40)) AS manager_data, 'engineer' AS type
FROM grunt UNION ALL SELECT manager.employee_id AS employee_id, manager.name AS name, manager.type AS type, manager.manager_data AS manager_data, 'manager' AS type
FROM manager) AS pjoin]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: 5.7.12-arch1-1 x86_64 GNU/Linux
 - Python: 3.8.5
 - SQLAlchemy: 1.3.18
 - Database: PostgreSQL and MySQL
 - DBAPI: psycopg2 and pymysql

**Have a nice day!**

**Comment by zzzeek** [comment]
Here's a workaround you can use for now, no ETA on this feature:

```
from sqlalchemy.orm import polymorphic_union

class MyBase(...):
    @classmethod
    def _create_polymorphic_union(cls, mappers):
        return polymorphic_union(
            OrderedDict(
                (mp.polymorphic_identity, mp.local_table) for mp in mappers
            ),
            "some_name_that_is_not_type",
            "pjoin",
        )

```

**Comment by Jesse-Bakker** [comment]
That was exactly my tried solution to this problem. It is not the entire workaround however, as there is also a reference to the `type` collumn in (https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/declarative/api.py#L631), so that method needs to be overridden as well

**Comment by zzzeek** [comment]
ouch, OK, so another way to get around this is to map your "type" column to a different name like this:

```
class Foo:
    alt_type = Column("type", ...)

```

I can accept PRs for allowing this name to change

**Comment by Jesse-Bakker** [comment]
Unfortunately, that does not fix the problem, as in queries, the actual column name is used instead of the mapped name. I have it working for now by overriding all methods mentioning `type`. 

I am willing to send a PR so I can get rid of the workaround. 
What would be the preferred way of configuring the column name? I see a couple options:
 
- Add a mapper argument
- Override the column name with `polymorphic_on` if set
- Add a class attribute (say, `__discriminator_columname__`)
- Add a class method to AbstractConcreteBase (`AbstractConcreteBase.with_discriminator_column("alternative")`)

**Comment by zzzeek** [comment]
this is very specific to the "ConcreteBase" thing so I would make it an attribute that is least likely to be confused as some general term, like "_concrete_discriminator_name".

**Comment by sqla-tester** [comment]
**Jesse Bakker** has proposed a fix for this issue in the **master** branch:

**Make discriminator column used by ConcreteBase configurable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by sqla-tester** [comment]
**Jesse Bakker** has proposed a fix for this issue in the **rel_1_3** branch:

**Make discriminator column used by ConcreteBase configurable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2156
