### ISSUE TITLE
_finalize_fairy function causes an exception after all code has finished running

### ISSUE THREAD

**Issue by MosheVai** [sqlalchemy/sqlalchemy#5522]
I have a code that runs for approx 20 min, after all the lines of code have finished running (according to my last log) I receive an exception.
I was unable to reproduce it in a minimal fashion, but it seems like there is a connection exception in the `_finalize_fairy` function:

<details>

```
Exception during reset or similar
Traceback (most recent call last):
  File "D:\code\git_code\my-repo\venv\lib\site-packages\sqlalchemy\pool\base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "D:\code\git_code\my-repo\venv\lib\site-packages\sqlalchemy\pool\base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "D:\code\git_code\my-repo\venv\lib\site-packages\sqlalchemy\engine\default.py", line 538, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

</details>

This is odd because as I said all "my" code has finished running, Is there some sort of thread that  `sqlalchemy`  spawns?
I also don't get a full exception stack to see which piece of code calls this function.

**Comment by zzzeek** [comment]
that exception is not actually "raising", it's just being logged.    this is typically due to a database connection not being returned to the pool when the program ends, but it's not typical that it indicates the server closed the connection, so I would assume this is because Python shutdown is non-deterministic and the connection is in a bad state.

SQLAlchemy does not spawn any threads but your Python interpreter does, namely the gc.collect() thread.   so when you see connection fairy things that seem to be in a new thread, they are in the Python interpreter's thread.

here's how to reproduce almost the same thing:

```

from sqlalchemy import create_engine

e = create_engine("postgresql://scott:tiger@localhost/test")

c = e.connect()

# close out the psycopg2 connection directly, so the pool
# can't act upon it.
c.connection.connection.close()



```

output:

```
$ python test3.py 
Exception during reset or similar
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/pool/base.py", line 620, in _finalize_fairy
    fairy._reset(pool)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/pool/base.py", line 820, in _reset
    pool._dialect.do_rollback(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/default.py", line 552, in do_rollback
    dbapi_connection.rollback()
psycopg2.InterfaceError: connection already closed

```

**Comment by zzzeek** [comment]
it's likely there is some unsmoothness here causing this error, however AFAICT this is just in the logs and is likely related to some unsmoothness in the GC process.  if you can provide a reproducer feel free to reopen.

**Comment by karlicoss** [comment]
I believe this is related to the error I was getting in https://github.com/sqlalchemy/sqlalchemy/issues/5632

(again, sorry for the 

```python
import_me = '''
# NOTE: if you comment this out, it works fine
from sqlalchemy import Column

import re
# NOTE: if you comment this out, it works fine
re.hack = lambda: None
'''
from pathlib import Path
Path('import_me.py').write_text(import_me)

### NOTE: couldn't reproduce without a separate file
import import_me

def it():
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:////tmp/test.sqlite')
    with engine.connect() as conn:
        try:
            print("BEFORE")
            yield 0
            print("AFTER")
        except GeneratorExit as e:
            print("GENERATOREXIT")

import logging
logging.basicConfig()
logging.getLogger('sqlalchemy.pool').setLevel(logging.DEBUG)

g = it()
next(g)

print("FINISHED")
```

Expected log:

```
BEFORE # corresponds to next(g)
FINISHED
GENERATOREXIT # happens after FINISHED, because python finalizes the generators on exit
```

**What I'm getting** (also added some traceback calls to the sqlalchemy code)
```
DEBUG:sqlalchemy.pool.impl.NullPool:Created new connection <sqlite3.Connection object at 0x7f08916f1210>
DEBUG:sqlalchemy.pool.impl.NullPool:Connection <sqlite3.Connection object at 0x7f08916f1210> checked out from pool
BEFORE
FINISHED
DEBUG:sqlalchemy.pool.impl.NullPool:Connection <sqlite3.Connection object at 0x7f08916f1210> being returned to pool
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 506, in <lambda>
    and _finalize_fairy(None, rec, pool, ref, echo),
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in _finalize_fairy
    traceback.print_stack()
DEBUG:sqlalchemy.pool.impl.NullPool:Connection <sqlite3.Connection object at 0x7f08916f1210> rollback-on-return
DEBUG:sqlalchemy.pool.impl.NullPool:Closing connection <sqlite3.Connection object at 0x7f08916f1210>
GENERATOREXIT
DEBUG:sqlalchemy.pool.impl.NullPool:Connection <sqlite3.Connection object at 0x7f08916f1210> being returned to pool
  File "run.py", line 25, in it
    print("GENERATOREXIT")
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 181, in __exit__
    self.close()
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 923, in close
    conn.close()
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 1037, in close
    self._checkin()
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 862, in _checkin
    _finalize_fairy(
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in _finalize_fairy
    traceback.print_stack()
DEBUG:sqlalchemy.pool.impl.NullPool:Connection <sqlite3.Connection object at 0x7f08916f1210> rollback-on-return
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 700, in _finalize_fairy
    fairy._reset(pool)
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 896, in _reset
    pool._dialect.do_rollback(self)
  File "python3.8/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

So what seems to happen is:
- first something within sqlalchemy tries to finalize the connection and succeeds
- then python tries to finalize the generator, and dispose of the context manager, which also tries to close the connection and results in this exception

Note that there are not explicit `close()` in this snippet or anything -- it relies on the context manager pattern, so expected to work fine? Feels kinda wrong that sqlalchemy closes the connection before the actual `__exit__` method of the context manger kicks in?

Either way, this is logged with `error` level, so it always ends up in the terminal. One way I can see now of suppressing it is something like:

```python
        except GeneratorExit as e:      
            logging.getLogger('sqlalchemy.pool').setLevel(logging.CRITICAL)
            print("GENERATOREXIT")
```

, not very nice, but does the trick.

**Comment by zzzeek** [comment]
@karlicoss your test is doing the thing that above I mention will cause this problem.  you have a database connection hanging open inside of a pending generator and then the program exits.   you should expect garbage collection messages in these cases.

**Comment by karlicoss** [comment]
Yeah, I agree it's sort of weird to have a generator holding onto the database (although it's something I have to do). But was a massive pain to investigate, so hopefully my logs would be useful to someone else :)

**Comment by karlicoss** [comment]
P.S. another snippet which doesn't even open connections, but causes some cleanup error messages:

```python
def it():
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:////tmp/test.sqlite')
    try:
        try:
            yield 0
        except GeneratorExit:
            pass
    finally:
        engine.dispose()

import logging
logging.basicConfig()
logging.getLogger('sqlalchemy.pool').setLevel(logging.DEBUG)

g = it()
next(g)
```

```
FINISHED
INFO:sqlalchemy.pool.impl.NullPool:Pool recreating
Exception ignored in: <generator object it at 0x7fd72822d740>
Traceback (most recent call last):
  File "run.py", line 33, in it
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 2078, in dispose
  File "python3.8/site-packages/sqlalchemy/pool/impl.py", line 244, in recreate
  File "<string>", line 2, in __init__
  File "python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
  File "python3.8/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "python3.8/site-packages/sqlalchemy/event/base.py", line 149, in _update
  File "python3.8/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "python3.8/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: <weakref at 0x7fd728368860; to 'function' at 0x7fd7273dd040 (go)>
```

Looks different, not sure if it's a legitimate logic error though...

**Comment by numeric-lee** [comment]
similar error. it did recover from this error and complete its task

Exception during reset or similar
Traceback (most recent call last):
  File "/home/le/.conda/envs/lex/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/le/.conda/envs/lex/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/le/.conda/envs/lex/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: SSL connection has been closed unexpectedly

**Comment by evoludigit** [comment]
I had the same problem for a long time, I managed to solve it by enclosing the generator in a try / finally clause:

before:

```python
@pytest.fixture(scope="function")
def session(in_memory_db):
    """SQLAlchemy session"""
    clear_mappers()
    orm.start_mappers()
    Session = sessionmaker(bind=in_memory_db)
    session = Session()
    yield session
````

would the following error:

````
Exception during reset or similar
Traceback (most recent call last):
  File "/path/to/sqlalchemy/pool/base.py", line 988, in _finalize_fairy
    fairy._reset(
  File "/path/to/sqlalchemy/pool/base.py", line 1436, in _reset
    pool._dialect.do_rollback(self)
  File "/path/to/sqlalchemy/engine/default.py", line 691, in do_rollback
    dbapi_connection.rollback()
  File "/path/to/psycopg/connection.py", line 889, in rollback
    self.wait(self._rollback_gen())
  File "/path/to/psycopg/connection.py", line 957, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/path/to/psycopg/pq/pq_ctypes.py", line 229, in socket
    rv = self._call_int(impl.PQsocket)
  File "/path/to/psycopg/pq/pq_ctypes.py", line 719, in _call_int
    raise e.OperationalError("the connection is closed")
```

I could solve the problem by enclosing the yield in a try/finally clause, and calling close_all_sessions() explicitly:

```
from sqlalchemy.orm import close_all_sessions()

@pytest.fixture(scope="function")
def session(in_memory_db):
    """SQLAlchemy session"""
    clear_mappers()
    orm.start_mappers()
    Session = sessionmaker(bind=in_memory_db)
    session = Session()
    try:
        yield session
    finally:
        close_all_sessions()
```

**Comment by CaselIT** [comment]
You don't need to close all sessions everywhere, you just need to close the session created in the context

**Comment by evoludigit** [comment]
@CaselIT 
you are right, thank you for your input. This did the job as well:

```python
try:
    yield session
finally:
    session.close()
```

**Comment by CaselIT** [comment]
I noticed only later that this is in pytest. Most likely in that case the two options are equivalent, but for a general purpose context manage, only the generated session should be closed
