### ISSUE TITLE
make URL a NamedTuple like stdlib url objects; provide a method to alter fields in a new copy

### ISSUE THREAD

**Issue by rjarry** [sqlalchemy/sqlalchemy#5526]
**Describe the bug**

Since commit https://github.com/sqlalchemy/sqlalchemy/commit/2644693c0bf5b775f7a7283cdbf566a37872586f converting an URL object to string will fail if query parameter values are not string nor bytes. Before this fix, query parameter values were (silently) converted to string (and not quoted, which was a problem).

**Expected behavior**

Non-string query parameter values should be converted to string before calling `urllib.parse.quote_plus()`.

**To Reproduce**

```pycon
root@f7839e4d5ed1:/# python3
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
...
>>> from sqlalchemy.engine import url
>>> u = url.make_url('mysql:///dbname?charset=utf8')
>>> u.query['use_unicode'] = True
>>> str(u)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/url.py", line 106, in __str__
    return self.__to_string__(hide_password=False)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/url.py", line 98, in __to_string__
    s += "?" + "&".join(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/url.py", line 99, in <genexpr>
    "%s=%s" % (util.quote_plus(k), util.quote_plus(element))
  File "/usr/lib/python3.8/urllib/parse.py", line 855, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/lib/python3.8/urllib/parse.py", line 839, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.8/urllib/parse.py", line 864, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Versions.**
 - OS: All
 - Python: 3
 - SQLAlchemy: 1.3.18
 - Database: All
 - DBAPI: N/A

**Naïve patch to fix the problem**

```diff
diff --git a/lib/sqlalchemy/engine/url.py b/lib/sqlalchemy/engine/url.py
index f0685d9e3367..f8be390ce943 100644
--- a/lib/sqlalchemy/engine/url.py
+++ b/lib/sqlalchemy/engine/url.py
@@ -96,7 +96,7 @@ class URL(object):
             keys = list(self.query)
             keys.sort()
             s += "?" + "&".join(
-                "%s=%s" % (util.quote_plus(k), util.quote_plus(element))
+                "%s=%s" % (util.quote_plus(k), util.quote_plus(str(element)))
                 for k in keys
                 for element in util.to_list(self.query[k])
             )
```

**Comment by zzzeek** [comment]
after looking at urllib.urlparse I realized it's kind of weird we aren't doing the same thing.   the change I made here though is a hard change for 1.4.    trying to do a deprecation path on this one would be really painful and I'm hoping those folks who have some URL mutation going on can make the change on their end for 1.4.    I have a few downstream things I've already put out modifications for.
