### ISSUE TITLE
Cannot insert ARRAY of Enum with Postgres

### ISSUE THREAD

**Issue by daveisfera** [sqlalchemy/sqlalchemy#5537]
**Describe the bug**
An `ARRAY` of `Enum` can now be created ( see #5265 and #5266 ), but values cannot be inserted into it.

**Expected behavior**
Values can be inserted into the created column

**To Reproduce**
```py
import enum
from typing import List

from sqlalchemy import ARRAY
from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

Base = declarative_base()


class MyEnum(enum.Enum):
    one = 1
    two = 2
    three = 3


class TestArrayEnum(Base):
    __tablename__ = "test_array_enum"
    id = Column(Integer, primary_key=True)
    values = Column(ARRAY(Enum(MyEnum)), nullable=False)

    def __init__(self, values: List[MyEnum]):
        self.values = values


engine = create_engine('***postgress connection string***')
Base.metadata.create_all(engine)

session = Session(engine)

session.add(TestArrayEnum([MyEnum.one, MyEnum.two, MyEnum.three]))

session.commit()
```

**Error**
```
Traceback (most recent call last):
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: column "values" is of type myenum[] but expression is of type text[]
LINE 1: INSERT INTO test_array_enum (values) VALUES (ARRAY['one','tw...
                                                     ^
HINT:  You will need to rewrite or cast the expression.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    session.commit()
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1252, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "values" is of type myenum[] but expression is of type text[]
LINE 1: INSERT INTO test_array_enum (values) VALUES (ARRAY['one','tw...
                                                     ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO test_array_enum (values) VALUES (%(values)s) RETURNING test_array_enum.id]
[parameters: {'values': ['one', 'two', 'three']}]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Versions.**
 - OS: macOS 10.15.6
 - Python: 3.8.2
 - SQLAlchemy: 1.3.19
 - Database: Postgres 11.7
 - DBAPI: psycopg2 2.8.5

**Additional context**
Setting `create_constraint=False, native_enum=False` is a workaround so data can be inserted

**Comment by zzzeek** [comment]
issue #5265 is explciitly "INSERT".  "create" has never been an issue.   So this issue would contradict what the test case I would assume is present there is testing.   triage is still ongoing as im on a phone call right now.

**Comment by zzzeek** [comment]
OK, we have a weird one because i know you didn't make up that stack trace, no failure on this end, Python 3.8.3, psycopg2 2.8.5, I have a lot of PG versions here and my 11 version is "PostgreSQL 11.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit'"

output is clean (perfect test thanks) see below for echo='debug':

```
 python test3.py 
2020-08-25 10:28:23,436 INFO sqlalchemy.engine.base.Engine select version()
2020-08-25 10:28:23,437 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,438 DEBUG sqlalchemy.engine.base.Engine Col ('version',)
2020-08-25 10:28:23,438 DEBUG sqlalchemy.engine.base.Engine Row ('PostgreSQL 11.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit',)
2020-08-25 10:28:23,439 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-08-25 10:28:23,439 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,440 DEBUG sqlalchemy.engine.base.Engine Col ('current_schema',)
2020-08-25 10:28:23,440 DEBUG sqlalchemy.engine.base.Engine Row ('public',)
2020-08-25 10:28:23,441 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-08-25 10:28:23,441 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,442 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-08-25 10:28:23,442 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,443 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-08-25 10:28:23,443 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,443 DEBUG sqlalchemy.engine.base.Engine Col ('standard_conforming_strings',)
2020-08-25 10:28:23,444 DEBUG sqlalchemy.engine.base.Engine Row ('on',)
2020-08-25 10:28:23,445 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2020-08-25 10:28:23,445 INFO sqlalchemy.engine.base.Engine {'name': 'test_array_enum'}
2020-08-25 10:28:23,447 DEBUG sqlalchemy.engine.base.Engine Col ('relname',)
2020-08-25 10:28:23,447 DEBUG sqlalchemy.engine.base.Engine Row ('test_array_enum',)
2020-08-25 10:28:23,447 INFO sqlalchemy.engine.base.Engine 
DROP TABLE test_array_enum
2020-08-25 10:28:23,447 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,450 INFO sqlalchemy.engine.base.Engine COMMIT
2020-08-25 10:28:23,454 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2020-08-25 10:28:23,454 INFO sqlalchemy.engine.base.Engine {'typname': 'myenum'}
2020-08-25 10:28:23,457 DEBUG sqlalchemy.engine.base.Engine Col ('exists',)
2020-08-25 10:28:23,457 DEBUG sqlalchemy.engine.base.Engine Row (True,)
2020-08-25 10:28:23,457 INFO sqlalchemy.engine.base.Engine DROP TYPE myenum
2020-08-25 10:28:23,457 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,459 INFO sqlalchemy.engine.base.Engine COMMIT
2020-08-25 10:28:23,462 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2020-08-25 10:28:23,462 INFO sqlalchemy.engine.base.Engine {'name': 'test_array_enum'}
2020-08-25 10:28:23,465 DEBUG sqlalchemy.engine.base.Engine Col ('relname',)
2020-08-25 10:28:23,466 INFO sqlalchemy.engine.base.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )
                
2020-08-25 10:28:23,466 INFO sqlalchemy.engine.base.Engine {'typname': 'myenum'}
2020-08-25 10:28:23,467 DEBUG sqlalchemy.engine.base.Engine Col ('exists',)
2020-08-25 10:28:23,468 DEBUG sqlalchemy.engine.base.Engine Row (False,)
2020-08-25 10:28:23,469 INFO sqlalchemy.engine.base.Engine CREATE TYPE myenum AS ENUM ('one', 'two', 'three')
2020-08-25 10:28:23,469 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,471 INFO sqlalchemy.engine.base.Engine COMMIT
2020-08-25 10:28:23,476 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE test_array_enum (
	id SERIAL NOT NULL, 
	values myenum[] NOT NULL, 
	PRIMARY KEY (id)
)


2020-08-25 10:28:23,476 INFO sqlalchemy.engine.base.Engine {}
2020-08-25 10:28:23,490 INFO sqlalchemy.engine.base.Engine COMMIT
2020-08-25 10:28:23,494 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-08-25 10:28:23,496 INFO sqlalchemy.engine.base.Engine INSERT INTO test_array_enum (values) VALUES (CAST(%(values)s AS myenum[])) RETURNING test_array_enum.id
2020-08-25 10:28:23,496 INFO sqlalchemy.engine.base.Engine {'values': ['one', 'two', 'three']}
2020-08-25 10:28:23,499 DEBUG sqlalchemy.engine.base.Engine Col ('id',)
2020-08-25 10:28:23,499 DEBUG sqlalchemy.engine.base.Engine Row (1,)
2020-08-25 10:28:23,500 INFO sqlalchemy.engine.base.Engine COMMIT

```

**Comment by zzzeek** [comment]
OK, it seems very likely you are not running SQLAlchemy 1.3.19 since the line numbers in your stack trace do not line up with that version of the code (I can't find which version they match up with).  your stack trace shows:

 File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multip

line 988 of SQLAlchemy 1.3.19 is not where execute() is.  That line is in the middle of a comment:

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_19/lib/sqlalchemy/engine/base.py#L988

another one, line 1252

File "/Users/dlj/.pyenv/versions/3.8.2/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1252, in _execute_context
    self._handle_dbapi_exception(

that's not the code on that line:

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_19/lib/sqlalchemy/engine/base.py#L1252

Please ensure you are running the latest SQLAlchemy 1.3.19 by inspecting sqlalchemy.__version__ at runtime and re-test, thanks!

**Comment by daveisfera** [comment]
Before submitting this issue, I verified that the version in `requirements.txt` was correct and that it had installed into the `venv` correctly, but didn't verify that the `venv` was being used. 🤦 

Now that I fixed that, the above test is running correctly. It's creating the column as a string type in the table instead of an enum, so is that expected?

**Comment by zzzeek** [comment]
> Before submitting this issue, I verified that the version in `requirements.txt` was correct and that it had installed into the `venv` correctly, but didn't verify that the `venv` was being used. facepalm
> 
> Now that I fixed that, the above test is running correctly. It's creating the column as a string type in the table instead of an enum, so is that expected?

you had mentioned you set "native_enum=False" for your workaround, you probably need to go back to using native_enum.      note the output I pasted in my run of your script as written:

```

CREATE TABLE test_array_enum (
	id SERIAL NOT NULL, 
	values myenum[] NOT NULL, 
	PRIMARY KEY (id)
)
```

**Comment by daveisfera** [comment]
`native_enum` defaults to `True`, so I'm not sure what I was seeing before, but I couldn't consistently reproduce the problem and after completely resetting my Postgres database and `venv`, I always get the expected result (i.e. it creates the enum in Postgres correctly), so looks like this was all just noise.

**Comment by zzzeek** [comment]
the table with the native_enum=False was probably still in your PG database and perhaps it didn't get dropped when you went to recreate it again.    glad it works now!
