### ISSUE TITLE
Feature not supported: UNIQUE column constraint

### ISSUE THREAD

**Issue by nndo1991** [sqlalchemy/sqlalchemy#5551]
**Describe the bug**

We are the developers of [sqlalchemy_exasol](https://github.com/blue-yonder/sqlalchemy_exasol) and we are trying to upgrade `SQLAlchemy==1.3.16` to `SQLAlchemy==1.3.19`. Now all of the _QuotedNameArgumentTest_ tests inside the **test_suite.py** are failing, and it used to work fine in 1.3.16

**To Reproduce**

```py
py.test --dropfirst --dburi exa+pyodbc://sys:exasol@localhost:8888/TEST?DRIVER=EXAODBC&CONNECTIONLCALL=en_US.UTF-8
```

**Error**

```
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_check_constraints[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_check_constraints[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_columns[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_columns[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_foreign_keys[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_foreign_keys[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_indexes[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_indexes[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_pk_constraint[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_pk_constraint[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_table_comment[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_table_comment[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_table_options[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_table_options[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_unique_constraints[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_unique_constraints[quote ' one-_exclusions0] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_view_definition[quote " two-_exclusions1] ERROR
test/test_suite.py::QuotedNameArgumentTest_exasol+pyodbc_6_2_6::test_get_view_definition[quote ' one-_exclusions0] ERROR
```

```
______________ ERROR at setup of QuotedNameArgumentTest_exasol+pyodbc_6_2_6.test_get_check_constraints[quote " two-_exclusions1] _____
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
pyodbc.NotSupportedError: ('0A000', '[0A000] [EXASOL][EXASolution driver]Feature not supported: UNIQUE column constraint (Session: 1676648133635310965) (-1) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/testing/fixtures.py", line 117, in setup_class
    cls._setup_once_tables()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/testing/fixtures.py", line 147, in _setup_once_tables
    cls.metadata.create_all(cls.bind)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4556, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2097, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 787, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.NotSupportedError: (pyodbc.NotSupportedError) ('0A000', '[0A000] [EXASOL][EXASolution driver]Feature not supported: UNIQUE column constraint (Session: 1676648133635310965) (-1) (SQLExecDirectW)')
[SQL: 
CREATE TABLE "quote ' one" (
	id INTEGER NOT NULL, 
	name VARCHAR(50), 
	"data" VARCHAR(50), 
	related_id INTEGER, 
	CONSTRAINT "pk quote ' one" PRIMARY KEY (id), 
	CONSTRAINT "uq quote' one" UNIQUE ("data"), 
	CONSTRAINT "ck quote ' one" CHECK (name != 'foo')
)

]
(Background on this error at: http://sqlalche.me/e/13/tw8g)
```

**Versions.**
 - OS: Debian GNU/Linux 10 (buster)
 - Python: 3.6.10
 - SQLAlchemy: 1.3.19
 - Database: Exasol
 - DBAPI: pyodbc==4.0.30

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there-

if you folks are actually developing the dialect, then you would need to mark these tests as unsupported if the pyodbc driver can't support this.   

As this test doesn't have a requires right now you likely need to add a stub QuotedNameArgumentTest that is a no-op, per the guidelines at https://github.com/sqlalchemy/sqlalchemy/blob/master/README.dialects.rst :

```
# test/test_suite.py

from sqlalchemy.testing.suite import *

class QuotedNameArgumentTest(object):
    "skip this suite"

```

if you can provide some background on exasol's capabilities we can add new requirements such as "symbol_names_with_single_quote" or "symbol_names_with_spaces" which you could mark as unsupported.

the suite was added as part of #5456 if you want to look at what's happening there.

**Comment by nndo1991** [comment]
Thank you, I did that to bypass that suite
