### ISSUE TITLE
StatementError is raised when connection is None

### ISSUE THREAD

**Issue by gospodima** [sqlalchemy/sqlalchemy#5565]
During the `session.query` call I got `sqlalchemy.exc.StatementError` when connection object is None and sqlalchemy is trying to get cursor from this connection.
I suppose, that this is caused by lost connection, so the question is, whether `StatementError` should be raised here? 
In this case it seems to me difficult to distinguish between an error in my query and a connection problem. 

Stack trace:
```
[2020-09-03 00:02:30,014] CRITICAL | __main__: (builtins.AttributeError) 'NoneType' object has no attribute 'cursor'
[SQL: <my SELECT statement>]
[parameters: [immutabledict({})]]
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 1211, in _execute_context
  File "sqlalchemy\engine\default.py", line 803, in _init_compiled
  File "sqlalchemy\engine\default.py", line 1159, in create_cursor
  File "sqlalchemy\pool\base.py", line 1000, in cursor
AttributeError: 'NoneType' object has no attribute 'cursor'

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  <my external stack trace>
  File "sqlalchemy\orm\query.py", line 3436, in one
  File "sqlalchemy\orm\query.py", line 3405, in one_or_none
  File "sqlalchemy\orm\query.py", line 3481, in __iter__
  File "sqlalchemy\orm\query.py", line 3506, in _execute_and_instances
  File "sqlalchemy\engine\base.py", line 1020, in execute
  File "sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "sqlalchemy\engine\base.py", line 1133, in _execute_clauseelement
  File "sqlalchemy\engine\base.py", line 1213, in _execute_context
  File "sqlalchemy\engine\base.py", line 1517, in _handle_dbapi_exception
  File "sqlalchemy\util\compat.py", line 178, in raise_
  File "sqlalchemy\engine\base.py", line 1211, in _execute_context
  File "sqlalchemy\engine\default.py", line 803, in _init_compiled
  File "sqlalchemy\engine\default.py", line 1159, in create_cursor
  File "sqlalchemy\pool\base.py", line 1000, in cursor
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'NoneType' object has no attribute 'cursor'
[SQL: <my SELECT statement>]
[parameters: [immutabledict({})]]
```

**Versions**
 - OS: Windows 10
 - Python: 3.8.1
 - SQLAlchemy: 1.3.17
 - Database: postgres (version 10)
 - DBAPI: psycopg2==2.8.5

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

might be nice for a nicer error raised but i have no idea how you are getting that result.  The "connection is None" is not a state I am familiar with.  if the database had a connectivity issue, that doesn't mean you get "None" for a connection in the Session, a connectivity error would be raised much sooner than that.

so can you please provide the details requested in [the issue template](https://github.com/sqlalchemy/sqlalchemy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), with special emphasis providing a [reproduction case](http://stackoverflow.com/help/mcve), thanks!

**Comment by gospodima** [comment]
Hi @zzzeek,
I couldn't find the way to reproduce this behabiour. So I will close issue and let you know in case I will find steps to reproduce such state. 
Thanks and sorry for the distraction!
