### ISSUE TITLE
About the MySQL Server has gone away exception.

### ISSUE THREAD

**Issue by weijiang1994** [sqlalchemy/sqlalchemy#5566]
**MySQL Server has gone away**

**Versions**
 - OS: Ubuntu 16.04
 - Python: 3.6
 - SQLAlchemy: 1.4
 - Database: MySQL
 - DBAPI: pymysql

**code**
```python3
_engine = create_engine('mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.
                        format(DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_DATABASE), pool_recycle=60, max_overflow=5,
                        pool_size=10)
_session = sessionmaker(bind=_engine)
_session = _session()
```
I added the `pool_recycle`=60 keyword parameter when I create the connect engine, and I look up mysql database parameter the `wait_time`=28800 second.But the exception not gone away.

What can I do to solve this problem?
PLEASE~
THANKS~
**Have a nice day!**

**Comment by zzzeek** [comment]
"server has gone away" can be almost anything, it often happens when the connection is put into a bad state by error conditions not being handled correctly.   need complete stack trace and information on under what conditions cause it to happen.   addtionally, pool_recycle only takes place when connections are checked out from the pool, so if your application is holding a connection outside of the pool and sleeping, that can also cause timeouts.

**Comment by weijiang1994** [comment]
> "server has gone away" can be almost anything, it often happens when the connection is put into a bad state by error conditions not being handled correctly. need complete stack trace and information on under what conditions cause it to happen. addtionally, pool_recycle only takes place when connections are checked out from the pool, so if your application is holding a connection outside of the pool and sleeping, that can also cause timeouts.

2020-09-09 09:32:49,564 - app - ERROR - Exception on /blogBriefInfo/0 [POST]
Traceback (most recent call last):
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 705, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 710, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/blog/flask-blog-owner/app/blueprint/index_bp.py", line 31, in get_blog_brief_info
    total = db.query_all(Article)
  File "/home/ubuntu/blog/flask-blog-owner/app/model/db_operate.py", line 36, in query_all
    return self.session.query(obj).all()
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/home/ubuntu/blog/flask-blog-owner/venv/lib/python3.5/site-packages/pymysql/connections.py", line 710, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: SELECT article.id AS article_id, article.title AS article_title, article.type AS article_type, article.img AS article_img, article.brief_content AS article_brief_content, article.content AS article_content, article.is_private AS article_is_private, article.create_time AS article_create_time, article.update_time AS article_update_time, article.read_times AS article_read_times, article.delete_flag AS article_delete_flag 
FROM article]

**Comment by zzzeek** [comment]
possibilities:

1. the network is unreliable

2. the server is crashing or otherwise being shut down

3. the database connection is in an undefined state from a previous operation, such as an error that was raised, or a rollback, etc.

4. the client process is hung and is not able to talk to the server in a timely manner.   this can happen if you are using event-based programming such as gevent and the program is too CPU bound.

you'll want to look in your MySQL server logs for anything unusual.

**Comment by weijiang1994** [comment]
> possibilities:
> 
> 1. the network is unreliable
> 2. the server is crashing or otherwise being shut down
> 3. the database connection is in an undefined state from a previous operation, such as an error that was raised, or a transaction that was corrupted and not rolled back, etc.
> 4. the client process is hung and is not able to talk to the server in a timely manner.   this can happen if you are using event-based programming such as gevent and the program is too CPU bound.
> 
> you'll want to look in your MySQL server logs for anything unusual.

thanks for your reply, I will try these solution.

**Comment by zzzeek** [comment]
reopen if you need more help.
