### ISSUE TITLE
Unable to migrate: mysql: DefaultClause doesn't have a dispatcher

### ISSUE THREAD

**Issue by smurfix** [sqlalchemy/sqlalchemy#5574]
**Describe the bug**

I get a traceback when trying to migrate a table via Alembic. The crash is caused by a missing attribute of `DefaultClause` which is why I'm reporting it here instead of in the Alembic tracker.

**Expected behavior**
The clause gets compiled and the migration step succeeds, of course.

**To Reproduce**

```py
# Insert code here
from sqlalchemy import Column
from sqlalchemy import Float
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

#url = "sqlite:////tmp/sqlite.db"  ## different error
url = "mysql://test:test@localhost/test"

# first let's create the old table

BasePrep = declarative_base()
class TestPrep(BasePrep):
    __tablename__ = "test123"
    id = Column(Integer, primary_key=True)
    label_x = Column(Float, nullable=False, server_default="0")
    label_y = Column(Float, nullable=False, server_default="0")
enginePrep = create_engine(url)
BasePrep.metadata.create_all(enginePrep)

# this is the new one

Base = declarative_base()
class Test(Base):
    __tablename__ = "test123"
    id = Column(Integer, primary_key=True)
    label_x = Column(Float, default=0)  # dies
    label_y = Column(Float, nullable=True)  # also dies

# now try to migrate this

from alembic.runtime.migration import MigrationContext
from alembic.autogenerate import api
from alembic.operations.base import Operations

engine = create_engine(url)

session = Session(engine)
ctx = MigrationContext(dialect=session.bind.dialect, connection=session.connection(), opts={})
res = api.produce_migrations(ctx,Test.__table__.metadata)
ops = Operations(ctx, ctx.impl)

# If there's an Alembic method to do this without looping, I haven't found it.
def all_ops(op):
    if hasattr(op,"ops"):
        for o in op.ops:
            yield from all_ops(o)
    else:
        yield op
for op in all_ops(res.upgrade_ops):
    print(type(op),vars(op))
    ops.invoke(op)
```

**Error**

```
Traceback (most recent call last):
  File "repro.py", line 50, in <module>
    ops.invoke(op)
  File "/home/smurf/src/alembic/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/home/smurf/src/alembic/alembic/operations/toimpl.py", line 43, in alter_column
    operations.impl.alter_column(
  File "/home/smurf/src/alembic/alembic/ddl/mysql.py", line 80, in alter_column
    self._exec(
  File "/home/smurf/src/alembic/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1112, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1199, in _execute_ddl
    compiled = ddl.compile(
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 479, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 508, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/ext/compiler.py", line 441, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/ext/compiler.py", line 495, in __call__
    expr = fn(element, compiler, **kw)
  File "/home/smurf/src/alembic/alembic/ddl/mysql.py", line 317, in _mysql_modify_column
    _mysql_colspec(
  File "/home/smurf/src/alembic/alembic/ddl/mysql.py", line 362, in _mysql_colspec
    spec += " DEFAULT %s" % _render_value(compiler, server_default)
  File "/home/smurf/src/alembic/alembic/ddl/mysql.py", line 349, in _render_value
    return compiler.sql_compiler.process(expr)
  File "/home/smurf/src/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 508, in process
    return obj._compiler_dispatch(self, **kwargs)
AttributeError: 'DefaultClause' object has no attribute '_compiler_dispatch'

```

**Versions.**
 - OS: Linux 5.whatever, Debian current
 - Python: 3.8
 - SQLAlchemy: master, ditto Alembic
 - Database: mariadb
 - DBAPI: ./.

**Comment by smurfix** [comment]
edited: updated the traceback w/ sqlalchemy+alembic master instead of system packages

**Comment by zzzeek** [comment]
hi there -

sorry, this is an alembic issue.  have not reproduced yet.    ill reopen.

**Comment by zzzeek** [comment]
please refer to https://github.com/sqlalchemy/alembic/issues/736
