### ISSUE TITLE
Cannot filter NULL JSON values on PostgreSQL

### ISSUE THREAD

**Issue by raphj** [sqlalchemy/sqlalchemy#5575]
**Describe the bug**

`query.filter(jsonField == JSON.NULL)` fails on PostgreSQL (9.6 and 12.4). It succeeds with MariaDB and SQLite.

**Expected behavior**
This should work on PostgreSQL: it should behave like it behaves with a MariaDB or a SQLite database.

The minimal example given below prints this when using SQLite: 

```
[(1, None)]
```

**To Reproduce**

See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

```py
from sqlalchemy import Column, Integer, Text, MetaData, Table, JSON, select, create_engine
from sqlalchemy.orm import sessionmaker

engine = create_engine('postgresql://user:pass@localhost/testdb?client_encoding=utf8')
#engine = create_engine("sqlite://")

Session = sessionmaker(bind=engine)
session = Session()

test_json = Table(
    'test_json', MetaData(),
    Column('id', Integer, primary_key=True),
    Column('fields', JSON),
)

#if not engine.has_table(test_json):
test_json.create(bind=engine)

engine.execute(test_json.insert().values(fields=None))

print(session.query(test_json).filter(test_json.c.fields == JSON.NULL).all())
```

**Error**

```
Traceback (most recent call last):
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: json = unknown
LINE 3: WHERE test_json.fields = 'null'
                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jsonnulsqlalchemy.py", line 21, in <module>
    print(session.query(test_json).filter(test_json.c.fields == JSON.NULL).all())
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/raphael/dl/tracim/backend/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: json = unknown
LINE 3: WHERE test_json.fields = 'null'
                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT test_json.id AS test_json_id, test_json.fields AS test_json_fields 
FROM test_json 
WHERE test_json.fields = %(fields_1)s]
[parameters: {'fields_1': 'null'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: Debian Buster
 - Python: 3.7
 - SQLAlchemy: 1.3.19
 - Database: pg 9.6, 12.4
 - DBAPI: psycopg2 2.8.6

**Comment by gordthompson** [comment]
I was able to reproduce the issue. I also noted that using `is_()` fails, too:

``` python
print(session.query(test_json).filter(test_json.c.fields.is_(JSON.NULL)).all())
```

produces 

``` text
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "'null'"
LINE 3: WHERE test_json.fields IS 'null'
                                  ^

[SQL: SELECT test_json.id AS test_json_id, test_json.fields AS test_json_fields 
FROM test_json 
WHERE test_json.fields IS %(fields_1)s]
[parameters: {'fields_1': 'null'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by zzzeek** [comment]
the postgresql database does not support a direct JSON->JSON comparison.   you need to cast to string:

```
print(
    session.query(test_json)
    .filter(
        cast(test_json.c.fields, String) == cast(literal(None, JSON()), String)
    )
    .all()
)

```

**Comment by zzzeek** [comment]
it can work this way also:

```
print(
    session.query(test_json)
    .filter(
        cast(test_json.c.fields, String) == cast(literal(JSON.NULL, JSON()), String)
    )
    .all()
)

```

there's really no other way this can be done using the JSON.NULL construct.  Postgresql does not suppport json== json, im sure they have an amazing reason but it's IMO a bug on their end:

```
test=> select cast('{"x": 5}' AS JSON);
   json   
----------
 {"x": 5}
(1 row)

test=> select cast('{"x": 5}' AS JSON) = cast('{"x": 5}' AS JSON);
ERROR:  operator does not exist: json = json
LINE 1: select cast('{"x": 5}' AS JSON) = cast('{"x": 5}' AS JSON);
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
test=> select cast(cast('{"x": 5}' AS JSON) AS VARCHAR) = cast(cast('{"x": 5}' AS JSON) AS VARCHAR);
 ?column? 
----------
 t
(1 row)

```

**Comment by gordthompson** [comment]
Aha. So if we explicitly assign `None` to the column it is saved as JSON `null`, but if we just ignore it then the row contains an SQL NULL.

``` python
from sqlalchemy import (
    Column,
    Integer,
    MetaData,
    Table,
    JSON,
    create_engine,
    text,
)
from sqlalchemy.orm import sessionmaker

engine = create_engine(
    "postgresql://scott:tiger@192.168.0.199/sqla_test?client_encoding=utf8",
    echo=True,
)

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS test_json"))

Session = sessionmaker(bind=engine)
session = Session()

test_json = Table(
    "test_json",
    MetaData(),
    Column("id", Integer, primary_key=True, autoincrement=False),
    Column("fields", JSON),
)

test_json.create(bind=engine)

engine.execute(test_json.insert().values(dict(id=1,)))

print(session.query(test_json).filter(test_json.c.fields.is_(None)).all())
# [(1, None)]
```

Weird.

**Comment by zzzeek** [comment]
this is configurable.   it's not simple because there's no way for it to be simple, but here it is:  https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.JSON.params.none_as_null

**Comment by zzzeek** [comment]
direct compare of json->json is unfortunately a little tricky as PG doesn't want to allow this without casting to string.
