### ISSUE TITLE
MSSQL TCP error 0x68 (104) leads to InvalidRequestError and 500 till server or application is restarted

### ISSUE THREAD

**Issue by zacqed** [sqlalchemy/sqlalchemy#5629]
We are running an Flask application (based on flask_appbuilder) in production with mssql as the database backend. It would seem that the mssql backend is a bit unstable and leads to TCP errors such as 

Error | What it means
-- | --
1.        Error [Microsoft][ODBC Driver 17 for SQL Server]TCP   Provider: Error code 0x68 (104) (SQLExecDirectW)' | 104      /* Connection reset by peer */
2.        ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL   Server]TCP Provider: Error code 0x274C (10060) (SQLExecDirectW)') | 0x274c   10060 WSAETIMEDOUT       A   connection attempt failed because the connected party did not properly   respond after a period of time, or established connection failed because   connected host has failed to respond.

Due to back-ends instability, the CRUD application on the application continue to fail with following traceback:

```
2020-10-04 17:41:59,743:INFO:sqlalchemy.engine.base.Engine:('4',)
2020-10-04 17:41:59,744:INFO:sqlalchemy.pool.impl.QueuePool:Invalidate connection <pyodbc.Connection object at 0x7f3c8abe3110> (reason: OperationalError:('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)'))
2020-10-04 17:41:59,744:DEBUG:sqlalchemy.pool.impl.QueuePool:Closing connection <pyodbc.Connection object at 0x7f3c8abe3110>
2020-10-04 17:41:59,744:ERROR:app:Exception on /eclscenario/edit/6 [POST]
Traceback (most recent call last):
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venvlib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/venvlib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venvlib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venvlib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/venvlib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venvlib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venvlib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/mnt/c/users/harshitgupta/source/repos2/MyAPP/MyAPP/app/views.py", line 34547, in edit
    widgets = self._edit_MyAPP(pk)
  File "/mnt/c/users/harshitgupta/source/repos2/MyAPP/MyAPP/app/views.py", line 34581, in _edit_MyAPP
    form = self.edit_form.refresh(request.form)
  File "/venvlib/python3.8/site-packages/flask_appbuilder/forms.py", line 329, in refresh
    form = self(obj=obj)
  File "/venvlib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/venvlib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/venvlib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/venvlib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/venvlib/python3.8/site-packages/wtforms/fields/core.py", line 310, in process
    self.process_formdata(self.raw_data)
  File "/venvlib/python3.8/site-packages/flask_appbuilder/fields.py", line 76, in process_formdata
    self.data = self.datamodel.get(valuelist[0])
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/venvlib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/venvlib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/venvlib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/venvlib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')
[SQL: SELECT [Master_Entity_Master].created_on AS [Master_Entity_Master_created_on], [Master_Entity_Master].changed_on AS [Master_Entity_Master_changed_on], [Master_Entity_Master].id AS [Master_Entity_Master_id], [Master_Entity_Master].from_date AS [Master_Entity_Master_from_date], [Master_Entity_Master].entity_name AS [Master_Entity_Master_entity_name], [Master_Entity_Master].entity_code AS [Master_Entity_Master_entity_code], [Master_Entity_Master].dimension_type_code AS [Master_Entity_Master_dimension_type_code], [Master_Entity_Master].parent_code AS [Master_Entity_Master_parent_code], [Master_Entity_Master].import_source AS [Master_Entity_Master_import_source], [Master_Entity_Master].created_by_fk AS [Master_Entity_Master_created_by_fk], [Master_Entity_Master].changed_by_fk AS [Master_Entity_Master_changed_by_fk]
FROM [Master_Entity_Master]
WHERE [Master_Entity_Master].id = ?]
[parameters: ('4',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-10-04 17:41:59,771:ERROR:app:Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2020-10-04 17:41:59,775:DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f3c582282d0> being returned to pool
2020-10-04 17:41:59,780:DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f3c582282d0> rollback-on-return, via agent
2020-10-04 17:41:59,780:INFO:sqlalchemy.engine.base.Engine:ROLLBACK

RETRY:

2020-10-04 17:44:02,753:ERROR:app:Exception on /eclscenario/edit/6 [POST]
Traceback (most recent call last):
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1202, in _execute_context
    conn = self._revalidate_connection()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 469, in _revalidate_connection
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/venvMyAPP/MyAPP/app/views.py", line 34547, in edit
    widgets = self._edit_MyAPP(pk)
  File "/venvMyAPP/MyAPP/app/views.py", line 34581, in _edit_MyAPP
    form = self.edit_form.refresh(request.form)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask_appbuilder/forms.py", line 329, in refresh
    form = self(obj=obj)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/wtforms/fields/core.py", line 310, in process
    self.process_formdata(self.raw_data)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/flask_appbuilder/fields.py", line 76, in process_formdata
    self.data = self.datamodel.get(valuelist[0])
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1206, in _execute_context
    self._handle_dbapi_exception(
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1202, in _execute_context
    conn = self._revalidate_connection()
  File "/venvMyAPP/MyAPP/kvenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 469, in _revalidate_connection
    raise exc.InvalidRequestError(
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
[SQL: SELECT [Master_Entity_Master].created_on AS [Master_Entity_Master_created_on], [Master_Entity_Master].changed_on AS [Master_Entity_Master_changed_on], [Master_Entity_Master].id AS [Master_Entity_Master_id], [Master_Entity_Master].from_date AS [Master_Entity_Master_from_date], [Master_Entity_Master].entity_name AS [Master_Entity_Master_entity_name], [Master_Entity_Master].entity_code AS [Master_Entity_Master_entity_code], [Master_Entity_Master].dimension_type_code AS [Master_Entity_Master_dimension_type_code], [Master_Entity_Master].parent_code AS [Master_Entity_Master_parent_code], [Master_Entity_Master].import_source AS [Master_Entity_Master_import_source], [Master_Entity_Master].created_by_fk AS [Master_Entity_Master_created_by_fk], [Master_Entity_Master].changed_by_fk AS [Master_Entity_Master_changed_by_fk]
FROM [Master_Entity_Master]
WHERE [Master_Entity_Master].id = ?]
[parameters: [{'%(139897350575440 param)s': '4'}]]
```

From my reading of SQLAlchemy and flask_sqlalchemy documentation, i should implement methods provided under "Dealing with Disconnects" to be able to circumvent such errors (while i agreed database server is the culprit). Having tried such methods, i am unable to find a way w/o having to restart the application (i.e. re-create the connection again.) Any guidance on how to handle it

```
SQLALCHEMY_ENGINE_OPTIONS = {
    "pool_size": 10,
    "pool_recycle": 120,
    "pool_pre_ping": True,
}
```

**Comment by zzzeek** [comment]
hi there -

the application recovers assuming you are rolling back the transaction that's failed.  

there's no reproducing code here so I can only comment on the error shown: 

"Can't reconnect until invalid transaction is rolled back"

this means the session (and the underlying Connection's transaction) isn't being rolled back when an error occurs, and then an attempt is made to continue using it.

It's not clear how this would happen without a reproducing example.  it looks like perhaps flask's error handlers are themselves attempting to access the database which wouldn't work, I see "  rv = self.handle_user_exception(e)" and then later down is where the database is attempting to be accessed, in flask_appbuilder and such.     It seems this might be a common issue where a web framework attempts to render a page within an error handler that itself tries to use the database that's in a failed state, so this would be an issue in the integration.

the "08S01" error itself is detected by the MSSQL dialect as requiring a connection invalidate and in the stack traces above we see this is happening correctly.   I don't see an example of the other SQL server error "Error code 0x68" in the above trace, I don't see that we have a detector for that string explicitly but would need to see one in context.

but in any case, the above traces show something not being handled on the flask side, when an error occurs, there has to be no DB access whatsoever until the transaction is rolled back. 

overall this is some kind of issue in flask_appbuilder and/or flask or related components.

**Comment by zzzeek** [comment]
please reopen if you need to provide further detail.

**Comment by erfannariman** [comment]
We have this exact same issue @zacqed were you able to find a solution?

**Comment by zzzeek** [comment]
i notice in their logs, after the SQL Server error and before the issue where the transaction wasn't restarted, is this message all by itself:

```
RETRY:
```

what's that?  is that some kind of retry feature in Flask?  that would be where the problem is, it needs to roll back the previous transaction.

**Comment by erfannariman** [comment]
> i notice in their logs, after the SQL Server error and before the issue where the transaction wasn't restarted, is this message all by itself:
> 
> ```
> RETRY:
> ```
> 
> what's that? is that some kind of retry feature in Flask? that would be where the problem is, it needs to roll back the previous transaction.

Not 100% sure since I found it hard to reproduce it locally. But I think the error happens here:

```python
user = User.query.filter_by(email=request.form.get("email")).first()
password = request.form.get("password")
```

`User` is a sqlalchemy db model.

**Comment by eskildht** [comment]
I'm also experiencing the `0x68` error having set `pool_pre_ping=True`:

```
DEBUG:sqlalchemy.pool.impl.QueuePool:Pool pre-ping on connection <pyodbc.Connection object at 0x7f8e66cdf020>
DEBUG:sqlalchemy.pool.impl.QueuePool:Pool pre-ping on connection <pyodbc.Connection object at 0x7f8e66cdf020> failed, will invalidate pool
INFO:sqlalchemy.pool.impl.QueuePool:Disconnection detected on checkout, invalidating all pooled connections prior to current timestamp (reason: InvalidatePoolError())
INFO:sqlalchemy.pool.impl.QueuePool:Invalidate connection <pyodbc.Connection object at 0x7f8e66cdf020> (reason: InvalidatePoolError:())
DEBUG:sqlalchemy.pool.impl.QueuePool:Hard-closing connection <pyodbc.Connection object at 0x7f8e66cdf020>
INFO:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f8e6504da30> invalidated due to pool invalidation; recycling
DEBUG:sqlalchemy.pool.impl.QueuePool:Hard-closing connection <pyodbc.Connection object at 0x7f8e6504da30>
DEBUG:sqlalchemy.pool.impl.QueuePool:Created new connection <pyodbc.Connection object at 0x7f8e6504da30>
DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f8e6504da30> checked out from pool
DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f8e6504da30> is fresh, skipping pre-ping
INFO:sqlalchemy.pool.impl.QueuePool:Invalidate connection <pyodbc.Connection object at 0x7f8e6504da30> (reason: OperationalError:('08S01', '[08S01] [Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)'))
DEBUG:sqlalchemy.pool.impl.QueuePool:Hard-closing connection <pyodbc.Connection object at 0x7f8e6504da30>
[2024-07-09 05:27:23 +0000] [10] [ERROR] Error in ASGI Framework
```

I don't quite get what adjustments I should make. Here `0x7f8e6504da30` is invalidated, a new connection is created, but it immediately suffers `OperationalError` (Connection reset by peer). This is after connection(s) have not been used for 2 hours. It's an Azure SQL database. Any help would be appreciated.
