### ISSUE TITLE
Query fails with "no such column" when sort by Many-to-Many count and eager load Many-to-One relationship. 

### ISSUE THREAD

**Issue by stepan-anokhin** [sqlalchemy/sqlalchemy#5637]
**Describe the bug**
I have the following declarative chema : 

* There are two main entity types: Parent and Child. 
* There is a Many-to-Many relationship between parents, implemented as association object (Link) with additional attributes (distance).
* There is a Many-to-One relationship from children to parents. 

See full [schema.py](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e#file-schema-py). 

I want to sort parents by count of "short" outgoing links (distance < threshold) and prefetch associated children with `joinedload`. 

When I don't use `joinedload` to prefetch children, the query (see the [first_query](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e#file-reproduce-py-L16)) works as expected and produces correct SQL request (see the [first_query.sql](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e#file-first_query-sql)). 

When I add `options(joinedload(Parent.children))` (see the [second_query](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e#file-reproduce-py-L27)) it produces invalid SQL request with extra `link_count` column (see the [second_query.sql](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e#file-second_query-sql-L11)) and fails with `no such column: link_count` error.

**Expected behavior**
The query should work with eager loading strategy as well.  

**To Reproduce**
Use files from the [gist](https://gist.github.com/stepan-anokhin/5159122305cd6b2dc63fd489725e7d3e) or just run the following script (the same code as a single file):

```py
from sqlalchemy import Column, Integer, Float, ForeignKey, String
from sqlalchemy import create_engine, func, literal_column
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import sessionmaker, joinedload

Base = declarative_base()


class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    children = relationship("Child")


class Link(Base):
    """Association object with extra fields implementing Many-to-Many relationship between parents."""

    __tablename__ = 'links'
    source_id = Column(Integer, ForeignKey('parent.id'), primary_key=True)
    target_id = Column(Integer, ForeignKey('parent.id'), primary_key=True)
    distance = Column(Float, nullable=False)


class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'), nullable=False)
    value = Column(Integer)


engine = create_engine('sqlite://')
Session = sessionmaker(bind=engine)

if __name__ == '__main__':
    # Create schema
    Base.metadata.create_all(bind=engine)
    session = Session()

    on_short_link = (Link.source_id == Parent.id) & (Link.distance <= 0.8)

    first_query = session. \
        query(Parent, func.count(Link.source_id).label("link_count")). \
        outerjoin(Link, on_short_link). \
        group_by(Parent.id). \
        order_by(literal_column("link_count").desc()). \
        limit(20).offset(0)

    print([(file.name, count) for file, count in first_query.all()])

    second_query = session. \
        query(Parent, func.count(Link.source_id).label("link_count")). \
        options(joinedload(Parent.children)). \
        outerjoin(Link, on_short_link). \
        group_by(Parent.id). \
        order_by(literal_column("link_count").desc()). \
        limit(20).offset(0)

    print([(file.name, count) for file, count in second_query.all()])
```
The `first_query` works as expected. The `second_query` fails with `no such column: link_count` error.

**Error**

```
[]
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Select at 0x7f37381a5a60; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381b20a0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Alias at 0x7f37381a55e0; %(139875141178848 anon)s> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381a08e0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Select at 0x7f37381a5640; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381a0ee0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Alias at 0x7f37381a5370; %(139875141178224 anon)s> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381a0cd0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Select at 0x7f373818fa00; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f373818fbe0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Alias at 0x7f37381a04f0; %(139875141158128 anon)s> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f373818f940; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Select at 0x7f3738206c40; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381989a0; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Alias at 0x7f373818f790; %(139875141089168 anon)s> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f3738198160; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Select at 0x7f37381a0d60; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381a5d30; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py:559: SAWarning: Column 'link_count' on table <sqlalchemy.sql.selectable.Alias at 0x7f37381a03a0; %(139875141157792 anon)s> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7f37381a5100; link_count>, which has the same key.  Consider use_labels for select() statements.
  util.warn(
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: link_count

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/stepan/PycharmProjects/sql-alchemy-report/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: link_count
[SQL: SELECT anon_1.parent_id AS anon_1_parent_id, anon_1.parent_name AS anon_1_parent_name, anon_1.link_count, child_1.id AS child_1_id, child_1.parent_id AS child_1_parent_id, child_1.value AS child_1_value 
FROM (SELECT parent.id AS parent_id, parent.name AS parent_name, count(links.source_id) AS link_count, link_count 
FROM parent LEFT OUTER JOIN links ON links.source_id = parent.id AND links.distance <= ? GROUP BY parent.id ORDER BY link_count DESC
 LIMIT ? OFFSET ?) AS anon_1 LEFT OUTER JOIN child AS child_1 ON anon_1.parent_id = child_1.parent_id ORDER BY anon_1.link_count DESC]
[parameters: (0.8, 20, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
python-BaseException

```

**Versions.**
 - OS: Ubuntu 16.04.2 LTS
 - Python: 3.8.3
 - SQLAlchemy: 1.3.19
 - Database: tested with in-memory SQLite and PostgreSQL 12.4
 - DBAPI:

**Comment by zzzeek** [comment]
hi there -

there's a lot going on in these queries that makes me nervous, such as loading whole entities when you also have a group_by primary key, but overall the issue here is simple which is that when you use literal_column() you are hardcoding a particular symbol name into your query and preventing it from being compatible with the aliasing that's necessarily applied by joinedload().

fortunately there's an appropriate API to use for this case when you want to ORDER BY a label name.   it is documented but it needs to be noted nearer to the order_by() docs which will be improved soon so it's not surprising you didn't find it, it is at https://docs.sqlalchemy.org/en/13/core/tutorial.html#ordering-or-grouping-by-a-label .

in this case this allows the label to be aliased correctly:

```
    from sqlalchemy import desc
    second_query = (
        session.query(Parent, func.count(Link.source_id).label("link_count"))
        .options(joinedload(Parent.children))
        .outerjoin(Link, on_short_link)
        .group_by(Parent.id)
        .order_by(desc("link_count"))
        .limit(20)
        .offset(0)
    )

```

the query is:
```

SELECT anon_1.parent_id AS anon_1_parent_id, anon_1.parent_name AS anon_1_parent_name, anon_1.link_count AS anon_1_link_count, child_1.id AS child_1_id, child_1.parent_id AS child_1_parent_id, child_1.value AS child_1_value 
FROM (SELECT parent.id AS parent_id, parent.name AS parent_name, count(links.source_id) AS link_count 
FROM parent LEFT OUTER JOIN links ON links.source_id = parent.id AND links.distance <= ? GROUP BY parent.id ORDER BY link_count DESC
 LIMIT ? OFFSET ?) AS anon_1 LEFT OUTER JOIN child AS child_1 ON anon_1.parent_id = child_1.parent_id ORDER BY anon_1.link_count DESC
```

**Comment by stepan-anokhin** [comment]
Hi @zzzeek,
`desc("link_count")` works perfect! Thanks a lot! You may close the issue. :)

One final question if you don't mind. What is bad about loading entire entity while using group_by and is there a better approach? I know the requirement to sort by count of links with `distance<threshold` is rather fancy, but it is dictated by the problem domain.

**Comment by zzzeek** [comment]
I'm always nervous when GROUP BY is used in conjunction with non-aggregated columns that are not in the GROUP BY, in the example query here we see parent.name is that column.   Historically, this would be abused on databases such as MySQL that did not correctly prevent a query that would lose rows by doing so.   However, the query is valid because you're grouping by primary key and there is no problem.

some discussion about this idea is here: https://dba.stackexchange.com/questions/158015/why-can-i-select-all-fields-when-grouping-by-primary-key-but-not-when-grouping-b

**Comment by stepan-anokhin** [comment]
@zzzeek ok, got it. :) Thanks!
