### ISSUE TITLE
Another exception raised during fetch interruption

### ISSUE THREAD

**Issue by sizmailov** [sqlalchemy/sqlalchemy#5642]
**Describe the bug**

`During handling of the above exception, another exception occurred` happens on `KeyboardInterrupt` during fetch

**Expected behavior**

No nested throw

**To Reproduce**

Query large amount of rows and hit `Ctrl+C`

```py
q = session.query(MyTable.id).yield_per(1024)
for table_id in q:
    pass 
```

**Error**

```
Traceback (most recent call last):
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1093, in fetchmany
    buf.extend(dbapi_cursor.fetchmany(size - lb))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 379, in iterrows
    for row in self._fetchiter_impl():
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 105, in chunks
    fetch = cursor.fetchmany(yield_per)
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1011, in fetchmany
    return self._manyrow_getter(self, size)
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 536, in manyrows
    rows = self._fetchmany_impl(num)
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1740, in _fetchmany_impl
    return self.cursor_strategy.fetchmany(self, self.cursor, size)
  File "<private>/venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1095, in fetchmany
    self.handle_exception(result, e)
TypeError: handle_exception() missing 1 required positional argument: 'err'

```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.2
 - SQLAlchemy: 1.4.0b1.dev0
 - Database: 
 - DBAPI: postgresql+psycopg2

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure all cursor self.handle_exception() calls are covered** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2298

**Comment by zzzeek** [comment]
thanks for testing 1.4.
