### ISSUE TITLE
MS SQL restart not recognized

### ISSUE THREAD

**Issue by frip** [sqlalchemy/sqlalchemy#5646]
**Describe the bug**
The mssql-pyodbc dialect fails to recognize a restart of the MS SQL server. (It doesn't expect the current (?) error-code `"01000"`.)

**Expected behavior**
The result of a restart should be understood as an `is_disconnect`-error, e.g. to trigger a reconnect.

**To Reproduce**
I can reproduce the problem with a local MS SQL Express installation, but what got me searching was a remote MS SQL server.

The example below stops after a successful query to await an input from the user after the DB-restart. After that the next query fails.

```py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

MY_DATABASE_NAME = 'your_db_name'

engine = create_engine('mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BSQL+Server%7D%3BSERVER%3D'
                       f'localhost%5CSQLEXPRESS%3BDATABASE%3D{MY_DATABASE_NAME}',
                       pool_pre_ping=True)
session = sessionmaker(bind=engine)()
session.execute('SELECT 1')  # this proves that everything was working OK
input('restart done?')
session.execute('SELECT 1')  # this triggers an exception if the DB was restarted
```

**Error**

```
restart done?
Traceback (most recent call last):
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('01000', '[01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionWrite (WrapperWrite()). (233) (SQLExecDirectW); [01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]Allgemeiner Netzwerkfehler. Weitere Informationen finden Sie in der Dokumentation über Netzwerke. (11)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/sqlalchemy_bug/main.py", line 12, in <module>
    session.execute('SELECT 1')
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1291, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('01000', '[01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionWrite (WrapperWrite()). (233) (SQLExecDirectW); [01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]Allgemeiner Netzwerkfehler. Weitere Informationen finden Sie in der Dokumentation über Netzwerke. (11)')
[SQL: SELECT 1]
(Background on this error at: http://sqlalche.me/e/13/dbapi)
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\xxx\PycharmProjects\sqlalchemy_bug\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC SQL Server Driver]Kommunikationsverbindungsfehler (0) (SQLEndTran)')
```

**Versions.**
 - OS: Windows 10 (German)
 - Python: seen with 3.8 and 3.6
 - SQLAlchemy: 1.3.20
 - Database: SQLEXPRESS (SQL Server 15.0.2000)
 - DBAPI: pyodbc version 4.0.30

**Additional context**
I have the following workaround:

```py
from sqlalchemy.dialects import registry

registry.register("mssql.pyodbc", "pyodbc_dialect", "MyMSDialectPyodbc")
```

with `pyodbc_dialect.py`:

```py
from sqlalchemy.dialects.mssql.pyodbc import MSDialect_pyodbc


class MyMSDialectPyodbc(MSDialect_pyodbc):
    def is_disconnect(self, e, connection, cursor):
        if isinstance(e, self.dbapi.Error):
            code = e.args[0]
            if code in (
                "01000",
            ):
                return True
        return super(MyMSDialectPyodbc, self).is_disconnect(
            e, connection, cursor
        )
```

...but I'd prefer not to need it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add SQL Server 01000 disconnect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2305

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add SQL Server 01000 disconnect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2306

**Comment by frip** [comment]
Thank you very much for the speedy fix and the improved workaround!

I think the second issue is due to my imperfect example-code: I am using the pool_pre_ping in my real code, in the context of Flask-SQLAlchemy, web-endpoints, etc. The example would be better and clearer without it!

In any case I am very impressed by your fast and accurate response!!
...and I'm looking forward to the next release of SQLAlchemy! :-)

**Comment by frip** [comment]
Sorry, I have a question regarding the `@event.listens_for(Engine, "handle_error")`-solution: If I try to use it with pool_pre_ping it catches an error on my query (when it is too late), not on the pre-ping.

Is that to be expected - am I using it wrong? Or is the problem somewhere "deeper in my stack"? (e.g. a connection being used without a ping because of Flask-SQLAlchemy or the way my flask is served...)

**Comment by zzzeek** [comment]
in fact you are absolutely correct, I forgot that the "ping" here fails to be part of that process.

so yes you need a patch for the immediate term:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/pyodbc.py b/lib/sqlalchemy/dialects/mssql/pyodbc.py
index 22e20c14c..cdaf08d08 100644
--- a/lib/sqlalchemy/dialects/mssql/pyodbc.py
+++ b/lib/sqlalchemy/dialects/mssql/pyodbc.py
@@ -52,7 +52,7 @@ name must be URL encoded which means using plus signs for spaces::
 
 Other keywords interpreted by the Pyodbc dialect to be passed to
 ``pyodbc.connect()`` in both the DSN and hostname cases include:
-``odbc_autotranslate``, ``ansi``, ``unicode_results``, ``autocommit``, 
+``odbc_autotranslate``, ``ansi``, ``unicode_results``, ``autocommit``,
 ``authentication`` (e.g., ``authentication=ActiveDirectoryIntegrated``).
 Note that in order for the dialect to recognize these keywords
 (including the ``driver`` keyword above) they must be all lowercase.
@@ -451,8 +451,9 @@ class MSDialect_pyodbc(PyODBCConnector, MSDialect):
     def is_disconnect(self, e, connection, cursor):
         if isinstance(e, self.dbapi.Error):
             code = e.args[0]
-            if code in (
+            if code in {
                 "08S01",
+                "01000",
                 "01002",
                 "08003",
                 "08007",
@@ -461,7 +462,7 @@ class MSDialect_pyodbc(PyODBCConnector, MSDialect):
                 "HYT00",
                 "HY010",
                 "10054",
-            ):
+            }:
                 return True
         return super(MSDialect_pyodbc, self).is_disconnect(
             e, connection, cursor

```


will add a separate issue for the ping thing.

**Comment by zzzeek** [comment]
oh, *or*, you could use the legacy recipe too:

https://docs.sqlalchemy.org/en/13/core/pooling.html#custom-legacy-pessimistic-ping

**Comment by frip** [comment]
Thank you for all your work, the comments and the new workarounds!

Judging by all the complications involved in using event-hooks to add an additional `is_disconnected`-code, my original workaround (inheriting the dialect and adding it to the dialect-registry) looks comparatively painless to me. Is there any deeper reason NOT to use a fix along that line?

**Comment by zzzeek** [comment]
oh you're actually registering it, heh.   sure that should be fine.   i was hoping my documented techniques actually worked here but since we've stumbled on that, you should be fine throughout 1.3.
