### ISSUE TITLE
Cannot update from 1.3.7 to 1.3.8: LookupError ... is not among the defined enum values

### ISSUE THREAD

**Issue by mlassnig** [sqlalchemy/sqlalchemy#5658]
Hello,

we are currently stuck on version 1.3.7 due to, what I assume, a change in the enum handling in 1.3.8. 

We use this recipe for `DeclEnum`: https://techspot.zzzeek.org/2011/01/14/the-enum-recipe/

i.e., https://github.com/rucio/rucio/blob/master/lib/rucio/db/sqla/enum.py

And the Enums are then defined like this:

```
class LifetimeExceptionsState(DeclEnum):
    APPROVED = 'A', 'APPROVED'
    REJECTED = 'R', 'REJECTED'
    WAITING = 'W', 'WAITING'
```

i.e., https://github.com/rucio/rucio/blob/master/lib/rucio/db/sqla/constants.py

Example code that is failing now:

```
    ...
    aid = session.query(models.IdentityAccountAssociation).filter_by(identity=identity, identity_type=identity_type, account=account).first()
    if aid is None:
        raise exception.IdentityError('Identity (\'%s\',\'%s\') does not exist!' % (identity, identity_type))
    aid.delete(session=session)
    ...
```
where `identity_type` is of class `EnumSymbol` from the recipe above.

The stack trace we get looks like this now (this is from 1.3.20, but starts happening in 1.3.8):
```
Traceback (most recent call last):
  File "/opt/rucio/lib/rucio/web/rest/account.py", line 626, in DELETE
    del_account_identity(identity, authtype, account, ctx.env.get('issuer'), vo=ctx.env.get('vo'))
  File "/opt/rucio/lib/rucio/api/identity.py", line 96, in del_account_identity
    return identity.del_account_identity(identity_key, IdentityType.from_sym(id_type), account)
  File "/opt/rucio/lib/rucio/db/sqla/session.py", line 377, in new_funct
    result = function(*args, **kwargs)
  File "/opt/rucio/lib/rucio/core/identity.py", line 187, in del_account_identity
    aid.delete(session=session)
  File "/opt/rucio/lib/rucio/db/sqla/models.py", line 237, in delete
    session.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 624, in execute
    uow,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 326, in delete_obj
    _organize_states_for_delete(base_mapper, states, uowtransaction)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 463, in _organize_states_for_delete
    base_mapper, uowtransaction, states
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1605, in _connections_for_states
    for state in _sort_states(base_mapper, states):
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1630, in _sort_states
    persistent, key=mapper._persistent_sortkey_fn
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2809, in key
    for key_fn, val in zip(key_fns, state.key[1])
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2809, in <genexpr>
    for key_fn, val in zip(key_fns, state.key[1])
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1524, in _db_value_for_elem
    replace_context=err,
  File "<string>", line 5, in raise_
LookupError: 'USERPASS' is not among the defined enum values. Enum name: ACCOUNT_MAP_ID_TYPE_CHK. Possible values: GSS, USERPASS, X509, ..., OIDC
```

Can you please point me in a direction how to fix this?

Thanks a lot,
Mario

**Versions**
 - OS: Linux
 - Python: 2.7.5
 - SQLAlchemy: works in 1.3.7, stops working from 1.3.8
 - Database: PostgreSQL
 - DBAPI: psycopg2-binary==2.8.6

**Comment by zzzeek** [comment]
heya -

can't reproduce.  the script at https://techspot.zzzeek.org/files/2011/decl_enum.py works for me if I update it for python 3 (print statement, metaclass), as below.

from the error, it seems simply that your "USERPASS" enumeration value is missing from your datatype somehow, or that you are passing a some other similar object to your type that isn't part of the enumeration.    The feature added in 1.3.8 had to be expanded to check that the values being passed were of what was expected.   if you are passing an object that isn't actually part of the enum values and it was silently passing, that was undefined behavior which now raises.

if you are "fixing" code in any case, it might be worth simply using real Python enums rather than that nine year old recipe, as the Enum type supports all pep-435 classes directly now; that's in fact what version 1.3.8 was adding.   

```
from sqlalchemy.types import SchemaType, TypeDecorator, Enum
from sqlalchemy import __version__
import re

if __version__ < "0.6.5":
    raise NotImplementedError(
        "Version 0.6.5 or higher of SQLAlchemy is required."
    )


class EnumSymbol(object):
    """Define a fixed symbol tied to a parent class."""

    def __init__(self, cls_, name, value, description):
        self.cls_ = cls_
        self.name = name
        self.value = value
        self.description = description

    def __reduce__(self):
        """Allow unpickling to return the symbol
        linked to the DeclEnum class."""
        return getattr, (self.cls_, self.name)

    def __iter__(self):
        return iter([self.value, self.description])

    def __repr__(self):
        return "<%s>" % self.name


class EnumMeta(type):
    """Generate new DeclEnum classes."""

    def __init__(cls, classname, bases, dict_):
        cls._reg = reg = cls._reg.copy()
        for k, v in dict_.items():
            if isinstance(v, tuple):
                sym = reg[v[0]] = EnumSymbol(cls, k, *v)
                setattr(cls, k, sym)
        return type.__init__(cls, classname, bases, dict_)

    def __iter__(cls):
        return iter(cls._reg.values())


class DeclEnum(metaclass=EnumMeta):
    """Declarative enumeration."""

    _reg = {}

    @classmethod
    def from_string(cls, value):
        try:
            return cls._reg[value]
        except KeyError:
            raise ValueError(
                "Invalid value for %r: %r" % (cls.__name__, value)
            )

    @classmethod
    def values(cls):
        return cls._reg.keys()

    @classmethod
    def db_type(cls):
        return DeclEnumType(cls)


class DeclEnumType(SchemaType, TypeDecorator):
    def __init__(self, enum):
        self.enum = enum
        self.impl = Enum(
            *enum.values(),
            name="ck%s"
            % re.sub(
                "([A-Z])", lambda m: "_" + m.group(1).lower(), enum.__name__
            )
        )

    def _set_table(self, table, column):
        self.impl._set_table(table, column)

    def copy(self):
        return DeclEnumType(self.enum)

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        return value.value

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return self.enum.from_string(value.strip())


if __name__ == "__main__":
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy import Column, Integer, String, create_engine
    from sqlalchemy.orm import Session

    Base = declarative_base()

    class EmployeeType(DeclEnum):
        part_time = "P", "Part Time"
        full_time = "F", "Full Time"
        contractor = "C", "Contractor"

    class Employee(Base):
        __tablename__ = "employee"

        id = Column(Integer, primary_key=True)
        name = Column(String(60), nullable=False)
        type = Column(EmployeeType.db_type())

        def __repr__(self):
            return "Employee(%r, %r)" % (self.name, self.type)

    e = create_engine("sqlite://", echo=True)
    Base.metadata.create_all(e)

    sess = Session(e)

    sess.add_all(
        [
            Employee(name="e1", type=EmployeeType.full_time),
            Employee(name="e2", type=EmployeeType.full_time),
            Employee(name="e3", type=EmployeeType.part_time),
            Employee(name="e4", type=EmployeeType.contractor),
            Employee(name="e5", type=EmployeeType.contractor),
        ]
    )
    sess.commit()

    print(sess.query(Employee).filter_by(type=EmployeeType.contractor).all())

```

**Comment by mlassnig** [comment]
Thanks a lot for the reply! That particular piece was not changed in the codebase for many many years now, so I will try to change everything to the correct enums now ;-) I'll report back my findings. Thanks again!

**Comment by mlassnig** [comment]
Hi,
this took a bit longer, but here's the changes I've had to make all over our codebase:

https://github.com/rucio/rucio/pull/4133/files

Maybe it's helpful for others in the future. You can close this ticket. Thanks!
