### ISSUE TITLE
Cannot retrieve a row that contains `ARRAY` with `dimensions`

### ISSUE THREAD

**Issue by dearoneesama** [sqlalchemy/sqlalchemy#5665]
I am attempting to use query to retrieve a row from a table that contains ARRAYs of Integers:
```py
from sqlalchemy import Column, Integer, String
from sqlalchemy.dialects.postgresql import ARRAY, array
from sqlalchemy.engine import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm.session import sessionmaker

Base = declarative_base()

class MyPoint1(Base):
    __tablename__ = 'my_point1_test'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    coord = Column(ARRAY(Integer, as_tuple=True))
    def __repr__(self): return f'<MyPoint1 id={self.id} name={self.name} coord={self.coord}>'

class MyPoint2(Base):
    __tablename__ = 'my_point2_test'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    coord = Column(ARRAY(Integer, as_tuple=True, dimensions=2))
    def __repr__(self): return f'<MyPoint1 id={self.id} name={self.name} coord={self.coord}>'

engine = create_engine('postgresql://user:pass@localhost:9999')
Base.metadata.create_all(engine) # type: ignore
Session = sessionmaker(bind=engine)

session = Session()

session.add(MyPoint1(name='pt1', coord=array([40, 50])))
session.add(MyPoint2(name='pt2', coord=array([40, 60])))

print(session.query(MyPoint1).filter_by(name='pt1').first()) # result 1
print(session.query(MyPoint2).filter_by(name='pt2').first()) # result 2

session.rollback()
```

I was able to print the first result:
```py
<MyPoint1 id=4 name=pt1 coord=(40, 50)>
```
However the second line fails with an error I do not understand:
```py
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    print(session.query(MyPoint2).filter_by(name='pt2').first())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
    _populate_full(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/array.py", line 359, in process
    return self._proc_array(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/array.py", line 306, in _proc_array
    return collection(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/array.py", line 307, in <genexpr>
    self._proc_array(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/sqlalchemydemo-eIQhHGJT-py3.8/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/array.py", line 304, in _proc_array
    return collection(arr)
TypeError: 'int' object is not iterable
```

When I omit `.first()` there was no error. Is there something wrong in my example code above?

**Versions**
 - OS: macOS 10.15.7
 - Python: 3.8
 - SQLAlchemy: 1.3.20
 - Database: psql11
 - DBAPI:

**Comment by CaselIT** [comment]
Hi,

The dimension is not the number of elements in it. A 2d array is a matrix. See https://en.wikipedia.org/wiki/Array_data_structure#Dimension

Your example array `array([40, 60])` has one single dimension. I guess changing the dimension to 1 will fix the issue

**Comment by CaselIT** [comment]
Please reopen if the issue was not solved.
