### ISSUE TITLE
hasattr(value, "__clause_element__") in Windows 10 raising KeyError

### ISSUE THREAD

**Issue by scott-wilson** [sqlalchemy/sqlalchemy#5697]
**Describe the bug**
I'm running into a weird issue where when we flush a session to create a database entry, the `hasattr(value, __clause_element__)` raises a KeyError instead of returning False.

**Expected behavior**
`hasattr(value, __clause_element__)` should return False instead of raising an error.

**To Reproduce**
I don't have a reproducible example yet, but I'll update the issue once I have one.

```py
# Insert code here
```

**Error**

```
Traceback (most recent call last):
  File "...\path\to\company\code.py"
    session.flush()
  File "...\sqlalchemy\orm\session.py", line 2536, in flush
    self._flush(objects)
  File "...\sqlalchemy\orm\session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "...\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "...\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "...\sqlalchemy\orm\session.py", line 2638, in _flush
    flush_context.execute()
  File "...\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "...\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "...\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "...\sqlalchemy\orm\persistence.py", line 1058, in _emit_insert_statements
    lambda rec: (
  File "...\sqlalchemy\orm\persistence.py", line 506, in _collect_insert_commands
    hasattr(value, "__clause_element__")
KeyError: '__clause_element__'
```

**Versions.**
 - OS:  Windows 10
 - Python: 3.7.9
 - SQLAlchemy: 1.3.20
 - Database: MySQL
 - DBAPI: mysqlclient 2.0.1

**Additional context**
I did some investigating, and it looks like the `hasattr` hasn't been altered at all (it looks like it is stock Python builtin). I'll try to recreate this issue with a small test case today if there's not enough context.

**Have a nice day!**

**Comment by zzzeek** [comment]
need a test case.  this would be a Python object that features a `__getattr__()` method but raises KeyError when an attribute isn't located.  the value would be assigned to a column attribute on an ORM mapped object.  search your app for objects that implement `__getattr__()`.

**Comment by scott-wilson** [comment]
Yeah, you're right. I managed to find the thing raising the KeyError. Thanks for the hint, though!
