### ISSUE TITLE
login failure when password contains a reserved character?

### ISSUE THREAD

**Issue by DeepGeek** [sqlalchemy/sqlalchemy#5715]
**Describe the bug**
Unable to connect to Oracle when the password has special characters.
(Many passwords are auto-generated when an account is set up and are required to have a certain number of special characters.)

**Expected behavior**
Expect successful connection: the connection is successful through other tools and through SQL Alchemy when the password is changed to something with special characters at the end.

**To Reproduce**
Connection string: `r'oracle+cx_oracle://someuser::%24jE?hpJ@SOME_TNS'`
The password randomly assigned was `:%24jE?hpJ`
Note the leading colon character ':' in the password.

```py
import sqlalchemy as sa
env = r'oracle+cx_oracle://someuser::%24jE?hpJ@SOME_TNS'
dbcon = sa.create_engine(env)
dbcon.execute('select 1 from dual')
```

**Error**

```
Traceback (most recent call last):
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 2243, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 2311, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 2348, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 1590, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Miniconda3\envs\r20\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-01017: invalid username/password; logon denied
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Versions.**
 - OS: Windows 10
 - Python: 3.8.5
 - SQLAlchemy: 1.3.17
 - Database: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
 - DBAPI: ? cx_Oracle 7.2.3

**Additional context**
cx_oracle is the lower library: that package project checked out the problem here and confirmed it was higher up the stack: https://github.com/oracle/python-cx_Oracle/issues/494
This is a minor bug with an easy workaround: change the password in Oracle with:
`ALTER USER YOUR_USER IDENTIFIED BY NewPassword replace OldPasswordWithSpecialChars`
But I'd hate for someone else to spend the same length of time figuring this out as I did.

**Have a nice day!**
Thanks for all you guys do.

**Comment by CaselIT** [comment]
Hi,

The password needs to be escaped if it contains special characters. Please refer to https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=create_engine#database-urls

@zzzeek I think we should improve the docs for `create_engine` to mention and link this, since it's a question that periodically comes up.

**Comment by zzzeek** [comment]
probably needs some dragons yup

**Comment by DeepGeek** [comment]
Ah thanks. I had no idea I had to escape or encode a python raw string. I'll add the url encoding.
Appreciate the quick answer!

**Comment by CaselIT** [comment]
I'll reopen the issue so we can track the documents improvements. It clearly could  be better for this case :)

**Comment by fejao** [comment]
I still can't parse special characters such as **@** to the **oracle+cx_oracle** engine. This problem is not happening to the **postgres+psycopg2** engine.  
```
import sqlalchemy as sa
import urlib.parse
user_pass = "p@ssword"
env = oracle+cx_oracle://someuser:'+urlib.parse.quote_plus(user_pass)+'@SOME_TNS'
dbcon = sa.create_engine(env)
dbcon.execute('select 1 from dual')
```
it also doesn't works when I set the string as hard-coded with the scape character for **@** as **%40**

**Comment by zzzeek** [comment]
> I still can't parse special characters such as **@** to the **oracle+cx_oracle** engine. This problem is not happening to the **postgres+psycopg2** engine.
> 
> ```
> import sqlalchemy as sa
> import urlib.parse
> user_pass = "p@ssword"
> env = oracle+cx_oracle://someuser:'+urlib.parse.quote_plus(user_pass)+'@SOME_TNS'
> dbcon = sa.create_engine(env)
> dbcon.execute('select 1 from dual')
> ```
> 
> it also doesn't works when I set the string as hard-coded with the scape character for **@** as **%40**

that sounds like a driver issue.   can you try a direct [cx_oracle](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#establishing-database-connections) connection to see if your password works?

**Comment by fejao** [comment]
@zzzeek Using the regular cx_Oracle.connect it does works without a problem
```
import cx_Oracle
user_pass = "p@ssword"
conn_str = 'someuser/'+user_pass+'//SOME_TNS'
conn = cx_Oracle.connect(conn_str)
cur = conn.cursor()
cur.execute('select 1 from dual')
```
could not be that you are parsing the URL for postgres and not for oracle?

**Comment by zzzeek** [comment]
SQLAlchemy connects as:

```
import cx_Oracle

conn_str = cx_Oracle.makedsn("oracle1120", 1521, sid="")
conn = cx_Oracle.connect(user="someuser", password="p@assword", dsn=conn_str)
cur = conn.cursor()
cur.execute("select 1 from dual")

```

since I dont have that username I get "invalid username/password; logon denied"

can confirm arguments are produced correctly however:

```
from sqlalchemy.engine import make_url
from sqlalchemy.dialects import oracle


url = make_url("oracle://scott:p%40ssword@oracle1120/")

dialect = oracle.dialect()
print(dialect.create_connect_args(url))


```
output:

    ([], {'dsn': 'oracle1120', 'password': 'p@ssword', 'user': 'scott'})

**Comment by fejao** [comment]
@zzzeek : Sorry for the delay on answering, the admin only let me in again today again at the DB
I can't reproduce your test. It looks like I got a different sqlalchemy installed when I runned
```
pip3 install sqlalchemy
```
because I don't have the **make_url** on **sqlalchemy.engine**
```
from sqlalchemy.engine import make_url
*** ImportError: cannot import name 'make_url' form 'sqlalchemy.engine' (/home/<USER_NAME>/.local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py)
```
The latest version that I can install is the **SQLAlchemy-1.3.22-cp38-cp38-manylinux2010_x86_64.whl**

**Comment by zzzeek** [comment]
in 1.3 it's under sqlalchemy.engine.url.

Here is a complete 1.3.22 session
```

Python 3.8.3 (default, May 23 2020, 16:34:37) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.22'
>>> from sqlalchemy.engine.url import make_url
>>> from sqlalchemy.dialects import oracle
>>> url = make_url("oracle://scott:p%40ssword@oracle1120/")
>>> dialect = oracle.dialect()
>>> print(dialect.create_connect_args(url))
([], {'dsn': 'oracle1120', 'password': 'p@ssword', 'user': 'scott'})

```

**Comment by fejao** [comment]
@zzzeek  Thank for such a fast reply.
It does looks like that the dialect are building the parameters with the special characters, but I'm still getting **ORA-01017: invalid username/password; logon denied** error
here is the full example:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> from sqlalchemy.engine.url import make_url
>>> from sqlalchemy.dialects import oracle
>>> from sqlalchemy import create_engine
>>> query = "SELECT banner FROM v$version"
>>> sid = cx_Oracle.makedsn('10.10.0.10', 1521, service_name='TESTDB1')
>>> print(sid)
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.10.0.10)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=TESTDB1)))
>>> conn_str = 'oracle://test_user:password%40@' + sid
>>> print(conn_str)
oracle://test_user:password%40@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.10.0.10)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=TESTDB1)))
>>> url = make_url(conn_str)
>>> dialect = oracle.dialect()
>>> print(dialect.create_connect_args(url))
([], {'dsn': '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.10.0.10)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=TESTDB1)))', 'password': 'password@', 'user': 'test_user'})
>>> engine = create_engine(conn_str, echo=True)
>>> conn = engine.connect()
Traceback (most recent call last):
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 509, in connect
    return self.dbapi.connect(*cargs, **cparams)
cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/virtuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 509, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-01017: invalid username/password; logon denied
(Background on this error at: http://sqlalche.me/e/13/4xp6)
>>>
```
and the **cx_Oracle** are working with the same credentials
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> query = "SELECT banner FROM v$version"
>>> conn_str = 'test_user/password@//10.10.0.10:1521/TESTDB1'
>>> conn = cx_Oracle.connect(conn_str)
>>> cur = conn.cursor()
>>> cur.execute(query)
<cx_Oracle.Cursor on <cx_Oracle.Connection to test_user@//10.10.0.10:1521/TESTDB1>>
>>> print(cur.fetchall())
[('Oracle Database .....',)]
>>> cur.close()
>>> conn.close()
```

**Comment by zzzeek** [comment]
hey there -

you still need to run the final step, which is to combine the connect arguments with cx_Oracle itself.   This will reveal if cx_Oracle is in fact mis-handling the password when **it is passed as a separate argument, not already in the connection string**.   like this:
```

import cx_Oracle
conn = cx_Oracle.connect(
    user='test_user',
    password='password@',
    dsn='(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.10.0.10)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=TESTDB1)))'
)
```

**Comment by fejao** [comment]
@zzzeek it does looks like that it is on the cx_Oracle side
I oppened an [issue](https://github.com/oracle/python-cx_Oracle/issues/515) at they're repo
I'll update it here if the issue is resolved

**Comment by zzzeek** [comment]
you can connect with SQLAlhcemy like this for now:

```
def creator():
    return cx_Oracle.connect(connection_string_that_works)

engine = create_engine("oracle://", creator=creator)

```

I will monitor the cx_Oracle issue.

**Comment by yechiel-optimalq** [comment]
Any update on this? We experience the same (reproduciable)

**Comment by zzzeek** [comment]
the original user likely was using the wrong password and no bug was observed on either the SQLAlchemy or cx_Oracle side.
