### ISSUE TITLE
Using `text(...)` for `Select.with_for_update(of=...)` argument broken since 1.3.2

### ISSUE THREAD

**Issue by sevens-ef** [sqlalchemy/sqlalchemy#5729]
**Describe the bug**
Using a `text(...)` value for the `of` argument in a `Select.with_for_update()` call results in a broken query since version 1.3.2; the value isn't included in the `FOR UPDATE OF` part at all.

**Expected behavior**
A valid query to be generated, including the supplied value in the `FOR UPDATE OF` part.

**To Reproduce**

```py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sqlalchemy.sql
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import *

Base = declarative_base()


class User(Base):
    __tablename__ = '_user_'  # Underscores to avoid being a postgres keyword

    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)


e = create_engine('postgresql://...', echo=True)
Base.metadata.create_all(e)
s = Session(e)

s.query(User.id).with_for_update(of=User).all()  # Succeeds
s.query(User.id).with_for_update(of=sqlalchemy.sql.text('_user_')).all()  # Fails
```

**Error**

```
Traceback (most recent call last):
  File "./reproduce.py", line 29, in <module>
    s.query(User.id).with_for_update(of=sqlalchemy.sql.text('_user_')).all()  # Fails
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/home/me/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at end of input
LINE 2: FROM _user_ FOR UPDATE OF
```

**Versions.**
 - OS: Ubuntu 18.04.5
 - Python: 3.9.0 (also reproduced on 3.6.x)
 - SQLAlchemy: 1.3.2, 1.3.20
 - Database: PostgreSQL 9.6
 - DBAPI: psycopg2 2.8.6

**Additional context**
This worked in SQLAlchemy 1.1.x, 1.2.x, 1.3.0 and 1.3.1.  It got broken in 1.3.2 (also tested 1.3.5, 1.3.10 and 1.3.20, broken in all of them).

Possibly introduced by the fix for https://github.com/sqlalchemy/sqlalchemy/issues/4550 ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't discard leftovers from surface_selectables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2383

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't discard leftovers from surface_selectables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2384
