### ISSUE TITLE
multiple select queries on single connection

### ISSUE THREAD

**Issue by mozartilize** [sqlalchemy/sqlalchemy#5743]
Hi,
I'm playing around with sqlalchemy asyncio with fastapi and have a thought about using single connection for GET requests which invoke select queries in it. The code works fine but I have some questions:

- Is it safe to have multiple select queries on single connection?
- Does it blocking while fetching cursor's results (from multiple select queries) on single connection?

Here is my sample code:
```python
db_engine = create_async_engine(
    settings.sqlalchemy_database_uri,
    poolclass=AsyncAdaptedQueuePool,
    pool_recycle=180,
)

autocommit_db_engine = create_async_engine(
    settings.sqlalchemy_database_uri,
    pool=db_engine.pool,
    connect_args={'autocommit': True}
)

conn = await autocommit_db_engine.connect()

async def get_users():
    re = await conn.execute(select(User))
    return re.all()


async def ping_db():
    re = await conn.execute(text('select 1'))
    return re.fetchone()

tasks = [*(get_users() for i in range(100), *(ping_db() for i in range(100))]
random.shuffle(tasks)
await asyncio.gather(*tasks)
```
**Versions**
 - OS: ubuntu 20.04
 - Python: 3.8
 - SQLAlchemy: 1.4 git
 - Database: mysql
 - DBAPI: pymysql

**Have a nice day!**

**Comment by zzzeek** [comment]
> Hi,
> I'm playing around with sqlalchemy asyncio with fastapi and have a thought about using single connection for GET requests which invoke select queries in it. The code works fine but I have some questions:
> 
>     * Is it safe to have multiple select queries on single connection?

OK so I had a bunch written here and then noticed you're running the pymysql driver through the whole thing.   There's no async support for MySQL right now so your program above is fully blocking; there would need to be an asyncio driver for MySQL (there *might* be one out there?  not sure if it uses a thread executor though which would not be very efficient)  and then we'd have to add a driver for it.    kind of crazy it runs though and we are talking about having this raise or warn or something like that, because while it "works" you are not actually getting any concurrency at all.

the only driver supported right now is asyncpg for PostgreSQL, and the general idea of your program above will run fine with asyncpg, each statement uses its own cursor and with PG drivers it's fine to have multiple, simultaneous cursors open (not so much with the MySQL drivers).

**Comment by XiNiHa** [comment]
> There's no async support for MySQL right now so your program above is fully blocking; there would need to be an asyncio driver for MySQL (there _might_ be one out there? not sure if it uses a thread executor though which would not be very efficient) and then we'd have to add a driver for it.

It looks like there are some of async MySQL drivers(haven't looked precisely). Is there any plan to support for any of those drivers?

**Comment by zzzeek** [comment]
of course, because we have to invent a DBAPI for each one they are a little more work but having a high quality MySQL driver would be great.   asyncio is in alpha right now overall.

**Comment by XiNiHa** [comment]
Sounds great! Does the upgrade to 2.0 involve any kind of improvements in asyncio support? Or would it make asyncio support have lower priority to maintain issues from 2.0 upgrade? Being super excited about both 2.0 upgrade and asyncio btw 😄

**Comment by zzzeek** [comment]
we hope by 2.0 that the API we've chosen for asyncio is acceptable to everyone and it does all the things needed, any catastrophic bugs etc have been fixed, etc.  because asyncio both can have a lot of issues like unexpected blocking etc. and as well as if we get it wrong on the API it could be very hard to change without breaking compatibility since asyncio is so explicit.    I'm totally assuming people are going to be putting asyncio into production with 1.4 in any case, I just need to reserve the right to change things if necessary.

**Comment by mozartilize** [comment]
@zzzeek thanks for your clarification. I'm totally misunderstand asyncio feature of sqlalchemy. Re-reading the migration guide and figuring out what it really is:

[https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#asynchronous-io-support-for-core-and-orm](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#asynchronous-io-support-for-core-and-orm)
> The internal features of SQLAlchemy are fully integrated by making use of the greenlet library in order to adapt the flow of execution within SQLAlchemy’s internals to propagate asyncio await keywords outwards from the database driver to the end-user API, which features async methods.

**Comment by zzzeek** [comment]
the aiomysql driver looks very easy to adapt, will see if I can get something in gerrit today.

**Comment by mozartilize** [comment]
@zzzeek hi, just have some time to test with asyncpg and the result is not expected, here is my example

```python
engine = create_async_engine("postgresql+asyncpg://scott:tiger@localhost/test")
conn = await engine.execution_options(isolation_level='AUTOCOMMIT').connect()

def task(conn, number):
    r = await conn.execute(text(f'select {num}'))
    return r.fetchall()

tasks = [task(conn, i) for i in range(100)]
asyncio.gather(*tasks)
```

Traceback:

```
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 384, in _prepare_and_execute
    prepared_stmt, attributes = await self._adapt_connection._prepare(
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 611, in _prepare
    prepared_stmt = await self._connection.prepare(operation)
  File "venv/lib/python3.8/site-packages/asyncpg/connection.py", line 425, in prepare
    return await self._prepare(query, timeout=timeout, use_cache=False)
  File "venv/lib/python3.8/site-packages/asyncpg/connection.py", line 429, in _prepare
    stmt = await self._get_statement(query, timeout, named=True,
  File "venv/lib/python3.8/site-packages/asyncpg/connection.py", line 351, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 149, in prepare
  File "asyncpg/protocol/protocol.pyx", line 664, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_context
    self.dialect.do_execute(
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 682, in do_execute
    cursor.execute(statement, parameters)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 418, in execute
    self._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 634, in _handle_exception
    raise error
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 414, in execute
    self._adapt_connection.await_(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 56, in await_only
    return current.driver.switch(awaitable)
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 109, in greenlet_spawn
    value = await result
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 410, in _prepare_and_execute
    self._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 630, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/htv-havt/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/htv-havt/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "<console>", line 2, in task
  File "venv/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 404, in execute
    result = await greenlet_spawn(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 114, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1453, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1322, in _execute_clauseelement
    ret = self._execute_context(
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1681, in _execute_context
    self._handle_dbapi_exception(
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _handle_dbapi_exception
    util.raise_(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_context
    self.dialect.do_execute(
  File "venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 682, in do_execute
    cursor.execute(statement, parameters)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 418, in execute
    self._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 634, in _handle_exception
    raise error
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 414, in execute
    self._adapt_connection.await_(
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 56, in await_only
    return current.driver.switch(awaitable)
  File "venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 109, in greenlet_spawn
    value = await result
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 410, in _prepare_and_execute
    self._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 630, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
[SQL: select 1]
(Background on this error at: http://sqlalche.me/e/14/rvf5)
```

**Comment by zzzeek** [comment]
> @zzzeek hi, just have some time to test with asyncpg and the result is not expected, here is my example

Indeed, asyncpg does not appear to support simultaneous prepared statements, so I've amended my answer above.

This is not a SQLAlchemy issue, here is your program in terms of asyncpg, same output.

```python

import asyncio
import asyncpg


async def run_query(conn, num):
    prepared = await conn.prepare(f"SELECT {num}")
    rows = await prepared.fetch()
    return rows

async def main():
    conn = await asyncpg.connect(user="scott", password="tiger", host="localhost", database="test")

    tasks = [run_query(conn, i) for i in range(100)]
    asyncio.gather(*tasks)

asyncio.run(main())
```
