### ISSUE TITLE
Unable to specify name argument to aliased with an association table

### ISSUE THREAD

**Issue by funseiki** [sqlalchemy/sqlalchemy#5750]
**Describe the bug**

When trying to use `aliased` with an association table and setting the 'name' argument:
```py
at_alias = aliased(association_table, name="myJoinedTable")
```
An assertion error appears
```
sqlalchemy/sql/coercions.py", line 922, in _post_coercion
    assert name is None
```

**Expected behavior**
Allowing a name parameter to be set for association tables (unless I'm missing something from the migration notes, in which case sorry!).

**To Reproduce**
```py
from sqlalchemy import create_engine, Column, Integer, String, DateTime, ForeignKey, Table, MetaData
from sqlalchemy.orm import sessionmaker, relationship, aliased, backref, registry

mapper_reg = registry()
engine = create_engine('sqlite:///:memory:', echo=False)
metadata = MetaData(bind=engine)
association_table = Table('association', metadata,
                          Column('parent_id', Integer, ForeignKey('things.id')),
                          Column('child_id', Integer, ForeignKey('things.id'))
                          )

things = Table('things', metadata,
               Column('id', Integer, primary_key=True))

class Thing(object):
    pass

mapper_reg.map_imperatively(Thing, things,
       properties={
           'children': relationship(Thing,
                                    secondary=association_table,
                                    primaryjoin=things.c.id == association_table.c.parent_id,
                                    secondaryjoin=things.c.id == association_table.c.child_id)
       })

metadata.create_all(engine)

# Below is where the error occurs
at_alias = aliased(association_table, name="myJoinedTable")
```

**Error**

```
Traceback (most recent call last):
  File "aliased_error.py", line 27, in <module>
    at_alias = aliased(association_table, name="myJoinedTable")
  File "/Users/me/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sqlalchemy/orm/util.py", line 1138, in aliased
    roles.AnonymizedFromClauseRole, element, name=name, flat=flat
  File "/Users/me/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sqlalchemy/sql/coercions.py", line 176, in expect
    **kw
  File "/Users/me/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sqlalchemy/sql/coercions.py", line 922, in _post_coercion
    assert name is None
AssertionError
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 2.7.14
 - SQLAlchemy: 1.4.0b1
 - Database: SQLite

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass through plain selectable to .alias()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2402

**Comment by zzzeek** [comment]
use table.alias(name=name) for now
