### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.

### ISSUE THREAD

**Issue by flozi00** [sqlalchemy/sqlalchemy#5753]
**Describe your question**

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

the script
```
from app import db
from app.models import ContactGroup, Contact
import random
from datetime import datetime

print(db.session.query(ContactGroup).filter(ContactGroup.created_by == 1))
```

the model
```
import datetime

from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin
from sqlalchemy import Column, Date, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.orm import backref
import random
from .. import db

mindate = datetime.date(datetime.MINYEAR, 1, 1)


class ContactGroup(AuditMixin, Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)

    def __repr__(self):
        return self.name


class CrmBackend(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)

    def __repr__(self):
        return self.name




class Contact(AuditMixin, Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(150), unique=False, nullable=False)
    address = Column(String(564))
    apikey = Column(String(564))
    contact_group_id = Column(Integer, ForeignKey("contact_group.id"), nullable=False)
    contact_group = relationship("ContactGroup") # this need to be filtered, cause only Group the user itself created should be displayed
    crm_backend_id = Column(Integer, ForeignKey("crm_backend.id"), nullable=False)
    crm_backend = relationship("CrmBackend")

    def __repr__(self):
        return self.name
```

**Complete stack trace, if applicable**

```
Traceback (most recent call last):
  File ".\testdata.py", line 6, in <module>
    print(db.session.query(ContactGroup).filter(ContactGroup.created_by == 1))
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\operators.py", line 365, in __eq__
    return self.operate(eq, other)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\attributes.py", line 219, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 1267, in __eq__
    self.property._optimized_compare(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 1648, in _optimized_compare
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.   Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use ContactGroup.created_by.has(**criteria).
```

**Versions**
 - OS: win 10
 - Python: 3.8
 - SQLAlchemy: Master
 - Database: sqllite
 - DBAPI:

**Additional context**
What's wrong with the relationship, how should it be right ?

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

your query refers to an attribute called "created_by" but I don't see this in your model.     however based on your naming convention I would assume you mean to say "filter(ContactGroup.created_by_id == 1)".  you can't compare a relationship to an integer number like "1", only to an object.  if you want to compare a primary key, then use the integer-column-bound attribute.

**Comment by flozi00** [comment]
go the error
crm_backend = relationship("CrmBackend", foreign_keys=[crm_backend_id])

I forgot to add the foreign keys
