### ISSUE TITLE
Syntax Error creating named check constraint in Mariadb

### ISSUE THREAD

**Issue by kdwyer** [sqlalchemy/sqlalchemy#5757]
**Describe the bug**
The `CREATE TABLE` statement generated when a named check constraint is specified results in a syntax error in Mariadb.  
```sql
CREATE TABLE foo20201209 (
        bar INTEGER CONSTRAINT ck_foo20201209_gt_0 CHECK (bar > 0)
)
```
There seems to be a comma missing between the column specification and the constraint specification, as this DDL succeeds:

```sql
CREATE TABLE foo20201209 (
        bar INTEGER, CONSTRAINT ck_foo20201209_gt_0 CHECK (bar > 0)
)
```

**Expected behavior**
The statement should be syntactically correct.

**To Reproduce**

```py
import sqlalchemy as sa

convention = {
  "ix": 'ix_%(column_0_label)s',
  "uq": "uq_%(table_name)s_%(column_0_name)s",
  "ck": "ck_%(table_name)s_%(constraint_name)s",
  "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
  "pk": "pk_%(table_name)s"
}
metadata = sa.MetaData(naming_convention=convention)

sa.Table('foo20201209', metadata,
         sa.Column('bar', sa.Integer, sa.CheckConstraint('bar > 0', name='gt_0'), default=0))


conn_strings = ['mysql+pymysql:///test',
                'mysql+mysqldb:///test',
                'mysql+mysqlconnector:///test']


for cs in conn_strings:
    engine = sa.create_engine(cs)
    print('Engine', engine.url)
    metadata.drop_all(bind=engine)
    try:
        metadata.create_all(bind=engine)
    except sa.exc.ProgrammingError as ex:
        print(ex)
    finally:
        engine.dispose()

```

**Error**

```
# Example output using pymysql, all three packages result in the same error.
Traceback (most recent call last):                                                                                             
  File "/home/kev/python_projects/so38/mariadb_constraint_test.py", line 26, in <module>                                       
    metadata.create_all(bind=engine)                                                                                           
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4501, in create_all            
    bind._run_ddl_visitor(                                                                                                     
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2844, in _run_ddl_visitor     
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)                                                                  
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_ddl_visitor     
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)                                                     
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 486, in traverse_single      
    return meth(obj, **kw)                                                                                                     
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 729, in visit_metadata            
    self.traverse_single(                                                                                                      
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 486, in traverse_single      
    return meth(obj, **kw)                                                                                                     
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 773, in visit_table               
    self.connection.execute(                                                                                                   
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1123, in execute              
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)                                                              
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection     
    return connection._execute_ddl(                                                                                            
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1213, in _execute_ddl         
    ret = self._execute_context(                                                                                               
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1671, in _execute_context     
    self._handle_dbapi_exception(                                                                                              
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1852, in _handle_dbapi_exception                                                                                                                             
    util.raise_(
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 180, in raise_
    raise exception
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1628, in _execute_context
    self.dialect.do_execute(
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 663, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/kev/virtual-envs/so39/lib/python3.9/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONSTRAINT ck_foo20201209_gt_0 CHECK (bar > 0)\n)' at line 2")
[SQL: 
CREATE TABLE foo20201209 (
        bar INTEGER CONSTRAINT ck_foo20201209_gt_0 CHECK (bar > 0)
)

]
```

**Versions.**
 - OS: Linux (OpenSuse Leap 15.1)
 - Python: CPython 3.9 (built from source)
 - SQLAlchemy: 1.4.0b1
 - Database: 10.2.36-MariaDB SUSE package
 - DBAPI:  mysql-connector-python 8.0.22
                 mysqlclient            2.0.1
                 PyMySQL                0.10.1

**Additional context**
Thanks for your excellent library!

**Comment by zzzeek** [comment]
hey there -

behavior is expected for the way in which you are specifying this constraint.  for a table-level constraint, move it outisde of Column:

```
sa.Table('foo20201209', metadata,
         sa.Column('bar', sa.Integer, default=0),
sa.CheckConstraint('bar > 0', name='gt_0'))

```

hope this helps!

**Comment by kdwyer** [comment]
Thanks for the reply.  Is this expected behaviour documented anywhere?  I couldn't find anything in the docs for constraints or MySQL, and I was puzzled because the example code works without error for Postgresql and Sqlite.

But I realise there isn't really much of a use case for naming inline constraints, so feel free to close this issue.

**Comment by zzzeek** [comment]
the CheckConstraint construct is illustrated using both forms here:

https://docs.sqlalchemy.org/en/13/core/constraints.html#check-constraint

there's a little box that says "SQL" on it, if you click that it will illustrate the SQL emitted for the example constraints.  it illustrates both a column level and a table-level CHECK constraint.

**Comment by kdwyer** [comment]
Thanks for your replies, and once again for SQLAlchemy.
