### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Mapper mapped class User->users could not assemble any primary key columns for mapped table 'users'

### ISSUE THREAD

**Issue by Timtaran** [sqlalchemy/sqlalchemy#5771]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

https://pastebin.com/GF3abSKd

**Error**

```
Traceback (most recent call last):
  File "C:/Users/user/Documents/GitHub/pythonProject/LifeSimulator/src/tests/test1.py", line 11, in <module>
    class User(Base):
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\api.py", line 76, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 131, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 160, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 194, in __init__
    self._early_mapping()
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 199, in _early_mapping
    self.map()
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 695, in map
    self.cls.__mapper__ = mp_ = mapper_cls(
  File "<string>", line 2, in mapper
  File "<string>", line 2, in __init__
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 723, in __init__
    self._configure_pks()
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1409, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper mapped class User->users could not assemble any primary key columns for mapped table 'users'
```

**Versions.**
 - OS: Windows 7 64-bit
 - Python: 3.8.6
 - SQLAlchemy: 1.3.20
 - Database: sqlite3
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

As the exception message says, sqlalchemy "could not assemble any primary key columns for mapped table 'users'". See https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Column.params.primary_key for how to set a primary key on a column
