### ISSUE TITLE
How to handle database restart

### ISSUE THREAD

**Issue by tyctor** [sqlalchemy/sqlalchemy#5776]
I am creating flask app with sqlalchemy orm, during develop i found circumstances in which app fails and i am not sure what is simple way how to handle it.
Imagine running app, which is responding to user browser (e.g. Flask-Admin) `and this app already did some responses.`
Now on backend side i need to restart DB server (postgres), restart is done and DB server is already up.
Now when i go back to browser and refresh page, and i will get `sqlalchemy.exc.OperationalError`

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection 
due to administrator command server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```

but this is not true, because DB is already up, and i need restart flask app to get it working.

when i start app, and i restart DB `before any request` (so not request was handled by app)
this error not occurs and app is working well.

i think that some session or db connection is cached with request, and is not invalidated if `OperationalError` occurs

what is best way to handle this?
i already tryied, but without success:
 - to create_engine with `pool_pre_ping=True`
 - to create_engine with `poolclass=NullPool` to get new connection with each request
 - invalidating `Session` after request

what is working for me, but i think is ugly solution, is to use flask errohandler
```    
    @app.errorhandler(OperationalError)
    def handle_operational_error(error):
        db.session.rollback()
        db.session.close_all()
        count = int(request.args.get('_err', -1))
        if count > 0:
            raise error
        count += 1
        return redirect(request.path + f'?_err={count}')
```

such error never happened to me with django orm.

is there some standart way how to handle this?
thanks for any hints

**Comment by zzzeek** [comment]
hey there -

your workaround suggests that your application is not ensuring that sessions are closed and/or connections are returned to the pool when a request ends.    There's no way to prevent a restarted database from impacting a request that is in progress.  however when connections are first pulled from the pool, the "pre-ping" feature should be working, and that you tried NullPool which also didn't work means that your errors are not occurring on pool checkout, as nullpool makes a new connection each time.    each Flask request when it goes to do database work should be starting from a point of procuring a connection from the pool and then ensuring it's back in the pool at the end of the request.

if you can share a complete stack trace that would illustrate if your disconnect error is not being handled on pool checkout or if this is a connection that is idle between requests or within a request.

**Comment by zzzeek** [comment]
> @zzzeek thanks for reply and hint
> 
> so i go back to use to create_engine with `poolclass=NullPool`
> and i added `after_request` handler and i tryied to close session with `session.close()` but still without success
> so i try to close all sessions and it seems it working now
> 
> ```
>     from sqlalchemy.orm.session import close_all_sessions
> 
>     @app.after_request
>     def close_session(response):
>         close_all_sessions()
>         return response
> ```
> 
> but what i read in doc is that `This function is not for general use but may be useful for test suites within the teardown scheme.`
> https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.close_all_sessions
> 
> is there any other solution to close all sessions?

the idea is that every Flask request is responsible for closing its *own* session.  If your requests are not doing that, they are leaving connections / transactions dangling between requests, and that is a bug either in your application or within flask.   "close_all_sessions()" is a bad antipattern because it indicates your application is not keeping track of where it is making use of database connections and is not cleaning up after itself when a request ends.   you will down the road have problems much worse than disconnects, with PG you'll see a lot of deadlocks too.     There's definitely a lot of help to be had within the Flask community about this issue.

**Comment by davidism** [comment]
Flask-SQLAlchemy gets a connection from the pool when the session is first accessed, and removes it when the request is torn down, regardless of if there was an error. I'm not sure what else we're supposed to do, and I don't know why pre-ping isn't detecting stale pooled connections.

**Comment by zzzeek** [comment]
@davidism pre_ping has not been shown to be failing here.  that the user uses NullPool, where "pre ping" is irrelevant, and still gets the error is indicative that they are starting out their request with a database connection that wasn't in the pool already; because if it were, the NullPool would be making a brand new database connection, where success means that the database is definitely up.

What the Flask community can do is work with this user to either fix their application or to get a self-contained, portable, reproducing test case that would illustrate exactly what's going wrong, which would then lead to either how they should fix things or how Flask could be documented etc. to handle this.

For SQLAlchemy's part, our documentation on how to correctly use the ORM session is at https://docs.sqlalchemy.org/en/13/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it

**Comment by zzzeek** [comment]
@davidism  one thing that flask devs can try immediately is to create a plain Flask application using Postgresql with pre_ping, run a few requests, then restart the database and see if subsequent requests still work.    I'm pretty sure it will work fine otherwise we'd have way more people reporting this.   @tyctor  you can add "echo_pool='debug'" to your create_engine() call as in the example below and it will illustrate all connection pool activity.  A successful pre-ping reconnect with the same PostgreSQL error condition you are seeing is shown below.

Below is a non-flask test case which I just used to confirm that restarting postgresql is handled correctly by pre-ping.   If I dont use pre-ping, the exception class and message matches the one being reported here:

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

```

if I do use pre-ping, the pool debugging shows the reconnect occurring and the request completes

```
2020-12-16 13:11:29,545 DEBUG sqlalchemy.pool.impl.QueuePool Connection <connection object at 0x7f4c1d84d9c0; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0> checked out from pool
2020-12-16 13:11:29,545 DEBUG sqlalchemy.pool.impl.QueuePool Pool pre-ping on connection <connection object at 0x7f4c1d84d9c0; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
2020-12-16 13:11:29,546 DEBUG sqlalchemy.pool.impl.QueuePool Pool pre-ping on connection <connection object at 0x7f4c1d84d9c0; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 2> failed, will invalidate pool
2020-12-16 13:11:29,546 INFO sqlalchemy.pool.impl.QueuePool Disconnection detected on checkout, invalidating all pooled connections prior to current timestamp (reason: InvalidatePoolError())
2020-12-16 13:11:29,546 INFO sqlalchemy.pool.impl.QueuePool Invalidate connection <connection object at 0x7f4c1d84d9c0; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 2> (reason: InvalidatePoolError:())
2020-12-16 13:11:29,546 DEBUG sqlalchemy.pool.impl.QueuePool Closing connection <connection object at 0x7f4c1d84d9c0; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 2>
2020-12-16 13:11:29,573 DEBUG sqlalchemy.pool.impl.QueuePool Created new connection <connection object at 0x7f4c1d867170; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
2020-12-16 13:11:29,574 DEBUG sqlalchemy.pool.impl.QueuePool Pool pre-ping on connection <connection object at 0x7f4c1d867170; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0>
2020-12-16 13:11:29,575 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-12-16 13:11:29,576 INFO sqlalchemy.engine.base.Engine select 1
2020-12-16 13:11:29,576 INFO sqlalchemy.engine.base.Engine {}
2020-12-16 13:11:29,577 INFO sqlalchemy.engine.base.Engine COMMIT
2020-12-16 13:11:29,578 DEBUG sqlalchemy.pool.impl.QueuePool Connection <connection object at 0x7f4c1d867170; dsn: 'user=scott password=xxx dbname=test host=localhost', closed: 0> being returned to pool

```

```python
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


e = create_engine(
    "postgresql://scott:tiger@localhost/test",
    echo=True,
    pool_pre_ping=True,
    echo_pool="debug",
)

session = sessionmaker(e)


def request():
    s = session()

    try:
        s.execute("select 1")

        s.commit()
    finally:
        s.close()


while True:
    input("press any key to request")
    request()

```

**Comment by davidism** [comment]
> I'm pretty sure it will work fine otherwise we'd have way more people reporting this.

Yes, my thoughts too. I've got some time so I'm working on a little test right now.

**Comment by davidism** [comment]
I can't reproduce this with the following Flask-SQLAlchemy example. Visiting the page, restarting Postgres, and visiting again works correctly with pre-ping.

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql:///fsqla_test"
app.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
    "echo": True,
    "echo_pool": "debug",
    "pool_pre_ping": True,
}
db = SQLAlchemy()
db.init_app(app)


@app.route("/")
def index():
    out = db.session.execute("select 'hello'").fetchone()[0]
    db.session.commit()
    return out
```

**Comment by tyctor** [comment]
ok here is log with echo_pool='debug'
it seems that NullPool is working well `INFO 2020-12-16 20:33:20,422 log 175879 140374460724800 Invalidate connection...`

but new connection is not created on 
`File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)`

i will try to prepare some minimal reproducible code

```
DEBUG 2020-12-16 20:33:01,104 log 175879 140374585935424 Created new connection <connection object at 0x7fab7b002a08; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0>
2020-12-16 20:33:01,104 DEBUG sqlalchemy.pool.impl.NullPool Created new connection <connection object at 0x7fab7b002a08; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0>
2020-12-16 20:33:01,109 DEBUG sqlalchemy.pool.impl.NullPool Connection <connection object at 0x7fab7b002a08; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0> checked out from pool
DEBUG 2020-12-16 20:33:01,109 log 175879 140374585935424 Connection <connection object at 0x7fab7b002a08; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0> checked out from pool
127.0.0.1 - - [16/Dec/2020 20:33:01] "GET /admin/event/ HTTP/1.1" 200 -
INFO 2020-12-16 20:33:01,349 _internal 175879 140374585935424 127.0.0.1 - - [16/Dec/2020 20:33:01] "GET /admin/event/ HTTP/1.1" 200 -
2020-12-16 20:33:01,712 DEBUG sqlalchemy.pool.impl.NullPool Created new connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0>
DEBUG 2020-12-16 20:33:01,712 log 175879 140374460724800 Created new connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0>
2020-12-16 20:33:01,712 DEBUG sqlalchemy.pool.impl.NullPool Connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0> checked out from pool
DEBUG 2020-12-16 20:33:01,712 log 175879 140374460724800 Connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 0> checked out from pool
INFO 2020-12-16 20:33:20,422 log 175879 140374460724800 Invalidate connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 2> (reason: AdminShutdown:terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
)2020-12-16 20:33:20,422 INFO sqlalchemy.pool.impl.NullPool Invalidate connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 2> (reason: AdminShutdown:terminating connection due to administrator command

DEBUG 2020-12-16 20:33:20,422 log 175879 140374460724800 Closing connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 2>
2020-12-16 20:33:20,422 DEBUG sqlalchemy.pool.impl.NullPool Closing connection <connection object at 0x7fab7a279180; dsn: 'user=tnt_admin password=xxx dbname=tnt_secreg host=127.0.0.1 port=5432', closed: 2>
127.0.0.1 - - [16/Dec/2020 20:33:20] "GET /admin/event/ HTTP/1.1" 500 -
INFO 2020-12-16 20:33:20,455 _internal 175879 140374460724800 127.0.0.1 - - [16/Dec/2020 20:33:20] "GET /admin/event/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/flaskapp/eggs/Flask_RESTful-0.3.8-py3.6.egg/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flaskapp/eggs/Flask_RESTful-0.3.8-py3.6.egg/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/flaskapp/eggs/Flask_Principal-0.4.0-py3.6.egg/flask_principal.py", line 477, in _on_before_request
    identity = loader()
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/core.py", line 515, in _identity_loader
    if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
  File "/home/flaskapp/eggs/Werkzeug-1.0.1-py3.6.egg/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/core.py", line 455, in _user_loader
    user = _security.datastore.find_user(**selector)
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/datastore.py", line 512, in find_user
    return query.filter_by(**kwargs).first()
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3375, in first
    ret = list(self[0:1])
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3149, in __getitem__
    return list(res)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT anon_1."User_id" AS "anon_1_User_id", anon_1."User_firstName" AS "anon_1_User_firstName", anon_1."User_lastName" AS "anon_1_User_lastName", anon_1."User_email" AS "anon_1_User_email", anon_1."User_password" AS "anon_1_User_password", anon_1."User__scopes" AS "anon_1_User__scopes", anon_1."User_last_login_at" AS "anon_1_User_last_login_at", anon_1."User_current_login_at" AS "anon_1_User_current_login_at", anon_1."User_last_login_ip" AS "anon_1_User_last_login_ip", anon_1."User_current_login_ip" AS "anon_1_User_current_login_ip", anon_1."User_login_count" AS "anon_1_User_login_count", anon_1."User_active" AS "anon_1_User_active", anon_1."User_fs_uniquifier" AS "anon_1_User_fs_uniquifier", anon_1."User_confirmed_at" AS "anon_1_User_confirmed_at", anon_1."User_is_superuser" AS "anon_1_User_is_superuser", anon_1."User_is_staff" AS "anon_1_User_is_staff", anon_1."User_is_idissuer" AS "anon_1_User_is_idissuer", anon_1."User_iiid" AS "anon_1_User_iiid", anon_1."User_is_eo" AS "anon_1_User_is_eo", anon_1."User_eoid" AS "anon_1_User_eoid", role_1.id AS role_1_id, role_1.name AS role_1_name, role_1.description AS role_1_description 
FROM (SELECT "User".id AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User".email AS "User_email", "User".password AS "User_password", "User"._scopes AS "User__scopes", "User".last_login_at AS "User_last_login_at", "User".current_login_at AS "User_current_login_at", "User".last_login_ip AS "User_last_login_ip", "User".current_login_ip AS "User_current_login_ip", "User".login_count AS "User_login_count", "User".active AS "User_active", "User".fs_uniquifier AS "User_fs_uniquifier", "User".confirmed_at AS "User_confirmed_at", "User".is_superuser AS "User_is_superuser", "User".is_staff AS "User_is_staff", "User".is_idissuer AS "User_is_idissuer", "User".iiid AS "User_iiid", "User".is_eo AS "User_is_eo", "User".eoid AS "User_eoid" 
FROM "User" 
WHERE "User".fs_uniquifier = %(fs_uniquifier_1)s 
 LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN (roles_users AS roles_users_1 JOIN role AS role_1 ON role_1.id = roles_users_1.role_id) ON anon_1."User_id" = roles_users_1.user_id]
[parameters: {'fs_uniquifier_1': '9dd1167c88f84bd594a690cb6e1b237d', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by zzzeek** [comment]
the logs confirm that your first request seems to not return its connection to the pool , and that at the end of that request, a second connection is made.  These two connections are created within the 20:33:01 timestamp and the ids are:  "connection object at 0x7fab7b002a08" and "connection object at 0x7fab7a279180".   there are no log messages indicating either of these connections are returned to the pool and/or closed.   Then at the 20:33:20 timestamp, 19 seconds later, we see "connection object at 0x7fab7a279180", still checked out now being used for another request where the database has been stopped and it fails.

**Comment by tyctor** [comment]
yes, two connection are in that log, connection 0x7fab7b002a08 is from first request before postgres restart (R1) and connection 0x7fab7a279180 is from second after postgres restart (R2)

just for clarify, calling `session.remove()` (called from Flask-SQLAlchemy) is not closing connection, it is only removing session, am i right?
so `connection.close()` need to be called manually from app, yes?

**Comment by tyctor** [comment]
so I finally found what caused this error
i have factory for creating flask app and db initialisation in separate file
and in factory i had relative import of database file
when i changed import to absolute problem disappear
