### ISSUE TITLE
cx_Oracle db get_isolation_level - ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by tjbergst** [sqlalchemy/sqlalchemy#5786]
**Describe the bug**
SQLAlchemy 1.3.21 has broken some oracle db connections, specifically changes from #5755. Same connection works correctly at <= 1.3.20.

**Expected behavior**
Running `engine.connect()` should succeed without error.

**To Reproduce**
```py
from sqlalchemy import create_engine

conn_string = 'oracle+cx_oracle://USERNAME:PASSWORD@HOST:PORT?service_name=TNS'
engine = create_engine(conn_string)
engine.connect()
```

**Error**

```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/coyotes/sql/db_conn.py", line 82, in create_sql_connection
    connection = engine.connect()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 664, in __connect
    pool.dispatch.first_connect.for_modify(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/event/attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1406, in go
    return once_fn(*arg, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 921, in initialize
    super(OracleDialect_cx_oracle, self).initialize(connection)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/dialects/oracle/base.py", line 1320, in initialize
    super(OracleDialect, self).initialize(connection)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 325, in initialize
    self.default_isolation_level = self.get_isolation_level(
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 956, in get_isolation_level
    cursor.execute(
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: table or view does not exist
(Background on this error at: http://sqlalche.me/e/13/4xp6)
```

**Versions.**
 - OS: Windows 10, RHEL7 (docker), WSL 
 - Python: 3.6.9, 3.8.3
 - SQLAlchemy: 1.3.**21**
 - Database: oracle odbc
 - DBAPI: cx_oracle

**Additional context**
This is the only oracle odbc database I have access to, so I am unable to test other connections.

Thanks!

**Comment by tjbergst** [comment]
Just realized this is a duplicate of #5783, #5784.

**Comment by CaselIT** [comment]
Hi,

It's already solved and we should release a fix shortly since this seems to be affecting a lot of people. In any case thanks for reporting it!
