### ISSUE TITLE
NoSuchModuleError ... dialects.postgres.psycopg2

### ISSUE THREAD

**Issue by transfluxus** [sqlalchemy/sqlalchemy#5799]
**Describe the bug**
cannot create engine for postgres dialect

**Expected behavior**

**To Reproduce**
SQLLAchemy version 1.4.0b1, calling create_engine   with a postgres uri: postgres:// or postgres+psycopg2://

```py
uri = f"postgres+psycopg2://{settings.POSTGRES_USER}:{settings.POSTGRES_PASSWORD.get_secret_value()}" \
      f"@{settings.POSTGRES_HOST}/{settings.POSTGRES_DB}"
try:
    engine = create_engine(uri)  # , pool_pre_ping=True)
    Base.metadata.create_all(engine)
    return engine
except OperationalError:
....
```

**Error**

```
app.db                                   INFO      postgres+psycopg2://pgman:**********@localhost/licci
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 47, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 54, in serve
    config.load()
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/uvicorn/config.py", line 306, in load
    self.loaded_app = import_from_string(self.app)
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 19, in <module>
    from app.setup import setup_all
  File "./app/setup/__init__.py", line 8, in <module>
    from app.services.service_worker import ServiceWorker
  File "./app/services/service_worker.py", line 8, in <module>
    from app.db import Session
  File "./app/db.py", line 48, in <module>
    sessionmaker(autocommit=False, autoflush=False, bind=setup_db())
  File "./app/db.py", line 32, in setup_db
    engine = create_engine(uri, future=True) #, pool_pre_ping=True)
  File "<string>", line 2, in create_engine
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 279, in warned
    return fn(*args, **kwargs)
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 511, in create_engine
    entrypoint = u._get_entrypoint()
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/mnt/SSD/projects/opentek_be/app/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 302, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres.psycopg2
```

**Versions.**
 - OS: ubuntu 20.10
 - Python: 3.8
 - SQLAlchemy: 1.4.0b1
 - Database: postgres
 - DBAPI: psycopg2

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi, 

As indicated in the documentation, the proper uri string is `postgresql` not `postgres`. 
See https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.psycopg2

**Comment by zzzeek** [comment]
"postgres" has been deprecated for many years, see https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-b2b94629c3428a7a3d1e7d10546de36f for removal note

**Comment by CaselIT** [comment]
Moving to discussion
