### ISSUE TITLE
ORM Model With Identical Table Name and secondaryjoin Results in: AttributeError: 'Table' object has no attribute

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [sqlalchemy/sqlalchemy#5805]
**Describe the bug**
A model with a string secondaryjoin fails to initalize 
I'm guessing it relates to https://github.com/sqlalchemy/sqlalchemy/issues/5774

**Expected behavior**
No exception should be thrown and relationships should be properly established.
The secondary relationship outlined below was working until I recently updated.

**To Reproduce**
Setup a postgres database
In the code below fill out 'db settings' and run.
This produces `AttributeError: 'Table' object has no attribute 'shotId'` (Full stack trace below)

```py
import traceback

from sqlalchemy import create_engine, Column, ForeignKey, Integer
from sqlalchemy.orm import Session, relationship, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

##########
# Models #
##########

class Project(Base):
    __tablename__       = 'Projects'
    projectId           = Column(Integer, primary_key=True)

class Shot(Base):    
    __tablename__       = "Shots"
    shotId              = Column(Integer, primary_key=True) 
    projectId           = Column(Integer, ForeignKey('Projects.projectId'))

class RenderOutput(Base):
    __tablename__ = 'RenderOutput'

    renderOutputId               = Column(Integer, primary_key=True)
    shotId                       = Column(Integer, ForeignKey('Shots.shotId'))

class RenderOutputVersion(Base):
    __tablename__             = 'RenderOutputVersions'

    renderOutputVersionId     = Column(Integer, primary_key=True)
    renderOutputId            = Column(Integer, ForeignKey('RenderOutput.renderOutputId'))

    # The secondary here triggers the error
    project = relationship('Project',
                            secondary='join(RenderOutput, Shot, RenderOutput.shotId==Shot.shotId).'
                                      'join(Project, Shot.projectId==Project.projectId)',
                            primaryjoin='RenderOutputVersion.renderOutputId==RenderOutput.renderOutputId',
                            secondaryjoin='RenderOutput.shotId==Shot.shotId',
                            uselist=False,
                            viewonly=True
                            )

#################
# DB Connection #
#################

# Fill out db settings
user = None
pw = None
address = None
port = None
db_name = None

engine = create_engine(f'postgresql://{user}:{pw}@{address}:{port}/{db_name}')
Session = sessionmaker(bind=engine)
session = Session()
Base.metadata.create_all(engine)

# Exception here
f = session.query(RenderOutputVersion).first()
```

<details>
<summary>Stack Trace</summary>

```
Traceback (most recent call last):
  File "\\192.168.15.130\projects\__Tests\Python\sqlalchemy\app.py", line 56, in <module>
    f = session.query(RenderOutputVersion).first()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2039, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 171, in __init__
    self._set_entities(entities)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 178, in _set_entities
    self._raw_columns = [
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 179, in <listcomp>
    coercions.expect(
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\sql\coercions.py", line 154, in expect
    insp._post_inspect
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1162, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2101, in _post_inspect
    configure_mappers()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3364, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1894, in _post_configure_properties
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 226, in init
    self.do_init()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2135, in do_init
    self._process_dependent_arguments()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2169, in _process_dependent_arguments
    self._clsregistry_resolve_arg(
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 408, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
AttributeError: 'Table' object has no attribute 'shotId'
(.venv) PS Microsoft.PowerShell.Core\FileSystem::\\192.168.15.130\projects\__Tests\Python\sqlalchemy>  cd '\\192.168.15.130\projects\__Tests\Python\sqlalchemy'; & 'C:\Users\Luke\envs\.venv\Scripts\python.exe' 'c:\Users\Luke\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\launcher' '57962' '--' '\\192.168.15.130\projects\__Tests\Python\sqlalchemy\app.py' 
Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Luke\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Luke\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Luke\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\\192.168.15.130\projects\__Tests\Python\sqlalchemy\app.py", line 52, in <module>
    f = session.query(RenderOutputVersion).first()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2039, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 171, in __init__
    self._set_entities(entities)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 178, in _set_entities
    self._raw_columns = [
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 179, in <listcomp>
    coercions.expect(
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\sql\coercions.py", line 154, in expect
    insp._post_inspect
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1162, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2101, in _post_inspect
    configure_mappers()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3364, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1894, in _post_configure_properties
    prop.init()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 226, in init
    self.do_init()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2135, in do_init
    self._process_dependent_arguments()
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2169, in _process_dependent_arguments
    self._clsregistry_resolve_arg(
  File "C:\Users\Luke\envs\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 408, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
AttributeError: 'Table' object has no attribute 'shotId'
```
</summary>

**Versions.**
 - OS: Windows 10
 - Python: 3.6.9
 - SQLAlchemy: 1.4.0b1
 - Database: postgres
 - DBAPI: psycopg2

**Comment by zzzeek** [comment]
hey there -

unfortuantely "secondary" expects a string table name and in #5774 we fixed the issue where class and table name are the same, table has to be favored.  the join condition you're putting into "secondary" is way outside of what was anticipated for the string use case so  unfortunately you need to change your code to use a lambda, not a string, to maintain compatibility.   sorry!

**Comment by Anti-Distinctlyminty** [comment]
@zzzeek Thank you for the prompt reply. I'm having issues locating how to do such a join in the docs. Could you point me in the right direction or show a working example for the above situation?

**Comment by zzzeek** [comment]
hey there -

lambda just means use a Python lambda like this:
```
from sqlalchemy import join

class RenderOutputVersion(Base):
    __tablename__             = 'RenderOutputVersions'

   # ...
    # The secondary here triggers the error
    project = relationship('Project',
                            secondary=lambda: join(RenderOutput, Shot, RenderOutput.shotId==Shot.shotId).
                                      join(Project, Shot.projectId==Project.projectId),
                                     ...

```

lambda also isn't needed if you can have Shot / Project / RenderOutput imported when you define this model.  Or you can add the relationship later:

```
class RenderOutput...
class Shot...
class Project...
class RenderOutputVersion...

# later, when you can import everything needed
RenderOutputVersion.project = relationship(Project, secondary=join(RenderOutput, Short, ...))
```
