### ISSUE TITLE
Problem with using dot-separated names for relationship targets

### ISSUE THREAD

**Issue by quantumdark** [sqlalchemy/sqlalchemy#5806]
**Describe the bug**
When I use dot-separated names as relationship targets and the models are in different files it raises an error

**Expected behavior**
Doesn't raise an error and works the same way as when models are defined in the same file

**To Reproduce**
base.py
```py
from sqlalchemy.ext.declarative.api import declarative_base

Base = declarative_base()
```

a.py
```py
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import Integer

from base import Base


class A(Base):
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)

```

test.py
```py
from sqlalchemy import Column, ForeignKey, Integer
from sqlalchemy.orm import relationship

import a  # noqa: F401
from base import Base


class B(Base):

    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(Integer, ForeignKey("a.id"))
    a = relationship("a.A")


B() # raises AttributeError
```

**Error**

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    B()
  File "<string>", line 2, in __init__
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 388, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 214, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3411, in _event_on_first_init
    configure_mappers()
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3299, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1965, in _post_configure_properties
    prop.init()
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 197, in init
    self.do_init()
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2077, in do_init
    self._process_dependent_arguments()
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2148, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 987, in __getattr__
    return self._fallback_getattr(key)
  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 961, in _fallback_getattr
    raise AttributeError(key)
AttributeError: entity
```

**Additional information**
When I use it like that it doesn't raise an error:
```py
from a import A
#....
   a = relationship("A")
```

I tracked it down to this code but I don't know why it only happens when there's more than one file, maybe has something to do with the current strategy for the relationship property:
```py
from sqlalchemy import util

class Foob(util.MemoizedSlots):
    __slots__ = ("foo",)

    def _memoized_method_foo(self):
        print("memoized")
        return "foobar"

    @util.memoized_property
    def bar(self):
        return "bar"


f1 = Foob()
f1.foo()
f1.bar() # error!
```

**Versions.**
 - Python: 3.7
 - SQLAlchemy: 1.3.22

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

as you might have guessed it's assuming that the name "a" is the Table object named "a", and not the module "a".  I would advise using a lambda, not a string name for this relationship:

```
def import_a():
    from myapp import a
    return a.A

class B:
 # ...
  a = relationship(import_a)


```

we will have to adjust the resolution logic for the case of the class target of a relationship but this has a high chance of regressions for people so it has to be 1.4.
