### ISSUE TITLE
Commit works fine but throws exception AttributeError: 'NoneType' object has no attribute 'accepts_scalar_loader'

### ISSUE THREAD

**Issue by ownchoice** [sqlalchemy/sqlalchemy#5862]
**Describe the bug**
After doing a commit, I get an AttributeError exception but data is saved just fine to the DB. Everything looks like it works, but the program still crashes and gives me this exception.
```
File "C:\Users\regularuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\instrumentation.py", line 122, in <listcomp>
    if attr.impl.accepts_scalar_loader
AttributeError: 'NoneType' object has no attribute 'accepts_scalar_loader'
```

**Expected behavior**
Doing a commit should not throw an exception if it's successful.

**To Reproduce**
I'm not able to reproduce it in an isolated way, it just doesn't crash on my other attempts to reproduce this same behavior. I've tried saving data to the same DB and table but it works just fine.

```py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session
from blog_db_schemas import (
    Articles,
    RelatedArticle
)
from blog_utils import get_related_articles


engine = create_engine("db url", pool_size=1)
session_factory = sessionmaker(bind=engine)
Session = scoped_session(session_factory)
session = Session()

articles = session.query(Articles).all()

for count, article in enumerate(articles):
    print(f"Processing ({count+1}/{len(articles)}): {article.title}")
    related_by_tags = get_related_articles(article.tags)
    for post in related_by_tags:
        new_row = RelatedArticle(title=post[0], image=post[1])
        new_row.related_to = article

        session.add(new_row)
        session.commit()

```

**Error**

```
Traceback (most recent call last):
  File "C:\Users\adminuser\git_repos\project045\dev\main.py", line 343, in <module>
    main()
  File "C:\Users\adminuser\git_repos\project045\dev\main.py", line 338, in main
    session.commit()
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 514, in commit
    self._remove_snapshot()
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 396, in _remove_snapshot
    s._expire(s.dict, self.session.identity_map._modified)
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\state.py", line 586, in _expire
    for impl in self.manager._scalar_loader_impls
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\instrumentation.py", line 119, in _scalar_loader_impls
    [
  File "C:\Users\adminuser\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\instrumentation.py", line 122, in <listcomp>
    if attr.impl.accepts_scalar_loader
AttributeError: 'NoneType' object has no attribute 'accepts_scalar_loader'
```

**Versions.**
 - OS: Windows 10 Pro 20H2
 - Python: 3.9.0
 - SQLAlchemy: 1.3.22
 - Database: PostgreSQL
 - DBAPI: postgresql+psycopg2

**Additional context**
The data seems to be saved correctly to the DB and everything looks fine, but I still get this error when executing my code.

**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

the stack trace looks like a bug but I have no information on how to reproduce it.   as you've stated you can't reproduce it either I can only guess that perhaps you have mappers that aren't configured or have failed to compile.   load your entire model and call sqlalchemy.orm.configure_mappers() .   look carefully for any warnings or errors.     please share complete information including Articles / RelatedArticle mappings as well as queries performed in get_related_articles().

**Comment by slavaivanov** [comment]
I had the same problem - program crushed and identical exception thrown. All because of the typo in relationship definition: 
coordinated_deals = **company_deals =** db.relationship(... 
After changing it to 
coordinated_deals = db.relationship(... 
every thing works as expected.

**Comment by CaselIT** [comment]
If you can produce a reproducible example can you open a new issue so we can investigate?
thanks!
