### ISSUE TITLE
TypeError when creating model instance in scrapy pipeline

### ISSUE THREAD

**Issue by JDRanpariya** [sqlalchemy/sqlalchemy#5872]
**Describe the bug**

When creating an instance of model defined in models.py It's giving `TypeError: Scene() got an unexpected keyword argument 'studio'` Where Scene is model

**Expected behavior**

It should accept the following line: `scene = Scene(**item)` and add that to database.

**To Reproduce**
I've seen some articles where It works fine but in my case Why it' showing unexpected keyword error
Proof 1: [here](http://newcoder.io/scrape/part-4/)
Proof 2: [here](https://towardsdatascience.com/a-minimalist-end-to-end-scrapy-tutorial-part-iii-bcd94a2e8bf3)
Proof 3: [here](https://www.reddit.com/r/learnpython/comments/chp6hf/how_to_insert_into_my_sqlite_database_or_update/)
In third case `quotedb = QuoteDB()` is working but in my case `scene = Scene()` is showing following error `TypeError: Scene() missing 1 required positional argument: 'DeclarativeBase'`

models.py
```models.py
from sqlalchemy import create_engine, MetaData, Column, Text, Integer, String, DateTime, ARRAY, Time, Float, Table
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.engine.url import URL
from abc_scraper import settings

DeclarativeBase = declarative_base()

def db_connect():
    """
    Performs database connection using database settings from settings.py.
    Returns sqlalchemy engine instance
    """
    return create_engine(URL(**settings.DATABASE))

def create_scenes_table(engine):
    """"""
    DeclarativeBase.metadata.create_all(engine)
    
def Scene(DeclarativeBase):
    """ c """
    __tablename__ = 'scenes'

    id = Column(Integer, primary_key=True)
    studio = Column('studio', String(80))
    parent_studio = Column('parent_studio', String, nullable=True)
    title = Column('title', String(100))
    thumbnail_url = Column('thumbnail_url', String, nullable=True)
    preview_url = Column('preview_url', String, nullable=True)
    performers = Column("performers", ARRAY(String))
    director = Column('director', String(80), nullable=True)
    length = Column('length', Time, nullable=True)
    description = Column('description', Text(), nullable=True)
    release_date = Column('release_date', DateTime, nullable=True)
    native_rating = Column('native_rating', Float, nullable=True)
    gallary_urls = Column("gallary_urls", ARRAY(String), nullable=True)
```
pipelines.py
```pipelines.py
from sqlalchemy.orm import sessionmaker
from abc_scraper.models import Scene, db_connect, create_scenes_table


class abcPipeline(object):
    """abc pipeline for storing scraped items in the database"""
    def __init__(self):
        """
        Initializes database connection and sessionmaker.
        Creates deals table.
        """
        engine = db_connect()
        create_scenes_table(engine)
        self.Session = sessionmaker(bind=engine)


    def process_item(self, item, spider):
        """Save deals in the database.

        This method is called for every item pipeline component.

        """
        session = self.Session()
       
        scene = Scene(**item)
        try:
            if session.query(Scene).filter_by(title=item['title']).first():
                pass
            else:
                session.add(scene)
                session.commit()
        except:
            session.rollback()
            raise
        finally:
            session.close()

        return item
```
**Error**

```
Traceback (most recent call last):
  File "c:\users\user\.virtualenvs\web_scraping-e_vvhamk\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\user\.virtualenvs\web_scraping-e_vvhamk\lib\site-packages\scrapy\utils\defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "D:\Projects\Web_Scraping\path_to_scraper\abc_scraper\pipelines.py", line 39, in process_item
    scene = Scene(**item)
TypeError: Scene() got an unexpected keyword argument 'studio'
```

**Versions.**
 - OS: Windows10
 - Python: 3.8.3
 - SQLAlchemy: 1.3.22
 - Database: Postgresql
 - DBAPI: 

**Additional context**

I've spent around 5 hr's on reading articles and stackoverflow but got nothing. So please look into this.
Regards, 
JDRanpariya

**Have a nice day!**

**Comment by Jesse-Bakker** [comment]
Your `Scene` is currently a function taking an argument called `DeclarativeBase`, where you probably meant it to be a class inheriting from `DeclarativeBase`. So in short: `def Scene` -> `class Scene`
