### ISSUE TITLE
1.4.0b1  Dataclasses with Declarative Table not working

### ISSUE THREAD

**Issue by leric** [sqlalchemy/sqlalchemy#5907]
Dataclasses with Declarative Table as described in [this example](https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#example-two-dataclasses-with-declarative-table) will raise exception:

**To Reproduce**

```py
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List
from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.orm import registry, relationship

mapper_registry = registry()

@mapper_registry.mapped
@dataclass
class User:
    __tablename__ = "user"
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
    name: str = field(default=None, metadata={"sa": Column(String(50))})
    fullname: str = field(default=None, metadata={"sa": Column(String(50))})
    nickname: str = field(default=None, metadata={"sa": Column(String(12))})
    addresses: List[Address] = field(
        default_factory=list, metadata={"sa": relationship("Address")}
    )

@mapper_registry.mapped
@dataclass
class Address:
    __tablename__ = "address"
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
    user_id: int = field(
        init=False, metadata={"sa": Column(ForeignKey("user.id"))}
    )
    email_address: str = field(
        default=None, metadata={"sa": Column(String(50))}
    )

if __name__ == '__main__':
    print(mapper_registry.metadata.tables)


```

**Error**

```
Traceback (most recent call last):
  File "/opt/apihub/juheapi/test.py", line 19, in <module>
    class User:
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 572, in mapped
    _as_declarative(self, cls, cls.__dict__)
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 125, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 176, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 313, in __init__
    self._early_mapping(mapper_kw)
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 199, in _early_mapping
    self.map(mapper_kw)
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 831, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 279, in warned
    return fn(*args, **kwargs)
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 677, in __init__
    self._configure_pks()
  File "/opt/apihub/juheapi/.venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1337, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper mapped class User->user could not assemble any primary key columns for mapped table 'user'
```

**Versions.**
 - OS: MacOS 11.1
 - Python: 3.8.2
 - SQLAlchemy: 1.4.0b1
 - Database: sqlite
 - DBAPI:

**Comment by zzzeek** [comment]
hey there -

my apologies, that's a great test case you have there, it works fine with git master, that is, if you install from https://github.com/sqlalchemy/sqlalchemy/ .  the example you refer towards will work in version 1.4.0b2 which I am rushing to get released ASAP.

**Comment by zzzeek** [comment]
1.4.0b2 is released.
