### ISSUE TITLE
primary_key=True, in combination with naming_convention, can result in a blank name attribute on the constraint object.

### ISSUE THREAD

**Issue by tcatut** [sqlalchemy/sqlalchemy#5919]
**Describe the bug**
We have several declarative_base, and associated Table classes, which are failing on `__table__.create()`.  Example class definition and traceback will be below.

I was able to examine the traceback and add a print statement at line 3238 in `sqlalchemy/sql/compiler.py`.  From this I was able to see that `constraint.name` passes the None check, but is being created as a blank string.  This results in the traceback below.

I did try a few things and found two work arounds, but I feel like these shouldn't be needed.

The first one is to explicitly declare `PrimaryKeyConstraint(idx)` into the class definition, instead of relying on `primary_key=True` in the Column definition.  If the constraint object is explicitly declared in the class, then it gets a proper name attribute and works without exception.

The other work around is to remove our naming_convention definition.  It appears this exception ONLY happens when using both `primary_key=True` and naming_convention together.  Obviously, for us, removing the naming_convention isn't an option.

**Expected behavior**
It's my understanding that `primary_key=True` is supposed to form a complete PrimaryKeyConstraint object automatically, and we should not have to explicitly declare this in every table class.

If nothing else, you should probably have some blank string protection here.  It would be nice to get a more descriptive error message.

**To Reproduce**
```
import sqlalchemy
from sqlalchemy import Column, String, TIMESTAMP, text, MetaData, PrimaryKeyConstraint
from sqlalchemy.dialects.mysql import BIGINT
from sqlalchemy.ext.declarative import declarative_base

naming_convention={
    'ix': '%(column_0N_name)s',
    'uq': '%(column_0N_name)s',
    'ck': '%(column_0N_name)s',
    'fk': 'fk_%(table_name)s_%(referred_table_name)s',
    'pk': '%(column_0N_name)s',
}

ADS_EQUIP_DATA_base = declarative_base(metadata=MetaData(naming_convention=naming_convention))
metadata = ADS_EQUIP_DATA_base.metadata


class ADS_EQUIP_DATA(ADS_EQUIP_DATA_base):
    __tablename__ = 'ADS_EQUIP_DATA'
    __table_args__ = {'schema': 'ADS_EQUIP_CNTL', 'mysql_engine': 'InnoDB'}

    deviceId = Column(String(32), index=True)
    input_column = Column('input', String(32))
    generalType = Column(String(32), index=True)
    category = Column(String(32))
    station = Column(String(32))
    slot = Column(String(32))
    columnType = Column('type', String(32))
    activityTime = Column(TIMESTAMP, nullable=False, index=True,
                          server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    idx = Column(BIGINT(unsigned=True), primary_key=True, nullable=False, autoincrement=True)
    # PrimaryKeyConstraint(idx)  # Uncomment this line and the exception goes away.

connection_string = 'mysql://{user}:{password}@{host}/'.format(user=user, password=password, host=host)
engine = sqlalchemy.create_engine(connection_string)

engine.execute("CREATE DATABASE IF NOT EXISTS ADS_EQUIP_CNTL")
engine.execute("USE ADS_EQUIP_CNTL")

ADS_EQUIP_DATA.__table__.create(engine)
```

**Error**

```
Traceback (most recent call last):
  File "/home/kshutt/.config/JetBrains/PyCharm2020.3/scratches/scratch_4.py", line 41, in <module>
    table.__table__.create(engine)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 928, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1066, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2961, in visit_create_table
    _include_foreign_key_constraints=create.include_foreign_key_constraints,  # noqa
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3012, in create_table_constraints
    for constraint in constraints
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3009, in <genexpr>
    p
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3019, in <genexpr>
    or not getattr(constraint, "use_alter", False)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1928, in visit_primary_key_constraint
    constraint
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3238, in visit_primary_key_constraint
    formatted_name = self.preparer.format_constraint(constraint)
  File "<string>", line 1, in <lambda>
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3779, in format_constraint
    return self.quote(name)
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3701, in quote
    if self._requires_quotes(ident):
  File "/home/kshutt/mandate/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 3614, in _requires_quotes
    or value[0] in self.illegal_initial_characters
IndexError: string index out of range
```

**Versions.**
 - OS:  CentOS Linux release 7.9.2009 (Core)
 - Python:  Python 2.7.5
 - SQLAlchemy:  1.3.23
 - Database:  mysql  Ver 14.14 Distrib 5.7.32-35, for Linux (x86_64) using  6.2
 - DBAPI:  MySQL-python 1.2.5, mysqlclient 1.4.6

**Additional context**

**Have a nice day!**

**Comment by tcatut** [comment]
Interesting... I just did another test on some tables that have UNIQUE fields, and it appears these work as expected when using `unique=True`.  It creates a UniqueConstraint object that works just fine.  

The behaviour here seems to be specific to the PRIMARY KEY constraint object only.

**Comment by zzzeek** [comment]
hi there -

the bug as you've likely surmised is limited to the "column" based conventions.   the fix will merge in a few hours but a new SQLAlchemy release was not planned for a few weeks.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Accommodate column-based naming conventions for pk constraint** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2533

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Accommodate column-based naming conventions for pk constraint** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2534

**Comment by tcatut** [comment]
Yup... that looks like exactly what we're seeing.  Thanks for the update and we look forward to seeing this in next release.

**Comment by zzzeek** [comment]
> Interesting... I just did another test on some tables that have UNIQUE fields, and it appears these work as expected when using `unique=True`. It creates a UniqueConstraint object that works just fine.
> 
> The behaviour here seems to be specific to the PRIMARY KEY constraint object only.

it's because Table always has a PrimaryKeyConstraint object set up, and it creates this before the columns have been added to the table.   so the fix has to accommodate both for this empty state as well as the changing state as new columns are added to the table, which can happen at any time.
