### ISSUE TITLE
sql.func().in_(...) fails to compile in 1.4

### ISSUE THREAD

**Issue by squaresmile** [sqlalchemy/sqlalchemy#5934]
**Describe the bug**
`sql.func().in_(...)` fails to compile

**Expected behavior**
`sql.func().in_(...)` to works.

**To Reproduce**
```py
import sqlalchemy
from sqlalchemy import Table, Column, Integer
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.sql import select, func

print(f"{sqlalchemy.__version__=}")

metadata = sqlalchemy.MetaData()
test_table = Table(
    "test",
    metadata,
    Column("numbers", ARRAY(Integer))
)

engine = sqlalchemy.create_engine("postgresql://user:password@localhost:5432/test")
metadata.create_all(engine)

with engine.connect() as conn:
    data = [{"numbers": [1,2,3]}, {"numbers": [1,2]}, {"numbers": [1,2,3,4]}]
    conn.execute(test_table.insert(), data)

    stmt = select([test_table]).where(func.array_length(test_table.c.numbers, 1).in_((2,3)))
    result = conn.execute(stmt).fetchall()
```

**Error**

```
sqlalchemy.__version__='1.4.0b2'
Traceback (most recent call last):
  File "sql_test.py", line 26, in <module>
    stmt = select([test_table]).where(func.array_length(test_table.c.numbers, 1).in_((2,3)))
  File ".venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File ".venv\lib\site-packages\sqlalchemy\sql\elements.py", line 827, in operate
    return op(self.comparator, *other, **kwargs)
  File ".venv\lib\site-packages\sqlalchemy\sql\operators.py", line 1395, in in_op
    return a.in_(b)
  File ".venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File ".venv\lib\site-packages\sqlalchemy\sql\type_api.py", line 73, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File ".venv\lib\site-packages\sqlalchemy\sql\default_comparator.py", line 155, in _in_impl
    seq_or_selectable = coercions.expect(
  File ".venv\lib\site-packages\sqlalchemy\sql\coercions.py", line 167, in expect
    resolved = impl._literal_coercion(
  File ".venv\lib\site-packages\sqlalchemy\sql\coercions.py", line 541, in _literal_coercion
    return expr._bind_param(operator, element, expanding=True)
TypeError: _bind_param() got an unexpected keyword argument 'expanding'
```

**Versions.**
 - OS: Windows 10
 - Python: 3.9.1
 - SQLAlchemy: 1.4.0b2
 - Database: Postgresql 13
 - DBAPI: psycopg2

**Additional context**
Adding `expanding` to [the function](https://github.com/sqlalchemy/sqlalchemy/blob/89dc4562adb38367ee5fabbcc04ee44968af4906/lib/sqlalchemy/sql/functions.py#L890) solves the error.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**test Function(?:Element)._bind_param() with in_()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2582

**Comment by zzzeek** [comment]
thanks for the report!
