### ISSUE TITLE
insert values to column named with parenthese fail

### ISSUE THREAD

**Issue by holymonson** [sqlalchemy/sqlalchemy#5941]
**Describe the bug**
If a column named with parenthese, sqlalchemy will generate SQL statement like `INSERT INTO test ("ab(cd)ef") VALUES (%(ab(cd)ef)s)`, and it fails.

**Expected behavior**
Able to insert column named like `ab(cd)ef`.

**To Reproduce**
```py
from sqlalchemy import Column, Integer, MetaData, Table, create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine("postgresql://localhost/test", echo=True)
metadata = MetaData(engine)
table = Table("test", metadata, Column("ab(cd)ef", Integer, primary_key=True))
metadata.create_all()

engine.execute(table.insert(), {"ab(cd)ef": 123})
```

**Error**

```
2021-02-14 00:20:38,437 INFO sqlalchemy.engine.base.Engine INSERT INTO test ("ab(cd)ef") VALUES (%(ab(cd)ef)s)
2021-02-14 00:20:38,437 INFO sqlalchemy.engine.base.Engine {'ab(cd)ef': 123}
2021-02-14 00:20:38,437 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/Caskroom/miniconda/base/envs/mas/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
KeyError: 'ab(cd'

```

**Versions.**
 - OS: macos
 - Python: 3.8
 - SQLAlchemy: 1.3.23
 - Database: postgresql 13.2
 - DBAPI: psycopg2

**Additional context**
column named with parenthese  is valid, at least in postgresql to my knowledge.

**Have a nice day!**

**Comment by zzzeek** [comment]
this is hard to fix so no timeline on this, I would recommend using columns with less unusual names for now.

**Comment by zzzeek** [comment]
there's documentation on this issue as well here: https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#bound-parameter-styles

> The default parameter style for the psycopg2 dialect is “pyformat”, where SQL is rendered using %(paramname)s style. This format has the limitation that it does not accommodate the unusual case of parameter names that actually contain percent or parenthesis symbols; as SQLAlchemy in many cases generates bound parameter names based on the name of a column, the presence of these characters in a column name can lead to problems.

the most immediate workaround is to put a ".key" in your Column:

    Column("ab(cd)ef", Integer, primary_key=True, key="abc")

that key will be used for the parameter name.


There does seem to be some escaping of percent signs in bound parameters occurring in 1.4, so I have hope that I implemented something for this that maybe we can drop the parenthesis into also so that 1.4 can fix this completely.

**Comment by zzzeek** [comment]
looks like it is #5653.

**Comment by zzzeek** [comment]
oh perfect, this is just what I was going to do, it's already done: "generalized cx_Oracle's quoted_bind_names facility into the compiler
  itself, and leveraged this for the psycopg2 dialect's issue with
  percent signs in names as well. "

great minds think alike

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**expand and further generalize bound parameter translate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2587
