### ISSUE TITLE
'ForeignKey.argument_for' fails in misleading manner

### ISSUE THREAD

**Issue by stephenfin** [sqlalchemy/sqlalchemy#5944]
**Describe the bug**

For historical reasons, the OpenStack Nova database migrations [sets a name on some `ForeignKey` constraints for MySQL but lets PostgreSQL generate its own names](https://github.com/openstack/nova/blob/a7dd1f8881484ba0bf4270dd48109c2be142c333/nova/db/sqlalchemy/migrate_repo/versions/402_train.py#L1589-L1601). I'm trying to clean things up somewhat, and stumbled upon the [`argument_for`](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.base.DialectKWArgs.argument_for) method allowing you to specify dialect-specific parameters. I can use this to add a `mysql_name` parameter that should ensure only this backend gets the manually specified names. My first attempt set this on `ForeignKey`, like so:

```
sa.ForeignKey.argument_for('mysql', 'name', None)
```

However, this fails with the following error message:

```
sqlalchemy.exc.ArgumentError: Argument 'mysql_name' is not accepted by dialect 'mysql' on behalf of <class 'sqlalchemy.sql.schema.ForeignKeyConstraint'>
```

It took me a while, but I eventually realized that I could change this to:

```
sa.ForeignKeyConstraint.argument_for('mysql', 'name', None)
```

and everything would "just work".

**Expected behavior**

I expected either the `ForeignKey.argument_for` implementation to work or, if this is not possible (I'm not familar with the guts of SQLA), for the call to fail outright with an indication to use `sa.ForeignKeyConstraint`. At a minimum, some reference to this in the docs would prevent head banging, though the documentation for this API is generic enough that I couldn't find any way to easily slot this in (I did try).

**To Reproduce**

Nova still uses `sqlalchemy-migrate` (I'm working on it!) so this is missing migrate-related boilerplate, but it should give you the general gist of what I was trying:

```py
import sqlalchemy as sa

sa.ForeignKey.argument_for('mysql', 'name', None)

instances = sa.Table(
    'instances', meta,
    sa.Column('id', sa.Integer, primary_key=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
)

instance_extra = sa.Table(
    'instance_extra', meta,
    sa.Column('id', sa.Integer, primary_key=True, nullable=False),
    sa.Column(
        'instance_uuid', sa.String(length=36),
        sa.ForeignKey(
            'instances.uuid',
            mysql_name='fk_instance_extra_instance_uuid'),
        nullable=False),
)
```

**Error**

```
+ python manage.py upgrade --database sqlite:///nova.db
401 -> 402...
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    main(debug='False', repository='.')
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/nova/.tox/py36/lib/python3.6/site-packages/migrate/versioning/script/py.py", line 154, in run
    script_func(engine)
  File "./versions/402_train.py", line 264, in upgrade
    mysql_charset='utf8'
  File "<string>", line 2, in __new__
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 560, in __new__
    metadata._remove_table(name, schema)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 555, in __new__
    table._init(name, metadata, *args, **kw)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 654, in _init
    self._init_items(*args)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 118, in _init_items
    spwd(self)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/base.py", line 462, in _set_parent_with_dispatch
    self.dispatch.after_parent_attach(self, parent)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 2207, in _set_table
    **self._unvalidated_dialect_kw
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 3327, in __init__
    **dialect_kw
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 2887, in __init__
    self._validate_dialect_kwargs(dialect_kw)
  File "/nova/.tox/py36/lib64/python3.6/site-packages/sqlalchemy/sql/base.py", line 315, in _validate_dialect_kwargs
    % (k, dialect_name, self.__class__)
sqlalchemy.exc.ArgumentError: Argument 'mysql_name' is not accepted by dialect 'mysql' on behalf of <class 'sqlalchemy.sql.schema.ForeignKeyConstraint'>
```

**Versions.**

 - OS: Fedora 33
 - Python: 3.6
 - SQLAlchemy: 1.3.22
 - Database: MySQL
 - DBAPI: `PyMySQL==1.0.2`

**Comment by stephenfin** [comment]
Looking at the schema diff, it appears the `ForeignKeyConstraint.argument_for` attempt doesn't actually work. The `mysql_name` parameter is ignored and auto-generated names are used instead :disappointed:

**Comment by stephenfin** [comment]
At the expense of making this sound like a usage question (which I don't think it is), I've been able to achieve this via a custom compile rule:

```
@compiler.compiles(sa.ForeignKeyConstraint, 'postgresql')
def process(element, compiler, **kw):
    element.name = None
    return compiler.visit_foreign_key_constraint(element, **kw)
```

Might be helpful in case anyone else stumbles upon this.

**Comment by zzzeek** [comment]
hiya -

the error message is referring to the [ForeignKeyConstraint](https://docs.sqlalchemy.org/en/13/core/constraints.html?highlight=foreignkeyconstraint#sqlalchemy.schema.ForeignKeyConstraint) class, not ForeignKey.  if you apply your custom argument name to ForeignKeyConstraint, the script raises no error, as expected:

    sa.ForeignKeyConstraint.argument_for('mysql', 'name', None)

that said, the purpose of argument_for() is to provide for new backend-specific arguments to be accepted, which then have to be implemented with the compiler.    so in this case, you could implement as:
```python

sa.ForeignKeyConstraint.argument_for('mysql', 'name', None)

@compiler.compiles(sa.ForeignKeyConstraint, 'mysql')
def process(element, compiler, **kw):
    if not element.name:
        mysql_name = element.dialect_options['mysql']['name']
        if mysql_name:

            element.name = mysql_name
    return compiler.visit_foreign_key_constraint(element, **kw)

```


it looks like what you were expecting was, that any arbitrary existing kwarg on ForiegnKeyConstraint could be somehow dialect-qualified to only take effect in some cases, in the manner as `TypeEngine.with_variant()`.  But such a feature would need to work similarly to `with_variant()` so that the entire object can be constructed individually; there was discussion about this at #5461 but it hasn't gone anywhere.

**Comment by stephenfin** [comment]
> it looks like what you were expecting was, that any arbitrary existing kwarg on ForiegnKeyConstraint could be somehow dialect-qualified to only take effect in some cases, in the manner as `TypeEngine.with_variant()`.

That's exactly what I was expecting, but that was based on thinking that `length` was a standard argument for `Index` which I now realize isn't true.

> But such a feature would need to work similarly to `with_variant()` so that the entire object can be constructed individually; there was discussion about this at #5461 but it hasn't gone anywhere.

Gotcha. Okay, this was more usage question'y that I was hoping for (sorry!) but the custom compile rule approach should do the trick. I'll proceed with that. Thanks, @zzzeek !
