### ISSUE TITLE
joincondition graceful degrade for noreferencedtable fails if subject table is a join or other composition

### ISSUE THREAD

**Issue by satodaiki** [sqlalchemy/sqlalchemy#5952]
**Versions**
 - OS: MacOS BigSur 11.1
 - Python: 3.8.0
 - SQLAlchemy: 1.3.22
 - Database: Postgresql = 9.6.20
 - DBAPI: psycopg2 = 2.8.6

## Description

Hello.

I'm having trouble generating a query and executing it, so I'd like to ask you a question.

Execution of the following query will fail.

```python
results = session.query(
    Parent.id,
    TestOne.id,
    TestTwo.id,
).outerjoin(
    TestOne,
    Parent.id == TestOne.parent_id
).outerjoin(
    TestTwo,
    Parent.id == TestTwo.parent_id
).all()
```

When I do this, I get the following error:

```
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2416: in outerjoin
    return self._join(
<string>:2: in _join
    ???
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/base.py:227: in generate
    fn(self, *args[1:], **kw)
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2587: in _join
    self._join_left_to_right(
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2611: in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2693: in _join_determine_implicit_left_side
    indexes = sql_util.find_left_clause_to_join_from(
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/util.py:151: in find_left_clause_to_join_from
    elif Join._can_join(f, s) or onclause is not None:
../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py:995: in _can_join
    constraints = cls._joincond_scan_left_right(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'sqlalchemy.sql.selectable.Join'>, a = <sqlalchemy.orm.util._ORMJoin at 0x1034f6670; Join object on %(4349806192 device)s(4349806192) and device_to_model_version(4349383056)>
a_subset = Table('device_to_model_version', MetaData(bind=None), Column('id', Integer(), table=<device_to_model_version>, primary...g(), table=<device_to_model_version>), Column('create_time', DateTime(), table=<device_to_model_version>), schema=None)
b = Table('device_to_solution_version', MetaData(bind=None), Column('id', Integer(), table=<device_to_solution_version>, p...able=<device_to_solution_version>), Column('create_time', DateTime(), table=<device_to_solution_version>), schema=None)
consider_as_foreign_keys = None

    @classmethod
    def _joincond_scan_left_right(
        cls, a, a_subset, b, consider_as_foreign_keys
    ):
        constraints = collections.defaultdict(list)
    
        for left in (a_subset, a):
            if left is None:
                continue
            for fk in sorted(
                b.foreign_keys, key=lambda fk: fk.parent._creation_order
            ):
                if (
                    consider_as_foreign_keys is not None
                    and fk.parent not in consider_as_foreign_keys
                ):
                    continue
                try:
                    col = fk.get_referent(left)
                except exc.NoReferenceError as nrte:
>                   if nrte.table_name == left.name:
E                   AttributeError: '_ORMJoin' object has no attribute 'name'

../../../../Library/Caches/pypoetry/virtualenvs/[my-directory-path]-LvS6Fldc-py3.8/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py:1024: AttributeError
```

Also, for some reason, the following query can be executed.

```python
results = session.query(
    Parent.id,
    TestOne.id,
).outerjoin(
    TestOne,
    Parent.id == TestOne.parent_id
).all()
```

The definition of each model is as follows.(Columns are omitted a little.)

```python
class Parent(Base):
    __tablename__="parent"
    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text('UUID_GENERATE_V4()'))
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)
```

```python
class TestOne(Base):
    __tablename__="test_one"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID, ForeignKey('parent.id'))
    create_time = Column(DateTime)
```

```python
class TestTwo(Base):
    __tablename__="test_two"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID, ForeignKey('parent.id'))
    create_time = Column(DateTime)
```

The SQL query I want to execute is fixed and looks like this:

```sql
SELECT
  *
FROM
  device 
LEFT OUTER JOIN
  device_to_solution_version
ON device.id = device_to_solution_version.device_id 
LEFT OUTER JOIN device_to_model_version 
ON device.id = device_to_model_version.device_id;
```

What implementation should I have to do this?

Thank you for your answer.

**Comment by zzzeek** [comment]
hey there -

This is a trivial join and there is nothing about it that should cause it to fail.  Here's a proper [MCVE](http://stackoverflow.com/help/mcve) against PostgreSQL, no failure.  Please run this test case to ensure it works fine on your end, thanks!

```python
import uuid

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session


Base = declarative_base()


class Parent(Base):
    __tablename__="parent"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)

class TestOne(Base):
    __tablename__="test_one"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey('parent.id'))
    create_time = Column(DateTime)


class TestTwo(Base):
    __tablename__="test_two"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey('parent.id'))
    create_time = Column(DateTime)

e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')

with e.connect() as conn:
    trans = conn.begin()

    Base.metadata.create_all(conn)

    s = Session(conn)

    p1 = Parent(id=uuid.uuid4(), name="p")
    s.add(p1)
    s.flush()

    s.add(TestOne(parent_id=p1.id))
    s.add(TestTwo(parent_id=p1.id))
    s.commit()

    session = Session(conn)
    results = session.query(
        Parent.id,
        TestOne.id,
        TestTwo.id,
    ).outerjoin(
        TestOne,
        Parent.id == TestOne.parent_id
    ).outerjoin(
        TestTwo,
        Parent.id == TestTwo.parent_id
    ).all()

    print(results)
```

output, including join at the end:

```sql
2021-02-17 10:23:12,488 INFO sqlalchemy.engine.base.Engine select version()
2021-02-17 10:23:12,488 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,489 DEBUG sqlalchemy.engine.base.Engine Col ('version',)
2021-02-17 10:23:12,489 DEBUG sqlalchemy.engine.base.Engine Row ('PostgreSQL 12.4 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 10.2.1 20200826 (Red Hat 10.2.1-3), 64-bit',)
2021-02-17 10:23:12,489 INFO sqlalchemy.engine.base.Engine select current_schema()
2021-02-17 10:23:12,489 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,490 DEBUG sqlalchemy.engine.base.Engine Col ('current_schema',)
2021-02-17 10:23:12,490 DEBUG sqlalchemy.engine.base.Engine Row ('public',)
2021-02-17 10:23:12,490 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-02-17 10:23:12,490 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,490 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-02-17 10:23:12,491 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,491 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2021-02-17 10:23:12,491 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,491 DEBUG sqlalchemy.engine.base.Engine Col ('standard_conforming_strings',)
2021-02-17 10:23:12,491 DEBUG sqlalchemy.engine.base.Engine Row ('on',)
2021-02-17 10:23:12,491 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-17 10:23:12,492 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-02-17 10:23:12,492 INFO sqlalchemy.engine.base.Engine {'name': 'parent'}
2021-02-17 10:23:12,492 DEBUG sqlalchemy.engine.base.Engine Col ('relname',)
2021-02-17 10:23:12,492 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-02-17 10:23:12,492 INFO sqlalchemy.engine.base.Engine {'name': 'test_one'}
2021-02-17 10:23:12,493 DEBUG sqlalchemy.engine.base.Engine Col ('relname',)
2021-02-17 10:23:12,493 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-02-17 10:23:12,493 INFO sqlalchemy.engine.base.Engine {'name': 'test_two'}
2021-02-17 10:23:12,493 DEBUG sqlalchemy.engine.base.Engine Col ('relname',)
2021-02-17 10:23:12,494 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE parent (
	id UUID NOT NULL, 
	name VARCHAR, 
	create_time TIMESTAMP WITHOUT TIME ZONE, 
	update_time TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)


2021-02-17 10:23:12,494 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,500 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE test_one (
	id SERIAL NOT NULL, 
	parent_id UUID, 
	create_time TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES parent (id)
)


2021-02-17 10:23:12,500 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,504 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE test_two (
	id SERIAL NOT NULL, 
	parent_id UUID, 
	create_time TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES parent (id)
)


2021-02-17 10:23:12,504 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,509 INFO sqlalchemy.engine.base.Engine INSERT INTO parent (id, name, create_time, update_time) VALUES (%(id)s, %(name)s, %(create_time)s, %(update_time)s)
2021-02-17 10:23:12,509 INFO sqlalchemy.engine.base.Engine {'id': UUID('fb38d7f3-a383-4301-82ff-69d72e7b736f'), 'name': 'p', 'create_time': None, 'update_time': None}
2021-02-17 10:23:12,510 INFO sqlalchemy.engine.base.Engine INSERT INTO test_one (parent_id, create_time) VALUES (%(parent_id)s, %(create_time)s) RETURNING test_one.id
2021-02-17 10:23:12,510 INFO sqlalchemy.engine.base.Engine {'parent_id': UUID('fb38d7f3-a383-4301-82ff-69d72e7b736f'), 'create_time': None}
2021-02-17 10:23:12,511 DEBUG sqlalchemy.engine.base.Engine Col ('id',)
2021-02-17 10:23:12,511 DEBUG sqlalchemy.engine.base.Engine Row (1,)
2021-02-17 10:23:12,512 INFO sqlalchemy.engine.base.Engine INSERT INTO test_two (parent_id, create_time) VALUES (%(parent_id)s, %(create_time)s) RETURNING test_two.id
2021-02-17 10:23:12,512 INFO sqlalchemy.engine.base.Engine {'parent_id': UUID('fb38d7f3-a383-4301-82ff-69d72e7b736f'), 'create_time': None}
2021-02-17 10:23:12,512 DEBUG sqlalchemy.engine.base.Engine Col ('id',)
2021-02-17 10:23:12,512 DEBUG sqlalchemy.engine.base.Engine Row (1,)
2021-02-17 10:23:12,513 INFO sqlalchemy.engine.base.Engine SELECT parent.id AS parent_id, test_one.id AS test_one_id, test_two.id AS test_two_id 
FROM parent LEFT OUTER JOIN test_one ON parent.id = test_one.parent_id LEFT OUTER JOIN test_two ON parent.id = test_two.parent_id
2021-02-17 10:23:12,514 INFO sqlalchemy.engine.base.Engine {}
2021-02-17 10:23:12,514 DEBUG sqlalchemy.engine.base.Engine Col ('parent_id', 'test_one_id', 'test_two_id')
2021-02-17 10:23:12,514 DEBUG sqlalchemy.engine.base.Engine Row (UUID('fb38d7f3-a383-4301-82ff-69d72e7b736f'), 1, 1)
[(UUID('fb38d7f3-a383-4301-82ff-69d72e7b736f'), 1, 1)]
2021-02-17 10:23:12,514 INFO sqlalchemy.engine.base.Engine ROLLBACK

```

**Comment by satodaiki** [comment]
Thank you!

I'm sorry, but I've just confirmed that this error isn't reproducible in the code I've provided.

However, while creating reproducible code, I solved it for the time being.

The implementations for which reproducibility was confirmed are as follows.

**test_main.py**
```python
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql.expression import text
from sqlalchemy import ForeignKey
from sqlalchemy.schema import Column, Sequence
from sqlalchemy.types import String, DateTime, Integer
from sqlalchemy.dialects.postgresql import UUID

Base = declarative_base()

class Parent(Base):
    __tablename__="parent"
    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text('UUID_GENERATE_V4()'))
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)

class TestOne(Base):
    __tablename__="test_one"
    id = Column(Integer, Sequence('device_to_model_version_id_seq'), primary_key=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey('parent.id'))
    other_one_id = Column(Integer, ForeignKey('other_one.id'))
    create_time = Column(DateTime)

class TestTwo(Base):
    __tablename__="test_two"
    id = Column(Integer, Sequence('device_to_solution_version_id_seq'), primary_key=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey('parent.id'))
    other_two_id = Column(Integer, ForeignKey('other_two.id'))
    create_time = Column(DateTime)

e = create_engine("postgres://postgres:password@localhost:5432/postgres", echo='debug')

with e.connect() as conn:
    trans = conn.begin()

    Base.metadata.create_all(conn)

    s = Session(conn)

    p1 = Parent(name="p")
    s.add(p1)
    s.flush()

    s.add(TestOne(parent_id=p1.id))
    s.add(TestTwo(parent_id=p1.id))
    s.commit()

    session = Session(conn)
    results = session.query(
        Parent.id,
        TestOne.id,
        TestTwo.id,
    ).outerjoin(
        TestOne,
        Parent.id == TestOne.parent_id
    ).outerjoin(
        TestTwo,
        Parent.id == TestTwo.parent_id
    ).all()

    print(results)
```

**models.py**
```python
from sqlalchemy.schema import Column, Sequence
from sqlalchemy.types import String, DateTime, Integer

from .test_main import Base

class OtherOne(Base):
    __tablename__="other_one"
    id = Column(Integer, Sequence('other_one_id_seq'), primary_key=True)
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)

class OtherTwo(Base):
    __tablename__="other_two"
    id = Column(Integer, Sequence('other_two_id_seq'), primary_key=True)
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)
```

The problem was defining the table on which the foreign key was based in a separate file.

I solved it by adding an import as below.

```python

class Parent(Base):
    __tablename__="parent"
    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text('UUID_GENERATE_V4()'))
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)

from .models import OtherOne, OtherTwo
```

**Comment by zzzeek** [comment]
OK, I can reproduce what happened, and what's happened here is that you got two separate stack traces.    When reporting issues please share the complete stack trace, including all "cause" exceptions.  We can modify my MCVE to reproduce your error as follows:

```python
import uuid

from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session


Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String)
    create_time = Column(DateTime)
    update_time = Column(DateTime)


class TestOne(Base):
    __tablename__ = "test_one"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey("parent.id"))
    create_time = Column(DateTime)
    other_one_id = Column(Integer, ForeignKey("other_one.id"))


class TestTwo(Base):
    __tablename__ = "test_two"
    id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey("parent.id"))
    create_time = Column(DateTime)
    other_two_id = Column(Integer, ForeignKey("other_two.id"))


session = Session()
q = (
    session.query(
        Parent.id,
        TestOne.id,
        TestTwo.id,
    )
    .outerjoin(TestOne, Parent.id == TestOne.parent_id)
    .outerjoin(TestTwo, Parent.id == TestTwo.parent_id)
)

```


the complete stack trace is therefore:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 1022, in _joincond_scan_left_right
    col = fk.get_referent(left)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 2107, in get_referent
    return table.corresponding_column(self.column)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 2247, in column
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'test_two.other_two_id' could not find table 'other_two' with which to generate a foreign key to target column 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 42, in <module>
    session.query(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2416, in outerjoin
    return self._join(
  File "<string>", line 2, in _join
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2587, in _join
    self._join_left_to_right(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2611, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2693, in _join_determine_implicit_left_side
    indexes = sql_util.find_left_clause_to_join_from(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/util.py", line 151, in find_left_clause_to_join_from
    elif Join._can_join(f, s) or onclause is not None:
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 995, in _can_join
    constraints = cls._joincond_scan_left_right(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 1024, in _joincond_scan_left_right
    if nrte.table_name == left.name:
AttributeError: '_ORMJoin' object has no attribute 'name'

```

I had noticed in your trace that the issue seemed to be related to reporting an error in any case, so we can repair the exception handling at least.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Extract table names when comparing to nrte error** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2592

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Extract table names when comparing to nrte error** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2593
