### ISSUE TITLE
Table object has no attribute _c.

### ISSUE THREAD

**Issue by Andrexxelles** [sqlalchemy/sqlalchemy#5963]
**Describe the bug**

There is nothing to describe, the code is light, I have nothing to say. Because of what this error is, I don’t know

**Expected behavior**

No error
```
from sqlalchemy import (
    create_engine, MetaData, Table,
    Column, INT, BOOLEAN, SMALLINT, VARCHAR, CHAR
)

engine = create_engine(
    'postgresql+psycopg2://username:password@localhost/db',
    isolation_level='REPEATABLE READ',
    future=True)

metadata = MetaData()

keys_table = Table('keys_table', metadata,
                   Column('id', INT, primary_key=True),
                   Column('user_id', INT),
                   Column('key', VARCHAR(24)),
                   Column('count', SMALLINT),
                   Column('status', BOOLEAN),
                   Column('value', CHAR)
                   )

```

**Error**

```
admin@BOOK C:\Users\admin\Desktop\Telegram_bot
# python db_manager.py
Traceback (most recent call last):
  File "db_manager.py", line 13, in <module>
    keys_table = Table('keys_table', metadata,
  File "<string>", line 2, in __new__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 601, in __new__
    metadata._remove_table(name, schema)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 198, in raise_
    raise exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 596, in __new__
    table._init(name, metadata, *args, **kw)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 631, in _init
    PrimaryKeyConstraint(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\base.py", line 1014, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 3805, in _set_parent
    table_pks = [c for c in table.c if c.primary_key]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 488, in c
    return self._c
AttributeError: 'Table' object has no attribute '_c'
```

**Versions.**
 - OS: Windows 7 home
 - Python: 3.8.3
 - SQLAlchemy: 1.4.0b3
 - Database: psycopg2  2.8.6
 - DBAPI:none

**Comment by gordthompson** [comment]
I am unable to reproduce your issue using de96fb2 given the code you provided. After enabling `echo=True` in `create_engine()` and adding …

```python
keys_table.drop(engine, checkfirst=True)
keys_table.create(engine)
```

… I can see the table being created correctly. The error is occurring somewhere else in your code.

**Comment by zzzeek** [comment]
you have an installation issue, this is not line 488 of SQLAlchemy 1.4.0b3.  line 488 is not even inside of a method:

 File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\sql\schema.py", line 488, in c
    return self._c

There is no line in current SQLAlchemy 1.4, nor in 1.3,  that looks like "return self._c", nor is there any attribute on a FromClause called "._c" in modern SQLAlchemy versions.

**Comment by Andrexxelles** [comment]
How does this happen ? 
I threw you my code completely,and it Sqlalchemy,and how the hell would ?
I'll think about how it could have turned out,but I threw you the code completely, which uses only the sqlalchemy library

**Comment by Andrexxelles** [comment]
I found the error.
I had the interpreter installed on an old version.

**Comment by kapsh** [comment]
For anyone landing here from google search, the reason for this error could be [Pycharm issue](https://youtrack.jetbrains.com/issue/PY-17735) when it "fixes" missing property. Reinstalling sqlalchemy package helps.

**Comment by CharlesB2** [comment]
Thanks @kapsh for the advice!

For me reinstalling sqlalchemy wasn't enough, I had to delete the whole venv and recreate it.
