### ISSUE TITLE
Optimize selectinload with many to many relationship to avoid unnecessary join

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5987]
Looking at the sql generated by selectinload with a many to many relationship and it's not too optimal.
Example:
given the models `A`, `B` and `a_b` as the secondary, the query 
```py
session.query(A).options(selectinload(A.bs)
```
executes the sql
```sql
select ...
from a
join a_b on a.id = a_b.a_id
join b on b.id = a_b.b_id
where a.id in (...)
```

The above sql could be simplified to avoid the join to the `a` table:
```sql
select ...
from a_b
join b on b.id = a_b.b_id
where a_b.a_id in (...)
```

Mikes suggestion is looking here: https://github.com/sqlalchemy/sqlalchemy/blob/553ac45aae5712e64a5380ba1fa1c6028acf5f39/lib/sqlalchemy/orm/strategies.py#L2497

**Comment by sqla-tester** [comment]
**bekapono** has proposed a fix for this issue in the **main** branch:

**omit_join optimization for selectinload on many-to-many relationships** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6674

**Comment by zzzeek** [comment]
the patch needs to support scenarios like the following (i.e. omit join should not be enabled for cases like the following):

```py
from __future__ import annotations

from sqlalchemy import create_engine, Table, Column, select
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship, selectinload
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


atob = Table(
    "atob", Base.metadata,
    Column("a_code", ForeignKey("a.code")),
    Column("b_id", ForeignKey("b.id")),
)

class A(Base):
    __tablename__ = "a"
    id: Mapped[int] = mapped_column(primary_key=True)
    code: Mapped[str] = mapped_column(unique=True)

    bs: Mapped[list[B]] = relationship("B", secondary=atob)


class B(Base):
    __tablename__ = "b"
    id: Mapped[int] = mapped_column(primary_key=True)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(code="q", bs=[B(), B(), B()]))
s.commit()

s.execute(select(A).options(selectinload(A.bs))).all()

```

output with the patch:

```
$ python test3.py 
2026-05-07 11:49:32,609 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-05-07 11:49:32,609 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("atob")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("atob")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("a")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("a")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("b")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("b")
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine 
CREATE TABLE a (
	id INTEGER NOT NULL, 
	code VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)


2026-05-07 11:49:32,610 INFO sqlalchemy.engine.Engine [no key 0.00007s] ()
2026-05-07 11:49:32,611 INFO sqlalchemy.engine.Engine 
CREATE TABLE b (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2026-05-07 11:49:32,611 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2026-05-07 11:49:32,611 INFO sqlalchemy.engine.Engine 
CREATE TABLE atob (
	a_code VARCHAR, 
	b_id INTEGER, 
	FOREIGN KEY(a_code) REFERENCES a (code), 
	FOREIGN KEY(b_id) REFERENCES b (id)
)


2026-05-07 11:49:32,611 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2026-05-07 11:49:32,611 INFO sqlalchemy.engine.Engine COMMIT
2026-05-07 11:49:32,614 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-05-07 11:49:32,615 INFO sqlalchemy.engine.Engine INSERT INTO a (code) VALUES (?)
2026-05-07 11:49:32,615 INFO sqlalchemy.engine.Engine [generated in 0.00010s] ('q',)
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine [generated in 0.00004s (insertmanyvalues) 1/3 (ordered; batch not supported)] ()
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/3 (ordered; batch not supported)] ()
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine [insertmanyvalues 3/3 (ordered; batch not supported)] ()
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine INSERT INTO atob (a_code, b_id) VALUES (?, ?)
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine [generated in 0.00006s] [('q', 1), ('q', 2), ('q', 3)]
2026-05-07 11:49:32,616 INFO sqlalchemy.engine.Engine COMMIT
2026-05-07 11:49:32,617 INFO sqlalchemy.engine.Engine BEGIN (implicit)
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 43, in <module>
    s.execute(select(A).options(selectinload(A.bs))).all()
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 2405, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 2295, in _execute_internal
    compile_state_cls.orm_execute_statement(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/context.py", line 312, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1447, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 534, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1658, in _execute_clauseelement
    elem._compile_w_cache(
    ~~~~~~~~~~~~~~~~~~~~~^
        dialect=dialect,
        ^^^^^^^^^^^^^^^^
    ...<4 lines>...
        linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 734, in _compile_w_cache
    compiled_sql = self._compiler(
        dialect,
    ...<4 lines>...
        **kw,
    )
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 331, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 1525, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 935, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 971, in process
    return obj._compiler_dispatch(self, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 128, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 4999, in visit_select
    compile_state = select_stmt._compile_state_factory(
        select_stmt, self, **kwargs
    )
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/base.py", line 787, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/context.py", line 457, in create_for_statement
    return cls._create_orm_context(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        cast("Union[Select, FromStatement]", statement),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **kw,
        ^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/context.py", line 1261, in _create_orm_context
    self._setup_for_generate()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/context.py", line 1380, in _setup_for_generate
    entity.setup_compile_state(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/context.py", line 2969, in setup_compile_state
    loading._setup_entity_query(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        compile_state,
        ^^^^^^^^^^^^^^
    ...<7 lines>...
        polymorphic_discriminator=self._polymorphic_discriminator,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 775, in _setup_entity_query
    value.setup(
    ~~~~~~~~~~~^
        compile_state,
        ^^^^^^^^^^^^^^
    ...<7 lines>...
        **kw,
        ^^^^^
    )
    ^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/interfaces.py", line 1173, in setup
    strat = self._get_strategy(loader.strategy)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/interfaces.py", line 1160, in _get_strategy
    self._strategies[key] = strategy = cls(self, key)
                                       ~~~^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/strategies.py", line 3024, in __init__
    self._query_info = self._init_for_omit_join()
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/strategies.py", line 3045, in _init_for_omit_join
    in_expr = fk_cols[0]
              ~~~~~~~^^^
IndexError: list index out of range

```

with current main:

```
$ python test3.py 
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("atob")
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("atob")
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,996 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("a")
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("a")
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("b")
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("b")
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine 
CREATE TABLE a (
	id INTEGER NOT NULL, 
	code VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)


2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [no key 0.00003s] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine 
CREATE TABLE b (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [no key 0.00003s] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine 
CREATE TABLE atob (
	a_code VARCHAR, 
	b_id INTEGER, 
	FOREIGN KEY(a_code) REFERENCES a (code), 
	FOREIGN KEY(b_id) REFERENCES b (id)
)


2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine [no key 0.00004s] ()
2026-05-07 11:49:54,997 INFO sqlalchemy.engine.Engine COMMIT
2026-05-07 11:49:55,001 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine INSERT INTO a (code) VALUES (?)
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine [generated in 0.00014s] ('q',)
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine [generated in 0.00004s (insertmanyvalues) 1/3 (ordered; batch not supported)] ()
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:55,002 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/3 (ordered; batch not supported)] ()
2026-05-07 11:49:55,003 INFO sqlalchemy.engine.Engine INSERT INTO b (id) VALUES (NULL) RETURNING id
2026-05-07 11:49:55,003 INFO sqlalchemy.engine.Engine [insertmanyvalues 3/3 (ordered; batch not supported)] ()
2026-05-07 11:49:55,003 INFO sqlalchemy.engine.Engine INSERT INTO atob (a_code, b_id) VALUES (?, ?)
2026-05-07 11:49:55,003 INFO sqlalchemy.engine.Engine [generated in 0.00006s] [('q', 1), ('q', 2), ('q', 3)]
2026-05-07 11:49:55,003 INFO sqlalchemy.engine.Engine COMMIT
2026-05-07 11:49:55,004 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-05-07 11:49:55,005 INFO sqlalchemy.engine.Engine SELECT a.id, a.code 
FROM a
2026-05-07 11:49:55,005 INFO sqlalchemy.engine.Engine [generated in 0.00005s] ()
2026-05-07 11:49:55,008 INFO sqlalchemy.engine.Engine SELECT a_1.id, b.id 
FROM a AS a_1 JOIN atob AS atob_1 ON a_1.code = atob_1.a_code JOIN b ON b.id = atob_1.b_id 
WHERE a_1.id IN (?)
2026-05-07 11:49:55,008 INFO sqlalchemy.engine.Engine [generated in 0.00018s] (1,)

```

**Comment by CaselIT** [comment]
We seem to completely miss selectinload in similar test cases, so they should be added.
Do you know were this type of model is tested so that we can parametrize on the loader?

**Comment by sqla-tester** [comment]
**bekapono** has proposed a fix for this issue in the **main** branch:

**omit_join optimization for selectinload on many-to-many relationships** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6674
