### ISSUE TITLE
Type annotations are not preserved by `declared_attr`, `hybrid_property`, and potentially other decorators

### ISSUE THREAD

**Issue by woodruffw** [sqlalchemy/sqlalchemy#5999]
First of all, thanks a ton for SQLAlchemy -- it's been absolutely invaluable to my work.

**Describe the bug**

I'm using `declared_attr` and `hybrid_property` throughout one of my codebases. That codebase is automatically documented using Sphinx + `sphinx-apidoc`, which includes type annotations (via `thing.__annotations__`) when present.

This normally works just fine, but SQLAlchemy's various decorators don't preserve `__annotations__`. As such, various decorated APIs in my documentation lack type signatures.

**Expected behavior**

`declared_attr` and `hybrid_property` should preserve their underlying `__annotations__` the way they currently do for `__doc__`.

**To Reproduce**

I don't have a simple test case yet, but I can try to produce one in a bit. In general, however:

1. Take a SQLAlchemy codebase that uses `hybrid_property` or another decorator.
2. Add type hints to the underlying (decorated) method
3. Attempt to generate Sphinx docs for the containing module
4. Check whether the generated docs include a type signature for the decorated method

**Versions.**
 - OS: Ubuntu 20.04
 - Python: CPython 3.8
 - SQLAlchemy: 1.3.12
 - Database: Postgres
 - DBAPI: psycopg2

---

I'm going to take a stab at fixing this, and will open a PR if my fixes work locally. Just figured I'd open an issue to track it as well 🙂

**Comment by CaselIT** [comment]
> I'm going to take a stab at fixing this, and will open a PR if my fixes work locally. Just figured I'd open an issue to track it as well 🙂

that sounds great, we appreciate opening an issue before a PR.

Regarding the issue I gather we need to copy the `__annotations__` attribute on the generated function if present? 
Since sqlalchemy still supports python2, it needs to be compatible also for py2 (by compatible I mean not error, the logic can be simply ignored in py2 since I don't think it has `__annotations__`)

**Comment by zzzeek** [comment]
hm.  in 2.0, type checkers such as mypy will work with hybrid and declared_attr.   but that doesnt' yet accommodate for runtime movement of `__annotations__`.   that would be something separate.

**Comment by zzzeek** [comment]
I'm not really following the "declared_attr" case so well, in terms of what that should do.   a "declared_attr" is replaced on a mapped class at mapping time.  If you have it on a mixin, it's a function decorator, implying we'd use `@functools.wraps` on it, but then it's not acting like an attribute but like a method.   Also, `declared_attr` doesn't transfer `__doc__` right now either.

beyond that, regular Python `@property` also does not do anything with `__annotations__`.  

```py
>>> class A:
...     id: int
...     @property
...     def foo(self) -> str:
...         ...
... 
>>> A.__annotations__
{'id': <class 'int'>}
>>> A.foo.__annotations__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'property' object has no attribute '__annotations__'

```

So....if `@property` doesn't do anything with `__annotations__`, what does that imply for a descriptor like `@hybrid_property` ?    I dont really know that we're supposed to be transferring `__annotations__`, or if we are, how, like, do we do "return" value?  The descriptor has no way to populate the `__annotations__` on the class itself when assigned.    So...not really sure what we're supposed to do here.

**Comment by woodruffw** [comment]
I'm not sure if it's helpful or not, but `@property` does something weird to preserve annotations -- they get added to the underlying `property.fget` callable, like so:

```py
>>> A.foo.fget.__annotations__
{'return': <class 'str'>}
```

But (also) strangely, `inspect.get_annotations` doesn't know about `property` objects:

```py
>>> inspect.get_annotations(A.foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/william/.pyenv/versions/3.10.0/lib/python3.10/inspect.py", line 144, in get_annotations
    raise TypeError(f"{obj!r} is not a module, class, or callable.")
TypeError: <property object at 0x7f7262b248b0> is not a module, class, or callable.
```

But *also*, extensions like `sphinx-autodoc-typehints` know about `fget` and know how to access it to get the annotations:

```py
    obj = obj.fget if isinstance(obj, property) else obj
    if not callable(obj):
        return
    obj = obj.__init__ if inspect.isclass(obj) else obj
    obj = inspect.unwrap(obj)

    try:
        signature = sphinx_signature(obj)
```

Permalink: https://github.com/tox-dev/sphinx-autodoc-typehints/blob/73aa9b6aea40720ca270b1107c1980b909943cb3/src/sphinx_autodoc_typehints/__init__.py#L492-L499

As is `sphinx` itself:

```py
    def add_directive_header(self, sig: str) -> None:
        super().add_directive_header(sig)
        sourcename = self.get_sourcename()
        if inspect.isabstractmethod(self.object):
            self.add_line('   :abstractmethod:', sourcename)
        if self.isclassmethod:
            self.add_line('   :classmethod:', sourcename)

        if safe_getattr(self.object, 'fget', None):  # property
            func = self.object.fget
        elif safe_getattr(self.object, 'func', None):  # cached_property
            func = self.object.func
        else:
            func = None

        if func and self.config.autodoc_typehints != 'none':
            try:
                signature = inspect.signature(func,
                                              type_aliases=self.config.autodoc_type_aliases)
                if signature.return_annotation is not Parameter.empty:
                    objrepr = stringify_typehint(signature.return_annotation)
                    self.add_line('   :type: ' + objrepr, sourcename)
            except TypeError as exc:
                logger.warning(__("Failed to get a function signature for %s: %s"),
                               self.fullname, exc)
                return None
            except ValueError:
                return None
```

Permalink: https://github.com/sphinx-doc/sphinx/blob/96b15e9e66bd4bc1079d983bf6be19d1e9aa7134/sphinx/ext/autodoc/__init__.py#L2726-L2753

**Comment by zzzeek** [comment]
> I'm not sure if it's helpful or not, but `@property` does something weird to preserve annotations -- they get added to the underlying `property.fget` callable, like so:
> 
> ```python
> >>> A.foo.fget.__annotations__
> {'return': <class 'str'>}
> ```

property doesn't "do" that, "fget" is the original decorated function.   

> 
> But (also) strangely, `inspect.get_annotations` doesn't know about `property` objects:
> 
> ```python
> >>> inspect.get_annotations(A.foo)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/william/.pyenv/versions/3.10.0/lib/python3.10/inspect.py", line 144, in get_annotations
>     raise TypeError(f"{obj!r} is not a module, class, or callable.")
> TypeError: <property object at 0x7f7262b248b0> is not a module, class, or callable.
> ```

ok....

> 
> But _also_, extensions like `sphinx-autodoc-typehints` know about `fget` and know how to access it to get the annotations:
> 
> ```python
>     obj = obj.fget if isinstance(obj, property) else obj
>     if not callable(obj):
>         return
>     obj = obj.__init__ if inspect.isclass(obj) else obj
>     obj = inspect.unwrap(obj)
> 
>     try:
>         signature = sphinx_signature(obj)
> ```
> 
> Permalink: https://github.com/tox-dev/sphinx-autodoc-typehints/blob/73aa9b6aea40720ca270b1107c1980b909943cb3/src/sphinx_autodoc_typehints/__init__.py#L492-L499
> 
> As is `sphinx` itself:
> 
> ```python
>     def add_directive_header(self, sig: str) -> None:
>         super().add_directive_header(sig)
>         sourcename = self.get_sourcename()
>         if inspect.isabstractmethod(self.object):
>             self.add_line('   :abstractmethod:', sourcename)
>         if self.isclassmethod:
>             self.add_line('   :classmethod:', sourcename)
> 
>         if safe_getattr(self.object, 'fget', None):  # property
>             func = self.object.fget
>         elif safe_getattr(self.object, 'func', None):  # cached_property
>             func = self.object.func
>         else:
>             func = None
> 
>         if func and self.config.autodoc_typehints != 'none':
>             try:
>                 signature = inspect.signature(func,
>                                               type_aliases=self.config.autodoc_type_aliases)
>                 if signature.return_annotation is not Parameter.empty:
>                     objrepr = stringify_typehint(signature.return_annotation)
>                     self.add_line('   :type: ' + objrepr, sourcename)
>             except TypeError as exc:
>                 logger.warning(__("Failed to get a function signature for %s: %s"),
>                                self.fullname, exc)
>                 return None
>             except ValueError:
>                 return None
> ```
> 
> Permalink: https://github.com/sphinx-doc/sphinx/blob/96b15e9e66bd4bc1079d983bf6be19d1e9aa7134/sphinx/ext/autodoc/__init__.py#L2726-L2753


can we get a sphinx person to just tell us what they'd like to see ?   otherwise I can just stick `self.__annotations__ = fn.__annotations__` just like `__doc__`, can you confirm that works w/ this extension for `declared_attr` and `hybrid_property`?  just search for `self.__doc__ = __doc__` in the source of `sqlalchemy/orm/decl_api.py` and `sqlalchemy/ext/hybrid.py` to see where it happens.

**Comment by zzzeek** [comment]
moving this off of 2.0 as this seems to have stalled

**Comment by LeonxLJX** [comment]
I'd like to take this one.

Thanks for the report — the `1.3.12` version context is useful. Before changing anything I'd like to reproduce this against current `main` first, since the surrounding code may have moved since this was filed.

Plan: trace the path, reproduce it, then make the smallest change that addresses it, plus a regression test if this area has coverage. If the root cause turns out to live somewhere other than where the report points, I'll report back here before forcing a change.

Anything already known about this that I should read first? (relevant PRs, existing tests, known constraints)

(claiming via @LeonxLJX)
