### ISSUE TITLE
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py)

### ISSUE THREAD

**Issue by FelixBenning** [sqlalchemy/sqlalchemy#6000]
I am not sure if this belongs here or into `sqlalchemy_utils`

```python
>>> import sqlalchemy
>>> import sqlalchemy_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
>>> sqlalchemy.__version__
'1.4.0b3'
```

**Comment by zzzeek** [comment]
this is in sqlalhcemy-utils, which would in theory need to change that import of a private entity over to "sqlalchemy.orm.context", however, the way _ColumnEntity is used is totally different now so they probably need to rethink what they are doing.     unfortunately they have to fix on their end, sorry.
