### ISSUE TITLE
select distinct raises NosuchColumnError on SQLAlchemy 1.4.0b3

### ISSUE THREAD

**Issue by bsdz** [sqlalchemy/sqlalchemy#6008]
**Describe the bug**

Selecting distinct from table with schema raises NosuchColumnError on SQLAlchemy 1.4.0b3 but works on older 1.3.23.

**Expected behavior**

It should not raise an exception and behave like in previous versions.

**To Reproduce**

Create database in postgresql:

```sql
CREATE DATABASE foo;

\connect foo;

CREATE SCHEMA bar;

CREATE TABLE bar.table1 (
    col1 integer NOT NULL,
    ADD CONSTRAINT table1_pk PRIMARY KEY (col1);
);
```

Then run following script:

```python
from sqlalchemy.ext.automap import automap_base
from sqlalchemy import create_engine
from sqlalchemy import distinct
from sqlalchemy.orm import sessionmaker, scoped_session

Base = automap_base()


class Table1(Base):
    __tablename__ = "table1"
    __table_args__ = {"schema": "bar"}


engine = create_engine("postgresql+psycopg2://docker:docker@localhost:5400/foo")
engine.echo = True
Base.prepare(engine, schema="bar", reflect=True)

session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

# runs okay on SQLA 1.3.23
# fails on SQLA 1.4.0b3 with NoSuchColumnError: "Could not locate column in row for column 'DISTINCT bar.table1.col1'"
recs = session.query(distinct(Table1.col1)).select_from(Table1).all()
```

**Error**

```
Traceback (most recent call last):
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 639, in _index_for_key
    rec = self._keymap[key]
KeyError: <sqlalchemy.sql.elements.UnaryExpression object at 0x7fc2f99d3790>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/blair/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/blair/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/blair/.vscode/extensions/ms-python.python-2021.2.582707922/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/blair/scratch/sqla/test.py", line 22, in <module>
    recs = session.query(distinct(Table1.col1)).select_from(Table1).all()
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2623, in all
    return self._iter().all()
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2758, in _iter
    result = self.session.execute(
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1656, in execute
    result = compile_state_cls.orm_setup_cursor_result(
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 302, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 88, in instances
    cursor.close()
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 68, in instances
    *[
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 69, in <listcomp>
    query_entity.row_processor(context, cursor)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2546, in row_processor
    getter = result._getter(column)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 886, in _getter
    return self._metadata._getter(key, raiseerr)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 99, in _getter
    index = self._index_for_key(key, raiseerr)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 641, in _index_for_key
    rec = self._key_fallback(key, ke, raiseerr)
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 783, in _key_fallback
    util.raise_(
  File "/home/blair/scratch/sqla/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'DISTINCT bar.table1.col1'"
```

**Versions.**
 - OS: ubutu focal
 - Python: 3.8.5
 - SQLAlchemy: 1.4.0b3
 - Database: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit 
 - DBAPI: psycopg2 : 2.8.6

**Have a nice day!**

**Comment by zzzeek** [comment]
just so you know this is not exactly how distinct() was expected to be used; for a plain "SELECT DISTINCT ..." you normally use query.distinct() or select.distinct().    the standalone distinct() is meant for expressions like "SELECT COUNT(DISTINCT col)".       that said, I can make this case work again but I'm seeing some edge cases that exist in both 1.3 and 1.4 as far as how standalone DISTINCT generates labels or not, which don't affect you here but just pointing that out.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**improve targeting and labeling for unary() in columns clause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2623

**Comment by bsdz** [comment]
> just so you know this is not exactly how distinct() was expected to be used

I've been naively using that form for a a long time now. Good to know - thanks.
