### ISSUE TITLE
switch custom.op() to handle escape doubling automatically

### ISSUE THREAD

**Issue by waweber** [sqlalchemy/sqlalchemy#6016]
**Describe the bug**
If you define a custom operator, e.g. `.op("%")` for Postgres similarity matching, you get a `TypeError: not enough arguments for format string` in 1.4.0b3, but not 1.4.0 versions before that.

**Expected behavior**
Either the query is executed properly, or maybe a clearer exception is raised and documented.

**To Reproduce**
```py
import sqlalchemy

DB_URL = "postgresql+asyncpg:///"

import asyncio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import select, column

async def async_main():
    engine = create_async_engine(
        DB_URL, echo=True,
    )

    async with engine.begin() as conn:
        q = select(
            column("'hello world'", is_literal=True)
            .op("%")(column("'ello wo'", is_literal=True))
        )
        res = await conn.execute(q)
        print(res.scalar())

asyncio.run(async_main())
```

**Error**

```
Traceback (most recent call last):
  File "/tmp/./test.py", line 25, in <module>
    asyncio.run(async_main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/./test.py", line 22, in async_main
    res = await conn.execute(q)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 404, in execute
    result = await greenlet_spawn(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 114, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1496, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in _execute_clauseelement
    ret = self._execute_context(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1724, in _execute_context
    self._handle_dbapi_exception(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1909, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1681, in _execute_context
    self.dialect.do_execute(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 416, in execute
    self._handle_exception(error)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 357, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 632, in _handle_exception
    raise error
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 412, in execute
    self._adapt_connection.await_(
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 56, in await_only
    return current.driver.switch(awaitable)
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 109, in greenlet_spawn
    value = await result
  File "/tmp/venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 377, in _prepare_and_execute
    operation = operation % self._parameter_placeholders(parameters)
TypeError: not enough arguments for format string
```

**Versions.**
 - OS: Fedora 33
 - Python: 3.9
 - SQLAlchemy: 1.4.0b3
 - Database: PostgreSQL
 - DBAPI: asyncpg 0.22.0

**Additional context**

This works in 1.4.0b2, but not in 1.4.0b3. In 1.4.0b3, changing the operator to `%%` will result in expected behavior.

Not sure if this is the proper behavior now, or if it was the proper behavior in 1.4.0b2. Also not sure if this is SQLAlchemy, or an asyncpg issue instead.

**Comment by zzzeek** [comment]
the parameter style was changed for the asyncpg dialect's DBAPI emulation layer to be the "format" paramstyle, rather than "qmark", so at this point it should behave the same as the psycopg2 dialect (however we should confirm that here).

the "%" operator is the modulus op and that's available using the Python % operator directly.

**Comment by waweber** [comment]
On a tangent, do you think it would be a good idea to add an actual "similarity" operation? In this case it is not the modulus operator, but overloaded to mean a postgres-specific similarity comparison operation. In the Python representation, I would expect `a % b` to have a result equivalent to the SQL `MOD(a, b)`

**Comment by zzzeek** [comment]
I googled for "postgresql similarity" and got this:

https://www.postgresql.org/docs/9.1/pgtrgm.html

you can use the % operator with "text" as well, and it should render the "%" operator.    

this does look like pretty esoteric Postgresql stuff right now (out of an ocean of tons of PostgreSQL extensions with different operators and such) and there are only two operators so I would think op() is likely good enough for now.

I think the bigger issue is that op("%") should be taking percent sign doubling into account, this shouldn't have to be doubled.

**Comment by zzzeek** [comment]
this actually breaks backwards compatibility w/ 1.3 but it's the 1.4 boundary so let's do it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Apply percent sign escaping to op(), custom_op()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2627
