### ISSUE TITLE
fix and test round trips + contains() for all PG ARRAY of: ENUM, JSON, VARCHAR, TEXT, BOOL, INET, CIDR, numerics, dates

### ISSUE THREAD

**Issue by mattbennett** [sqlalchemy/sqlalchemy#6023]
**Describe the bug**

Querying an Array of Enum values results in a cast error when not using a native enum.

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying[] @> text[]
LINE 4: WHERE entries.nonnative_days_of_week @> ARRAY['Friday']) AS ...
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Expected behavior**

The query should work as it does when using a native enum.

**To Reproduce**

Run the following script

```py
from enum import Enum

from sqlalchemy import Column
from sqlalchemy import Enum as DBEnum
from sqlalchemy import Integer, String, create_engine
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


class Entry(Base):
    __tablename__ = "entries"

    id = Column(Integer, primary_key=True)

    class DayOfWeek(Enum):
        Monday = "Mon"
        Tuesday = "Tue"
        Wednesday = "Wed"
        Thursday = "Thu"
        Friday = "Fri"
        Saturday = "Sat"
        Sunday = "Sun"

    name = Column(String)

    native_days_of_week = Column(
        ARRAY(DBEnum(DayOfWeek, create_constraint=False, native_enum=True)),
        nullable=True,
    )
    """ array of DOW pattern """

    nonnative_days_of_week = Column(
        ARRAY(DBEnum(DayOfWeek, create_constraint=False, native_enum=False)),
        nullable=True,
    )
    """ array of DOW pattern """


engine = create_engine("postgresql://postgres:password@localhost/test")
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

try:

    # insert some data
    weekdays = Entry(
        id=1,
        name="weekdays",
        native_days_of_week=[
            Entry.DayOfWeek.Monday,
            Entry.DayOfWeek.Tuesday,
            Entry.DayOfWeek.Wednesday,
            Entry.DayOfWeek.Thursday,
            Entry.DayOfWeek.Friday,
        ],
        nonnative_days_of_week=[
            Entry.DayOfWeek.Monday,
            Entry.DayOfWeek.Tuesday,
            Entry.DayOfWeek.Wednesday,
            Entry.DayOfWeek.Thursday,
            Entry.DayOfWeek.Friday,
        ],
    )

    session.add(weekdays)
    session.commit()

    # query
    friday = Entry.DayOfWeek.Friday
    print(
        session.query(Entry)
        .filter(Entry.native_days_of_week.contains([friday]))
        .count()
    )

    # non-native query raises
    # LINE 4: WHERE entries.nonnative_days_of_week @> ARRAY['Friday']) AS ...
    #                                              ^
    # HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
    print(
        session.query(Entry)
        .filter(Entry.nonnative_days_of_week.contains([friday]))
        .count()
    )

finally:

    session.close()
    Base.metadata.drop_all(engine)
```

**Error**

```
╰─ python /tmp/repro.py
1
Traceback (most recent call last):
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 575, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying[] @> text[]
LINE 4: WHERE entries.nonnative_days_of_week @> ARRAY['Friday']) AS ...
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/repro.py", line 86, in <module>
    .filter(Entry.nonnative_days_of_week.contains([friday]))
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3803, in count
    return self.from_self(col).scalar()
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3523, in scalar
    ret = self.one()
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/mattbennett/.virtualenvs/repro/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 575, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying[] @> text[]
LINE 4: WHERE entries.nonnative_days_of_week @> ARRAY['Friday']) AS ...
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

[SQL: SELECT count(*) AS count_1
FROM (SELECT entries.id AS entries_id, entries.name AS entries_name, entries.native_days_of_week AS entries_native_days_of_week, entries.nonnative_days_of_week AS entries_nonnative_days_of_week
FROM entries
WHERE entries.nonnative_days_of_week @> %(nonnative_days_of_week_1)s) AS anon_1]
[parameters: {'nonnative_days_of_week_1': ['Friday']}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: MacOS 11.2.2
 - Python: 3.7.7
 - SQLAlchemy: 1.3.23
 - Database: Postgres 9.6
 - DBAPI: psycopg2-binary==2.8.2

**Comment by zzzeek** [comment]
@CaselIT - the logic for cast looks like it should be opened up to meet varchar enums as well to fix:

```
diff --git a/lib/sqlalchemy/dialects/postgresql/array.py b/lib/sqlalchemy/dialects/postgresql/array.py
index 91bb89ea9..e365a0fd0 100644
--- a/lib/sqlalchemy/dialects/postgresql/array.py
+++ b/lib/sqlalchemy/dialects/postgresql/array.py
@@ -340,7 +340,6 @@ class ARRAY(sqltypes.ARRAY):
     def _against_native_enum(self):
         return (
             isinstance(self.item_type, sqltypes.Enum)
-            and self.item_type.native_enum
         )
 
     def bind_expression(self, bindvalue):

```

we need to add some comparator tests to the ArrayEnum and ArrayJson suites.

**Comment by zzzeek** [comment]
we need the cast for plain VARCHAR / String() in general.     not sure about other datatypes yet.   for ints, seems to not be the case but I'm not understanding why.

**Comment by zzzeek** [comment]
it looks like we send it like:

    WHERE entries.nonnative_days_of_week @> %(nonnative_days_of_week_1)s

that is, we are sending the whole list as a bound param to psycopg2.   then psycopg2 sends it as:

    WHERE entries.nonnative_days_of_week @> ARRAY['th']

so I think we need a suite that is doing "contains" tests for combinations:

    1. all major datatypes, string, int, float, number, dates, json, array, maybe hstore
    2. all the postgresql drivers
    3. doing full round trips

**Comment by CaselIT** [comment]
That's strange. I'll take a look. Usually pg casts `ARRAY['th']` as a `text[]` so it should not complain when the other type is an array of text.
Or do we renter `Enum(<enum>, native_enum=False)` as a `varchar`? Maybe for pg we could use text instead?

**Comment by zzzeek** [comment]
well we should support ARRAY of VARCHAR directly as well, so if PG is complaining about casting from varchar to text, which is particularly picky of it, I think we just generally need to be detecting any textual type on the left side (like CHAR, VARCHAR, etc) and be casting if the right hand is delivered as TEXT.   but also need to see what the three different drivers do.

**Comment by zzzeek** [comment]
same issue just reported at #6030, here's the MCVE:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Table
from sqlalchemy import Text
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.dialects.postgresql import CIDR
from sqlalchemy.dialects.postgresql import INET
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql.schema import MetaData

Base = declarative_base()

m = MetaData()

a = Table(
    "a",
    m,
    Column("t", ARRAY(Text)),
    Column("i", ARRAY(INET)),
    Column("c", ARRAY(CIDR)),
)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
m.drop_all(e)
m.create_all(e)


with e.begin() as conn:
    conn.execute(
        a.insert(),
        [
            {
                "i": ["1.2.3.4", "2.3.4.5"],
                "t": ["aaa bbb", "xxx, yyy", "zzz"],
                "c": ["10.0.0.0/8", "192.168.0.0/16"],
            },
            {
                "i": ["1.2.3.4", "2.3.4.5"],
                "t": ["aaa bbb", "xxx, yyy", "zzz"],
                "c": ["10.0.0.0/8", "192.168.0.0/16"],
            },
            {
                "i": ["1.2.3.4", "2.3.4.5"],
                "t": ["aaa bbb", "xxx, yyy", "zzz"],
                "c": ["10.0.0.0/8", "192.168.0.0/16"],
            },
            {
                "i": ["1.2.3.4", "2.3.4.5"],
                "t": ["aaa bbb", "xxx, yyy", "zzz"],
                "c": ["10.0.0.0/8", "192.168.0.0/16"],
            },
            {
                "i": ["1.2.3.4", "2.3.4.5"],
                "t": ["aaa bbb", "xxx, yyy", "zzz"],
                "c": ["10.0.0.0/8", "192.168.0.0/16"],
            },
        ],
    )
```


turning on the cast resolves:

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/array.py b/lib/sqlalchemy/dialects/postgresql/array.py
index 91bb89ea9..a6355128b 100644
--- a/lib/sqlalchemy/dialects/postgresql/array.py
+++ b/lib/sqlalchemy/dialects/postgresql/array.py
@@ -332,9 +332,7 @@ class ARRAY(sqltypes.ARRAY):
 
     @util.memoized_property
     def _require_cast(self):
-        return self._against_native_enum or isinstance(
-            self.item_type, sqltypes.JSON
-        )
+        return True
 
     @util.memoized_property
     def _against_native_enum(self):

```

**Comment by zzzeek** [comment]
Here are the combinations needed:

insert->execute, insert->executemany, select, select using contains(), (update w/ SET ?)
    ENUM(native), ENUM(non-native), HSTORE, JSON, VARCHAR, TEXT, BOOL, BYTEA, INET, CIDR, numerics, dates, others? 
         psycopg2 , asyncpg, pg8000

**Comment by CaselIT** [comment]
I guess it makes tense to always just turn on casting for array.

**Comment by zzzeek** [comment]
probably not for numerics and maybe not dates. i just want to get a test harness that will do every combination and then we can fix them all.

**Comment by CaselIT** [comment]
It's happy also with dates, numbers etc

**Comment by CaselIT** [comment]
Also for dates you could use the string version, and that may cause problems if it's not casted

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**The ARRAY type in postgresql will always emit a cast when used as value.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2628

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**The ARRAY type in postgresql will always emit a cast when used as value.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2630
