### ISSUE TITLE
Regression with joinedload() on 1.4

### ISSUE THREAD

**Issue by brmzkw** [sqlalchemy/sqlalchemy#6052]
**Describe the bug**

I am unable to call `.joinedload()` and `.count()` at the same time with SQLAlchemy 1.4. It affects Flask-SQLAlchemy, as `.paginate()` is broken (https://github.com/pallets/flask-sqlalchemy/issues/910)

**To Reproduce**
```py
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    String,
    create_engine,
)
from sqlalchemy.orm import (
    joinedload,
    relationship,
    sessionmaker,
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
engine = create_engine('sqlite:///:memory')
Session = sessionmaker(bind=engine)


class User(Base):
    __tablename__ = 'users'

    def __repr__(self):
        return 'User %s' % self.id

    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('users.id'))
    parent = relationship('User', remote_side=[id], lazy='raise')

Base.metadata.create_all(engine)
session = Session()

u = User()
session.add(u)
session.commit()

u2 = User(parent=u)
session.add(u2)
session.commit()

query = session.query(User).options(joinedload(User.parent))
query.count()
```

**Error**

```
Traceback (most recent call last):
  File "bug-1.4.py", line 42, in <module>
    query.count()
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3009, in count
    return self._from_self(col).scalar()
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2753, in scalar
    ret = self.one()
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2730, in one
    return self._iter().one()
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2771, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1653, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1387, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 539, in _compile_w_cache
    **kw
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2965, in visit_select
    select_stmt, self, **kwargs
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 492, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 579, in create_for_statement
    opt.process_compile_state(self)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategy_options.py", line 136, in process_compile_state
    self._process(compile_state, not bool(compile_state.current_path))
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategy_options.py", line 652, in _process
    raiseerr,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategy_options.py", line 796, in _bind_loader
    entities, prop, token._parententity, raiseerr
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategy_options.py", line 882, in _find_entity_prop_comparator
    % (util.clsname_as_plain_name(type(prop)), prop)
sqlalchemy.exc.ArgumentError: Query has only expression-based entities, which do not apply to relationship property "User.parent"
```

**Versions.**

- SQLAlchemy 1.4

**Comment by zzzeek** [comment]
I would see if Flask can remove this meaningless joinedload() as it is not necessary here.

**Comment by zzzeek** [comment]
OK this is extremely specific to just the query.count() method.    Usually, options that make no sense raise an error, including on 1.3, such as:

    s.query(A.id).options(joinedload(A.bs)).all()

I'll adjust query.count() to behave as closely to the old way as possible as this is all frozen in time stuff.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Move enable_eagerloads(False) out of _from_self() into count()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2633

**Comment by brmzkw** [comment]
As always, thanks a lot @zzzeek. I confirm the fix works.

> I would see if Flask can remove this meaningless joinedload() as it is not necessary here.

I tried to keep the example as minimal as possible. The `joinedload()` is necessary for me, because the relationship is defined with `lazy='raise'` and I use the same query to `count()` the number of items, and access the relatated object.

**Comment by zzzeek** [comment]
> As always, thanks a lot @zzzeek. I confirm the fix works.
> 
> > I would see if Flask can remove this meaningless joinedload() as it is not necessary here.
> 
> I tried to keep the example as minimal as possible. The `joinedload()` is necessary for me, because the relationship is defined with `lazy='raise'` and I use the same query to `count()` the number of items, and access the relatated object.

that sounds very strange, query.count() does not access any related object, can you please clarify what you're doing there?    note that Query is legacy overall, so the whole pattern here is no longer the "best" way to do it.

**Comment by brmzkw** [comment]
What I'm doing is:

```python
query = session.query(User).options(joinedload(User.parent))

count = query.count()
items = query.items()
```

or, with flask-sqlalchemy:

```python
def my_endpoint():
  query = query.options(joinedload(User.parent))
  res = query.paginate(page=0, per_page=30)
  schema = schemas.UserListSchema()
  return schema.dump({'data': res.items, 'meta': res})
```

What is the "best" way to achieve this?

**Comment by zzzeek** [comment]
you would have two separate queries:

```python
count = session.query(func.count()).select_from(User).scalar()

items = sesion.query(User).options(joinedload(User.parent)).all()

```

the idea is that this does not rely on implicit guessing and you also get a much more efficient query for the COUNT part, as the ORM's .count() method has to run everything in an inefficient subquery.

**Comment by zzzeek** [comment]
ah nevermind
