### ISSUE TITLE
Explicitly naming a column fails when it is referenced by ForeignKey

### ISSUE THREAD

**Issue by Plutaniano** [sqlalchemy/sqlalchemy#6070]
**Describe the bug**
The following code does not work when explicitly declaring a name to a column.

**Expected behavior**
I expected a column `id` to be created, where `id.name == 'parent id'`   

**To Reproduce**

```python
from sqlalchemy import create_engine, Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
engine = create_engine('sqlite:///:memory:')

class Parent(Base):
    __tablename__ = 'parents'

    # id = Column(Integer, primary_key=True) # this works
    id = Column('parent id', Integer, primary_key=True) # this doesnt
    children = relationship('Child', backref='parent')


class Child(Base):
    __tablename__ = 'children'

    id = Column('child id', Integer, primary_key=True)
    parent = Column('parent', Integer, ForeignKey('parents.id'))

Base.metadata.create_all(engine)
```
**Error**

```python
Traceback (most recent call last):
  File "teste.py", line 23, in <module>
    Base.metadata.create_all(engine)
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4663, in create_all
    bind._run_visitor(
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 759, in visit_metadata
    collection = sort_tables_and_constraints(
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1195, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 3534, in referred_table
    return self.elements[0].column.table
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/lucas/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 2260, in column
    raise exc.NoReferencedColumnError(
sqlalchemy.exc.NoReferencedColumnError: Could not initialize target column for ForeignKey 'parents.id' on table 'children': table 'parents' has no column named 'id'
```

**Versions.**
 - OS: Ubuntu 20.04 running on WSL2
 - Python: 3.8.5
 - SQLAlchemy: 1.3.23 
 - Database: -
 - DBAPI: -

**Additional context**
This is my first github issue and I'm pretty new to SQL/SQLAlchemy. I talked to a more experienced dev and he suggested submitting an issue here.

**Comment by zzzeek** [comment]
hi there -

the string argument to `ForeignKey()` works at the level of `Table()` and `Column()`.  So you want to reference the actual name of the `Column()` object, which in your test would default to "id", but since you are naming it differently, it has to be that name:

```
class Child(Base):
    __tablename__ = 'children'

    id = Column('child id', Integer, primary_key=True)
    parent = Column('parent', Integer, ForeignKey('parents.parent id'))

```

**Comment by Plutaniano** [comment]
Makes sense. Thanks a lot!
