### ISSUE TITLE
failed to wrap query with labels with .exists()

### ISSUE THREAD

**Issue by senseysensor** [sqlalchemy/sqlalchemy#6076]
**Describe the bug**
In version 1.4.0 I have following error:

ArgumentError FROM expression, such as a Table or alias() object expected, got Column('col1', Text(), table=<T1>).

trying to make `query.exists()` where `query` has labeled field in select part of statement.

**Expected behavior**
In version 1.3.23 that behaviour worked.

**To Reproduce**
```python
x = self.session.query(T1.col1.label('dfd'))
x = x.exists()
```

**Error**

```
Traceback (most recent call last):
  File "/Users/project/src/repository/case_correction.py", line 349, in time_series
    x.exists()
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2949, in exists
    inner = inner.select_from(ezero)
  File "<string>", line 2, in select_from
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 96, in _generative
    x = fn(self, *args, **kw)
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5462, in select_from
    self._from_obj += tuple(
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5463, in <genexpr>
    coercions.expect(
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 192, in expect
    return impl._implicit_coercions(
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 928, in _implicit_coercions
    self._raise_for_expected(original_element, argname, resolved)
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 416, in _raise_for_expected
    return super(_SelectIsNotFrom, self)._raise_for_expected(
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 262, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/Users/poetry_virtual_env/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: FROM expression, such as a Table or alias() object expected, got <sqlalchemy.sql.elements.Label object at 0x11049ef70>.
```

**Versions.**
 - OS: os x 10.15.7
 - Python: 3.9.2
 - SQLAlchemy: 1.4.0
 - Database: postgres 12
 - DBAPI: psycopg2 2.8.6

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure entity or None returned from _entity_from_pre_ent_zero()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2643

**Comment by zzzeek** [comment]
thanks for reporting, this will be in 1.4.1
