### ISSUE TITLE
sqlalchemy.case failing when a iterable is provided

### ISSUE THREAD

**Issue by datapythonista** [sqlalchemy/sqlalchemy#6081]
**Describe the bug**

`sqlalchemy.case` used to accept a generator to specify the `WHEN` conditions, but in 1.4 raises an exception. It works well with a list, so a workaround can be implemented by simply materializing to a list. But open an issue so you are aware of the regression and can decide what's best.

Thanks!

**Expected behavior**

```py
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.23'
>>> users_table = sqlalchemy.Table('users',
...                                sqlalchemy.MetaData(),
...                                sqlalchemy.Column('name', sqlalchemy.Integer, primary_key=True))
>>> when = ((users_table.c.name == k, v) for k, v in {'wendy': 'W', 'jack': 'J'}.items())
>>> sqlalchemy.case(when, else_='E')
<sqlalchemy.sql.elements.Case object at 0x7fae117f8970>
```

**To Reproduce**

```py
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.4.0'
>>> users_table = sqlalchemy.Table('users',
...                                sqlalchemy.MetaData(),
...                                sqlalchemy.Column('name', sqlalchemy.Integer, primary_key=True))
>>> when = ((users_table.c.name == k, v) for k, v in {'wendy': 'W', 'jack': 'J'}.items())
>>> sqlalchemy.case(when, else_='E')
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in case
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 2767, in __init__
    whenlist = [
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 2769, in <listcomp>
    coercions.expect(
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 167, in expect
    resolved = impl._literal_coercion(
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 350, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 262, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression expected, got (<sqlalchemy.sql.elements.BinaryExpression object at 0x7f95166413d0>, 'W').
```

**Versions.**
 - OS: Linux
 - Python: Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46)
 - SQLAlchemy: 1.4
 - Database:
 - DBAPI:

**Comment by zzzeek** [comment]
we can restore this by testing *args, but we should probably see if it can apply to other things that accept *args.  it might not be worth it and i might want to look for best practices for things that accept *args.

**Comment by zzzeek** [comment]
using the new API presents no problems, so while there's a slight degradation in the deprecated API here it's not worth trying to fix:

```py
import sqlalchemy

users_table = sqlalchemy.Table(
    "users",
    sqlalchemy.MetaData(),
    sqlalchemy.Column("name", sqlalchemy.Integer, primary_key=True),
)
when = (
    (users_table.c.name == k, v)
    for k, v in {"wendy": "W", "jack": "J"}.items()
)


print(
    sqlalchemy.case(*when, else_="E").compile(
        compile_kwargs={"literal_binds": True}
    )
)

```

output

```
CASE WHEN (users.name = 'wendy') THEN 'W' WHEN (users.name = 'jack') THEN 'J' ELSE 'E' END
```
