### ISSUE TITLE
"identity" column query introduced in 1.4.0 breaks Redshift compatibility because it's a reservered word

### ISSUE THREAD

**Issue by NicolasPA** [sqlalchemy/sqlalchemy#6082]
## Bug
Fails to reflect a **Redshift** table with `sqlalchemy.Table(table, metadata, autoload=True)` from a Redshift database with Python 3.8 and SQLAlchemy 1.4.0.

Reproduce:
```python
connection_string = "postgresql+psycopg2://user:password@cluster.zone.redshift.amazonaws.com:5439/db"
redshift_engine = sqlalchemy.create_engine(connection_string)
redshift_connection = redshift_engine.connect()
metadata = sqlalchemy.MetaData(redshift_connection)
table_name = "some_table"
sqlalchemy.Table(table_name, metadata, autoload_with=redshift_connection)
```

Error:
```python
Traceback (most recent call last):
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "identity"
LINE 14:               NULL as identity
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nicolas/Projects/code/projectabc/logs/sqlalchemybug.py", line 14, in <module>
    table = sqlalchemy.Table(table, metadata, autoload=True)
  File "<string>", line 2, in __new__
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 597, in __new__
    metadata._remove_table(name, schema)
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 592, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 667, in _init
    self._autoload(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 702, in _autoload
    conn_insp.reflect_table(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 773, in reflect_table
    for col_d in self.get_columns(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 496, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3625, in get_columns
    c = connection.execute(s, dict(table_oid=table_oid))
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/nicolas/.virtualenvs/projectabc/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "identity"
LINE 14:               NULL as identity
                               ^

[SQL: 
            SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod),
              (
                SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                FROM pg_catalog.pg_attrdef d
                WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
                AND a.atthasdef
              ) AS DEFAULT,
              a.attnotnull,
              a.attrelid as table_oid,
              pgd.description as comment,
              NULL as generated,
              NULL as identity
            FROM pg_catalog.pg_attribute a
            LEFT JOIN pg_catalog.pg_description pgd ON (
                pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
            WHERE a.attrelid = %(table_oid)s
            AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum
        ]
[parameters: {'table_oid': 2177308}]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

## Origin

This  commit "Add reflection for Identity columns ": https://github.com/sqlalchemy/sqlalchemy/commit/7362d454f46107cae4076ce54e9fa430c3370734, introduced a query that uses a column alias `identity` here: https://github.com/sqlalchemy/sqlalchemy/blame/master/lib/sqlalchemy/dialects/postgresql/base.py#L3594

But this is a reserved word for Redshift, see: https://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html

## Workaround

Downgrading to SQLAlchemy 1.3.23 removes this change and prevents the bug.

## Suggested solution

A fix, for Redshift, is to use double quotes around the reserved word, so in the Python code it would give:
```python
identity = 'NULL as "identity"'
```

**Comment by zzzeek** [comment]
hey there -

there's a dedicated [sqlalchemy-redshift](https://pypi.org/project/sqlalchemy-redshift/) driver that builds on the postgresql driver and is intended to provide the correct reflection queries for this diverging database.  can you give that a try?

**Comment by zzzeek** [comment]
at the same time, @CaselIT we probably shouldnt use the word "identity" as a label as that is a reserved word, can we tweak that?

**Comment by CaselIT** [comment]
Sure, should be just a one line fix

**Comment by CaselIT** [comment]
That path is taken only if `server_version_info` id detected ad below `< 10`. What version is detected for Redshift @NicolasPA ?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Rename column name that used a reserved word** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2645

**Comment by NicolasPA** [comment]
Thanks for the suggestion @zzzeek.

@CaselIT `server_version_info = (8, 0, 2)`
This query gives the full version detail on Redshift:
```sql
SELECT VERSION();
-- PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24421
```

**Comment by CaselIT** [comment]
Ok then it make sense that it took that path.
I wonder why it redshirt identifies itself this a version that old..

I also think it be better to use the external dialect since some things in the postgres dialect that depend on the version detection will be disabled

**Comment by NicolasPA** [comment]
I think it dates back from when Redshift started and reused the worked done on ParAccel with PostgreSQL 8.  
Then I guess they decided that they had other priorities than keeping pace with PostgreSQL evolution.  
So yeah, using `sqlalchemy-redshift` is probably the best solution for the future.  

It appears that `identity` is not a reserved word for PostgreSQL but it is in the SQL:2016 standard: https://www.postgresql.org/docs/current/sql-keywords-appendix.html

**Comment by CaselIT** [comment]
> It appears that identity is not a reserved word for PostgreSQL but it is in the SQL:2016 standard: https://www.postgresql.org/docs/current/sql-keywords-appendix.html

thanks for pointing mentioning it. we will change it in the name so it should no longer be a problem either way
