### ISSUE TITLE
NoSuchColumnError stack trace for a function column in a Query

### ISSUE THREAD

**Issue by bigjools** [sqlalchemy/sqlalchemy#6086]
**Describe the bug**

I am converting my code from using 1.3.x to 1.4.1 and one of my existing queries is now stack tracing with a NoSuchColumnError, where the Query is returning a `func` column along with other data from a Query.

**Expected behavior**

I've tried to investigate in the debugger and I can boil it down to a simple statement:
`session.query(models.Image, func.count(models.Image.id)).group_by(models.Image)`
(not the actual one I am using but it reproduces the error)
Normally I would expect to get a result back, but in this case it stack traces.

I am really struggling to provide a reproducible test case for you because this error **only** happens with **one** of my model classes! If I swap out my `models.Image` with a different, but equally complex model, it works as expected. I cannot work out what is different about it that causes this error. It is not particularly an unusual model, it has a few relationships and a couple of them are `joinedload`ed.

I might be able to privately send the model definition to someone but I cannot post it publicly.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
# Insert code here
```

**Error**

```
(Pdb++) session.query(models.Image, func.count(models.Image.id)).group_by(models.Image).all()     
*** sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'count(anon_1.image_id)'"
Traceback (most recent call last):
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 639, in _index_for_key
    rec = self._keymap[key]
KeyError: <sqlalchemy.sql.functions.count at 0x7f9e453e5c70; count>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2644, in all
    return self._iter().all()
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2779, in _iter
    result = self.session.execute(
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1656, in execute
    result = compile_state_cls.orm_setup_cursor_result(
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 318, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 88, in instances
    cursor.close()
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 68, in instances
    *[
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 69, in <listcomp>
    query_entity.row_processor(context, cursor)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2582, in row_processor
    getter = result._getter(column)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 886, in _getter
    return self._metadata._getter(key, raiseerr)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 99, in _getter
    index = self._index_for_key(key, raiseerr)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 641, in _index_for_key
    rec = self._key_fallback(key, ke, raiseerr)
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 783, in _key_fallback
    util.raise_(
  File "/home/juledwar/src/helios/.tox/py3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception

```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.5
 - SQLAlchemy: 1.4.1
 - Database: sqlite here, but happens on postgres too
 - DBAPI:

**Additional context**
Example of amending the expression above to a different model:
```
(Pdb++) session.query(models.ImageTag, func.count(models.ImageTag.id)).group_by(models.ImageTag).all()
[(<helios.dbschema.models.ImageTag: id: 1 tag: taghostvvO8DzBk8j.edu/tagrepoM9WqXQBFOi:tagversionK6xfFad7ui>, 1), (<helios.dbschema.models.ImageTag: id: 2 tag: taghostbCBr6y3grl.edu/tagrepomZaWo7ekXT:tagversionvzCrsmKxtR>, 1)]
```
**Have a nice day!**

**Comment by zzzeek** [comment]
no worries, the query you describe plus the joinedload is sufficinet to reproduce:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="joined")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()


s.query(A, func.count(A.id)).group_by(A).all()
```

**Comment by zzzeek** [comment]
fortunately this can be worked around by applying a label to your func.count():

    s.query(A, func.count(A.id).label('count')).group_by(A).all()

if you can verify that fixes the problem for you now, I can get to this issue after i do some others

**Comment by bigjools** [comment]
Can confirm using `label` does the trick, thanks very much for figuring it out!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure ClauseAdapter treats FunctionElement as a ColumnElement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2654
