### ISSUE TITLE
Issue with Query.join() false-positive ambiguity

### ISSUE THREAD

**Issue by alanwilter** [sqlalchemy/sqlalchemy#6089]
**Describe the bug**

It's about [Key Behavioral Changes - ORM](https://docs.sqlalchemy.org/en/14/changelog/migration_13.html#key-behavioral-changes-orm), new in 1.4.

My query works fine in 1.3 and has the ON clause, though it's multiple ones and hence are wrapped with `_and` function.

```python
db_session.query(HomozygousVariant, Variant)
        .filter(HomozygousVariant.individual == individual.phenopolis_id)
        .join(
            Variant,
            and_(
                HomozygousVariant.CHROM == Variant.CHROM,
                HomozygousVariant.POS == Variant.POS,
                HomozygousVariant.REF == Variant.REF,
                HomozygousVariant.ALT == Variant.ALT,
            ),
        )
        .with_entities(Variant)
```
and translates in SQl as:
``` SQL
SELECT variants.variant_id AS variants_variant_id, variants."CHROM" AS "variants_CHROM", variants."POS" AS "variants_POS", variants."ID" AS "variants_ID", variants."REF" AS "variants_REF", variants."ALT" AS "variants_ALT", variants."AF" AS "variants_AF", variants."AC" AS "variants_AC", variants."AN" AS "variants_AN", variants."HET_COUNT" AS "variants_HET_COUNT", variants."HOM_COUNT" AS "variants_HOM_COUNT", variants."DP" AS "variants_DP", variants."FS" AS "variants_FS", variants."MLEAC" AS "variants_MLEAC", variants."MLEAF" AS "variants_MLEAF", variants."MQ" AS "variants_MQ", variants."FILTER" AS "variants_FILTER", variants."HET" AS "variants_HET", variants."HOM" AS "variants_HOM", variants.most_severe_consequence AS variants_most_severe_consequence, variants.af_kaviar AS variants_af_kaviar, variants.af_gnomad_genomes AS variants_af_gnomad_genomes, variants.af_jirdc AS variants_af_jirdc, variants.af_tommo AS variants_af_tommo, variants.af_krgdb AS variants_af_krgdb, variants.af_converge AS variants_af_converge, variants.af_hgvd AS variants_af_hgvd, variants.gene_id AS variants_gene_id, variants.gene_symbol AS variants_gene_symbol, variants.hgvsc AS variants_hgvsc, variants.hgvsp AS variants_hgvsp, variants.dann AS variants_dann, variants.cadd_phred AS variants_cadd_phred
FROM hom_variants JOIN variants ON hom_variants."CHROM" = variants."CHROM" AND hom_variants."POS" = variants."POS" AND hom_variants."REF" = variants."REF" AND hom_variants."ALT" = variants."ALT"
WHERE hom_variants.individual = %(individual_1)s
```
**Error**

```
*** sqlalchemy.exc.InvalidRequestError: Don't know how to join to <Mapper at 0x109fddac0; Variant>. Please use the .select_from() method to establish an explicit left side, as well as providing an explicit ON clause if not present already to help resolve the ambiguity.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2795, in __str__
    return str(statement.compile(bind))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 504, in compile
    return self._compiler(dialect, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2964, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 492, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 601, in create_for_statement
    self._setup_for_generate()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 620, in _setup_for_generate
    self._legacy_join(query._legacy_setup_joins)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 1455, in _legacy_join
    self._join_left_to_right(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 1495, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 1655, in _join_determine_implicit_left_side
    raise sa_exc.InvalidRequestError(
```

**Versions.**
 - OS: macOS Big Sur 11.2.3
 - Python: 3.9.2
 - SQLAlchemy: 1.4
 - Database: Postgres 12.5

**Comment by zzzeek** [comment]
hey there -

OK what's likely happening here is that you're calling with_entities(Variant), so when the join() is calculated (this now occurs later, rather than sooner), it knows nothing about HomozygousVariant.   This is a bit of a change but I'm going to ask that you write your query something like this:

     session.query(Variant).select_from(HomozygousVariant).join(Variant, and_(...))

there's no way for the SQLAlchemy to know the "left side" here otherwise because the with_entities() has already taken effect when it looks at your join().

**Comment by alanwilter** [comment]
Thanks a lot @zzzeek

Indeed, I tried this at first on my own but though my hunch was right my syntax was wrong.
I got to fix other similar issues but I have one still standing and if I can ask for help, here it is:
On v. 1.3 I need to do **`op("%%")`**
```python
            db_session.query(Gene, Gene.other_names.op("<->")(query).label("distance"))
            .filter(Gene.other_names.op("%%")(query))
            .order_by("distance", asc(func.lower(Gene.gene_name)))
            .limit(limit)
            .all()
```
But on v. 1.4, I need to do  **`op("%")`**. 
Is there a way to reconcile both versions?

**Comment by zzzeek** [comment]
heh....so that came in very late in 1.4 and the fact that nobody's ever reported that led me to believe that OK, this is not a widely used thing so we can just fix it, and here we are two days in the release and you're hitting it.

you will get the modulus operator if you use the Python % operator directly, can you try that?    otherwise you need to do something like this:

```
if sqlalchemy.__version__.startswith("1.3"):
    def percent_op(left, right):
        return left.op("%%")(right)
else:
    def percent_op(left, right):
        return left.op("%")(right)

```

SQLAlchemy does the percent escaping for all other ad-hoc constructs like that and op() was an oversight (Since we already have "%" by just using "%", but I realize PG has a different meaning for this operator)

**Comment by alanwilter** [comment]
Thanks for that. I'll close this issue then.

**Comment by zzzeek** [comment]
#6503 proposes maybe query.join() could memoize the current joinpoint to help this case.
