### ISSUE TITLE
AssertionError in _make_proxy when subclass of AbstractConcreteBase have column with name "type"

### ISSUE THREAD

**Issue by AvachaBay** [sqlalchemy/sqlalchemy#6090]
**Describe the bug**
AssertionError in _make_proxy when subclass of AbstractConcreteBase have column with name "type". All works when subclass doesn't have column "type".

**Expected behavior**
configure_mappers() without errors

**To Reproduce**

```py
import sqlalchemy as sa

from sqlalchemy.ext.declarative import AbstractConcreteBase, declarative_base
from sqlalchemy.orm import configure_mappers

Base = declarative_base()


class Post(AbstractConcreteBase, Base):
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)


class ForumPost(Post):
    __tablename__ = 'posts_forums'
    
    type = sa.Column(sa.Text)
    
    __mapper_args__ = {
        'polymorphic_identity': 'posts_forums',
        'concrete': True
    }


class MarketplacePost(Post):
    __tablename__ = 'posts_marketplaces'
    
    options = sa.Column(sa.JSON)
    
    __mapper_args__ = {
        'polymorphic_identity': 'posts_marketplaces',
        'concrete': True
    }


configure_mappers()
```

**Error**

```
Traceback (most recent call last):
  File "C:/path/sqlalchemy_minimal.py", line 35, in <module>
    configure_mappers()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3354, in configure_mappers
    _configure_registries(_all_registries(), cascade=True)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3378, in _configure_registries
    Mapper.dispatch._for_class(Mapper).before_configured()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\event\attr.py", line 256, in __call__
    fn(*args, **kw)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\events.py", line 743, in wrap
    fn(*arg, **kw)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 326, in before_configured
    self.cls.__declare_first__()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\ext\declarative\extensions.py", line 244, in __declare_first__
    cls._sa_decl_prepare_nocascade()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\ext\declarative\extensions.py", line 294, in _sa_decl_prepare_nocascade
    m = to_map.map()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1013, in map
    return super(_DeferredMapperConfig, self).map(mapper_kw)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 936, in map
    self._prepare_mapper_arguments(mapper_kw)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 864, in _prepare_mapper_arguments
    mapper_args = self.mapper_args_fn()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\ext\declarative\extensions.py", line 289, in mapper_args
    args["polymorphic_on"] = pjoin.c[discriminator_name]
  File "C:\path\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1095, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 746, in columns
    self._populate_column_collection()
  File "C:\path\.venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 1620, in _populate_column_collection
    self.element._generate_fromclause_column_proxies(self)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 3852, in _generate_fromclause_column_proxies
    select_0._generate_fromclause_column_proxies(subquery)
  File "C:\path\.venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 5755, in _generate_fromclause_column_proxies
    c._make_proxy(
  File "C:\path\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 4338, in _make_proxy
    assert key == self.name
AssertionError

Process finished with exit code 1
```

**Versions.**
 - OS: Windows 10
 - Python: Python 3.8.2
 - SQLAlchemy: 1.4.1
 - Database: Postgresql 
 - DBAPI: psycopg2 2.8.6

**Comment by zzzeek** [comment]
OK so this is another one that is a bug on this end that I will fix, but it's also a bug on your end.  The ConcreteBase uses this name "type" to create the polymorphic selectable, and when I run your program on 1.3 I get a lot of warnings to this effect:

```
/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/base.py:557: SAWarning: Column 'type' on table <sqlalchemy.sql.selectable.Select at 0x7faf1de925e0; Select object> being replaced by <sqlalchemy.sql.elements.ColumnClause at 0x7faf1de929d0; type>, which has the same key.  Consider use_labels for select() statements.
```
you should move the virtual "type" column by using ``_concrete_discriminator_name``:

```
class Post(AbstractConcreteBase, Base):
    _concrete_discriminator_name = '_concrete_discriminator'

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)

```

you can observe a select for this class looks like:

```
SELECT pjoin.id, pjoin.options, pjoin.type, pjoin._concrete_discriminator 
FROM (SELECT posts_marketplaces.id AS id, posts_marketplaces.options AS options, CAST(NULL AS TEXT) AS type, 'posts_marketplaces' AS _concrete_discriminator 
FROM posts_marketplaces UNION ALL SELECT posts_forums.id AS id, CAST(NULL AS JSON) AS options, posts_forums.type AS type, 'posts_forums' AS _concrete_discriminator 
FROM posts_forums) AS pjoin

```

**Comment by zzzeek** [comment]
in 1.3, the query that's generated has the "type" twice and the discriminator is ignored, so I'm leaning towards this should raise an informative exception:

```python

SELECT pjoin.id AS pjoin_id, pjoin.options AS pjoin_options, pjoin.type AS pjoin_type 
FROM (SELECT posts_marketplaces.id AS id, posts_marketplaces.options AS options, CAST(NULL AS TEXT) AS type, 'posts_marketplaces' AS type 
FROM posts_marketplaces UNION ALL SELECT posts_forums.id AS id, CAST(NULL AS JSON) AS options, posts_forums.type AS type, 'posts_forums' AS type 
FROM posts_forums) AS pjoin
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Raise at Core / ORM concrete inh level for label overlap** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2647
