### ISSUE TITLE
Issue using func.current_date() in relationship primaryjoin

### ISSUE THREAD

**Issue by madeleineabed2** [sqlalchemy/sqlalchemy#6095]
**Describe the bug**

When using `func.current_date()` in a `relationship` `primaryjoin`, accessing that field after loading the object from the database emits an incorrect query that doesn't properly translate `func.current_date()`.

This issue doesn't occur with `sqlalchemy 1.3.23` and so this seems to be a regression.

**Expected behavior**

`func.current_date()` is properly translated (to `CURRENT_DATE` in this case specifically) and the relationship field can be accessed.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, ForeignKey, Date, MetaData, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, scoped_session, sessionmaker, selectinload

metadata = MetaData()
Base = declarative_base(metadata=metadata)


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    _date = Column(Date)
    b_id = Column(Integer, ForeignKey("b.id"))
    b = relationship("B")


class B(Base):
    __tablename__ = "b"

    id = Column(Integer, primary_key=True)
    a_s = relationship(
        "A",
        primaryjoin="and_(B.id == A.b_id, A._date >= func.current_date())",
        viewonly=True
    )


Session = scoped_session(sessionmaker())
engine = create_engine("sqlite:///:memory:", echo=True)
Base.metadata.bind = engine
Session.configure(bind=engine)
Base.metadata.create_all()

Session.add(B(id=1))
Session.commit()

print(Session.query(B).options(selectinload(B.a_s)).get(1).a_s)  # works
print(Session.query(B).get(1).a_s)  # doesn't work
```

**Error**

```
Traceback (most recent call last):
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "(": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/madeleine/fail.py", line 39, in <module>
    print(Session.query(B).get(1).a_s)  # doesn't work
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 449, in __get__
    return self.impl.get(state, dict_)
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 893, in get
    value = self.callable_(state, passive)
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 874, in _load_for_state
    return self._emit_lazyload(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 1029, in _emit_lazyload
    result = session.execute(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1653, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/sql/lambdas.py", line 480, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/madeleine/.local/share/virtualenvs/x-HyZwumyA/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT a.id AS a_id, a._date AS a__date, a.b_id AS a_b_id 
FROM a 
WHERE ? = a.b_id AND a._date >= current_date()]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Versions.**
 - OS: macOS Catalina 10.15.7
 - Python: 3.9.1
 - SQLAlchemy: 1.4.1
 - Database: SQLite 3
 - DBAPI: sqlite3

**Additional context**

Loading the same object with the `selectinload` eager loading option does not have this issue, and translates the query properly.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deannoate functions before matching .__class__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2655

**Comment by zzzeek** [comment]
this is a compiler bug that exists in 1.3 and previous versions also but was not encountered until usage of certain features by the ORM in 1.4.  thanks for reporting!

**Comment by madeleineabed2** [comment]
Cool, thanks for looking into this so quickly :)

**Comment by CaselIT** [comment]
> 
> 
> this is a compiler bug that exists in 1.3 and previous versions also but was not encountered until usage of certain features by the ORM in 1.4. thanks for reporting!

should't this be 1.3.x then?

**Comment by zzzeek** [comment]
> > this is a compiler bug that exists in 1.3 and previous versions also but was not encountered until usage of certain features by the ORM in 1.4. thanks for reporting!
> 
> shouldn't this be 1.3.x then?

it doesn't impact 1.3 because there's no part of the ORM that is using the "annotations" feature with SQL functions in this way.
