### ISSUE TITLE
Boolean column crashes mypy plugin

### ISSUE THREAD

**Issue by bryanforbes** [sqlalchemy/sqlalchemy#6109]
**Describe the bug**
Using a `Boolean` column in an ORM class crashes the mypy plugin

**Expected behavior**
`mypy` should exit with `Success: no issues found in 1 source file`

**To Reproduce**

```py
from sqlalchemy import Boolean, Column
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class TestBoolean(Base):
    __tablename__ = 'test_boolean'

    flag = Column(Boolean)
```

**mypy.ini**

```
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

**Error**

```
$ mypy --show-traceback test_boolean.py    
test_boolean.py:7: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.812
Traceback (most recent call last):
  File "mypy/semanal.py", line 4835, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1048, in visit_class_def
  File "mypy/semanal.py", line 1125, in analyze_class
  File "mypy/semanal.py", line 1134, in analyze_class_body_common
  File "mypy/semanal.py", line 1194, in apply_class_plugin_hooks
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 159, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 123, in _scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(cls, api, stmt, cls_metadata)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 380, in _scan_declarative_assignment_stmt
    python_type_for_type = _infer_type_from_decl_column(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 714, in _infer_type_from_decl_column
    python_type_for_type = _extract_python_type_from_typeengine(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 989, in _extract_python_type_from_typeengine
    assert False, "could not extract Python type from node: %s" % node
AssertionError: could not extract Python type from node: TypeInfo(
  Name(sqlalchemy.sql.sqltypes.Boolean)
  Bases(sqlalchemy.sql.type_api.Emulated, sqlalchemy.sql.type_api.TypeEngine[builtins.bool], sqlalchemy.sql.sqltypes.SchemaType)
  Mro(sqlalchemy.sql.sqltypes.Boolean, sqlalchemy.sql.type_api.Emulated, sqlalchemy.sql.type_api.TypeEngine, sqlalchemy.sql.visitors.Traversible, sqlalchemy.sql.sqltypes.SchemaType, sqlalchemy.sql.base.SchemaEventTarget, builtins.object)
  Names(
    __init__
    __visit_name__ (builtins.str)
    bind_processor
    create_constraint (Any)
    literal_processor
    name (Any)
    native (builtins.bool)
    python_type
    result_processor))
test_boolean.py:7: : note: use --pdb to drop into pdb
```

**Versions.**
 - OS: macOS 11.2.3
 - Python: 3.9.1
 - SQLAlchemy: 1.4.2
 - mypy: 0.812
 - Database: n/a
 - DBAPI: n/a

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add support for Boolean, Enum** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2663

**Comment by zzzeek** [comment]
thanks for reporting!
