### ISSUE TITLE
Criteria based loader options together with association_proxy issue

### ISSUE THREAD

**Issue by torsdag** [sqlalchemy/sqlalchemy#6131]
**Describe the bug**
I am running into an issue when using criteria based loader options together with a association_proxy. Looks to be related to the caching as the query executes fine the first time but fails when executed again.

**Expected behavior**
For the query to execute correctly when run again.

**To Reproduce**
```py
from sqlalchemy import (
    Column, Integer, String, ForeignKey, create_engine
)
from sqlalchemy.orm import (
    relationship, backref, declarative_base, sessionmaker, selectinload
)
from sqlalchemy.ext.associationproxy import (
    association_proxy
)


Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = Column(
        Integer, primary_key=True
    )


class Register(Base):
    __tablename__ = 'register'

    id = Column(
        Integer, primary_key=True
    )

    name = Column(
        String(64)
    )

    attribute_type = Column(
        String(64)
    )

    __mapper_args__ = {
        'polymorphic_on': attribute_type
    }


class ObjectRegister(Register):
    __mapper_args__ = {
        'polymorphic_identity': 'object_registry'
    }


class ObjectLink(Base):
    __tablename__ = 'object_link'

    id = Column(
        Integer, primary_key=True
    )

    entity_id = Column(
        Integer, ForeignKey(
            Entity.id
        )
    )

    entity = relationship(
        Entity, backref=backref(
            'links'
        )
    )

    object_register_id = Column(
        Integer, ForeignKey(ObjectRegister.id)
    )

    object_register = relationship(
        ObjectRegister
    )

    key = association_proxy(
        'object_register', 'name'
    )


engine = create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sessionmaker(
    bind=engine
)

session = Session()

session.add(
    Entity(
        id=1
    )
)
session.add(
    ObjectRegister(
        id=1, name='test'
    )
)


session.add(
    ObjectLink(entity_id=1, object_register_id=1)
)

session.commit()

query = session.query(
    Entity
)

query = query.options(
    selectinload(
        Entity.links.and_(
            ObjectLink.key.in_(
                ['test', 'test2']
            )
        )
    )
)

#Works
query.all()

#Failes the second time
query.all()

```

**Error**

```
Traceback (most recent call last):
  File ".../test.py", line 135, in <module>
    query.all()
  File "...venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2656, in all
    return self._iter().all()
  File "...venv/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1328, in all
    return self._allrows()
  File "...venv/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "...venv/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1236, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "...venv/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1629, in _fetchall_impl
    return list(self.iterator)
  File "...venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 122, in chunks
    post_load.invoke(context, path)
  File "...venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 1294, in invoke
    loader(context, path, states, self.load_keys, *arg, **kw)
  File "...venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 2843, in _load_for_path
    lambda q: q.options(*options)._update_compile_options(
  File "...venv/lib/python2.7/site-packages/sqlalchemy/sql/lambdas.py", line 474, in add_criteria
    return LinkedLambdaElement(other, parent_lambda=self, opts=opts)
  File "...venv/lib/python2.7/site-packages/sqlalchemy/sql/lambdas.py", line 568, in __init__
    self._retrieve_tracker_rec(fn, self, opts)
  File "...venv/lib/python2.7/site-packages/sqlalchemy/sql/lambdas.py", line 212, in _retrieve_tracker_rec
    rec.closure_bindparams, bindparams
  File "...venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 1407, in _with_value
    cloned = self._clone(maintain_key=maintain_key)
TypeError: _clone() got an unexpected keyword argument 'maintain_key'

Process finished with exit code 1

```

**Versions.**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - Python: Python 2.7.17
 - SQLAlchemy: 1.4.2
 - Database: mariadb / sqlite
 - DBAPI: any

**cheers**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Accept **kw in annotated._clone() method** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2675

**Comment by zzzeek** [comment]
this looks like our first regression *within* the 1.4 series due to #6055.  thanks for reporting.

**Comment by zzzeek** [comment]
ah not a regression, just a bug in the new stuff.

**Comment by torsdag** [comment]
thanks for looking at it so quickly

cheers
