### ISSUE TITLE
"Adjacency List" relationship implemented using a single `RelationshipProperty` fails to back populate during `append` when both the source and target object are of the same mapper class

### ISSUE THREAD

**Issue by tonywu7** [sqlalchemy/sqlalchemy#6137]
**Describe the bug**
 
For an ORM mapper (name it `Node`), and an ORM relationship (`Node.neighbors`) that is

- a many-to-many self-referential relationship `Node.neighbors -> Node`;
- implemented using a secondary join table having `FOREIGN KEY`s to the table mapped by `Node`;
- set up to back populate, such that for `a = Node()` and `b = Node()`, if `b in a.neighbors` then`a in b.neighbors`;

When such a relationship is also inherited by additional polymorphic subclasses of `Node`, back-population works as expected when the owning class and the target class of the relationship are different classes, but fails when they are the same.

**Versions**
 - OS: macOS 11.2.3
 - Python: 3.8.8
 - SQLAlchemy: 1.4.2
 - Database: SQLite
 - DBAPI: `pysqlite`

**To Reproduce**

Run the following as a script:

```py
from __future__ import annotations

from typing import List

from sqlalchemy import MetaData, Table, __version__, create_engine, types
from sqlalchemy.orm import (Session, declarative_base, declared_attr,
                            relationship, scoped_session, sessionmaker)
from sqlalchemy.schema import Column, ForeignKey, Index

metadata = MetaData(
    naming_convention={
        'ix': 'ix_%(table_name)s_%(column_0_N_name)s',
        'uq': 'uq_%(table_name)s_%(column_0_N_name)s',
        'ck': 'ck_%(table_name)s_%(column_0_N_name)s',
        'fk': 'fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s',
        'pk': 'pk_%(table_name)s',
    },
)
RESTRICT = 'RESTRICT'
CASCADE = 'CASCADE'

Base = declarative_base(metadata=metadata)


class BaseNode(Base):
    """All ORM mappers inherit from this class.

    `BaseNode` does not define relationships, but only primary keys and polymorphism attributes.
    It is the target of foreign keys in the adjacency list secondary join tables that will
    be used for all relationships on subclasses of `BaseNode`.
    """
    id: int = Column(types.Integer(), primary_key=True, autoincrement=True)
    polymorph: str = Column(types.String())

    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

    @declared_attr
    def __mapper_args__(cls):
        return {
            'polymorphic_identity': 'BaseNode',
            'polymorphic_on': cls.polymorph
        }


adj_undirected = Table(
    'adj_undirected', metadata,
    Column('id', types.Integer(), primary_key=True, autoincrement=True),
    Column('x', types.Integer(), ForeignKey(BaseNode.id, ondelete=CASCADE, onupdate=RESTRICT), nullable=False),
    Column('y', types.Integer(), ForeignKey(BaseNode.id, ondelete=CASCADE, onupdate=RESTRICT), nullable=False),
    Index(None, 'x', 'y', unique=True),
)


class Node(BaseNode):
    id: int = Column(types.Integer(), ForeignKey(BaseNode.id, ondelete=CASCADE, onupdate=RESTRICT), primary_key=True)

    @declared_attr
    def __mapper_args__(cls):
        return {
            'polymorphic_identity': 'Node',
        }

    # Property for a many-to-many self-referential undirected relationship.
    # For Node A and Node B, if B in A.neighbors then A in B.neighbors.
    neighbors: List[Node] = relationship(
        'Node', back_populates='neighbors', secondary=adj_undirected,
        primaryjoin=BaseNode.id == adj_undirected.c.x,
        secondaryjoin=BaseNode.id == adj_undirected.c.y,
        cascade_backrefs=False,
    )

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return f'Node {self.id}'


class RedNode(Node):
    id: int = Column(types.Integer(), ForeignKey(Node.id, ondelete=CASCADE, onupdate=RESTRICT), primary_key=True)

    @declared_attr
    def __mapper_args__(cls):
        return {
            'polymorphic_identity': 'RedNode',
        }


class GreenNode(Node):
    id: int = Column(types.Integer(), ForeignKey(Node.id, ondelete=CASCADE, onupdate=RESTRICT), primary_key=True)

    @declared_attr
    def __mapper_args__(cls):
        return {
            'polymorphic_identity': 'GreenNode',
        }


def test():
    print(f'SQLAlchemy version {__version__}')
    engine = create_engine('sqlite:///:memory:')
    metadata.create_all(engine)
    get_session = scoped_session(sessionmaker(bind=engine, autoflush=False, future=True))
    session: Session = get_session()

    node_1 = RedNode()
    node_2 = GreenNode()
    node_1.id = 1
    node_2.id = 2

    node_1.neighbors.append(node_2)
    assert node_1 in node_2.neighbors

    session.add_all([node_1, node_2])
    session.flush()

    node_3 = RedNode()
    node_4 = RedNode()
    node_3.id = 3
    node_4.id = 4

    node_3.neighbors.append(node_4)
    assert node_3 in node_4.neighbors  # Fails

    session.add_all([node_3, node_4])
    session.flush()


if __name__ == '__main__':
    test()
```

**Expected**

No error when running the above code directly using `python`.

**Error**

`AssertionError` for the second `assert` statement in the `test()` function:

```py
assert node_3 in node_4.neighbors  # Fails
```

but not for the first one:

```py
assert node_1 in node_2.neighbors
```

suggesting unexpected inconsistent `back_populates` behaviors.

```
Traceback (most recent call last):
  File "undirected.py", line 154, in <module>
    test()
  File "undirected.py", line 147, in test
    assert node_3 in node_4.neighbors  # Fails
AssertionError
```

**Additional context/explanation**

I am attempting to implement a self-referential relationship that resembles an undirected graph, following the pattern
discussed in [Adjacency List Relationships](https://docs.sqlalchemy.org/en/14/orm/self_referential.html) in the documentation,
with the key distinction being

- **Instead of placing the foreign key attributes onto the `Node` class itself,**
**the relationship is configured to use a secondary join-table.**
- **Instead of having separate `parent` and `children` relationship properties,**
**there is a single `neighbors` property that `back_populates` the same `neighbors` property.**

In the example code above, class `BaseNode` defines a primary key `id` and a `polymorph` column for join table polymorphism. Class `BaseNode` is inherited by all other mappers.

`adj_undirected` defines a secondary `Table` whose `x` and `y` columns are both foreign keys to `BaseNode.id`.

`Node` inherits from `BaseNode`, and defines the self-referential relationship
that uses `adj_undirected` as the join table.

`RedNode` and `GreenNode` (names are for illustrative purposes) inherit from `Node` with no additional overrides (other than the polymorphic identity).

In the `test()` function, appending a `GreenNode` to `RedNode.neighbors`,
and the `RedNode` will be appended to `GreenNode.neighbors`. However, when a `RedNode` is appended to another `RedNode`'s `.neighbors` list, back population
does not occur.

---

I attempted to debug through `sqlalchemy`'s internal code. While I am not familiar
with how the relationship instrumentation is implemented, I noticed a line whose results differ between the two scenarios:

**sqlalchemy/orm/attributes.py:1691**

```py
if (
    initiator is not check_append_token  # Line in question
    and initiator is not check_bulk_replace_token
):
    ...
```

In the second (failing) scenario, the `append` operation seems to be skipped
because `initiator is not check_append_token` evaluates to `False`, whereas in
the first scenario, it is `True`.

---

**Have a nice day!**

**Comment by zzzeek** [comment]
i may not have time to look at this for a bit, it would be very helpful if you could determine if this is a 1.4 regression or not by running your test script on SQLAlchemy 1.3 also.   thanks!

**Comment by tonywu7** [comment]
I've ran a few more tests, tweaking several aspects:

- Run the script using 1.3.19 or 1.3.23
- Remove `future=True` from the call to `sessionmaker` while using 1.4
- Remove `cascade_backref=False` from call to `relationship` (doesn't seem relevant but I ran just in case)
- Persist one of the `Node` object before adding the relationship
- Persist both of the objects before adding the relationship

The problem (that back population happens inconsistently, instead of always or never happens) exists in all independent cases.

Additionally, I wrote a much shorter test script that removes polymorphism from the setup:

```py
from sqlalchemy import MetaData, Table, __version__, create_engine, types
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, relationship, scoped_session, sessionmaker
from sqlalchemy.schema import Column, ForeignKey, Index

metadata = MetaData()
RESTRICT = 'RESTRICT'
CASCADE = 'CASCADE'

Base = declarative_base(metadata=metadata)


class Node(Base):
    __tablename__ = 'node'
    id: int = Column(types.Integer(), primary_key=True, autoincrement=True)

    # Property for a many-to-many self-referential undirected relationship.
    # For Node A and Node B, if B in A.neighbors then A in B.neighbors.
    neighbors = relationship(
        'Node', back_populates='neighbors', secondary='adj_undirected',
        primaryjoin='Node.id == adj_undirected.c.x',
        secondaryjoin='Node.id == adj_undirected.c.y',
    )


adj_undirected = Table(
    'adj_undirected', metadata,
    Column('id', types.Integer(), primary_key=True, autoincrement=True),
    Column('x', types.Integer(), ForeignKey(Node.id, ondelete=CASCADE, onupdate=RESTRICT), nullable=False),
    Column('y', types.Integer(), ForeignKey(Node.id, ondelete=CASCADE, onupdate=RESTRICT), nullable=False),
    Index(None, 'x', 'y', unique=True),
)


def test():
    print(f'SQLAlchemy version {__version__}')
    engine = create_engine('sqlite:///:memory:')
    metadata.create_all(engine)
    get_session = scoped_session(sessionmaker(bind=engine, autoflush=False))
    session: Session = get_session()

    node_1 = Node()
    node_2 = Node()
    node_1.id = 1
    node_2.id = 2

    node_1.neighbors.append(node_2)
    assert node_1 in node_2.neighbors  # Fails

    session.add_all([node_1, node_2])
    session.flush()


if __name__ == '__main__':
    test()
```

In this case, there is no comparative tests, but it remains that the back population does not occur.

**Comment by zzzeek** [comment]
Just missed that, I had my own narrowed down version of what you're doing:

```python
from __future__ import annotations

from typing import List

from sqlalchemy import Table
from sqlalchemy import types
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.schema import Column
from sqlalchemy.schema import ForeignKey

Base = declarative_base()


class Node(Base):
    __tablename__ = "node"
    id: int = Column(types.Integer(), primary_key=True, autoincrement=True)

    neighbors: List[Node] = relationship(
        "Node",
        back_populates="neighbors",
        secondary="adj_undirected",
        primaryjoin="Node.id == adj_undirected.c.x",
        secondaryjoin="Node.id == adj_undirected.c.y",
    )


adj_undirected = Table(
    "adj_undirected",
    Base.metadata,
    Column("id", types.Integer(), primary_key=True, autoincrement=True),
    Column("x", types.Integer(), ForeignKey(Node.id), nullable=False),
    Column("y", types.Integer(), ForeignKey(Node.id), nullable=False),
)


class RedNode(Node):
    pass

node_1 = Node()
node_2 = RedNode()

node_1.neighbors.append(node_2)
assert node_1 in node_2.neighbors


node_3 = Node()
node_4 = Node()

node_3.neighbors.append(node_4)
assert node_3 in node_4.neighbors  # Fails

```


at the moment this is kind of expected, but I need to see what the history is for this, because I'm fairly certain we have tests for this kind of mapping and I'm not sure what the policy was to be here.

the thing you're hitting is the guard against a recursion overflow.   if you change it:

```diff
diff --git a/lib/sqlalchemy/orm/attributes.py b/lib/sqlalchemy/orm/attributes.py
index 610ee2726..4bed423c4 100644
--- a/lib/sqlalchemy/orm/attributes.py
+++ b/lib/sqlalchemy/orm/attributes.py
@@ -1692,8 +1692,9 @@ def backref_listeners(attribute, key, uselist):
         )
 
         if (
-            initiator is not check_append_token
-            and initiator is not check_bulk_replace_token
+            True
+#            initiator is not check_append_token
+#            and initiator is not check_bulk_replace_token
         ):
             child_impl.append(
                 child_state,

```

then it has no way to know when to stop:

```
# 100s of lines
 File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 1699, in emit_backref_from_collection_append_event
    child_impl.append(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 1425, in append
    collection.append_with_event(value, initiator)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/collections.py", line 627, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/collections.py", line 1131, in append
    item = __set(self, item, _sa_initiator)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/collections.py", line 1096, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/collections.py", line 727, in fire_append_event
    return self.attr.fire_append_event(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 1348, in fire_append_event
    for fn in self.dispatch.append:
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/event/attr.py", line 326, in __iter__
    return chain(self.parent_listeners, self.listeners)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

I guess the reason this is usually not an issue is that adjacency lists usually use one-to-many/many-to-one, and in that case I would assume the tokens are set up to not collide with each other and it all works out.   so perhaps we don't have much coverage for this case using many-to-many.

in any case, this seems like it would be a really old issue that nobody has ever reported.

**Comment by zzzeek** [comment]
oh this is actually neighbors to neighbors, WOW, OK, that's actually totally novel.   We've never supported a relationship that back populates to itself, that's not supposed to work at all.       Classically, this would have been backref:

```python
    neighbors: List[Node] = relationship(
        "Node",
        backref="neighbors",
#        back_populates="neighbors",
        secondary="adj_undirected",
        primaryjoin="Node.id == adj_undirected.c.x",
        secondaryjoin="Node.id == adj_undirected.c.y",
    )

```

that raises:

sqlalchemy.exc.ArgumentError: Error creating backref 'neighbors' on relationship 'Node.neighbors': property of that name exists on mapper 'mapped class Node->node'

the bug here is that the mapping you're doing should probably be raising an error at least for now.     All relationships have an explicit **direction** , in this case your "x , y" is a direction.   so to create an "undirected" view you would want to use a `@hybrid_property`.      

SQL relationships don't actually support "undirected" relationships within the relational model (NOTE: I could be totally proven wrong by some deep relational algrebra geniuses on that, which I am not, would love to see it!)   I noticed theres another (surprising!  but then not surprising!) effect of your first test which is that it inserts *two* rows, because your backref trick is appending both nodes to each.  That makes the relationship *act* like it's bidrectional from a SQL point of view, but it's really not.

From a SQL point of view, we have Node(id=1) and Node(id=2), we add one row to adj_undirected: (x=1, y=2).   Right there we can see a row in this table is not "undirected", if we want to query for the neighbors of Node(id=1) we need to query the table in terms of x=(our node) ,y=(what we're looking for), but to get Node(id=2) we would need to query the table in terms of x=(what we're looking for), y=(our node), else we'd not get a result.     So you'd really want to call this table "adj_directed", then build a system by which you know you're putting two rows in for a particular "undirected" setup.

SQLAlchemy thinks of things in terms of the second approach, where an append() to a list means **one** row.    it's kind of a quirk of the backref thing that it's putting two rows here.

For this relationship I would likely create a third mapping called DirectedEdge(), link Node to DirectedEdge directly, and then you would make sure that two DirectedEdge records go in for a particular "undirected" mapping.     this would not be sidestepping the assumptions currently made by SQLAlchemy.

I think for this to work exactly as you have it, there likely should be some flag on relationship() that signals "hey this is a double-entry relationship, do <new, not currently implemented or tested behaviors X, Y, and Z> to suit this case".

**Comment by tonywu7** [comment]
This is super interesting! In the program that I am designing, I've been trying to make the database resemble a generic mathematical undirected graph, and I didn't realize (from reading the docs) that backrefs are never intended to be used this way. That it has worked so long in my program without issues is indeed a pleasant surprise :)

I hope that eventually there will be some support for this (apparently rare) use case. In the meantime, following the idea that undirectional relationship can be emulated using bidirectional ones, I made the following solution using a `DirectedEdge` association object, the `association_proxy` extension, plus two "private" `relationship` properties:

```py
from __future__ import annotations

from typing import List

from sqlalchemy import MetaData, __version__, create_engine, types
from sqlalchemy.orm import Session, relationship, scoped_session, sessionmaker, backref, declarative_base, declared_attr
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.schema import Column, ForeignKey, Index

metadata = MetaData()

Base = declarative_base(metadata=metadata)


class Node(Base):
    __tablename__ = 'node'
    id: int = Column(types.Integer(), primary_key=True, autoincrement=True)

    _outgoing_edges: List[DirectedEdge]
    _incoming_edges: List[DirectedEdge]

    neighbors = association_proxy('_outgoing_edges', 'dst')

    def connect(self, other: Node):
        # Simply creating the edges is enough.
        DirectedEdge(src=other, dst=self)
        DirectedEdge(src=self, dst=other)

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return f'Node {self.id}'


class DirectedEdge(Base):
    __tablename__ = 'edges'

    id: int = Column(types.Integer(), primary_key=True, autoincrement=True)
    src_id: int = Column('src_id', types.Integer(), ForeignKey(Node.id), nullable=False)
    dst_id: int = Column('dst_id', types.Integer(), ForeignKey(Node.id), nullable=False)

    src = relationship(
        Node, foreign_keys=src_id, cascade_backrefs=False, uselist=False,
        backref=backref('_outgoing_edges', cascade='all, delete-orphan', cascade_backrefs=False),
    )
    dst = relationship(
        Node, foreign_keys=dst_id, cascade_backrefs=False, uselist=False,
        backref=backref('_incoming_edges', cascade='all, delete-orphan', cascade_backrefs=False),
    )

    @declared_attr
    def __table_args__(self):
        return (Index(None, 'src_id', 'dst_id', unique=True),)

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return f'Node {self.src.id} -> Node {self.dst.id}'


def test():
    print(f'SQLAlchemy version {__version__}')
    engine = create_engine('sqlite:///:memory:')
    metadata.create_all(engine)
    get_session = scoped_session(sessionmaker(bind=engine, autoflush=False))
    session: Session = get_session()

    node_1 = Node()
    node_2 = Node()
    node_1.id = 1
    node_2.id = 2

    node_1.connect(node_2)
    assert node_1 in node_2.neighbors

    session.add_all([node_1, node_2])
    session.commit()


if __name__ == '__main__':
    test()
```

which seems to be working with no issues, with the caveat being it needs an additional helper method `Node.connect(self, other)`, as I can't find a way to accomplish creating the edges through `association_proxy`'s `creator` option (is there a way to use an instance method as the `creator`?)

In any case, thank you so much for explaining this through!

**Comment by zzzeek** [comment]
there might be a way using the [validates](https://docs.sqlalchemy.org/en/14/orm/mapped_attributes.html?highlight=validates#simple-validators) decorator, but it has the same recursive issue that would need some careful tailoring to avoid.  here's a version that causes a recursion issue, maybe you can work out how to keep if from going into a loop.  But I think `node.connect()` is much cleaner here.

```
class DirectedEdge(Base):
    # ...

    @validates("dst", "src")
    def _add_src(self, key, obj):
        if key == "dst" and "src" not in obj.__dict__:
            obj.src = self
            DirectedEdge(src=obj, dst=self)
        elif key == "src" and "dst" not in obj.__dict__:
            obj.dst = self
            DirectedEdge(src=self, dst=obj)

```

**Comment by khouli** [comment]
I just ran into this issue myself and was also surprised that it turns out to be an exotic use-case requiring some legwork. Have there been any relevant developments since this issue was opened?

Here's the solution I came up with. Compared to the above, it avoids redundant edges:

```
from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import create_engine
from sqlalchemy import select
from sqlalchemy import Table, Column, Integer, ForeignKey
from sqlalchemy import CheckConstraint
from sqlalchemy.orm import sessionmaker, registry
from sqlalchemy.orm import Mapped, mapped_column, relationship


reg = registry()


edge_table = Table(
    "edge",
    reg.metadata,
    Column("node_id_lt",  Integer, ForeignKey("node.id"), primary_key=True),
    Column("node_id_gt", Integer, ForeignKey("node.id"), primary_key=True, index=True),
    CheckConstraint("node_id_lt < node_id_gt"),
)


@reg.mapped_as_dataclass
class Node:
    __tablename__ = "node"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    _neighbors_lt: Mapped[list["Node"]] = relationship(
            default_factory=list,
            repr=False,
            argument="Node",
            secondary=edge_table,
            primaryjoin=(id == edge_table.c.node_id_lt),
            secondaryjoin=(id == edge_table.c.node_id_gt),
            back_populates="_neighbors_gt",
        )

    _neighbors_gt: Mapped[list["Node"]] = relationship(
            default_factory=list,
            repr=False,
            argument="Node",
            secondary=edge_table,
            primaryjoin=(id == edge_table.c.node_id_gt),
            secondaryjoin=(id == edge_table.c.node_id_lt),
            back_populates="_neighbors_lt",
        )

    @dataclass
    class NeighborsProxy:
        node: Node

        __emulates__ = list

        def __repr__(self):
            return repr(list(self.__iter__()))

        def append(self, other_node):
            if self.node.id < other_node.id:
                self.node._neighbors_lt.append(other_node)
            elif self.node.id > other_node.id:
                self.node._neighbors_gt.append(other_node)
            else:
                raise ValueError

        def remove(self, other_node):
            if self.node.id < other_node.id:
                self.node._neighbors_lt.remove(other_node)
            elif self.node.id > other_node.id:
                self.node._neighbors_gt.remove(other_node)
            else:
                raise ValueError

        def extend(self, other_nodes):
            other_nodes_1 = []
            other_nodes_2 = []
            for other_node in other_nodes:
                if self.node.id < other_node.id:
                    other_nodes_1.append(other_node)
                elif self.node.id > other_node.id:
                    other_nodes_2.append(other_node)
                else:
                    raise ValueError
            self.node._neighbors_lt.extend(other_nodes_1)
            self.node._neighbors_gt.extend(other_nodes_2)

        def __iter__(self):
            yield from self.node._neighbors_lt
            yield from self.node._neighbors_gt

    @property
    def neighbors(self):
        return Node.NeighborsProxy(self)

    def __repr__(self):
        neighbors_repr = ", ".join((f"Node(id={n.id})" for n in self.neighbors))
        return f"{self.__class__.__name__}(id={self.id}, neighbors=[{neighbors_repr}])"


engine = create_engine('sqlite:///:memory:', echo=True)
reg.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

node1 = Node(1)
node2 = Node(2)
node3 = Node(3)

assert list(node1.neighbors) == []
assert list(node2.neighbors) == []
assert list(node3.neighbors) == []

node1.neighbors.append(node2)
node2.neighbors.append(node3)
node3.neighbors.append(node1)

assert list(node1.neighbors) == [node2, node3]
assert list(node2.neighbors) == [node3, node1]
assert list(node3.neighbors) == [node2, node1]

session.add_all([node1, node2, node3])
session.commit()

print(node1)
print(node2)
print(node3)
```

I tried extracting this out of the `Node` class body and into something potentially reusable but it's very awkward:

```
from typing import Callable
from operator import lt

class SymmetricManyToMany:
    def __init__(self, key: str, adjacencies_1_name: str, adjacencies_2_name: str, compare: Callable=lt):
        self.key = key
        self.adjacencies_1 = adjacencies_1_name
        self.adjacencies_2 = adjacencies_2_name
        self.compare = compare

    def __set_name__(self, _, name: str):
        key = self.key
        adjacencies_1 = self.adjacencies_1
        adjacencies_2 = self.adjacencies_2
        compare = self.compare

        class Proxy:
            def __init__(self, obj):
                self.obj = obj

            __emulates__ = list

            def __repr__(self):
                return repr(list(self.__iter__()))

            def append(self, other):
                if compare(getattr(self.obj, key), getattr(other, key)):
                    getattr(self.obj, adjacencies_1).append(other)
                else:
                    getattr(self.obj, adjacencies_2).append(other)

            def remove(self, other):
                if compare(getattr(self.obj, key), getattr(other, key)):
                    getattr(self.obj, adjacencies_1).remove(other)
                else:
                    getattr(self.obj, adjacencies_2).remove(other)

            def extend(self, others):
                others_1 = []
                others_2 = []
                for other in others:
                    if compare(getattr(self.obj, key), getattr(other, key)):
                        others_1.append(other)
                    else:
                        others_2.append(other)
                getattr(self.obj, adjacencies_1).extend(other_1)
                getattr(self.obj, adjacencies_2).extend(other_2)

            def __iter__(self):
                yield from getattr(self.obj, adjacencies_1)
                yield from getattr(self.obj, adjacencies_2)

        self.Proxy = Proxy

    def __get__(self, obj, _):
        return self.Proxy(obj)


def make_symmetric_adjacencies(
        cls_name, foreign_key, foreign_key_name,
        secondary, remote_key_1, remote_key_2,
        half_adjacency_name_1, half_adjacency_name_2
        ):
    half_adjacency_1: Mapped[list[cls_name]] = relationship(
            default_factory=list,
            repr=False,
            argument=cls_name,
            secondary=secondary,
            primaryjoin=(foreign_key == remote_key_1),
            secondaryjoin=(foreign_key == remote_key_2),
            back_populates=half_adjacency_name_2,
        )
    half_adjacency_2: Mapped[list[cls_name]] = relationship(
            default_factory=list,
            repr=False,
            argument=cls_name,
            secondary=secondary,
            primaryjoin=(foreign_key == remote_key_2),
            secondaryjoin=(foreign_key == remote_key_1),
            back_populates=half_adjacency_name_1,
        )
    full_adjacency = SymmetricManyToMany(foreign_key_name, half_adjacency_name_1, half_adjacency_name_2)
    return full_adjacency, half_adjacency_1, half_adjacency_2


@reg.mapped_as_dataclass
class Node:
    __tablename__ = "node"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    neighbors, _neighbors_lt, _neighbors_gt = make_symmetric_adjacencies(
        "Node", id, "id",
        edge_table, edge_table.c.node_id_lt, edge_table.c.node_id_gt,
        "_neighbors_lt", "_neighbors_gt"
        )

    def __repr__(self):
        neighbors_repr = ", ".join((f"Node(id={n.id})" for n in self.neighbors))
        return f"{self.__class__.__name__}(id={self.id}, neighbors=[{neighbors_repr}])"
```

Is there a better way to do this these days?

> SQL relationships don't actually support "undirected" relationships within the relational model (NOTE: I could be totally proven wrong by some deep relational algrebra geniuses on that, which I am not, would love to see it!)

I'm not a deep relational algebra guru either, but in terms of theory, trivially, you can just have an undirected edge itself as an element in a tuple since the tuples in relational algebra can contain all sorts of mathematical objects as long as they have some notion of equality. But yeah, there isn't unordered tuple comparison like you're thinking.

**Comment by zzzeek** [comment]
> I just ran into this issue myself and was also surprised that it turns out to be an exotic use-case requiring some legwork. Have there been any relevant developments since this issue was opened?

nope, what you see here is the issue

> Is there a better way to do this these days? 

my comment above, where it looks like I was doing a lot of deep thinking on this, is from 2021, which is not really that long ago, we were well into the new architecture by then so not much has changed since.


> Any pointers for where I should look in the documentation or code if I want to fiddle with this a bit more?

I mean, read all the relationship config docs, which it looks like you already did :)  the main thing is that any kind of way of doing things needs to have feature and test support in SQLAlchemy for it to be considered "a thing", otherwise some pattern that sort of works might break someday because we change something.
