### ISSUE TITLE
Behavior of StaticPool seems to have changed with 1.4.3

### ISSUE THREAD

**Issue by wyattanderson** [sqlalchemy/sqlalchemy#6145]
**Describe the bug**

After upgrading to SQLAlchemy 1.4.3, an `Engine` created with a `StaticPool` and a single connection passed via `creator` is no longer usable after disposal.

Caveat: the reproduction code shows roughly what's being done. The original author is no longer around, and I have absolutely no context on why the engine is created this way. It's possible, if not likely, that we're just doing it wrong. But it works with SQLAlchemy 1.4.2.

Likely triggered by changes to `StaticPool` in 502be87a0b5c7bfa28db62b4af867457cd29a5fa.

**Expected behavior**

Calling `engine.connect()` after `engine.dispose()` succeeds, returning the never-closed DBAPI connection.

**To Reproduce**
```
import pymysql
from sqlalchemy import create_engine
from sqlalchemy.pool import StaticPool

connection = pymysql.connect(
    **{
        "host": "localhost",
        "db": "test",
        "user": "root",
        "password": "password",
    }
)

engine = create_engine(
    "mysql+pymysql://", poolclass=StaticPool, creator=lambda: connection, echo=True
)
conn = engine.connect()
engine.dispose()

# DBAPI (conn.connection.connection) is *open* at this point in 1.4.2, but
# *closed* in 1.4.3.

# This fails under SQLAlchemy 1.4.3 (but passes under 1.4.2) with an
# pymysql.err.InterfaceError: (0, '') exception
engine.connect()
```

**Error**

```
Traceback (most recent call last):
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3113, in _wrap_pool_connect
    return fn()
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 446, in _do_get
    rec = self.connection
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1095, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 406, in connection
    return _ConnectionRecord(self)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 612, in __connect
    pool.dispatch.connect(self.connection, self)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 320, in __call__
    fn(*args, **kw)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 659, in on_connect
    do_on_connect(conn)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 130, in on_connect
    cursor.execute("SET NAMES %s" % charset_name)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/wanderson/.virtualenvs/sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
```

**Versions.**
 - OS: Mac OS X 10.15.6
 - Python: 3.8.7
 - SQLAlchemy: 1.4.3
 - Database: MySQL
 - DBAPI: PyMySQL 1.0.2

**Comment by zzzeek** [comment]
OK I just put bug/regression but looking at the code, I dont think this is a bug.  dispose() was not working before, and now it is.     I didnt think anyone was really using `StaticPool` which is why I just went and changed it, but certainly if you call dispose(), you should expect the connection to be closed, that's what dispose() documents as doing.  

is it possible you simply could use the normal QueuePool or NullPool for MySQL backends?  there's no need to use StaticPool.  Or, don't call dispose() if you dont mean to actually close the connections in the pool.

**Comment by zzzeek** [comment]
or of course use a real callable for your creator....

**Comment by wyattanderson** [comment]
> OK I just put bug/regression but looking at the code, I dont think this is a bug. dispose() was not working before, and now it is. I didnt think anyone was really using `StaticPool` which is why I just went and changed it, but certainly if you call dispose(), you should expect the connection to be closed, that's what dispose() documents as doing.
> 
> is it possible you simply could use the normal QueuePool or NullPool for MySQL backends? there's no need to use StaticPool. Or, don't call dispose() if you dont mean to actually close the connections in the pool.

Yeah, it sounds like our code is Doing It Wrong. Just wanted to confirm. Thanks!
