### ISSUE TITLE
in_ operator fails with ArgumentError

### ISSUE THREAD

**Issue by Andrey-mp** [sqlalchemy/sqlalchemy#6149]
**Describe the bug**
we use 'in_' operator in the code https://github.com/openstack/ec2-api/blob/master/ec2api/db/sqlalchemy/api.py#L226
It worked with version 1.3.23 and it started to fail with new version (now I see 1.4.2).

**Expected behavior**
regression is not seen

**To Reproduce**
run tox -epy36 for project https://github.com/openstack/ec2-api

**Error**

```
ec2api.tests.unit.test_db_api.DbApiTestCase.test_get_public_items
-----------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/ec2api/tests/unit/test_db_api.py", line 296, in test_get_public_items'
    b"    items = db_api.get_public_items(self.context, 'fake',"
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/ec2api/db/api.py", line 115, in get_public_items'
    b'    return IMPL.get_public_items(context, kind, item_ids)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/ec2api/db/sqlalchemy/api.py", line 72, in wrapper'
    b'    return f(*args, **kwargs)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/ec2api/db/sqlalchemy/api.py", line 226, in get_public_items'
    b'    query = query.filter(models.Item.id.in_(item_ids))'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 604, in in_'
    b'    return self.operate(in_op, other)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 289, in operate'
    b'    return op(self.comparator, *other, **kwargs)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 1395, in in_op'
    b'    return a.in_(b)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 604, in in_'
    b'    return self.operate(in_op, other)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/orm/properties.py", line 424, in operate'
    b'    return op(self.__clause_element__(), *other, **kwargs)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 1395, in in_op'
    b'    return a.in_(b)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 604, in in_'
    b'    return self.operate(in_op, other)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 827, in operate'
    b'    return op(self.comparator, *other, **kwargs)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 1395, in in_op'
    b'    return a.in_(b)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 604, in in_'
    b'    return self.operate(in_op, other)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 74, in operate'
    b'    return o[0](self.expr, op, *(other + o[1:]), **kwargs)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/default_comparator.py", line 155, in _in_impl'
    b'    seq_or_selectable = coercions.expect('
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 175, in expect'
    b'    resolved = impl._literal_coercion('
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 552, in _literal_coercion'
    b'    self._raise_for_expected(element, **kw)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 270, in _raise_for_expected'
    b'    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)'
    b'  File "/home/zuul/src/opendev.org/openstack/ec2-api/.tox/lower-constraints/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_'
    b'    raise exception'
    b"sqlalchemy.exc.ArgumentError: IN expression list, SELECT construct, or bound parameter object expected, got 'fake-666c369c'."
    b''
```

**Versions.**
 - OS:
 - Python: 3.6
 - SQLAlchemy: 1.4.2
 - Database:
 - DBAPI:

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

the in_() operator accepts a list or other non-string sequence.  the error message indicates that a plain string is being passed which is invalid.   1.3 erroneously allows this to silently pass, producing a useless expression:

```
# 1.3's behavior
>>> print(column('q').in_('fake-string'))
q IN (:q_1, :q_2, :q_3, :q_4, :q_5, :q_6, :q_7, :q_8, :q_9, :q_10, :q_11)

```

1.4 correctly detects this error.

**Comment by Andrey-mp** [comment]
hm, thank you for explanation. will fix ec2-api code.
