### ISSUE TITLE
1.4.x: Core API: MySQLDialect.has_table() broken on MySQL 5.0.x & 5.1.x

### ISSUE THREAD

**Issue by ScottKevill** [sqlalchemy/sqlalchemy#6151]
**Describe the bug**
`MySQLDialect.has_table()` on 1.4.x always returns `False` on MySQL 5.0.x & 5.1.x.

This causes `MetaData.create_all(checkfirst=True)` (the default) and `Table.create(checkfirst=True)` to fail with an exception if the table already exists.

This does not occur on MySQL 5.5, 5.6, 5.7, or 8.0.

**Expected behavior**
MySQL 5.0.x & 5.1.x should behave the same as MySQL 5.5, 5.6, 5.7, or 8.0, rather than throwing an exception.

**Detailed Explanation**
`MySQLDialect.has_table()` on 1.4.x checks for existence of a table by retrieving its info from `information_schema.tables`, and calling `bool(Result.scalar())`.

On MySQL 5.5, 5.6, 5.7, and 8.0, the first column of that result (`TABLE_CATALOG`) is defined to always be the string `'def'`, so this works.

On MySQL 5.0 and 5.1, the first column (still `TABLE_CATALOG`) is defined to always be `NULL`. This causes `Result.scalar()` to return `None` (since it uses the value of `row[0]`) which ends up being the same as if the row did not exist (and hence the table). So `MySQLDialect.has_table()` always returns `False`.

Discovered this as a new user (have not previously tried SQLAlchemy) going through the tutorial for the Core API, but using the MySQL engine instead of SQLite. `MetaData.create_all()` would throw an exception on the second run where the table already existed, due to the incorrect result from `MySQLDialect.has_table()`.

**Possible Fix**
A simple fix is to change the query in `MySQLDialect.has_table()` from `SELECT * FROM ...` to `SELECT COUNT(*) FROM ...`. This check would be more robust with the result as `1` or `0`, rather than specific details.

**To Reproduce**
Run the script below with MySQL 5.0 or 5.1, and compare with MySQL 5.5, 5.6, 5.7, or 8.0. It uses the `test` database.

On MySQL 5.0 or 5.1, it will output `AFTER:  insp.has_table('tt'): False` (when it should be `True`) after the first `metadata.create_all()`, and the second `metadata.create_all()` will throw an exception `pymysql.err.OperationalError: (1050, "Table 'tt' already exists")`.

```py
from sqlalchemy import create_engine, inspect
from sqlalchemy import Table, Column, Integer, MetaData
from sqlalchemy.sql import text

engine = create_engine("mysql+pymysql://test@localhost/test?charset=utf8", echo=True)
engine.execute(text("DROP TABLE IF EXISTS tt"))

insp = inspect(engine)

metadata = MetaData()
tt = Table('tt', metadata, Column('id', Integer))

print("BEFORE: insp.has_table('tt'): ", insp.has_table('tt'))
metadata.create_all(engine)
print("AFTER:  insp.has_table('tt'): ", insp.has_table('tt'))

metadata.create_all(engine)
```

**Error**

```
2021-03-29 05:33:36,567 INFO sqlalchemy.engine.Engine SHOW VARIABLES LIKE 'sql_mode'
2021-03-29 05:33:36,567 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-03-29 05:33:36,571 INFO sqlalchemy.engine.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2021-03-29 05:33:36,572 INFO sqlalchemy.engine.Engine [generated in 0.00030s] {}
2021-03-29 05:33:36,575 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2021-03-29 05:33:36,575 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-03-29 05:33:36,580 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS tt
2021-03-29 05:33:36,581 INFO sqlalchemy.engine.Engine [generated in 0.00030s] {}
2021-03-29 05:33:36,586 INFO sqlalchemy.engine.Engine COMMIT
2021-03-29 05:33:36,591 INFO sqlalchemy.engine.Engine SELECT * FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2021-03-29 05:33:36,592 INFO sqlalchemy.engine.Engine [generated in 0.00035s] {'table_schema': 'test', 'table_name': 'tt'}
BEFORE: insp.has_table('tt'):  False
2021-03-29 05:33:36,599 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-03-29 05:33:36,602 INFO sqlalchemy.engine.Engine SELECT * FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2021-03-29 05:33:36,602 INFO sqlalchemy.engine.Engine [cached since 0.01109s ago] {'table_schema': 'test', 'table_name': 'tt'}
2021-03-29 05:33:36,608 INFO sqlalchemy.engine.Engine
CREATE TABLE tt (
        id INTEGER
)


2021-03-29 05:33:36,608 INFO sqlalchemy.engine.Engine [no key 0.00031s] {}
2021-03-29 05:33:36,618 INFO sqlalchemy.engine.Engine COMMIT
2021-03-29 05:33:36,620 INFO sqlalchemy.engine.Engine SELECT * FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2021-03-29 05:33:36,620 INFO sqlalchemy.engine.Engine [cached since 0.02913s ago] {'table_schema': 'test', 'table_name': 'tt'}
AFTER:  insp.has_table('tt'):  False
2021-03-29 05:33:36,628 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-03-29 05:33:36,632 INFO sqlalchemy.engine.Engine SELECT * FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
2021-03-29 05:33:36,632 INFO sqlalchemy.engine.Engine [cached since 0.04118s ago] {'table_schema': 'test', 'table_name': 'tt'}
2021-03-29 05:33:36,638 INFO sqlalchemy.engine.Engine
CREATE TABLE tt (
        id INTEGER
)


2021-03-29 05:33:36,638 INFO sqlalchemy.engine.Engine [no key 0.00029s] {}
2021-03-29 05:33:36,642 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
  File "./.venv/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "./.venv/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "./.venv/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "./.venv/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1050, "Table 'tt' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    metadata.create_all(engine)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4742, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2980, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 850, in visit_metadata
    _is_metadata_operation=True,
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    include_foreign_key_constraints,  # noqa
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1296, in _execute_ddl
    compiled,
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "./.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
  File "./.venv/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "./.venv/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "./.venv/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "./.venv/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "./.venv/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1050, "Table 'tt' already exists")
[SQL:
CREATE TABLE tt (
        id INTEGER
)

]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Versions.**
 - OS: Mac OS X (but not relevant here)
 - Python: 3.7.9 (but not relevant here)
 - SQLAlchemy: 1.4.3 (appears to start with 1.4.0 based on commit [dc91c7d](https://github.com/sqlalchemy/sqlalchemy/commit/dc91c7db7ff32243cd2f6fc04f4e3a6d62f7b11b#diff-e571eef91fce6ab48dfa623d8498f5033a63963f03b98ebddc5e14cb5ce6bf06R2712), but not tested with 1.3)
 - Database: MySQL 5.1.73 (MySQL 5.0.x & 5.1,.x affected. MySQL 5.5, 5.6, 8.0 unaffected.)
 - DBAPI: PyMySQL (but all MySQL DBAPIs call the base `MySQLDialect.has_table()`)

**Additional context**
1.4.x's new version of `MySQLDialect.has_table()` added in commit [dc91c7d](https://github.com/sqlalchemy/sqlalchemy/commit/dc91c7db7ff32243cd2f6fc04f4e3a6d62f7b11b#diff-e571eef91fce6ab48dfa623d8498f5033a63963f03b98ebddc5e14cb5ce6bf06R2712).

An older issue (still open) related to a previous version of `MySQLDialect.has_table()`: #5418

MySQL 5.0 Reference: [The INFORMATION_SCHEMA TABLES Table](https://downloads.mysql.com/docs/refman-5.1-en.a4.pdf) (PDF, Page 1758, Section 19.12)
MySQL 5.1 Reference: [The INFORMATION_SCHEMA TABLES Table](https://downloads.mysql.com/docs/refman-5.1-en.a4.pdf) (PDF, Page 2367, Section 20.20)

>  _MySQL 5.0, 5.1:_
> | `INFORMATION_SCHEMA` Name  |`SHOW` Name | Remarks |
> | -------------------------- |:----------:| :-----: |
> | `TABLE_CATALOG`            |            | `NULL`  |

MySQL 5.5 Reference: [The INFORMATION_SCHEMA TABLES Table](https://downloads.mysql.com/docs/refman-5.5-en.a4.pdf) (PDF, Page 2559, Section 21.22)
MySQL 5.6 Reference: [The INFORMATION_SCHEMA TABLES Table](https://dev.mysql.com/doc/refman/5.6/en/information-schema-tables-table.html) (HTML, Direct Link)
MySQL 5.7 Reference: [The INFORMATION_SCHEMA TABLES Table](https://dev.mysql.com/doc/refman/5.7/en/information-schema-tables-table.html) (HTML, Direct Link)
MySQL 8.0 Reference: [The INFORMATION_SCHEMA TABLES Table](https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html) (HTML, Direct Link)
> _MySQL 5.5, 5.6, 5.7, 8.0:_
>
> `TABLE_CATALOG`
> The name of the catalog to which the table belongs. This value is always `def`.

MySQL 5.1 output showing `TABLE_CATALOG` from table info:
```
mysql> SELECT * FROM information_schema.tables WHERE table_schema = 'test' and table_name = 'tt'\G
*************************** 1. row ***************************
  TABLE_CATALOG: NULL
   TABLE_SCHEMA: test
     TABLE_NAME: tt
     TABLE_TYPE: BASE TABLE
         ENGINE: MyISAM
        VERSION: 10
     ROW_FORMAT: Fixed
     TABLE_ROWS: 0
 AVG_ROW_LENGTH: 0
    DATA_LENGTH: 0
MAX_DATA_LENGTH: 1970324836974591
   INDEX_LENGTH: 1024
      DATA_FREE: 0
 AUTO_INCREMENT: NULL
    CREATE_TIME: 2021-03-29 05:33:36
    UPDATE_TIME: 2021-03-29 05:33:36
     CHECK_TIME: NULL
TABLE_COLLATION: latin1_swedish_ci
       CHECKSUM: NULL
 CREATE_OPTIONS:
  TABLE_COMMENT:
1 row in set (0.00 sec)
```

MySQL 8.0 output showing `TABLE_CATALOG` from table info:
```
mysql> SELECT * FROM information_schema.tables WHERE table_schema = 'test' and table_name = 'tt'\G
*************************** 1. row ***************************
  TABLE_CATALOG: def
   TABLE_SCHEMA: test
     TABLE_NAME: tt
     TABLE_TYPE: BASE TABLE
         ENGINE: InnoDB
        VERSION: 10
     ROW_FORMAT: Dynamic
     TABLE_ROWS: 0
 AVG_ROW_LENGTH: 0
    DATA_LENGTH: 16384
MAX_DATA_LENGTH: 0
   INDEX_LENGTH: 0
      DATA_FREE: 0
 AUTO_INCREMENT: NULL
    CREATE_TIME: 2021-03-28 21:38:33
    UPDATE_TIME: NULL
     CHECK_TIME: NULL
TABLE_COLLATION: utf8mb4_0900_ai_ci
       CHECKSUM: NULL
 CREATE_OPTIONS:
  TABLE_COMMENT:
1 row in set (0.00 sec)
```

**Comment by zzzeek** [comment]
per fc97854f69ee589774627f1 I made the minimum version at 5.0.2 but as noted in https://docs.sqlalchemy.org/en/14/dialects/mysql.html we don't have testing infrastructure below 5.6.

what is your SQLAlchemy use case that you have ready access to MySQL 5.0,5.1, 5.5, 5.6, 5.7, 8.0 and that supporting this very wide range of versions is an important use case , are you working for Oracle ?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix has table reflection on MySQL 5.0 5.1** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2704

**Comment by zzzeek** [comment]
since we are doing 1.3ish things for the moment lets backport it also

**Comment by zzzeek** [comment]
oh does this apply to 1.3 ?

**Comment by zzzeek** [comment]
oops, 1.4. only.  great!

**Comment by CaselIT** [comment]
no, on 1.3 we still use describe
