### ISSUE TITLE
SELECT within WHERE clause changes between 1.3.23 and 1.4.4

### ISSUE THREAD

**Issue by p-l-** [sqlalchemy/sqlalchemy#6181]
I use a `.in_(select([...]))` construction: something like `select(scan.xxx).where(scan.id.in_(select(port.scan.id.where(...))))` (the exact code is [here](https://github.com/cea-sec/ivre/blob/master/ivre/db/sql/__init__.py#L1955)).

this code used to work (1.3.23) and no longer works (1.4.4). I would like to understand whether my code was wrong in the first place or if the API has changed, and how I should code that.

Using `git bisect`, a9b62055bfa61c11e9fe0b2984437e2c3e32bf0e seems to be the "guilty" commit.

With the current SQLAchemy code, I get the following stacktrace:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/VENV/lib/python3.9/site-packages/ivre/db/sql/__init__.py", line 1497, in count
    return self.db.execute(
  File "<string>", line 2, in execute
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3009, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 533, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2964, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 492, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 603, in create_for_statement
    SelectState.__init__(self, self.statement, compiler, **kw)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4065, in __init__
    self.froms = self._get_froms(statement)
  File "/VENV/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4145, in _get_froms
    if item._is_subquery and item.element is statement:
AttributeError: 'Select' object has no attribute '_is_subquery'
```

Thanks in advance!

**Comment by zzzeek** [comment]
hi there -

please provide an [MCVE](http://stackoverflow.com/help/mcve) so that I know how to reproduce your issue.  thanks!

**Comment by zzzeek** [comment]
oh you have a link nevertmind

**Comment by zzzeek** [comment]
no, I really need a simple self contained example I can run, thanks, that's just a line from deep inside your application I can't just run.

**Comment by p-l-** [comment]
Yeah I **knew** you would ask for that but was secretly hopping you would have an idea with the stack trace ;-).

Anyway, thanks for your answer. Here is something that reproduces the problem, as simple as I could:
```Python
from sqlalchemy import (
    Column,
    Integer,
    String,
    column,
    func,
    select,
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Port(Base):
    __tablename__ = "port"
    id = Column(Integer, primary_key=True)
    scan = Column(Integer)
    port = Column(Integer)
    state = Column(String(32))

class Scan(Base):
    __tablename__ = "scan"
    id = Column(Integer, primary_key=True)
    scan = Column(Integer)
    name = Column(String(32))


req = select([column("scan")]).select_from(
    select([Port.scan.label("scan"), func.count().label("count")])
    .where(Port.state == "open")
    .group_by(Port.scan)
    .alias("pcnt")
)
print(str(select([Scan.name]).where(Scan.id.in_(req))))
```

**Comment by zzzeek** [comment]
nope, that's a weird one, it's easy enough to fix that check I just couldn't see how to get there, I haven't looked yet to see what's bringing it there but this is the test case

```python

from sqlalchemy import Column
from sqlalchemy import column
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table

m = MetaData()


t = Table('t', m, Column('a', Integer))

req = select([column("scan")])


print(select([t.c.a]).where(t.c.a.in_(req)))
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure Grouping._with_binary_element_type() maintains class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2707

**Comment by zzzeek** [comment]
you can work around this for now by using columns with types, `column('count', Integer)`

**Comment by p-l-** [comment]
Thanks a lot, both for the fix and the workaround!
