### ISSUE TITLE
psycopg2.errors.DatatypeMismatch when using array of enum and with_variant

### ISSUE THREAD

**Issue by karec** [sqlalchemy/sqlalchemy#6182]
**Describe the bug**
Using a type `ARRAY(Enum(enum_class)).with_variant(...)` on PostgreSQL, when inserting values, the array is not cast as it is without the `with_variant(...)`, resulting in the following error: 

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "items" is of type myenum[] but expression is of type text[]
```

It won't check the existance of the type either.

This issue is only present in SQLAlchemy > 1.3.23

**Expected behavior**
Emitted queries should be the same as the one without `with_variant`
 
**To Reproduce**

Note that in this example the `with_variant` doesn't make any sens at all, but that was to simplify the example. Same issue is observed no matter what we have in the `with_variant` arguments.

```py
import enum

from sqlalchemy import create_engine, Column, Integer, Enum, ARRAY
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


engine = create_engine("postgresql://user@host/db", echo=True)
Base = declarative_base()
Session = sessionmaker(bind=engine)


class MyEnum(enum.Enum):
    a = "a"
    b = "b"


# Variant type doesn't seems to matter at all, anything else with trigger the same issue
TypeWithVariant = ARRAY(Enum(MyEnum)).with_variant(ARRAY(Enum(MyEnum)), "other")


class MyModel(Base):
    __tablename__ = "my_model"

    id = Column(Integer, primary_key=True)
    items = Column(TypeWithVariant)


Base.metadata.create_all(engine)

session = Session()
obj = MyModel(items=[MyEnum.a])

session.add(obj)
session.commit()

```
**Emitted query:**

```sql
INSERT INTO my_model (items) VALUES (%(items)s) RETURNING my_model.id
```

**Emitted query without the `with_variant()` call**

```sql
INSERT INTO my_model (items) VALUES (%(items)s::myenum[]) RETURNING my_model.id
```

**Full logs**

```
2021-04-01 15:15:05,784 INFO sqlalchemy.engine.base.Engine select version()
2021-04-01 15:15:05,784 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:15:05,785 INFO sqlalchemy.engine.base.Engine select current_schema()
2021-04-01 15:15:05,785 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:15:05,786 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-04-01 15:15:05,786 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:15:05,787 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-04-01 15:15:05,787 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:15:05,787 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2021-04-01 15:15:05,787 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:15:05,788 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-04-01 15:15:05,788 INFO sqlalchemy.engine.base.Engine {'name': 'my_model'}
2021-04-01 15:15:05,790 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-04-01 15:15:05,791 INFO sqlalchemy.engine.base.Engine INSERT INTO my_model (items) VALUES (%(items)s) RETURNING my_model.id
2021-04-01 15:15:05,791 INFO sqlalchemy.engine.base.Engine {'items': ['a']}
2021-04-01 15:15:05,791 INFO sqlalchemy.engine.base.Engine ROLLBACK
```

**Error**

```
Traceback (most recent call last):
  File "/test.py", line 35, in <module>
    session.commit()
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "VENV/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "VENV/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "VENV/python3.9/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "VENV/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "VENV/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "VENV/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "VENV/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "VENV/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "VENV/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "VENV/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "VENV/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "VENV/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "VENV/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "VENV/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "VENV/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "items" is of type myenum[] but expression is of type text[]
LINE 1: INSERT INTO my_model (items) VALUES (ARRAY['a']) RETURNING m...
                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO my_model (items) VALUES (%(items)s) RETURNING my_model.id]
[parameters: {'items': ['a']}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: any
 - Python: 3.9
 - SQLAlchemy: >1.3.23
 - Database: postgresql
 - DBAPI: psycopg2 2.8.6

**Additional context**
I've tried to play with the arguments of `with_variant`, testing multiple types, but it always result in the same error.

In addition, I've also tested with a simple enum without array, and this works, giving me the following queries 

```
2021-04-01 15:21:39,153 INFO sqlalchemy.engine.base.Engine select version()
2021-04-01 15:21:39,153 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:21:39,154 INFO sqlalchemy.engine.base.Engine select current_schema()
2021-04-01 15:21:39,154 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:21:39,154 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-04-01 15:21:39,155 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:21:39,155 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-04-01 15:21:39,155 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:21:39,155 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2021-04-01 15:21:39,155 INFO sqlalchemy.engine.base.Engine {}
2021-04-01 15:21:39,156 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-04-01 15:21:39,156 INFO sqlalchemy.engine.base.Engine {'name': 'my_model'}
2021-04-01 15:21:39,158 INFO sqlalchemy.engine.base.Engine
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t
                WHERE t.typname = %(typname)s
                AND pg_type_is_visible(t.oid)
                )

2021-04-01 15:21:39,158 INFO sqlalchemy.engine.base.Engine {'typname': 'myenum'}
2021-04-01 15:21:39,160 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-04-01 15:21:39,161 INFO sqlalchemy.engine.base.Engine INSERT INTO my_model (items) VALUES (%(items)s) RETURNING my_model.id
2021-04-01 15:21:39,161 INFO sqlalchemy.engine.base.Engine {'items': 'a'}
2021-04-01 15:21:39,162 INFO sqlalchemy.engine.base.Engine COMMIT

```

**Have a nice day!**

**Comment by zzzeek** [comment]
this would be due to #6023

**Comment by zzzeek** [comment]
this might be having bigger problems on 1.4

**Comment by zzzeek** [comment]
I'm not seeing metadata.create_all() able to create the PG enum at all when it's embedded inside the variant, unless we do a .create() directly on it and that's in 1.3.23.   did you have trouble getting the "CREATE TYPE" to work with this type?  the test case you have wont run unless I do this:

    e = Enum(MyEnum)
    e.create(engine, checkfirst=True)

**Comment by zzzeek** [comment]
that part looks like this:

```diff
diff --git a/lib/sqlalchemy/sql/type_api.py b/lib/sqlalchemy/sql/type_api.py
index bfce00cb5..e69520f3e 100644
--- a/lib/sqlalchemy/sql/type_api.py
+++ b/lib/sqlalchemy/sql/type_api.py
@@ -1500,19 +1500,19 @@ class Variant(TypeDecorator):
     def _set_parent(self, column, **kw):
         """Support SchemaEventTarget"""
 
-        if isinstance(self.impl, SchemaEventTarget):
+        if hasattr(self.impl, "_set_parent"):
             self.impl._set_parent(column, **kw)
         for impl in self.mapping.values():
-            if isinstance(impl, SchemaEventTarget):
+            if hasattr(impl, "_set_parent"):
                 impl._set_parent(column, **kw)
 
     def _set_parent_with_dispatch(self, parent):
         """Support SchemaEventTarget"""
 
-        if isinstance(self.impl, SchemaEventTarget):
+        if hasattr(self.impl, "_set_parent_with_dispatch"):
             self.impl._set_parent_with_dispatch(parent)
         for impl in self.mapping.values():
-            if isinstance(impl, SchemaEventTarget):
+            if hasattr(impl, "_set_parent_with_dispatch"):
                 impl._set_parent_with_dispatch(parent)
 
     def with_variant(self, type_, dialect_name):

```

**Comment by zzzeek** [comment]
hmmm nope, the change is elsewhere...

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Correct for Variant + ARRAY cases in psycopg2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2700

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Correct for Variant + ARRAY cases in psycopg2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2701

**Comment by karec** [comment]
> I'm not seeing metadata.create_all() able to create the PG enum at all when it's embedded inside the variant, unless we do a .create() directly on it and that's in 1.3.23. did you have trouble getting the "CREATE TYPE" to work with this type? the test case you have wont run unless I do this:
> 
> ```
> e = Enum(MyEnum)
> e.create(engine, checkfirst=True)
> ```


You're right, that's my bad sorry, I forgot to remove the type on postgresql beforehand so the type was already present in my postgresql server, created by previous tests.
Strangely enough, our CI for our main app is able to create them with SQLAlchemy 1.3.23, but I may need to dig a bit more since it use flask-SQLAlchemy `db.create_all()`

**Comment by zzzeek** [comment]
well in any case it's definitely buggy for 1.3 and 1.4 so Ive also included a fix for that

**Comment by zzzeek** [comment]
why....would you use Variant with ARRAY anyway as Postgresql is the only DB that supports ARRAY ?   you're doing a non-arrayish thing in variants?

**Comment by karec** [comment]
That's when my bad habits are exposed :sweat_smile: 

But you're right, that's because we have a sqlite variant with a custom type to "mimic" an array. 
This variant is only used when we want to run tests locally using in-memory sqlite, mainly for reducing execution time as their only used as a "first check". We then let the CI test against Postgresql

**Comment by zzzeek** [comment]
that's what I guessed.  using the variant your column loses the array comparator stuff like `column[5]`.
