### ISSUE TITLE
cte() and subquery() should not be Executable

### ISSUE THREAD

**Issue by JunyuanChen** [sqlalchemy/sqlalchemy#6204]
**Describe the bug**

When using `sqlalchemy.literal` in a CTE with SQLite3, sqlite3 module complains about incorrect number of bindings.
However, without using a CTE everything will work just fine.
```python
import sqlalchemy


engine = sqlalchemy.create_engine("sqlite://")
literal = sqlalchemy.literal(1)  # DEMO
cte = sqlalchemy.select([literal]).cte()  # (1)
engine.execute(cte)  #=> Error
```

If I comment the line marked as `(1)` out, no error will occur and the result `[(1,)]` is returned, which is expected.
However, with line `(1)`, an error is raised.

**Error**

```
Traceback (most recent call last):
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 691, in do_execute
    cursor.execute(statement, parameters)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in execute
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3037, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/user/pandas-alchemy/.env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 691, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
[SQL: SELECT ? AS anon_2]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
 - Python: Python 3.7.3
 - SQLAlchemy: SQLAlchemy==1.4.5
 - Database: sqlite
 - DBAPI: ??

**Comment by zzzeek** [comment]
> **Describe the bug**
> 
> When using `sqlalchemy.literal` in a CTE with SQLite3, sqlite3 module complains about incorrect number of bindings.
> However, without using a CTE everything will work just fine.
> 
> ```python
> import sqlalchemy
> 
> 
> engine = sqlalchemy.create_engine("sqlite://")
> literal = sqlalchemy.literal(1)  # DEMO
> cte = sqlalchemy.select([literal]).cte()  # (1)
> engine.execute(cte)  #=> Error

there's a bug in SQLAlchemy here however it's that it's failing ungracefully; you should not be able to "execute" a CTE because it's not a SELECT statement, it's only a fragment of one.

to fix your application ensure you execute a SELECT statement:

```
with engine.connect() as conn:
    conn.execute(cte.select())

```

**Comment by zzzeek** [comment]
in 1.3 this has the bizarre behavior of invoking a blank string as a statement.    however CTE and subquery() aren't executable and this should raise an error.   the non-workingness of CTE in 1.3 indicates this is safe for a straight change in 1.4, but invoking a subquery in 1.3 seems to invoke the inner SELECT, so not sure if that one is as safe.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Disallow AliasedReturnsRows from execution** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2715
