### ISSUE TITLE
last successful session.flush() persisting data although transaction fails after and even rollback performed

### ISSUE THREAD

**Issue by tolgadayanc** [sqlalchemy/sqlalchemy#6208]
**Problem**

There are cases where flush() is needed to grab related PK's to be used later. In the end transaction may still fail and ideal state is to rollback everything. What I'm experimenting with sqlalchemy working with mssql is that, flush() being used as `savepoint` , so Although `rollback()` is performed, it still persist rows from the last successful `flush()` run and entities were in that session

**Important Note: This is not happening when using postgre**

configs: 
```
autocommit: False
autoflush: False
```
version:
SQLAlchemy==1.3.23 or even latest 1.4.5
db: mssql

logic:
```
Session = sessionmaker(db.engine)
    session = Session()
    try:
        session.begin()
        next_id = session.execute("SELECT NEXT VALUE FOR dbo.SEQ_tblBox as next_val").scalar()
        box = BoxModel(
            id=next_id, box_type_id=2
        )
        box_number = get_random_str()
        breakpoint()
        print(box_number)
        mbl_box = MBLModel(
            box=box,
            number=box_number,
        )
        session.add(mbl_box)
        session.flush()
        # session.flush() above runs successfully, and I'm adding a model to a session which will cause an error because nonNull field is not provided, above entities (MblModel and BoxModel) is not persisted at the end because session.rollback() will be performed.
        cause_error = RouteModel(id=0)
        session.add(cause_error)
        session.commit()
        return box.id
    except:
        session.rollback()
        raise
 ```
here is the trace log which shows rollback and pyodbc.IntegrityError that I intentionally caused.

```2021-04-06 16:13:21,331 INFO sqlalchemy.engine.Engine ROLLBACK
2021-04-06 16:13:21 [56] [INFO] sqlalchemy.engine.Engine ROLLBACK
2021-04-06 16:13:21 [56] [INFO] werkzeug         192.168.48.1 - - [06/Apr/2021 16:13:21] "GET /test3 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/pyenv/versions/3.7.8/envs/nct_shipments/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/pyenv/versions/3.7.8/envs/nct_shipments/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 691, in do_execute
    cursor.execute(statement, parameters)
  File "/pyenv/versions/3.7.8/envs/nct_shipments/lib/python3.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 105, in execute
    return self._trace_method(self.__wrapped__.execute, self._self_datadog_name, query, {}, query, *args, **kwargs)
  File "/pyenv/versions/3.7.8/envs/nct_shipments/lib/python3.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 52, in _trace_method
    return method(*args, **kwargs)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'RoSequence', table 'csn_shipment.dbo.tblRoute'; column does not allow nulls. INSERT fails. (515) (SQLExecDirectW)")
```

Models :

```


class MBLModel(BaseModel, AuditBase):
    __tablename__ = "tblMBLBox"
    __table_args__ = {"extend_existing": True}

    # To enable audit logging inherit AuditBase and add this line based on app
    # MutationLog table
    audit_models = [(MutationLogModel, "all")]

    def __repr__(self):
        return str(self.to_dict())

    box_id = Column(
        "MblBoxID",
        BIGINT,
        ForeignKey("tblBox.BoxID"),
        primary_key=True,
        nullable=False,
        autoincrement=False,
    )
    box = db.relationship("BoxModel", foreign_keys=[box_id], lazy="raise")

    number = Column("MblBoxNumber", NVARCHAR(20), nullable=True)
    scac = Column("MblBoxSCAC", NVARCHAR(4), nullable=True)
    booking_group_id = Column("MblBoxBookingGroupID", BIGINT, nullable=True)
    booking_ref_number = Column("MblBookingRefNumber", NVARCHAR(256), nullable=True)
    it_number = Column("MblBoxItNumber", NVARCHAR(35), nullable=True)
    firms_code = Column("MblBoxFirmsCode", NVARCHAR(35), nullable=True)
    entry_port_facility_id = Column("MblBoxEntryPortFacID", BIGINT, nullable=True)
    
    
    
    
class BoxModel(BaseModel, AuditBase):
    __tablename__ = "tblBox"
    __table_args__ = {"extend_existing": True}

    id = Column(
        "BoxID",
        BIGINT,
        primary_key=True,
        doc="The Box ID",
        nullable=False,
        autoincrement=False,
    )

    box_type_id = Column(
        "BoxTypeID", TINYINT, primary_key=False, doc="The Box Type ID", nullable=False
    )
    
    and the model I intentionally caused error for.
    
    
class RouteModel(BaseModel, AuditBase):
    __tablename__ = "tblRoute"
    __table_args__ = {"extend_existing": True}
    audit_models = [(MutationLogModel, "all")]

    id = Column("RoID", BIGINT, primary_key=True, doc="The Route ID", nullable=False)

    route_type_id = Column(
        "RoTypeID",
        TINYINT,
        ForeignKey("tblplRouteType.RoTypeID"),
        primary_key=True,
        doc="The Route Type ID",
        nullable=False,
    )
    vehicle_id = Column(
        "RoVehicleBoxID",
        BIGINT,
        ForeignKey("tblBox.BoxID"),
        doc="The Vehicle Facility ID",
        nullable=True,
    )
    vehicle = db.relationship("BoxModel", foreign_keys=[vehicle_id], lazy="raise")
    
   ```

**Comment by CaselIT** [comment]
Hi,

Could you post the structure of the models you mention in the example? Thanks

**Comment by tolgadayanc** [comment]
Updated the description with models, though It may not be related with the models. 
One experiment is that, if you move `flush` to right before `commit` which means after bad input causes exception, then `flush` at that point does the rollback properly.

**Comment by zzzeek** [comment]
Hey there -

if the claim is that pyodbc .rollback is not working, we would need to see a [succinct reproducing case](http://stackoverflow.com/help/mcve).   Here's a simple test of the claims stated which does not show any issue.  If you can modify this test script to illustrate a rollback not occurring, that would be helpful.   SQLAlchemy does not use SAVEPOINT unless explicitly told to do so.  thanks!

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import exc
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql.schema import UniqueConstraint

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String(10))

    __table_args__ = (UniqueConstraint("data"),)


e = create_engine(
    "mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server",
    echo=True,
)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e, autoflush=False, autocommit=False)

s.add_all([A(data="data1"), A(data="data2"), A(data="data3")])

s.commit()

# INSERT "data1.5"
s.add(A(data="data1.5"))
s.flush()

# INSERT more rows including a dupe
s.add_all(
    [
        A(data="data2"),
        A(data="data3"),
        A(data="data4"),
    ]
)

# error is raised
try:
    s.flush()
    assert False
except exc.IntegrityError as err:
    print("Got error as expected: %s" % err)

# rollback has already happened, the connection we would use to
# see these rows is gone, rolled back
try:
    s.connection()
    assert False
except exc.InvalidRequestError as pe:
    print("we're already rolled back: %s"% pe)

# data was not committed
with e.connect() as conn:
    assert {
        row.data for row in conn.execute("select data from a").fetchall()
    } == {"data1", "data2", "data3"}

s.rollback()

# rollback has happened
assert {row.data for row in s.query(A.data)} == {"data1", "data2", "data3"}

```

**Comment by tolgadayanc** [comment]
Thank you for your quick response. I'm closing the issue as we noticed we had internal wrapper overriding pyodbc connection autocommit mode.
