### ISSUE TITLE
Hybrids defined without decorator return error when queried as a separate attribute

### ISSUE THREAD

**Issue by kvesteri** [sqlalchemy/sqlalchemy#6215]
**Describe the bug**

In SA 1.4 hybrid property defined without decorator returns error when queried as a separate attribute.

**Expected behavior**

The given query should work.

**To Reproduce**

```py
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

dsn = 'postgresql://postgres:@localhost/test'
engine = sa.create_engine(dsn)
connection = engine.connect()


class City(Base):
    __tablename__ = 'city'
    id = sa.Column(sa.Integer, primary_key=True)

    @hybrid_property
    def some_hybrid(self):
        return self.id

    some_hybrid2 = hybrid_property(lambda self: self.id)


sa.orm.configure_mappers()
Base.metadata.create_all(connection)
Session = sessionmaker(bind=connection)
session = Session()

print(session.query(City).all())  # works!
print(session.query(City.some_hybrid).all())  # works!
print(session.query(City.some_hybrid2).all())  # throws error :(

```

**Error**

```
Traceback (most recent call last):
  File "script.py", line 31, in <module>
    print(session.query(City.some_hybrid2).all())  # throws error :(
  File "python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "python3.8/site-packages/sqlalchemy/orm/session.py", line 1662, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "python3.8/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "python3.8/site-packages/sqlalchemy/sql/elements.py", line 535, in _compile_w_cache
    compiled_sql = self._compiler(
  File "python3.8/site-packages/sqlalchemy/sql/elements.py", line 570, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "python3.8/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "python3.8/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "python3.8/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "python3.8/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2966, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "python3.8/site-packages/sqlalchemy/sql/base.py", line 492, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "python3.8/site-packages/sqlalchemy/orm/context.py", line 568, in create_for_statement
    _QueryEntity.to_compile_state(self, select_statement._raw_columns)
  File "python3.8/site-packages/sqlalchemy/orm/context.py", line 2203, in to_compile_state
    _ColumnEntity._for_columns(
  File "python3.8/site-packages/sqlalchemy/orm/context.py", line 2519, in _for_columns
    _ORMColumnEntity(
  File "python3.8/site-packages/sqlalchemy/orm/context.py", line 2684, in __init__
    self.expr = getattr(_entity.entity, orm_key)
AttributeError: type object 'City' has no attribute '<lambda>'
```

**Versions.**
 - SQLAlchemy: 1.4

**Additional context**

We've been trying to get SA-Utils to support SA 1.4. This bug is currently causing problem with [SA-Utils translation hybrid](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/i18n.py)

**Comment by zzzeek** [comment]
1.3 is not without a bug here:
```

session.add(City(id=1))
session.flush()

row = session.query(City.some_hybrid2).first()
print(row.keys())
```

output:

    ['<lambda>']

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Check for hybrid's attribute name and support no name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2718
