### ISSUE TITLE
schema_translate_map is no longer working for stubbed schemas

### ISSUE THREAD

**Issue by rad-pat** [sqlalchemy/sqlalchemy#6216]
**Describe the bug**
If a table has been set up with a schema stub, an incomplete reference, such as `schema_{}`, this schema stub is no longer substituted using a schema_translate_map which contains that stub e.g.  `{'schema_{}': 'schema_one'}` . The stub appears to be supplemented with a prefix `SCHEMA_` e.g. `SCHEMA_schema_{}` and, as such does not match the translate map. If the schema has no curly braces, the map behaves as expected.

**Expected behavior**
I expect the substitution to occur - it did in versions prior to 1.4.

**To Reproduce**
Run the below code after substituting the connection string

```py
import sqlalchemy
from sqlalchemy import Table, Column, String, Integer

metadata = sqlalchemy.MetaData()


user_table = Table(
    'user', metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String(50)),
    schema='Test_{}',
    #schema='normal'
)

engine = sqlalchemy.create_engine('postgresql://....')

connection = engine.connect().execution_options(
    schema_translate_map={'Test_{}': 'Test_{}'.format('schema_one')}
    #schema_translate_map={'normal': 'schema_one'}
)

result = connection.execute(user_table.select())
```

**Error**

```
Traceback (most recent call last):
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "["
LINE 1: SELECT [SCHEMA_Test_{}]."user".id, [SCHEMA_Test_{}]."user".n...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/plaid/src/plaid/plaid/temp/patbuxton/schema_translate_map.py", line 23, in <module>
    result = connection.execute(user_table.select())
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/plaid/py39/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "["
LINE 1: SELECT [SCHEMA_Test_{}]."user".id, [SCHEMA_Test_{}]."user".n...
               ^

[SQL: SELECT [SCHEMA_Test_{}]."user".id, [SCHEMA_Test_{}]."user".name 
FROM [SCHEMA_Test_{}]."user"]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.9
 - SQLAlchemy: 1.4.4
 - Database: Postgresql 10.15
 - DBAPI: psycopg2

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Expand reg for schema translate map for most special characters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2720

**Comment by zzzeek** [comment]
curly braces are OK.  square brackets `[]` I now have to explicitly disallow as they are the delimiting character.
