### ISSUE TITLE
[bug report] PyMySQL driver are broken

### ISSUE THREAD

**Issue by HuJK** [sqlalchemy/sqlalchemy#6217]
**Describe the bug**

I followed the instruction from https://docs.sqlalchemy.org/en/14/dialects/mysql.html#mariadb-support
And the code are not work:
```
import sqlalchemy
engine = sqlalchemy.create_engine("mysql+pymsql://aaa:bbb@127.0.0.1:3306/ccc?charset=utf8mb4")
# Error occured here
```

**Expected behavior**
```
import sqlalchemy
engine = sqlalchemy.create_engine("mysql+pymsql://aaa:bbb@127.0.0.1:3306/ccc?charset=utf8mb4")
# load success
```

**To Reproduce**
```bash
#create a clean, one time use ubuntu 20.04 environment
docker run -it --rm ubuntu bash 
### enter docker environment now
apt update
apt install -y python3 python3-pip  #install python3
pip3 install sqlalchemy pymysql
python3
### enter python shell now
import sqlalchemy
engine = sqlalchemy.create_engine("mysql+pymsql://aaa:bbb@127.0.0.1:3306/ccc?charset=utf8mb4")
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 339, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.pymsql
```

**Versions.**
 - OS: ubuntu 20.04
 - Python: 3.8
 - SQLAlchemy: 1.4.6
 - Database: None
 - DBAPI: PyMySQL==1.0.2

**Additional context**

Environments should be very clean:
```
root@a5d06902da68:/# pip3 freeze
greenlet==1.0.0
PyMySQL==1.0.2
SQLAlchemy==1.4.6
```

**Have a nice day!**

**Comment by zzzeek** [comment]
this is a typo.  please use "mysql+pymysql"

**Comment by HuJK** [comment]
Oh, it works, what is the pymsql do in the docs?

**Comment by zzzeek** [comment]
it is an error.  the new documentation will be up in an hour.

**Comment by HuJK** [comment]
Oh, the documentation error mislead me. 
Thank your answer a lot. 😃👍
