### ISSUE TITLE
Connection to AWS RDS Serverless Aurora PostgreSQL throws an exception

### ISSUE THREAD

**Issue by norus** [sqlalchemy/sqlalchemy#6219]
**Describe the bug**
When running `database_exists` against a serverless RDS, sqlalchemy throws an exception:
```shell
>>> database_exists('postgresql://XXX:XXX@acme-XXX-postgres.cluster-XXX.us-west-2.rds.amazonaws.com:5432/XXX')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "XXX" does not exist
```

When running against an on-prem PostgreSQL 11 on Debian 10:
```shell
>>> database_exists('postgresql://XXX:XXX@foo.com:5432/XXX')
True
```
**Expected behavior**
`database_exists` should be able to properly return either True or False.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
from sqlalchemy_utils import database_exists
database_exists('postgresql://XXX:XXX@XXX-postgres.cluster-XXX.us-west-2.rds.amazonaws.com:5432/XXX')
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: Ubuntu 18.04.4 LTS
 - Python: 3.6.9
 - SQLAlchemy: 0.36.8
 - Database: AWS RDS Serverless Aurora PostgreSQL
 - DBAPI: -

**Additional context**

**Have a nice day!**

**Comment by jvanasco** [comment]
sqlalchemy_utils is a 3rd party package.  You should report it there: https://github.com/kvesteri/sqlalchemy-utils
