### ISSUE TITLE
Column property using select construct throws warning

### ISSUE THREAD

**Issue by kvesteri** [sqlalchemy/sqlalchemy#6225]
**Describe the bug**
Simple column property using select construct throws warning. 

**Expected behavior**
The given column property should not throw a warning.

**To Reproduce**

```py
import warnings

import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import sessionmaker

warnings.simplefilter('error', sa.exc.SAWarning)

Base = declarative_base()

dsn = 'postgresql://postgres:@localhost/test'
engine = sa.create_engine(dsn)
connection = engine.connect()


class Address(Base):
    __tablename__ = 'address'
    id = sa.Column(sa.Integer, primary_key=True)
    user_id = sa.Column(sa.Integer, sa.ForeignKey('user.id'))


class User(Base):
    __tablename__ = 'user'
    id = sa.Column(sa.Integer, primary_key=True)
    address_count = sa.orm.column_property(
        sa.select(sa.func.count(Address.id))
        .where(Address.user_id == id)
        .correlate_except(Address)
    )  # <- throws a warning
```

**Error**

```
Traceback (most recent call last):
  File "script.py", line 23, in <module>
    class User(Base):
  File "script.py", line 26, in User
    address_count = sa.orm.column_property(
  File "<string>", line 2, in column_property
  File "python3.8/site-packages/sqlalchemy/orm/properties.py", line 156, in __init__
    self._orig_columns = [
  File "python3.8/site-packages/sqlalchemy/orm/properties.py", line 157, in <listcomp>
    coercions.expect(roles.LabeledColumnExprRole, c) for c in columns
  File "python3.8/site-packages/sqlalchemy/sql/coercions.py", line 200, in expect
    return impl._implicit_coercions(
  File "python3.8/site-packages/sqlalchemy/sql/coercions.py", line 786, in _implicit_coercions
    new = super(LabeledColumnExprImpl, self)._implicit_coercions(
  File "python3.8/site-packages/sqlalchemy/sql/coercions.py", line 319, in _implicit_coercions
    self._warn_for_scalar_subquery_coercion()
  File "python3.8/site-packages/sqlalchemy/sql/coercions.py", line 307, in _warn_for_scalar_subquery_coercion
    util.warn(
  File "python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1617, in warn
    warnings.warn(msg, exc.SAWarning, stacklevel=2)
sqlalchemy.exc.SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
```

**Versions.**
 - SQLAlchemy: 1.4.6

**Comment by zzzeek** [comment]
working as intended. please follow the directions in the warning:

```python

class User(Base):
    __tablename__ = 'user'
    id = sa.Column(sa.Integer, primary_key=True)
    address_count = sa.orm.column_property(
        sa.select(sa.func.count(Address.id))
        .where(Address.user_id == id)
        .correlate_except(Address).scalar_subquery()
    ) 
```

**Comment by kvesteri** [comment]
Thanks for the quick reply Mike. The docs regarding column property could be updated to accommodate this change: https://docs.sqlalchemy.org/en/14/orm/mapped_sql_expr.html#using-column-property
