### ISSUE TITLE
syntax error from sqlite when executing an insert with multiple rows but no non-default columns 

### ISSUE THREAD

**Issue by davisagli** [sqlalchemy/sqlalchemy#6254]
**Describe the bug**
Executing an insert of multiple rows into a sqlite table with a single autoincrement column works in sqlalchemy 1.3.24, but raises an OperationalError in sqlalchemy 1.4.7.

**Expected behavior**
Expected the insert to succeed.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, MetaData, Table, create_engine

engine = create_engine("sqlite:///test.db")
with engine.connect() as conn:
    metadata = MetaData(bind=conn)
    table = Table(
        "test",
        metadata,
        Column("id", Integer(), primary_key=True, autoincrement=True),
    )
    metadata.create_all()

    conn.execute(table.insert(), ({}, {}))
```

**Error**

```
Traceback (most recent call last):
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1685, in _execute_context
    self.dialect.do_executemany(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 689, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: near "DEFAULT": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cumulusci/tasks/bulkdata/repro.py", line 14, in <module>
    conn.execute(table.insert(), ({}, {}))
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1685, in _execute_context
    self.dialect.do_executemany(
  File "/Users/dglick/.pyenv/versions/cci/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 689, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DEFAULT": syntax error
[SQL: INSERT INTO test (id) VALUES (DEFAULT)]
[parameters: ((), ())]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.8.0
 - SQLAlchemy: 1.4.7
 - Database: SQLite (from Python)
 - DBAPI: sqlite3

**Comment by zzzeek** [comment]
tahnks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support DEFAULT VALUES and VALUES(DEFAULT) individually** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2740
