### ISSUE TITLE
asertion error using legacy select APIs

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6261]
from #6257, this should warn like crazy but should not fail assertions:
```

from sqlalchemy import select, table, column

t1 = table('t1', column('a'), column('b'))
s1 = select(t1.c.a)

s1.append_column(s1.c.a)
```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 6, in <module>
    s1.append_column(s1.c.a)
  File "<string>", line 2, in append_column
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 3985, in append_column
    self.add_columns.non_generative(self, column)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 5261, in add_columns
    self._assert_no_memoizations()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 1143, in _assert_no_memoizations
    assert elem not in self.__dict__
AssertionError
```

add_column() needs to check for "_internal_subquery" and alter it in this case, rather than asserting.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**omit text from selected_columns; clear memoizations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2769

**Comment by zzzeek** [comment]
breaks:

```diff
diff --git a/test/orm/test_core_compilation.py b/test/orm/test_core_compilation.py
index c313843e90..51868dae90 100644
--- a/test/orm/test_core_compilation.py
+++ b/test/orm/test_core_compilation.py
@@ -50,6 +50,29 @@ class SelectableTest(QueryTest, AssertsCompiledSQL):
             "WHERE users.name = :name_1",
         )
 
+    def test_c_accessor_not_mutated_subq(self):
+        """test #6394, ensure all_selected_columns is generated each time"""
+        User = self.classes.User
+
+        s1 = select(User.id)
+
+        eq_(s1.subquery().c.keys(), ['id'])
+        eq_(s1.subquery().c.keys(), ['id'])
+
+    def test_scalar_subquery_from_subq_same_source(self):
+        """test #6394, ensure all_selected_columns is generated each time"""
+        User = self.classes.User
+
+        s1 = select(User.id)
+
+        for i in range(2):
+            stmt = s1.subquery().select().scalar_subquery()
+            self.assert_compile(
+                stmt,
+                "(SELECT anon_1.id FROM "
+                "(SELECT users.id AS id FROM users) AS anon_1)",
+            )
+
     def test_froms_single_table(self):

```

need to not use iterator for context.all_selected_columns

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**ensure SelectState.all_selected_columns not memoized as a generator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2787
