### ISSUE TITLE
'CompoundSelect' object has no attribute 'mapper'

### ISSUE THREAD

**Issue by andrewcooke** [sqlalchemy/sqlalchemy#6274]
**Describe the bug**
Calling aliased(union(Query, Query)) gives the error 'CompoundSelect' object has no attribute 'mapper'

**Expected behavior**
I expect it to return something that represents the SQL ALIAS construct.

**To Reproduce**

```py
class SQLAlchemyTest(TestCase):

    def test_sqlalchemy(self):

        engine = create_engine('sqlite:///:memory:')
        Base = declarative_base()
        Session = sessionmaker(engine)

        class Table(Base):
            __tablename__ = 'table'
            id = Column(Integer, primary_key=True)

        Base.metadata.create_all(engine)

        with Session() as s:
            q1 = s.query(Table).filter(Table.id == 1)
            q2 = s.query(Table).filter(Table.id == 2)
            q3 = aliased(union(q1, q2))
```

**Error**

```
Ran 1 test in 0.010s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/home/andrew/project/choochoo/py/tests/test_search.py", line 52, in test_sqlalchemy
    q3 = aliased(union(q1, q2))
  File "/home/andrew/project/choochoo/py/env/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 1201, in aliased
    return AliasedClass(
  File "/home/andrew/project/choochoo/py/env/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 495, in __init__
    mapper = insp.mapper
AttributeError: 'CompoundSelect' object has no attribute 'mapper'
```

**Versions.**
 - OS: OpenSuse 15.2
 - Python: 3.9.0
 - SQLAlchemy: 1.4.7
 - Database: sqlite3
 - DBAPI: sqlite

**Additional context**
https://github.com/sqlalchemy/sqlalchemy/discussions/6271

**Have a nice day!**

**Comment by andrewcooke** [comment]
Actually, select() has the same problem:

```py
        with Session() as s:
            q1 = select(Table).filter(Table.id == 1)
            q2 = select(Table).filter(Table.id == 2)
            q3 = aliased(union(q1, q2))
```

gives the same error

```
Traceback (most recent call last):
  File "/home/andrew/project/choochoo/py/tests/test_search.py", line 52, in test_sqlalchemy
    q3 = aliased(union(q1, q2))
  File "/home/andrew/project/choochoo/py/env/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 1201, in aliased
    return AliasedClass(
  File "/home/andrew/project/choochoo/py/env/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 495, in __init__
    mapper = insp.mapper
```

**Comment by zzzeek** [comment]
OK so, we can fix the error message here, as that should be emitting a specific kind of warning then doing the coercion to subquery, but the main problem is that you can't make an "aliased" out of a UNION or SELECT, it has to be a subquery first.   1.3 silently coerces this for you, and 1.4 is supposed to do that here as well while emitting  a warning, so we can fix that.

anyway, to fix your program, create the subquery explicitly:

    aliased(my_union.subquery())

background on the change is at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#a-select-statement-is-no-longer-implicitly-considered-to-be-a-from-clause

**Comment by andrewcooke** [comment]
OK, thanks for the explanation.  Maybe I am mis-understanding the docs, but it still seems odd to me that:
```
aliased(union(...))
```
raises an error, but
```
union(...).alias()
```
is just fine (alias() being a, well, alias for subquery()).

**Comment by zzzeek** [comment]
yes you are probably right since I did not deprecate alias() being a synonym for subquery(), so it will just do the right thing.

**Comment by andrewcooke** [comment]
I think I have this code working, thanks.

**Comment by zzzeek** [comment]
this is still an active issue.  in 2.0, pylance shows the usage as wrong, but we get that same error still, so this should be fixed via coercions etc

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import union
from sqlalchemy.orm import aliased
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class Table(Base):
    __tablename__ = "table"
    id = Column(Integer, primary_key=True)


with Session() as s:
    q1 = s.query(Table).filter(Table.id == 1)
    q2 = s.query(Table).filter(Table.id == 2)
    q3 = aliased(union(q1, q2))

```

```
raceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 25, in <module>
    q3 = aliased(union(q1, q2))
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/_orm_constructors.py", line 2189, in aliased
    return AliasedInsp._alias_factory(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/util.py", line 986, in _alias_factory
    return AliasedClass(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/util.py", line 667, in __init__
    mapper = insp.mapper
AttributeError: 'CompoundSelect' object has no attribute 'mapper'

```

this can have a 1.4 backport

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Raise informative error for aliased() against select/union constructs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6829

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**Deprecation warning for aliased() against select/union constructs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6830
