### ISSUE TITLE
metadata.create_all() cause test failure in test/aaa_profiling/test_memusage.py

### ISSUE THREAD

**Issue by honglei** [sqlalchemy/sqlalchemy#6277]
Env: Python3.9.1/sqlalchemy 1.4.7/

```
__________________________________________________________________ MemUsageWBackendTest_mariadb+pymysql_10_3_22_0.test_savepoints ______________________________________________________________
Traceback (most recent call last):
  File "/home/lccy/sqlalchemy-rel_1_4_7/test/aaa_profiling/test_memusage.py", line 600, in test_savepoints
    metadata.create_all()
  File "/home/lccy/sqlalchemy-rel_1_4_7/test/../lib/sqlalchemy/sql/schema.py", line 4743, in create_all
    bind = _bind_or_error(self)
  File "/home/lccy/sqlalchemy-rel_1_4_7/test/../lib/sqlalchemy/sql/base.py", line 1545, in _bind_or_error
    util.warn_deprecated_20(
  File "/home/lccy/sqlalchemy-rel_1_4_7/test/../lib/sqlalchemy/util/deprecations.py", line 60, in warn_deprecated_20
    _warn_with_version(
  File "/home/lccy/sqlalchemy-rel_1_4_7/test/../lib/sqlalchemy/util/deprecations.py", line 41, in _warn_with_version
    warnings.warn(warn, stacklevel=stacklevel + 1)
sqlalchemy.exc.RemovedIn20Warning: The ``bind`` argument for schema methods that invoke SQL against an engine or connection will be required in SQLAlchemy 2.0. (Background on SQLAlchemy 2.0 atp://sqlalche.me/e/b8d9)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**test fixes from non-gerrit builds** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2746

**Comment by zzzeek** [comment]
thanks for reporting!
