### ISSUE TITLE
new proxy thing for Session makes subclassing hard

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6285]
from https://github.com/pallets/flask-sqlalchemy/issues/953

```python
from sqlalchemy.orm import Session, sessionmaker, scoped_session
from sqlalchemy import create_engine



class MySession(Session):
    def get_bind(self, mapper=None, **kwargs):
        return super().get_bind(mapper=mapper, **kwargs)

#    def get_bind(self, mapper=None, *args, **kwargs):
#        return super().get_bind(mapper=mapper, *args, **kwargs)


e = create_engine("sqlite://")

s1 = MySession(e)
assert s1.get_bind() is e

ss = scoped_session(sessionmaker(e, class_=MySession))

assert ss.get_bind() is e


```

will raise 

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 21, in <module>
    assert ss.get_bind() is e
  File "<string>", line 2, in get_bind
TypeError: get_bind() takes from 1 to 2 positional arguments but 6 were given

```

we can do proxying on kw instead which I think makes this better, not sure if im missing some other negative side effect

```diff
diff --git a/lib/sqlalchemy/util/langhelpers.py b/lib/sqlalchemy/util/langhelpers.py
index b31f316fee..75f4374d8a 100644
--- a/lib/sqlalchemy/util/langhelpers.py
+++ b/lib/sqlalchemy/util/langhelpers.py
@@ -478,7 +478,7 @@ def get_callable_argspec(fn, no_self=False, _is_init=False):
         raise TypeError("Can't inspect callable: %s" % fn)
 
 
-def format_argspec_plus(fn, grouped=True):
+def format_argspec_plus(fn, grouped=True, debug=False):
     """Returns a dictionary of formatted, introspected function arguments.
 
     A enhanced variant of inspect.formatargspec to support code generation.
@@ -558,6 +558,18 @@ def format_argspec_plus(fn, grouped=True):
         defaulted_vals,
         formatvalue=lambda x: "=" + x,
     )
+
+    if spec[0]:
+        apply_kw_proxied = compat.inspect_formatargspec(
+            name_args[1:],
+            spec[1],
+            spec[2],
+            defaulted_vals,
+            formatvalue=lambda x: "=" + x,
+        )
+    else:
+        apply_kw_proxied = apply_kw
+
     if grouped:
         return dict(
             args=args,
@@ -565,6 +577,7 @@ def format_argspec_plus(fn, grouped=True):
             apply_pos=apply_pos,
             apply_kw=apply_kw,
             apply_pos_proxied=apply_pos_proxied,
+            apply_kw_proxied=apply_kw_proxied
         )
     else:
         return dict(
@@ -573,6 +586,7 @@ def format_argspec_plus(fn, grouped=True):
             apply_pos=apply_pos[1:-1],
             apply_kw=apply_kw[1:-1],
             apply_pos_proxied=apply_pos_proxied[1:-1],
+            apply_kw_proxied=apply_kw_proxied[1:-1]
         )
 
 
@@ -634,6 +648,7 @@ def create_proxy_methods(
             metadata = {
                 "name": fn.__name__,
                 "apply_pos_proxied": caller_argspec["apply_pos_proxied"],
+                "apply_kw_proxied": caller_argspec["apply_kw_proxied"],
                 "args": caller_argspec["args"],
                 "self_arg": caller_argspec["self_arg"],
             }
@@ -641,14 +656,14 @@ def create_proxy_methods(
             if clslevel:
                 code = (
                     "def %(name)s(%(args)s):\n"
-                    "    return target_cls.%(name)s(%(apply_pos_proxied)s)"
+                    "    return target_cls.%(name)s(%(apply_kw_proxied)s)"
                     % metadata
                 )
                 env["target_cls"] = target_cls
             else:
                 code = (
                     "def %(name)s(%(args)s):\n"
-                    "    return %(self_arg)s._proxied.%(name)s(%(apply_pos_proxied)s)"  # noqa E501
+                    "    return %(self_arg)s._proxied.%(name)s(%(apply_kw_proxied)s)"  # noqa E501
                     % metadata
                 )
 
diff --git a/test/orm/test_scoping.py b/test/orm/test_scoping.py
index 60ad0285f4..30ced0c221 100644
--- a/test/orm/test_scoping.py
+++ b/test/orm/test_scoping.py
@@ -145,10 +145,10 @@ class ScopedSessionTest(fixtures.MappedTest):
         eq_(
             mock_session.mock_calls,
             [
-                mock.call.add("add", True),
+                mock.call.add("add", _warn=True),
                 mock.call.delete("delete"),
                 mock.call.get(
-                    "Cls", 5, mock.ANY, mock.ANY, mock.ANY, mock.ANY
+                    'Cls', 5, options=None, populate_existing=False, with_for_update=None, identity_token=None
                 ),
             ],
         )

```

**Comment by dpgaspar** [comment]
Any luck on this one @zzzeek ?

**Comment by zzzeek** [comment]
> Any luck on this one @zzzeek ?

so my understanding was flask-sqlalchemy was the main project affected by this and they've worked around it, so I was going to get to this whenever.  However, my [comment](https://github.com/sqlalchemy/sqlalchemy/issues/6285#issue-859014733) above has the patch, so if you'd like to turn this into a PR and verify it fixes your use case, we can push it through as is assuming all the tests pass.

**Comment by zzzeek** [comment]
it looks like they haven't merged their PR yet in any case, so we will get this in.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Adjust create_proxy_methods() to use kw arguments** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2854
