### ISSUE TITLE
`tuple_` empty `in_` cannot be literally compiled

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6290]
**Describe the bug**
cannot literally compile an empty in on a tuple_ element

**Expected behavior**
it would literally compile an empty in on a tuple_ element

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
e = sa.tuple_(sa.column("x"), sa.column("y")).in_([])
e.compile(compile_kwargs={"literal_binds": True})
```

**Error**

```
Traceback (most recent call last):
  File "C:\Users\cfede\Dev\GitHub\sqlalchemy\test4.py", line 9, in <module>
    sa.tuple_(sa.column("x"), sa.column("y"))
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\elements.py", line 506, in compile
    return self._compiler(dialect, **kw)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\elements.py", line 570, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 2042, in visit_binary
    return self._generate_generic_binary(
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 2098, in _generate_generic_binary
    + binary.right._compiler_dispatch(
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 2266, in visit_bindparam
    ret = self.render_literal_bindparam(
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 2357, in render_literal_bindparam
    to_update, replacement_expr = leep(bindparam, value)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\sql\compiler.py", line 1917, in _literal_execute_expanding_parameter_literal_binds
    assert not parameter.type._is_tuple_type
AssertionError
```

**Versions.**
 - OS: any
 - Python: 3.9
 - SQLAlchemy: 1.4+
 - Database: any
 - DBAPI: any

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
can you plaese work up tests in test/sql/test_operator.py for this patch:

```
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 0c701cb523..a466216e3c 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1914,10 +1914,14 @@ class SQLCompiler(Compiled):
     ):
 
         if not values:
-            assert not parameter.type._is_tuple_type
-            replacement_expression = self.visit_empty_set_expr(
-                [parameter.type]
-            )
+            if parameter.type._is_tuple_type:
+                replacement_expression = (
+                    "VALUES " if self.dialect.tuple_in_values else ""
+                ) + self.visit_empty_set_expr(parameter.type.types)
+            else:
+                replacement_expression = self.visit_empty_set_expr(
+                    [parameter.type]
+                )
 
         elif isinstance(values[0], (tuple, list)):
             assert parameter.type._is_tuple_type
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index e97ed252eb..699a874fb8 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -1407,8 +1407,8 @@ class BindParameter(roles.InElementRole, ColumnElement):
                 self.type = type_api._resolve_value_to_type(check_value)
         elif isinstance(type_, type):
             self.type = type_()
-        elif type_._is_tuple_type:
-            if expanding and value:
+        elif type_._is_tuple_type and value:
+            if expanding:
                 check_value = value[0]
             else:
                 check_value = value

```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fit literal compile of empty in on a tuple** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2751
