### ISSUE TITLE
Declarative Base with __iter__ Compatibility with 1.4+ Selectable

### ISSUE THREAD

**Issue by dgilland** [sqlalchemy/sqlalchemy#6300]
In sqlalchemy `1.4`, if a custom declarative base class defines an `__iter__` method, then it cannot be used in `select(SomeModel)` unless it's wrapped with a `list`. Otherwise, an exception is raised (see example and traceback below).

Is this the intended behavior?

**Example**

```python
from sqlalchemy import create_engine, select
from sqlalchemy.orm import declarative_base

class Base:
    def __iter__(self):
        # some method to yield key/value tuples for dict(instance) conversion
        data = {k: v for k, v in self.__dict__.items() if not k.startswith("_sa_")}
        yield from data.items()

Base = declarative_base(cls=Base)

class User(Base):
    __tablename__ = "users"
    id = sa.Column(sa.Integer(), primary_key=True)
    name = sa.Column(sa.Text())

engine = create_engine("sqlite://")
Base.metadata.create_all(engine)

stmt = select([User])  # <-- no error when wrapped with list
stmt = select(User)    # <-- throws error below
```

**Complete stack trace**
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<string>", line 2, in select
  File "<snip>/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4893, in _create
    return cls.create_legacy_select(*args, **kw)
  File "<string>", line 2, in create_legacy_select
  File "<snip>/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "<snip>/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4771, in create_legacy_select
    self._raw_columns = [
TypeError: 'DeclarativeMeta' object is not iterable
```

**Versions**
 - OS: MacOS 11.2.3
 - Python: 3.9.4
 - SQLAlchemy: 1.4.8
 - Database: sqlite3
 - DBAPI: sqlite3

**Comment by zzzeek** [comment]
hi and thanks for reporting.

this is a regression..of a regression.     Original regression is #5935.   now we have to tune back the other way.   For now, use a list for that entity, for devs we will apply this patch + new tests as follows:

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index 2a221cdf0b..878ff58605 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -55,6 +55,7 @@ from .elements import TableValuedColumn
 from .elements import UnaryExpression
 from .visitors import InternalTraversal
 from .. import exc
+from ..inspection import inspect
 from .. import util
 
 if util.TYPE_CHECKING:
@@ -4887,8 +4888,16 @@ class Select(
         """
         if (
             args
-            and hasattr(args[0], "__iter__")
-            and not isinstance(args[0], util.string_types + (ClauseElement,))
+            and (
+                isinstance(args[0], list)
+                or (
+                    hasattr(args[0], "__iter__")
+                    and not isinstance(
+                        args[0], util.string_types + (ClauseElement,)
+                    )
+                    and not inspect(args[0], raiseerr=False)
+                )
+            )
         ) or kw:
             return cls.create_legacy_select(*args, **kw)
         else:
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure iterable passed to Select is not a mapped class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2794
