### ISSUE TITLE
columns objects require explicit types for alembic statements

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#6336]
**Describe the bug**

Prior to SQLAlchemy 1.4, simple `table` and `column` objects could be used to render statements without providing types to `column`, but this now produces an error.

```python
my_table = table('my_table', column('i'))

def upgrade():
    op.execute(my_table.update().values(i=0))
```

**Expected behavior**

`alembic upgrade base:head --sql` should produce `UPDATE my_table SET i = 0` without error. If giving types is required now, then I expected to find a change log entry.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

I think this is something to do with literal_binds but I wasn't able to produce a `.compile()` that did the right thing on SQLAlchemy 1.3 for an MCVE, but this is what the alembic revision would look like.

```python
my_table = table('my_table', column('i'))

def upgrade():
    op.execute(my_table.update().values(i=0))
```

**Error**

```
Traceback (most recent call last):
  ...
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/.../migrations/env.py", line 230, in <module>
    run_migrations_offline()
  File "/Users/.../migrations/env.py", line 129, in run_migrations_offline
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 560, in run_migrations
    step.migration_fn(**kw)
  File "/Users/.../migrations/versions/redacted.py", line 252, in upgrade
    op.execute(my_table.update().values(i=0))
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/operations/ops.py", line 2075, in execute
    return operations.invoke(op)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/operations/base.py", line 354, in invoke
    return fn(self, operation)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 180, in execute_sql
    operations.migration_context.impl.execute(
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 150, in execute
    self._exec(sql, execution_options)
  File "/Users/.../venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 134, in _exec
    construct.compile(dialect=self.dialect, **compile_kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 506, in compile
    return self._compiler(dialect, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 570, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3654, in visit_update
    crud_params = crud._get_crud_params(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 148, in _get_crud_params
    _scan_cols(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 371, in _scan_cols
    _append_param_parameter(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 482, in _append_param_parameter
    value = _handle_values_anonymous_param(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 236, in _handle_values_anonymous_param
    return value._compiler_dispatch(compiler, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 603, in visit_bindparam
    text = super(PGCompiler_psycopg2, self).visit_bindparam(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2270, in visit_bindparam
    ret = self.render_literal_bindparam(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2364, in render_literal_bindparam
    return self.render_literal_value(value, bindparam.type)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2227, in render_literal_value
    value = super(PGCompiler, self).render_literal_value(value, type_)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2379, in render_literal_value
    return processor(value)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 3145, in process
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Don't know how to render literal SQL value: 0
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.9.1
 - SQLAlchemy: 1.4.10
 - Database: PostgreSQL
 - DBAPI: psycopg2

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
I'd have to bisect to see where the change occurred but from my testing below this did not work in SQLAlchemy 1.3 either, it does sometihng worse which is to emit the wrong SQL:

```
from sqlalchemy import table, column

my_table = table('my_table', column('i'))

stmt =my_table.update().values(i=0)

print(stmt.compile(compile_kwargs={"literal_binds": True}))
```

output:

    UPDATE my_table SET i=NULL

that's not just the zero, it does it for any value:

```
from sqlalchemy import table, column

my_table = table('my_table', column('i'))

stmt =my_table.update().values(i=5)

print(stmt.compile(compile_kwargs={"literal_binds": True}))


stmt =my_table.update().values(i="some value")

print(stmt.compile(compile_kwargs={"literal_binds": True}))

```
```

UPDATE my_table SET i=NULL
UPDATE my_table SET i=NULL

```

if you give the column a type, then 1.3 seems to know how to render it.   

Maybe the PG dialect is different?  not here at least...

```
from sqlalchemy import table, column
from sqlalchemy.dialects import postgresql


def run_w_value(val):
    my_table = table("my_table", column("i"))

    stmt = my_table.update().values(i=val)

    print(
        stmt.compile(
            dialect=postgresql.dialect(),
            compile_kwargs={"literal_binds": True},
        )
    )


run_w_value(5)
run_w_value(0)
run_w_value("hi")

```

```
UPDATE my_table SET i=NULL
UPDATE my_table SET i=NULL
UPDATE my_table SET i=NULL

```


did you observe that the value "0" would be rendered when running on alembic?

**Comment by CaselIT** [comment]
I think this qualifies as a bug also on 1.3?

**Comment by zzzeek** [comment]
it's a bug in 1.3 but in 1.4 I think the behavior might be correct

**Comment by CaselIT** [comment]
yes, I guess so for 1.4, since we don't know how to literally compile a null type and `str()` does not seem a sensible option in the general case

**Comment by zzzeek** [comment]
it might *not* be correct because we do infer types for bound parameters.  it might be that this doesnt happen in update() / insert() -> crud.py.

**Comment by RazerM** [comment]
Right, I can confirm 1.3 produces the wrong output too. I thought I had checked that already but I must have not reset my git checkout...

The error in 1.4 is definitely preferable to silently producing `SET i=NULL` then.
