### ISSUE TITLE
Using text() inside a union_all select raises an exception

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#6343]
**Describe the bug**

Trying to use `union_all` with `select` statements containing a `text()` construct fail to compile.

**Expected behavior**

The MCVE below produces this output on SQLAlchemy 1.3

```
INSERT INTO t3 (id, name) SELECT t1.id, 'whatever' 
FROM t1
INSERT INTO t3 (id, name) SELECT t1.id, 'whatever' 
FROM t1 UNION ALL SELECT t2.id, 'whatever' 
FROM t2
```

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
from sqlalchemy import column, select, text, table
from sqlalchemy.dialects import postgresql

dialect = postgresql.dialect()

t1 = table('t1', column('id'))
t2 = table('t2', column('id'))

# Obviously `literal('whatever')` makes more sense here,
# but it illustrates the problem with using `text()`
stmt1 = select([t1.c.id, text("'whatever'")])
stmt2 = stmt1.union_all(select([t2.c.id, text("'whatever'")]))

print(stmt1.compile(dialect=dialect))
print(stmt2.compile(dialect=dialect))
```

**Error**

```
SELECT t1.id, 'whatever' 
FROM t1
Traceback (most recent call last):
  File "/Users/.../scratch_30.py", line 14, in <module>
    print(stmt2.compile(dialect=dialect))
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 506, in compile
    return self._compiler(dialect, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 570, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1809, in visit_compound_select
    text = (" " + keyword + " ").join(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 1811, in <genexpr>
    c._compiler_dispatch(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3029, in visit_select
    froms = self._setup_select_stack(
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3159, in _setup_select_stack
    numcols = len(select_0.selected_columns)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1160, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5640, in selected_columns
    [(conv(c), c) for c in self._exported_columns_iterator()]
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5640, in <listcomp>
    [(conv(c), c) for c in self._exported_columns_iterator()]
  File "/Users/.../venv/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4142, in go
    name = c._proxy_key
AttributeError: 'TextClause' object has no attribute '_proxy_key'
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.9.1
 - SQLAlchemy: 1.4.11
 - Database: N/A
 - DBAPI: N/A

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
this is another one where, you really don't want to be doing that, as it will do the wrong thing in 1.3 in lots of situations as well.  such as:

```python

stmt1 = select([t1.c.id, text("'whatever'")])

stmt2 = stmt1.union_all(select([t2.c.id, text("'whatever'")])).alias().select()

print(stmt2.compile(dialect=dialect))
```


output:

```
SELECT anon_1.id 
FROM (SELECT t1.id AS id, 'whatever' 
FROM t1 UNION ALL SELECT t2.id AS id, 'whatever' 
FROM t2) AS anon_1
```

seems like it lost that column on the outside.

So, this is probably something I should have deprecated in 1.4 because the text() object doesnt support being turned into a column.   or we have to figure out how to make text() act more like a column than it did before.   not really sure, but you have your solution which is to use literal_column().

**Comment by zzzeek** [comment]
1.4 seems to do most of the same tings 1.3 does and the error here is very specific to union so i can fix that to do the same weird thing as 1.3.

**Comment by CaselIT** [comment]
I think it could raise an explicit unsupported error. This raises the same error:
```py
import sqlalchemy as sa
sa.select(sa.text('whatever')).selected_columns
```

**Comment by CaselIT** [comment]
> 
> 
> 1.4 seems to do most of the same tings 1.3 does and the error here is very specific to union so i can fix that to do the same weird thing as 1.3.

I think it's very general as error, see the select exemple

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**omit text from selected_columns; clear memoizations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2769

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Suggest ``literal_column`` instead of ``text`` for column elements** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2771

**Comment by kevr** [comment]
I'm sorry, this isn't actually a real part of the thread, but I just have to vent: What the hell is with sqlite; they should've just named it almostsql or notreallysql instead. There are so many sql dialects that it doesn't support.

What a downer.
