### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'pysqlite' is not async.

### ISSUE THREAD

**Issue by Timtaran** [sqlalchemy/sqlalchemy#6355]
```py
#https://docs.sqlalchemy.org/en/14/_modules/examples/asyncio/async_orm.html
#"sqlite:///database.sqlite3",
#If  "aiosqlite:///database.sqlite3", - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:aiosqlite
```

**Error**

```
Traceback (most recent call last):
  File "D:/Timur/LSN/main.py", line 2, in <module>
    from src import async_main
  File "D:\Timur\LSN\src\__init__.py", line 1, in <module>
    from .bd import *
  File "D:\Timur\LSN\src\bd\__init__.py", line 1, in <module>
    from .main import async_main, A, B
  File "D:\Timur\LSN\src\bd\main.py", line 101, in <module>
    asyncio.run(async_main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\Timur\LSN\src\bd\main.py", line 44, in async_main
    engine = create_async_engine(
  File "D:\Timur\LSN\venv\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 48, in create_async_engine
    return AsyncEngine(sync_engine)
  File "D:\Timur\LSN\venv\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 538, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'pysqlite' is not async.

Process finished with exit code 1

```

**Versions.**
 - OS: Win7x64
 - Python: 3.8.6
 - SQLAlchemy: 1.4.11
 - Database: sqlite
 - DBAPI: aiosqlite

**Additional context**

**Have a nice day!**

**Comment by Timtaran** [comment]
sqlite+aiosqlite
