### ISSUE TITLE
SQLAlchemy does not autoconvert type when using `asyncpg`

### ISSUE THREAD

**Issue by Ahsoka** [sqlalchemy/sqlalchemy#6364]
## Describe the bug

Whenever I use SQLAlchemy with `asyncpg` and I input the incorrect type SQLAlchemy does not attempt to convert the type to the correct type, unlike when I am using SQLAlchemy with `psycopg2`.  See the examples below for reference.  I am not sure if this intended behavior or not.

### Using `psycopg2`
```py
create_table = '''
CREATE TABLE dtype_test (
    index BIGINT,
    "A" FLOAT(53),
    "B" TEXT
)
'''

url = ...
engine = create_engine(url)

with engine.begin() as conn:
    conn.execute(text(create_table))
    # "B" should be an str but here it's boolean
    # SQLAlchemy or psycopg2 automatically converts to an str
    conn.execute(
        text('INSERT INTO dtype_test (index, "A", "B") VALUES(:index, :a, :b)'),
        {'index': 0, 'a': 0.8, 'b': True}
    )
# Runs with no issue
```

### Using `asyncpg`
```py
url = ...

create_table = '''
CREATE TABLE dtype_test (
    index BIGINT,
    "A" FLOAT(53),
    "B" TEXT
)
'''

engine = create_async_engine(url)
async with engine.begin() as conn:
    await conn.execute(text(create_table))
    # Using the wrong type here for "B"
    await conn.execute(text(
        'INSERT INTO dtype_test (index, "A", "B") VALUES(:index, :a, :b)'),
        {'index': 0, 'a': 0.8, 'b': True}
    )
# This errors out, see error below
```

**Error**

```
Traceback (most recent call last):
  File "asyncpg\protocol\prepared_stmt.pyx", line 155, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\protocol\codecs/base.pyx", line 193, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\protocol\codecs/base.pyx", line 104, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\pgproto\./codecs/text.pyx", line 29, in asyncpg.pgproto.pgproto.text_encode
  File "asyncpg\pgproto\./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got bool

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 412, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\asyncpg\prepared_stmt.py", line 168, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\asyncpg\prepared_stmt.py", line 233, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\asyncpg\prepared_stmt.py", line 222, in __do_execute
    return await executor(protocol)
  File "asyncpg\protocol\protocol.pyx", line 181, in bind_execute
  File "asyncpg\protocol\prepared_stmt.pyx", line 171, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $3: True (expected str, got bool)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1706, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 61, in await_only
    return current.driver.switch(awaitable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 114, in greenlet_spawn
    value = await result
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: True (expected str, got bool)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "error.py", line 42, in <module>
    asyncio.run(main())
  File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "error.py", line 40, in main
    await conn.execute(text(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 411, in execute
    result = await greenlet_spawn(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 119, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1521, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1390, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1749, in _execute_context
    self._handle_dbapi_exception(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1930, in _handle_dbapi_exception
    util.raise_(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1706, in _execute_context
    self.dialect.do_execute(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 61, in await_only
    return current.driver.switch(awaitable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 114, in greenlet_spawn
    value = await result
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: True (expected str, got bool)
[SQL: INSERT INTO dtype_test (index, "A", "B") VALUES(%s, %s, %s)]
[parameters: (0, 0.8, True)]
(Background on this error at: http://sqlalche.me/e/14/dbapi)
```

**Versions.**
 - OS: Windows 10
 - Python: 3.8.5
 - SQLAlchemy: 1.4.11
 - Database: PostgreSQL
 - DBAPI: `asyncpg` and `psycopg2`

**Have a nice day!**

**Comment by zzzeek** [comment]
SQLAlchemy doesn't infer types when they are passed to connection.execute(), it only does its own inference when SQL constructs are being constructed, such as if you say something like `select(table.c.x == 5)`.

if asyncpg is complaining about types you would have to supply these upfront.  you can send the values directly to text.bindparams() where it will infer the types:

```python
stmt = text(
     'INSERT INTO dtype_test (index, "A", "B") VALUES(:index, :a, :b)'
).bindparams(index=0, a=0.8, b=True)
```
you could use those values as placeholders, they will be overridden if you supply different values to .execute().

or you can send just the datatypes, but the syntax is more verbose at the moment:

```python
stmt = text(
     'INSERT INTO dtype_test (index, "A", "B") VALUES(:index, :a, :b)'
).bindparams(bindparam("index", type_=Integer), bindparam("a", type_=Float), bindparam("b", type_=Boolean)))
```
