### ISSUE TITLE
1.4.11 Got Future <Future pending> attached to a different loop when using asyncio.gather()

### ISSUE THREAD

**Issue by FNSdev** [sqlalchemy/sqlalchemy#6409]
**Describe the bug**
Hi everyone!

We are using `asyncio.gather()` to run a few tasks that use the same AsyncEngine. It worked fine in 1.4.10, however, it works neither in 1.4.11 nor 1.4.12.

We are getting `Got Future <Future pending> attached to a different loop` if there is more than one future passed into the `asyncio.gather`.

**Expected behavior**

All futures should be processed without errors.

**To Reproduce**

```py
import asyncio

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine(
    'postgresql+asyncpg://postgres:admin@127.0.0.1:5432/postgres',
    future=True,
    pool_size=100,
    max_overflow=100,
)


async def main():
    tasks = [
        task()
        for _ in range(2)
    ]

    await asyncio.gather(*tasks)


async def task():
    async with engine.begin() as connection:
        result = await connection.execute(text('select 1 = 1'))


if __name__ == '__main__':
    asyncio.run(main())

```

**Error**

```
Traceback (most recent call last):
  File "/home/fns/workspace/work/example/main.py", line 30, in <module>
    asyncio.run(main())
  File "/home/fns/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/fns/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/fns/workspace/work/example/main.py", line 20, in main
    await asyncio.gather(*tasks)
  File "/home/fns/workspace/work/example/main.py", line 24, in task
    async with engine.begin() as connection:
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/base.py", line 15, in __aenter__
    return await self.start()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 522, in start
    await self.conn.start()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 111, in start
    self.sync_connection = await (greenlet_spawn(self.sync_engine.connect))
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 119, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 438, in connect
    return super(Engine, self).connect()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3096, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 92, in __init__
    else engine.raw_connection()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3175, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3142, in _wrap_pool_connect
    return fn()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect()
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 616, in __connect
    pool.dispatch.connect.for_modify(
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 327, in _exec_w_sync_on_first_run
    with self._exec_once_mutex:
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 139, in __enter__
    await_fallback(self.mutex.acquire())
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 85, in await_fallback
    return current.driver.switch(awaitable)
  File "/home/fns/.pyenv/versions/3.9.1/envs/example/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 114, in greenlet_spawn
    value = await result
  File "/home/fns/.pyenv/versions/3.9.1/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-3' coro=<task() running at /home/fns/workspace/work/example/main.py:24> cb=[gather.<locals>._done_callback() at /home/fns/.pyenv/versions/3.9.1/lib/python3.9/asyncio/tasks.py:761]> got Future <Future pending> attached to a different loop
```

**Versions.**
 - OS: Linux Mint 19.3 / Ubuntu 18.04
 - Python: 3.9.1
 - SQLAlchemy: 1.4.11, 1.4.12
 - Database: PostgreSQL
 - DBAPI: asyncpg

**Additional context**

We have figured out that we need to execute any query with engine before using it in the tasks, like this:

```py
import asyncio

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine(
    'postgresql+asyncpg://postgres:admin@127.0.0.1:5431/postgres',
    future=True,
    pool_size=100,
    max_overflow=100,
)


async def main():
    async with engine.begin() as connection:
        await connection.execute(text('select 1 = 1'))

    tasks = [
        task()
        for _ in range(100)
    ]

    await asyncio.gather(*tasks)


async def task():
    async with engine.begin() as connection:
        await connection.execute(text('select 1 = 1'))


if __name__ == '__main__':
    asyncio.run(main())

```

However, we do not understand why.

**Thank you and have a nice day!**

**Comment by zzzeek** [comment]
likely due to #6337 .  we were missing a lock previously.

**Comment by zzzeek** [comment]
so it has to do with this thing @CaselIT showed me which is that some event loop gets assigned ahead of time, so the test case here works if you create the engine in the await loop, but we will try to fix this

```python
import asyncio

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine



async def main():
    engine = create_async_engine(
        'postgresql+asyncpg://scott:tiger@localhost/test',
        future=True,
        pool_size=100,
        max_overflow=100,
    )

    tasks = [
        task(engine)
        for _ in range(2)
    ]

    await asyncio.gather(*tasks)


async def task(engine):
    async with engine.begin() as connection:
        result = await connection.execute(text('select 1 = 1'))


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by zzzeek** [comment]
or initialize your engine in the awaitable before calling gather().  not sure what gather() has to do with this but it does.

```python
async def main():
    tasks = [
        task()
        for _ in range(2)
    ]

    conn = await engine.connect()
    await conn.close()

    await asyncio.gather(*tasks)

```

**Comment by zzzeek** [comment]
@Caselit what do you think of this?

```diff

diff --git a/lib/sqlalchemy/util/_concurrency_py3k.py b/lib/sqlalchemy/util/_concurrency_py3k.py
index b905f903b8..74492cf5e7 100644
--- a/lib/sqlalchemy/util/_concurrency_py3k.py
+++ b/lib/sqlalchemy/util/_concurrency_py3k.py
@@ -133,9 +133,14 @@ async def greenlet_spawn(
 
 class AsyncAdaptedLock:
     def __init__(self):
-        self.mutex = asyncio.Lock()
+        self.mutex = None
 
     def __enter__(self):
+        # seems like a race right?  but it's asyncio, no racing
+        # unless await were used
+        if self.mutex is None:
+            self.mutex = asyncio.Lock()
+
         await_fallback(self.mutex.acquire())
         return self
 

```

**Comment by CaselIT** [comment]
testing for this is a mess :(

**Comment by zzzeek** [comment]
note I'm not able to reproduce this from python 3.10 on forward even if I check out 1.4.11.   it repros in python 3.8.
