### ISSUE TITLE
How to express SELECT FROM (INSERT INTO ... RETURNING) in 1.4?

### ISSUE THREAD

**Issue by mathrick** [sqlalchemy/sqlalchemy#6425]
**Describe your question**

Context: I'm writing a system that needs to do a high volume of correlated inserts (coming from another DB which stores denormalised records, so I'm essentially splitting a single object into multiple sub-objects mapped in different tables). Since I know I will have millions of rows to write, I'm trying to batch the writes and do lookup-or-create of the referenced objects inline, without incurring a roundtrip for every single row while SQLAlchemy looks things up.

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

I have the following SQL query for the lookup-or-create portion:

```sql
WITH token_vals (git_branch, git_commit, git_tree_clean, extras) AS (
     (VALUES
        ('foo', 'bar', true, NULL::JSONB),
        ('bar', 'asd', true, NULL::JSONB),
        ('baz', 'bar', true, NULL::JSONB)
     )),
     existing_tokens AS (
     SELECT source_tokens.* FROM source_tokens, token_vals
     WHERE source_tokens.git_branch IS NOT DISTINCT FROM token_vals.git_branch AND
           source_tokens.git_commit IS NOT DISTINCT FROM token_vals.git_commit AND
           source_tokens.git_tree_clean IS NOT DISTINCT FROM token_vals.git_tree_clean AND
           source_tokens.extras IS NOT DISTINCT FROM token_vals.extras
     ),
     inserted_tokens AS (
     INSERT INTO source_tokens(git_branch, git_commit, git_tree_clean, extras)
     SELECT token_vals.* FROM source_tokens, token_vals
     WHERE NOT EXISTS (
           SELECT id FROM source_tokens
           WHERE source_tokens.git_branch IS NOT DISTINCT FROM token_vals.git_branch AND
                 source_tokens.git_commit IS NOT DISTINCT FROM token_vals.git_commit AND
                 source_tokens.git_tree_clean IS NOT DISTINCT FROM token_vals.git_tree_clean AND
                 source_tokens.extras IS NOT DISTINCT FROM token_vals.extras
     )
     RETURNING *
)
SELECT * FROM existing_tokens UNION SELECT * FROM inserted_tokens;
```

It works fine with PostgreSQL 12. I'm now trying to express this in SQLAlchemy 1.4, and I'm running into a problem, since apparently `table.insert()` is not a valid `FromClause` so it cannot be used in a `union()`:

```python
st = SourceToken.__table__

st_vals = values(
    column('git_branch'),
    column('git_commit'),
    column('git_tree_clean'),
    column('extras'),
).data([
    ('foo', 'bar', True, cast(None, JSONB)),
    ('bar', 'asd', True, cast(None, JSONB)),
    ('baz', 'bar', True, cast(None, JSONB))
])

existing_cond = (
    st.c.git_branch.is_not_distinct_from(st_vals.c.git_branch) &
    st.c.git_commit.is_not_distinct_from(st_vals.c.git_commit) &
    st.c.git_tree_clean.is_not_distinct_from(st_vals.c.git_tree_clean) &
    st.c.extras.is_not_distinct_from(st_vals.c.extras)
)

st_existing = select(st).select_from(st, st_vals.alias('v')).where(existing_cond)

st_inserted = st.insert().from_select(st_vals.c, select(st_vals.c).where(~st_existing.exists())).returning('*')

st_all = st_existing.union(select(st_inserted))
```

**Complete stack trace, if applicable**

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mathrick/Dev/Cerebras/devinfra/grey-haven/grey_haven/model/mapping.py", line 80, in <module>
    st_all = st_existing.union(select(st_inserted))
  File "<string>", line 2, in select
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4909, in _create
    return cls._create_future_select(*args)
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4849, in _create_future_select
    self._raw_columns = [
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 4850, in <listcomp>
    coercions.expect(
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 200, in expect
    return impl._implicit_coercions(
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 242, in _implicit_coercions
    self._raise_for_expected(element, argname, resolved)
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 424, in _raise_for_expected
    return super(_SelectIsNotFrom, self)._raise_for_expected(
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 270, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/home/mathrick/.pyenv/versions/grey-haven/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression or FROM clause expected, got <sqlalchemy.sql.dml.Insert object at 0x7f4cc0be25b0>.
```

**Versions**
 - OS: Ubuntu 20.10
 - Python: 3.8
 - SQLAlchemy: 1.4
 - Database: PostgreSQL 12
 - DBAPI: Psycopg2

**Comment by zzzeek** [comment]
it looks like you want to use CTEs for your UNION at the bottom so that would be more like:

```python
st_vals = st_vals.cte()
st_existing = select(st).select_from(st, st_vals).where(existing_cond).cte()

st_inserted = st.insert().from_select(st_vals.c, select(st_vals.c).where(~st_existing.exists())).returning('*').cte()

st_all = st_existing.union(select(st_inserted))
```

things get a little crazy and i havent tried those examples but all those things should be supported.

also, if you're just trying to get an ETL job done, you've got the query you want in plain SQL and you're definitely all PostgreSQL so there's not much reason you couldn't just using text("""your query""") and be done with it.

**Comment by zzzeek** [comment]
the values construct needs to be from a select() to do cte():


```python
from sqlalchemy import cast
from sqlalchemy import column
from sqlalchemy import select
from sqlalchemy import values
from sqlalchemy.dialects.postgresql import JSONB


st_vals = values(
    column('git_branch'),
    column('git_commit'),
    column('git_tree_clean'),
    column('extras'),
).data([
    ('foo', 'bar', True, cast(None, JSONB)),
    ('bar', 'asd', True, cast(None, JSONB)),
    ('baz', 'bar', True, cast(None, JSONB))
])

st_vals_cte = st_vals.select().cte()

print(select(st_vals_cte))
```
