### ISSUE TITLE
ArgumentError: FROM expression, such as a Table or alias() object expected, got sqlalchemy.sql.selectable.ScalarSelect

### ISSUE THREAD

**Issue by gibizer** [sqlalchemy/sqlalchemy#6429]
After bumping SQLAlchemy to >= 1.4 Some queries in OpenStack Placement started to fail.

2021-05-05 09:40:15.673 | Traceback (most recent call last):
2021-05-05 09:40:15.673 |   File "/opt/stack/new/placement/placement/cmd/manage.py", line 140, in _run_online_migration
2021-05-05 09:40:15.673 |     found, done = migration_meth(ctxt, count)
2021-05-05 09:40:15.673 |   File "/usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/enginefacade.py", line 1014, in wrapper
2021-05-05 09:40:15.673 |     return fn(*args, **kwargs)
2021-05-05 09:40:15.673 |   File "/opt/stack/new/placement/placement/objects/resource_provider.py", line 513, in set_root_provider_ids
2021-05-05 09:40:15.673 |     subq_1 = sa.alias(subq_1.as_scalar(), name="subq_1")
2021-05-05 09:40:15.673 |   File "<string>", line 2, in alias
2021-05-05 09:40:15.673 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/selectable.py", line 1710, in _factory
2021-05-05 09:40:15.673 |     return coercions.expect(
2021-05-05 09:40:15.673 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 200, in expect
2021-05-05 09:40:15.673 |     return impl._implicit_coercions(
2021-05-05 09:40:15.673 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 927, in _implicit_coercions
2021-05-05 09:40:15.673 |     self._raise_for_expected(original_element, argname, resolved)
2021-05-05 09:40:15.674 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 424, in _raise_for_expected
2021-05-05 09:40:15.674 |     return super(_SelectIsNotFrom, self)._raise_for_expected(
2021-05-05 09:40:15.674 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 270, in _raise_for_expected
2021-05-05 09:40:15.674 |     util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
2021-05-05 09:40:15.674 |   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
2021-05-05 09:40:15.674 |     raise exception
2021-05-05 09:40:15.674 | sqlalchemy.exc.ArgumentError: FROM expression, such as a Table or alias() object expected, got <sqlalchemy.sql.selectable.ScalarSelect object at 0x7f3980595c70>.

The actual query is here: https://github.com/openstack/placement/blob/6f00ba5f685183539d0ebf62a4741f2f6930e051/placement/objects/resource_provider.py#L493-L513

The job run where the failure is visible: https://f3901c2ab495edeb466e-702e71c7599c1b8a63aa681f1646fd34.ssl.cf2.rackcdn.com/788471/3/check/nova-grenade-multinode/0f75669/

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8
 - SQLAlchemy: 1.4.13
 - Database: mysql
 - DBAPI: pymsql

**Comment by zzzeek** [comment]
the error is due to this line:

    subq_1 = sa.alias(subq_1.as_scalar(), name="subq_1")


"subq_1" here is not being used as a scalar subquery, and the non-scalar / scalar subquery use cases are mutually exclusive, see https://docs.sqlalchemy.org/en/14/glossary.html#term-subquery for background.

change the code to the following which will work in all SQLAlchemy versions:

    subq_1 = sa.alias(subq_1, name="subq_1")

**Comment by gibizer** [comment]
Thank you for the help. I've pushed a fix on OpenStack side https://review.opendev.org/c/openstack/placement/+/789921

**Comment by gibizer** [comment]
The tests shows that the suggested change cause issue in the outer select. 

`ft1.1: placement.tests.functional.cmd.test_status.UpgradeCheckIncompleteConsumersTestCase.test_check_root_provider_idstesttools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/openstack/placement/.tox/py36/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/openstack/placement/placement/tests/functional/cmd/test_status.py", line 78, in test_check_root_provider_ids
    resource_provider.set_root_provider_ids(self.context, batch_size=50)
  File "/home/zuul/src/opendev.org/openstack/placement/.tox/py36/lib/python3.6/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 1014, in wrapper
    return fn(*args, **kwargs)
  File "/home/zuul/src/opendev.org/openstack/placement/placement/objects/resource_provider.py", line 515, in set_root_provider_ids
    subq_2 = sa.select([subq_1.c.id]).select_from(subq_1)
  File "/home/zuul/src/opendev.org/openstack/placement/.tox/py36/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: id
`

The result is the same with SQLAlchemy==1.3.23 and with SQLAlchemy-1.4.13 .

**Comment by zzzeek** [comment]
hey there -

I had "subq_1 = sa.alias(subq_1, name="subq_1")" for a moment but realized this is a legacy ORM Query object, so as I edited above, use "subq_1 = subq_1.subquery(name="subq_1")"

**Comment by gibizer** [comment]
Thank you. Now it passed the test both with the old and the new SQLAlchemy version
