### ISSUE TITLE
AttributeError: 'sqlalchemy.cimmutabledict.immutabledict' object has no attribute 'setdefault' 

### ISSUE THREAD

**Issue by MuffinAmor** [sqlalchemy/sqlalchemy#6445]
**Describe the bug**
I used Anaconda with Python3.9 (anaconda latest py version) to run a Website used Flask, SQL Alchemy 1.4.14, and some other frameworks/packages/whatever

I have run my project today after updating, and it throws back an internal server error with following console output:
See lower.

**Expected behavior**
i except it throws no error. 

**To Reproduce**
I just run my application, which run without sql erros before. 
Do the same after pip package update.

```py
def create_default_user():
    data = game.query.filter_by(user_name="default").first()
    if not data:
        with open("data/upd.json", encoding='utf-8') as fp:
            user_data = json.load(fp)
        user_data["name"] = "default"
        new_user = game(
            user_name='default',
            game_json=user_data
        )
        new_account = users(
            email="default@lucys-dungeon.de",
            name="default",
            password=encrypt_password('2BeDefault'),
            blocked=False,
            online=False
        )
        db.session.add(new_user)
        db.session.add(new_account)
        db.session.commit()
```

**Error**

```
Traceback (most recent call last):
  File "C:\Users\n-des\Anaconda3\lib\site-packages\sqlalchemy\util\_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <Greenlet at 0x19d9c089480: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket at 0x19d9c1560a0 object, )>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask\app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask\app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "C:\Users\n-des\Desktop\Lucy's Dungeon\lucys-dungeon.de\app\main\auth.py", line 45, in before_first_request
    create_default_user()
  File "C:\Users\n-des\Desktop\Lucy's Dungeon\lucys-dungeon.de\app\main\user_data\__init__.py", line 29, in create_default_user
    data = game.query.filter_by(user_name="default").first()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "C:\Users\n-des\Anaconda3\lib\site-packages\sqlalchemy\orm\scoping.py", line 129, in __call__
    return self.registry()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\sqlalchemy\util\_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "C:\Users\n-des\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 4058, in __call__
    return self.class_(**local_kw)
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 943, in engine
    return self.get_engine()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "C:\Users\n-des\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 884, in apply_driver_hacks
    sa_url.query.setdefault('charset', 'utf8')
AttributeError: 'sqlalchemy.cimmutabledict.immutabledict' object has no attribute 'setdefault'
[2021-05-07 12:08:26,018] INFO in handler: 127.0.0.1 - - [2021-05-07 12:08:26] "GET /favicon.ico HTTP/1.1" 500 136 0.002998

```

**Versions.**
 - OS: Windows 10 20h2
 - Python: 3.9.0
 - SQLAlchemy: 1.4.14
 - Database: Mariadb
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by MuffinAmor** [comment]
Sorry i'm just dump.
Have updated flask-sqlachemy and it had fixed the error.

**Comment by CaselIT** [comment]
Hi,

I was suggesting to open an issue with flask-sqlalchemy. Glad you could resolve
