### ISSUE TITLE
mypy hits an AssertionError when using a custom base class for declarative_base

### ISSUE THREAD

**Issue by VincentVanlaer** [sqlalchemy/sqlalchemy#6476]
The sqlalchemy typing plugin will fail with an AssertionError when the following requirements are satisfied:

1. Use a custom base class for `sql_base = declarative_base(cls=CustomBase)`
2. Use the declarative base as a base class for a new class in another file, importing only `sql_base` and not `CustomBase`
3. Have mypy use a cache

It seems that the custom base class is not included in the context of the derived class/second file when loading from cache, but it is the case when no cache is available (caching disabled or first run). If one explicitly imports `CustomBase` in the second file then the assert no longer happens.

**To Reproduce**
* Install `sqlalchemy[mypy]` either globally or in a virtual environment
* Configure mypy to use the SQLAlchemy plugin in `mypy.ini`
```ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```
* Define a declarative base with a custom base class in the file `base.py`
```py
from sqlalchemy.ext.declarative import declarative_base

class CustomBase:
    pass

sql_base = declarative_base(cls=CustomBase)
```
* Define a table in another python file, using the declarative base in the file `table.py`
```py
from base import sql_base

class Table(sql_base):
    pass

a: int = "a"  # Typing mistake in order to have mypy retry on the next run
```
* Run mypy twice: `python -m mypy base.py table.py`
*  The first time it will populate the cache, the second time it wel load the cache and hit the assert

**Error**

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/__main__.py", line 23, in <module>
    console_entry()
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/build.py", line 2688, in dispatch
    process_graph(graph, manager)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/build.py", line 3012, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/build.py", line 3104, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 394, in refresh_partial
    self.refresh_top_level(node)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 405, in refresh_top_level
    self.accept(d)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 4853, in accept
    node.accept(self)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 1051, in visit_class_def
    self.analyze_class(defn)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 1128, in analyze_class
    self.analyze_class_body_common(defn)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 1137, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/mypy/semanal.py", line 1197, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 199, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
    _scan_for_mapped_bases(cls, api, cls_metadata)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
    _scan_declarative_assignments_and_apply_types(
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
    _scan_for_mapped_bases(cls, api, cls_metadata)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
    _scan_declarative_assignments_and_apply_types(
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 51, in _scan_declarative_assignments_and_apply_types
    info = util._info_for_cls(cls, api)
  File "/home/vincenttc/data/temp/mypy-test/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 211, in _info_for_cls
    assert sym and isinstance(sym.node, TypeInfo)
AssertionError: 
table.py:3: : note: use --pdb to drop into pdb
```

**Versions.**
 - Python: 3.9.4
 - SQLAlchemy: 0d5508d77653b37368ff9de22307c154cc90cf71
 - sqlalchemy2-stubs: sqlalchemy/sqlalchemy2-stubs@e1285079279594336af3ef52f4057753ddc7bdf4
 - mypy: python/mypy@6fac70122c177340d1a1a49747ba244d13a29efd

**Have a nice day!**

**Comment by 3rdcycle** [comment]
Not sure if related but I'm getting a similar assertion with `@as_declarative()`:

```python
@as_declarative()
class OrmBase:
    id = Column('_oid', Integer, primary_key=True)

@declarative_mixin
class DeleteOrphansMixin:
    ...

class ChildType(DeleteOrphansMixin, OrmBase):
    __abstract__ = True
    parent_id = Column('_parent_oid', Integer)
```

throws:
```
Traceback (most recent call last):
  File "mypy/semanal.py", line 4835, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1048, in visit_class_def
  File "mypy/semanal.py", line 1125, in analyze_class
  File "mypy/semanal.py", line 1134, in analyze_class_body_common
  File "mypy/semanal.py", line 1194, in apply_class_plugin_hooks
  File "/.../venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 199, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/.../venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 64, in _scan_declarative_assignments_and_apply_types
    assert cls_metadata.is_mapped
AssertionError: 
/.../main.py:9: : note: use --pdb to drop into pdb

```

Removing/disabling the cache doesn't seem to help though.

**Comment by mazlum** [comment]
+1

**Comment by zzzeek** [comment]
cc @bryanforbes  is this part of what you're looking into?

**Comment by zzzeek** [comment]
thanks for the clear test info , I have a patch that fixes this although i dont know if the behavior going forward from that point is still correct.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**accommodate no cls info found in _scan_declarative** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2881
