### ISSUE TITLE
get_bind() got an unexpected keyword argument 'bind'

### ISSUE THREAD

**Issue by flyher** [sqlalchemy/sqlalchemy#6486]
I'm working in a project which query rows by raw sql

```python
db.session.execute(sqltext, bind=db.get_engine(current_app, 'dbname')).fetchall()
```

after i update flask-sqlalchemy it show me the following error:

```log
Traceback (most recent call last):
  File "***\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "***\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "***\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "***\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "***\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "***\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "***\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "***\backend\service\de.py", line 92, in get_detail_by_id
    rows_count = db.session.execute(
  File "<string>", line 2, in execute
  File "***\lib\site-packages\sqlalchemy\orm\session.py", line 1667, in execute
    bind = self.get_bind(**bind_arguments)
TypeError: get_bind() got an unexpected keyword argument 'bind'
```

And the bug seems as [flask-sqlalchemy#issues/942](https://github.com/pallets/flask-sqlalchemy/issues/942)

- OS: Win10, Ubuntu20
- Python version: 3.9.4, 3.9.1
- Database: sqlite3

can't work well in
```log
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.4.7
```

but work well in:
```log
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.3.21


- Flask-SQLAlchemy version: 2.4.4
- SQLAlchemy version: 1.3.21
```

[sqlalchemy sha1 #6930dfc032c3f9f474e71ab4e021c0ef8384930e](https://github.com/sqlalchemy/sqlalchemy/commit/6930dfc032c3f9f474e71ab4e021c0ef8384930e)

The line 1775 in 1.3.21:
```python
if bind is None:
    bind = self.get_bind(mapper, clause=clause, **kw)
```

and in 1.4.15:
```python
if bind is None:
    bind = self.get_bind(**bind_arguments)
```

**Comment by CaselIT** [comment]
Hi,

This seems to be an issue of flask-sqlalchemy. You seem to point an issue on their tracker, I would suggest asking there for guidance.
