### ISSUE TITLE
NotImplementedError: Don't know how to literal-quote value UUID(...) -- when UUID column used in Index(..., postgresql_where=...)

### ISSUE THREAD

**Issue by peterth3** [sqlalchemy/sqlalchemy#6514]
**Describe the bug**
Creating a postgres partial index that uses a `UUID` column in `postgresql_where` throws a `NotImplementedError`, while using standard SQLAlchemy column types does not throw an error.

**To Reproduce**

```py
import random
import uuid

from sqlalchemy.dialects.postgresql import UUID
import sqlalchemy as sa


# Simple example table
metadata = sa.MetaData()
scatter = sa.Table(
    'scatter',
    metadata,
    sa.Column('x', sa.Integer),
    sa.Column('y', sa.Integer),
    sa.Column('facet_id', UUID(as_uuid=True)),
)
engine = sa.create_engine('postgresql+psycopg2://postgres:@localhost:5432/postgres')
metadata.create_all(engine)

# Insert some data
facet_a = uuid.uuid4()
facet_b = uuid.uuid4()
with engine.begin() as conn:
    for facet_id in (facet_a, facet_b,):
        for _ in range(10):
            conn.execute(
                scatter.insert()
                .values(
                    x=random.randint(0, 100),
                    y=random.randint(0, 100),
                    facet_id=facet_id,
                )
            )

# Create unique partial index on x with facet_a
partial_index = sa.Index(
    'scatter_x_facet_a',
    scatter.c.x,
    unique=True,
    postgresql_where=scatter.c.facet_id == facet_a,
)
partial_index.create(engine)
```

**Error**
```
Traceback (most recent call last):
  File "/Users/peter/Code/sa-bug-create-index/reproduce.py", line 42, in <module>
    partial_index.create(engine)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4171, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3079, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2081, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 485, in traverse_single
    return meth(obj, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 933, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1349, in _execute_ddl
    compiled = ddl.compile(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 522, in compile
    return self._compiler(dialect, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2635, in visit_create_index
    where_compiled = self.sql_compiler.process(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2076, in visit_binary
    return self._generate_generic_binary(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2132, in _generate_generic_binary
    + binary.right._compiler_dispatch(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 603, in visit_bindparam
    text = super(PGCompiler_psycopg2, self).visit_bindparam(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2299, in visit_bindparam
    ret = self.render_literal_bindparam(
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2393, in render_literal_bindparam
    return self.render_literal_value(value, bindparam.type)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2227, in render_literal_value
    value = super(PGCompiler, self).render_literal_value(value, type_)
  File "/Users/peter/.virtualenvs/SA/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 2410, in render_literal_value
    raise NotImplementedError(
NotImplementedError: Don't know how to literal-quote value UUID('f0699ddf-add2-453d-b87c-3dd54d030a04')
```

**Versions.**
 - OS: MacOS+Linux
 - Python: 3.9.1
 - SQLAlchemy: 1.4.15
 - Database: PostgreSQL
 - DBAPI: psycopg2

**Additional context**
You can workaround this issue with casting like so:
```py
partial_index = sa.Index(
    'scatter_x_facet_a',
    scatter.c.x,
    unique=True,
    postgresql_where=sa.cast(scatter.c.facet_id, sa.String) == str(facet_a),
)
partial_index.create(engine)
```
But there's probably a performance penalty with this approach.

**Have a nice day! 😄**

**Comment by CaselIT** [comment]
Hi,

I think you can also just pass a string without the casting, like so:
```py
partial_index = sa.Index(
    'scatter_x_facet_a',
    scatter.c.x,
    unique=True,
    postgresql_where=scatter.c.facet_id == str(facet_a),
)
partial_index.create(engine)
```

In any case the issue is that currently sqlalchemy does not implements literal compile for every type, a similar issue would likely also happen for date time columns.

**Comment by peterth3** [comment]
Thanks @CaselIT! I tried that method without casting and it still throws the exception, because I have the `facet_id` column set with `UUID(as_uuid=True)`. I assumed that `postgresql_where` would work the same way as a normal `select(...).where(...)` method in SQLAlchemy Core.

For example, this works fine:

```py
facet_a_avg_x = conn.execute(
    sa.select([sa.func.avg(scatter.c.x)])
    .where(scatter.c.facet_id == facet_a)
).scalar()
print(facet_a_avg_x)
```

Does SQLAlchemy need to handle where clauses during index creation differently than it handles where clauses like the above?

**Comment by CaselIT** [comment]
Ok, this time I actually tried it. [`type_coerce`](https://docs.sqlalchemy.org/en/14/core/sqlelement.html?highlight=type_coerce#sqlalchemy.sql.expression.type_coerce) to the rescue 
```py
postgresql_where=scatter.c.facet_id == sa.type_coerce(str(facet_a), sa.Text),
```
If you enable the `echo` flag on the engine, the index sql will be generated as
```sql
CREATE UNIQUE INDEX scatter_x_facet_a ON scatter (x) WHERE facet_id = '01a6747a-75db-42e6-8b4b-f8a83ebd116e'
```

> Does SQLAlchemy need to handle where clauses during index creation differently than it handles where clauses like the above?

yes, in a normal query sqlalchemy will use bind parameters and will pass the parameters to the dbapi directly. I guess bind parameters cannot be used in an index generation, so the parameter needs to be literally compiled to the text

**Comment by zzzeek** [comment]
this should also work as literal():


    postgresql_where=scatter.c.facet_id == literal(str(facet_a))
   
or as text() / literal_column:

    postgresql_where=scatter.c.facet_id == literal_column("'%s'" % str(facet_a))

**Comment by CaselIT** [comment]
that were on the list as my next try :)

**Comment by peterth3** [comment]
Thanks @zzzeek and @CaselIT! I'll use the `literal(str(facet_a))` solution.

> I guess bind parameters cannot be used in an index generation, so the parameter needs to be literally compiled to the text

Ahh, that's annoying but I guess it makes sense.
