### ISSUE TITLE
psycopg2 "Can't adapt type" when using any() on array of enums

### ISSUE THREAD

**Issue by versusvoid** [sqlalchemy/sqlalchemy#6515]
**Describe the bug**
"Can't adapt type" from psycopg2 when using `any()` on array-of-enums column

**To Reproduce**

```py
import enum
from sqlalchemy import create_engine, MetaData, Table, Column, Enum
from sqlalchemy.dialects.postgresql import ARRAY

engine = create_engine('postgresql://postgres:postgres@localhost/bug')
meta = MetaData()

class Options(enum.Enum):
    OPTION1 = '1'
    OPTION2 = '2'
    OPTION3 = '3'

table = Table(
    'bug', meta,
    Column('options', ARRAY(Enum(Options))),
)
meta.create_all(engine)
with engine.connect() as conn:
    conn.execute(table.select().where(table.c.options.any(Options.OPTION1)))
```

**Error**
```
Traceback (most recent call last):
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'Options'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug.py", line 30, in <module>
    conn.execute(table.select().where(table.c.options.any(Options.OPTION1)))
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 330, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/home/versus/.local/share/virtualenvs/bug-b_UBd_54/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'Options'
[SQL: SELECT bug.options 
FROM bug 
WHERE %(param_1)s = ANY (bug.options)]
[parameters: {'param_1': <Options.OPTION1: '1'>}]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Linux
 - Python: 3.6
 - SQLAlchemy: 1.4.15
 - Database: PostgreSQL 13.2
 - DBAPI: psycopg2-binary 2.8.6

**Comment by versusvoid** [comment]
Update with
```py
func.array_remove(table.c.options, Options.OPTION1)
```
will give the same error

**Comment by CaselIT** [comment]
Hi,

array of enum is a bit troublesome, we have had s number of other issues all related to casts.

Does using `sa.cast(Options.OPTION1, Enum(Options))` work?

**Comment by versusvoid** [comment]
Yes it does.
I've dug sources a little and reduced example to
```python
import enum
from sqlalchemy import create_engine, MetaData, Table, Column, Enum
from sqlalchemy.dialects.postgresql import ARRAY, dialect

class Options(enum.Enum):
    OPTION1 = '1'
    OPTION2 = '2'
    OPTION3 = '3'

table = Table(
    'bug', MetaData(),
    Column('options', ARRAY(Enum(Options))),
)
d = dialect()

q = table.select().where(table.c.options.contains([Options.OPTION1]))
print(q.compile(dialect=d).bind_names)

q = table.select().where(table.c.options.any(Options.OPTION1))
print(q.compile(dialect=d).bind_names)
```

Following patch fixes this concrete issue with `any()` (tested on b2ab2bbf4faf508b3fa5749969019203a702786f)
```diff
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 4f8654a..a4ba8e5 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -2809,7 +2809,7 @@ class ARRAY(SchemaEventTarget, Indexable, Concatenable, TypeEngine):
             # send plain BinaryExpression so that negate remains at None,
             # leading to NOT expr for negation.
             return elements.BinaryExpression(
-                coercions.expect(roles.ExpressionElementRole, other),
+                coercions.expect(roles.ExpressionElementRole, other, type_=self.type.item_type),
                 elements.CollectionAggregate._create_any(self.expr),
                 operator,
             )
```
but I'm not sure if it is a good idea as a whole

**Comment by zzzeek** [comment]
looking at the codepath used by contains() i think this is the most appropriate approach, short of replacing the construction of the BinaryExpression here with "self.operate()":

```diff
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 4f8654afd9..3d97decf8b 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -2809,7 +2809,12 @@ class ARRAY(SchemaEventTarget, Indexable, Concatenable, TypeEngine):
             # send plain BinaryExpression so that negate remains at None,
             # leading to NOT expr for negation.
             return elements.BinaryExpression(
-                coercions.expect(roles.ExpressionElementRole, other),
+                coercions.expect(
+                    roles.BinaryElementRole,
+                    element=other,
+                    operator=operator,
+                    expr=self.expr,
+                ),
                 elements.CollectionAggregate._create_any(self.expr),
                 operator,
             )
@@ -2849,7 +2854,12 @@ class ARRAY(SchemaEventTarget, Indexable, Concatenable, TypeEngine):
             # send plain BinaryExpression so that negate remains at None,
             # leading to NOT expr for negation.
             return elements.BinaryExpression(
-                coercions.expect(roles.ExpressionElementRole, other),
+                coercions.expect(
+                    roles.BinaryElementRole,
+                    element=other,
+                    operator=operator,
+                    expr=self.expr,
+                ),
                 elements.CollectionAggregate._create_all(self.expr),
                 operator,
             )
```

**Comment by zzzeek** [comment]
ok the above patch is how I think we shoudl do this if someone wants to add some tests and push up a patch.

**Comment by zzzeek** [comment]
and the patch doesnt work in main, so , back to the drawing board

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**properly type array element in any() / all()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3808

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**properly type array element in any() / all()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3809
