### ISSUE TITLE
Python 3.10.0b1 DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.

### ISSUE THREAD

**Issue by hrnciar** [sqlalchemy/sqlalchemy#6540]
**Describe the bug**
SelectableGroups dict interface is deprecated, select should be used instead.

**To Reproduce**
 Build sqlalchemy with Python 3.10.0b1.

**Error**
```
________________________ CreateEngineTest.test_bad_args ________________________
[gw1] linux -- Python 3.10.0 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/engine/test_parseconnect.py", line 523, in test_bad_args
    assert_raises(
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/testing/assertions.py", line 324, in assert_raises
    return _assert_raises(except_cls, callable_, args, kw, check_context=True)
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/testing/assertions.py", line 348, in _assert_raises
    callable_(*args, **kwargs)
  File "<string>", line 2, in create_engine
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/util/langhelpers.py", line 338, in load
    for impl in compat.importlib_metadata_get(self.group):
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/util/compat.py", line 116, in importlib_metadata_get
    return importlib_metadata.entry_points().get(group, ())
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 305, in get
    flake8_bypass(self._warn)()
DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
```

**Versions.**
 - OS: Fedora 34
 - Python: 3.10.0b1
 - SQLAlchemy: 1.4.15

**Additional context**

Downstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1959305
**Have a nice day!**

**Comment by CaselIT** [comment]
Thanks for the report

@zzzeek so that change in import_metadata did indeed made it to python 3.10 :)
We already have some compat machinery for this, but it's probably not working right.

@hrnciar since you seems to be running test on 3.10, did pytest fixed the deprecation warnings it was raising or you are ignoring them for now?

**Comment by hrnciar** [comment]
@CaselIT I think in Fedora we are currently ignoring them. See https://src.fedoraproject.org/rpms/pytest/pull-request/21#request_diff

**Comment by CaselIT** [comment]
Ok, thanks. I was trying to add a py310 gate to the test here https://github.com/CaselIT/sqlalchemy/tree/workflow_test_py10

I'll probably have to look if pytest has already fixed them or to ignore them

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**get tests to pass on python 3.10** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2843

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**get tests to pass on python 3.10** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2843
