### ISSUE TITLE
test TestAsyncAdaptedQueue.test_error_other_loop fails with Python 3.10.0b1

### ISSUE THREAD

**Issue by hrnciar** [sqlalchemy/sqlalchemy#6543]
**Describe the bug**

test TestAsyncAdaptedQueue.test_error_other_loop fails with Python 3.10.0b1

**To Reproduce**
 Build sqlalchemy with Python 3.10.0b1.

**Error**
```
_________________ TestAsyncAdaptedQueue.test_error_other_loop __________________
[gw1] linux -- Python 3.10.0 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/base/test_concurrency_py3k.py", line 208, in test_error_other_loop
    is_true(run[0])
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/testing/assertions.py", line 247, in is_true
    is_(bool(a), True, msg=msg)
  File "/builddir/build/BUILD/SQLAlchemy-1.4.15/test/../lib/sqlalchemy/testing/assertions.py", line 256, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: False is not True
assert False is True
```

**Versions.**
 - OS: Fedora 34
 - Python: 3.10.0b1
 - SQLAlchemy: 1.4.15

**Additional context**

Downstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1959305
**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**get tests to pass on python 3.10** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2843
