### ISSUE TITLE
BIND_PARAMS_ESC changed my sentence

### ISSUE THREAD

**Issue by xiaochaom** [sqlalchemy/sqlalchemy#6562]
**Describe the bug**

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
Save this field to the database: 
    commit_dic = {'branch_id': 541, 'commit_id': '12033e58f19f1c5bc9da64b89bb985493e9059d4', 'commit_msg': 'merge :merge from test'}


```
![image](https://user-images.githubusercontent.com/21215047/120192171-6f451200-c24d-11eb-8158-4a5fb9c5dd61.png)

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
# Copy complete stack trace and error message here, including SQL log output
if applicable.
```

**Versions.**
 - OS:Mac os 11.2.3
 - Python:3.6.8
 - SQLAlchemy:1.4.15
 - Database:5.7
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by xiaochaom** [comment]
`
Traceback (most recent call last):
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1671, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 983, in _init_compiled
    for grp, m in enumerate(parameters)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 983, in <listcomp>
    for grp, m in enumerate(parameters)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1006, in construct_params
    code="cd3x",
sqlalchemy.exc.InvalidRequestError: A value is required for bind parameter 'merge' (Background on this error at: http://sqlalche.me/e/14/cd3x)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/xxx.py", line 306, in execute_update_sql
    raise e
  File "/Users/xxx/xxx.py", line 281, in execute_update_sql
    cursor_result = BaseOrm.connection.execute(sql_str, attr_dict)
  File "<string>", line 2, in execute
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 330, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1677, in _execute_context
    e, util.xxx(statement), parameters, None, None
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1671, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 983, in _init_compiled
    for grp, m in enumerate(parameters)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 983, in <listcomp>
    for grp, m in enumerate(parameters)
  File "/Users/xxx/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1006, in construct_params
    code="cd3x",
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'merge'
[SQL: INSERT INTO git_commit_info(`branch_id`,`commit_id`,`commit_msg`) VALUES (541,'12033e58f19f1c5bc9da64b89bb985493e9059d4','merge %(merge)s from test')]
[parameters: [{}]]
(Background on this error at: http://sqlalche.me/e/14/cd3x)
`

**Comment by xiaochaom** [comment]
My bad, it needs to be escaped
