### ISSUE TITLE
asyncpg connections not being invalidated upon asyncio exceptions

### ISSUE THREAD

**Issue by jamescobonkerr** [sqlalchemy/sqlalchemy#6592]
**Describe the bug**
An asyncio exception (e.g. `CancelledError`) experienced during a call to asyncpg's `execute` method does not result in the invalidation of the dbapi connection. Instead, the connection is returned to the connection pool in a dodgy state. Subsequent executions then pick up the connection and attempt to execute transactions as nested transactions.

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

To mock the dbapi exceptions we are seeing, I am randomly setting the execution timeout to 0. To do this, add the following line to the start of `asyncpg.connection.Connection.execute`: `timeout = timeout if random.random() < 0.9 else 0`.

```py
import asyncio

from sqlalchemy import Column, Integer, String, insert
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


async def async_main():
    engine = create_async_engine(
        "postgresql+asyncpg://user:password@localhost/db",
        echo="debug",
        echo_pool="debug",
        pool_size=1,  # Max 1 connection
        max_overflow=0,
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    while True:  # Loop until we trigger a TimeoutError
        async with engine.begin() as conn:
            try:
                await conn.execute(insert(A), [{"data": "a"}])
            except asyncio.exceptions.TimeoutError:
                # I would expect the connection to be invalidated here
                break

    # XXX: Connection is returned to the pool in a dodgy state

    while True:  # Loop until we _don't_ trigger a TimeoutError
        async with engine.begin() as conn:
            try:
                await conn.execute(insert(A), [{"data": "b"}])  # This reuses the above connection
                break
            except asyncio.exceptions.TimeoutError:
                pass


asyncio.run(async_main())
```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
(.venv)  ~/code/bug  /Users/jamescobon-kerr/code/bug/.venv/bin/python /Users/jamescobon-kerr/code/bug/test.py
2021-06-07 15:21:53,849 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Created new connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40>
2021-06-07 15:21:53,857 INFO sqlalchemy.engine.Engine select version()
2021-06-07 15:21:53,858 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-07 15:21:53,865 DEBUG sqlalchemy.engine.Engine Col ('version',)
2021-06-07 15:21:53,865 DEBUG sqlalchemy.engine.Engine Row ('PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit',)
2021-06-07 15:21:53,865 INFO sqlalchemy.engine.Engine select current_schema()
2021-06-07 15:21:53,866 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-07 15:21:53,869 DEBUG sqlalchemy.engine.Engine Col ('current_schema',)
2021-06-07 15:21:53,870 DEBUG sqlalchemy.engine.Engine Row ('public',)
2021-06-07 15:21:53,873 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2021-06-07 15:21:53,873 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-07 15:21:53,877 DEBUG sqlalchemy.engine.Engine Col ('standard_conforming_strings',)
2021-06-07 15:21:53,878 DEBUG sqlalchemy.engine.Engine Row ('on',)
2021-06-07 15:21:53,881 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> checked out from pool
2021-06-07 15:21:53,882 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-07 15:21:53,884 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%s
2021-06-07 15:21:53,884 INFO sqlalchemy.engine.Engine [generated in 0.00023s] ('a',)
2021-06-07 15:21:53,891 DEBUG sqlalchemy.engine.Engine Col ('relname',)
2021-06-07 15:21:53,891 DEBUG sqlalchemy.engine.Engine Row ('a',)
2021-06-07 15:21:53,891 INFO sqlalchemy.engine.Engine 
DROP TABLE a
2021-06-07 15:21:53,891 INFO sqlalchemy.engine.Engine [no key 0.00010s] ()
2021-06-07 15:21:53,900 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%s
2021-06-07 15:21:53,900 INFO sqlalchemy.engine.Engine [cached since 0.01649s ago] ('a',)
2021-06-07 15:21:53,906 DEBUG sqlalchemy.engine.Engine Col ('relname',)
2021-06-07 15:21:53,906 INFO sqlalchemy.engine.Engine 
CREATE TABLE a (
        id SERIAL NOT NULL, 
        data VARCHAR, 
        PRIMARY KEY (id)
)


2021-06-07 15:21:53,906 INFO sqlalchemy.engine.Engine [no key 0.00016s] ()
2021-06-07 15:21:53,920 INFO sqlalchemy.engine.Engine COMMIT
2021-06-07 15:21:53,924 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> being returned to pool
2021-06-07 15:21:53,924 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> rollback-on-return
2021-06-07 15:21:53,924 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> checked out from pool
2021-06-07 15:21:53,925 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-07 15:21:53,926 INFO sqlalchemy.engine.Engine INSERT INTO a (data) VALUES (%s) RETURNING a.id
2021-06-07 15:21:53,926 INFO sqlalchemy.engine.Engine [generated in 0.00017s] ('a',)
2021-06-07 15:21:53,934 DEBUG sqlalchemy.engine.Engine Col ('id',)
2021-06-07 15:21:53,934 DEBUG sqlalchemy.engine.Engine Row (1,)
2021-06-07 15:21:53,934 INFO sqlalchemy.engine.Engine COMMIT
2021-06-07 15:21:53,939 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> being returned to pool
2021-06-07 15:21:53,939 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> rollback-on-return
2021-06-07 15:21:53,939 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> checked out from pool
2021-06-07 15:21:53,939 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-07 15:21:53,940 INFO sqlalchemy.engine.Engine INSERT INTO a (data) VALUES (%s) RETURNING a.id
2021-06-07 15:21:53,940 INFO sqlalchemy.engine.Engine [cached since 0.01412s ago] ('a',)
2021-06-07 15:21:53,940 INFO sqlalchemy.engine.Engine COMMIT
2021-06-07 15:21:53,940 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> being returned to pool
2021-06-07 15:21:53,940 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> rollback-on-return
2021-06-07 15:21:53,941 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> checked out from pool
2021-06-07 15:21:53,941 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-07 15:21:53,942 INFO sqlalchemy.engine.Engine INSERT INTO a (data) VALUES (%s) RETURNING a.id
2021-06-07 15:21:53,942 INFO sqlalchemy.engine.Engine [cached since 0.01634s ago] ('b',)
2021-06-07 15:21:53,946 INFO sqlalchemy.engine.Engine ROLLBACK
2021-06-07 15:21:53,946 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> being returned to pool
2021-06-07 15:21:53,946 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x108b5aa40> rollback-on-return
Traceback (most recent call last):
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 684, in _start_transaction
    await self._transaction.start()
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/asyncpg/transaction.py", line 138, in start
    await self._connection.execute(query)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 300, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.NoActiveSQLTransactionError: SAVEPOINT can only be used in transaction blocks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 378, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 686, in _start_transaction
    self._handle_exception(error)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.Error: <class 'asyncpg.exceptions.NoActiveSQLTransactionError'>: SAVEPOINT can only be used in transaction blocks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamescobon-kerr/code/bug/test.py", line 56, in <module>
    asyncio.run(async_main())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/jamescobon-kerr/code/bug/test.py", line 43, in async_main
    await conn.execute(insert(A), [{"data": "b"}])  # This reuses the above connection
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 398, in execute
    result = await greenlet_spawn(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 120, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 378, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 686, in _start_transaction
    self._handle_exception(error)
  File "/Users/jamescobon-kerr/code/bug/.venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.NoActiveSQLTransactionError'>: SAVEPOINT can only be used in transaction blocks
[SQL: INSERT INTO a (data) VALUES (%s) RETURNING a.id]
[parameters: ('b',)]
(Background on this error at: http://sqlalche.me/e/14/dbapi)
```

```
postgres_1  | 2021-06-07 14:21:53.881 UTC [43] LOG:  statement: BEGIN ISOLATION LEVEL READ COMMITTED;
postgres_1  | 2021-06-07 14:21:53.885 UTC [43] LOG:  execute __asyncpg_stmt_3__: select version()
postgres_1  | 2021-06-07 14:21:53.891 UTC [43] LOG:  execute __asyncpg_stmt_4__: select current_schema()
postgres_1  | 2021-06-07 14:21:53.895 UTC [43] LOG:  execute __asyncpg_stmt_5__: show transaction isolation level
postgres_1  | 2021-06-07 14:21:53.899 UTC [43] LOG:  execute __asyncpg_stmt_6__: show standard_conforming_strings
postgres_1  | 2021-06-07 14:21:53.902 UTC [43] LOG:  statement: ROLLBACK;
postgres_1  | 2021-06-07 14:21:53.907 UTC [43] LOG:  statement: BEGIN ISOLATION LEVEL READ COMMITTED;
postgres_1  | 2021-06-07 14:21:53.912 UTC [43] LOG:  execute __asyncpg_stmt_7__: select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=$1
postgres_1  | 2021-06-07 14:21:53.912 UTC [43] DETAIL:  parameters: $1 = 'a'
postgres_1  | 2021-06-07 14:21:53.919 UTC [43] LOG:  execute __asyncpg_stmt_8__:
postgres_1  | 	DROP TABLE a
postgres_1  | 2021-06-07 14:21:53.927 UTC [43] LOG:  execute __asyncpg_stmt_9__: select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=$1
postgres_1  | 2021-06-07 14:21:53.927 UTC [43] DETAIL:  parameters: $1 = 'a'
postgres_1  | 2021-06-07 14:21:53.934 UTC [43] LOG:  execute __asyncpg_stmt_a__:
postgres_1  | 	CREATE TABLE a (
postgres_1  | 		id SERIAL NOT NULL,
postgres_1  | 		data VARCHAR,
postgres_1  | 		PRIMARY KEY (id)
postgres_1  | 	)
postgres_1  |
postgres_1  |
postgres_1  | 2021-06-07 14:21:53.944 UTC [43] LOG:  statement: COMMIT;
postgres_1  | 2021-06-07 14:21:53.949 UTC [43] LOG:  statement: BEGIN ISOLATION LEVEL READ COMMITTED;
postgres_1  | 2021-06-07 14:21:53.954 UTC [43] LOG:  execute __asyncpg_stmt_b__: INSERT INTO a (data) VALUES ($1::varchar) RETURNING a.id
postgres_1  | 2021-06-07 14:21:53.954 UTC [43] DETAIL:  parameters: $1 = 'a'
postgres_1  | 2021-06-07 14:21:53.959 UTC [43] LOG:  statement: COMMIT;
postgres_1  | 2021-06-07 14:21:53.967 UTC [43] LOG:  statement: SAVEPOINT __asyncpg_savepoint_c__;
postgres_1  | 2021-06-07 14:21:53.967 UTC [43] ERROR:  SAVEPOINT can only be used in transaction blocks
postgres_1  | 2021-06-07 14:21:53.967 UTC [43] STATEMENT:  SAVEPOINT __asyncpg_savepoint_c__;
```

**Versions.**
 - OS: macOS 11.2.3 (20D91)
 - Python: 3.8.10
 - SQLAlchemy: 1.4.17
 - Database: postgres 13.2
 - DBAPI: asyncpg 0.23.0

**Comment by zzzeek** [comment]
"SAVEPOINT __asyncpg_savepoint_c__;" how strange, why is asyncpg doing that?

**Comment by zzzeek** [comment]
we don't use asyncpg's .execute() method.    So it looks like it's in fact the start of a transaction where this happens as asyncpg uses this internally when we call transaction.start().

**Comment by zzzeek** [comment]
this can't work with a fix because the "break" is blocking the context manager from receiving the exception:

```
    while True:  # Loop until we trigger a TimeoutError
        async with engine.begin() as conn:
            try:
                await conn.execute(insert(A), [{"data": "a"}])
            except asyncio.exceptions.TimeoutError:
                # such as, if you said conn.invalidate() here
                break
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add asyncio.TimeoutError as an exit exception** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2861

**Comment by zzzeek** [comment]
as you have some very specific situation on your end I will need you to please test the patch in the above review in your environment: https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~2861/revisions/1/patch?zip

**Comment by jamescobonkerr** [comment]
> as you have some very specific situation on your end I will need you to please test the patch in the above review in your environment: https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~2861/revisions/1/patch?zip

Hey Mike, thanks for the fast response. Your changes seem to resolve the issue in my minimal working example:

```
2021-06-07 17:09:52,376 INFO sqlalchemy.pool.impl.AsyncAdaptedQueuePool Invalidate connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x103d71ac0> (reason: TimeoutError:)
2021-06-07 17:09:52,376 DEBUG sqlalchemy.pool.impl.AsyncAdaptedQueuePool Closing connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x103d71ac0>
```

However, I'm still seeing the savepoint logs (as above) and a new error when running our service against your changes. I'll try to write another minimal working example to reproduce what I'm now seeing. In the meantime, this is the current stack trace:

```
 2021-06-07T16:55:15Z |   ERROR |                 grpc._cython.cygrpc |                  run: 390 | Unexpected [InterfaceError] raised by servicer method [/service.service/endpoint]
Traceback (most recent call last):
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 684, in _start_transaction
    await self._transaction.start()
  File "my-venv/lib/python3.8/site-packages/asyncpg/transaction.py", line 101, in start
    raise apg_errors.InterfaceError(
asyncpg.exceptions._base.InterfaceError: cannot use Connection.transaction() in a manually started transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 794, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 684, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 378, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 686, in _start_transaction
    self._handle_exception(error)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot use Connection.transaction() in a manually started transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 655, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 754, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 520, in _handle_unary_unary_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 377, in _finish_handler_with_unary_response
  File "my-venv/lib/python3.8/site-packages/grpc-helper/something.py", line 50, in wrapped
    return await f(*args, **kwargs)
  File "my-venv/lib/python3.8/site-packages/grpc-helper/something.py", line 74, in wrapped
    result = await f(*args, **kwargs)
  File "my-venv/lib/python3.8/site-packages/grpc-helper/something.py", line 31, in wrapped
    result = await f(*args, **kwargs)
  File "/Users/jamescobon-kerr/code/my-service/server/service.py", line 77, in LinkProblem
    await self._store.add(model)
  File "/Users/jamescobon-kerr/code/my-service/persistence/model.py", line 40, in add
    session.add(model)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 178, in __aexit__
    await self.gen.__anext__()
  File "/Users/jamescobon-kerr/code/my-service/persistence/model.py", line 36, in _new_session
    yield s
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in __aexit__
    await greenlet_spawn(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 120, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/util.py", line 219, in __exit__
    self.rollback()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/util.py", line 216, in __exit__
    self.commit()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3286, in flush
    self._flush(objects)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3426, in _flush
    transaction.rollback(_capture_exception=True)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3386, in _flush
    flush_context.execute()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 209, in save_obj
    for (
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 370, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1709, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 626, in connection
    return self._connection_for_bind(bind, execution_options)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 735, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 794, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 684, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 378, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 686, in _start_transaction
    self._handle_exception(error)
  File "my-venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot use Connection.transaction() in a manually started transaction
(Background on this error at: http://sqlalche.me/e/14/rvf5)
```

BTW could we also handle `asyncio.exceptions.CancelledError`? This is also causing pain from the same method in asyncpg.

Thanks again for your help.

**Comment by zzzeek** [comment]
i can add CancelledError, the "Savepoint" logs looks like normal operation of asyncpg but it just wouldn't be failing.

**Comment by zzzeek** [comment]
it's updated, if you can please test again

**Comment by jamescobonkerr** [comment]
> it's updated, if you can please test again

Hmm, I'm still seeing:

```
postgres_1  | 2021-06-07 16:55:00.284 UTC [196] LOG:  statement: SAVEPOINT __asyncpg_savepoint_b5__;
postgres_1  | 2021-06-07 16:55:00.284 UTC [196] ERROR:  SAVEPOINT can only be used in transaction blocks
postgres_1  | 2021-06-07 16:55:00.284 UTC [196] STATEMENT:  SAVEPOINT __asyncpg_savepoint_b5__;
```

in the db logs with the `asyncpg.exceptions._base.InterfaceError` error as above being raised. I think there's a bit more going on here as I don't think we should be entering into nested transaction blocks at all. I'm going to take a better look and get back to you.

**Comment by zzzeek** [comment]
the name __asyncpg_savepoint__ is being generated from asyncpg and I have a feeling that's something it's doing internally when it starts a transaction.

**Comment by jamescobonkerr** [comment]
Please ignore my last two comments — I was doing something wrong on my end. I am confident that we are now invalidating connections correctly, and I can no longer reproduce the `savepoint` logs/errors. From my perspective, these changes are good to go. Thanks again!

**Comment by zzzeek** [comment]
thanks for the fast turnaround!
