### ISSUE TITLE
TiDB specific comment causes reflection regex to fail

### ISSUE THREAD

**Issue by dveeden** [sqlalchemy/sqlalchemy#6659]
**Describe the bug**

On TiDB there is a `clustered_index` feature. This adds a `CLUSTERED`
keyword to the PK definition. This is in a TiDB specific comment.

However as the comment isn't followed by a space (` `) the regex
used by SQL Alchemy fails to decode this line.

```
INFO:sqlalchemy.engine.Engine:SHOW CREATE TABLE `t`
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('Table', 'Create Table')
DEBUG:sqlalchemy.engine.Engine:Row ('t', 'CREATE TABLE `t` (\n  `id` int(11) NOT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin')
INFO:root:LINE:   PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
/home/dvaneeden/dev/sqlalchemy_tidb/./sqlalchemy_tidb.py:26: SAWarning: Unknown schema content: '  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */'
  metadata.reflect(engine, only=['t'])
```

```
mysql> show create table t\G
*************************** 1. row ***************************
       Table: t
Create Table: CREATE TABLE `t` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.2.0-alpha-88-ged52601e6
Edition: Community
Git Commit Hash: ed52601e6eb560138db8cdccdfa1b5e2d33a11f0
Git Branch: master
UTC Build Time: 2021-06-16 13:03:48
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
#!/bin/env python3
#
# Based on https://docs.sqlalchemy.org/en/14/orm/extensions/automap.html
#
# TiDB details:
# create table t(id int primary key);
# on 5.7.25-TiDB-v5.2.0-alpha-88-ged52601e6
# (tiup playground nightly --tiflash 0 --monitor=false)
#
# pip freeze output:
# greenlet==1.1.0
# mysqlclient==2.0.3
# SQLAlchemy==1.4.18
#
# Python 3.9.5
import logging
from sqlalchemy import create_engine, MetaData
from sqlalchemy.ext.automap import automap_base

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)

engine = create_engine("mysql://root@127.0.0.1:4000/test")

metadata = MetaData()
metadata.reflect(engine, only=['t'])

Base = automap_base(metadata=metadata)
Base.prepare()

```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
(sqlalchemy_tidb) [dvaneeden@dve-carbon sqlalchemy_tidb]$ python -Werror sqlalchemy_tidb.py 
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('Variable_name', 'Value')
DEBUG:sqlalchemy.engine.Engine:Row ('sql_mode', 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION')
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00007s] ()
DEBUG:sqlalchemy.engine.Engine:Col ('Variable_name', 'Value')
DEBUG:sqlalchemy.engine.Engine:Row ('lower_case_table_names', '2')
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('DATABASE()',)
DEBUG:sqlalchemy.engine.Engine:Row ('test',)
INFO:sqlalchemy.engine.Engine:SHOW FULL TABLES FROM `test`
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('Tables_in_test', 'Table_type')
DEBUG:sqlalchemy.engine.Engine:Row ('t', 'BASE TABLE')
INFO:sqlalchemy.engine.Engine:SHOW CREATE TABLE `t`
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.engine.Engine:Col ('Table', 'Create Table')
DEBUG:sqlalchemy.engine.Engine:Row ('t', 'CREATE TABLE `t` (\n  `id` int(11) NOT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin')
Traceback (most recent call last):
  File "/home/dvaneeden/dev/sqlalchemy_tidb/sqlalchemy_tidb.py", line 26, in <module>
    metadata.reflect(engine, only=['t'])
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4710, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/sql/schema.py", line 600, in __new__
    metadata._remove_table(name, schema)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/sql/schema.py", line 595, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/sql/schema.py", line 670, in _init
    self._autoload(
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/sql/schema.py", line 705, in _autoload
    conn_insp.reflect_table(
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 757, in reflect_table
    tbl_opts = self.get_table_options(
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 398, in get_table_options
    return self.dialect.get_table_options(
  File "<string>", line 2, in get_table_options
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2995, in get_table_options
    parsed_state = self._parsed_state_or_create(
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 3244, in _parsed_state_or_create
    return self._setup_parser(
  File "<string>", line 2, in _setup_parser
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 3280, in _setup_parser
    return parser.parse(sql, charset)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/dialects/mysql/reflection.py", line 62, in parse
    util.warn("Unknown schema content: %r" % line)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1636, in warn
    _warnings_warn(msg, exc.SAWarning)
  File "/home/dvaneeden/sqlalchemy_tidb/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1673, in _warnings_warn
    warnings.warn(message, category, stacklevel=stacklevel + 1)
sqlalchemy.exc.SAWarning: Unknown schema content: '  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */'

```

**Versions.**
 - OS: Fedora 34
 - Python: 3.9.5
 - SQLAlchemy: 1.4.8
 - Database: TiDB. Tested with v5.2.0 (nightly build) but happens on any 5.x version
 - DBAPI: mysqlcient 2.0.3

**Comment by zzzeek** [comment]
hey there -

I've never heard of TiDB.  it looks like TiDB claims "MySQL compatibility" but in this case it would appear that's not the case.  TiDB is not part of our current support and I would prefer if a third party could create a [third party dialect](https://docs.sqlalchemy.org/en/14/dialects/index.html#external-dialects) to support the idiosyncrasies of this database, not unlike [sqlalchemy-redshift](https://pypi.org/project/sqlalchemy-redshift/) does so for Amazon's variant of PostgreSQL.

**Comment by zzzeek** [comment]
it looks like you are working on a PR, so I'll take a look and if it's nothing intrusive we can see if this can be added, but it has to include tests for the regex directly somehwere around [here](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/mysql/test_reflection.py#L1121)

**Comment by dveeden** [comment]
> hey there -
> 
> I've never heard of TiDB. it looks like TiDB claims "MySQL compatibility" but in this case it would appear that's not the case. TiDB is not part of our current support and I would prefer if a third party could create a [third party dialect](https://docs.sqlalchemy.org/en/14/dialects/index.html#external-dialects) to support the idiosyncrasies of this database, not unlike [sqlalchemy-redshift](https://pypi.org/project/sqlalchemy-redshift/) does so for Amazon's variant of PostgreSQL.

If you want to see how TiDB works you can use https://tiup.io to setup a local test cluster (aka playground). Another option is to download the `tidb-server` binary and run it. That won't give you a full cluster, but allows the full functionality when it comes to SQL.

Something like this:
```
curl -s https://tiup-mirrors.pingcap.com/tidb-v5.0.1-linux-amd64.tar.gz | tar zxvf -
./tidb-server &
mysql -h 127.0.0.1 -P 4000 -u root --comments
```

And if there is anything really TiDB specific (like https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence ) we could create a third-party dialect for that. But I don't think this change needs that.

**Comment by sqla-tester** [comment]
**Daniël van Eeden** has proposed a fix for this issue in the **master** branch:

**mysql reflection: Fix TiDB clustered PK comment compatibility** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2888
