### ISSUE TITLE
Cannot override operators with custom Comparator on UserDefinedTypes

### ISSUE THREAD

**Issue by r-bar** [sqlalchemy/sqlalchemy#6669]
**Describe the bug**

When implementing a custom `Comparator` on a `UserDefinedType` defined methods fail to override the base implementations. Meanwhile operator methods with novel names work as expected.

**To Reproduce**

The following short script attempts to create a basic custom type class and define a `__contains__` operator for it.

This script is complete and should run as is. Requires python >3.7 and sqlalchemy 1.4.
```py
import traceback

import sqlalchemy as sa
from sqlalchemy import types
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import type_api


class Cube(types.UserDefinedType):
    """Basic custom type"""

    def get_col_spec(self, **kw):
        return "CUBE"

    def bind_processor(self, dialect):
        return lambda value: value

    def result_processor(self, dialect, coltype):
        return lambda value: value

    class Comparator(type_api.TypeEngine.Comparator):
        def __contains__(self, other):
            return self.op("@>", is_comparison=True)(other)

        def contains(self, other):
            return self.op("@>", is_comparison=True)(other)

        def foo(self, other):
            return self.op("@>", is_comparison=True)(other)

    comparator_factory = Comparator


class Place(declarative_base()):
    """A sample orm model"""
    __tablename__ = "places"
    id = sa.Column(sa.Integer, primary_key=True)
    # the column with the custom type
    location = sa.Column(Cube)


# test the custom operators

print(".contains")
try:
    print(f"    {Place.location.contains('other')}")
except Exception as exc:
    traceback.print_exc()
    # inspecting the comparison method reveals it is still defined by
    # ColumnOperators.contains
    print(f"    {Place.location.contains!r}")


print("\n.__contains__()")
try:
    print(f"    {'other' in Place.location}")
except Exception as exc:
    traceback.print_exc()
    # inspecting the comparison method reveals it is still defined by
    # ColumnOperators.__contains__
    print(f"    {Place.location.__contains__!r}")


# operators that are not already defined on the TypeEngine.Comparator class
# appear to work as expected, rendering the custom operator
print("\n.foo()")
print(f"    {Place.location.foo('other')}")
# inspection reveals foo belongs to Cube.Comparator as expected
print(f"    {Place.location.foo!r}")
```

**Error**
(and full output of the above program)
```
.contains
Traceback (most recent call last):
  File "/home/ryan/src/endpointclosing/solex-order-service/sscce.py", line 46, in <module>
    print(f"    {Place.location.contains('other')}")
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 946, in contains
    return self.operate(contains_op, other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 316, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1469, in contains_op
    return _escaped_like_impl(a.contains, b, escape, autoescape)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1436, in _escaped_like_impl
    return fn(other, escape=escape)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 946, in contains
    return self.operate(contains_op, other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/orm/properties.py", line 424, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1469, in contains_op
    return _escaped_like_impl(a.contains, b, escape, autoescape)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1436, in _escaped_like_impl
    return fn(other, escape=escape)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 946, in contains
    return self.operate(contains_op, other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 841, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1469, in contains_op
    return _escaped_like_impl(a.contains, b, escape, autoescape)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 1436, in _escaped_like_impl
    return fn(other, escape=escape)
TypeError: contains() got an unexpected keyword argument 'escape'
    <bound method ColumnOperators.contains of <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f1b820bcb30>>

.__contains__()
Traceback (most recent call last):
  File "/home/ryan/src/endpointclosing/solex-order-service/sscce.py", line 57, in <module>
    print(f"    {'other' in Place.location}")
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 425, in __contains__
    return self.operate(contains, other)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 316, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 425, in __contains__
    return self.operate(contains, other)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/orm/properties.py", line 424, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 425, in __contains__
    return self.operate(contains, other)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 841, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/ryan/src/endpointclosing/solex-order-service/.direnv/python-3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 3714, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
    <bound method ColumnOperators.__contains__ of <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f1b820bcb30>>

.foo()
    places.location @> :location_1
    <bound method Cube.Comparator.foo of <__main__.Cube.Comparator object at 0x7f1b820bae80>>
```

**Versions.**
 - OS: Linux
 - Python: CPython 3.9.5
 - SQLAlchemy: 1.4.18
 - Database: Any
 - DBAPI: N/A

**Additional context**

**Thank you for your work on SQLAlchemy!**

**Comment by zzzeek** [comment]
hey there -

the first error you're getting is that the contains() method on the Comparator class expects a keyword argument called "escape".  change your comparator as follows and it works:

```python
    class Comparator(type_api.TypeEngine.Comparator):
        def contains(self, other, **kw):
            return self.op("@>", is_comparison=True)(other)
```

the second exception is due to the fact that SQLAlchemy does not support overriding the Python "in" operator as a SQL expression, due to the mechanics of Python.  Python's own "contains()" function wants to evaluate the end product as a boolean, so we don't support overriding `__contains__()`.  The reason the comparator base class includes this is to catch users trying to use it for things with ARRAY objects where we raise an exception.

**Comment by zzzeek** [comment]
the docstring for contains is https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnElement.contains so changing this to use question
