### ISSUE TITLE
Error when using tablesample with floats

### ISSUE THREAD

**Issue by luhn** [sqlalchemy/sqlalchemy#6733]
Attempting to run the following code:

```python
from sqlalchemy import (Column, Integer, String, create_engine, select,
                        tablesample)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)


if __name__ == '__main__':
    engine = create_engine('postgresql:///test', echo=True)
    Base.metadata.create_all(engine)
    db = Session(bind=engine, autoflush=False)
    sampled = tablesample(User, 0.1)
    db.execute(select(sampled.c.id))
```

Gives the following output:

```
2021-07-07 18:13:55,996 INFO sqlalchemy.engine.Engine select version()
2021-07-07 18:13:55,996 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-07 18:13:55,996 INFO sqlalchemy.engine.Engine select current_schema()
2021-07-07 18:13:55,996 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-07 18:13:55,997 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2021-07-07 18:13:55,997 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-07 18:13:55,997 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-07-07 18:13:55,997 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2021-07-07 18:13:55,997 INFO sqlalchemy.engine.Engine [generated in 0.00006s] {'name': 'user'}
2021-07-07 18:13:55,998 INFO sqlalchemy.engine.Engine COMMIT
2021-07-07 18:13:55,999 INFO sqlalchemy.engine.Engine BEGIN (implicit)
Traceback (most recent call last):
  File "/Users/luhn/Code/revenue/bug.py", line 21, in <module>
    db.execute(select(sampled.c.id))
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1443, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 501, in _compile_w_cache
    elem_cache_key = self._generate_cache_key()
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1189, in oneshot
    result = fn(self, *args, **kw)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 272, in _generate_cache_key
    return HasCacheKey._generate_cache_key(self)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 251, in _generate_cache_key
    key = self._gen_cache_key(_anon_map, bindparams)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 203, in _gen_cache_key
    [
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 204, in <listcomp>
    elem._gen_cache_key(anon_map, bindparams)
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 168, in _gen_cache_key
    obj._gen_cache_key(anon_map, bindparams),
  File "/Users/luhn/.pyenv/versions/revenue/lib/python3.9/site-packages/sqlalchemy/sql/traversals.py", line 168, in _gen_cache_key
    obj._gen_cache_key(anon_map, bindparams),
AttributeError: 'float' object has no attribute '_gen_cache_key'
```

This was introduced in 1.4, 1.3 works as expected.

Explicitly using a sample function, e.g. `tablesample(User, func.system(0.1))`, works fine.

**Comment by zzzeek** [comment]
the second argument has to be a SQL function, ".1" is not acceptable.   

what is the SQL you are looking to emit?
