### ISSUE TITLE
schema_translate_map ignored when using Enum with ARRAY

### ISSUE THREAD

**Issue by marodere** [sqlalchemy/sqlalchemy#6739]
While an ``Enum`` type being correctly created with the schema specified, it's impossible to use the type as an ``ARRAY`` element type. A ``CREATE TABLE`` and a subsequent ``CAST`` clauses generated will lack of schema for the ``Enum``.

**To Reproduce**
```py
from sqlalchemy import create_engine, Table, Column, Integer, MetaData, ARRAY, Enum

metadata = MetaData()

t = Table(
    "test_table",  
    metadata,
    Column("id", Integer, primary_key=True),
    Column("value", ARRAY(Enum("one", "two", "three", name="an_enum"))),
)

engine = create_engine('postgresql+psycopg2://...', echo=True)
conn = engine.connect().execution_options(
        schema_translate_map={None: "test_schema"}
)

metadata.create_all(conn)
conn.execute(t.insert(), [{"value": ["one"]}, {"value": ["two", "three"]}])
metadata.drop_all(conn)
```

**Error**
```
2021-07-09 00:50:40,999 INFO sqlalchemy.engine.Engine select version()
2021-07-09 00:50:41,000 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-09 00:50:41,041 INFO sqlalchemy.engine.Engine select current_schema()
2021-07-09 00:50:41,041 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-09 00:50:41,084 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2021-07-09 00:50:41,084 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-07-09 00:50:41,128 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname=%(schema)s and relname=%(name)s
2021-07-09 00:50:41,128 INFO sqlalchemy.engine.Engine [generated in 0.00082s] {'schema': 'test_schema', 'name': 'test_table'}
2021-07-09 00:50:41,171 INFO sqlalchemy.engine.Engine 
            SELECT EXISTS (
                SELECT * FROM pg_catalog.pg_type t, pg_catalog.pg_namespace n
                WHERE t.typnamespace = n.oid
                AND t.typname = %(typname)s
                AND n.nspname = %(nspname)s
                )
                
2021-07-09 00:50:41,171 INFO sqlalchemy.engine.Engine [generated in 0.00041s] {'typname': 'an_enum', 'nspname': 'test_schema'}
2021-07-09 00:50:41,193 INFO sqlalchemy.engine.Engine 
CREATE TABLE test_schema.test_table (
	id SERIAL NOT NULL, 
	value an_enum[], 
	PRIMARY KEY (id)
)


2021-07-09 00:50:41,193 INFO sqlalchemy.engine.Engine [no key 0.00016s] {}
2021-07-09 00:50:41,221 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: type "an_enum[]" does not exist
LINE 4:  value an_enum[], 
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tolich/Dev/sqlalchemy/lib/mvp.py", line 17, in <module>
    metadata.create_all(conn)
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 4740, in create_all
    bind._run_ddl_visitor(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2082, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 520, in traverse_single
    return meth(obj, **kw)
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 846, in visit_metadata
    self.traverse_single(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 520, in traverse_single
    return meth(obj, **kw)
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 890, in visit_table
    self.connection.execute(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1353, in _execute_ddl
    ret = self._execute_context(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "an_enum[]" does not exist
LINE 4:  value an_enum[], 
               ^

[SQL: 
CREATE TABLE test_schema.test_table (
	id SERIAL NOT NULL, 
	value an_enum[], 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Linux Ubuntu 21.04
 - Python: 3.9.5
 - SQLAlchemy: 1.4.x
 - Database: postgresql
 - DBAPI: psycopg2

**Additional context**
The first issue with a ``CREATE TABLE`` statement looks pretty easy to fix:
```diff
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -2866,9 +2866,7 @@ class PGTypeCompiler(compiler.GenericTypeCompiler):
         return "BYTEA"
 
     def visit_ARRAY(self, type_, **kw):
-
-        # TODO: pass **kw?
-        inner = self.process(type_.item_type)
+        inner = self.process(type_.item_type, **kw)
         return re.sub(
             r"((?: COLLATE.*)?)$",
             (
```
But then the program will fail on a subsequent ``INSERT`` call, with very similar symptoms.
```
Traceback (most recent call last):
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1751, in _execute_context
    self.dialect.do_executemany(
  File "/home/tolich/Dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/psycopg2.py", line 962, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 1292, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedObject: type "an_enum[]" does not exist
LINE 1: ...t_schema.test_table (value) VALUES (ARRAY['one']::an_enum[])...
                                                             ^
```

Here my expertise is over, I haven't discovered how/where to fix it.

Thank you for your attention!

**Comment by zzzeek** [comment]
here's a patch that includes part of a test

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/base.py b/lib/sqlalchemy/dialects/postgresql/base.py
index ea2eda902f..123e6f0fa8 100644
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -2820,7 +2820,6 @@ class PGTypeCompiler(compiler.GenericTypeCompiler):
     def visit_ENUM(self, type_, identifier_preparer=None, **kw):
         if identifier_preparer is None:
             identifier_preparer = self.dialect.identifier_preparer
-
         return identifier_preparer.format_type(type_)
 
     def visit_TIMESTAMP(self, type_, **kw):
@@ -2867,8 +2866,7 @@ class PGTypeCompiler(compiler.GenericTypeCompiler):
 
     def visit_ARRAY(self, type_, **kw):
 
-        # TODO: pass **kw?
-        inner = self.process(type_.item_type)
+        inner = self.process(type_.item_type, **kw)
         return re.sub(
             r"((?: COLLATE.*)?)$",
             (
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 4b3b2c293c..6851a920b8 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1497,6 +1497,7 @@ class SQLCompiler(Compiled):
 
     def visit_typeclause(self, typeclause, **kw):
         kw["type_expression"] = typeclause
+        kw["identifier_preparer"] = self.preparer
         return self.dialect.type_compiler.process(typeclause.type, **kw)
 
     def post_process_text(self, text):
@@ -4717,7 +4718,6 @@ class IdentifierPreparer(object):
     def _with_schema_translate(self, schema_translate_map):
         prep = self.__class__.__new__(self.__class__)
         prep.__dict__.update(self.__dict__)
-
         def symbol_getter(obj):
             name = obj.schema
             if name in schema_translate_map and obj._use_schema_map:
diff --git a/test/dialect/postgresql/test_compiler.py b/test/dialect/postgresql/test_compiler.py
index e48de9d21d..e50dcaa41c 100644
--- a/test/dialect/postgresql/test_compiler.py
+++ b/test/dialect/postgresql/test_compiler.py
@@ -249,6 +249,30 @@ class CompileTest(fixtures.TestBase, AssertsCompiledSQL):
             "'y', 'z')))",
         )
 
+    def test_cast_enum_schema(self):
+        e1 = Enum("x", "y", "z", name="somename")
+        e2 = Enum("x", "y", "z", name="somename", schema="someschema")
+
+        stmt = select(cast(column("foo"), e1), cast(column("bar"), e2))
+        self.assert_compile(
+            stmt,
+            "SELECT CAST(foo AS somename) AS foo, CAST(bar AS someschema.somename) AS bar",
+        )
+
+    def test_cast_enum_schema_translate(self):
+        e1 = Enum("x", "y", "z", name="somename")
+        e2 = Enum("x", "y", "z", name="somename", schema="someschema")
+        schema_translate_map = {None: "bat", "someschema": "hoho"}
+
+        stmt = select(cast(column("foo"), e1), cast(column("bar"), e2))
+        self.assert_compile(
+            stmt,
+            "SELECT CAST(foo AS bat.somename) AS foo, "
+            "CAST(bar AS hoho.somename) AS bar",
+            schema_translate_map=schema_translate_map,
+            render_schema_translate=True
+        )
+
     def test_create_type_schema_translate(self):
         e1 = Enum("x", "y", "z", name="somename")
         e2 = Enum("x", "y", "z", name="somename", schema="someschema")
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**repair schema_translate_map for schema type use cases** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2955
