### ISSUE TITLE
KeyError on engine.dispose() in __del__

### ISSUE THREAD

**Issue by relsunkaev** [sqlalchemy/sqlalchemy#6740]
**Describe the bug**
When trying to dispose of engine in an object's __del__ function, a KeyError is raised.

**To Reproduce**

```py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker


class Database:

    def __init__(self):
        self._engine = create_engine('sqlite://')

    def __del__(self):
        self._engine.dispose()


db = Database()
```

**Error**

```
Exception ignored in: <function Database.__del__ at 0x10ce0d790>
Traceback (most recent call last):
  File "/Users/user/bug_example.py", line 11, in __del__
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2921, in dispose
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/user/pool/impl.py", line 318, in recreate
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 310, in __init__
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 194, in __init__
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 155, in _update
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 414, in _update
  File "/Users/user/.local/share/virtualenvs/calculation-service-5Hyvx6By/lib/python3.8/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: <weakref at 0x10c5e2360; to 'function' at 0x10ce68820 (go)>
```

**Versions.**
 - OS: macOS 11.4
 - Python: 3.8.10
 - SQLAlchemy: 1.4.20
 - Database: Any
 - DBAPI: Any

**Additional context**
The function in the KeyError fluctuates between `go` and `on_connect`

**Have a nice day!**

**Comment by zzzeek** [comment]
I would advise against using `__del__` for anything in Python, this kind of problem is typically unavoidable as it is called at random phases within garbage collection, and the state objects is not deterministic.  [weakref callbacks should be preferred](https://stackoverflow.com/questions/43758886/can-weakref-callbacks-replace-del).   I could fix this particular KeyError (which BTW is ignored because this is only GC where such errors are expected) then someone will do something else in a `__del__` that also has some kind of problem.   

the best I could do here is add some flag to dispose() like "recreate=False", it's not worth trying to make pool recreation work inside of a `__del__` method.   You can likely dispose the pool directly here like this:

```
def __del__(self):
    engine.pool.dispose()
```

**Comment by zzzeek** [comment]
that's actually an amazing MCVE you made there, nice job coming up with that I know those are hard.

I'll add a guard strongref here for this particular issue as it is logic dealing with weakrefs.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**guard against unexpected weakref cleanups** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2967
