### ISSUE TITLE
Recurring Exception of size-change during iteration

### ISSUE THREAD

**Issue by dwt** [sqlalchemy/sqlalchemy#6771]
**Describe the bug**
My test suite regularly (but not always) fails because of `RuntimeError: dictionary changed size during iteration` errors.

The full exception is:
```
Traceback (most recent call last):
  File "/home/jenkins-slave/workspace/yeepa-pipeline/yeepa/backend/models/tests/translatable_test.py", line 259, in test_should_know_if_they_are_incomplete
    translation_for = self.TranslatableParent(translatable='foo')
  File "<string>", line 4, in __init__
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3569, in _event_on_init
    instrumenting_mapper._check_configure()
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3400, in _do_configure_registries
    for mapper in reg._mappers_to_configure():
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/decl_api.py", line 626, in <genexpr>
    manager.mapper
  File "/usr/lib64/python2.7/weakref.py", line 327, in iterkeys
    for wr in self.data.iterkeys():
RuntimeError: dictionary changed size during iteration
``` 

The test in question always (as far as I can tell) runs fine if run in isolation. I strongly suspect that the real culprit is another test where I trigger some threaded behaviour that I suspect is not cleaned up properly. However I haven't been able to reduce the problem, i.e. I can only make it happen when running the full test and ac yest suite on our ci server.

**This is the test I suspect**
```py
import threading
import time

import transaction
import sqlalchemy as sa

from yeepa.backend.models.meta import DBSession

from pyexpect import expect

from yeepa.backend.testing.mariadb_testcase import MariaDBTestCase

from .. import meta

class TransactionRetryWithExponentialBackoffTest(MariaDBTestCase):
    """
    Using separate tables as this test needs to commit to drop locks, which would otherwise destroy test isolation.
    """
    LOCK_WAIT_TIMEOUT = 10  # innodb_lock_wait_timeout defaults to 50
    
    def setUp(self):
        self.super()
        self._setup_local_metadata()
        
        from sqlalchemy import Column, Integer
        # Hidden in method so the venusian scanner doesn't find it
        class BlockingTable(self.Base):
            __tablename__ = 'BlockingTable'
            id = Column(Integer, primary_key=True)
            value = Column(Integer)
        
        class UnrelatedTable(self.Base):
            __tablename__ = 'UnrelatedTable'
            id = Column(Integer, primary_key=True)
        self.UnrelatedTable = UnrelatedTable
        self.metadata.create_all()
        
        self.set_reduced_lock_timeout()
        # Aquire lock
        # does this aquire a table or row level lock?
        # I'm guessing a table level lock since we are not using an index
        BlockingTable(value=3).save()
    
    def set_reduced_lock_timeout(self):
        # Enusure we are not waiting longer than neccessary
        DBSession.execute('SET SESSION innodb_lock_wait_timeout = :lock_timeout', dict(lock_timeout=self.LOCK_WAIT_TIMEOUT))
    
    def run_thread(self, a_method):
        did_finish_starting = threading.Event()
        
        def thread_starting_wrapper():
            self.set_reduced_lock_timeout()
            did_finish_starting.set()
            a_method()
            # ensure changes in thread become visible in main thread
            transaction.commit()
            # forwarded to thread local session to prevent it lingering afte the thread is closed
            DBSession.remove()
        
        thread = threading.Thread(name=str(a_method), target=thread_starting_wrapper)
        thread.start()
        did_finish_starting.wait()
        
        time.sleep(self.LOCK_WAIT_TIMEOUT * 1.5)
        transaction.commit() # drop locks
        thread.join()
        
        # I'm seeing ocasional 
        # RuntimeError: dictionary changed size during iteration
        # Emanating from inside of SQLAlchemy, which I suspect are created by the garbage collector
        # claiming mappers and other stuff created inside these threads
        # Trying to workaround that by explicityl invoking the collector in teardown
        # should be unneccessary after the session is removed - but...
        import gc
        self.addCleanup(gc.collect)
    
    def acquire_row_lock(self):
        # This fails to aquire a read lock since .. I guess the whole table is locked
        DBSession.execute('SELECT * FROM BlockingTable WHERE value=3 LOCK IN SHARE MODE')
        # This would aquire a write lock - not needed, the above already blocks
        # DBSession.execute('SELECT * FROM BlockingTable WHERE value=3 FOR UPDATE')
    
    # Tests ..............................................................................
    
    def test_can_retry_query_that_timeouts(self):
        self.run_count = 0
        @meta.retry_on_deadlock_with_exponential_backoff
        def blocked():
            self.run_count += 1
            self.acquire_row_lock()
        
        self.run_thread(blocked)
        expect(self.run_count) == 2
    
    def test_should_undo_changes_to_unrelated_tables_when_retrying(self):
        @meta.retry_on_deadlock_with_exponential_backoff
        def blocked():
            self.UnrelatedTable().save()
            self.acquire_row_lock()
        
        expect(lambda: self.run_thread(blocked)).to_change(
            self.UnrelatedTable.query.count, by=1
        )
    
    def test_should_log_when_retrying(self):
        @meta.retry_on_deadlock_with_exponential_backoff
        def blocked():
            self.acquire_row_lock()
        
        from testfixtures import LogCapture
        with LogCapture() as captured:
            self.run_thread(blocked)
            from testfixtures import StringComparison as S
            captured.check_present(
                ('root', 'WARNING', S(r'(?ms)^Caught deadlock or timeout\. Retrying in'))
            )
```

**Error**
```
Stacktrace
Traceback (most recent call last):
  File "/home/jenkins-slave/workspace/yeepa-pipeline/yeepa/backend/models/tests/translatable_test.py", line 259, in test_should_know_if_they_are_incomplete
    translation_for = self.TranslatableParent(translatable='foo')
  File "<string>", line 4, in __init__
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3569, in _event_on_init
    instrumenting_mapper._check_configure()
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3400, in _do_configure_registries
    for mapper in reg._mappers_to_configure():
  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/decl_api.py", line 626, in <genexpr>
    manager.mapper
  File "/usr/lib64/python2.7/weakref.py", line 327, in iterkeys
    for wr in self.data.iterkeys():
RuntimeError: dictionary changed size during iteration
Standard Ausgabe (STDOUT)
nose2.loader: DEBUG: loadTestsFromName yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete/None
nose2.plugins.loader.discovery: DEBUG: _find_tests('yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete', '/home/jenkins-slave/workspace/yeepa-pipeline/yeepa')
nose2.plugins.loader.testcases: DEBUG: load yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete from None
txn.140187873515328: DEBUG: new transaction
nose2.plugins.mp: DEBUG: Received results for yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete
nose2.plugins.mp: DEBUG: Received startTest(StartTestEvent(handled=False, test='yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete', result=None, startTime=1626270686.483036))
nose2.plugins.mp: DEBUG: Received setTestOutcome(TestOutcomeEvent(handled=False, test='yeepa.backend.models.tests.translatable_test.TranslationForDecoratorTest.test_should_know_if_they_are_incomplete', result=None, outcome='error', exc_info=(<type 'exceptions.RuntimeError'>, RuntimeError('dictionary changed size during iteration',), 'Traceback (most recent call last):\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/yeepa/backend/models/tests/translatable_test.py", line 259, in test_should_know_if_they_are_incomplete\n    translation_for = self.TranslatableParent(translatable=\'foo\')\n  File "<string>", line 4, in __init__\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _initialize_instance\n    manager.dispatch.init(self, args, kwargs)\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 343, in __call__\n    fn(*args, **kw)\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3569, in _event_on_init\n    instrumenting_mapper._check_configure()\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1873, in _check_configure\n    _configure_registries({self.registry}, cascade=True)\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3384, in _configure_registries\n    _do_configure_registries(registries, cascade)\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3400, in _do_configure_registries\n    for mapper in reg._mappers_to_configure():\n  File "/home/jenkins-slave/workspace/yeepa-pipeline/venv/lib/python2.7/site-packages/sqlalchemy/orm/decl_api.py", line 626, in <genexpr>\n    manager.mapper\n  File "/usr/lib64/python2.7/weakref.py", line 327, in iterkeys\n    for wr in self.data.iterkeys():\nRuntimeError: dictionary changed size during iteration\n'), reason=None, expected=False, shortLabel=None, longLabel=None))
```

**Versions.**
 - OS: CentOs 7
 - Python: 2.7.5
 - SQLAlchemy: 1.4.21
 - Database: mysqld 10.2.39-MariaDB
 - DBAPI: PyMySQL  0.10.1

**Additional context**
The original problem I was trying to solve is that I have some background workers that need to try saving something in a database that might be deadlocked for writing at some point. The exponential backoff is meant to work around that, as that writing is not time critical. I guess I'm not cleaning up correctly after using SQLA from a thread in that test.

Is that a likely explanation for the behaviour I'm seeing? If so, where can I find more info on how to correctly tear down SqlA after such threaded usage? I did find only a passing mention of `Session.close()` - but that's not much to go by. There are also some closed bug reports - but nothing that seemed applicable.

**Comment by zzzeek** [comment]
this is a common problem with weak-referencing dictionaries.  we will fix by adapting the collection to a list() first, then processing.

**Comment by zzzeek** [comment]
I have no way to confirm the fix on this end.  this is the patch I will merge, if you can see if this resovles your issue it would be helpful.

```diff
diff --git a/lib/sqlalchemy/orm/decl_api.py b/lib/sqlalchemy/orm/decl_api.py
index 54e927ee47..23b89a5434 100644
--- a/lib/sqlalchemy/orm/decl_api.py
+++ b/lib/sqlalchemy/orm/decl_api.py
@@ -624,14 +624,14 @@ class registry(object):
         return itertools.chain(
             (
                 manager.mapper
-                for manager in self._managers
+                for manager in list(self._managers)
                 if manager.is_mapped
                 and not manager.mapper.configured
                 and manager.mapper._ready_for_configure
             ),
             (
                 npm
-                for npm in self._non_primary_mappers
+                for npm in list(self._non_primary_mappers)
                 if not npm.configured and npm._ready_for_configure
             ),
         )
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**apply list() around weakkeydictionary iteration** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2963

**Comment by zzzeek** [comment]
committed what I can, if you have time to confirm it helps your behavior that would help.

**Comment by dwt** [comment]
I'll put that into my test harness and report back with my findings.

Thanks a lot!
