### ISSUE TITLE
`FlushError` after unexpected cache hit after `bulk_save_objects`

### ISSUE THREAD

**Issue by Alexxxir** [sqlalchemy/sqlalchemy#6793]
**Describe the bug**
When I use `bulk_save_objects` it caches the `INSERT` query without `RETURNING`.
If after that I use `session.add` and` session.flush` it fetches that cache request but expects a request with `RETURNING` so we get` FlushError`.

**To Reproduce**

```py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import Session

Base = declarative_base()


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)


engine = create_engine("postgresql://postgres:postgres@localhost/postgres", echo=True)

Base.metadata.create_all(engine)

session = Session(bind=engine)

session.bulk_save_objects([User(name="A"), User(name="B")])
# 2021-07-21 11:30:13,342 INFO sqlalchemy.engine.Engine INSERT INTO "user" (name) VALUES (%(name)s)
# 2021-07-21 11:30:13,342 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ({'name': 'A'}, {'name': 'B'})


session.add(User(name="C"))
session.add(User(name="D"))
session.flush()
# 2021-07-21 11:30:13,351 INFO sqlalchemy.engine.Engine INSERT INTO "user" (name) VALUES (%(name)s)
# 2021-07-21 11:30:13,351 INFO sqlalchemy.engine.Engine [cached since 0.009323s ago] ({'name': 'C'}, {'name': 'D'})
# 2021-07-21 11:30:13,354 INFO sqlalchemy.engine.Engine ROLLBACK

```

**Error**
```
Traceback (most recent call last):
  File ".../bug.py", line 26, in <module>
    session.flush()
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3404, in _flush
    flush_context.finalize_flush_changes()
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 477, in finalize_flush_changes
    self.session._register_persistent(other)
  File ".../venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2465, in _register_persistent
    raise exc.FlushError(
sqlalchemy.orm.exc.FlushError: Instance <User at 0x7fd79161bd60> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.

```

**Versions.**
 - OS: Ubuntu, MacOS
 - Python: 3.9
 - SQLAlchemy: 1.4.21
 - Database: PostgreSQL
 - DBAPI: psycopg2

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**implement cache key for return_defaults token** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2970

**Comment by zzzeek** [comment]
thanks for reporting, I hope to release today.
