### ISSUE TITLE
ShardedSession不能执行原生sql语句

### ISSUE THREAD

**Issue by Fire-Dragons** [sqlalchemy/sqlalchemy#6816]
**Describe the bug**
ShardSession使用execute执行原生sql语句报错

**To Reproduce**

```py
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Integer, Text
from sqlalchemy import ForeignKey, Sequence, MetaData, Table
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.horizontal_shard import ShardedSession, ShardedQuery
import os

host = 'localhost'
port = '3306'
user = 'root'
pwd = '545733'
db = 'identity_test'

# 初始化数据库链接
engine = create_engine('mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(user, pwd, host, port, db), pool_recycle=600, encoding='utf-8', pool_pre_ping=True)
# 创建对象的基类
Base = declarative_base()
md = MetaData(bind=engine)  # 引用MetaData


class User(Base):
    # 表的名字
    __table__ = Table("user", md, autoload=True)  # 自动加载表结构


Session = sessionmaker(twophase=True, class_=ShardedSession)
shards = {'test': engine}

def shard_chooser(mapper, instance, clause=None, **kw):
    """"""
    return 'test'

def id_chooser(query, identity):
    """"""
    return ['test']

def execute_chooser(orm_context):
    """"""
    return ['test']

Session.configure(shards=shards, shard_chooser=shard_chooser, id_chooser=id_chooser,
                        execute_chooser=execute_chooser, query_cls=ShardedQuery)
session = Session()

session.execute('select * from user')
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = fn(orm_exec_state)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.8/site-packages/sqlalchemy/ext/horizontal_shard.py", line 216, in execute_and_instances
    update_options = active_options = orm_context.update_delete_options
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 457, in update_delete_options
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This ORM execution is not against an UPDATE or DELETE statement so there are no update options
```

**Versions.**
 - OS:mac
 - Python:3.8.5
 - SQLAlchemy:1.4.19
 - Database:mysql
 - DBAPI:mysqlclient

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**accommodate plain core textual statements** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2982

**Comment by zzzeek** [comment]
thanks for reporting
