### ISSUE TITLE
Inabiliity to connect to CockroachDB via asyncpg

### ISSUE THREAD

**Issue by SoftwareSheriff** [sqlalchemy/sqlalchemy#6825]
### Describe the bug

Using SQLAlchemy to connect to CockroachDB via asyncpg fails because it's assumed that CockroachDB has a `json` type and it does not. Fixing that assumption then leads to assuming that it has a `jsonb` type, which it does, but appears to be broken (at least, via asyncpg) on versions older than v21.1.0, which results in the following exception with an otherwise identical stack trace: `asyncpg.exceptions._base.InterfaceError: cannot use custom codec on non-scalar type pg_catalog.jsonb`.

### To Reproduce

```python
#!/usr/bin/env python3

import asyncio
from sqlalchemy.ext.asyncio import create_async_engine


async def main():
    # Spin up cockroachdb via docker or something
    engine = create_async_engine("postgresql+asyncpg://root@localhost:26257")

    async with engine.begin() as conn:
        pass


if __name__ == "__main__":
    asyncio.run(main())
```

### Error

```
Traceback (most recent call last):
  File "./main.py", line 17, in <module>
    asyncio.run(main())
  File "/home/charles/.pyenv/versions/3.8.10/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/charles/.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./main.py", line 12, in main
    async with engine.begin() as conn:
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/base.py", line 57, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 516, in start
    await self.conn.start(is_ctxmanager=is_ctxmanager)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 106, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 622, in __connect
    pool.dispatch.connect.for_modify(
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 658, in on_connect
    do_on_connect(dbapi_connection)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1042, in connect
    conn.await_(_setup_type_codecs(conn))
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1026, in _setup_type_codecs
    await conn._connection.set_type_codec(
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/asyncpg/connection.py", line 1166, in set_type_codec
    typeinfo = await self._introspect_type(typename, schema)
  File "/home/charles/.pyenv/versions/msgset/lib/python3.8/site-packages/asyncpg/connection.py", line 467, in _introspect_type
    raise ValueError(
ValueError: unknown type: pg_catalog.json
```

### Versions

- OS: Arch Linux
- Python: 3.8.10
- SQLAlchemy: 1.4.22
- Database: CockroachDB
- DBAPI: asyncpg

**Comment by CaselIT** [comment]
Hi,

CockroachDB  has its own dialect https://github.com/cockroachdb/sqlalchemy-cockroachdb, connection is not supported via asyncpg.

cc @gordthompson

**Comment by SoftwareSheriff** [comment]
Hmm, it seems as though [`asyncpg` itself supports being used with CockroachDB](https://github.com/MagicStack/asyncpg/issues?q=is%3Aissue+cockroachdb), and it also doesn't appear that `sqlalchemy-cockroachdb` supports async at all, which is a requirement for what I'm doing.

**Comment by CaselIT** [comment]
I meant in the context of sqlalchemy. There are numerous db that use the a somewhat pg compatible format, and it would be nearly impossible to support them all with the same internal dialect. We don't test against any of those db so it would be impossible to guarantee that some change would break support.

My opinion is that it would be better to involve  the CockroachDB folks and/or to have a separate dialect for this, that can extend the internal asyncpg one with the appropriate modifications.

**Comment by SoftwareSheriff** [comment]
Ah I see, that seems reasonable to me. I suppose I'll hold off on closing this until we get more opinions, but I find the "lots of things to support, can't test them all, weird to maintain" points to be compelling.

**Comment by jvanasco** [comment]
Mike is on vacation, but I guarantee he will reject this for the reasons @CaselIT mentioned.  This essentially backdoors in first-party support for "yet another database", and Mike has been very adamant in limiting first-party support to a small number of databases and growing an ecosystem of third-party dialects that can support, maintain and test their own code.

The CockroachDB people should really be handling this.  If they need some changes/hooks to better support things, it could potentially be made in an abstract way that all third-party dialects could use.

**Comment by CaselIT** [comment]
>Ah I see, that seems reasonable to me. I suppose I'll hold off on closing this until we get more opinions, but I find the "lots of things to support, can't test them all, weird to maintain" points to be compelling.

Thanks for understanding. 

Sure we can keep this open until we have Mike and Gord opition. IIRC Gord was in contact with the CockroachDB people so it may ask their point of view on this also.

**Comment by gordthompson** [comment]
I agree that such a request should be directed toward the [sqlalchemy-cockroachdb](https://github.com/cockroachdb/sqlalchemy-cockroachdb) dialect. It currently only supports psycopg2. AFAIK there has been no discussion of supporting asyncpg. That might be because

1. there's something about CockroachDB's distributed architecture that makes async infeasible (or unnecessary?), or perhaps
2. nobody has asked.

**Comment by CaselIT** [comment]
> One thing that might impact SQLAlchemy is that I'm pretty sure the test suite (used by third-party dialects) does not have much (if any) coverage for async.

The test suite should work with the existing tests.
When using async dialects each test is wrapped in its own async context, so the classic suite should work also in 3rd party async dialects. 
I guess there may be some rough edges to fix thought, since I don't think there are external async dialects at the moment

**Comment by zzzeek** [comment]
this is a third party driver issue.
