### ISSUE TITLE
before_execute no longer allows modification of the statement

### ISSUE THREAD

**Issue by DanCardin** [sqlalchemy/sqlalchemy#6913]
### Describe the bug

Seems like previously the before_execute handling code actually used the statement part of the return value, whereas [now](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/base.py#L1382), it doesn't appear to make any use of that value.

So while it may be possible to mutate a statement, for immutable query types like strings (or even `text`, i would imagine one would have to mutate private internals), one can seemingly no longer alter the query

### To Reproduce

```python
from sqlalchemy import create_engine, event

engine = create_engine("sqlite://")


@event.listens_for(engine, "before_execute", retval=True)
def listen(conn, clauseelement, multiparams, params, execution_options=None):
    clauseelement = clauseelement + "wat"
    return clauseelement, multiparams, params


engine.execute("select 1")
```

### Error

In sqlalchemy 1.3: (Given the alteration, this is the error i would expect!)
```
﻿Traceback (most recent call last):
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: unrecognized token: "1wat"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "meow.py", line 12, in <module>
    engine.execute("select 1")
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    ret = self._execute_context(
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/Users/danc/work/schireson/pytest-mock-resources/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unrecognized token: "1wat"
[SQL: select 1wat]
```

In sqlalchemy 1.4, this returns without error (which given the alteration, i wouldn't expect!). If you plop a debugger on a theoretical `before_cursor_execute`, it executes the original query

### Versions

- SQLAlchemy: 1.3 vs 1.4

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**restore statement substitution to before_execute()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3013

**Comment by zzzeek** [comment]
the changeset that removed this in a1939719a652774a437f69f8d4788b3f08650089 looks pretty intentional but there's no mention of this being done.   I want to check old notes to see if i was thinking something here but I can't see at the moment why this was removed.
