### ISSUE TITLE
Mypy crashes when using query_expression

### ISSUE THREAD

**Issue by olzhasar** [sqlalchemy/sqlalchemy#6950]
### Describe the bug

Mypy crashes while analyzing module with query_expressions in it

### To Reproduce

```python
models/user.py code looks like this:

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)

    created_at = deferred(Column(DateTime, nullable=False, default=datetime.utcnow))
    modified_at = deferred(
        Column(
            DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow
        )
    )

    email = Column(String(255), nullable=False, unique=True, index=True)
    email_verified = Column(Boolean, nullable=False, default=False, index=True)

    password = deferred(Column(String(100)))
    name = Column(String(100), nullable=False)

    score = Column(Integer, nullable=False, default=0, index=True)

    question_count: int = query_expression()
    answer_count: int = query_expression()

    @property
    def is_authenticated(self) -> bool:
        return bool(self.id)

    @property
    def is_active(self) -> bool:
        return True

    @property
    def is_anonymous(self) -> bool:
        return not self.is_authenticated

    def get_id(self) -> str:
        return str(self.id)

    @property
    def url(self) -> Optional[str]:
        if not self.is_authenticated:
            return None
        return url_for("users.profile", id=self.id)
```

And the Base is defined like this:
```
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
```
```


### Error

version: 0.910
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1056, in visit_class_def
  File "mypy/semanal.py", line 1134, in analyze_class
  File "mypy/semanal.py", line 1143, in analyze_class_body_common
  File "mypy/semanal.py", line 1203, in apply_class_plugin_hooks
  File "/home/olzhas/.local/share/virtualenvs/backend-6v_sO_dE/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 258, in _base_cls_hook
    decl_class.scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/home/olzhas/.local/share/virtualenvs/backend-6v_sO_dE/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 93, in scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(
  File "/home/olzhas/.local/share/virtualenvs/backend-6v_sO_dE/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 443, in _scan_declarative_assignment_stmt
    python_type_for_type = infer.infer_type_from_right_hand_nameexpr(
  File "/home/olzhas/.local/share/virtualenvs/backend-6v_sO_dE/lib/python3.9/site-packages/sqlalchemy/ext/mypy/infer.py", line 59, in infer_type_from_right_hand_nameexpr
    python_type_for_type = _infer_type_from_decl_column_property(
  File "/home/olzhas/.local/share/virtualenvs/backend-6v_sO_dE/lib/python3.9/site-packages/sqlalchemy/ext/mypy/infer.py", line 287, in _infer_type_from_decl_column_property
    first_prop_arg = stmt.rvalue.args[0]
IndexError: list index out of range
./models/user.py:12: : note: use --pdb to drop into pdb

### Versions

- OS: PopOS 20.04
- Python: 3.9.5
- SQLAlchemy: 1.4.23
- Database: postgres-13
- DBAPI: psycopg2-binary 2.9.1
- Mypy: 0.910


### Additional context

_No response_

**Comment by olzhasar** [comment]
@zzzeek I tried the latest release, the problem is still present with the same traceback

**Comment by CaselIT** [comment]
it's not yet released, you need to install from github to get the fixed version

**Comment by olzhasar** [comment]
@CaselIT I tried installing from github as well with no success

**Comment by CaselIT** [comment]
@olzhasar I cannot reproduce using this file

```py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, DateTime, Boolean, String
from sqlalchemy.orm import deferred, query_expression
from datetime import datetime

Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)

    created_at = deferred(Column(DateTime, nullable=False, default=datetime.utcnow))
    modified_at = deferred(
        Column(
            DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow
        )
    )

    email = Column(String(255), nullable=False, unique=True, index=True)
    email_verified = Column(Boolean, nullable=False, default=False, index=True)

    password = deferred(Column(String(100)))
    name = Column(String(100), nullable=False)

    score = Column(Integer, nullable=False, default=0, index=True)

    question_count: int = query_expression()
    answer_count: int = query_expression()

    @property
    def is_authenticated(self) -> bool:
        return bool(self.id)

    @property
    def is_active(self) -> bool:
        return True

    @property
    def is_anonymous(self) -> bool:
        return not self.is_authenticated

    def get_id(self) -> str:
        return str(self.id)

    # @property
    # def url(self) -> Optional[str]:
    #     if not self.is_authenticated:
    #         return None
    #     return url_for("users.profile", id=self.id)
```

I get: 
```
> mypy file.py
Success: no issues found in 1 source file
```

**Comment by zzzeek** [comment]
please provide failing stack trace which will indicate if you are running the correct vresion of the code.  the code is different now so there's no way you could get the same error in the same way.

**Comment by olzhasar** [comment]
@zzzeek @CaselIT  Sorry guys, I installed stubs from github by mistake instead of sqlalchemy. That's embarrassing.
It works as expected now. This issue can be closed. Thank you!

**Comment by CaselIT** [comment]
Ok, no problems
