### ISSUE TITLE
lambda_stmt & union_all waste clause.bind on Session.get_bind

### ISSUE THREAD

**Issue by kataev** [sqlalchemy/sqlalchemy#6961]
### Describe the bug

When wrap union_all with lambda_stmt, session can't find their bind.

### To Reproduce

```python
from sqlalchemy import Column, Integer, select, lambda_stmt, union_all
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker

engine = create_engine("sqlite://", echo=1)

engine.execute("CREATE TABLE foo (id integer)")
engine.execute("INSERT INTO foo (id) VALUES (1), (2), (3), (4), (5)")

Base = declarative_base(bind=engine)


class Foo(Base):
    __tablename__ = 'foo'

    id = Column(Integer, primary_key=True)


Session = sessionmaker()

current_id = 5

with Session.begin() as session:
    query1 = select(Foo.id).select_from(Foo)
    query2 = select(Foo.id).select_from(Foo)
    stmt = union_all(query1, query2)

    assert session.execute(stmt).scalars().all()

    assert session.execute(lambda_stmt(lambda: stmt)).scalars().all()
```

### Error

❯ python -m scratch_57
2021-08-31 12:53:45,979 INFO sqlalchemy.engine.Engine CREATE TABLE foo (id integer)
2021-08-31 12:53:45,979 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-31 12:53:45,980 INFO sqlalchemy.engine.Engine COMMIT
2021-08-31 12:53:45,980 INFO sqlalchemy.engine.Engine INSERT INTO foo (id) VALUES (1), (2), (3), (4), (5)
2021-08-31 12:53:45,980 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-31 12:53:45,980 INFO sqlalchemy.engine.Engine COMMIT
2021-08-31 12:53:45,983 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-31 12:53:45,985 INFO sqlalchemy.engine.Engine SELECT foo.id
FROM foo UNION ALL SELECT foo.id
FROM foo
2021-08-31 12:53:45,985 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ()
2021-08-31 12:53:45,985 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/Users/d.kataev/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/d.kataev/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/d.kataev/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch_57.py", line 31, in <module>
    assert session.execute(lambda_stmt(lambda: stmt)).scalars().all()
  File "/Users/d.kataev/.pyenv/versions/3.9.4/envs/dialog-platform/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    bind = self.get_bind(**bind_arguments)
  File "/Users/d.kataev/.pyenv/versions/3.9.4/envs/dialog-platform/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2094, in get_bind
    raise sa_exc.UnboundExecutionError(
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on SQL expression or this Session.

### Versions

- OS: mac os 
- Python: 3.9.4
- SQLAlchemy: 1.4.23
- Database: sqlite, pg
- DBAPI: ???

**Comment by zzzeek** [comment]
Hi there -

This is not something worth fixing, and within the new "lambda statement" feature there was never any assumption that "bound metadata" would work at all.    "bound metadata" has been legacy for many years, is deprecated in SQLAlchemy 1.4 where "lambda statements" were introduced, and will not be present in the next major SQLAlchemy release.     I would not be adding any new features to applications without first removing all reliance on this feature; the general assumption has been that most modern applications are not using it as it has long since been removed from most documentation.

I would advise modernizing your Session approach before digging into new 1.4 features, thanks!
