### ISSUE TITLE
Probably unexpected behavior of sqlalchemy.engine.url.URL._assert_str

### ISSUE THREAD

**Issue by stijm** [sqlalchemy/sqlalchemy#6983]
### Describe the bug
https://github.com/sqlalchemy/sqlalchemy/blob/d640192877e4d1da75e8dea34d2374c404e80538/lib/sqlalchemy/engine/url.py#L155-L169

If `_assert_str` returns a value which is `None` immediately, it doesn't assert a parameter value is a string, but it asserts that it's a string _or_ None – but, inferring from the names, `_assert_none_str` is meant to do so instead.

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

my_url = URL.create(None)
create_engine(my_url)
```

### Error

No direct error, but probably an unexpected behavior.

```
Traceback (most recent call last):
  File "C:/Users/stijm/AppData/Roaming/JetBrains/PyCharm2021.1/scratches/scratch_10.py", line 5, in <module>
    create_engine(my_url)
  File "<string>", line 2, in create_engine
  File ".\Anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File ".\Anaconda3\lib\site-packages\sqlalchemy\engine\create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File ".\Anaconda3\lib\site-packages\sqlalchemy\engine\url.py", line 632, in _get_entrypoint
    if "+" not in self.drivername:
TypeError: argument of type 'NoneType' is not iterable
```

### Versions

- OS: Windows-10-10.0.17134-SP0
- Python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
- SQLAlchemy: 1.4.23

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**remove erroneous None check from _assert_str** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3062

**Comment by zzzeek** [comment]
thanks for finding that!
