### ISSUE TITLE
Document how to use the `ShardedSession` with asyncio

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7028]
### Describe the use case

Now that we have `sync_session_class` we can also use `ShardedSession` with it with something like
```py
shard1_engine = create_async_engine(...)
shard2_engine = create_async_engine(...)

Session = sessionmaker(
    class_=AsyncSession,
    future=True,
    shards={
        "shard1": shard1_engine.sync_engine,
        "shard2": shard2_engine.sync_engine
    },
    sync_session_class=ShardedSession
)
```

so we should document this use case in the ShardedSession documentation

### Databases / Backends / Drivers targeted

any

### Example Use

see above

**Comment by saraducks** [comment]
Tried to use the suggested code above, I am getting the error
`File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 200, in execute
    return await greenlet_spawn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 116, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = fn(orm_exec_state)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/horizontal_shard.py", line 252, in execute_and_instances
    for shard_id in session.execute_chooser(orm_context):
TypeError: 'coroutine' object is not iterable`

**Comment by CaselIT** [comment]
I'm not overly familiar with the sharded session, but it seems you are passing a `execute_chooser` that returns a co-routine instead of a list of shards.

The `ShardedSession` does not support async itself, we are just proxing it, so you would need to provide an `execute_chooser`.

An alternative may if async operation are needed is to use `sqlalchemy.util.concurrency.await_only`:

```py
from sqlalchemy.util.concurrency import await_only

async def get_current_shard(id):
    # do some async stuff
    return ['shard-42']

def execute_chooser(orm_context):
    id = orm_context.parameters.get('id')
    # use await_only instead of await
    execute_chooser = await_only(get_current_shard(id))
    return execute_chooser
```

Please note that all of `sqlalchemy.util` is not really public api, so if you can avoid using an `execute_chooser` it's probably better

**Comment by saraducks** [comment]
That didn't work. getting the same error, while stepping through the code the error happens at context switch.

**Comment by saraducks** [comment]
I am getting different error now 

```
usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py:772: RuntimeWarning: coroutine 'AsyncConnection.close' was never awaited
  conn.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
INFO:     172.17.0.1:64450 - "GET /test/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "./fastapi_sqlalchemy/app.py", line 20, in find_nonsense
    sql_rows = await db_session.execute(text(select_query), {'id':id})
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 200, in execute
    return await greenlet_spawn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = fn(orm_exec_state)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/horizontal_shard.py", line 253, in execute_and_instances
    result_ = iter_for_shard(shard_id, load_options, update_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/horizontal_shard.py", line 235, in iter_for_shard
    return orm_context.invoke_statement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 233, in invoke_statement
    return self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 758, in _connection_for_bind
    elif conn.in_transaction():
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 200, in in_transaction
    conn = self._sync_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 160, in _sync_connection
    self._raise_for_not_started()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/base.py", line 67, in _raise_for_not_started
    raise async_exc.AsyncContextNotStarted(
sqlalchemy.ext.asyncio.exc.AsyncContextNotStarted: AsyncConnection context has not been started and object has not been awaited.
```

**Comment by CaselIT** [comment]
You need to pass the `engine.sync_engine` in the shard list. I've updated the example above

Basically `ShardedSession` knows nothing about async, so it should reason as if everything is sync.

**Comment by CaselIT** [comment]
runnable example:
```py
import asyncio

import sqlalchemy as sa
import sqlalchemy.orm
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.ext.horizontal_shard import ShardedSession
from sqlalchemy.util.concurrency import await_only

e1 = create_async_engine("sqlite+aiosqlite:///")
e2 = create_async_engine("sqlite+aiosqlite:///")


def id_chooser(stmt, values):
    print("id_chooser")
    return ["shard1"]


def shard_chooser(stmt, instance, **kw):
    print("shard_chooser")
    return "shard1"


async def some_async_fn():
    print("some_async_fn")
    await asyncio.sleep(0.001)


def execute_chooser(exec_state):
    print("execute_chooser")
    v = exec_state.execution_options.get("shard")
    await_only(some_async_fn())  # example of running an async thing here
    if v:
        return [v]
    else:
        return ["shard1", "shard2"]


SM = sa.orm.sessionmaker(
    class_=AsyncSession,
    future=True,
    # bind=e1
    shards={"shard1": e1.sync_engine, "shard2": e2.sync_engine},
    sync_session_class=ShardedSession,
    id_chooser=id_chooser,
    shard_chooser=shard_chooser,
    execute_chooser=execute_chooser,
)

meta = sa.MetaData()
T = sa.Table("tbl", meta, sa.Column("value", sa.Integer))


async def prepare(engine, value):
    async with engine.connect() as c:
        await c.run_sync(meta.create_all)
        await c.execute(T.insert().values({"value": value}))
        await c.commit()


async def go():
    await prepare(e1, 1)
    await prepare(e2, 2)

    s: AsyncSession = SM()
    print((await s.execute(T.select())).all())
    print((await s.execute(T.select(), execution_options={'shard': 'shard2'})).all())
    await s.close()


asyncio.run(go())
```

**Comment by saraducks** [comment]
Thank you, This is very helpful to get me unblocked. Appreciate your time 👍🏽

**Comment by jvanasco** [comment]
Thanks for the example, @CaselIT. I can work that into the docs.

**Comment by zzzeek** [comment]
I think we can add this to examples/sharding with some modernizations and that would be it here.

**Comment by CaselIT** [comment]
This can be in v2.x milestone too

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add set_shard_id() loader option for horizontal shard** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4379
