### ISSUE TITLE
EncryptedType create a "TypeError: string argument without an encoding" when querying.

### ISSUE THREAD

**Issue by lambda-science** [sqlalchemy/sqlalchemy#7054]
### Describe the bug

When I use a EncryptedType type for encryption of columns, querying the SQLite database results in an error: `TypeError: string argument without an encoding`  
By  modifying the last line in SQLAlchemy tracebook from `value = bytes(value)` to `value = bytes(value, "utf8")` it works perfectly fine. Should I fork the project and open a pull request ?

### To Reproduce
Here is the code of my SQL-Alchemy class (in Flask) where I try to encrypt the Username field.
```python
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import db

from sqlalchemy_utils import EncryptedType
from sqlalchemy_utils.types.encrypted.encrypted_type import FernetEngine


key = b'zle4-UMuzTsquDBfN8faOqKVzl_QN2kMW3UIaMox7KI=' # This is not my real key


class User(UserMixin, db.Model):
    """Database table for Users"""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(
        EncryptedType(db.String(64), key, FernetEngine),
        index=True,
        unique=True,
        nullable=False,
    )
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    images = db.relationship("Image", backref="creator", lazy="dynamic")
    report = db.relationship("ReportHisto", backref="creator", lazy="dynamic")

    def __repr__(self):
        return "<User {} Email {}>".format(self.username, self.email)

    def set_password(self, password):
        """Method to hash password in DB"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Method to check plain-text password against hashed password"""
        return check_password_hash(self.password_hash, password)


Then I register my User using Flask Shell such as:
```python
> user = User(username="demo", email="demo@demo.demo")
> user.set_password("demo")
> db.session.add(user)
> db.session.commit()
```
It works as expected. But then when I query it using `User.query.get(1)` I get the traceback bellow.

### Error

```python-traceback
>>> User.query.get(1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
    _populate_full(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1275, in process
    return process_value(impl_processor(value), dialect)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 946, in process
    value = bytes(value)
TypeError: string argument without an encoding
```

### Versions

- OS: UBUNTU 20.04.2 LTS
- Python: 3.8.10
- SQLAlchemy: 1.3.23 ; sqlalchemy-utils=0.37.8
- Database: SQLITE 3.36.0
- DBAPI: Not Sure ?

**Comment by CaselIT** [comment]
Hi,

I think this should be raised to the `sqlalchemy-utils`, since the issues seems to be `EncryptedType`

**Comment by CaselIT** [comment]
Also looking at your example:
> `EncryptedType(db.String(64), key, FernetEngine),`

and the error, maybe you should use a binary column instead of `String`

**Comment by zzzeek** [comment]
this is a third party issue outside of SQLAlchemy.
