### ISSUE TITLE
Column as keys for insert.values() with multi-values with declarative_base

### ISSUE THREAD

**Issue by scott-arne** [sqlalchemy/sqlalchemy#7060]
### Describe the bug

This bug is an extension of:
https://github.com/sqlalchemy/sqlalchemy/issues/4162

I've found the same bug when using declarative_base columns as keys. It works with a single row, but fails with multiple.

Attached in "To Reproduce" is a minimal script that reproduces the error.

But mainly from that example, the following works:

```python
    with engine.connect() as conn:
        stmt = insert(Metadata).values({Metadata.key: "foo", Metadata.value: "bar"})
        conn.execute(stmt)
```

And the following doesn't:

```python
    with engine.connect() as conn:
        # Try with list of values and column keys from the declarative_base object
        stmt = insert(Metadata).values([
            {Metadata.key: "baz", Metadata.value: "does not work"},
            {Metadata.key: "bum", Metadata.value: "does not work"}
        ])
        conn.execute(stmt)
```

### To Reproduce

```python
import os
from sqlalchemy import insert, create_engine, Column, Text
from sqlalchemy.engine.url import URL
from sqlalchemy.orm import declarative_base


ExampleBase = declarative_base()


class Metadata(ExampleBase):
    __tablename__ = "METADATA"

    key = Column("KEY", Text, primary_key=True)
    value = Column("VALUE", Text, nullable=True)


if __name__ == "__main__":
    # For testing purposes, create a fresh test db
    if os.path.exists("test.db"):
        os.unlink("test.db")

    # Create engine
    engine = create_engine(
        URL(
            drivername="sqlite",
            database="test.db"
        )
    )

    # Create the schema
    ExampleBase.metadata.create_all(engine)

    # This works!
    with engine.connect() as conn:
        stmt = insert(Metadata).values({Metadata.key: "foo", Metadata.value: "bar"})
        conn.execute(stmt)

    print("Inserted foo")

    # Trying with multiple values doesn't work
    with engine.connect() as conn:
        # Try with list of values and column keys from the declarative_base object
        stmt = insert(Metadata).values([
            {Metadata.key: "baz", Metadata.value: "does not work"},
            {Metadata.key: "bum", Metadata.value: "does not work"}
        ])
        conn.execute(stmt)
```

### Error
```
Traceback (most recent call last):
  File "/Users/johnss51/Development/python/cakedock/create_error.py", line 47, in <module>
    conn.execute(stmt)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1444, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 531, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 553, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 765, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 454, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 489, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3625, in visit_insert
    crud_params = crud._get_crud_params(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 174, in _get_crud_params
    values = _extend_values_for_multiparams(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 938, in _extend_values_for_multiparams
    new_param = _process_multiparam_default_bind(
  File "/Users/johnss51/Development/python/cakedock/venv/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 816, in _process_multiparam_default_bind
    raise exc.CompileError(
sqlalchemy.exc.CompileError: INSERT value for column METADATA.KEY is explicitly rendered as a boundparameter in the VALUES clause; a Python-side value or SQL expression is required
```
### Versions

- OS: Mac OS 10.15.7
- Python: 3.9.6
- SQLAlchemy: 1.4.23
- Database: SQLite
- DBAPI: SQLite 3.34.0

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**coerce for multivalues keys** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3092
