### ISSUE TITLE
An attempt to complete a transaction has failed. No corresponding transaction found.

### ISSUE THREAD

**Issue by paradox-lab** [sqlalchemy/sqlalchemy#7065]
### Describe the bug

I'm trying to connect to an Azure SQL Data Warehouse via SQLAchemy, but it throw an exception.

### To Reproduce

```python
from sqlalchemy import create_engine

engine = create_engine('mssql+pyodbc://{{username}}:{{password}}@{{host}}/{{db}}?driver=ODBC Driver 17 for SQL Server')

engine.connect()
```

### Error
```
Traceback (most recent call last):
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 419, in checkout
    rec = pool._do_get()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    self._dec_overflow()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 142, in _do_get
    return self._create_connection()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 612, in __connect
    pool.dispatch.connect(self.connection, self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\event\attr.py", line 320, in __call__
    fn(*args, **kw)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1643, in go
    return once_fn(*arg, **kw)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 672, in first_connect
    dialect.do_rollback(c.connection)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 641, in do_rollback
    dbapi_connection.rollback()
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]111214;An attempt to complete a transaction has failed. No corresponding transaction found. (111214) (SQLEndTran)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "E:\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6bd5b75ddd5e>", line 1, in <module>
    c.connect()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 91, in __init__
    else engine.raw_connection()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3144, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2003, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 419, in checkout
    rec = pool._do_get()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    self._dec_overflow()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 142, in _do_get
    return self._create_connection()
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 612, in __connect
    pool.dispatch.connect(self.connection, self)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\event\attr.py", line 320, in __call__
    fn(*args, **kw)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1643, in go
    return once_fn(*arg, **kw)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 672, in first_connect
    dialect.do_rollback(c.connection)
  File "E:\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 641, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]111214;An attempt to complete a transaction has failed. No corresponding transaction found. (111214) (SQLEndTran)')
(Background on this error at: http://sqlalche.me/e/14/f405)
```
### Versions

- OS: win10
- Python: 3.9.6
- SQLAlchemy: 1.4.5
- Database: Azure SQL Data Warehouse
- DBAPI: pyodbc

### Additional context

If I run the via pyodbc, it work fine:

```python
import pyodbc

pyodbc.connect('DRIVER=ODBC Driver 17 for SQL Server;SERVER={{host}};DATABASE={{db}};UID={{username}};PWD={{password}}')
```

I found that it can't connect to db after executing the method `get_isolation_level`:
![image](https://user-images.githubusercontent.com/57354735/134316039-9d1f70f2-f2af-4678-9393-18fe294b4fde.png)

![image](https://user-images.githubusercontent.com/57354735/134317661-528bd47f-c8c5-42e7-b248-d19fd9482664.png)

and it could reproduce using pyodbc API:
```python
conn = pyodbc.connect('DRIVER=ODBC Driver 17 for SQL Server;SERVER={{host}};DATABASE={{db}};UID={{username}};PWD={{password}}')

cursor = conn.cursor()
view = 'sys.dm_exec_sessions'
cursor.execute(
                    """
                  SELECT CASE transaction_isolation_level
                    WHEN 0 THEN NULL
                    WHEN 1 THEN 'READ UNCOMMITTED'
                    WHEN 2 THEN 'READ COMMITTED'
                    WHEN 3 THEN 'REPEATABLE READ'
                    WHEN 4 THEN 'SERIALIZABLE'
                    WHEN 5 THEN 'SNAPSHOT' END AS TRANSACTION_ISOLATION_LEVEL
                    FROM %s
                    where session_id = @@SPID
                  """
                    % view
                )
# it got Exception: Catalog view 'dm_exec_sessions' is not supported in this version.
cursor.close()
conn.rollback()
# it got Exception below:
"""
Traceback (most recent call last):
  File "E:\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-8084f4370a6e>", line 1, in <module>
    conn.rollback()
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]111214;An attempt to complete a transaction has failed. No corresponding transaction found. (111214) (SQLEndTran)')
"""
```

**Comment by zzzeek** [comment]
paging @gordthompson   - looks like you dealt wiht this at https://stackoverflow.com/questions/57123667/sqlalchemy-error-an-attempt-to-complete-a-transaction-has-failed-no-correspond .  2K views also.  are we not allowed to call rollback() with azure?  did we document using autocommit isolation level w/ this?

**Comment by gordthompson** [comment]
> are we not allowed to call rollback() with azure? 

AFAIK, "Azure SQL **Data Warehouse**" does not do transactions at all.

> did we document using autocommit isolation level w/ this?

No, the only mention of Azure in the mssql dialect docs is regarding authentication (tokens, and whatnot).

Unfortunately, I currently do not have an Azure SQL DW instance available for testing, but I suspect that the fix could be as simple as declaring the engine like this:

```python
engine = create_engine(connection_uri).execution_options(
    isolation_level="AUTOCOMMIT"
)
```

If @paradox-lab can confirm that it works then we could add that to the dialect docs and I could answer the SO question (since the `autocommit=True` flag I mentioned in the comments is deprecated).

**Comment by paradox-lab** [comment]
Thanks for the reply.

> If @paradox-lab can confirm that it works then we could add that to the dialect docs and I could answer the SO question (since the `autocommit=True` flag I mentioned in the comments is deprecated).

It got the same expectation.

```python
engine = create_engine(connection_uri).execution_options(
    isolation_level="AUTOCOMMIT"
)

engine.connect()

# raise:
"""
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]111214;An attempt to complete a transaction has failed. No corresponding transaction found. (111214) (SQLEndTran)')
(Background on this error at: http://sqlalche.me/e/14/f405)
"""
```

**Comment by gordthompson** [comment]
Hmm. Okay, how about if you also append `autocommit=True` to your connection URI, e.g.,

```
connection_uri = "mssql+pyodbc://@mssqlLocal?autocommit=True"
```

**Comment by paradox-lab** [comment]
> Hmm. Okay, how about if you also append `autocommit=True` to your connection URI, e.g.,
> 
> ```
> connection_uri = "mssql+pyodbc://@mssqlLocal?autocommit=True"
> ```

I append `?autocommit=True`  to connection URI but it seem not support this parameter.

-------------------------------------------------

 I fixed this error by this way:

```python
engine = create_engine(connection_uri, connect_args={"autocommit": True})
engine.connect()
```

**Comment by CaselIT** [comment]
I think it may make sense add a paragraph in the documentation

**Comment by zzzeek** [comment]
that connect_arg "autocommit=True" should work in the URL as well, should be equivalent can we check on that?

**Comment by gordthompson** [comment]
> that connect_arg "autocommit=True" should work in the URL as well, should be equivalent can we check on that?

Looks okay to me:

```python
engine1 = sa.create_engine("mssql+pyodbc://@mssqlLocal?autocommit=True")
engine2 = sa.create_engine(
    "mssql+pyodbc://@mssqlLocal", connect_args={"autocommit": True}
)
pyodbc_conn1 = engine1.raw_connection()
pyodbc_conn2 = engine2.raw_connection()
assert pyodbc_conn1.autocommit == True  # no error
assert pyodbc_conn2.autocommit == True  # no error
```

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add autocommit documentation for Azure SQL DW** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3098
