### ISSUE TITLE
do_connect event not implemented on AsyncEngine

### ISSUE THREAD

**Issue by dgilmanTORQATA** [sqlalchemy/sqlalchemy#7074]
### Describe the bug

Trying to implement the do_connect event hook on the AsyncEngine returned by create_async_engine raises an exception. I notice that the object has a property `sync_engine` and it is possible to attach the event hook to that, but I do not know if that works or if it is recommended. If hooking the internal sync_engine object is the intended way to do this it should probably be documented.

### To Reproduce

```python
from sqlalchemy import create_engine, event

async_engine = create_async_engine(
    async_db_url,
)

@event.listens_for(async_engine, "do_connect")
def do_connect_async(dialect, conn_rec, cargs, cparams):
    pass
```

### Error
```
Traceback (most recent call last):
  File "/Users/dgilman/stash/oe-poet/api/.venv/lib/python3.9/site-packages/sqlalchemy/event/base.py", line 104, in __getattr__
    ls = self._empty_listeners[name]
KeyError: 'do_connect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[...snip...]
  File "/Users/dgilman/stash/oe-poet/api/oe_poet_backend/db.py", line 89, in <module>
    def do_connect_async(dialect, conn_rec, cargs, cparams):
  File "/Users/dgilman/stash/oe-poet/api/.venv/lib/python3.9/site-packages/sqlalchemy/event/api.py", line 142, in decorate
    listen(target, identifier, fn, *args, **kw)
  File "/Users/dgilman/stash/oe-poet/api/.venv/lib/python3.9/site-packages/sqlalchemy/event/api.py", line 99, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/Users/dgilman/stash/oe-poet/api/.venv/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 213, in listen
    dispatch_collection = getattr(target.dispatch, identifier)
  File "/Users/dgilman/stash/oe-poet/api/.venv/lib/python3.9/site-packages/sqlalchemy/event/base.py", line 106, in __getattr__
    raise AttributeError(name)
AttributeError: do_connect
```
### Versions

- OS: Mac
- Python: Yes
- SQLAlchemy: Yes
- Database: asyncpg
- DBAPI: ????

**Comment by CaselIT** [comment]
Hi,

Yes, using the `sync_engine` is the reccomented way of registering events for asyncio.

I though it was documented, but apparently it's not yet so. Also the exception would probably be nicer. I'll leave it open as a documentation issue

**Comment by zzzeek** [comment]
we have a lot of docs for this here: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#using-events-with-the-asyncio-extension  as part of 38d6c6c5dc3  / #6899
