### ISSUE TITLE
Migrating to 1.4 breaks pickeling of joinloaded relationships

### ISSUE THREAD

**Issue by zvyn** [sqlalchemy/sqlalchemy#7134]
### Describe the bug

Pickeling an object loaded with `session.query(Child).options(joinedload(Child.parent), raiseload("*").first()` fails if `Parent` has relationship(s) of it's own because the `PathToken` object created in that case fails to be pickled. The issue occurred after migrating from 1.3 to 1.4 (independent of the `future`-flag). 

### To Reproduce

```python
from pickle import dumps

import sqlalchemy as sa
from sqlalchemy import orm, schema

print("SQLAlchemy", sa.__version__)

metadata = schema.MetaData()


@orm.as_declarative(metadata=metadata)
class Base:

    @orm.declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()



class Grandparent(Base):

    id = sa.Column(sa.Integer, primary_key=True)


class Parent(Base):

    id = sa.Column(sa.Integer, primary_key=True)
    grandparent_id = sa.Column(sa.ForeignKey("grandparent.id", ondelete="CASCADE"), nullable=False)
    grandparent = orm.relationship(Grandparent)


class Child(Base):

    id = sa.Column(sa.Integer, primary_key=True)
    parent_id = sa.Column(sa.ForeignKey("parent.id", ondelete="CASCADE"), nullable=False)
    parent = orm.relationship(Parent)


def set_up_example_data(engine):
    metadata.create_all(engine)
    with orm.Session(engine) as session:
        grandparent = Grandparent()
        session.add(grandparent)
        parent = Parent(grandparent=grandparent)
        session.add(parent)
        session.add(Child(parent=parent))
        session.commit()


def main():
    engine = sa.create_engine("sqlite+pysqlite:///:memory:", future=True)
    set_up_example_data(engine)

    with orm.Session(engine) as session:
        child = session.query(Child).options(
            orm.joinedload(Child.parent),
            orm.raiseload("*"),
        ).first()

    # This raises an AttributeError:
    dumps(child)


if __name__ == "__main__":
    main()
```

### Error

```
SQLAlchemy 1.4.25
Traceback (most recent call last):
  File "./it_is_a_pickle.py", line 65, in <module>
    main()
  File "./it_is_a_pickle.py", line 61, in main
    dumps(child)
  File "/home/milan/Code/sqlalchemy_pickle/env/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 631, in __getstate__
    d["path"] = self.path.serialize()
  File "/home/milan/Code/sqlalchemy_pickle/env/lib/python3.8/site-packages/sqlalchemy/orm/path_registry.py", line 178, in serialize
    return self._serialize_path(path)
  File "/home/milan/Code/sqlalchemy_pickle/env/lib/python3.8/site-packages/sqlalchemy/orm/path_registry.py", line 134, in _serialize_path
    [m.class_ for m in [path[i] for i in range(0, len(path), 2)]],
  File "/home/milan/Code/sqlalchemy_pickle/env/lib/python3.8/site-packages/sqlalchemy/orm/path_registry.py", line 134, in <listcomp>
    [m.class_ for m in [path[i] for i in range(0, len(path), 2)]],
AttributeError: 'PathToken' object has no attribute 'class_'
```

### Versions

- OS: Ubuntu 20.04.3
- Python: 3.8.10 (also tested with 3.7 on Debian with the same result)
- SQLAlchemy: 1.4.25

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting the issue.

**Comment by CaselIT** [comment]
Also looking at the example, it seems that you are using the loaded object after the session context has exited. It's probably not it, but you should manipulated the object obtained from the session in its' condext:

```py
def main():
    engine = sa.create_engine("sqlite+pysqlite:///:memory:", future=True)
    set_up_example_data(engine)

    with orm.Session(engine) as session:
        child = session.query(Child).options(
            orm.joinedload(Child.parent),
            orm.raiseload("*"),
        ).first()

        # This raises an AttributeError:
        dumps(child)
```
