### ISSUE TITLE
`TypeError: unhashable type: 'bytearray'` when reflecting a table using mysqlconnector

### ISSUE THREAD

**Issue by anthnyprschka** [sqlalchemy/sqlalchemy#7170]
### Describe the bug

When I try to reflect an existing MySQL table, I get `TypeError: unhashable type: 'bytearray'`

### To Reproduce

```python
>>> from sqlalchemy import create_engine, MetaData, Table
>>> engine = create_engine(
...     "mysql+mysqlconnector://...",
...     echo=True,
...     future=True,
... )
>>> metadata = MetaData() 
>>> tablea = Table("tablea", metadata, autoload_with=engine)
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in __new__
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 601, in __new__
    metadata._remove_table(name, schema)
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    table._init(name, metadata, *args, **kw)
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 671, in _init
    self._autoload(
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 706, in _autoload
    conn_insp.reflect_table(
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 794, in reflect_table
    self._reflect_fk(
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 947, in _reflect_fk
    fkeys = self.get_foreign_keys(
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 564, in get_foreign_keys
    return self.dialect.get_foreign_keys(
  File "<string>", line 2, in get_foreign_keys
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 3124, in get_foreign_keys
    self._correct_for_mysql_bugs_88718_96365(fkeys, connection)
  File "/bini/venv/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 3191, in _correct_for_mysql_bugs_88718_96365
    d[(lower(schema), lower(tname))]["SCHEMANAME"] = schema
TypeError: unhashable type: 'bytearray'
``` 

### Versions

- OS: Ubuntu 20.04
- Python: 3.8.10
- SQLAlchemy: 1.4.22
- Database: MySQL 8.0.23
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysql-connector-python-rf==2.2.2, mysqlclient==2.0.3

**Comment by zzzeek** [comment]
hey there -

step one, dont use mysqlconnector.  this driver has ongoing issues and surprising API effects.   please try mysqlclient or pymysql.

this is not an MCVE so moving to discussion.

**Comment by zzzeek** [comment]
please share all mysqlconnector URL options as well.   you may need to include encoding, etc.

**Comment by zzzeek** [comment]
there's probably a way to alter the mysqlconnector dialect to work around this but i dont have the resources to deal with it right now.
