### ISSUE TITLE
can't import mysql wo greenlet installed

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7204]
```
$ python -m sqlalchemy.dialects.mysql
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/mysql/__init__.py", line 57, in <module>
    from . import asyncmy  # noqa
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/mysql/asyncmy.py", line 175, in <module>
    class AsyncAdapt_asyncmy_connection(AdaptedConnection):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/mysql/asyncmy.py", line 185, in AsyncAdapt_asyncmy_connection
    async def _mutex_and_adapt_errors(self):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/concurrency.py", line 63, in asynccontextmanager
    _not_implemented()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/concurrency.py", line 37, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function.
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**vendor asynccontextmanager outside of greenlet dependency** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3173
