### ISSUE TITLE
`Query.yield_from` keeps query active after iterating through all results; filtered results dont close correctly

### ISSUE THREAD

**Issue by zuckerruebe** [sqlalchemy/sqlalchemy#7274]
### Describe the bug

I have an alembic migration that adds and removes a couple of columns in a  table and needs to remold the existing rows to fit the new schema. Because I'm dealing with a lot of rows and I need to do non-trivial work to reshape the rows I'm doing that on the client side, in Python. For obvious reasons I turned to "streaming mode"/"yield from" for that. However, after having transformed all my rows I get an error about a query still being active when I want to delete my old table.

### To Reproduce

```python
"""Accommodate measurements from any endpoint.

Revision ID: 22964e2b9c5b
Revises: 640fd90533f0
Create Date: 2021-10-19 11:41:46.791621

"""
import typing as tp
import logging as log

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "22964e2b9c5b"
down_revision = "aa3a6dd24d0c"
branch_labels = None
depends_on = None

from sqlalchemy import Boolean, CHAR, Column, DateTime, Float, ForeignKey, Identity, Integer, String
from sqlalchemy.orm import declarative_base, relationship

import rest_api as _api

logger = log.getLogger(f"migration-{revision}")

Base = declarative_base()


class Building(Base):
    __tablename__ = "buildings"

    _id = Column(CHAR(24), primary_key=True)
    name = Column(String(64))
    created_at = Column(DateTime)
    street = Column(String(64))
    street_nr = Column(String(64))
    city = Column(String(64))
    postal = Column(Integer)
    floors = Column(Integer)

    apartments = relationship("Apartment", back_populates="building")


class Apartment(Base):
    __tablename__ = "apartments"

    _id = Column(CHAR(24), primary_key=True)
    building_id = Column(ForeignKey("buildings._id"), nullable=False)
    name = Column(String(128))
    created_at = Column(DateTime)
    occ_state = Column(String(64))
    apartment_type = Column(String(64))
    active = Column(Boolean)

    building = relationship("Building", back_populates="apartments")
    rooms = relationship("Room", back_populates="apartment")


class Room(Base):
    __tablename__ = "rooms"

    _id = Column(CHAR(24), primary_key=True)
    apartment_id = Column(ForeignKey("apartments._id"), nullable=False)
    name = Column(String(128))
    created_at = Column(DateTime)

    apartment = relationship("Apartment", back_populates="rooms")
    devices = relationship("Device", back_populates="room")


class Device(Base):
    __tablename__ = "devices"

    _id = Column(CHAR(24), primary_key=True)
    room_id = Column(ForeignKey("rooms._id"), nullable=False)
    name = Column(String(128))
    code = Column(CHAR(7))
    created_at = Column(DateTime)

    room = relationship("Room", back_populates="devices")
    measurements = relationship("OldMeasurement", back_populates="dev")


class OldMeasurement(Base):
    __tablename__ = "measurements"

    _id = Column(
        Integer,
        Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
        primary_key=True,
    )
    dev_id = Column(ForeignKey("devices._id"), nullable=False)
    tstamp = Column(DateTime)
    temperature_current = Column(Float(53))
    temperature_target = Column(Float(53))

    dev = relationship("Device", back_populates="measurements")


class NewMeasurement(Base):
    __tablename__ = "new_measurement"

    _id = Column(
        Integer,
        Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
        primary_key=True,
    )
    dev_id = Column(ForeignKey("devices._id"), nullable=False)
    endpoint_id = Column(CHAR(24), nullable=False)
    tstamp = Column(DateTime)
    value = Column(Float(53))


def upgrade():
    logger.info("Starting upgrade...")

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    NewMeasurement.__table__.create(bind)

    _create_new_measurements_based_on_old_ones(session)

    OldMeasurement.__table__.drop(bind)

    op.rename_table(NewMeasurement.__tablename__, OldMeasurement.__tablename__)


def _create_new_measurements_based_on_old_ones(session: sa.orm.Session):
    old_measurements = session.query(OldMeasurement).yield_per(1000)
    for i, old_measurement in enumerate(old_measurements):
        new_measurements = _create_new_measurement(old_measurement)
        for new_measurement in new_measurements:
            session.add(new_measurement)

        if i % 1000 == 0:
            session.commit()
            logger.info("Migrated %i measurements...", i)
    session.commit()


def _create_new_measurement(old_measurement: OldMeasurement) -> tp.Iterable[NewMeasurement]:
    device_code = old_measurement.dev.code.strip()

    assert device_code == "000061", f"{device_code=}"

    device_type = _api.DEVICE_TYPES_BY_CODE[device_code]

    room_temperature_endpoint = device_type.get_endpoint("Room temperature")
    target_temperature_endpoint = device_type.get_endpoint("Target temperature")

    if old_measurement.temperature_current:
        yield NewMeasurement(
            dev_id=old_measurement.dev_id,
            endpoint_id=room_temperature_endpoint.id,
            tstamp=old_measurement.tstamp,
            value=old_measurement.temperature_current,
        )
    elif old_measurement.temperature_target:
        yield NewMeasurement(
            dev_id=old_measurement.dev_id,
            endpoint_id=target_temperature_endpoint.id,
            tstamp=old_measurement.tstamp,
            value=old_measurement.temperature_target,
        )
    else:
        raise AssertionError("Neither room nor target temperature is set.")
```

### Error

```
Traceback (most recent call last):
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ObjectInUse: cannot DROP TABLE "measurements" because it is being used by active queries in this session


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyscripts/GoZmart/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pyscripts/GoZmart/alembic/env.py", line 75, in <module>
    run_migrations_online()
  File "/home/pyscripts/GoZmart/alembic/env.py", line 69, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/home/pyscripts/GoZmart/alembic/versions/22964e2b9c5b_accommodate_measurements_from_any_.py", line 135, in upgrade
    OldMeasurement.__table__.drop(bind)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 967, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2110, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1097, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1286, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1378, in _execute_ddl
    ret = self._execute_context(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/home/pyscripts/GoZmart/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.ObjectInUse) cannot DROP TABLE "measurements" because it is being used by active queries in this session

[SQL:
DROP TABLE measurements]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

``` 

### Versions

- OS: Windows 10
- Python: 3.9
- SQLAlchemy: 1.4.25
- Database: PostgreSQL (on Ubuntu 20.04)
- DBAPI: psycopg2

### Additional context

I tried but gave up finding the reason for this error in the documentation. As far as I understood `commit`ing should deal with a lot of "old stuff still lying around" issues as should exhausting the iterable in the `for` loop...

**Comment by CaselIT** [comment]
Hi,

This was answered on gitter. A solution is to close the session before dropping the table.
But I think the result should be closed when the yield has finished iterating, and it does not seem to do that at the moment.

**Comment by zuckerruebe** [comment]
@CaselIT Or maybe close the `Result` as a work-around, seems more...right...to me somehow. :) Thanks for your answer on Gitter, btw.

**Comment by zzzeek** [comment]
hi there -

OK your test case sent me down the wrong trail, which is because your alembic migration is not doing what you think it is.  those calls to session.commit() are no-ops, because your alembic migration is already in a transaction.  the pattern with your session is basically the one illustrated at https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites .   so this is why, even after you call session.commit(), the table can't be dropped.  because nothing was committed.  Usually the normal error when trying to drop a table in a new transaction when results are opened elsewhere is that PostgreSQL hangs, but PG here is able to give you that immediate error because this is all in the same transaction.

what your program is doing is that it's trying to drop the table on the same connection / transaction as the one in which you were fetching results, and in that case, SQLAlchemy's 1.4 ORM is in fact missing a cursor.close() that we can stick in there to "fix" the issue, but your program is still running in one big transaction.   might be fine, I'd change those session.commits() to session.flush().

Since there is a spot for close() to run we will add that.

**Comment by zuckerruebe** [comment]
@zzzeek Thanks for the analysis!

I'm lacking a lot of context here, but I was just wondering whether `commit` shouldn't throw in that case as it doesn't/couldn't do what I expect it to.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**improve .close() behavior / options for yield_per** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3254

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**improve .close() behavior / options for yield_per** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3255

**Comment by zzzeek** [comment]
> @zzzeek Thanks for the analysis!
> 
> I'm lacking a lot of context here, but I was just wondering whether `commit` shouldn't throw in that case as it doesn't/couldn't do what I expect it to.

well it's doing something that's a documented use case, so we'd have to add new explicit API for "checking" this, like a flag on Session to enable the "join an external transaction mode", but we can't do that all at once due to compatibility.  there's certainly a lot less of the "nesting" thing in SQLAlchemy 2.0 but this particular one is still there because this is a widely used pattern.

**Comment by zzzeek** [comment]
this is in fetchmany() for the server side cursor result set, ORM should not have to call .close().

**Comment by zzzeek** [comment]
as i am fixing close() and will be directing to this issue, here is another bug we can illustrate occurring with yield_per, where the buffered result in use does not correctly close out its iterators when it's soft closed:

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import exc
from sqlalchemy import Integer, select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine(
    "postgresql://scott:tiger@localhost/test", echo=True, future=True
)

Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([A(data=f"data {i}") for i in range(500)])
s.commit()
s.close()


s = Session(e)
result = s.execute(select(A), execution_options={"yield_per": 10})

batch = result.fetchmany(50)

result.first()

# fails.   if yield per is not on, returns empty list.
# but really should raise ResourceClosedError, because first() was called.
assert not result.fetchmany(10)
```
