### ISSUE TITLE
Deferred loading fails with joined table inheritance 

### ISSUE THREAD

**Issue by torsdag** [sqlalchemy/sqlalchemy#7304]
### Describe the bug

When loading a column lazily from a child model ( using joined inheritance ) the attribute fails to populate. If the exception is caught and the attribute is accessed again it returns the expected result.

### To Reproduce

```python
import sqlalchemy
import sqlalchemy.orm

from sqlalchemy.ext.declarative import (
    declarative_base
)

Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, primary_key=True
    )

    parent_id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey(id), nullable=True
    )

    children = sqlalchemy.orm.relationship(
        'Entity', backref=sqlalchemy.orm.backref(
            'parent',  remote_side='Entity.id'
        )
    )

    attribute_type = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_on': attribute_type,
        'polymorphic_identity': 'entity'
    }


class EntityTwo(Entity):
    __tablename__ = 'entity_two'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey(Entity.id), primary_key=True
    )

    name = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_identity': 'entity_two'
    }


engine = sqlalchemy.create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sqlalchemy.orm.sessionmaker(
    bind=engine
)

session = Session()

session.add(
    EntityTwo(
        id=1,
        name='test1'
    )
)
session.add(
    EntityTwo(
        id=2,
        parent_id=1
    )
)

session.commit()

result = session.query(
    Entity
).options(
    sqlalchemy.orm.load_only(
        Entity.id
    )
).options(
    sqlalchemy.orm.joinedload(
        Entity.parent
    ).load_only(
        Entity.id
    )
).filter(
    Entity.id == 2
).all()


result[0].parent.name
```

### Error

```
Traceback (most recent call last):
 File "test.py", line 99, in <module>
   result[0].parent.name
 File "..venv/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
   return self.impl.get(state, dict_)
 File "..venv/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 941, in get
   replace_context=err,
 File "<string>", line 5, in raise_
 KeyError: "Deferred loader for attribute 'name' failed to populate correctly"``` 

### Versions

- OS: fedora 34
- Python: 2.7.18
- SQLAlchemy: 1.4.26
- Database: mariadb / sqlite ( tested ) 
- DBAPI : any


### Additional context

_No response_

**Comment by zzzeek** [comment]
well you've managed to combine every difficult feature into one issue, great job w/ the test case.   with option pathing issues I'm never quite sure how solvable they are so will keep you posted here.

**Comment by torsdag** [comment]
ah yes, sorry should have separated that out.

cheers

**Comment by zzzeek** [comment]
no problem at all! this is a really specific thing you've found here.  very helpful

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**upgrade deferred loader to regular loader if refresh_state** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3296

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**upgrade deferred loader to regular loader if refresh_state** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3297
