### ISSUE TITLE
multiple query entities load options are applied inappropriately when reloading expired attributes

### ISSUE THREAD

**Issue by owtaylor** [sqlalchemy/sqlalchemy#7318]
### Describe the bug

With sqlalchemy-1.4.x, when a query: 

 * returns multiple different types of entities, because `add_entity()` is used, or because multiple arguments are passed to Query()
 * has options like `joinedload()`

E.g:

``` python
query_result = session.query(User) \
    .join(UserExtra, UserExtra.username == User.username) \
    .add_entity(UserExtra) \
    .options(joinedload(User.pet))
```

Then these options are saved in the instance state, and applied when reloading expired attributes *of all returned entities*, even when not applicable to the query generated for reloading the expired attributes.

The example I am providing works with 1.3.24, but fails with 1.4.26 and older 1.4.x.

### To Reproduce

```python
from sqlalchemy import create_engine, Column, ForeignKey, Integer, String
from sqlalchemy.orm import joinedload, relationship, sessionmaker
from sqlalchemy.ext.declarative import as_declarative


@as_declarative()
class Base:
    id = Column(Integer, primary_key=True)

class User(Base):
    __tablename__ = 'users'

    username = Column(String, nullable=False)

class Pet(Base):
    __tablename__ = 'pet'

    name = Column(String, nullable=False)

    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    user = relationship("User", back_populates="pet", uselist=False)

User.pet = relationship("Pet", back_populates="user")

class UserExtra(Base):
    __tablename__ = 'user_extras'

    username = Column(String, nullable=False)
    age = Column(Integer, nullable=False)

# ---------------------------------

engine = create_engine('sqlite:///:memory:', echo=True)
Session = sessionmaker(bind=engine)
Base.metadata.create_all(engine)

session = Session()

user = User(username="john.doe")
fido = Pet(user=user, name="Fido")
fifi = Pet(user=user, name="Fifi")
session.add(user)

extra = UserExtra(username="john.doe", age=42)
session.add(extra)

session.commit()

# --------------------------------------

session = Session()

query_result = session.query(User) \
    .join(UserExtra, UserExtra.username == User.username) \
    .add_entity(UserExtra) \
    .options(joinedload(User.pet)).all()

for user, extra in query_result:
    print(user.username, user.pet, extra.age)

for user, extra in query_result:
    session.expire(extra)
    print(extra.age)
```

### Error

```
2021-11-12 14:13:56,980 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-11-12 14:13:56,980 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("users")
2021-11-12 14:13:56,980 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,980 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("users")
2021-11-12 14:13:56,980 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("pet")
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("pet")
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user_extras")
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("user_extras")
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine 
CREATE TABLE users (
	id INTEGER NOT NULL, 
	username VARCHAR NOT NULL, 
	PRIMARY KEY (id)
)


2021-11-12 14:13:56,981 INFO sqlalchemy.engine.Engine [no key 0.00006s] ()
2021-11-12 14:13:56,982 INFO sqlalchemy.engine.Engine 
CREATE TABLE user_extras (
	id INTEGER NOT NULL, 
	username VARCHAR NOT NULL, 
	age INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2021-11-12 14:13:56,982 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2021-11-12 14:13:56,982 INFO sqlalchemy.engine.Engine 
CREATE TABLE pet (
	id INTEGER NOT NULL, 
	name VARCHAR NOT NULL, 
	user_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)


2021-11-12 14:13:56,982 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2021-11-12 14:13:56,982 INFO sqlalchemy.engine.Engine COMMIT
2021-11-12 14:13:56,985 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-11-12 14:13:56,986 INFO sqlalchemy.engine.Engine INSERT INTO users (username) VALUES (?)
2021-11-12 14:13:56,986 INFO sqlalchemy.engine.Engine [generated in 0.00009s] ('john.doe',)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine INSERT INTO user_extras (username, age) VALUES (?, ?)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine [generated in 0.00007s] ('john.doe', 42)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine INSERT INTO pet (name, user_id) VALUES (?, ?)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine [generated in 0.00007s] ('Fido', 1)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine INSERT INTO pet (name, user_id) VALUES (?, ?)
2021-11-12 14:13:56,987 INFO sqlalchemy.engine.Engine [cached since 0.000231s ago] ('Fifi', 1)
2021-11-12 14:13:56,988 INFO sqlalchemy.engine.Engine COMMIT
2021-11-12 14:13:56,988 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-11-12 14:13:56,990 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.username AS users_username, user_extras.id AS user_extras_id, user_extras.username AS user_extras_username, user_extras.age AS user_extras_age, pet_1.id AS pet_1_id, pet_1.name AS pet_1_name, pet_1.user_id AS pet_1_user_id 
FROM users JOIN user_extras ON user_extras.username = users.username LEFT OUTER JOIN pet AS pet_1 ON users.id = pet_1.user_id
2021-11-12 14:13:56,990 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
john.doe [<__main__.Pet object at 0x7f1e33b42950>, <__main__.Pet object at 0x7f1e33b429b0>] 42
Traceback (most recent call last):
  File "/var/home/otaylor/Source/flatpak-status/sqlbug.py", line 63, in <module>
    print(extra.age)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 926, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 957, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/state.py", line 710, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1451, in load_scalar_attributes
    result = load_on_ident(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1473, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 520, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 555, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3223, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/context.py", line 645, in create_for_statement
    opt.process_compile_state(self)
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 260, in process_compile_state
    self._process(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 904, in _process
    val._bind_loader(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 1051, in _bind_loader
    entity = self._find_entity_prop_comparator(
  File "/var/home/otaylor/.local/share/virtualenvs/flatpak-status-zdA04J2s/lib64/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 1142, in _find_entity_prop_comparator
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapped attribute "User.pet" does not apply to any of the root entities in this query, e.g. mapped class UserExtra->user_extras. Please specify the full path from one of the root entities to the target attribute. 
```

### Versions

- OS: Fedora 35
- Python: 3.10.0
- SQLAlchemy: 1.4.26
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): sqlite3

**Comment by zzzeek** [comment]
this is not related to add_entity (not to be confused with with_entities(), which we had a lot of problems with).

the exception is raised if you put the entity at the top as well

```py
query_result = session.query(User, UserExtra) \
    .join(UserExtra, UserExtra.username == User.username) \
    .options(joinedload(User.pet)).all()

```

**Comment by zzzeek** [comment]
it's also not new that the options are propagated to the object, 1.3 propagates that joinedload to all of the User, UserExtra, and Pet as well.   

the regression might well be because the un-expiry handlers [run eager loaders](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#eager-loaders-emit-during-unexpire-operations) now, meaning this regression is due to #1763.

**Comment by zzzeek** [comment]
this will silence the raise when we are refreshing an object

```diff
diff --git a/lib/sqlalchemy/orm/strategy_options.py b/lib/sqlalchemy/orm/strategy_options.py
index 675c7218bd..23a8c45332 100644
--- a/lib/sqlalchemy/orm/strategy_options.py
+++ b/lib/sqlalchemy/orm/strategy_options.py
@@ -260,7 +260,8 @@ class Load(Generative, LoaderOption):
         self._process(
             compile_state,
             compile_state._lead_mapper_entities,
-            not bool(compile_state.current_path),
+            not bool(compile_state.current_path)
+            and not compile_state.compile_options._for_refresh_state,
         )
 
     def _process(self, compile_state, mapper_entities, raiseerr):

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**disable raiseerr for refresh state loader options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3321

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**disable raiseerr for refresh state loader options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3322
