### ISSUE TITLE
Crash with @declared_attr on non-trivial __mapper_args__

### ISSUE THREAD

**Issue by phy1729** [sqlalchemy/sqlalchemy#7321]
**Describe the bug**
When using `@declared_attr` on a `__mapper_args__` method with a return type annotation and non-trivial body, the plugin crashes.

**Expected behavior**
No crash.

**To Reproduce**
With test.py as
```py
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import Mapped


Base = declarative_base()


class Foo(Base):
    @declared_attr
    def __mapper_args__(
        cls,
    ) -> Mapped[dict]:
        if True:
            return {}
        else:
            return {}
```

and setup.cfg as
```ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

run
```
 python3 -m venv venv
./venv/bin/pip install 'sqlalchemy[mypy]'
./venv/bin/mypy --show-traceback test.py
```

**Error**

```
test.py:-1: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "/home/phy1729/,demo2/./venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 2697, in dispatch
    process_graph(graph, manager)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 3021, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 3119, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 2165, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 1726, in visit_class_def
    self.accept(defn.defs)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 1975, in visit_block
    self.accept(s)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1073, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2013, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2124, in check_assignment
    rvalue_type = self.check_simple_assignment(lvalue_type, rvalue, context=rvalue,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2985, in check_simple_assignment
    rvalue_type = self.expr_checker.accept(rvalue, lvalue_type,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3911, in accept
    typ = node.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1558, in accept
    return visitor.visit_call_expr(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 271, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 353, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 858, in check_call_expr_with_callee_type
    return self.check_call(callee_type, e.args, e.arg_kinds, e,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 924, in check_call
    return self.check_any_type_call(args, callee)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 2011, in check_any_type_call
    self.infer_arg_types_in_empty_context(args)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 1085, in infer_arg_types_in_empty_context
    arg_type = self.accept(arg)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3911, in accept
    typ = node.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1866, in accept
    return visitor.visit_lambda_expr(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3511, in visit_lambda_expr
    ret_type = self.accept(e.expr(), allow_none_return=True)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3900, in accept
    if node in self.type_overrides:
TypeError: unhashable type: 'list'
test.py:-1: : note: use --pdb to drop into pdb
```

**Versions.**
 - OS: Reproduced on OpenBSD and Alpine.
 - Python: Reproduced with 3.8.10, 3.8.12, and 3.9.7
 - SQLAlchemy: 1.4.27
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a19

**Additional context**
I believe the requirements to crash are

* The class must be derived from `declarative_base`.
* `@declared_attr` must be used.
* There must be a return type annotation. `dict` is sufficient (as is `typing.Dict`). The `Mapped` bit is just to kill off a warning `test.py:9: error: [SQLAlchemy Mypy plugin] Can't infer type from @declared_attr on function '__mapper_args__'; please specify a return type from this function that is one of: Mapped[<python type>], relationship[<target class>], Column[<TypeEngine>], MapperProperty[<python type>]`
* The body can't be trivial i.e. `return {}` wasn't sufficient to produce the crash.

**Have a nice day!**
:slightly_smiling_face:

**Comment by zzzeek** [comment]
oh ok, the Mapped part, which is wrong to have here but should not crash, is also a symptom of the problem that it's trying to treat this attr as mapped.

but any other attribute that is a dict shouldnt try to be treated as mapped either...

**Comment by zzzeek** [comment]
oh it's becasue of the declared attr, right.  got it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**exclude special names from @declared_attr check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3310

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**exclude special names from @declared_attr check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3311

**Comment by phy1729** [comment]
The proposed fix appears to fix the crash. However, if I add a type annotation `cls: Type['Foo']`, there's a warning
```
test.py:12: error: The erased type of self "Type[test.Foo]" is not a supertype of its class "test.Foo"
```
This warning does not appear prior to the proposed fix.

**Comment by zzzeek** [comment]
> The proposed fix appears to fix the crash. However, if I add a type annotation `cls: Type['Foo']`, there's a warning
> 
> ```
> test.py:12: error: The erased type of self "Type[test.Foo]" is not a supertype of its class "test.Foo"
> ```
> 
> This warning does not appear prior to the proposed fix.

this issue is not related to the plugin, this involves the stubs setup for the declared_attr class.   same message if you turn off the plugin and use a simple example:

```py
from typing import Any
from typing import Type
from sqlalchemy.orm import declared_attr


class Foo:
    @declared_attr
    def anything(cls: Type[Foo]) -> dict[Any, Any]:
        return {}
```

mypy will accept the class if you put classmethod on top and this seems to not interfere with declarative's work:


```py
from typing import Any
from typing import Type
from sqlalchemy.orm import declared_attr


class Foo:
    @classmethod
    @declared_attr
    def anything(cls: Type[Foo]) -> dict[Any, Any]:
        return {}
```

I dont know the correct way to make the declared_attr mimic the behavior of `@classmethod`, @CaselIT might have some ideas, but this would be on the stubs side. we can maybe look at the previous sqlalchemy-stubs package to see what they're doing.   I would also hope that there's a way to do this, i.e. that mypy isn't just hardcoding a rule for `@classmethod` specifically, but it wouldnt be the first time as they do hardcode some typing logic for things like `tuple`, where we on the outside cannot yet create tuple-like types of our own.

**Comment by phy1729** [comment]
For the first example, I see the supertype error; however, if I change `Foo` to be derived from `declarative_base()` the error goes away.
```py
from typing import Any
from typing import Type
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class Foo(Base):
    @declared_attr
    def anything(cls: Type[Foo]) -> dict[Any, Any]:
        return {}
```

Same thing for if `__foo__` is used in place of `anything`; however the error returns with the proposed fix in place.

**Comment by zzzeek** [comment]
again this is not related to the "fix", the plugin itself is interpreting "anything" as a mapped attribute, and that is handling the attribute in this case.  in the case of ``__mapper_args__`` etc these are not mapped attributes and should not be counted by the plugin as mapped, which is why it was crashing.   

turn off the plugin and your example above produces mypy errors related to Base and does not get as far as the `@declared_attr`.

**Comment by zzzeek** [comment]
ill try to modify this so that it still rewrites those lines, beacuse I think otherwise if there is no `@classmethod` then this form isn't possible w/ mypy

**Comment by zzzeek** [comment]
mypy will see them rewritten as:

   ``__mapper_args__: Any``

this is not as ideal as actually validating that these are written correctly, but it's better than a false error.

**Comment by zzzeek** [comment]
that's in the gerrit now if you want to look again

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use typing.Dict** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3323

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**use typing.Dict** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3324
