### ISSUE TITLE
dmypy incremental runs can terminate with fatal error

### ISSUE THREAD

**Issue by jaens** [sqlalchemy/sqlalchemy#7347]
### Describe the bug

Currently, running mypy in the daemon mode (ie. `dmypy`) can crash on the second run if the SQLAlchemy mypy plugin is enabled.

This is due to a `fullname` being `None` on a `Var` node, which is mandatory in the mypy incremental path in certain cases.

(see linked pull request for a fix)

In particular, it's missing on eg. the `__table__` field:

![mypy_sqlalchemy_failure_symbol_fullname](https://user-images.githubusercontent.com/639345/142690056-71725cd4-a9f7-4f44-8d5b-e2931b8ab820.png)

(also shown is the code that requires it)

### To Reproduce

1. Go to a SQLAlchemy project with the plugin enabled
2. `dmypy run .`
3. Do a code change, rerun above, or do a `dmypy suggest <some fully qualified function name>`

### Error

```
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 229, in serve
    resp = self.run_command(command, data)
  File "mypy/dmypy_server.py", line 272, in run_command
    return method(self, **data)
  File "mypy/dmypy_server.py", line 850, in cmd_suggest
    out = engine.suggest(function)
  File "mypy/suggestions.py", line 239, in suggest
    suggestion = self.get_suggestion(mod, node)
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "mypy/suggestions.py", line 266, in restore_after
    self.reload(self.graph[module])
  File "mypy/suggestions.py", line 642, in reload
    return self.fgmanager.update([(state.id, state.path)], [])
  File "mypy/server/update.py", line 264, in update
    changed_modules = propagate_changes_using_dependencies(
  File "mypy/server/update.py", line 834, in propagate_changes_using_dependencies
    triggered |= reprocess_nodes(manager, graph, id, nodes, deps, processed_targets)
  File "mypy/server/update.py", line 924, in reprocess_nodes
    old_symbols_snapshot = snapshot_symbol_table(file_node.fullname, file_node.names)
  File "mypy/server/astdiff.py", line 164, in snapshot_symbol_table
    result[name] = snapshot_definition(node, common)
  File "mypy/server/astdiff.py", line 224, in snapshot_definition
    symbol_table = snapshot_symbol_table(prefix, node.names)
  File "mypy/server/astdiff.py", line 160, in snapshot_symbol_table
    if node and get_prefix(node.fullname) != name_prefix:
  File "mypy/util.py", line 287, in get_prefix
    return fullname.rsplit('.', 1)[0]
AttributeError: 'NoneType' object has no attribute 'rsplit'
``` 

### Versions

- Python: 3.9
- SQLAlchemy: 1.4 *and* main

**Comment by zzzeek** [comment]
hey there -

Im not really sure how to use this program.  I just ran it and it took some time and then spit out another stack trace

```
Daemon crashed!
Traceback (most recent call last):
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/dmypy_server.py", line 229, in serve
    resp = self.run_command(command, data)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/dmypy_server.py", line 272, in run_command
    return method(self, **data)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/dmypy_server.py", line 331, in cmd_run
    return self.check(sources, is_tty, terminal_width)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/dmypy_server.py", line 388, in check
    res = self.initialize_fine_grained(sources, is_tty, terminal_width)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/dmypy_server.py", line 423, in initialize_fine_grained
    result = mypy.build.build(sources=sources,
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/build.py", line 2697, in dispatch
    process_graph(graph, manager)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/build.py", line 3021, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/build.py", line 3113, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 396, in refresh_partial
    self.refresh_top_level(node)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 407, in refresh_top_level
    self.accept(d)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 4874, in accept
    report_internal_error(err, self.errors.file, node.line, self.errors, self.options)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/errors.py", line 810, in report_internal_error
    raise err
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 4872, in accept
    node.accept(self)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 1056, in visit_class_def
    self.analyze_class(defn)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 1134, in analyze_class
    self.analyze_class_body_common(defn)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 1143, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/home/classic/.venv3100/lib/python3.10/site-packages/mypy/semanal.py", line 1203, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/mypy/plugin.py", line 258, in _base_cls_hook
    decl_class.scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/mypy/decl_class.py", line 106, in scan_declarative_assignments_and_apply_types
    apply.add_additional_orm_attributes(cls, api, mapped_attributes)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/mypy/apply.py", line 273, in add_additional_orm_attributes
    _apply_placeholder_attr_to_class(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/mypy/apply.py", line 290, in _apply_placeholder_attr_to_class
    assert isinstance(sym.node, TypeInfo)
AssertionError
```

and i dont even know what it was looking at, that's in the SQLAlchemy source directory so...I guess it was scanning every file?  im not really sure what it's doing.

so...I dont really know how to write tests for this, we cant (or more like, we should really really try not to) commit changes that have no tests.    we do testing for mypy incremental mode right now by putting files with changes in them into https://github.com/sqlalchemy/sqlalchemy/tree/main/test/ext/mypy/incremental .   but it looks like there's a lot of problems here, not just the one you found.

do you have insight on how i can get dmypy to act more deterministically?

**Comment by jaens** [comment]
dmypy is the daemon version of mypy to make it faster, which eg. the VSCode plugin for MyPy and such use.

Unfortunately I can't comment on the internals of it, figuring this bug out was as far as I got.

The `Var` class that the SA plugin uses seems to be undocumented, but one of the invariants seems to be that it should have `fullname` set, and basically almost all code that works on it indeed does that.

I'm not sure how one would have a test for an undocumented invariant that could basically cause some random thing to break if it's violated, as even if there was a repro, another similar bug could happen somewhere else... 

I'd say it's only really truly fixable by either:
* mypy's side having the invariants statically or dynamically enforced (so the problem would surface earlier)
* not using internal undocumented APIs (that's just impossible though)

**Comment by jaens** [comment]
There's some funky stuff going on with that `Var` class field:

```python
  # TODO: Should be Optional[str]
  self._fullname = cast('Bogus[str]', None)  # Name with module prefix
```

so someone *has* thought that it needs to be `Optional`, but they couldn't make it so (probably because plenty of code depends on it...)

**Comment by zzzeek** [comment]
we will probably push this change but one way it could be tested is if you had a repro where you:

1. run mypy on a .py file
2. change the file
3. run mypy again, where it will use the cached inforamtion and hit this same crash

that's the kind of tests we have in the above mentioned directory.

**Comment by zzzeek** [comment]
it can involve multiple files too.  we hvae repros that work that way in the test suite.

**Comment by jaens** [comment]
I actually didn't even need to change the code to get it to crash, just force a recheck somehow.

Unless there's an automatic tool to extract a testcase from 10k lines of code I don't think I'll be having a repro though.

**Comment by RomainJamet** [comment]
Bump: same issue here drove me insane, jaens' fix worked.

**Comment by zzzeek** [comment]
curious does https://gitter.im/sqlalchemy/devel?at=61d369597842bd3ca92a8005 look like the same error ?

**Comment by RomainJamet** [comment]
@zzzeek I don't get a crash in this file, but it sure seems related. The fix pointed out by @jaens (and apparently suggested by Github's AI?) is simply adding `var._fullname = cls.fullname + "." + attrname` in the file `sqlalchemy\ext\mypy\apply.py`. I did that change locally in my env version of sqlalchemy and it works, the mypy daemon ceased to crash on every second iteration. I didn't had to change anything else.

For the record, here is my dmypy crash log, with mypy 0.930, the stubs and plugin set-up but without the aforementionioned fix
```
Daemon crashed!
Traceback (most recent call last):
  File "mypy\dmypy_server.py", line 229, in serve
  File "mypy\dmypy_server.py", line 272, in run_command
  File "mypy\dmypy_server.py", line 331, in cmd_run
  File "mypy\dmypy_server.py", line 393, in check
  File "mypy\dmypy_server.py", line 568, in fine_grained_increment_follow_imports
  File "mypy\server\update.py", line 245, in update
  File "mypy\server\update.py", line 328, in update_one
  File "mypy\server\update.py", line 388, in update_module
  File "mypy\server\astdiff.py", line 164, in snapshot_symbol_table
  File "mypy\server\astdiff.py", line 224, in snapshot_definition
  File "mypy\server\astdiff.py", line 160, in snapshot_symbol_table
TypeError: str object expected; got None
```

To trigger it, I use the [VS Code mypy extension](https://marketplace.visualstudio.com/items?itemName=matangover.mypy) that runs dmypy, I save a file once after the daemon launches, it works, then I edit anything (like a string) and save again, then this occurs. I guess the same result could be obtained running the dmypy daemon independently but I haven't tried it.

Now it could be that the _fullname member should be marked optional if it is, I am rather new to using Python for web apps and mypy. All that I can tell is that defining it seems to fix the issue. I'll see if I can set-up a github with the issue replicated today...

**Comment by CaselIT** [comment]
@zzzeek I think we could just merge the PR

**Comment by RomainJamet** [comment]
Here you go @zzzeek 
https://github.com/RomainJamet/sqlalchemy-mypy-crash

Merging jaens' PR would be nice though, I'm still in dev phase of my project so using the fix locally works out but having that fix on the official package would greatly help my prod release later ☺

**Comment by zzzeek** [comment]
> @zzzeek I think we could just merge the PR

sure, if we can put it throguh with a 1.4 backport + changelog note

**Comment by sqla-tester** [comment]
**Jaen Saul** has proposed a fix for this issue in the **rel_1_4** branch:

**fix(mypy): Placeholder vars should have fullname set** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482

**Comment by CaselIT** [comment]
> > @zzzeek I think we could just merge the PR
> 
> sure, if we can put it throguh with a 1.4 backport + changelog note

The pr seems to already target 1.4 so we should forwardport to main instead

**Comment by zzzeek** [comment]
not my preference but whatever works

**Comment by sqla-tester** [comment]
**Jaen Saul** has proposed a fix for this issue in the **main** branch:

**fix(mypy): Placeholder vars should have fullname set.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3526

**Comment by sqla-tester** [comment]
**Jaen Saul** has proposed a fix for this issue in the **rel_1_4** branch:

**fix(mypy): Placeholder vars should have fullname set.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482
