### ISSUE TITLE
include_columns feature for indexes does not round trip, entry is in the wrong place

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7382]
### Describe the bug

I'm noticing that the include columns feature added in 1a08d1aade0 puts a new entry "include_columns" directly in the index reflection dict, and does not put it in dialect_options where it should be.  this means a reflection of these entries won't round-trip correctly and there does not seem to be a test for this.  

### To Reproduce

```python
diff --git a/lib/sqlalchemy/dialects/postgresql/base.py b/lib/sqlalchemy/dialects/postgresql/base.py
index 614c84b56e..85e3b741a7 100644
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -4242,6 +4242,7 @@ class PGDialect(default.DefaultDialect):
                 "column_names": [idx["cols"][i] for i in idx["key"]],
             }
             if self.server_version_info >= (11, 0):
+                # TODO: this is legacy, this is part of dialect_options now
                 entry["include_columns"] = [idx["cols"][i] for i in idx["inc"]]
             if "duplicates_constraint" in idx:
                 entry["duplicates_constraint"] = idx["duplicates_constraint"]
@@ -4250,6 +4251,10 @@ class PGDialect(default.DefaultDialect):
                     (idx["cols"][idx["key"][i]], value)
                     for i, value in idx["sorting"].items()
                 )
+            if "include_columns" in entry:
+                entry.setdefault("dialect_options", {})[
+                    "postgresql_include"
+                ] = entry["include_columns"]
             if "options" in idx:
                 entry.setdefault("dialect_options", {})[
                     "postgresql_with"
diff --git a/lib/sqlalchemy/testing/suite/test_reflection.py b/lib/sqlalchemy/testing/suite/test_reflection.py
index ba176bcd91..c7f78c6e47 100644
--- a/lib/sqlalchemy/testing/suite/test_reflection.py
+++ b/lib/sqlalchemy/testing/suite/test_reflection.py
@@ -1264,10 +1264,19 @@ class ComponentReflectionTestExtra(fixtures.TestBase):
                     "column_names": ["x"],
                     "include_columns": ["y"],
                     "unique": False,
+                    "dialect_options": {
+                        "%s_include" % connection.engine.name: ["y"]
+                    }
                 }
             ],
         )
 
+        t2 = Table("t", MetaData(), autoload_with=connection)
+        eq_(
+            list(t2.indexes)[0].dialect_options[connection.engine.name]["include"],
+            ["y"],
+        )
+
     def _type_round_trip(self, connection, metadata, *types):
         t = Table(
             "t",
```

### Error

```
_______________________________________ ComponentReflectionTestExtra_postgresql+psycopg2_13_4.test_reflect_covering_index _______________________________________
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/suite/test_reflection.py", line 1272, in test_reflect_covering_index
    eq_(
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 237, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: None != ['y']
assert None == ['y']
  +None
  -['y']
``` 

### Versions

etc

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Fixed reflection of covering indexes to** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3416

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Reflect included columns as dialect_options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3436

**Comment by CaselIT** [comment]
gonna remove this for 2.1
