### ISSUE TITLE
Misleading error when greenlet is incorrectly installed

### ISSUE THREAD

**Issue by reslario** [sqlalchemy/sqlalchemy#7419]
### Describe the bug

When SQLAlchemy fails to import the greenlet library, it raises an exception saying "the greenlet library is required to use this function" every time you try to use functionality that depends on it.

This makes it seem like the library is missing, but in my case, it wasn't:

```shell
$ pip show greenlet
Name: greenlet
Version: 1.1.0
Summary: Lightweight in-process concurrent programming
Home-page: https://greenlet.readthedocs.io/
Author: 
Author-email: 
License: MIT License
Location: [path]/venv/lib/python3.9/site-packages
Requires: 
Required-by:
```

The issue was rather that greenlet was installed with the wrong architecture:
```shell
$ python -c "import greenlet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[path]/venv/lib/python3.9/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen([path]/venv/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        [path]/venv/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so: mach-o, but wrong architecture
       [path]/venv/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so: mach-o, but wrong architecture
```

This caused me some confusion until I'd discovered the problem, as the library seemed to be installed, but SQLAlchemy's error suggested it wasn't.
It would be nice if the reason for the import failing was included with the error that is currently raised.

### To Reproduce

```python
# any code using SQLAlchemy that depends on greenlet functionality
```

### Error

```
Traceback (most recent call last):
  File "[path]/venv/lib/python3.9/site-packages/quart/asgi.py", line 311, in __call__
    await self.app.startup()
  File "[path]/venv/lib/python3.9/site-packages/quart/app.py", line 1755, in startup
    await self.ensure_async(func)()
  File "[path]/api.py", line 35, in initialize
    app.database = create_async_engine(
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 40, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 672, in create_engine
    event.listen(pool, "connect", on_connect)
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/event/api.py", line 115, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 232, in listen
    self.dispatch_target.dispatch._listen(self, *args, **kw)
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/pool/events.py", line 63, in _listen
    event_key.base_listen(**kw)
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 270, in base_listen
    for_modify._set_asyncio()
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 274, in _set_asyncio
    self._exec_once_mutex = AsyncAdaptedLock()
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 63, in AsyncAdaptedLock
    _not_implemented()
  File "[path]/venv/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 46, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[path]/server.py", line 7, in <module>
    asyncio.run(serve(app, Config()))
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "[path]/venv/lib/python3.9/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "[path]/venv/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 63, in worker_serve
    raise exception
  File "[path]/venv/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 32, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "[path]/venv/lib/python3.9/site-packages/hypercorn/utils.py", line 246, in invoke_asgi
    await app(scope, receive, send)
  File "[path]/venv/lib/python3.9/site-packages/quart/app.py", line 1722, in __call__
    await self.asgi_app(scope, receive, send)
  File "[path]/venv/lib/python3.9/site-packages/quart/app.py", line 1748, in asgi_app
    await asgi_handler(receive, send)
  File "[path]/venv/lib/python3.9/site-packages/quart/asgi.py", line 313, in __call__
    await send(
  File "[path]/venv/lib/python3.9/site-packages/hypercorn/asyncio/lifespan.py", line 82, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'the greenlet library is required to use this function.'
``` 

### Versions

- OS: MacOS Big Sur 11.5.1 (Apple M1 chip)
- Python: 3.9.9
- SQLAlchemy: 1.4.27
- Database: irrelevant
- DBAPI: irrelevant

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Include import error message when greenlet is not installed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3362

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Include import error message when greenlet is not installed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3363

**Comment by CaselIT** [comment]
thanks for reporting
