### ISSUE TITLE
AttributeError when querying using a `hybrid_property` in a `relationship.any` for polymorphic classes with `with_polymorphic` set

### ISSUE THREAD

**Issue by sjhewitt** [sqlalchemy/sqlalchemy#7425]
### Describe the bug

When trying add a `hybrid_property` as a query filter to a `relationship.any` where the relationship is to a polymorphic class with `with_polymorphic`, I am getting the following error:

The error isn't present when putting the filter explicitly in the `relationship.any` call, or if the polymorphic class has the `with_polymorphic` option removed.

### To Reproduce

```python
from sqlalchemy import Column, ForeignKey, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()
engine = create_engine("sqlite://", echo=True)


class A(Base):
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)

    bs = relationship("B", back_populates="a", lazy="joined")


class B(Base):
    __tablename__ = "poly"
    __mapper_args__ = {
        "polymorphic_on": "type",
        # if with_polymorphic is removed, Query 2 below works.
        "with_polymorphic": "*",
    }
    name = Column(String, primary_key=True)
    type = Column(String)
    a_id = Column(ForeignKey(A.id))

    a = relationship(A, back_populates="bs")

    @hybrid_property
    def is_foo(self):
        return self.name == "foo"


Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
Session = sessionmaker(engine)
session = Session()
session.add(A(bs=[B(name="foo"), B(name="bar")]))
session.commit()


# Query 1 - works:
session.query(A).filter(A.bs.any(B.name == "foo")).all()

# Query 2 - doesn't work:
session.query(A).filter(A.bs.any(B.is_foo)).all()
```

### Error

```python
Traceback (most recent call last):
  File "lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 589, in __getattr__
    return getattr(descriptor, attribute)
AttributeError: 'hybrid_property' object has no attribute 'impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 843, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'impl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 609, in __getattr__
    return getattr(comparator, attribute)
  File "lib/python3.10/site-packages/sqlalchemy/ext/hybrid.py", line 1178, in __getattr__
    return getattr(self.expression, key)
  File "lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 845, in __getattr__
    util.raise_(
  File "lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
AttributeError: Neither 'BinaryExpression' object nor 'Comparator' object has an attribute 'impl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqlatest.py", line 45, in <module>
    session.query(A).filter(A.bs.any(B.is_foo)).all()
  File "lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 546, in any
    return self.operate(PropComparator.any_op, criterion, **kwargs)
  File "lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 317, in operate
    return op(self.comparator, *other, **kwargs)
  File "lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 466, in any_op
    return a.any(b, **kwargs)
  File "lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1459, in any
    return self._criterion_exists(criterion, **kwargs)
  File "lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1381, in _criterion_exists
    criterion = target_adapter.traverse(criterion)
  File "lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 619, in traverse
    return replacement_traverse(obj, self.__traverse_options__, replace)
  File "lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 848, in replacement_traverse
    obj = clone(
  File "lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 843, in clone
    cloned[id_elem] = newelem = elem._clone(**kw)
  File "lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 307, in _clone
    impl=self.impl,
  File "lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 611, in __getattr__
    util.raise_(
  File "lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
AttributeError: Neither 'hybrid_property' object nor 'ExprComparator' object associated with B.is_foo has an attribute 'impl'
``` 

### Versions

- OS: Arch / Ubuntu
- Python: 3.10
- SQLAlchemy: 1.4.27
- Database: sqlite / postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): sqlite, psycopg2

**Comment by zzzeek** [comment]
hi -

unfortunately no timeline for a fix.   you will need to find another way to solve your problem for now.

**Comment by zzzeek** [comment]
I can release this for 1.4.28 today if you can confirm this patch fully solves your issue:

```diff
diff --git a/lib/sqlalchemy/orm/attributes.py b/lib/sqlalchemy/orm/attributes.py
index b66d552507..de62b5b9f7 100644
--- a/lib/sqlalchemy/orm/attributes.py
+++ b/lib/sqlalchemy/orm/attributes.py
@@ -571,6 +571,16 @@ def create_proxied_attribute(descriptor):
                 adapt_to_entity,
             )
 
+        def _clone(self, **kw):
+            return self.__class__(
+                self.class_,
+                self.key,
+                self.descriptor,
+                self._comparator,
+                adapt_to_entity=self._adapt_to_entity,
+                original_property=self.original_property
+            )
+
         def __get__(self, instance, owner):
             retval = self.descriptor.__get__(instance, owner)
             # detect if this is a plain Python @property, which just returns
```

**Comment by zzzeek** [comment]
like, in the next hour, otherwise 1.4.28 has to go out

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement attributes.Proxy._clone()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3358

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**implement attributes.Proxy._clone()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3359

**Comment by sjhewitt** [comment]
Testing it now

**Comment by zzzeek** [comment]
thanks!  i was literally in the middle of releaseing 1.4.28 when this came in.

**Comment by zzzeek** [comment]
also was not as hard as it looked

**Comment by sjhewitt** [comment]
@zzzeek  can confirm it fixes my MCV code and the issue in my larger codebase. Thanks for the rapid fix!

**Comment by zzzeek** [comment]
woop
