### ISSUE TITLE
RecursionError creating engine URL with query from Python2 unicode string

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7446]
from #7445 ,  confirmed this doesn't occur in 1.3, so is a 1.4 regression

```py
[classic@photon3 sqlalchemy:rel_1_4]$ python2
Python 2.7.18 (default, Sep 17 2021, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy.engine import make_url
>>> make_url(u'mysql+mysqldb://user:password@localhost/foo?charset=utf8mb4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 731, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 789, in _parse_rfc1738_args
    return URL.create(name, **components)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 153, in create
    cls._str_dict(query),
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 210, in _str_dict
    for key, value in dict_items
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 210, in <dictcomp>
    for key, value in dict_items
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 188, in _assert_value
    return tuple(_assert_value(elem) for elem in val)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 188, in <genexpr>
    return tuple(_assert_value(elem) for elem in val)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 188, in _assert_value

..

 File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 188, in <genexpr>
    return tuple(_assert_value(elem) for elem in val)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/engine/url.py", line 187, in _assert_value
    elif isinstance(val, collections_abc.Sequence):
  File "/usr/lib64/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "/usr/lib64/python2.7/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**check for string_types, not str, for py2 support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3401

**Comment by CaselIT** [comment]
was fixed. this is 1_4 only since main no longer support py2
