### ISSUE TITLE
test/sql/test_compare.py::CompareAndCopyTest::test_all_present fails on armvhl, aarch64, s390x

### ISSUE THREAD

**Issue by nphilipp** [sqlalchemy/sqlalchemy#7450]
### Describe the bug

I attempted to build SQLAlchemy 1.4.28 on Fedora 35 and Rawhide, but the builds failed because the test suite reliably failed on armvhl, aarch64, s390x in `test/sql/test_compare.py::CompareAndCopyTest::test_all_present`.

### To Reproduce

```python
# In the source tree (from tarball or the rel_1_4 branch) on a machine of an affected architecture, build sqlalchemy and run pytest twice(!) on a certain subset of tests:

[nphilipp@aarch64-test01 sqlalchemy][PROD]$ python3 setup.py build

...

[nphilipp@aarch64-test01 sqlalchemy][PROD]$ PYTHONPATH=. python3 -m pytest test/sql/test_c* -x 

... [ succeeds! ]

[nphilipp@aarch64-test01 sqlalchemy][PROD]$ PYTHONPATH=. python3 -m pytest test/sql/test_c* -x 
======================================== test session starts =========================================
platform linux -- Python 3.10.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/fedora/nphilipp/src/sqlalchemy, configfile: setup.cfg
plugins: xdist-2.3.0, forked-1.3.0
collected 478 items                                                                                  

test/sql/test_case_statement.py::CaseTest::test_case PASSED                                    [  0%]
test/sql/test_case_statement.py::CaseTest::test_literal_interpretation_one PASSED              [  0%]
test/sql/test_case_statement.py::CaseTest::test_literal_interpretation_three PASSED            [  0%]
test/sql/test_case_statement.py::CaseTest::test_literal_interpretation_two PASSED              [  0%]
test/sql/test_case_statement.py::CaseTest::test_literal_interpretation_two_point_five PASSED   [  1%]
test/sql/test_case_statement.py::CaseTest::test_text_doenst_explode_even_in_whenlist PASSED    [  1%]
test/sql/test_case_statement.py::CaseTest::test_text_doesnt_explode PASSED                     [  1%]
test/sql/test_case_statement.py::CaseTest::test_when_dicts[<lambda>-CASE WHEN (test.col1 = :col1_1) THEN :param_1 ELSE :param_2 END] PASSED [  1%]
test/sql/test_case_statement.py::CaseTest::test_when_dicts[<lambda>-CASE WHEN (test.col1 = :col1_1) THEN :param_1 WHEN (test.col1 = :col1_2) THEN :param_2 ELSE :param_3 END] PASSED [  1%]
test/sql/test_case_statement.py::CaseTest::test_when_dicts[<lambda>-CASE test.col1 WHEN :param_1 THEN :param_2 END] PASSED [  2%]
test/sql/test_case_statement.py::CaseTest::test_when_dicts[<lambda>-CASE test.col1 WHEN :param_1 THEN :param_2 WHEN :param_3 THEN :param_4 END] PASSED [  2%]
test/sql/test_compare.py::CacheKeyTest::test_bindparam_subclass_nocache PASSED                 [  2%]
test/sql/test_compare.py::CacheKeyTest::test_bindparam_subclass_ok_cache PASSED                [  2%]
test/sql/test_compare.py::CacheKeyTest::test_cache_key PASSED                                  [  2%]
test/sql/test_compare.py::CacheKeyTest::test_cache_key_equal PASSED                            [  3%]
test/sql/test_compare.py::CacheKeyTest::test_cache_key_no_method PASSED                        [  3%]
test/sql/test_compare.py::CacheKeyTest::test_cache_key_unknown_traverse PASSED                 [  3%]
test/sql/test_compare.py::CacheKeyTest::test_copy_internals_no_method PASSED                   [  3%]
test/sql/test_compare.py::CacheKeyTest::test_dml_not_cached_yet[dml_stmt0] PASSED              [  3%]
test/sql/test_compare.py::CacheKeyTest::test_dml_not_cached_yet[dml_stmt1] PASSED              [  4%]
test/sql/test_compare.py::CacheKeyTest::test_dml_not_cached_yet[dml_stmt2] PASSED              [  4%]
test/sql/test_compare.py::CacheKeyTest::test_generative_cache_key_regen PASSED                 [  4%]
test/sql/test_compare.py::CacheKeyTest::test_generative_cache_key_regen_w_del PASSED           [  4%]
test/sql/test_compare.py::CacheKeyTest::test_get_children_no_method PASSED                     [  5%]
test/sql/test_compare.py::CacheKeyTest::test_literal_binds PASSED                              [  5%]
test/sql/test_compare.py::CacheKeyTest::test_values_doesnt_caches_right_now PASSED             [  5%]
test/sql/test_compare.py::CompareAndCopyTest::test_all_present FAILED                          [  5%]

============================================== FAILURES ==============================================
________________________________ CompareAndCopyTest.test_all_present _________________________________
Traceback (most recent call last):
  File "/home/fedora/nphilipp/src/sqlalchemy/test/sql/test_compare.py", line 1382, in test_all_present
    is_false(bool(need), "%d Remaining classes: %r" % (len(need), need))
  File "/home/fedora/nphilipp/src/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 274, in is_false
    is_(bool(a), False, msg=msg)
  File "/home/fedora/nphilipp/src/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 279, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: 1 Remaining classes: {<class 'test.sql.test_compare.CacheKeyTest.test_get_children_no_method.<locals>.Foobar2'>}
assert True is False
====================================== short test summary info =======================================
FAILED test/sql/test_compare.py::CompareAndCopyTest::test_all_present - AssertionError: 1 Remaining...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================== 1 failed, 26 passed in 1.61s ====================================
[nphilipp@aarch64-test01 sqlalchemy][PROD]$
```

### Error

From the [build log](https://koji.fedoraproject.org/koji/taskinfo?taskID=79808940) for Fedora 35 on s390x:

```
...
=================================== FAILURES ===================================
_____________________ CompareAndCopyTest.test_all_present ______________________
[gw1] linux -- Python 3.10.0 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.4.28/test/sql/test_compare.py", line 1382, in test_all_present
    is_false(bool(need), "%d Remaining classes: %r" % (len(need), need))
  File "/builddir/build/BUILD/SQLAlchemy-1.4.28/test/../lib/sqlalchemy/testing/assertions.py", line 274, in is_false
    is_(bool(a), False, msg=msg)
  File "/builddir/build/BUILD/SQLAlchemy-1.4.28/test/../lib/sqlalchemy/testing/assertions.py", line 279, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: 3 Remaining classes: {<class 'test.sql.test_compare.CacheKeyTest.test_get_children_no_method.<locals>.Foobar2'>, <class 'test.sql.test_compare.CacheKeyTest.test_copy_internals_no_method.<locals>.Foobar2'>, <class 'test.sql.test_compare.CacheKeyTest.test_bindparam_subclass_nocache.<locals>._literal_bindparam'>}
assert True is False
=========================== short test summary info ============================
...
``` 

### Versions

- OS: Fedora 35 and Rawhide
- Python: 3.10.0 and 3.10.1
- SQLAlchemy: 1.4.28
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

Failed Fedora builds:

- Rawhide [build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1865779) and [corresponding task](https://koji.fedoraproject.org/koji/taskinfo?taskID=79832478)
- Fedora 35 [build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1865780) and [corresponding task](https://koji.fedoraproject.org/koji/taskinfo?taskID=79808922)

I bisected the issue and this was the first commit with which I could reproduce the error:

```
commit 8d5ed4c39eed6a13397f43159278138bbe1a4a1b
Author: Mike Bayer <mike_mp@zzzcomputing.com>
Commit: Mike Bayer <mike_mp@zzzcomputing.com>

    Warn when caching is disabled / document
    ...
```

This chunk seems to be the change that triggers this behavior compared to previous versions:

```
@@ -1356,6 +1364,7 @@ class CompareAndCopyTest(CoreFixtures, fixtures.TestBase):
             and (
                 "__init__" in cls.__dict__
                 or issubclass(cls, AliasedReturnsRows)
+                or "inherit_cache" not in cls.__dict__
             )
             and not issubclass(cls, (Annotated))
             and "orm" not in cls.__module__
```

Looking at the classes reported when the test fails, they all seem to be ephemeral ones which are defined inside a test method – and this is were it gets speculative: I think these class objects still exist by the time `test_all_present()` is run, because for some reason or another they aren’t garbage-collected and therefore still show up in the subclass hierarchy of `ClauseElement` which disrupts the test. I don't know if the late garbage-collection hints at a problem in the Python interpreter on these architectures, but regardless of that, it's easy to fix that (or work around it) with a single liner fix in the test to ignore classes which are defined in a module located in `test/`, which I'll submit as a PR.

**Comment by CaselIT** [comment]
Hi.

That's strange since the ci does run arm builds (using emulation via qemu) and we do not seem to have issues there:
https://github.com/sqlalchemy/sqlalchemy/blob/04421c8bed9e93a625b7164e99eb1ee0395bebfe/.github/workflows/run-test.yaml#L86-L121

Not sure if it's something local to fedora.

**Comment by zzzeek** [comment]
@CaselIT I think it might just be an issue of the order in which tests run, in any case, yes I changed that logic and yes it should definitely not be catching ephemeral classes.  I opened that test up a bit as we were not testing the caching on a good number of constructs in the dialects.

**Comment by sqla-tester** [comment]
**Nils Philippsen** has proposed a fix for this issue in the **main** branch:

**Ignore ephemeral classes in test_all_present()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3404

**Comment by sqla-tester** [comment]
**Nils Philippsen** has proposed a fix for this issue in the **rel_1_4** branch:

**Ignore ephemeral classes in test_all_present()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3407
