### ISSUE TITLE
MariaDB pool_pre_ping not refreshing connection

### ISSUE THREAD

**Issue by dferreruw** [sqlalchemy/sqlalchemy#7457]
### Describe the bug

When I use `pool_pre_ping=True` with `mariadbconnector` DBAPI and a stale connection, SQLAlchemy raises a "Server has gone away" (or similar) error rather than refreshing the connection.

### To Reproduce

```python
# Running MariaDB server via: docker run --env MARIADB_ROOT_PASSWORD=password -p 3307:3306 mariadb:10.6.5
# And MariaDB client installed locally via "brew install mariadb"

import time

import mariadb
import sqlalchemy

engine = sqlalchemy.create_engine(
    "mariadb+mariadbconnector://root:password@127.0.0.1:3307",
    pool_size=1,
    pool_pre_ping=True
)
with engine.connect() as conn:
    conn.execute("SET wait_timeout=2")  # Short timeout for quick stale connections.
    conn.execute("SELECT 1")
    time.sleep(4)  # Wait for server to close the connection.
    conn.execute("SELECT 1")  # This throws the error.
```

### Error

```
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
mariadb.InterfaceError: Server has gone away

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 966, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
mariadb.InterfaceError: Server has gone away

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dferrer/code/mariadb_connector_test.py", line 44, in <module>
    connection.execute("SELECT 1")
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1274, in execute
    return self._exec_driver_sql(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2021, in _handle_dbapi_exception
    self._autorollback()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 84, in __exit__
    compat.raise_(value, with_traceback=traceback)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2021, in _handle_dbapi_exception
    self._autorollback()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1096, in _autorollback
    self._rollback_impl()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 968, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1928, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 966, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.InterfaceError: (mariadb.InterfaceError) Server has gone away
(Background on this error at: https://sqlalche.me/e/14/rvf5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
mariadb.InterfaceError: Server has gone away
Traceback (most recent call last):
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
mariadb.InterfaceError: Server has gone away

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 966, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
mariadb.InterfaceError: Server has gone away

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dferrer/code/mariadb_connector_test.py", line 44, in <module>
    connection.execute("SELECT 1")
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1274, in execute
    return self._exec_driver_sql(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2021, in _handle_dbapi_exception
    self._autorollback()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 84, in __exit__
    compat.raise_(value, with_traceback=traceback)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2021, in _handle_dbapi_exception
    self._autorollback()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1096, in _autorollback
    self._rollback_impl()
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 968, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1928, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 966, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/dferrer/miniconda3/envs/mariadbconnector_test/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.InterfaceError: (mariadb.InterfaceError) Server has gone away
(Background on this error at: https://sqlalche.me/e/14/rvf5)
``` 

### Versions

- OS: macOS Big Sur
- Python: 3.9.7
- SQLAlchemy: 1.4.28
- Database: MariaDB 10.6.5
- DBAPI: mariadbconnector

### Additional context

Hi, thanks for a great library! SQLAlchemy is a pleasure to work with.

I tracked this down to the `is_disconnect` method of `mariadbconnector`: https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/mariadbconnector.py#L108. This method first calls the [base is_disconnect](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/base.py#L2545) method, which checks for disconnect error codes in the case of `OperationalError` or `ProgrammingError`. The MySQL DBAPIs raise those error classes on disconnect, but the `mariadbconnector` DBAPI raises an `InterfaceError`. Maybe [this](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/mariadbconnector.py#L114-L115) could be updated to check if `e.errno` is one of the disconnect error codes?

**Comment by zzzeek** [comment]
hey there -

so a couple of things, I was about to convert this issue to discussion because the test case is wrong; it's not expected that pre_ping can re-connect mid-transaction like that.

however, separately it looks like we are not catching the current disconnect error for mariadbconnector, for this particular case, as mariadbconnector seems to have started using a different exception class.

the test you have above will **continue to not pass** when this bug is fixed.  The correct test which **will pass** and **passes for other MySQL / MariaDB drivers** is below

```py

import time

import sqlalchemy
from sqlalchemy import text


engine = sqlalchemy.create_engine(
    "mariadb+mariadbconnector://scott:tiger@localhost/test",

    # other drivers work fine
    "mysql://scott:tiger@localhost/test",
    pool_size=1,
    pool_pre_ping=True
)
with engine.connect() as conn:
    conn.execute(text("SET wait_timeout=2"))  # Short timeout for quick stale connections.
    conn.execute(text("SELECT 1"))


time.sleep(4)  # Wait for server to close the connection.

with engine.connect() as conn:  # pre_ping + reconnect happens here
    conn.execute(text("SELECT 1"))
```

**Comment by zzzeek** [comment]
this is the patch in case you feel like independently confirming; our test suite tests for disconnects but only those that are generated from calling .close() on the connection right now, so I'm confirming this fix only from the perspective of running the above test case

```diff
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index fef1ec81a5..fcffff0ebd 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -2540,7 +2540,12 @@ class MySQLDialect(default.DefaultDialect):
 
     def is_disconnect(self, e, connection, cursor):
         if isinstance(
-            e, (self.dbapi.OperationalError, self.dbapi.ProgrammingError)
+            e,
+            (
+                self.dbapi.OperationalError,
+                self.dbapi.ProgrammingError,
+                self.dbapi.InterfaceError,
+            ),
         ):
             return self._extract_error_code(e) in (
                 1927,

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include InterfaceError for mariadb disconnect check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3408

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**include InterfaceError for mariadb disconnect check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3409

**Comment by dferreruw** [comment]
Thanks! Confirming that my service no longer throws disconnect errors when I apply this patch.
