### ISSUE TITLE
"SELECT statement has a cartesian product" warning printed

### ISSUE THREAD

**Issue by chiq-dror** [sqlalchemy/sqlalchemy#7507]
### Describe the bug

When accessing a field of an ORM instance with multiple levels of inheritance and a polymorphic identity, the resulting SELECT statement has a cartesian product, even though this could be avoided using the inheritance's foreign key constraints.

As far as I can tell, this only happens if the class structure is at least A -> B -> C -> D, where C doesn't have any fields but B and D have.
In such a case, the select statement only contains B and D, which don't have a direct foreign key relationship between them, which causes the catesian product warning to be printed.

### To Reproduce

```python
from sqlalchemy import Column, String, ForeignKey, Integer
from sqlalchemy.future import create_engine
from sqlalchemy.orm import declarative_base, Session, relationship

engine = create_engine("sqlite+pysqlite:///:memory:", future=True)
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    a = Column(String, nullable=False)
    type_ = Column(String)
    __mapper_args__ = {'polymorphic_on': type_, 'polymorphic_identity': 'a'}


class B(A):
    __tablename__ = 'b'
    __mapper_args__ = {'polymorphic_identity': 'b'}

    id = Column(Integer, ForeignKey('a.id'), primary_key=True)
    b = Column(String, nullable=False)


class C(B):
    __tablename__ = 'c'
    __mapper_args__ = {'polymorphic_identity': 'c'}

    id = Column(Integer, ForeignKey('b.id'), primary_key=True)


class D(C):
    __tablename__ = 'd'
    __mapper_args__ = {'polymorphic_identity': 'd'}

    id = Column(Integer, ForeignKey('c.id'), primary_key=True)
    c = Column(String, nullable=False)


Base.metadata.create_all(engine)
with Session(engine) as session:
    session.add(D(a='x', b='y', c='z'))
    session.commit()

with Session(engine) as session:
    d: D = session.query(A).one()
    print(d.c)
```

### Error

Traceback (most recent call last):
  File "/home/dror/.config/JetBrains/PyCharmCE2021.3/scratches/scratch_152.py", line 48, in <module>
    print(d.c)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 480, in __get__
    return self.impl.get(state, dict_)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 926, in get
    value = state._load_expired(state, passive)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 675, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1386, in load_scalar_attributes
    result = load_on_ident(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 374, in load_on_ident
    return load_on_pk_identity(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 531, in load_on_pk_identity
    session.execute(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1443, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 551, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 586, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 770, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3325, in _compiler_dispatch
    return compiler.process(compile_state.statement, **kw)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3135, in visit_select
    text = self._compose_select_body(
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3295, in _compose_select_body
    from_linter.warn()
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 362, in warn
    util.warn(message)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1621, in warn
    _warnings_warn(msg, exc.SAWarning)
  File "/home/dror/.virtualenvs/chiqchuq/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1658, in _warnings_warn
    warnings.warn(message, category, stacklevel=stacklevel + 1)
sqlalchemy.exc.SAWarning: SELECT statement has a cartesian product between FROM element(s) "b" and FROM element "d".  Apply join condition(s) between each element to resolve.

### Versions

- OS: ubuntu 20.04
- Python: 3.9.9
- SQLAlchemy: 1.4.15
- Database: sqlite+pysqlite:///:memory:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

**Comment by zzzeek** [comment]
that's a fascinating issue because there isn't actually a cartesian product, the query is "safe" because an identifier is sent for both 'b' and 'd', but the cartesian warning doesn't attempt to pick up on that particular artifact (which it shouldn't).   1.3 does the same thing but we didnt have the warning built in.

i think in this case it's best that the query bring in the "c" table even though it is not strictly necessary.   

do you have a real world use case of this structure?  what is the purpose of the "c" table that has no columns?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include empty intermediary tables in optimized get** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3433

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**include empty intermediary tables in optimized get** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3434

**Comment by chiq-dror** [comment]
> do you have a real world use case of this structure? what is the purpose of the "c" table that has no columns?

It's only for relationships.
Let's say I have the class _Book_, and the classes _ChildrenBook_ and _Dictionary_.
If I want to have in my _DepartmentStore_ class a list of all non-standard books, the only way to do it afaik is to have a _NonStandardBook_ class that inherits from _Book_ and both classes inherit from it.
This class of course won't necessarily have any columns.
