### ISSUE TITLE
__dict__ does not contain @hybrid_property

### ISSUE THREAD

**Issue by rajatgng** [sqlalchemy/sqlalchemy#7510]
### Issue

When using @hybrid_property, that property doesn't contain in __dict__. Even when directly returning model response in fastAPI, even that doesn't contain the hybrid property.

In the below code, I am trying to access "posts_count" after storing __dict__ value but it's doesn't present in it

### To Reproduce

```python
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    password = Column(String, nullable=False)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    posts= relationship("Post", back_populates="owner")
    
   
    @hybrid_property
    def posts_count(self):
        return len(self.posts)
    
   
    @posts_count.expression
    def posts_count(self):
        return len(self.posts)

#also user. __dict__ does not contain "posts_count" property as well   
```

### Error

```
INFO:     127.0.0.1:42552 - "POST /auth/login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 234, in app
    response_data = await serialize_response(
  File "/home/rajat/Desktop/studied/python API DEV/fastAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for LoggedInUserResDTO
response -> posts_count
  field required (type=value_error.missing)
``` 

### Versions

- OS: Ubuntu 20
- Python: 3.8
- SQLAlchemy:1.4.28
- Database:postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
these attributes are [python descriptors](https://docs.python.org/3/howto/descriptor.html) which are evaluated each time you call them.  they would only populate into `__dict__` if you added additional logic to perform this operation yourself.  

for serialization that includes dynamically generated attributes you would need to write this logic yourself, and/or use a schema-driven serialization system such as [marshmallow](https://marshmallow.readthedocs.io/en/stable/).

**Comment by CaselIT** [comment]
I'm not sure if you can make pydantic call the property here. You should probably investigate that.
As an alternative you could use `column_property` with a subquery you to count the number of posts

**Comment by rajatgng** [comment]
> t the number of posts

Yes `column_property` is working, but I want to use @hybrid_property, as column_property have a limitation of having SQL queries, so I can't perform complex operation in it

**Comment by rajatgng** [comment]
> these attributes are [python descriptors](https://docs.python.org/3/howto/descriptor.html) which are evaluated each time you call them. they would only populate into `__dict__` if you added additional logic to perform this operation yourself.
> 
> for serialization that includes dynamically generated attributes you would need to write this logic yourself, and/or use a schema-driven serialization system such as [marshmallow](https://marshmallow.readthedocs.io/en/stable/).

@zzzeek thanks.

So it means that I have to use a separate logic to generate these hybrid property, Isn't there any direct way to get hybrid property in fastAPI

**Comment by CaselIT** [comment]
> Isn't there any direct way to get hybrid property in fastAPI

you would need to check with fastapi / pydantic here. SQLAlchemy has no control on how either of the two are working.

maybe you could use a reconstructor https://docs.sqlalchemy.org/en/14/orm/constructors.html to override the hybrid property in the instance?

```py
class User(Base):
  ...
  @reconstructor
  def reconstruct(self):
    self.post_count = self.post_count
```

**Comment by rajatgng** [comment]
> > Isn't there any direct way to get hybrid property in fastAPI
> 
> you would need to check with fastapi / pydantic here. SQLAlchemy has no control on how either of the two are working.
> 
> maybe you could use a reconstructor https://docs.sqlalchemy.org/en/14/orm/constructors.html to override the hybrid property in the instance?
> 
> ```python
> class User(Base):
>   ...
>   @reconstructor
>   def reconstruct(self):
>     self.post_count = self.post_count
> ```

Thanks, @CaselIT, will look into it.
