### ISSUE TITLE
Setup.py has a bug if it fails to compile since the cython merge

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7539]
Thanks @gordthompson for the report

```
PS C:\Users\Gord\git\sqla-gerrit> pip install -e .
Obtaining file:///C:/Users/Gord/git/sqla-gerrit
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting greenlet!=0.4.17
  Using cached greenlet-1.1.2-cp39-cp39-win_amd64.whl (101 kB)
Installing collected packages: typing-extensions, greenlet, SQLAlchemy
  Running setup.py develop for SQLAlchemy
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\gord\git\sqla-gerrit\venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gord\\git\\sqla-gerrit\\setup.py'"'"'; __file__='
"'"'C:\\Users\\Gord\\git\\sqla-gerrit\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'
"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\Gord\git\sqla-gerrit\
    Complete output (75 lines):
    running develop
    C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Us
e build and pip and other standards-based tools.
      warnings.warn(
    C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and
 pip and other standards-based tools.
      warnings.warn(
    running egg_info
    warning: no files found matching '*.html' under directory 'doc'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no files found matching '*.js' under directory 'doc'
    no previously-included directories found matching 'doc\build\output'
    writing manifest file 'lib\SQLAlchemy.egg-info\SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 84, in build_extension
        super().build_extension(ext)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
        self.initialize()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 156, in <module>
        run_setup(True)
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 130, in run_setup
        setup(cmdclass=cmdclass, distclass=Distribution, **kwargs)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 78, in run
        super().run()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Gord\AppData\Local\Temp\pip-build-env-qssd0gre\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 86, in build_extension
        raise BuildFailed() from e
    __main__.BuildFailed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gord\git\sqla-gerrit\setup.py", line 168, in <module>
        exc.cause,
    AttributeError: 'BuildFailed' object has no attribute 'cause'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\gord\git\sqla-gerrit\venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gord\\git\\sqla-
gerrit\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gord\\git\\sqla-gerrit\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from
setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full com
mand output.
```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix AttributeError typo in setup.py that prevented fallback** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3487
