### ISSUE TITLE
raise an error if stream_results is used with async / .execute() / Result, does not seem to be working

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7667]
program crashes after a few rows, looks like when it tries to re-buffer results.  

by definition this can't work because the Result is not an async object, they should use session.stream().

we have a lot of sync stream_results tests that should be failing for asyncpg etc.   so maybe add more rows and then set up requirement blocks.

```py
#!/usr/bin/env python3

import asyncio
import random
from sqlalchemy import Column, LargeBinary, Table, select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()
database_table = Table(
    "database",
    Base.metadata,
    Column("data", LargeBinary(), nullable=False),
)

def generate_bytes():
    return b"".join(
        random.randint(0, 50000000).to_bytes(10, 'big') for i in range(1000)
    )

async def main() -> None:
    engine = create_async_engine(
        "postgresql+asyncpg://scott:tiger@localhost/test"
    )
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async_session_factory = sessionmaker(
        engine, expire_on_commit=False, class_=AsyncSession
    )
    async with async_session_factory() as async_session:
        for i in range(5):
            await async_session.execute(
                database_table.insert(),
                [{"data": generate_bytes()} for i in range(2)],
            )
        await async_session.commit()

    async with async_session_factory() as async_session:
        query = (select(database_table.c.data)).execution_options(
            stream_results=True, max_row_buffer=1
        )
        rows = await async_session.execute(query)
        for row in rows:
            print(len(row["data"]))

    await engine.dispose()


asyncio.run(main())
```

```
$ python test3.py 
10000
10000
10000
10000
10000
10000
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 52, in <module>
    asyncio.run(main())
  File "/opt/python-3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/python-3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/classic/dev/sqlalchemy/test3.py", line 46, in main
    for row in rows:
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 381, in iterrows
    for row in self._fetchiter_impl():
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 1794, in _fetchiter_impl
    row = fetchone(self, self.cursor)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 1083, in fetchone
    self._buffer_rows(result, dbapi_cursor)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 1055, in _buffer_rows
    self.handle_exception(result, dbapi_cursor, e)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2036, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 1053, in _buffer_rows
    new_rows = dbapi_cursor.fetchmany(size)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/asyncpg.py", line 546, in fetchmany
    self._adapt_connection.await_(self._cursor.fetch(size - lb))
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/_concurrency_py3k.py", line 67, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
sys:1: RuntimeWarning: coroutine 'Cursor.fetch' was never awaited
```

**Comment by zzzeek** [comment]
we document asyncio as "API details are subject to change however at this point it is unlikely for there to be significant backwards-incompatible changes." so we have the green light for this to just raise.   programs that are silently relying on this behavior because they only fetch a few rows will crash sooner.

**Comment by zzzeek** [comment]
update, we are already trying to raise:

```
    conn = self._sync_connection()

        result = await greenlet_spawn(
            conn._execute_20,
            statement,
            parameters,
            execution_options,
            _require_await=True,
        )
        if result.context._is_server_side:
            raise async_exc.AsyncMethodRequired(
                "Can't use the connection.execute() method with a "
                "server-side cursor."
                "Use the connection.stream() method for an async "
                "streaming result set."
            )
        return result
```

so.....why not working

**Comment by zzzeek** [comment]
because ORM session doesnt use that codepath!   OK.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure exception raised for all stream w/ sync result** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3574

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**ensure exception raised for all stream w/ sync result** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3575
