### ISSUE TITLE
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor SET string construction

### ISSUE THREAD

**Issue by cmflynn** [sqlalchemy/sqlalchemy#7668]
### Describe the bug

SET query execution with params on the engine.sync_engine cursor inside engine_connect event listen is throwing error: `sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError: <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "$1"` 

```py
    # this works
    cursor.execute(
        "select %s", (identity,)
    )
    # throws an error 
    cursor.execute(
        "set session iam.identity = %s", (identity,)
    )
```

### To Reproduce

```python
import asyncio

from sqlalchemy import event
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

db_url = make_url('postgresql://xxx:yyy@127.0.0.1/my_db')

async_db_url = db_url.set(drivername="postgresql+asyncpg")
engine = create_async_engine(
    async_db_url,
    pool_timeout=5,
    pool_pre_ping=True,
    pool_recycle=600,
    future=True,
)

async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False, future=True,)


def foobar_engine_connect_listener(connection, branch):

    identity = "arn:aws:sts::123456:assumed-role/thing_1"

    cursor = connection.connection.cursor()
    
    # THIS WORKS 
    cursor.execute(
        "select %s", (identity,)
    )
    
    # THIS THROWS THE ERROR
    cursor.execute(
        "set session iam.identity = %s", (identity,)
    )


event.listens_for(engine.sync_engine, "engine_connect")(foobar_engine_connect_listener)


async def go():
    async with async_session() as session:
        await session.execute('select 1')


if __name__ == "__main__":
    asyncio.run(go())
```

### Error

```
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 388, in _prepare_and_execute
    prepared_stmt, attributes = await adapt_connection._prepare(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 630, in _prepare
    prepared_stmt = await self._connection.prepare(operation)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/asyncpg/connection.py", line 530, in prepare
    return await self._prepare(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/asyncpg/connection.py", line 546, in _prepare
    stmt = await self._get_statement(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/asyncpg/connection.py", line 375, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 166, in prepare
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "$1"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/code.capitalrx.com/help_me.py", line 48, in <module>
    asyncio.run(go())
  File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/mnt/code.capitalrx.com/help_me.py", line 44, in go
    await session.execute('select 1')
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 157, in execute
    return await greenlet_spawn(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 120, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1676, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1526, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 120, in __init__
    self.dispatch.engine_connect(self, _branch_from is not None)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/mnt/code.capitalrx.com/help_me.py", line 34, in foobar_engine_connect_listener
    cursor.execute(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 62, in await_only
    return current.driver.switch(awaitable)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    value = await result
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/vagrant/.pyenv/versions/3.8.1/envs/capitalrx/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError: <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "$1"``` 

### Versions

- OS: Description:    Ubuntu 18.04.5 LTS
- Python: 3.8.1
- SQLAlchemy: 1.4.15
- Database: postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): I dont think sqlalchemy 1.4 async is dbapi? but it ill say asyncpg 


### Additional context

_No response_

**Comment by zzzeek** [comment]
the PostgreSQL database does not accept a bound parameter format in this context.    Here's asyncpg

```py
import asyncio
import asyncpg

async def main():
    conn = await asyncpg.connect(user="scott", password="tiger", host="localhost", database="test")

    identity = "arn:aws:sts::123456:assumed-role/thing_1"

    await conn.execute("set session iam.identity = $1", (identity,))

asyncio.run(main())
```

same error

**Comment by zzzeek** [comment]
so you want to apply that string directly like this:
```py
 cursor.execute(
        f"set session iam.identity = {identity}"
    )
```

hope this helps

**Comment by cmflynn** [comment]
hey thanks for the quick response. I was not sure if this was a bug or not, but the same approach works for a standard engine instead of async with slightly different parameter format so I figured it was probably a bug.  I dont think formatting with f strings will be a safe enough implementation for me. I did read through asyncpg docs but idk, i wasn't able to find to how to construct these SET strings. 

```py
from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker


def foobar_engine_connect_listener(connection, branch):
    identity = "arn:aws:sts::123456:assumed-role/thing_1"
    cursor = connection.connection.cursor()
    cursor.execute("set session iam.identity = %(identity)s", {
        "identity": identity,
    })


sync_engine = create_engine(
    'postgresql://xxx:yyy@127.0.0.1/my_db',
    executemany_mode="batch",
    pool_timeout=5,
    pool_pre_ping=True,
)

Session = sessionmaker(sync_engine)


event.listens_for(sync_engine, "engine_connect")(foobar_engine_connect_listener)


def go():
    with Session() as session:
        session.execute('select 1')


if __name__ == "__main__":
    go()

```

**Comment by zzzeek** [comment]
the psycopg2 driver is interpolating the given parameters on the client side, asyncpg is using server prepared statements.   so different behaviors

**Comment by cmflynn** [comment]
for others who may encounter this, the solution I ended up with is the following: 
the important part being using set_config function with %s param substitution. 

```py
import asyncio

from sqlalchemy import event
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

db_url = make_url('postgresql://xxx:yyy@127.0.0.1/my_db')
async_db_url = db_url.set(drivername="postgresql+asyncpg")

engine = create_async_engine(
    async_db_url,
    pool_timeout=5,
    pool_pre_ping=True,
    pool_recycle=600,
    future=True,
)

async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False, future=True,)


def foobar_engine_connect_listener(connection, branch):
    identity = "arn:aws:sts::123456:assumed-role/thing_1"
    cursor = connection.connection.cursor()
    cursor.execute(
        "select %s", (identity,)
    )

    cursor.execute("select set_config('iam.identity', %s, false)", (identity,))


event.listens_for(engine.sync_engine, "engine_connect")(foobar_engine_connect_listener)


async def go():
    async with async_session() as session:
        await session.execute('select 1')


if __name__ == "__main__":
    asyncio.run(go())

```
