### ISSUE TITLE
url connectivity for SQL server on SQLAlchemy 1.4, but works on 1.3.24

### ISSUE THREAD

**Issue by valhuber** [sqlalchemy/sqlalchemy#7680]
### Describe the bug

API Logic Server migration to 1.4 is working on sqlite, MySQL, and Postgres, but fails on SqlServer.

This test case isolates the issue: [https://github.com/valhuber/SqlSvr](https://github.com/valhuber/SqlSvr):

- test project - example program, requirements.txt, stacktrace

I am wondering if there is a change in the connection string; I checked, but did not find anything.

### To Reproduce

From [https://github.com/valhuber/SqlSvr](https://github.com/valhuber/SqlSvr):

```python

from sqlalchemy.engine import create_engine
from sqlalchemy.schema import MetaData

"""
db on docker: docker run --name sqlsvr-container --net dev-network -p 1433:1433 -d apilogicserver/sqlsvr:version1.0.0
"""

url = "mssql+pyodbc://sa:posey386!@localhost:1433/NORTHWND?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=no"

engine = create_engine(url)

metadata = MetaData(engine)
metadata.reflect(engine)  # fails here with SQLAlchemy==1.4.29, works with SQLAlchemy==1.3.24
"""
sqlalchemy.exc.DBAPIError: (pyodbc.Error)
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server?trusted_connection=no' :
file not found (0) (SQLDriverConnect)") 
"""

print(f'opened')
```

### Error

```
(venv) val@Vals-MacBook-Pro-16 SqlSvr %  cd /Users/val/Desktop/SqlSvr ; /usr/bin/env /Users/val/Desktop/SqlSvr/venv/bin/py
thon /Users/val/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/launcher 50951 -- /Us
ers/val/Desktop/SqlSvr/open_test.py 
Traceback (most recent call last):
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server?trusted_connection=no' : file not found (0) (SQLDriverConnect)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/val/Desktop/SqlSvr/open_test.py", line 13, in <module>
    metadata.reflect(engine)  # fails here with SQLAlchemy==1.4.29, works with SQLAlchemy==1.3.24
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4697, in reflect
    with inspection.inspect(bind)._inspection_context() as insp:
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/val/Desktop/SqlSvr/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server?trusted_connection=no' : file not found (0) (SQLDriverConnect)")
(Background on this error at: https://sqlalche.me/e/14/dbapi)
``` 

### Versions

- OS: MAC
- Python: 3.8
- SQLAlchemy: SQLAlchemy==1.4.29
- Database: SqlServer
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc==4.0.32

**Comment by zzzeek** [comment]
hey Val -

it's your URL.  For some reason a lot of SQL Server users have a URL like the one you have here, with two question marks:

url = "mssql+pyodbc://sa:posey386!@localhost:1433/NORTHWND?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=no"


it should be:

url = "mssql+pyodbc://sa:posey386!@localhost:1433/NORTHWND?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=no"


hopefully that was it.

**Comment by valhuber** [comment]
Bingo!  So, it caught a long-standing bug… totally fine with that.

It works as you said, closing the issue.
