### ISSUE TITLE
"AttributeError: entity" on invalid, fully qualified, string relationship path

### ISSUE THREAD

**Issue by DanCardin** [sqlalchemy/sqlalchemy#7697]
### Describe the bug

If you have more than one model with the same class name, sqlalchemy will prompt you on any string-defined relationships like so:
```
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "Foo" in the registry of this declarative base. Please use a fully module-qualified path.
```

If you give a **completely** bogus fully qualified path, you'll get
```
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Test1->test1, expression 'name.dir.Foo' failed to locate a name ("name 'name' is not defined"). If this is a class name, consider adding this relationship() to the <class 'dir.test1.Test1'> class after both dependent classes have been defined.
```

If you provide a valid path, regardless of whether `Foo` is available at that path, you'll instead get
```
AttributeError: entity
```

I would expect to get something the 2nd error instead

### To Reproduce
Repro is slightly weird because it needs a minimal amount of resolvable packages available.

```bash
mkdir example
touch example/__main__.py
touch example/__init__.py
```

`example/__init__.py` then looks like:

```python
from sqlalchemy import Column, ForeignKey, Integer
from sqlalchemy.orm import relationship

from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foo"

    id = Column(Integer(), primary_key=True)


class Test(Base):
    __tablename__ = "test"

    foo_id = Column(Integer(), ForeignKey('foo.id'), primary_key=True)

    foo = relationship('example.test.Foo', uselist=False)

print(Foo())
```

and finally `python -m example`.

For the other, proper error messages, replace `example.test.Foo` with `Foo`, `example.Foo`, or `adlfkjasdflkj.Foo`. the `adlfkjasdflkj.Foo` error is the one i would expect.

The setup here is a bit contrived to make it more concise. The real scenarios are where sqlalchemy forces the use of fully qualified names (because more than one model has the same name), and where I might (accidentally) put a path that *is* importable in python to get to the model, but which does not describe the path to where the class is defined.

### Error

```
Traceback (most recent call last):
  File "python3-3.7.9/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "python3-3.7.9/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "python3-3.7.9/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "example/__init__.py", line 9, in <module>
    print(foo.Foo())
  File "<string>", line 2, in __init__
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 373, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File ".venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 199, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File ".venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 297, in __call__
    fn(*args, **kw)
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3341, in _event_on_first_init
    configure_mappers()
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3229, in configure_mappers
    mapper._post_configure_properties()
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1853, in do_init
    self._process_dependent_arguments()
  File ".venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1915, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File ".venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 949, in __getattr__
    return self._fallback_getattr(key)
  File ".venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 923, in _fallback_getattr
    raise AttributeError(key)
AttributeError: entity
``` 

It's especially difficult to determine the source of the problem because the source of the error is no where in the stack trace.

Setting a breakpoint at the exception point and going up two levels to `orm/relationships.py", line 1915, in _process_dependent_arguments` allows one to see `self.parent` to figure out where it is. So it's **possible** to figure out, just the UX is subpar.

### Versions

- OS: doesn't matter
- Python: Doesn't matter but 3.8/3.9
- SQLAlchemy: 1.3 and 1.4 are what I've tested, in various patch versions.
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

**Comment by zzzeek** [comment]
OK it's any token in the middle there, Test or test.

**Comment by DanCardin** [comment]
Yes. Although i first encountered it where the qualified path i gave was a valid path to a reference to the model (import alias under an `__init__.py`, i.e. `foo.bar.Baz` Instead of `foo.bar.baz.Baz`), but not the literal path to the definition…if that’s helpful information

**Comment by zzzeek** [comment]
the class resolver is raising correctly, it's just that it's doing AttributeError for this case and that is getting squashed by a "hasattr()".    so I probably should just change the exception class.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Raise and re-catch NameError from _ModNS** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3588

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Raise and re-catch NameError from _ModNS** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3589
