### ISSUE TITLE
reflection fails on Firebird database in 1.4.31

### ISSUE THREAD

**Issue by hmoffatt** [sqlalchemy/sqlalchemy#7699]
### Describe the bug

I have just upgraded SQLAlchemy from 1.1.18 to 1.4.31 and Flask-SQLAlchemy from 2.3.0 to 2.5.1. Now reflection fails on Firebird database.

```
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1667, in exec_driver_sql
    args_10style, kwargs_10style = _distill_params_20(parameters)
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/util.py", line 142, in _distill_params_20
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: List argument must consist only of tuples or dictionaries
```

### To Reproduce

```python
import sys
import flask
import os
import os.path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)


app.config.setdefault('DB_PATH', os.getcwd())
app.config.setdefault('SESSION_DB_HOST', 'localhost')
app.config.setdefault('SESSION_DB', 'db/sessions.fdb')
app.config.setdefault('FIREBIRD_USER', 'sysdba')
app.config.setdefault('FIREBIRD_PASSWORD', 'masterkey')

app.config.setdefault('SQLALCHEMY_DATABASE_URI', 'firebird+fdb://%s:%s@%s/%s'
                      % (app.config['FIREBIRD_USER'],
                         app.config['FIREBIRD_PASSWORD'],
                          app.config['SESSION_DB_HOST'],
                          os.path.join(app.config['DB_PATH'], app.config['SESSION_DB'])))

session_db = SQLAlchemy()
session_db.init_app(app)

with app.app_context():
    # session_db.engine.echo = True
    session_db.metadata.bind = session_db.engine
    session_db.metadata.reflect()
```

### Error

```
Traceback (most recent call last):
  File ".../test.py", line 29, in <module>
    session_db.metadata.reflect()
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4756, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File ".../lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 607, in __new__
    metadata._remove_table(name, schema)
  File ".../lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File ".../lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 602, in __new__
    table._init(name, metadata, *args, **kw)
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 677, in _init
    self._autoload(
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 712, in _autoload
    conn_insp.reflect_table(
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File ".../lib/python3.9/site-packages/sqlalchemy/dialects/firebird/base.py", line 838, in get_columns
    pk_constraint = self.get_pk_constraint(connection, table_name)
  File "<string>", line 2, in get_pk_constraint
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 47, in cache
    return fn(self, con, *args, **kw)
  File ".../lib/python3.9/site-packages/sqlalchemy/dialects/firebird/base.py", line 781, in get_pk_constraint
    c = connection.exec_driver_sql(keyqry, ["PRIMARY KEY", tablename])
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1667, in exec_driver_sql
    args_10style, kwargs_10style = _distill_params_20(parameters)
  File ".../lib/python3.9/site-packages/sqlalchemy/engine/util.py", line 142, in _distill_params_20
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: List argument must consist only of tuples or dictionaries
``` 

### Versions

- OS: Debian 11 buster
- Python: 3.9.2
- SQLAlchemy: 1.4.31 (regression since 1.1.18)
- Database: Firebird
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): fdb

**Comment by hmoffatt** [comment]
Ugh, sorry I see Firebird is deprecated now. It would be ideal if the failure would say that in some way.

**Comment by CaselIT** [comment]
Hi,

The documentation list an external driver for Firebird

**Comment by hmoffatt** [comment]
I was surprised that the 'firebird+fdb' syntax was still recognised now that it is deprecated.

I have now installed the external driver and it is working ok. Thanks.

**Comment by CaselIT** [comment]
Well, deprecated means that it still works but raises deprecation warning.
In v2 it will raise since the deprecated dialects have been removed

**Comment by hmoffatt** [comment]
Unfortunately it doesn't work, as per my report above.

**Comment by CaselIT** [comment]
by work I meant it will still instantiate the internal firebird dialect.
failures are expected, since it's not tested and it's the main reason why it was deprecated

**Comment by hmoffatt** [comment]
Why not remove it properly now since it is not working?

**Comment by CaselIT** [comment]
It seems just reflection is not working.

Basic functionality should still be there, and I don't think most people uses reflection.

**Comment by zzzeek** [comment]
> Why not remove it properly now since it is not working?

it has been removed in ed78e679eafe787f.

**Comment by hmoffatt** [comment]
Is that commit not in 1.4.31 ? As per my report I am getting this confusing reflection error using firebird+fdb in 1.4.31.

**Comment by CaselIT** [comment]
no, that's for v2. 1.4.31 will keep the deprecated dialect
