### ISSUE TITLE
Possible cache issue - joined inheritance query is reusing old query options instead of adhering to new ones

### ISSUE THREAD

**Issue by huntfx** [sqlalchemy/sqlalchemy#7731]
### Describe the bug

If using the joined inheritance feature, and you perform a query with options, it seems to reuse those options on subsequent queries and ignore any new ones you set.

The workaround is doing a `session.rollback()` - or in my actual use case, deleting the variable storing the results of the previous query, though I wasn't able to replicate that in the example.

### To Reproduce

```python
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *

Engine = create_engine('sqlite:///')
Base = declarative_base(bind=Engine)
Session = sessionmaker(bind=Base.metadata.bind)

class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    type = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'employee',
        'polymorphic_on':type
    }

class Engineer(Employee):
    __tablename__ = 'engineer'
    id = Column(Integer, ForeignKey('employee.id'), primary_key=True)
    manager_id = Column(Integer, ForeignKey('manager.id'))
    manager = relationship('Manager', foreign_keys=manager_id, backref='engineers')

    __mapper_args__ = {
        'polymorphic_identity':'engineer',
    }

class Manager(Employee):
    __tablename__ = 'manager'
    id = Column(Integer, ForeignKey('employee.id'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity':'manager',
    }

Base.metadata.create_all()

session = Session()
manager = Manager()
session.add(manager)
engineer = Engineer(manager=manager)
session.add(engineer)
session.commit()

stmt = select(Employee).where(Employee.id == 2).options(
    raiseload('*'),
)
session.execute(stmt).scalar()  # COMMENT THIS BIT OUT AND IT WORKS
# session.rollback()   # UNCOMMENT THIS AND IT ALSO WORKS

stmt = select(Employee).where(Employee.id == 2).options(
    selectinload(Engineer.manager),
)
for employee in session.execute(stmt).scalars():
    if isinstance(employee, Engineer):
        print(employee.manager)
```

### Error

```
Traceback (most recent call last):
  File "c:/Blue-Zoo/Pipeline/bz/dev/bluebox/api/bluebox/v1/routes/test.py", line 153, in <module>
    print(employee.manager)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\attributes.py", line 975, in _fire_loader_callables
    return callable_(state, passive)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\strategies.py", line 1170, in __call__
    extra_criteria=self.extra_criteria,
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\strategies.py", line 854, in _load_for_state
    self._invoke_raise_load(state, passive, "raise")
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\strategies.py", line 815, in _invoke_raise_load
    "'%s' is not available due to lazy='%s'" % (self, lazy)
sqlalchemy.exc.InvalidRequestError: 'Engineer.manager' is not available due to lazy='raise'
``` 

### Versions

- OS: Windows 10
- Python: 3.7.9
- SQLAlchemy: 1.4.29, 1.4.31
- Database: SQLite

### Additional context

I'm not 100% sure it's specific to joined inheritance, but I'm stabbing in the dark a bit here and that's just a way I was able to replicate it.

**Comment by zzzeek** [comment]
so when debugging issues like these, it's essential that you turn on echo=True on the engine to see what's actually happening.  if we run just your "selectinload" part, with workarounds in place as given, SQL is:

```sql
 BEGIN (implicit)
2022-02-18 08:34:55,661 INFO sqlalchemy.engine.Engine SELECT employee.id, employee.type 
FROM employee 
WHERE employee.id = ?
2022-02-18 08:34:55,661 INFO sqlalchemy.engine.Engine [caching disabled 0.00010s] (2,)
2022-02-18 08:34:55,662 INFO sqlalchemy.engine.Engine SELECT engineer.manager_id AS engineer_manager_id 
FROM engineer 
WHERE ? = engineer.id
2022-02-18 08:34:55,662 INFO sqlalchemy.engine.Engine [caching disabled 0.00008s] (2,)
2022-02-18 08:34:55,664 INFO sqlalchemy.engine.Engine SELECT manager.id AS manager_id, employee.id AS employee_id, employee.type AS employee_type 
FROM employee JOIN manager ON employee.id = manager.id 
WHERE employee.id = ?

```

what we see here is the selectinload is not taking effect, it's emitting **three** SELECT queries.  One for "Employee", one for "Engineer", and then a lazy load for "manager".  This is because when you query for "Employee", that does not automatiaclly load rows from the "engineer" table.    The "Employee" entity in this configuration does not imply the "Engineer" entity is present.   

what we want to do is use [with_polymorphic](https://docs.sqlalchemy.org/en/14/orm/inheritance_loading.html?highlight=with_polymorphic#with-polymorphic) to control how the Employee entity is loaded.   We can use it on a per query basis here as:

```py
emp_w_engineer = with_polymorphic(Employee, (Engineer, ))
stmt = (
    select(emp_w_engineer)
    .where(emp_w_engineer.id == 2)
    .options(
        selectinload(emp_w_engineer.Engineer.manager),
    )
)
```

then you get the selectinload, with the caveat that since you want to load all Employee rows as well as the optional "Engineer" row, it has to use LEFT OUTER JOIN which is less efficient from a SQL perspective:

```sql
 SELECT employee.id, employee.type, engineer.id AS id_1, engineer.manager_id 
FROM employee LEFT OUTER JOIN engineer ON employee.id = engineer.id 
WHERE employee.id = ?
2022-02-18 08:37:42,482 INFO sqlalchemy.engine.Engine [caching disabled 0.00007s] (2,)
2022-02-18 08:37:42,484 INFO sqlalchemy.engine.Engine SELECT employee.id AS employee_id, manager.id AS manager_id, employee.type AS employee_type 
FROM employee JOIN manager ON employee.id = manager.id 
WHERE employee.id IN (?)

```

you can also set up with_polymoprhic on the mapping:

```py
class Employee(Base):
    __tablename__ = "employee"
    id = Column(Integer, primary_key=True)
    type = Column(String(50))

    __mapper_args__ = {
        "polymorphic_identity": "employee",
        "polymorphic_on": type,
        "with_polymorphic": ("*")
    }
```

that one line added will also allow your program as given to run completely, but it means the SQL to load Employee objects is by default more cumbersome for query planners and data fetched:

```sql
SELECT employee.id, employee.type, engineer.id AS id_1, engineer.manager_id, manager.id AS id_2 
FROM employee LEFT OUTER JOIN engineer ON employee.id = engineer.id LEFT OUTER JOIN manager ON employee.id = manager.id 
WHERE employee.id = ?
2022-02-18 08:38:31,455 INFO sqlalchemy.engine.Engine [caching disabled 0.00031s] (2,)
2022-02-18 08:38:31,458 INFO sqlalchemy.engine.Engine SELECT employee.id AS employee_id, manager.id AS manager_id, employee.type AS employee_type 
FROM employee JOIN manager ON employee.id = manager.id 
WHERE employee.id IN (?)
```


Still another way to get the load you want is to just load Engineer directly, which will emit the most efficient SQL of "employee JOIN engineer":

```py
stmt = (
    select(Engineer)
    .where(Engineer.id == 2)
    .options(
        selectinload(Engineer.manager),
    )
)

```


still *another* option, which I dont even know when I added this, is to try out [polymorphic selectin loading](https://docs.sqlalchemy.org/en/14/orm/inheritance_loading.html?highlight=with_polymorphic#polymorphic-selectin-loading), which will again eagerly fetch for "Engineer" and/or "Manager" but use a separate SELECT query, without the outerjoin, this line added also fixes your test case:

```py
class Engineer(Employee):
    __tablename__ = "engineer"
    id = Column(Integer, ForeignKey("employee.id"), primary_key=True)
    manager_id = Column(Integer, ForeignKey("manager.id"))
    manager = relationship(
        "Manager", foreign_keys=manager_id, backref="engineers"
    )

    __mapper_args__ = {
        "polymorphic_identity": "engineer",
        'polymorphic_load': 'selectin',
    }
```

make sure you remove "with_polymorphic: ('*',)" with the above option.  then the SQL at the end is:


```sql
SELECT employee.id, employee.type 
FROM employee 
WHERE employee.id = ?
2022-02-18 08:45:04,376 INFO sqlalchemy.engine.Engine [caching disabled 0.00027s] (2,)
2022-02-18 08:45:04,378 INFO sqlalchemy.engine.Engine SELECT engineer.id AS engineer_id, employee.id AS employee_id, employee.type AS employee_type, engineer.manager_id AS engineer_manager_id 
FROM employee JOIN engineer ON employee.id = engineer.id 
WHERE employee.id IN (?) ORDER BY employee.id
2022-02-18 08:45:04,379 INFO sqlalchemy.engine.Engine [caching disabled 0.00023s] (2,)
2022-02-18 08:45:04,380 INFO sqlalchemy.engine.Engine SELECT employee.id AS employee_id, manager.id AS manager_id, employee.type AS employee_type 
FROM employee JOIN manager ON employee.id = manager.id 
WHERE employee.id IN (?)
```


so is this a simple problem?  not at all.   joined inheritance has a lot of moving parts.   This is why most ORMs don't even get into this sort of thing.   but there you go , hope this helps

**Comment by zzzeek** [comment]
> HI,
> 
> The behaviour you are seeing it because the object you are trying to reload is already in the session. See [populate_existing](https://docs.sqlalchemy.org/en/14/orm/queryguide.html?highlight=populate_existing#populate-existing) for more information

that's what I thought at first also but it also needed a different query for the selectinload to take effect.    since the "manager" attribute is not loaded, you don't need populate_existing in this case.

**Comment by CaselIT** [comment]
Ah yes, i had not noticed the selectinload parameter
