### ISSUE TITLE
regression in composites

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#7751]
### Describe the bug

Something in a (relatively) recent commit seems to have broken the "Vertex" example used in

doc/build/orm/composites.rst

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy.orm import composite
from sqlalchemy.orm import declarative_base

connection_url = "sqlite://"
engine = create_engine(
    connection_url,
    echo=True,
)

Base = declarative_base()


class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __composite_values__(self):
        return self.x, self.y

    def __repr__(self):
        return "Point(x=%r, y=%r)" % (self.x, self.y)

    def __eq__(self, other):
        return isinstance(other, Point) and \
            other.x == self.x and \
            other.y == self.y

    def __ne__(self, other):
        return not self.__eq__(other)


class Vertex(Base):
    __tablename__ = 'vertices'

    id = Column(Integer, primary_key=True)
    x1 = Column(Integer)
    y1 = Column(Integer)
    x2 = Column(Integer)
    y2 = Column(Integer)

    start = composite(Point, x1, y1)
    end = composite(Point, x2, y2)
```

### Error

```
/home/gord/git/sqla-gerrit/venv/bin/python /home/gord/git/sqla-gerrit/gord_test/vertex.py
/home/gord/git/sqla-gerrit/gord_test/vertex.py:37: SAWarning: On class 'Vertex', Column object 'x' named directly multiple times, only one will be used: x1, x2. Consider using orm.synonym instead
  class Vertex(Base):
/home/gord/git/sqla-gerrit/gord_test/vertex.py:37: SAWarning: On class 'Vertex', Column object 'y' named directly multiple times, only one will be used: y1, y2. Consider using orm.synonym instead
  class Vertex(Base):
/home/gord/git/sqla-gerrit/gord_test/vertex.py:37: SADeprecationWarning: A column with name 'x' is already present in table 'vertices'. Please use method :meth:`_schema.Table.append_column` with the parameter ``replace_existing=True`` to replace an existing column.
  class Vertex(Base):
/home/gord/git/sqla-gerrit/gord_test/vertex.py:37: SADeprecationWarning: A column with name 'y' is already present in table 'vertices'. Please use method :meth:`_schema.Table.append_column` with the parameter ``replace_existing=True`` to replace an existing column.
  class Vertex(Base):
Traceback (most recent call last):
  File "/home/gord/git/sqla-gerrit/gord_test/vertex.py", line 37, in <module>
    class Vertex(Base):
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_api.py", line 127, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 135, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 186, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 343, in __init__
    self._early_mapping(mapper_kw)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 218, in _early_mapping
    self.map(mapper_kw)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 1119, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/util/deprecations.py", line 324, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/mapper.py", line 678, in __init__
    self._configure_properties()
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/mapper.py", line 1423, in _configure_properties
    self._configure_property(key, prop, False)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/mapper.py", line 1688, in _configure_property
    prop = self._property_from_column(key, prop)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/mapper.py", line 1861, in _property_from_column
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: When configuring property 'x1' on Mapper[Vertex(vertices)], column 'vertices.x' is not represented in the mapper's table. Use the `column_property()` function to force this column to be mapped as a read-only attribute.
``` 

### Versions

- OS: Xubuntu 20.04
- Python: 3.8
- SQLAlchemy: current main branch
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**undefer column name sooner to accommodate composites** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3626
