### ISSUE TITLE
additional regression in composites

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#7753]
### Describe the bug

#7751 has been resolved by 35c57486008b865ce06840ea80dd65750afa1849, but there is still an issue with composites.

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy.orm import composite
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

connection_url = "sqlite://"
engine = create_engine(
    connection_url,
    echo=True,
)

Base = declarative_base()


class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __composite_values__(self):
        return self.x, self.y

    def __repr__(self):
        return "Point(x=%r, y=%r)" % (self.x, self.y)

    def __eq__(self, other):
        return isinstance(other, Point) and \
            other.x == self.x and \
            other.y == self.y

    def __ne__(self, other):
        return not self.__eq__(other)


class Vertex:
    def __init__(self, start, end):
        self.start = start
        self.end = end

    @classmethod
    def _generate(self, x1, y1, x2, y2):
        """generate a Vertex from a row"""
        return Vertex(
            Point(x1, y1),
            Point(x2, y2)
        )

    def __composite_values__(self):
        return \
            self.start.__composite_values__() + \
            self.end.__composite_values__()


class HasVertex(Base):
    __tablename__ = 'has_vertex'
    id = Column(Integer, primary_key=True)
    x1 = Column(Integer)
    y1 = Column(Integer)
    x2 = Column(Integer)
    y2 = Column(Integer)

    vertex = composite(Vertex._generate, x1, y1, x2, y2)


with Session(engine) as s:
    hv = HasVertex(vertex=Vertex(Point(1, 2), Point(3, 4)))
```

### Error

```
Traceback (most recent call last):
  File "/home/gord/git/sqla-gerrit/gord_test/has_vertex.py", line 68, in <module>
    hv = HasVertex(vertex=Vertex(Point(1, 2), Point(3, 4)))
  File "<string>", line 4, in __init__
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/util/langhelpers.py", line 141, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/decl_base.py", line 1279, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "<string>", line 1, in __set__
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/descriptor_props.py", line 235, in fset
    self._composite_values_from_instance(value),
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/orm/descriptor_props.py", line 166, in _composite_values_from_instance
    return self._generated_composite_accessor(value)
AttributeError: 'Vertex' object has no attribute 'x1'
``` 

### Versions

- OS: Xubuntu 20.04
- Python: 3.8
- SQLAlchemy: current main branch
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
OK we can just have reopened the one I just fixed.  i had noticed we didnt have a lot of tests for composite so this is great you're finding all these cases thanks!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**limit new constructor scan thing for composites to dataclasses only** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3627
