### ISSUE TITLE
Creating views described in the wiki example is not working

### ISSUE THREAD

**Issue by hochstibe** [sqlalchemy/sqlalchemy#7779]
### Describe the bug

Creating views as described in the [wiki/views](https://github.com/sqlalchemy/sqlalchemy/wiki/Views) is not working:

- The views have no columns
- Deprecation warning

The deprecation warning can be fixed on line 35
```python
# instead of 'for c in selectable.c:'
for c in selectable.subquery().c:
    c._make_proxy(t)
```

### To Reproduce

```python
#!python
import sqlalchemy as sa
from sqlalchemy.ext import compiler
from sqlalchemy.schema import DDLElement
from sqlalchemy.sql import table


class CreateView(DDLElement):
    def __init__(self, name, selectable):
        self.name = name
        self.selectable = selectable


class DropView(DDLElement):
    def __init__(self, name):
        self.name = name


@compiler.compiles(CreateView)
def compile(element, compiler, **kw):
    return "CREATE VIEW %s AS %s" % (
        element.name,
        compiler.sql_compiler.process(element.selectable, literal_binds=True),
    )


@compiler.compiles(DropView)
def compile(element, compiler, **kw):
    return "DROP VIEW %s" % (element.name)


def view(name, metadata, selectable):
    t = table(name)

    for c in selectable.c:
        c._make_proxy(t)

    sa.event.listen(metadata, "after_create", CreateView(name, selectable))
    sa.event.listen(metadata, "before_drop", DropView(name))
    return t


if __name__ == "__main__":

    engine = sa.create_engine("sqlite://", echo=True)
    metadata = sa.MetaData()
    stuff = sa.Table(
        "stuff",
        metadata,
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("data", sa.String(50)),
    )

    more_stuff = sa.Table(
        "more_stuff",
        metadata,
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("stuff_id", sa.Integer, sa.ForeignKey("stuff.id")),
        sa.Column("data", sa.String(50)),
    )
    # SQLite requires you to explicitly give a label to a column in a select list otherwise the column name
    # is undefined and this breaks this demo as the query cannot find the column 'stuff_view.data'
    # See http://www.sqlite.org/c3ref/column_name.html
    stuff_view = view(
        "stuff_view",
        metadata,
        sa.select(
            [
                stuff.c.id.label("id"),
                stuff.c.data.label("data"),
                more_stuff.c.data.label("moredata"),
            ]
        )
        .select_from(stuff.join(more_stuff))
        .where(stuff.c.data.like(("%orange%"))),
    )

    # the ORM would appreciate this
    assert stuff_view.primary_key == [stuff_view.c.id]

    with engine.begin() as conn:
        metadata.create_all(conn)

    with engine.begin() as conn:
        conn.execute(
            stuff.insert(),
            [
                {"data": "apples"},
                {"data": "pears"},
                {"data": "oranges"},
                {"data": "orange julius"},
                {"data": "apple jacks"},
            ],
        )

        conn.execute(
            more_stuff.insert(),
            [{"stuff_id": 3, "data": "foobar"}, {"stuff_id": 4, "data": "foobar"}],
        )

    assert set(
        r[0:2]
        for r in engine.execute(sa.select([stuff_view.c.data, stuff_view.c.moredata])).fetchall()
    ) == set([("oranges", "foobar"), ("orange julius", "foobar")])

    # illustrate ORM usage
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy.orm import Session

    Base = declarative_base(metadata=metadata)

    class MyStuff(Base):
        __table__ = stuff_view

        def __repr__(self):
            # this is just an example of repr
            return str(self.__dict__)

    s = Session(engine)
    print(s.query(MyStuff).all())
    s.close()
    with engine.begin() as conn:
        metadata.drop_all(conn)
```

### Error

```
Traceback (most recent call last):
  File "C:\_devel\bitbucket\geo-api\tester.py", line 86, in <module>
    assert stuff_view.primary_key == [stuff_view.c.id]
  File "C:\Users\sho\Miniconda3\envs\zustand\lib\site-packages\sqlalchemy\sql\base.py", line 1207, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "C:\Users\sho\Miniconda3\envs\zustand\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
AttributeError: id
``` 

The problem is, that the views have no columns:
```
print(stuff_view.columns)
# ImmutableColumnCollection()
print(stuff.columns)
# ImmutableColumnCollection(stuff.id, stuff.data)
```

### Versions

- OS: Windows
- Python: 3.10
- SQLAlchemy: 1.4.31
- Database: PostgreSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2, asyncpg

**Comment by hochstibe** [comment]
Thanks a lot for the quick response. I have a related question, but I can also open a new ticket:

If the db already exists, `CREATE VIEW` is still executed and results in a ProgrammingError (DuplicateTableError). I replaced it with `CREATE OR REPLACE`. It would be smoother if sqlalchemy would skip the statement instead.
Try / Except ProgrammingError did not resolve it.

Any hints for a workaround?

**Comment by zzzeek** [comment]
yes you need to figure out the SQL query that will show if the view exists or not, then when you create the CreateView() / DropView() objects , you need to attach [execute_if](https://docs.sqlalchemy.org/en/14/core/ddl.html#sqlalchemy.schema.DDLElement.execute_if) callables to each, some docs for this are at https://docs.sqlalchemy.org/en/14/core/ddl.html#controlling-ddl-sequences , so it would be like:

```py

   def view_doesnt_exist(ddl, target, connection, **kw):
         # CHANGE THIS PART TO EMIT THE CORRECT SQL
         row = connection.exec_driver_sql(
            f"select does_the_view_exist({ddl.element.name}) from mydatabase.system_catalogs"
         ).scalar()
         return not bool(row)

   def view_exists(ddl, target, connection, **kw):
         # CHANGE THIS PART TO EMIT THE CORRECT SQL
         row = connection.exec_driver_sql(
            f"select does_the_view_exist({ddl.element.name}) from mydatabase.system_catalogs"
         ).scalar()
         return bool(row)

   sa.event.listen(metadata, "after_create", CreateView(name, selectable).execute_if(view_doesnt_exist))
   sa.event.listen(metadata, "before_drop", DropView(name).execute_if(view_exists))
```

above we can see there's no option other than emitting some SQL, so in that sense "CREATE IF NOT EXISTS" is a lot more succinct.

**Comment by zzzeek** [comment]
actually we have reflection methods to get views, so I can actually update the recipe on this

**Comment by zzzeek** [comment]
OK I updated the wiki, here is that excerpt

```py
def view_exists(ddl, target, connection, **kw):
    return ddl.name in sa.inspect(connection).get_view_names()


def view_doesnt_exist(ddl, target, connection, **kw):
    return not view_exists(ddl, target, connection, **kw)


def view(name, metadata, selectable):
    t = table(name)

    t._columns._populate_separate_keys(
        col._make_proxy(t) for col in selectable.selected_columns
    )

    sa.event.listen(
        metadata,
        "after_create",
        CreateView(name, selectable).execute_if(callable_=view_doesnt_exist),
    )
    sa.event.listen(
        metadata, "before_drop", DropView(name).execute_if(callable_=view_exists)
    )
    return t
```

**Comment by hochstibe** [comment]
Thanks a lot, you're my hero 🥇
