### ISSUE TITLE
Using generated declarative base inside function leads to mypy crash

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#7790]
**Describe the bug**
I have two main packages (main and tests) which both use typing. In the tests package, I have a function which generates a declarative base and uses it as a base class of another class.
Then after I run mypy, I change something in the main module. Afterwards, mypy crashes.

**Expected behavior**
No crash.

**To Reproduce**

1. Create the following files

pyproject.toml
```toml
[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"

```

main/\_\_init__.py
```py
from __future__ import annotations


def pr() -> str:
    return "abc"
```

tests/\_\_init__.py
```py
from __future__ import annotations

from sqlalchemy import Column, Integer

from sqlalchemy.orm import declarative_base


def test_types_in_select() -> None:
    Base = declarative_base()

    class DummyTable(Base):
        __tablename__ = "user2"
        col1 = Column(Integer, primary_key=True)
```

2. `mypy main/ tests/`
3. Change `main/__init__.py`, so that the method signature is `def pr() -> str|None:`
4. `mypy main/ tests/`

**Error**

```
Traceback (most recent call last):
  File "/root/git/empty_test/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/root/git/empty_test/venv/lib64/python3.7/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 256, in _build
  File "mypy/build.py", line 2717, in dispatch
  File "mypy/build.py", line 3041, in process_graph
  File "mypy/build.py", line 3119, in process_fresh_modules
  File "mypy/build.py", line 2008, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 90, in visit_symbol_table
  File "mypy/fixup.py", line 48, in visit_type_info
  File "mypy/types.py", line 970, in accept
  File "mypy/fixup.py", line 155, in visit_instance
  File "mypy/fixup.py", line 272, in lookup_fully_qualified_typeinfo
  File "mypy/lookup.py", line 29, in lookup_fully_qualified
AssertionError: Cannot find module for Base
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.31
 - mypy: 0.931
 - SQLAlchemy2-stubs: 0.0.2a20

**Additional context**
I guess this is somehow related to the cache. If you take a look into `.mypy_cache/3.7/tests/__init__.data.json`, you see that `Base` is referenced but not listed as a standalone class.
If you now change something, w/o that this cache file is rebuilt, mypy fails to get the `Base` class data.

As a workaround, the `Base = declarative_base()` can be moved outside the function. Looking then into the cache file, there is data for the class.

**Have a nice day!**

**Comment by zzzeek** [comment]
there might not be a way to fix this for the plugin.   another workaround is to not use the declarative_base function and instead use the form currently documented at https://docs.sqlalchemy.org/en/14/orm/declarative_styles.html#creating-an-explicit-base-non-dynamically-for-use-with-mypy-similar .

**Comment by zzzeek** [comment]
as mentioned I don't have a way to fix this, and the mypy plugin is deprecated, as is the entire declarative_base() function.  so I would stick with workarounds for now, including 1. dont run the mypy plugin on test suites 2. use an explicit base class as mentioned previously.
