### ISSUE TITLE
AsyncSession improperly coerces the BigInteger type when passing it to the function polymorphic in its arguments

### ISSUE THREAD

**Issue by igoras1993** [sqlalchemy/sqlalchemy#7813]
### Describe the bug

So, this is a really minor bug, which can be also related to **asyncpg** but I am not sure. The problem emerges when using **asyncpg**, it is not present when using **psycopg2**. It is easily reproducible, so I will let the code to speak for itself.

Take following statement:

```
lock_id_64bit = 4944215145091319531
stmt = select(func.pg_try_advisory_lock(lock_id_64bit)
```

When executed, it should fire the postgres `pg_try_advisory_lock` which is polymorphic in its arguments, having following prototypes:

- `pg_try_advisory_lock(key bigint)`
- `pg_try_advisory_lock(key1 int, key2 int)`

In our case, this is the first version which should be executed. And it does, but only if using `Session` and **psycopg2** wrapper. **When using `AsyncSession` and asyncpg, it fails when executed with following error:**

```
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 4944215145091319531 (value out of int32 range)
[SQL: SELECT pg_try_advisory_lock(%s) AS pg_try_advisory_lock_1]
[parameters: (4944215145091319531,)]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
```

The reason I think that this is a problem with SQLAlchemy, is that You can easily overcome this issue with explicit type coertion, which is a part of SQLAlchemy API. Use following statement:

```
stmt = select(func.pg_try_advisory_lock(type_coerce(lock_id_64bit, BigInteger())))
```

And everything runs flawlessly.

### To Reproduce

```python
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy import select, func, BigInteger
from sqlalchemy.sql.expression import type_coerce

import asyncio


engine = create_async_engine(
    "postgresql+asyncpg://postgres:1234567890@localhost:6543/postgres",
    echo=True,
)

SessionLocal = sessionmaker(
    class_=AsyncSession,
    autocommit=False,
    autoflush=False,
    expire_on_commit=False,
    future=True,
    bind=engine,
)


async def main():
    lock_id_64bit = 4944215145091319531
    async with SessionLocal() as session:
        # stmt = f"SELECT pg_try_advisory_lock({lock_id_64bit})"
        stmt = select(
            # This will work:
            # func.pg_try_advisory_lock(type_coerce(lock_id_64bit, BigInteger()))
            # But this not (only when using AsyncIO api, synchronous runs this without issues)
            func.pg_try_advisory_lock(lock_id_64bit)
        )
        result = (await session.execute(stmt)).scalar_one()

    print(result)


if __name__ == "__main__":
    asyncio.run(main())
```

### Error

Full traceback:

```
Traceback (most recent call last):
  File "asyncpg/protocol/prepared_stmt.pyx", line 168, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg/protocol/codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg/protocol/codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg/pgproto/./codecs/int.pyx", line 60, in asyncpg.pgproto.pgproto.int4_encode
OverflowError: value out of int32 range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: 4944215145091319531 (value out of int32 range)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 4944215145091319531 (value out of int32 range)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/sqlalchemy_advisory_lock_poly/main.py", line 38, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/code/sqlalchemy_advisory_lock_poly/main.py", line 32, in main
    result = (await session.execute(stmt)).scalar_one()
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
    result = await greenlet_spawn(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1487, in _execute_clauseelement
    ret = self._execute_context(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/code/sqlalchemy_advisory_lock_poly/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 4944215145091319531 (value out of int32 range)
[SQL: SELECT pg_try_advisory_lock(%s) AS pg_try_advisory_lock_1]
[parameters: (4944215145091319531,)]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
``` 

### `pip freeze`

```
asyncpg==0.25.0
black==22.1.0
click==8.0.4
greenlet==1.1.2
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.5.1
psycopg2==2.9.3
pycodestyle==2.8.0
SQLAlchemy==1.4.32
tomli==2.0.1
typing_extensions==4.1.1
```

### python3 --version

```
Python 3.9.10
```

### Operating system 

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

### Database

PostgreSQL 14 (`psql (PostgreSQL) 14.1 (Debian 14.1-1.pgdg110+1)`)

**Comment by CaselIT** [comment]
Hi,

sqlalchemy tries to guess what type to use based on the in argument. since python has only one kind of integer, that's what guessed. You can specify a type on the function, doing `select(func.pg_try_advisory_lock(lock_id_64bit, type_=BigInteger)`

I think this is an expected behaviour, since `pg_try_advisory_lock` uses a generic function, so it has to guess the type from the arguments.
