### ISSUE TITLE
Allow include columns in a `UniqueConstraint`

### ISSUE THREAD

**Issue by dhirschfeld** [sqlalchemy/sqlalchemy#7843]
### Describe the use case

Allowing include columns in an *index* to specify a covering index was implemented in #4458 (at least for MSSQL/Postgres IIUC).

I'd like to also be able to specify include columns in a `UniqueConstraint` so that the index it creates can also be a covering index.

### Databases / Backends / Drivers targeted

I'm specifically interested in MSSQL but this might be a generic capability - i.e. the kwargs could be passed down to the underlying `Index` which can then decide if it supports them or not.

### Example Use

My example is similar to:
```python
import sqlalchemy as sa
from sqlalchemy.schema import (
    Column,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.types import (
    Float,
    Integer as Int32,
    String,
)
from sqlalchemy.dialects.mssql import DATETIME2 as DateTime
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class Temperature(Base):
    __tablename__ = 'Temperature'
    __table_args__ = (
        UniqueConstraint(
            'publisher',
            'weather_station',
            'value_date',
            mssql_include=['value'],
        ),
        {'schema': 'observations'}
    )

    pkid = Column(
        Int32,
        primary_key=True,
        autoincrement=True,
    )
    insert_timestamp = Column(
        DateTime(),
        nullable=False,
        server_default=sa.func.sysutcdatetime(),
    )
    publisher = Column(String(64), nullable=False)
    weather_station = Column(String(64), nullable=False)
    value_date = Column(DateTime(), nullable=False)
    value = Column(Float(53), nullable=False)
```
```python-traceback
Traceback (most recent call last):

  File "C:\Users\dhirschf\code\sandbox\test_sa_bug.py", line 19, in <module>
    class Temperature(Base):

  File "C:\Users\dhirschf\code\sandbox\test_sa_bug.py", line 26, in Temperature
    mssql_include=['value'],

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\sqlalchemy\sql\schema.py", line 3288, in __init__
    Constraint.__init__(self, **kw)

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\sqlalchemy\sql\schema.py", line 3132, in __init__
    self._validate_dialect_kwargs(dialect_kw)

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\sqlalchemy\sql\base.py", line 441, in _validate_dialect_kwargs
    % (k, dialect_name, self.__class__)

ArgumentError: Argument 'mssql_include' is not accepted by dialect 'mssql' on behalf of <class 'sqlalchemy.sql.schema.UniqueConstraint'>
```
```python
In [5]: sa.__version__
Out[5]: '1.4.14'
```

Every time I look up the temperature for a given `publisher`/`weather_station`/`value_date` I will want the associated temperature `value` so it would be good to be able to add it as an include column in the underlying index to make it a covering index.

**Comment by dhirschfeld** [comment]
Ok, I don't think this is possible at the SQL level:
* https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-table-constraint-transact-sql?view=sql-server-ver15

So, I've instead created the unique index directly rather than using a `UniqueConstraint`:
```python
    __table_args__ = (
        Index(
            'uk-Temperature',
            'publisher',
            'weather_station',
            'value_date',
            mssql_include=['value'],
            unique=True,
        ),
        {'schema': 'observations'},
    )
```

Seems to work so I'll go ahead and close this:

![image](https://user-images.githubusercontent.com/881019/159624202-3d589ab0-66ff-4979-969d-c1fa015fabfb.png)
