### ISSUE TITLE
Attempting to raise NotImplementedError in testing/provision.py causes another error

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy#7902]
### Describe the bug

Since the `URL` object is a named tuple, passing it to this style string formatting causes an error
https://github.com/sqlalchemy/sqlalchemy/blob/3b4d62f4f72e8dfad7f38db192a6a90a8551608c/lib/sqlalchemy/testing/provision.py#L380-L382
leading to:
```
TypeError: not all arguments converted during string formatting
```

### To Reproduce

```python
from sqlalchemy.engine import make_url
raise NotImplementedError(
        "no temp table keyword args routine for cfg: %s" % make_url("sqllite:///")
    )
```
```


### Error

```
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 304, in define_tables
    cls.define_reflected_tables(metadata, None)
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 450, in define_reflected_tables
    cls.define_temp_tables(metadata)
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/suite/test_reflection.py", line 454, in define_temp_tables
    kw = temp_table_keyword_args(config, config.db)
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/provision.py", line 47, in __call__
    return self.fns["*"](cfg, *arg)
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/provision.py", line 380, in temp_table_keyword_args
    "no temp table keyword args routine for cfg: %s" % eng.url
TypeError: not all arguments converted during string formatting
``` 

### Versions

- OS: MacOS
- Python: 3.10.2
- SQLAlchemy: 1.4.34
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): custom but also the base code looks broken


### Additional context

_No response_

**Comment by zzzeek** [comment]
we are changing to f strings as much as possible.  however since this bug is in 1.4 as well (I assume) , an initial fix can target changing that syntax to a tuple.

**Comment by cancan101** [comment]
Are you you saying to fix this specific bug using an f string?

**Comment by dzcode** [comment]
I've put up a PR [here](https://github.com/sqlalchemy/sqlalchemy/pull/7987), though would appreciate any suggestions on how to simply test
