### ISSUE TITLE
`could not decorrelate subquery` when creating orm instance containing `Enum` with asyncpg and cockroachdb

### ISSUE THREAD

**Issue by DominiqueGarmier** [sqlalchemy/sqlalchemy#7945]
### Describe the bug

When I try to commit an instance of an ORM model containing an `Enum` field I get `could not decorrelate subquery` when using asyncpg. Running the same thing with psycopg2 works as expected (i.e swap the last two lines).

### To Reproduce

```python
import uuid
import asyncio
from enum import Enum as pyEnum
from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import registry
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine


registry_mapper = registry()


ASYNC_URL = 'cockroachdb+asyncpg://****'  # noqa
SYNC_URL = 'cockroachdb://****'  # noqa


class MyEnum(pyEnum):
    foo = 1
    bar = 2


@registry_mapper.mapped
class TestEnum:
    __tablename__ = 'TestEnums'
    id = Column(UUID(as_uuid=True), default=uuid.uuid4, primary_key=True)
    test = Column(Enum(MyEnum))

    def __repr__(self):
        return f'{type(self).__name__}(id={self._id!r}, test={self.test!r})'


async def test():
    engine = create_async_engine(ASYNC_URL)

    async with engine.begin() as conn:
        await conn.run_sync(registry_mapper.metadata.create_all)

    session = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)

    async with session() as sess:
        test = TestEnum(test=MyEnum.foo)
        sess.add(test)
        await sess.commit()


async def drop():
    engine = create_async_engine(ASYNC_URL)

    async with engine.begin() as conn:
        await conn.run_sync(registry_mapper.metadata.drop_all)


def _test():
    engine = create_engine(SYNC_URL)

    registry_mapper.metadata.create_all(bind=engine)

    session = sessionmaker(engine, expire_on_commit=False)

    with session() as sess:
        test = TestEnum(test=MyEnum.foo)
        sess.add(test)
        sess.commit()


def _drop():
    engine = create_engine(SYNC_URL)
    registry_mapper.metadata.drop_all(bind=engine)


asyncio.run(drop())
asyncio.run(test())

# _drop()
# _test()
```

### Error

```
Traceback (most recent call last):
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 399, in _prepare_and_execute
    prepared_stmt, attributes = await adapt_connection._prepare(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 641, in _prepare
    prepared_stmt = await self._connection.prepare(operation)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 566, in prepare
    return await self._prepare(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 584, in _prepare
    stmt = await self._get_statement(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 413, in _get_statement
    types, intro_stmt = await self._introspect_types(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 459, in _introspect_types
    return await self.__execute(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1731, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions._base.UnknownPostgresError: could not decorrelate subquery

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 460, in execute
    self._adapt_connection.await_(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 435, in _prepare_and_execute
    self._handle_exception(error)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 370, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 663, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions._base.UnknownPostgresError'>: could not decorrelate subquery

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/testing/testing_enum.py", line 57, in <module>
    asyncio.run(test())
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/testing/testing_enum.py", line 44, in test
    await sess.commit()
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 576, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
    result = context.switch(value)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3502, in _flush
    with util.safe_reraise():
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1221, in _emit_insert_statements
    result = connection._execute_20(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 460, in execute
    self._adapt_connection.await_(
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 435, in _prepare_and_execute
    self._handle_exception(error)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 370, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/Users/dominiquegarmier/Documents/workspace/projects/tostudy/database/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 663, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions._base.UnknownPostgresError'>: could not decorrelate subquery
[SQL: INSERT INTO "TestEnums" (id, test) VALUES (%s, %s)]
[parameters: (UUID('296e0286-5268-47a8-a561-68b423db5b34'), 'foo')]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
``` 

### Versions

- OS: Mac OS Monterey 12.3.1
- Python: 3.10.2
- SQLAlchemy: 1.4.31
- Database: CockroachDB 21.2.8
- DBAPI: asyncpg: 0.25.0 / sqlalchemy-cockroachdb: 1.4.3

**Comment by CaselIT** [comment]
Hi,

This seems to be an issue in the `cockroachdb` dialect, I think that it should cast the `foo` value with asyncpg, like the internal dialect does. cc @gordthompson

**Comment by gordthompson** [comment]
This is not an issue with SQLAlchemy or the sqlalchemy-cockroachdb dialect *per se*. asyncpg has presented similar challenges for CockroachDB on several occasions

https://github.com/cockroachdb/cockroach/issues?q=%22could+not+decorrelate+%22

and this is another case. I have reproduced the issue using plain text SQL statements (without SQLAlchemy being involved)

| | psycopg2 | asyncpg |
| - | - | - |
| PostgreSQL | pass | pass |
|CockroachDB | pass | fail |

so I will create a [CockroachDB issue](https://github.com/cockroachdb/cockroach/issues) with a link to this one.

**Comment by DominiqueGarmier** [comment]
thanks for the quick response I'll close this issue now. For future reference go to https://github.com/cockroachdb/cockroach/issues/80169 for a follow up.
