### ISSUE TITLE
CTE cannot be aliased multiple times, raise Multiple CTEs with SAME NAME

### ISSUE THREAD

**Issue by zyp-rgb** [sqlalchemy/sqlalchemy#7962]
### Describe the bug

a CTE cannot be aliased multiple times, raise Multiple CTEs with SAME NAME;

### To Reproduce

```python
from sqlalchemy import Table
from sqlalchemy import MetaData
from sqlalchemy import Column
from sqlalchemy import Float
from sqlalchemy import create_engine


sa_table = Table('district',
                 MetaData(schema='real_estate'),
                 Column('price', Float))

# table = select([sa_table.c.price]).cte('not_a', nesting=True)
table = select([sa_table.c.price]).cte('not_a')
sum_table = table.alias('a')
common_table = table.alias('a')
sql = select(
    [select([func.sum(sum_table.c.price)]).as_scalar() /
     common_table.c.price]
).select_from(common_table)

sql.compile()
```

### Error

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 489, in compile
    return self._compiler(dialect, **kw)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 553, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 765, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 454, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 489, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3263, in visit_select
    text = self._compose_select_body(
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3407, in _compose_select_body
    [
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3408, in <listcomp>
    f._compiler_dispatch(
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/zzz/backend/mdt_parser/py_venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2549, in visit_cte
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Multiple, unrelated CTEs found with the same name: 'a'``` 

### Versions

- OS: macOS Big Sur
- Python: 3.8
- SQLAlchemy: 1.3.24 & 1.4.24
- Database: Postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg


### Additional context

_No response_

**Comment by zzzeek** [comment]
this is the expected behavior.  use a different name for the two aliases, or more conveniently, don't use any name at all and anonymous names will be assigned as SQL construction time.

I would assume the argument made here is that these two CTEs technically would not be confused by the database's SQL parser, but SQLAlchemy's compiler is not as sophisticated as a SQL parser; the check for duplicate CTE names guards against a wide range of error scenarios, so to the degree that this may be a false positive, that's how it works for now.

**Comment by zyp-rgb** [comment]
> 

well thanks, I could accept that and avoid it in my code. 
Maybe consider a feature flag relaxing the check in future?

**Comment by zzzeek** [comment]
> > 
> 
> well thanks, I could accept that and avoid it in my code. Maybe consider a feature flag relaxing the check in future?

it shouldn't need a flag, the rules for generating CTEs would ideally have appropriate gating at the level that a particular name is known not to "leak" outside.    We can accept PRs for this that don't break existing tests.

**Comment by zzzeek** [comment]
the current naming logic is probably not that easy to change here, so unless there's great motivation for someone to change this, closing this.
