### ISSUE TITLE
relationships using sqlmodel do not work

### ISSUE THREAD

**Issue by fozt** [sqlalchemy/sqlalchemy#7993]
### Describe the bug

Relationships to other tables using [sqlmodel](https://github.com/tiangolo/sqlmodel) and async_engine sqlalchemy do not work on the new version of sqlalchemy==1.4.36. On version 1.4.35 everything works

### To Reproduce

```sh
#Created a git repository with docker-compose to reproduce the error
#https://github.com/fozt/fastapi-sqlalchemy-bug-example


git clone git@github.com:fozt/fastapi-sqlalchemy-bug-example.git
cd fastapi-sqlalchemy-bug-example
cp .env.example .env && docker-compose up -d --build
sleep 30
# sqlalchemy==1.4.35
curl -X 'GET' 'http://localhost:8000/get-user' -H 'accept: application/json' 
# sqlalchemy==1.4.36
curl -X 'GET' 'http://localhost:8001/get-user' -H 'accept: application/json'
```

### Error

```
fastapi_server_not_working  | ERROR:uvicorn.error:Exception in ASGI application
fastapi_server_not_working  | Traceback (most recent call last):
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
fastapi_server_not_working  |     result = await app(self.scope, self.receive, self.send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
fastapi_server_not_working  |     return await self.app(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
fastapi_server_not_working  |     await super().__call__(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
fastapi_server_not_working  |     await self.middleware_stack(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
fastapi_server_not_working  |     raise exc
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
fastapi_server_not_working  |     await self.app(scope, receive, _send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
fastapi_server_not_working  |     raise exc
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
fastapi_server_not_working  |     await self.app(scope, receive, sender)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
fastapi_server_not_working  |     raise e
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
fastapi_server_not_working  |     await self.app(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
fastapi_server_not_working  |     await route.handle(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
fastapi_server_not_working  |     await self.app(scope, receive, send)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
fastapi_server_not_working  |     response = await func(request)
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
fastapi_server_not_working  |     raw_response = await run_endpoint_function(
fastapi_server_not_working  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
fastapi_server_not_working  |     return await dependant.call(**values)
fastapi_server_not_working  |   File "/code/./main.py", line 24, in root
fastapi_server_not_working  |     return user.role
fastapi_server_not_working  | AttributeError: 'User' object has no attribute 'role'
``` 

### Versions

- OS: linux (alpine docker)
- Python: 3.8+
- SQLAlchemy: 1.4.36
- Database: postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): postgresql+asyncpg

**Comment by zzzeek** [comment]
SQLModel needs to fix this here:  https://github.com/tiangolo/sqlmodel/issues/315
