### ISSUE TITLE
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

### ISSUE THREAD

**Issue by maksymchuk-mm** [sqlalchemy/sqlalchemy#8010]
### Describe the bug

After the SQLALCEMY library upgrade to 1.4.9
Before that, on SQLALCHEMY 1.3.23 the code worked.
Update to Version 1.4.36 did not solve this problem.
And cannot change to the old version, a many dependencies on the 1.4.9

### To Reproduce

```python
ttables = self.get_table(db_name, source=False)
tconn = self.get_connect(db_name, source=False)
inserting = insert(ttables.ticket)

inserting = inserting.on_conflict_do_update(
    index_elements=[tt_ticket.c.id],
    set_={
        'status': inserting.excluded.status,
        'last_updated_date': inserting.excluded.last_updated_date,
        'exchanged_to_id': inserting.excluded.exchanged_to_id,
        'extra_data': inserting.excluded.extra_data,
        'is_cleaned': inserting.excluded.is_cleaned,
        'is_hold': inserting.excluded.is_hold,
        'version': inserting.excluded.version,
        'basket_id': inserting.excluded.basket_id,
   }
)

with tconn.begin():
    if tickets:
        tconn.execute(inserting, tickets)
```

### Error

```
[2022-05-12, 17:26:46 EEST] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/summus/airflow/plugins/operators/data_sampler.py", line 572, in execute
    self.get_tickets()
  File "/home/summus/airflow/plugins/operators/data_sampler.py", line 290, in get_tickets
    self.select_tickets_to_copy()
  File "/home/summus/airflow/plugins/operators/data_sampler.py", line 302, in select_tickets_to_copy
    self.__copy_data(ticket_ids_to_copy)
  File "/home/summus/airflow/plugins/operators/data_sampler.py", line 313, in __copy_data
    self.__copy_ticket(db_name, tickets_ids)
  File "/home/summus/airflow/plugins/operators/data_sampler.py", line 396, in __copy_ticket
    tconn.execute(inserting, tickets)
  File "/home/summus/airflow/.venv13/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/summus/airflow/.venv13/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/summus/airflow/.venv13/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1365, in _execute_clauseelement
    keys = sorted(distilled_params[0])
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'
```

### Versions

- OS: ubuntu 18.04
- Python: 3.8
- SQLAlchemy: 1.4.9
- Database: PostgreSQL 12
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2-binary==2.8.6

**Comment by CaselIT** [comment]
Hi,

Can you provide the table definition? Without it it's not really easy to reproduce. Also what is the data you are trying to insert?

**Comment by maksymchuk-mm** [comment]
> Hi,
> 
> Can you provide the table definition? Without it it's not really easy to reproduce. Also what is the data you are trying to insert?

```sql

CREATE TABLE IF NOT EXISTS public.ticket
(
    id numeric(25,0) NOT NULL,
    game_id integer NOT NULL,
    game_pk smallint NOT NULL,
    status smallint NOT NULL,
    price_var smallint NOT NULL,
    created_date timestamp without time zone NOT NULL,
    first_draw_id integer NOT NULL,
    last_draw_id integer NOT NULL,
    price bigint NOT NULL,
    created_cdc integer NOT NULL,
    player_id integer NOT NULL,
    boards_0 integer[],
    boards_1 integer[],
    boards_2 integer[],
    boards_3 integer[],
    id_extra smallint,
    last_updated_date timestamp without time zone,
    quick_pick integer[],
    exchanged_from_id numeric(25,0),
    exchanged_to_id numeric(25,0),
    extra_data text COLLATE pg_catalog."default",
    version smallint DEFAULT 0,
    client_os smallint NOT NULL,
    basket_id integer,
    terminal_id integer,
    teller_id integer,
    is_cleaned boolean NOT NULL DEFAULT false,
    is_claimed boolean NOT NULL DEFAULT false,
    is_hold boolean NOT NULL DEFAULT false,
    payment_bank smallint,
    paying_phone_no text COLLATE pg_catalog."default",
    payment_id bigint,
    termval_date timestamp without time zone,
    lat double precision,
    lng double precision,
    termval_lat real,
    termval_lng real,
    extern_id text COLLATE pg_catalog."default",
    signature text COLLATE pg_catalog."default",
    psign text COLLATE pg_catalog."default",
    receipt_id bigint,
    CONSTRAINT ticket_pkey PRIMARY KEY (id),
)

```
Data: 
```
[ (Decimal('12345678910120040732'), 355, 159, 1, 4, datetime.datetime(2022, 5, 11, 0, 7, 20, 840908), 536981, 536981, 5000, 2323, 0, 34534706, 100000072, datetime.datetime(2022, 5, 11, 0, 9, 29, 49337), 1, 14, [[1], [2], [3], [4], [8]], None, None, None, 79, [0], None, None, '{"payment_method_id":64}', 0, False, False, False, datetime.datetime(1, 1, 1, 0, 0), 0.0, 0.0, None, None, 0, '', '', '')]
```

```python
GTICKETID = sa.NUMERIC(25, 0)

sa.Table('ticket', metadata,
        sa.Column('id', GTICKETID, primary_key=True),
        sa.Column('game_id', sa.Integer, nullable=False),
        sa.Column('game_pk', sa.SmallInteger, nullable=False),
        sa.Column('status', sa.SmallInteger, nullable=False),
        sa.Column('price_var', sa.SmallInteger, nullable=False),
        sa.Column('created_date', sa.TIMESTAMP, nullable=False),
        sa.Column('first_draw_id', sa.Integer, nullable=False),
        sa.Column('last_draw_id', sa.Integer, nullable=False),
        sa.Column('price', sa.BIGINT, nullable=False),
        sa.Column('created_cdc', sa.Integer, nullable=False),
        sa.Column('player_id', sa.Integer, nullable=False, server_default=sa.text('0')),
        sa.Column('terminal_id', sa.Integer, nullable=False, server_default=sa.text('0')),
        sa.Column('teller_id', sa.Integer, nullable=False, server_default=sa.text('0')),
        sa.Column('last_updated_date', sa.TIMESTAMP, nullable=False),
        sa.Column('version', sa.SmallInteger, nullable=False, server_default=sa.text('0')),
        sa.Column('client_os', sa.SmallInteger, nullable=False),
        sa.Column('boards_0', sa.ARRAY(sa.Integer)),
        sa.Column('boards_1', sa.ARRAY(sa.Integer)),
        sa.Column('boards_2', sa.ARRAY(sa.Integer)),
        sa.Column('boards_3', sa.ARRAY(sa.Integer)),
        sa.Column('id_extra', sa.SmallInteger),
        sa.Column('quick_pick', sa.ARRAY(sa.Integer)),
        sa.Column('exchanged_from_id', GTICKETID),
        sa.Column('exchanged_to_id', GTICKETID),
        sa.Column('extra_data', sa.TEXT),
        sa.Column('basket_id', sa.Integer, sa.ForeignKey('basket.id')),
        sa.Column('is_cleaned', sa.Boolean, nullable=False, server_default=sa.text('False')),
        sa.Column('is_claimed', sa.Boolean, nullable=False, server_default=sa.text('False')),
        sa.Column('is_hold', sa.Boolean, nullable=False, server_default=sa.text('False')),
        sa.Column('termval_date', sa.TIMESTAMP),
        sa.Column('lat', DOUBLE_PRECISION),
        sa.Column('lng', DOUBLE_PRECISION),
        sa.Column('termval_lat', sa.REAL),
        sa.Column('termval_lng', sa.REAL),
        sa.Column('receipt_id', sa.BIGINT),
        sa.Column('extern_id', sa.TEXT),
        sa.Column("signature", sa.TEXT),
        sa.Column("psign", sa.TEXT),
)
```

**Comment by zzzeek** [comment]
hi - 

we need a lot more information here to understand the issue.   Most importantly is the structure of `tickets`.  If you are sending a list of tuples for example, this is deprecated API and it would be easier for you to switch to the correct form.

**Comment by gusostow** [comment]
Seeing this problem also when inserting a list of tuples. I bisected the issue to this commit if that helps https://github.com/sqlalchemy/sqlalchemy/commit/77f1b7d236dba6b1c859bb428ef32d118ec372e6.

Is passing values arguments as tuples not supported anymore?

**Comment by CaselIT** [comment]
> Is passing values arguments as tuples not supported anymore?

Do you have a reproduction case?

**Comment by zzzeek** [comment]
> Seeing this problem also when inserting a list of tuples. I bisected the issue to this commit if that helps [77f1b7d](https://github.com/sqlalchemy/sqlalchemy/commit/77f1b7d236dba6b1c859bb428ef32d118ec372e6).

a simple [MCVE](http://stackoverflow.com/help/mcve) is what would help, and would get whatever issue might be here fixed for you within a day or so.


> 
> Is passing values arguments as tuples not supported anymore?

There's a bunch of places things that might be called "values arguments" could be passed so I don't know what this refers towards without a specific example.

**Comment by gusostow** [comment]
@CaselIT's example from above matches my case https://github.com/sqlalchemy/sqlalchemy/issues/8010#issuecomment-1125144887.

**Comment by zzzeek** [comment]
> @CaselIT's example from above matches my case [#8010 (comment)](https://github.com/sqlalchemy/sqlalchemy/issues/8010#issuecomment-1125144887).

that example doesn't work in any SQLAlchemy version.  Passing tuples to execute() is only supported in the 1.4.x and earlier series if you are invoking textual SQL, a.k.a. "driver SQL", like this:

```py
    conn.execute("insert into test (id, name) values (?, ?)", [(1, "tmp"), (2, "tmp2")])
```

that works in all 1.x versions.  in 2.0, you would need to call exec_driver_sql() for the above form.

**Comment by gusostow** [comment]
> that example doesn't work in any SQLAlchemy version. 

Okay I hadn't tested it but it looked similar. Passing a list of tuples does work in my case in 1.3 but not 1.4, but I don't have time to create a reproducer. Switching to a list of dicts fixed my problem. Thanks for the help.

**Comment by ulie50** [comment]
I have the same issue, when I try to insert a list of tuples with sqlalchemy.text.

**To Reproduce**

```
import sqlalchemy

test_eng = sqlalchemy.create_engine('mssql+pyodbc://...?driver=FreeTDS',
                                             echo=True,fast_executemany=True)

create_table_stmt = sqlalchemy.text(
    """CREATE TABLE test_db.dbo.test_table (
        test_int_1 int NULL,
        test_int_2 int NULL,
        test_nvarchar_1 nvarchar(500) NULL,
        test_nvarchar_2 nvarchar(150) NULL,
        );"""
)

with test_eng.begin() as conn:
    conn.execute(create_table_stmt)
    
insert_values = [(1,2,"a","b"),(3,4,"c","d")]

insert_stmt = sqlalchemy.text('INSERT INTO dbo.test_table(test_int_1,test_int_2,test_nvarchar_1,test_nvarchar_2) VALUES(?,?,?,?)')

with test_eng.begin() as conn:
    conn.execute(insert_stmt,insert_values)
```

**Error**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [14], in <module>
      1 insert_stmt = sqlalchemy.text('INSERT INTO dbo.test_table(test_int_1,test_int_2,test_nvarchar_1,test_nvarchar_2) VALUES(?,?,?,?)')
      3 with crm03_eng.begin() as conn:
----> 4     conn.execute(insert_stmt,insert_values)

File ~/Dokumente/test_sqlalchemy/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1380, in Connection.execute(self, statement, *multiparams, **params)
   1376     util.raise_(
   1377         exc.ObjectNotExecutableError(statement), replace_context=err
   1378     )
   1379 else:
-> 1380     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)

File ~/Dokumente/test_sqlalchemy/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:333, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    329 def _execute_on_connection(
    330     self, connection, multiparams, params, execution_options, _force=False
    331 ):
    332     if _force or self.supports_execution:
--> 333         return connection._execute_clauseelement(
    334             self, multiparams, params, execution_options
    335         )
    336     else:
    337         raise exc.ObjectNotExecutableError(self)

File ~/Dokumente/test_sqlalchemy/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1548, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1536     (
   1537         elem,
   1538         distilled_params,
   (...)
   1542         elem, distilled_params, execution_options
   1543     )
   1545 if distilled_params:
   1546     # ensure we don't retain a link to the view object for keys()
   1547     # which links to the values, which we don't want to cache
-> 1548     keys = sorted(distilled_params[0])
   1549     for_executemany = len(distilled_params) > 1
   1550 else:

TypeError: '<' not supported between instances of 'str' and 'int'
```
**Versions**

-  SQLAlchemy 1.4.40
- Python 3.8.10

**Comment by CaselIT** [comment]
When using text in execute you need to use the named param style and pass list of dicts.
If you want to use a statement that's passed to the driver as is use exec_driver_sql and pass the string directly

**Comment by ulie50** [comment]
@CaselIT, that worked indeed, I will comment it in my Issue and close it. Thank you!
