### ISSUE TITLE
pool_pre_ping=True doesn't reconnect stale connection with MySQL 8.0.28

### ISSUE THREAD

**Issue by valievkarim** [sqlalchemy/sqlalchemy#8036]
### Describe the bug

When using pool_pre_ping=True with MySQL version 8.0.28 and a stale
connection, SQLAlchemy raises the following error instead of
reconnecting:

MySQLdb._exceptions.OperationalError: (4031, 'The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.')

### To Reproduce

```python
# using MySQL 8.0.28 (or at least 8.0.24) set the following in my.cnf

# [mysqld]
# wait_timeout=10
# interactive_timeout = 10

# update password in connection string below

import time

from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

engine = create_engine("mysql+mysqldb://root:@localhost:3306/mysql", echo=False, future=True, pool_pre_ping=True)

with Session(engine) as session:
    print(session.query(text("1")).all())
time.sleep(11)
with Session(engine) as session:
    print(session.query(text("1")).all())
```

### Error

```
$ python3 reconnect_test.py
[(1,)]
Traceback (most recent call last):
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2930, in raw_connection
    return self.pool.connect()
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 384, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1211, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 185, in do_ping
    dbapi_connection.ping(False)
MySQLdb._exceptions.OperationalError: (4031, 'The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/karim/huiscan/reconnect_test.py", line 12, in <module>
    print(session.query(text("1")).all())
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2562, in all
    return self._iter().all()  # type: ignore
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2695, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1951, in execute
    return self._execute_internal(
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1836, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1726, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 978, in _connection_for_bind
    conn = bind.connect()
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2906, in connect
    return self._connection_cls(self)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2930, in raw_connection
    return self.pool.connect()
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 384, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1211, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 185, in do_ping
    dbapi_connection.ping(False)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (4031, 'The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 910, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1300, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/karim/huiscan/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 592, in do_rollback
    dbapi_connection.rollback()
MySQLdb._exceptions.OperationalError: (4031, 'The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.')
```

### Versions

- OS: MacOS 11.6.2 
- Python: Python 3.9.12
- SQLAlchemy: from git main commit 9e7bed9df601ead02fd96bf2fc787b23b536d2d6
- Database: MySQL  8.0.28
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysqlclient

**Comment by zzzeek** [comment]
OK, it looks like you are PRing to add this new code.   in the meantime, MySQL idle timeouts can be avoided entirely by also using the pool_recycle parameter on create_engine that will prevent a connection from being that old in the first place.

**Comment by sqla-tester** [comment]
**valievkarim** has proposed a fix for this issue in the **main** branch:

**Include new MySQL error code 4031 for MySQL disconnect check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3846
