### ISSUE TITLE
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) DPI-1043: invalid number

### ISSUE THREAD

**Issue by Fire-Dragons** [sqlalchemy/sqlalchemy#8056]
### Describe the bug

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) DPI-1043: invalid number

### To Reproduce

```python
from sqlalchemy import create_engine, String, DateTime, Column
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Integer, Text
from sqlalchemy import ForeignKey, Sequence, MetaData, Table
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.horizontal_shard import ShardedSession, ShardedQuery
from sqlalchemy import Enum
import os
import uuid
import datetime
import enum


# 初始化数据库链接
engine = create_engine('oracle+cx_oracle://user:pwd@host:1521/enfo', pool_recycle=600, pool_pre_ping=True, echo=True)
# 创建对象的基类
md = MetaData(bind=engine)  # 引用MetaData
Base = declarative_base(metadata = md)

def global_id():
    return str(uuid.uuid4()).replace('-','')

class BaseStatusEnum(enum.Enum):
    available = 1
    deleted = 2

class user_menuaccess(Base):
    # 表的名字
    __tablename__ = 'user_menuaccess'
    _id = Column(String(32), nullable=False, primary_key=True, default=global_id, comment="主键")
    _create_time = Column(DateTime, nullable=False, index=True, default=datetime.datetime.now, comment="创建时间")
    _update_time = Column(DateTime, nullable=False, index=True, default=datetime.datetime.now, onupdate=datetime.datetime.now,
                             comment="更新时间")
    _operator = Column(String(32), nullable=True, index=True, comment="更新者")
    _status = Column(Enum(BaseStatusEnum), key="status", nullable=False, index=True, default=BaseStatusEnum.available,comment="记录状态,available代表可用,deleted代表已删除")
    _version = Column("_version", Integer, nullable=False,info={"version_meta": True}, default=1,comment="当前版本号")
    user_id = Column(String(32), comment="用户的ID")
    menu_id = Column(String(32), comment="菜单ID")
    accesscount = Column(Integer, comment="用户点击菜单的次数")
    __mapper_args__ = {
        "version_id_col": _version
    }


Session = sessionmaker(twophase=True, class_=ShardedSession)
shards = {'test': engine}

def shard_chooser(mapper, instance, clause=None, **kw):
    """"""
    return 'test'

def id_chooser(query, identity):
    """"""
    return ['test']

def execute_chooser(orm_context):
    """"""
    return ['test']

Session.configure(shards=shards, shard_chooser=shard_chooser, id_chooser=id_chooser,
                        execute_chooser=execute_chooser, query_cls=ShardedQuery)
session = Session()

obj = user_menuaccess(user_id='1', menu_id='2', accesscount=1)
session.add(obj)
session.flush()
obj.accesscount = 2
session.commit()
```

### Error

```
2022-05-27 09:08:50,286 INFO sqlalchemy.engine.Engine UPDATE user_menuaccess SET "_update_time"=:"_update_time", "_version"=:"_version", accesscount=:accesscount WHERE user_menuaccess."_id" = :user_menuaccess__id AND user_menuaccess."_version" = :user_menuaccess__version
2022-05-27 09:08:50,286 INFO sqlalchemy.engine.Engine [generated in 0.00017s] {'"_update_time"': datetime.datetime(2022, 5, 27, 9, 8, 50, 286445), '"_version"': -2268487166655872354, 'accesscount': 2, 'user_menuaccess__id': '2c0aefef6a2b4b9d9340a03749dd40f5', 'user_menuaccess__version': symbol('NO_VALUE')}
Traceback (most recent call last):
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: DPI-1043: invalid number

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 974, in _emit_update_statements
    c = connection._execute_20(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1487, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/Users/fire/opt/miniconda3/envs/i5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) DPI-1043: invalid number
[SQL: UPDATE user_menuaccess SET "_update_time"=:"_update_time", "_version"=:"_version", accesscount=:accesscount WHERE user_menuaccess."_id" = :user_menuaccess__id AND user_menuaccess."_version" = :user_menuaccess__version]
[parameters: {'"_update_time"': datetime.datetime(2022, 5, 27, 9, 8, 50, 286445), '"_version"': -2268487166655872354, 'accesscount': 2, 'user_menuaccess__id': '2c0aefef6a2b4b9d9340a03749dd40f5', 'user_menuaccess__version': symbol('NO_VALUE')}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
``` 

### Versions

- OS:12.4
- Python:3.9.7
- SQLAlchemy:1.4.36
- Database:oracle
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):cx_oracle

**Comment by Fire-Dragons** [comment]
change "_versoin" to "version" is ok

**Comment by CaselIT** [comment]
seems to be the same issue as https://github.com/sqlalchemy/sqlalchemy/issues/8053. that was fixed by it's not yet released.

for now you can solve specifying the `key` in the `Column`

**Comment by Fire-Dragons** [comment]
> 似乎与#8053相同的问题。这是由它尚未发布修复。
> 
> 你现在可以解决`key`在`Column`

but examples/versioned_history/history_meta.py change "version“ to ”_version“ and add key="version" it not work

**Comment by zzzeek** [comment]
agree, definitely an ORM-manifesting bug, still dependent on Oracle in some way so still likely in Core but I haven't fully traced it out yet.

**Comment by zzzeek** [comment]
will need an involved fix.   persistence.py refers to `c.context.compiled_parameters` and `c.context.compiled_parameters[0]` in many places...these are escaped, so they can't work for reverse lookups.    ideally the param escaping would move to where default.py generates the final execute params, but a quick attempt caused other problems, will need to spend more time looking into it.

as a secondary issue, the ORMs versioning seems like it will fail on update if the version_id_col is expired on the object.


right now you have to change that column name to not start with an underscore in order to proceed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**move bindparam quote application from compiler to default** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3875

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**move bindparam quote application from compiler to default** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3876
