### ISSUE TITLE
Hostname in URI reverts to fully qualified localhost

### ISSUE THREAD

**Issue by bmakan** [sqlalchemy/sqlalchemy#8058]
### Describe the bug

When I create engine with an URI and then session from it, I get error because the username tries to connect to localhost instead of specified host.

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

URI = 'mysql+mysqldb://<username>:<password>@<fully-qualified-hostname>/<db-name>?charset=utf8'
e = create_engine(URI)
s = Session(e)
s.connection()
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
``` 
Traceback (most recent call last):
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user '\<username\>'@'\<fully-qualified-hostname\>' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1526, in connection
    return self._connection_for_bind(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/bmakan/python-venvs/regressdb3/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user '\<username\>'@'\<fully-qualified-hostname\>' (using password: YES)")

### Versions

- OS: Ubuntu 20.04
- Python: 3.8
- SQLAlchemy: 1.4.36
- Database: 10.7.3-MariaDB
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):
 mysqlcliet 2.1.0

### Additional context

I recently switched to a new devpc at work. I used CentOS and python 3.6 before. I also used older versions of libs. I didn't have this issue.
I have another environment similar to the old devpc where the issue doesn't occur. The libs are a bit older there too.

Let me know if I can provide further information to track this down.

**Comment by CaselIT** [comment]
dupe of https://github.com/sqlalchemy/sqlalchemy/issues/6574, https://github.com/sqlalchemy/sqlalchemy/issues/6567, https://github.com/sqlalchemy/sqlalchemy/discussions/6568 , ....

URL escape @ signs in passwords as documented to resolve

see docs at https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=password#database-urls

**Comment by bmakan** [comment]
I don't use `@` in my password.

**Comment by CaselIT** [comment]
that's valid for any special character. does the error persist after escaping the string?

**Comment by bmakan** [comment]
I'm actually already escaping it. Had the issue with the `@` several months ago.

```python
        password = urlquote(password)
        self.URI = f'mysql+mysqldb://{username}:{password}@{hostname}/{database}?charset=utf8'
```

**Comment by CaselIT** [comment]
May be something different then. Does your username contains special characters?

**Comment by bmakan** [comment]
No special characters at all.
This definitely worked in older environment and lib versions. I'll try connecting with pure mysqlclient without SQLA wrappers.
