### ISSUE TITLE
Leading  curly brace (%7B) character in password of a connection string leads to login failure

### ISSUE THREAD

**Issue by aagateuip** [sqlalchemy/sqlalchemy#8062]
### Describe the bug

When password in a connection string starts with "{" (url encoded to %7B) the login fails

Database: Azure SQL Database 

Tried with SQLAlchemy==1.4.36 and SQLAlchemy==1.3.24

 

### To Reproduce

```python
from sqlalchemy import create_engine
engine = create_engine('mssql+pyodbc://testuser@sqlserverhost-sql.database.windows.net:%7B4cbW123@sqlserverhost-sql.database.windows.net:1433/AppDb?driver=ODBC+Driver+17+for+SQL+Server')
engine.connect()
```

### Error

```
Traceback (most recent call last):
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
pyodbc.InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'testuser'. (18456) (SQLDriverConnect)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/appuser/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'testuser'. (18456) (SQLDriverConnect)")
(Background on this error at: https://sqlalche.me/e/14/rvf5)
``` 

### Versions

- OS: Ubuntu
- Python: 3.8
- SQLAlchemy: 1.4.36 and 1.3.24
- Database: Azure SQL Database
- Driver: Microsoft ODBC driver 17 

### Additional context

if the password is reset so the the leading character is not { then it works e.g. a%7B4cbW123
```
from sqlalchemy import create_engine
engine = create_engine('mssql+pyodbc://testuser@sqlserverhost-sql.database.windows.net:a%7B4cbW123@sqlserverhost-sql.database.windows.net:1433/AppDb?driver=ODBC+Driver+17+for+SQL+Server')
engine.connect()
<sqlalchemy.engine.base.Connection object at 0x7f637e4862b0>
```

**Comment by zzzeek** [comment]
CC @gordthompson 

the password comes out correctly from the URL but I suspect this needs some kind of escaping in the ODBC string?

```py
>>> u = url.make_url("mssql+pyodbc://testuser@sqlserverhost-sql.database.windows.net:%7B4cbW123@sqlserverhost-sql.database.windows.net:1433/AppDb?driver=ODBC+Driver+17+for+SQL+Server")
>>> u.password
'{4cbW123'
>>> from sqlalchemy.dialects.mssql import pyodbc
>>> dialect = pyodbc.dialect()
>>> dialect.create_connect_args(u)
(('DRIVER={ODBC Driver 17 for SQL Server};Server=sqlserverhost-sql.database.windows.net,1433;Database=AppDb;UID=testuser@sqlserverhost-sql.database.windows.net;PWD={4cbW123',), {})
```

Otherwise can someone indicate what the pyodbc string should look like...thanks!

**Comment by gordthompson** [comment]
For a SQL Server login

Login name: `larry`
Password: `{M0e`

the ODBC connection string needs to include

```
UID=larry;PWD={{M0e};
```

It appears that this is only an issue when the first character of the attribute is `{`. For

Login name: `larry`
Password: `M0e{`

this works fine

```
UID=larry;PWD=M0e{;
```

**Comment by gordthompson** [comment]
Additional: If the first character is `{` *and* the password also contains `}` then the `}` characters need to be doubled-up.

Login name: `larry`
Password: `{M}0e`

requires

```
UID=larry;PWD={{M}}0e};
```

**Comment by gordthompson** [comment]
So that would be

```python
def odbc_escape(thing):
    return (
        "{" + thing.replace("}", "}}") + "}"
        if thing.startswith("{")
        else thing
    )


print(odbc_escape("{M0e"))  # {{M0e}
print(odbc_escape("M0e{"))  # M0e{
print(odbc_escape("{M}0e"))  # {{M}}0e}
```

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**mssql login failure if password starts with "{"** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3873

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**mssql login failure if password starts with "{"** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3874

**Comment by jayaddison** [comment]
Could the adopted fix here break credentials that contain both a `;` and a `}` but do not start with a `{`?

**Comment by CaselIT** [comment]
So something like `foo;bar}baz`?

**Comment by jayaddison** [comment]
Yep, exactly (I worry that the [`or` condition](https://github.com/sqlalchemy/sqlalchemy/commit/ba0d68b99182871b0ef9d554fc9804ae434f573d#diff-6cb667b523bd7908d3ae1f0c48c2490dbf89f4b62cd877115300509ff7765830R63) might be too permissive)

**Comment by CaselIT** [comment]
It seems to work for me. Try this snippet
```py
from sqlalchemy.connectors import pyodbc
from sqlalchemy import make_url
from urllib.parse import quote_plus

pc = pyodbc.PyODBCConnector()
for pwd in ("{password}", "{}{{{pwd", "foo;bar}baz"):
    print(
        pwd,
        pc.create_connect_args(
            make_url(
                f"mssql+pyodbc://testuser@example.com:{quote_plus(pwd)}@example.com:1433/AppDb?driver=Driver"
            ),
        ),
    )
```
this prints
```
{password} (('DRIVER={Driver};Server=example.com,1433;Database=AppDb;UID=testuser@example.com;PWD={{password}}}',), {})
{}{{{pwd (('DRIVER={Driver};Server=example.com,1433;Database=AppDb;UID=testuser@example.com;PWD={{}}{{{pwd}',), {})
foo;bar}baz (('DRIVER={Driver};Server=example.com,1433;Database=AppDb;UID=testuser@example.com;PWD={foo;bar}}baz}',), {})
```

so the above `"foo;bar}baz"` was translated into `PWD={foo;bar}}baz}` that seems correct to me

**Comment by jayaddison** [comment]
Thanks, that makes sense (I should have attempted some examples / test coverage).

The `{password}` -> `PWD={{password}}}` case looks odd, though.  Isn't that a pre-escaped token that we should leave as-is?  (the unbalanced braces in the output seem like they could be a problem)

**Comment by jayaddison** [comment]
> The `{password}` -> `PWD={{password}}}` case looks odd, though. Isn't that a pre-escaped token that we should leave as-is? (the unbalanced braces in the output seem like they could be a problem)

It may look a little strange, but this is as-expected.

Consider the parser/receiving side that reads the PWD value: after finding that the initial character is `{`, we switch into 'escaped content' mode.  Within that mode, any closing brackets are expected to be read as pairs, and they translate into a single closing bracket in the output stream.  The exception is that the final character of the token is expected to be a closing bracket.

We don't need to handle that here, though: identifying the case where the content begins with an opening curly bracket and handling that is sufficient.

@gordthompson a question to check my understanding: in theory would it be possible to perform this style of escaping on _all_ credential tokens, regardless of their character-content?

**Comment by gordthompson** [comment]
> in theory would it be possible to perform this style of escaping on all credential tokens, regardless of their character-content?

Yes, it would be possible, like some database tools that quote all table/column names whether they need it or not. For example:

```sql
SELECT [customer_id], [last_name], [first_name] FROM [dbo].[customer]
```

None of those names really need to be quoted, but it doesn't hurt anything (except perhaps readability). Similarly, instead of 

```
UID=scott;PWD=tiger;
```

we could use

```
UID={scott};PWD={tiger};
```

That is perfectly valid, although the "escaping" is unnecessary.
