### ISSUE TITLE
UPDATE fails on a child class, works with parent class

### ISSUE THREAD

**Issue by Nowado** [sqlalchemy/sqlalchemy#8097]
### Describe the bug

Update query following [documentation](https://docs.sqlalchemy.org/en/14/tutorial/orm_data_manipulation.html#orm-enabled-update-statements) fails with "sqlalchemy.exc.CompileError: Unconsumed column names:". When table name is replaced with it's parent name it works fine.

### To Reproduce

```python
import uuid
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

engine = create_async_engine(DATABASE_URL)

SessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

Base = declarative_base()

class ItemTable(Base):
    __tablename__ = "items"
    id = Column(UUID(as_uuid=True), primary_key=True, index=True, default=uuid.uuid4)
    text = Column('text', Text)

    type = Column(String(50))
    __mapper_args__ = {
        'polymorphic_identity': 'item',
        'polymorphic_on': type
    }

class EntreatyTable(ItemTable):
    __tablename__ = "entreaties"
    id = Column(UUID(as_uuid=True), ForeignKey('items.id'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity': 'entreaty',
    }

# entreaty_in.id is a generated UUID
# This works
db.execute(update(ItemTable).where(ItemTable.id == entreaty_in.id).values(text='some text')
# This fails
db.execute(update(EntreatyTable).where(EntreatyTable.id == entreaty_in.id).values(text='some text')
```

### Error

```
discu-react-app-1         | ERROR:    Exception in ASGI application
discu-react-app-1         | Traceback (most recent call last):
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
discu-react-app-1         |     result = await app(self.scope, self.receive, self.send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
discu-react-app-1         |     return await self.app(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
discu-react-app-1         |     await super().__call__(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
discu-react-app-1         |     await self.middleware_stack(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
discu-react-app-1         |     raise exc
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
discu-react-app-1         |     await self.app(scope, receive, _send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
discu-react-app-1         |     await self.simple_response(scope, receive, send, request_headers=headers)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
discu-react-app-1         |     await self.app(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
discu-react-app-1         |     raise exc
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
discu-react-app-1         |     await self.app(scope, receive, sender)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
discu-react-app-1         |     raise e
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
discu-react-app-1         |     await self.app(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
discu-react-app-1         |     await route.handle(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
discu-react-app-1         |     await self.app(scope, receive, send)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
discu-react-app-1         |     response = await func(request)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
discu-react-app-1         |     raw_response = await run_endpoint_function(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
discu-react-app-1         |     return await dependant.call(**values)
discu-react-app-1         |   File "/app/./app/routers/entreaties.py", line 109, in update_entreaties
discu-react-app-1         |     await db.execute(update(EntreatyTable).where(EntreatyTable.id == entreaty_in.id).values({"text":entreaty_in.text})
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
discu-react-app-1         |     result = await greenlet_spawn(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
discu-react-app-1         |     result = context.switch(*args, **kwargs)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
discu-react-app-1         |     result = conn._execute_20(statement, params or {}, execution_options)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
discu-react-app-1         |     return meth(self, args_10style, kwargs_10style, execution_options)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
discu-react-app-1         |     return connection._execute_clauseelement(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1490, in _execute_clauseelement
discu-react-app-1         |     compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 523, in _compile_w_cache
discu-react-app-1         |     compiled_sql = self._compiler(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
discu-react-app-1         |     return dialect.statement_compiler(dialect, self, **kw)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
discu-react-app-1         |     Compiled.__init__(self, dialect, statement, **kwargs)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
discu-react-app-1         |     self.string = self.process(self.statement, **compile_kwargs)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
discu-react-app-1         |     return obj._compiler_dispatch(self, **kwargs)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/annotation.py", line 196, in _compiler_dispatch
discu-react-app-1         |     return self.__element.__class__._compiler_dispatch(self, visitor, **kw)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
discu-react-app-1         |     return meth(self, **kw)
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 4029, in visit_update
discu-react-app-1         |     crud_params = crud._get_crud_params(
discu-react-app-1         |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/crud.py", line 169, in _get_crud_params
discu-react-app-1         |     raise exc.CompileError(
discu-react-app-1         | sqlalchemy.exc.CompileError: Unconsumed column names: text``` 

### Versions

- OS: docker image 'python:3.8'
- Python: 3.8
- SQLAlchemy: 1.4.31
- Database: postgres:14
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2 2.9


### Additional context

After failing few times following different SO answers I decided to try swapping the name and it simply worked. I didn't notice similar behaviour anywhere else in code with other commands, although I haven't been looking for it.

**Comment by zzzeek** [comment]
hiya -

this is [documented](https://docs.sqlalchemy.org/en/14/orm/session_basics.html#orm-expression-update-delete) in the caveats for ORM-enabled update and delete (pink dragon box).   EntreatyTable is a JOIN between two tables and there's not generally facilities to update a JOIN directly.
