### ISSUE TITLE
LookupError when querying Table with enum column containing non defined values

### ISSUE THREAD

**Issue by karolpawlowski** [sqlalchemy/sqlalchemy#8106]
### Describe the bug

While migrating our code from `1.3.23` to `1.4.37`

```
report = self.session.query(Report).filter_by(id=self.report_ids[0]).one()
report.report_category = "gibberish"  # type: ignore
self.session.add(report)
self.session.commit()
self.session.query(Report).all()
```

where

`report. report_category` is:
```
report_category = Column(
        Enum(
            ReportCategory,
            native_enum=False,
            length=60,
            create_constraint=False,
            validate_strings=False,
        ),
        nullable=False,
    )
```

and 

```
@enum.unique
class ReportCategory(str, enum.Enum):
    QUALITY = "quality"
```

ends up with `LookupError` when calling `.all()`:

```LookupError: 'gibberish' is not among the defined enum values. Enum name: report_category. Possible values: QUALITY ```

It doesn't seem like a new 1.4 feature and I expect it should occur with the previous version too. Also I thought `validate_strings=False` could help but without success.

Added LookupError handling for now, but preferred to report this. Maybe it is some kind of error or I do something wrong?

### To Reproduce

```python
report = self.session.query(Report).filter_by(id=self.report_ids[0]).one()
report.report_category = "gibberish"  # type: ignore
self.session.add(report)
self.session.commit()
self.session.query(Report).all()
```
```


### Error

```LookupError: 'gibberish' is not among the defined enum values. Enum name: report_category. Possible values: QUALITY ```

### Versions

- OS: Docker 4.8.2
- Python: python:3.8-slim
- SQLAlchemy: 1.4.37
- Database: postgres:13
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):


### Additional context

_No response_

**Comment by zzzeek** [comment]
it would be appreciated if you could please format a runnable test case.

assuming this lookup error is on the query side, I'm not sure how it would function in 1.3 because it needs to return an element from your enumeration, which is not possible if the name doesn't match.

**Comment by zzzeek** [comment]
no difference is observed, test script:

```py
import enum

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Enum
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()

class MyEnum(enum.Enum):
    a = 'a'
    b = 'b'

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(Enum(MyEnum, create_constraint=False))

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data='c'))
s.commit()

s.query(A).first()
```

1.4:

    LookupError: 'c' is not among the defined enum values. Enum name: myenum. Possible values: a, b


1.3:

    LookupError: 'c' is not among the defined enum values. Enum name: myenum. Possible values: a, b

**Comment by alijewers** [comment]
Hi @zzzeek , I have created a minimal example which reproduces the issue on both mine and @karolpawlowski 's machines:

```py
import enum

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Enum
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, sessionmaker

Base = declarative_base()


@enum.unique
class MyEnum(str, enum.Enum):
    E1 = "E1"


class MyTable(Base):
    __tablename__ = "my_table"

    id = Column(Integer, primary_key=True)
    data = Column(
        Enum(
            MyEnum,
            native_enum=False,
            length=60,
            create_constraint=False,
        ),
        nullable=False
    )

e = create_engine("sqlite://", echo=True)
SessionMaker = sessionmaker(bind=e, expire_on_commit=False)
Base.metadata.create_all(e)

connection = e.connect()
tx = connection.begin()

s: Session = SessionMaker(bind=connection)
s.add(MyTable(data="E1"))
s.commit()

row: MyTable = s.query(MyTable).one()
row.data = "E2"  # type: ignore

s.add(row)
s.commit()

rows = s.query(MyTable).all()

for row in rows:
    print(row.data)

tx.rollback()
s.close()
connection.close()

```

With SQLAlchemy 1.3.24, no errors are raised, output is:

```
2022-06-09 10:13:33,501 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2022-06-09 10:13:33,502 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,502 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2022-06-09 10:13:33,502 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,502 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("my_table")
2022-06-09 10:13:33,502 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,503 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("my_table")
2022-06-09 10:13:33,503 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,503 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE my_table (
        id INTEGER NOT NULL, 
        data VARCHAR(60) NOT NULL, 
        PRIMARY KEY (id)
)


2022-06-09 10:13:33,503 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,504 INFO sqlalchemy.engine.base.Engine COMMIT
2022-06-09 10:13:33,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2022-06-09 10:13:33,506 INFO sqlalchemy.engine.base.Engine INSERT INTO my_table (data) VALUES (?)
2022-06-09 10:13:33,506 INFO sqlalchemy.engine.base.Engine ('E1',)
2022-06-09 10:13:33,507 INFO sqlalchemy.engine.base.Engine SELECT my_table.id AS my_table_id, my_table.data AS my_table_data 
FROM my_table
2022-06-09 10:13:33,507 INFO sqlalchemy.engine.base.Engine ()
2022-06-09 10:13:33,508 INFO sqlalchemy.engine.base.Engine UPDATE my_table SET data=? WHERE my_table.id = ?
2022-06-09 10:13:33,509 INFO sqlalchemy.engine.base.Engine ('E2', 1)
2022-06-09 10:13:33,509 INFO sqlalchemy.engine.base.Engine SELECT my_table.id AS my_table_id, my_table.data AS my_table_data 
FROM my_table
2022-06-09 10:13:33,510 INFO sqlalchemy.engine.base.Engine ()
E2
2022-06-09 10:13:33,510 INFO sqlalchemy.engine.base.Engine ROLLBACK
```

With SQLAlchemy 1.4.37, a lookup error is raised at the point of querying the table (but not at the point of inserting the invalid value)

```
2022-06-09 10:14:49,537 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-09 10:14:49,537 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("my_table")
2022-06-09 10:14:49,537 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-06-09 10:14:49,537 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("my_table")
2022-06-09 10:14:49,537 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-06-09 10:14:49,538 INFO sqlalchemy.engine.Engine 
CREATE TABLE my_table (
        id INTEGER NOT NULL, 
        data VARCHAR(60) NOT NULL, 
        PRIMARY KEY (id)
)


2022-06-09 10:14:49,538 INFO sqlalchemy.engine.Engine [no key 0.00011s] ()
2022-06-09 10:14:49,539 INFO sqlalchemy.engine.Engine COMMIT
2022-06-09 10:14:49,539 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-06-09 10:14:49,541 INFO sqlalchemy.engine.Engine INSERT INTO my_table (data) VALUES (?)
2022-06-09 10:14:49,541 INFO sqlalchemy.engine.Engine [generated in 0.00032s] ('E1',)
2022-06-09 10:14:49,544 INFO sqlalchemy.engine.Engine SELECT my_table.id AS my_table_id, my_table.data AS my_table_data 
FROM my_table
2022-06-09 10:14:49,544 INFO sqlalchemy.engine.Engine [generated in 0.00025s] ()
2022-06-09 10:14:49,545 INFO sqlalchemy.engine.Engine UPDATE my_table SET data=? WHERE my_table.id = ?
2022-06-09 10:14:49,546 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ('E2', 1)
2022-06-09 10:14:49,546 INFO sqlalchemy.engine.Engine SELECT my_table.id AS my_table_id, my_table.data AS my_table_data 
FROM my_table
2022-06-09 10:14:49,546 INFO sqlalchemy.engine.Engine [cached since 0.002528s ago] ()
Traceback (most recent call last):
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'E2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ali/Documents/Temp/sqlalchemy-enum-test/sqlalchemy-enumm-test.py", line 49, in <module>
    rows = s.query(MyTable).all()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2768, in all
    return self._iter().all()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1371, in all
    return self._allrows()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1284, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1696, in _fetchall_impl
    return list(self.iterator)
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/Users/ali/.local/share/virtualenvs/sqlalchemy-enum-test-egxoRteE/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
LookupError: 'E2' is not among the defined enum values. Enum name: myenum. Possible values: E1
```

I am not entirely sure what change between your example and ours causes this though.

Hope this helps!

**Comment by zzzeek** [comment]
OK that's not 1.3 acting any differently from the "enum" point of view, it has to do with a change in how data is loaded from database rows deep inside of Core as far as why the Core-level validator is called in 1.4 and not 1.3.

you definitely need LookupError handling in your 1.3 code because your example above works only by delicate accident.  change it for example like this and you'll see the error:

```py
s.expire_all()

rows = s.query(MyTable).all()

for row in rows:
    print(row.data)
```

the difference in 1.4 is that when the SQL is run for `s.query(MyTable).all()`, the row-level data handlers like the Enum validator are run up front as the rows are fetched from the DBAPI cursor.  in 1.3, the row level data handlers are only called when the element in the row is actually used.   since the "row" object is already loaded, neither 1.3 nor 1.4 actually consume the row once delivered.

looks like I wrote a pretty big blurb on that change which is at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#rowproxy-is-no-longer-a-proxy-is-now-called-row-and-behaves-like-an-enhanced-named-tuple

**Comment by PatrickCovreRodrigues** [comment]
Good... I know this question was two years ago, but if anyone still has this question, go to your database and make a select in the enum command: SELECT unnest(enum_range(NULL::new_todostate));
SELECT unnest(enum_range(NULL::sua_table));
see the attributes that are here by default they come Trash done and standby, then you will have to create manually as I did, maybe you can create in sqlalchemy, but I don't know why I didn't find anything (it may have been due to lack of attention I didn't find it)

Sample command to redo from scratch
CREATE TYPE new_todostate AS ENUM ('PENDING', 'TODO', 'INPROGRESS', 'DONE');

ALTER TABLE you_table
ALTER COLUMN you_column TYPE new_todostate USING you_column::text::new_todostate;

Here it worked for me

**Comment by ubuntujule** [comment]
LookupError is documented [here](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum)
..." When reading a value from the database in a result set, the string value is always checked against the list of possible values and a LookupError is raised if no match is found."...
