### ISSUE TITLE
Reflected mssql table with NUMERIC() IDENTITY column errors on Core insert()

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#8111]
### Describe the bug

A reflected mssql table with a NUMERIC(18, 0) IDENTITY column throws an error when we try to use Core insert() on it.

### To Reproduce

```python
import sqlalchemy as sa

connection_url = (
    "mssql+pyodbc://scott:tiger^5HHH@192.168.0.199/test"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
engine = sa.create_engine(connection_url)

table_name = "numeric_identity"

with engine.begin() as conn:
    conn.exec_driver_sql(f"DROP TABLE IF EXISTS {table_name}")
    conn.exec_driver_sql(
        f"CREATE TABLE {table_name} (id numeric(18, 0) identity primary key, txt varchar(50))"
    )
    conn.exec_driver_sql(f"INSERT INTO {table_name} (txt) VALUES ('raw sql')")

with engine.begin() as cn:
    print(cn.exec_driver_sql(f"SELECT * FROM {table_name}").all())
    # [(Decimal('1'), 'raw sql')]

tbl = sa.Table(table_name, sa.MetaData(), autoload_with=engine)

with engine.begin() as conn:
    conn.execute(tbl.insert(), dict(txt="core insert"))
    # sqlalchemy.exc.ArgumentError: Column type NUMERIC(18, 0) on column 'numeric_identity.id' is not compatible with autoincrement=True
```

### Error

```
Traceback (most recent call last):
  File "/home/gord/git/sqla-gerrit/gord_test/numeric_identity.py", line 26, in <module>
    conn.execute(tbl.insert(), dict(txt="core insert"))
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/engine/base.py", line 1303, in execute
    return meth(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/elements.py", line 479, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/engine/base.py", line 1519, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/elements.py", line 644, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/dialects/mssql/base.py", line 1902, in __init__
    super(MSSQLCompiler, self).__init__(*args, **kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/compiler.py", line 981, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/compiler.py", line 593, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/compiler.py", line 625, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/compiler.py", line 4369, in visit_insert
    crud_params_struct = crud._get_crud_params(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/crud.py", line 249, in _get_crud_params
    _scan_cols(
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/crud.py", line 526, in _scan_cols
    ) = _get_returning_modifiers(compiler, stmt, compile_state, toplevel)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/crud.py", line 1313, in _get_returning_modifiers
    and stmt.table._autoincrement_column is not None
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/util/langhelpers.py", line 1128, in __get__
    return self.fget(obj)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/schema.py", line 991, in _autoincrement_column
    return self.primary_key._autoincrement_column
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/util/langhelpers.py", line 1139, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/schema.py", line 4574, in _autoincrement_column
    _validate_autoinc(col, True)
  File "/home/gord/git/sqla-gerrit/lib/sqlalchemy/sql/schema.py", line 4546, in _validate_autoinc
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column type NUMERIC(18, 0) on column 'numeric_identity.id' is not compatible with autoincrement=True
``` 

### Versions

- OS: Ubuntu 20.04
- Python: 3.8
- SQLAlchemy: current main (bf40bade)
- Database: SQL Server 2019
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

**Comment by zzzeek** [comment]
hmmm @CaselIT did we come across this at some point?

**Comment by CaselIT** [comment]
Not sure, I think I modified that logic when adding identity, so maybe it broke then.

@gordthompson can you try to see if this happens also on 1.4.0?

**Comment by gordthompson** [comment]
> @gordthompson can you try to see if this happens also on 1.4.0?

Hey, @CaselIT - Yes, 1.4.0 exhibits the same behaviour.

**Comment by CaselIT** [comment]
Then I guess the bug dates to the introduction of identity.

Thanks for testing!

**Comment by gordthompson** [comment]
Confirmed that this is also an issue with ORM and `automap_base()`. (Not surprising.)

This isn't really a problem with reflection, it's a problem with the assumption that Core makes when it tries to process an insert based on the *results* of that reflection.

I would go ahead and update the labels but I'm not sure which one(s) to pick.

Also, what milestone would be appropriate for this one?

**Comment by zzzeek** [comment]
this would be 1.4 since it's a bug that prevents the feature from working.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Allow NUMERIC()/DECIMAL() IDENTITY columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3925

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Allow NUMERIC()/DECIMAL() IDENTITY columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3934
