### ISSUE TITLE
OperationalError when using on_conflict_do_update with sqlite3

### ISSUE THREAD

**Issue by jangxx** [sqlalchemy/sqlalchemy#8118]
### Describe the bug

I'm trying to use the `on_conflict_do_update` function of the sqlite3 dialect to generate an upsert query, but every time I try to execute the statement, I'm confronted with a `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ON": syntax error`

### To Reproduce

```python
import uuid
import sqlalchemy as sa
import sqlalchemy.dialects.sqlite as sa_sqlite

engine = sa.create_engine("sqlite:///database_test.sqlite3")

meta = sa.MetaData()
table = sa.Table("test", meta,
    sa.Column("id", sa.String(36), primary_key=True),
    sa.Column("value", sa.Integer)
)

meta.create_all(engine)

with engine.connect() as conn:
    id = str(uuid.uuid4())

    query = sa_sqlite.insert(table).values(id=id, value=1)
    conn.execute(query)

    query = sa_sqlite.insert(table).values(id=id, value=2)
    query = query.on_conflict_do_update(
        index_elements = [ table.c.id ],
        set_ = dict( value=2 )
    )
    conn.execute(query)
```

### Error

Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "ON": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/project/bugreport.py", line 27, in <module>
    conn.execute(query)
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/path/to/project/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ON": syntax error
[SQL: INSERT INTO test (id, value) VALUES (?, ?) ON CONFLICT (id) DO UPDATE SET value = ?]
[parameters: ('6438ab68-3f56-4ad2-956a-2219cd81e73a', 2, 2)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Versions

- OS: Linux Mint 19.3
- Python: 3.9.13
- SQLAlchemy: 1.4.37
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
hey there -

your test case runs perfectly, so based on how your SQLite seems to not know what "ON" is at all it seems likely you are on a [version older than SQLite 3.24.0](https://www.sqlite.org/changes.html#version_3_24_0) which is where support for this construct was added.  if you are on for example an older Centos / RHEL, something like that, you might have an older SQLite3 library installed.

here's how to check:

```py
$ python
Python 3.10.0 (default, Nov  5 2021, 17:23:47) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.36.0'
```
