### ISSUE TITLE
mypy plugin crashes on lambda

### ISSUE THREAD

**Issue by tchapi** [sqlalchemy/sqlalchemy#8196]
### Describe the bug

The mypy plugin crashes when encountering a lambda in a column definition (_fixable by https://github.com/sqlalchemy/sqlalchemy/pull/8195_)

### To Reproduce

```python
import uuid
from sqlalchemy import Column

class MyClass(Base):
    id = Column(String, default=lambda: uuid.uuid4(), primary_key=True)
```

### Error

```
apps/file.py:10: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "mypy/semanal.py", line 5220, in accept
  File "mypy/nodes.py", line 1020, in accept
  File "mypy/semanal.py", line 1113, in visit_class_def
  File "mypy/semanal.py", line 1191, in analyze_class
  File "mypy/semanal.py", line 1200, in analyze_class_body_common
  File "mypy/semanal.py", line 1260, in apply_class_plugin_hooks
  File "/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 258, in _base_cls_hook
    decl_class.scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 96, in scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(
  File "/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 459, in _scan_declarative_assignment_stmt
    python_type_for_type = infer.infer_type_from_right_hand_nameexpr(
  File "/lib/python3.8/site-packages/sqlalchemy/ext/mypy/infer.py", line 52, in infer_type_from_right_hand_nameexpr
    python_type_for_type = _infer_type_from_decl_column(
  File "/lib/python3.8/site-packages/sqlalchemy/ext/mypy/infer.py", line 395, in _infer_type_from_decl_column
    assert False
AssertionError:
apps/file.py:10: : note: use --pdb to drop into pdb
```

### Versions

- OS: macOS
- Python: 3.8.13
- SQLAlchemy: 1.4.39
- Database: PostgreSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg

**Comment by sqla-tester** [comment]
**Cyril Chapellier** has proposed a fix for this issue in the **rel_1_4** branch:

**Support lambda expression in mypy plugin** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3966

**Comment by sqla-tester** [comment]
**Cyril Chapellier** has proposed a fix for this issue in the **main** branch:

**Support lambda expression in mypy plugin** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3967

**Comment by CaselIT** [comment]
I've taken the liberty of taking your commit and adding you test file. You can find the changes following the likes posrted by the sqla-tester bot
