### ISSUE TITLE
support TextualSelect with ORM mappings

### ISSUE THREAD

**Issue by mdixon4** [sqlalchemy/sqlalchemy#8326]
### Describe the bug

Declarative class based on a TextualSelect object throws an error in the following script. I am aware that there are better ways to achieve what this script seems to achieve; this is a contrived example.

Note that error is only thrown at the call to `print(q)`; if this is omitted, the script completes without error.

### To Reproduce

```python
from sqlalchemy import create_engine, literal, text, Column, Integer, String, select
from sqlalchemy.orm import declarative_base, relationship

engine = create_engine("sqlite+pysqlite:///:memory:", echo=True, future=True)
Base = declarative_base()

class Book(Base):

	subq = text("""
		SELECT id, title, author_id 
		FROM publication 
		WHERE publication_type = 'BOOK'
	""").columns(
		Column('id', Integer, primary_key=True),
		Column('title', String),
		Column('author_id', Integer)
	).subquery('subq')

	__table__ = subq

	author = relationship('Author', 
		primaryjoin = lambda: Book.author_id == Author.id,
		viewonly = True
	)


class Author(Base):
	__tablename__ = 'Author'
	id = Column(Integer, primary_key=True)
	name = Column(String)


q = select(Book).join(Author)


print(q)
```

### Error

```
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    print(q)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 569, in __str__
    return str(self.compile())
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 501, in compile
    return self._compiler(dialect, **kw)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 565, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 778, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3280, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 700, in create_for_statement
    _QueryEntity.to_compile_state(
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2447, in to_compile_state
    _MapperEntity(
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 2520, in __init__
    entity._post_inspect
  File ".../env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 2147, in _post_inspect
    self._check_configure()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1924, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 3448, in _configure_registries
    _do_configure_registries(registries, cascade)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 3487, in _do_configure_registries
    mapper._post_configure_properties()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1941, in _post_configure_properties
    prop.init()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2137, in do_init
    self._setup_join_conditions()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2233, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2631, in __init__
    self._annotate_remote()
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2980, in _annotate_remote
    elif self._refers_to_parent_table():
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2957, in _refers_to_parent_table
    visitors.traverse(self.primaryjoin, {}, {"binary": visit_binary})
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 727, in traverse
    return traverse_using(iterate(obj, opts), obj, visitors)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 693, in traverse_using
    meth(target)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2951, in visit_binary
    and pt.is_derived_from(f.table)
  File ".../env/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 1641, in is_derived_from
    return self.element.is_derived_from(fromclause)
AttributeError: 'TextualSelect' object has no attribute 'is_derived_from'
``` 

### Versions

- OS: Ubuntu 20.04
- Python: 3.8.10
- SQLAlchemy: 1.4.39
- Database: Sqlite, Oracle, probably others
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): sqlite, cx_oracle

### Additional context

This construct worked previously in SQLAlchemy 1.0.x, but I am attempting to upgrade to 1.4.39 and getting this error.

**Comment by zzzeek** [comment]
hi - 

whether this is a quick fix for 1.4 or something we make into a full feature for 2.0 depends on if you can test for us.  

here is the immediate fix:

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index a6047bec17..37f533e752 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -6680,6 +6680,9 @@ class TextualSelect(SelectBase, Executable, Generative):
         ]
         self.positional = positional
 
+    def is_derived_from(self, fromclause: Optional[FromClause]) -> bool:
+        return False
+
     @HasMemoized_ro_memoized_attribute
     def selected_columns(
         self,
```

your script needs some fixes then to work, for example, there's no `select(Book).join(Author)` because no foreign keys, you need to use `select(Book).join(Book.author)`.    This script works w/ above change:

```py
from sqlalchemy import create_engine, literal, text, Column, Integer, String, select
from sqlalchemy.orm import declarative_base, relationship, foreign

engine = create_engine("sqlite+pysqlite:///:memory:", echo=True, future=True)
Base = declarative_base()

class Book(Base):

	subq = text("""
		SELECT id, title, author_id
		FROM publication
		WHERE publication_type = 'BOOK'
	""").columns(
		Column('id', Integer, primary_key=True),
		Column('title', String),
		Column('author_id', Integer)
	).subquery('subq')

	__table__ = subq

	author = relationship('Author',
		primaryjoin = lambda: foreign(Book.author_id) == Author.id,
		viewonly = True
	)


class Author(Base):
	__tablename__ = 'Author'
	id = Column(Integer, primary_key=True)
	name = Column(String)


q = select(Book).join(Book.author)


print(q)
```


we can merge the above fix w/ a simple test for 1.4.   however if there are bigger issues w/ mapping to TextualSelect then that has to be more of a 2.x change.  

can you help us test starting w/ patch above?

**Comment by mdixon4** [comment]
Hi @zzzeek thanks for the quick response!

That patch seems to do the trick. My test case and my actual code base where I first encountered this error both work as expected now. Thank you!

**Comment by JoepvandenHoven-Bluemine** [comment]
Is there any chance to `is_derived_from` is going to be added to TextualSelect at some point? Only now TextualSelect is basically the only subclass of SelectBase that misses it, and it is kind of an requirement to be able to use TextualSelect as a subquery.

I think either all selectables should implement is_derived_from (they almost all do), or the implementation of is_derived_from in SubQuery should check if is_derived_from is implemented in the selectable. Right now TextualSelect is a bit of a weird exception.
