### ISSUE TITLE
Deepcopy of AliasedClass fails first time

### ISSUE THREAD

**Issue by eseglem** [sqlalchemy/sqlalchemy#8333]
### Describe the bug

I don't have a specific need for a deep copy of the AliasedClass, but a recent change to a separate library caused it to be called in my code and break. I can prevent it from running the deep copy but I figured it was worth reporting here in case this is actually unexpected behavior.

What is especially weird about it to me is that if you run the example interactive and run a second `deepcopy(a)` it does not break that time. But I have not been able to determine why yet. 

### To Reproduce

```python
from copy import deepcopy
from sqlalchemy import Column, Integer
from sqlalchemy.orm.decl_api import declarative_base
from sqlalchemy.orm.util import aliased

Base = declarative_base()

class MyTable(Base):
    __tablename__ = "mytable"
    id = Column(Integer, primary_key=True)

a = aliased(MyTable)
deepcopy(a)
```

### Error

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    deepcopy(a)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 229, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration
``` 

### Versions

- OS: Ubuntu 20.04.4 LTS
- Python: Python 3.8.10
- SQLAlchemy: 1.4.39
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

**Comment by CaselIT** [comment]
Hi,

Thanks for responding, but I think this is unlikely to get fixed. The issue seems to be caused by a memorized property that's lazy loaded by an attribute access, causing a class dict to be populated causing the error

**Comment by zzzeek** [comment]
it works for me in 2.0, and im not really sure what happens in 1.4, because the stack trace only shows deepcopy itself.   

if someone feels like tracing out what actualyl happens, that's fine and this can be reopened but for now we dont have resources to dedicate to this.
