### ISSUE TITLE
change / possible regression when mixing Column, InstrumentedAttribute and table inheritance

### ISSUE THREAD

**Issue by torsdag** [sqlalchemy/sqlalchemy#8473]
### Describe the bug

We are migrating some code from sqlalchemy 1.2 to 1.4 and run into to some issues with code that previously worked. Were mixing the usage of sqlalchemy.sql.schema.Column and sqlalchemy.orm.attributes.InstrumentedAttribute leads to the join being added but the join condition being lost. 

Not sure if we should be expecting this to work.

### To Reproduce

```python
import sqlalchemy.orm

from sqlalchemy.ext.declarative import (
    declarative_base
)

Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, primary_key=True
    )

    attribute_type = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_on': attribute_type,
        'polymorphic_identity': 'entity'
    }


class EntityTwo(Entity):
    __tablename__ = 'entity_two'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey(Entity.id), primary_key=True
    )

    name = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_identity': 'entity_two'
    }


engine = sqlalchemy.create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sqlalchemy.orm.sessionmaker(
    bind=engine
)

session = Session()

session.add(
    EntityTwo(
        id=1,
        name='test1'
    )
)
session.add(
    EntityTwo(
        id=2,
        name='test2'

    )
)

session.commit()


result = session.query(
    sqlalchemy.inspect(EntityTwo).primary_key[0]
).filter(
    EntityTwo.name == 'test1'
)

#
# SELECT entity.id AS entity_id 
# FROM entity, entity_two 
# WHERE entity_two.name = ?
assert (len(result.all()) == 1)
```

### Error

```
reproduce.py:82: SAWarning: SELECT statement has a cartesian product between FROM element(s) "entity_two" and FROM element "entity".  Apply join condition(s) between each element to resolve.
  assert (len(result.all()) == 1)
Traceback (most recent call last):
  File "reproduce.py", line 82, in <module>
    assert (len(result.all()) == 1)
AssertionError
``` 

### Versions

- OS: Fedora 36
- Python: python 2.7 
- SQLAlchemy: 1.4.41
- Database: sqlite, mariadb

**Comment by zzzeek** [comment]
hey there -

I get the same result in 1.2, 1.3, and 1.4, it does not render the JOIN because when you SELECT from a plain Column (that is not a special annotated version used in the ORM, but currently is not what mapper.primary_key contains), it just sees the Table and not the EntityTwo mapper.

So the "works in 1.2" part of this is strange as that doesn't work on my end, but overall the correct way to ensure the source entity is to use select_from()

```py
result = session.query(
    sqlalchemy.inspect(EntityTwo).primary_key[0]
).select_from(EntityTwo).filter(
    EntityTwo.name == 'test1'
)
```

that will work in all versions.

**Comment by torsdag** [comment]
Hey, 

Sorry about that. It looks like I failed miserably when attempting to simplify the example, below is a an example that works in 1.2 but not 1.4. It is the outer join condition that joins "incorrectly". 

### To Reproduce

```
import sqlalchemy.orm

from sqlalchemy.ext.declarative import (
    declarative_base
)

Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, primary_key=True
    )

    attribute_type = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_on': attribute_type,
        'polymorphic_identity': 'entity'
    }


class EntityTwo(Entity):
    __tablename__ = 'entity_two'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey(Entity.id), primary_key=True
    )

    name = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_identity': 'entity_two'
    }


engine = sqlalchemy.create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sqlalchemy.orm.sessionmaker(
    bind=engine
)

session = Session()

session.add(
    EntityTwo(
        id=1,
        name='test1'
    )
)
session.add(
    EntityTwo(
        id=2,
        name='test2'

    )
)

session.commit()


result = session.query(
    sqlalchemy.inspect(EntityTwo).primary_key[0]
).join(
    EntityTwo,
    EntityTwo.id == Entity.id
).filter(
    EntityTwo.name == 'test1'
)

#
# SELECT entity.id AS entity_id
# FROM entity JOIN (entity AS entity_1 JOIN entity_two AS entity_two_1 ON entity_1.id = entity_two_1.id) ON entity_two_1.id = entity_1.id
# WHERE entity_two_1.name = ?
assert (len(result.all()) == 1)

```

### Error
```
reproduce.py:85: SAWarning: An alias is being generated automatically against joined entity mapped class EntityTwo->entity_two due to overlapping tables.  This is a legacy pattern which may be deprecated in a later release.  Use the aliased(<entity>, flat=True) construct explicitly, see the linked example. (Background on this error at: https://sqlalche.me/e/14/xaj2)
  assert (len(result.all()) == 1)
Traceback (most recent call last):
  File "reproduce.py", line 85, in <module>
    assert (len(result.all()) == 1)
AssertionError

```

query from 1.2

```
SELECT entity.id AS entity_id 
FROM entity JOIN (entity AS entity_1 JOIN entity_two AS entity_two_1 ON entity_1.id = entity_two_1.id) ON entity_two_1.id = entity.id 
WHERE entity_two_1.name = ?
```
query from 1.4

```
SELECT entity.id AS entity_id 
FROM entity JOIN (entity AS entity_1 JOIN entity_two AS entity_two_1 ON entity_1.id = entity_two_1.id) ON entity_two_1.id = entity_1.id 
WHERE entity_two_1.name = ?
```

**Comment by zzzeek** [comment]
OK yes there's a warning there, that's why this is not working - joining from EntityTwo to Entity is not really valid because EntityTwo *is* an Entity.      use an aliased() as the warning indicates, and also you want to have a [select_from()](https://docs.sqlalchemy.org/en/14/tutorial/data_select.html#explicit-from-clauses-and-joins) in there as it is ambiguous where you want to join from

```py
result = session.query(
    sqlalchemy.inspect(EntityTwo).primary_key[0]
).select_from(ent).join(
    EntityTwo,
    EntityTwo.id == ent.id
).filter(
    EntityTwo.name == 'test1'
)

```

**Comment by torsdag** [comment]
makes sense, just wanted to double check since it worked in 1.2

cheers

**Comment by zzzeek** [comment]
1.3 and former just had a huge complex guessing thing going on, so it was all luck :)

**Comment by torsdag** [comment]
haha cool, glad we have the warnings!

cheers
