### ISSUE TITLE
Cannot connect to Azure Synapse when lacking "view database state" permission

### ISSUE THREAD

**Issue by cdcadman** [sqlalchemy/sqlalchemy#8475]
### Describe the bug

If a user lacks the "view database state" permission for Azure Synapse, that user cannot connect to it with sqlalchemy version 1.4.40, because the user does not have permission to select from the system view `sys.dm_pdw_nodes_exec_sessions`.  Prior to version 1.4.39, this exception was handled within sqlalchemy and Engine.connect() returned a sqlalchemy Connection rather than raising the exception.  This changed with pull request #8233 .

### To Reproduce

```python
from urllib.parse import quote_plus
from sqlalchemy import create_engine

username = input("Username: ")
password = input("Password: ")
server = input("Server: ") #tcp:<server name>.database.windows.net,1433
database = input("Database: ") #Azure Synapse Database on the server
driver = "{ODBC Driver 17 for SQL Server}"
connstr = f"Driver={driver};Server={server};Database={database};Authentication=ActiveDirectoryPassword;UID={username};PWD={password}"
ce_params = {"odbc_connect": quote_plus(connstr), "autocommit": "true"}

engine = create_engine("mssql+pyodbc:///?" + "&".join(f"{key}={value}" for key, value in ce_params.items()))
engine.connect()
```

### Error

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 343, in __call__
    fn(*args, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\create.py", line 674, in first_connect
    dialect.initialize(c)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2868, in initialize
    super(MSDialect, self).initialize(connection)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 420, in initialize
    self.default_isolation_level = self.get_default_isolation_level(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 486, in get_default_isolation_level
    return self.get_isolation_level(dbapi_conn)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2845, in get_isolation_level
    cursor.execute(
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]User does not have permission to perform this action. (6004) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Temp\test_azure_synapse.py", line 13, in <module>
    engine.connect()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 343, in __call__
    fn(*args, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\create.py", line 674, in first_connect
    dialect.initialize(c)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2868, in initialize
    super(MSDialect, self).initialize(connection)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 420, in initialize
    self.default_isolation_level = self.get_default_isolation_level(
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 486, in get_default_isolation_level
    return self.get_isolation_level(dbapi_conn)
  File "C:\Program Files\Python310\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2845, in get_isolation_level
    cursor.execute(
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]User does not have permission to perform this action. (6004) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/14/f405)
``` 

### Versions

- OS: Microsoft Windows 10 Enterprise
- Python: 3.10
- SQLAlchemy: 1.4.40
- Database: Microsoft Azure SQL Data Warehouse - 10.0.15670.0 Aug 26 2022 18:59:26 Copyright (c) Microsoft Corporation
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

**Comment by zzzeek** [comment]
hi yup, I knew that would break something

cc @gordthompson

**Comment by zzzeek** [comment]
hi -

I'm not sure how this would have worked in 1.4.39 because we query from both ``dm_exec_sessions`` and ``dm_pdw_nodes_exec_sessions``, and if we can't read either, we raise an error anyway.

can someone tell me if this Azure database has **both views present** ?   

@cdcadman can you tell me, running SQLAlchemy 1.4.39 the output of:


```py

e = create_engine("mssql+pyodbc://...url ...")
e.connect().close()
print(e.dialect.default_isolation_level)

```

**Comment by cdcadman** [comment]
@zzzeek sys.dm_pdw_nodes_exec_sessions is present in this database, but sys.dm_exec_sessions is not present.  If the user does not have "view database state" permission:
* The user can still query sys.system_views to determine that sys.dm_pdw_nodes_exec_sessions is present.
* `engine.dialect.default_isolation_level` is None on sqlalchemy version 1.4.39 (the code you asked about prints out "None")
* Sqlalchemy also raises this warning on version 1.4.39:

`SAWarning: Could not fetch transaction isolation level, tried views: ('sys.dm_exec_sessions', 'sys.dm_pdw_nodes_exec_sessions'); final error was: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]User does not have permission to perform this action. (6004) (SQLExecDirectW)')
  engine.connect().close()`

**Comment by cdcadman** [comment]
@zzzeek , the default.DefaultDialect class catches the NotImplementedError, which is what gets raised by get_isolation_level in sqlalchemy 1.4.39

            try:
                self.default_isolation_level = self.get_default_isolation_level(
                    connection.connection
                )
            except NotImplementedError:
                self.default_isolation_level = None

**Comment by zzzeek** [comment]
OK, then we will set it to None, good enough thanks!

**Comment by zzzeek** [comment]
hi @cdcadman  - 

since we don't have live access to this database, to ensure the next SQLAlchemy release works with your database, this is the patch we will be merging for 1.4.41:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index ee6ce87696..9d57c0e931 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2859,10 +2859,13 @@ class MSDialect(default.DefaultDialect):
             )
             row = cursor.fetchone()
             assert row is not None
-            val = row[0]
+            val = row[0].upper()
+        except self.dbapi.Error:
+            # e.g., permissions error on dm_pdw_nodes_exec_sessions view
+            val = None
         finally:
             cursor.close()
-        return val.upper()
+        return val
 
     def initialize(self, connection):
         super(MSDialect, self).initialize(connection)

```


if you are able to apply this patch to your local 1.4.40 release and confirm you are again able to access your database fully, that would give us some more confidence that this fix is acceptable.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix Azure Synapse connection error** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4065

**Comment by zzzeek** [comment]
hi @cdcadman  - 

since we don't have live access to this database, to ensure the next SQLAlchemy release works with your database, this is the patch we will be merging for 1.4.41:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index ee6ce87696..0d0a4b8f5e 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2842,27 +2842,40 @@ class MSDialect(default.DefaultDialect):
                 )

             view_name = "sys.{}".format(row[0])
-            cursor.execute(
-                """
-                    SELECT CASE transaction_isolation_level
-                    WHEN 0 THEN NULL
-                    WHEN 1 THEN 'READ UNCOMMITTED'
-                    WHEN 2 THEN 'READ COMMITTED'
-                    WHEN 3 THEN 'REPEATABLE READ'
-                    WHEN 4 THEN 'SERIALIZABLE'
-                    WHEN 5 THEN 'SNAPSHOT' END AS TRANSACTION_ISOLATION_LEVEL
-                    FROM {}
-                    where session_id = @@SPID
-                """.format(
-                    view_name
+
+            try:
+                cursor.execute(
+                    """
+                        SELECT CASE transaction_isolation_level
+                        WHEN 0 THEN NULL
+                        WHEN 1 THEN 'READ UNCOMMITTED'
+                        WHEN 2 THEN 'READ COMMITTED'
+                        WHEN 3 THEN 'REPEATABLE READ'
+                        WHEN 4 THEN 'SERIALIZABLE'
+                        WHEN 5 THEN 'SNAPSHOT' END
+                        AS TRANSACTION_ISOLATION_LEVEL
+                        FROM {}
+                        where session_id = @@SPID
+                    """.format(
+                        view_name
+                    )
                 )
-            )
-            row = cursor.fetchone()
-            assert row is not None
-            val = row[0]
+            except self.dbapi.Error as err:
+                util.raise_(
+                    NotImplementedError(
+                        "Can't fetch isolation level;  encountered "
+                        "error {} when "
+                        'attempting to query the "{}" view.'.format(
+                            err, view_name
+                        )
+                    ),
+                    from_=err,
+                )
+            else:
+                row = cursor.fetchone()
+                return row[0].upper()
         finally:
             cursor.close()
-        return val.upper()

     def initialize(self, connection):
         super(MSDialect, self).initialize(connection)
diff --git a/test/dialect/mssql/test_engine.py b/test/dialect/mssql/test_engine.py

```


if you are able to apply this patch to your local 1.4.40 release and confirm you are again able to access your database fully, that would give us some more confidence that this fix is acceptable.

**Comment by cdcadman** [comment]
Hi @zzzeek , it works perfectly.  Thank you and @gordthompson for quickly fixing this!
