### ISSUE TITLE
Timeout on SQL Queries with ` in password

### ISSUE THREAD

**Issue by blakeromano** [sqlalchemy/sqlalchemy#8485]
### Describe the bug

When there is a ` in the password of postgres credentials it will connect, but will timeout on queries.

### To Reproduce

```python
Use a back tick in a postgres password.
```

### Error

```
Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
-- | --

  | Sep 2, 2022 @ 18:49:41.182 | return self.dbapi.connect(*cargs, **cparams)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 747, in connect

  | Sep 2, 2022 @ 18:49:41.182 | await_only(self.asyncpg.connect(*arg, **kw)),

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only

  | Sep 2, 2022 @ 18:49:41.182 | return current.driver.switch(awaitable)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn

  | Sep 2, 2022 @ 18:49:41.182 | value = await result

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2045, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return await connect_utils._connect(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 790, in _connect

  | Sep 2, 2022 @ 18:49:41.182 | raise last_error

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 776, in _connect

  | Sep 2, 2022 @ 18:49:41.182 | return await _connect_addr(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 676, in _connect_addr

  | Sep 2, 2022 @ 18:49:41.182 | return await __connect_addr(params, timeout, True, *args)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 726, in __connect_addr

  | Sep 2, 2022 @ 18:49:41.182 | await compat.wait_for(connected, timeout=timeout)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for

  | Sep 2, 2022 @ 18:49:41.182 | return await asyncio.wait_for(fut, timeout)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for

  | Sep 2, 2022 @ 18:49:41.182 | raise exceptions.TimeoutError() from exc

  | Sep 2, 2022 @ 18:49:41.182 | asyncio.exceptions.TimeoutError

  | Sep 2, 2022 @ 18:49:41.182 | ERROR:uvicorn.error:Exception in ASGI application

  | Sep 2, 2022 @ 18:49:41.182 | Traceback (most recent call last):

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for

  | Sep 2, 2022 @ 18:49:41.182 | return fut.result()

  | Sep 2, 2022 @ 18:49:41.182 | asyncio.exceptions.CancelledError

  | Sep 2, 2022 @ 18:49:41.182 | -

  | Sep 2, 2022 @ 18:49:41.182 | The above exception was the direct cause of the following exception:

  | Sep 2, 2022 @ 18:49:41.182 | -

  | Sep 2, 2022 @ 18:49:41.182 | Traceback (most recent call last):

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi

  | Sep 2, 2022 @ 18:49:41.182 | result = await app(self.scope, self.receive, self.send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | return await self.app(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | await super().__call__(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | await self.middleware_stack(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | raise exc

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | await self.app(scope, receive, _send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 57, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | task_group.cancel_scope.cancel()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__

  | Sep 2, 2022 @ 18:49:41.182 | raise exceptions[0]

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 30, in coro

  | Sep 2, 2022 @ 18:49:41.182 | await self.app(scope, request.receive, send_stream.send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | raise exc

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | await self.app(scope, receive, sender)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__

  | Sep 2, 2022 @ 18:49:41.182 | await route.handle(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle

  | Sep 2, 2022 @ 18:49:41.182 | await self.app(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app

  | Sep 2, 2022 @ 18:49:41.182 | response = await func(request)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app

  | Sep 2, 2022 @ 18:49:41.182 | solved_result = await solve_dependencies(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 496, in solve_dependencies

  | Sep 2, 2022 @ 18:49:41.182 | solved_result = await solve_dependencies(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 525, in solve_dependencies

  | Sep 2, 2022 @ 18:49:41.182 | solved = await call(**sub_values)

  | Sep 2, 2022 @ 18:49:41.182 | File "/app/./src/middlewares/auth_middleware.py", line 22, in auth_middleware

  | Sep 2, 2022 @ 18:49:41.182 | token = await token_repo.get_token(token)

  | Sep 2, 2022 @ 18:49:41.182 | File "/app/./src/repositories/access_token_repository.py", line 30, in get_token

  | Sep 2, 2022 @ 18:49:41.182 | result = await self.session.execute(stmt)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 143, in execute

  | Sep 2, 2022 @ 18:49:41.182 | return await greenlet_spawn(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn

  | Sep 2, 2022 @ 18:49:41.182 | result = context.throw(*sys.exc_info())

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute

  | Sep 2, 2022 @ 18:49:41.182 | conn = self._connection_for_bind(bind)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind

  | Sep 2, 2022 @ 18:49:41.182 | return self._transaction._connection_for_bind(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind

  | Sep 2, 2022 @ 18:49:41.182 | conn = bind.connect()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 419, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return super(Engine, self).connect()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return self._connection_cls(self, close_with_result=close_with_result)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__

  | Sep 2, 2022 @ 18:49:41.182 | else engine.raw_connection()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection

  | Sep 2, 2022 @ 18:49:41.182 | return self._wrap_pool_connect(self.pool.connect, _connection)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect

  | Sep 2, 2022 @ 18:49:41.182 | return fn()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return _ConnectionFairy._checkout(self)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout

  | Sep 2, 2022 @ 18:49:41.182 | fairy = _ConnectionRecord.checkout(pool)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout

  | Sep 2, 2022 @ 18:49:41.182 | rec = pool._do_get()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get

  | Sep 2, 2022 @ 18:49:41.182 | self._dec_overflow()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

  | Sep 2, 2022 @ 18:49:41.182 | compat.raise_(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

  | Sep 2, 2022 @ 18:49:41.182 | raise exception

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get

  | Sep 2, 2022 @ 18:49:41.182 | return self._create_connection()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection

  | Sep 2, 2022 @ 18:49:41.182 | return _ConnectionRecord(self)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__

  | Sep 2, 2022 @ 18:49:41.182 | self.__connect()

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect

  | Sep 2, 2022 @ 18:49:41.182 | pool.logger.debug("Error on connect(): %s", e)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

  | Sep 2, 2022 @ 18:49:41.182 | compat.raise_(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

  | Sep 2, 2022 @ 18:49:41.182 | raise exception

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect

  | Sep 2, 2022 @ 18:49:41.182 | connection = pool._invoke_creator(self)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return dialect.connect(*cargs, **cparams)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return self.dbapi.connect(*cargs, **cparams)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 747, in connect

  | Sep 2, 2022 @ 18:49:41.182 | await_only(self.asyncpg.connect(*arg, **kw)),

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only

  | Sep 2, 2022 @ 18:49:41.182 | return current.driver.switch(awaitable)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn

  | Sep 2, 2022 @ 18:49:41.182 | value = await result

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2045, in connect

  | Sep 2, 2022 @ 18:49:41.182 | return await connect_utils._connect(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 790, in _connect

  | Sep 2, 2022 @ 18:49:41.182 | raise last_error

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 776, in _connect

  | Sep 2, 2022 @ 18:49:41.182 | return await _connect_addr(

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 676, in _connect_addr

  | Sep 2, 2022 @ 18:49:41.182 | return await __connect_addr(params, timeout, True, *args)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 726, in __connect_addr

  | Sep 2, 2022 @ 18:49:41.182 | await compat.wait_for(connected, timeout=timeout)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for

  | Sep 2, 2022 @ 18:49:41.182 | return await asyncio.wait_for(fut, timeout)

  | Sep 2, 2022 @ 18:49:41.182 | File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for

  | Sep 2, 2022 @ 18:49:41.182 | raise exceptions.TimeoutError() from exc

  | Sep 2, 2022 @ 18:49:41.182 | asyncio.exceptions.TimeoutError

  | Sep 2, 2022 @ 18:49:41.181 | ERROR:    Exception in ASGI application

  | Sep 2, 2022 @ 18:49:41.181 | Traceback (most recent call last):

  | Sep 2, 2022 @ 18:49:41.181 | asyncio.exceptions.CancelledError

  | Sep 2, 2022 @ 18:49:41.181 | -

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | await super().__call__(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.181 | await self.middleware_stack(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.181 | raise exc

  | Sep 2, 2022 @ 18:49:41.181 | await self.app(scope, receive, _send)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__

  | Sep 2, 2022 @ 18:49:41.181 | await self.app(scope, request.receive, send_stream.send)

  | Sep 2, 2022 @ 18:49:41.181 | raise exc

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | await route.handle(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.181 | await self.app(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 496, in solve_dependencies

  | Sep 2, 2022 @ 18:49:41.181 | solved = await call(**sub_values)

  | Sep 2, 2022 @ 18:49:41.181 | File "/app/./src/middlewares/auth_middleware.py", line 22, in auth_middleware

  | Sep 2, 2022 @ 18:49:41.181 | File "/app/./src/repositories/access_token_repository.py", line 30, in get_token

  | Sep 2, 2022 @ 18:49:41.181 | result = await self.session.execute(stmt)

  | Sep 2, 2022 @ 18:49:41.181 | return await greenlet_spawn(

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn

  | Sep 2, 2022 @ 18:49:41.181 | conn = self._connection_for_bind(bind)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for

  | Sep 2, 2022 @ 18:49:41.181 | return fut.result()

  | Sep 2, 2022 @ 18:49:41.181 | -

  | Sep 2, 2022 @ 18:49:41.181 | The above exception was the direct cause of the following exception:

  | Sep 2, 2022 @ 18:49:41.181 | Traceback (most recent call last):

  | Sep 2, 2022 @ 18:49:41.181 | result = await app(self.scope, self.receive, self.send)

  | Sep 2, 2022 @ 18:49:41.181 | return await self.app(scope, receive, send)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 57, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | task_group.cancel_scope.cancel()

  | Sep 2, 2022 @ 18:49:41.181 | raise exceptions[0]

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 30, in coro

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__

  | Sep 2, 2022 @ 18:49:41.181 | await self.app(scope, receive, sender)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app

  | Sep 2, 2022 @ 18:49:41.181 | response = await func(request)

  | Sep 2, 2022 @ 18:49:41.181 | solved_result = await solve_dependencies(

  | Sep 2, 2022 @ 18:49:41.181 | solved_result = await solve_dependencies(

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 525, in solve_dependencies

  | Sep 2, 2022 @ 18:49:41.181 | token = await token_repo.get_token(token)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 143, in execute

  | Sep 2, 2022 @ 18:49:41.181 | result = context.throw(*sys.exc_info())

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind

  | Sep 2, 2022 @ 18:49:41.181 | return self._transaction._connection_for_bind(

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind

  | Sep 2, 2022 @ 18:49:41.181 | conn = bind.connect()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 419, in connect

  | Sep 2, 2022 @ 18:49:41.181 | return super(Engine, self).connect()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect

  | Sep 2, 2022 @ 18:49:41.181 | return self._connection_cls(self, close_with_result=close_with_result)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__

  | Sep 2, 2022 @ 18:49:41.181 | else engine.raw_connection()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection

  | Sep 2, 2022 @ 18:49:41.181 | return self._wrap_pool_connect(self.pool.connect, _connection)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect

  | Sep 2, 2022 @ 18:49:41.181 | return fn()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect

  | Sep 2, 2022 @ 18:49:41.181 | return _ConnectionFairy._checkout(self)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout

  | Sep 2, 2022 @ 18:49:41.181 | fairy = _ConnectionRecord.checkout(pool)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout

  | Sep 2, 2022 @ 18:49:41.181 | rec = pool._do_get()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get

  | Sep 2, 2022 @ 18:49:41.181 | self._dec_overflow()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

  | Sep 2, 2022 @ 18:49:41.181 | compat.raise_(

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

  | Sep 2, 2022 @ 18:49:41.181 | raise exception

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get

  | Sep 2, 2022 @ 18:49:41.181 | return self._create_connection()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection

  | Sep 2, 2022 @ 18:49:41.181 | return _ConnectionRecord(self)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__

  | Sep 2, 2022 @ 18:49:41.181 | self.__connect()

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect

  | Sep 2, 2022 @ 18:49:41.181 | pool.logger.debug("Error on connect(): %s", e)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

  | Sep 2, 2022 @ 18:49:41.181 | compat.raise_(

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

  | Sep 2, 2022 @ 18:49:41.181 | raise exception

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect

  | Sep 2, 2022 @ 18:49:41.181 | connection = pool._invoke_creator(self)

  | Sep 2, 2022 @ 18:49:41.181 | File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect

  | Sep 2, 2022 @ 18:49:41.181 | return dialect.connect(*cargs, **cparams)

  | Sep 2, 2022 @ 18:49:41.178 | INFO:     127.0.0.6:55821 - "POST /v1.0/employees/filter HTTP/1.1" 500 Internal Server Error

```

### Versions

- OS: Docker
- Python: 3.9
- SQLAlchemy: 1.4.23
- Database: Postgres

**Comment by zzzeek** [comment]
please escape special characters in passwords:

https://docs.sqlalchemy.org/en/14/core/engines.html#escaping-special-characters-such-as-signs-in-passwords
