### ISSUE TITLE
Removing a key from PostgreSQL's JSONB causes TypeError: unsupported operand type(s) for -: 'dict' and 'str'

### ISSUE THREAD

**Issue by marcinbarczynski** [sqlalchemy/sqlalchemy#8507]
### Describe the bug

Removing a key from JSONB object raises an exception in synchronizing code. It works fine with SQLAlchemy 1.3.24.

### To Reproduce

```python
#!/usr/bin/python
from sqlalchemy import BigInteger, Column
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

engine = create_engine("postgresql://URI", echo=True)
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()


class Demo(Base):
    __tablename__ = "demo"

    id = Column(BigInteger, primary_key=True)
    params = Column(JSONB, nullable=False, server_default="{}")


Base.metadata.drop_all(bind=engine)
Base.metadata.create_all(bind=engine)

target = Demo(params={"foo1": "bar", "foo2": "baz"})
session.add(target)
session.flush()
session.expunge(target)

# works fine if the next line is commented
prev_object = session.query(Demo).get(target.id)
session.query(Demo).filter(Demo.id == target.id).update(
    {Demo.params: Demo.params - "foo1"},
    # {Demo.params: {"foo2": "baz"}},  # this also works fine
    synchronize_session="fetch",
)
session.commit()
```

### Error

```
2022-09-12 14:59:06,134 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-09-12 14:59:06,135 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-09-12 14:59:06,135 INFO sqlalchemy.engine.Engine select current_schema()
2022-09-12 14:59:06,135 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-09-12 14:59:06,136 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-09-12 14:59:06,136 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-09-12 14:59:06,136 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-09-12 14:59:06,137 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-09-12 14:59:06,137 INFO sqlalchemy.engine.Engine [generated in 0.00011s] {'name': 'demo'}
2022-09-12 14:59:06,138 INFO sqlalchemy.engine.Engine 
DROP TABLE demo
2022-09-12 14:59:06,138 INFO sqlalchemy.engine.Engine [no key 0.00007s] {}
2022-09-12 14:59:06,139 INFO sqlalchemy.engine.Engine COMMIT
2022-09-12 14:59:06,148 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-09-12 14:59:06,149 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-09-12 14:59:06,149 INFO sqlalchemy.engine.Engine [cached since 0.01203s ago] {'name': 'demo'}
2022-09-12 14:59:06,152 INFO sqlalchemy.engine.Engine 
CREATE TABLE demo (
	id BIGSERIAL NOT NULL, 
	params JSONB DEFAULT '{}' NOT NULL, 
	PRIMARY KEY (id)
)


2022-09-12 14:59:06,152 INFO sqlalchemy.engine.Engine [no key 0.00029s] {}
2022-09-12 14:59:06,163 INFO sqlalchemy.engine.Engine COMMIT
2022-09-12 14:59:06,167 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-09-12 14:59:06,170 INFO sqlalchemy.engine.Engine INSERT INTO demo (params) VALUES (%(params)s) RETURNING demo.id
2022-09-12 14:59:06,170 INFO sqlalchemy.engine.Engine [generated in 0.00053s] {'params': '{"foo1": "bar", "foo2": "baz"}'}
2022-09-12 14:59:06,180 INFO sqlalchemy.engine.Engine SELECT demo.id AS demo_id, demo.params AS demo_params 
FROM demo 
WHERE demo.id = %(pk_1)s
2022-09-12 14:59:06,180 INFO sqlalchemy.engine.Engine [generated in 0.00062s] {'pk_1': 1}
2022-09-12 14:59:06,190 INFO sqlalchemy.engine.Engine UPDATE demo SET params=(demo.params - %(params_1)s) WHERE demo.id = %(id_1)s RETURNING demo.id
2022-09-12 14:59:06,190 INFO sqlalchemy.engine.Engine [generated in 0.00051s] {'params_1': 'foo1', 'id_1': 1}
Traceback (most recent call last):
  File "/media/q/Encrypted/q/q/../demo-sqlalchemy.py", line 33, in <module>
    session.query(Demo).filter(Demo.id == target.id).update(
  File "/home/q/.virtualenvs/sf/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3297, in update
    result = self.session.execute(
  File "/home/q/.virtualenvs/sf/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1715, in execute
    result = compile_state_cls.orm_setup_cursor_result(
  File "/home/q/.virtualenvs/sf/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1891, in orm_setup_cursor_result
    cls._do_post_synchronize_fetch(session, result, update_options)
  File "/home/q/.virtualenvs/sf/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 2430, in _do_post_synchronize_fetch
    dict_[key] = update_options._value_evaluators[key](obj)
  File "/home/q/.virtualenvs/sf/lib/python3.10/site-packages/sqlalchemy/orm/evaluator.py", line 211, in evaluate
    return operator(eval_left(obj), eval_right(obj))
TypeError: unsupported operand type(s) for -: 'dict' and 'str'
``` 

### Versions

- OS: Ubuntu
- Python: 3.10.4
- SQLAlchemy: 1.4.41
- Database: PostgreSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2 2.9.3

**Comment by CaselIT** [comment]
Strange that the evaluation is performed even when the strategy is set to `fetch`

**Comment by zzzeek** [comment]
It's evaluating the SET clause, not the WHERE clause.  This might be something new in 1.4

**Comment by CaselIT** [comment]
Yes, but since it has fetched the rows, maybe it does not need to? It probably has a reason for doing this, just mentioning that it seems unnecessary

**Comment by zzzeek** [comment]
I'm not totally sure why it's not fetching the data here , I would have to look.  But it suggests it wasn't yet implemented that way and if that's the case, I'm not going to change that implementation in 1.4.  there's way more flexibility with RETURNING in my new patches so a total change in methodology would be in there.

**Comment by marcinbarczynski** [comment]
Thanks for the fast analysis. I noticed the fix is scheduled for the next release. Any workaround until then?

**Comment by zzzeek** [comment]
OK the evaluator is used correctly here, it just can't detect that this particular expression is not evaluable.

so you can either use synchronize_session=False, or use an expression that won't be mistaken as evaluable:   `literal_column("params - 'foo1'")`.    it's too bad PG does not seem to have a jsonb_del() function here.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Add type awareness to evaluator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4075
