### ISSUE TITLE
Cannot connect to Azure SQL CRM database with SQLAlchemy version 1.4.40 and 1.4.41

### ISSUE THREAD

**Issue by Carnuntum** [sqlalchemy/sqlalchemy#8525]
### Describe the bug

When trying to connect to a Microsoft Dynamics CRM Database via Azure Active Directory authentication the Error below appears with SQLAlchemy version 1.4.40 and 1.4.41. Earlier versions (e.g. 1.4.39) work with a warning that the transaction isolation level cannot be fetched. The error happens both on windows and linux. This issue may be related to #8475.

The warning with version 1.4.39 may indicated that these system views do not exist in the database (as mentioned in [here](https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/455335/configure-odbc-to-connect-to-dynamics-crm))

### To Reproduce

```python
connection_string = (
    "Driver={ODBC Driver 18 for SQL Server};"
    "Server=<CRM-Server>;"
    "Database=<Database>;"
    f"UID={os.environ['USER']};"
    f"PWD={os.environ['PWD']};"
    "Authentication=ActiveDirectoryPassword;"
    "Port=<Port>;"
)

connection_url = URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})

engine = create_engine(connection_url, echo = True)

engine.connect()
```

### Error

2022-09-15 09:15:22,454 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2022-09-15 09:15:22,454 INFO sqlalchemy.engine.Engine [raw sql] ()
This Connection is closed
2022-09-15 09:15:23,252 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2022-09-15 09:15:23,252 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-09-15 09:15:23,385 INFO sqlalchemy.engine.Engine SELECT schema_name()
2022-09-15 09:15:23,385 INFO sqlalchemy.engine.Engine [generated in 0.00019s] ()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 674, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/dialects/mssql/base.py", line 2868, in initialize
    super(MSDialect, self).initialize(connection)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 420, in initialize
    self.default_isolation_level = self.get_default_isolation_level(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 486, in get_default_isolation_level
    return self.get_isolation_level(dbapi_conn)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/dialects/mssql/base.py", line 2833, in get_isolation_level
    cursor.execute(
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid table name system_views for schema sys. Line:1, Position:18\nRequestId: TDS;6ceef7be-73a6-b503-b4db-42894f74f50b;11\nTime: 2022-09-15T09:15:23.7180440Z (40000) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//test_crm_connect.py", line 34, in <module>
    engine.connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 1695, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 674, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/dialects/mssql/base.py", line 2868, in initialize
    super(MSDialect, self).initialize(connection)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 420, in initialize
    self.default_isolation_level = self.get_default_isolation_level(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 486, in get_default_isolation_level
    return self.get_isolation_level(dbapi_conn)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/dialects/mssql/base.py", line 2833, in get_isolation_level
    cursor.execute(
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid table name system_views for schema sys. Line:1, Position:18\nRequestId: TDS;6ceef7be-73a6-b503-b4db-42894f74f50b;11\nTime: 2022-09-15T09:15:23.7180440Z (40000) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/14/f405)
[error_windows.txt](https://github.com/sqlalchemy/sqlalchemy/files/9574277/error_windows.txt)

### Versions

- OS: Ubuntu 22.04 lts / Windows 10 Pro 10.0.19043 Build 19043
- Python: 3.9.7 / 3.10.4
- SQLAlchemy: 1.4.40 1.4.41 
- Database: Microsoft SQL Azure (RTM) - 12.0.2000.8   Aug 10 2022 15:14:09   Copyright (C) 2022 Microsoft Corporation 
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

### Additional context

The warning in version 1.4.39 is this:

`C:\temp\test_crm_connect.py:38: SAWarning: Could not fetch transaction isolation level, tried views: ('sys.dm_exec_sessions', 'sys.dm_pdw_nodes_exec_sessions'); final error was: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid table name dm_pdw_nodes_exec_sessions for schema sys. Line:9, Position:26\nRequestId: TDS;92b1e9b0-d466-4f15-a97c-9bb1c3d1e50b;13\nTime: 2022-09-15T09:40:19.7237219Z (40000) (SQLExecDirectW)')`

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. Looking at the code we probably need to extend the try / catch to cover also the first query that tries to select what table to query

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**catch exception for system_views also** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4079

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**catch exception for system_views also** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4080
