### ISSUE TITLE
The database name is not added to the url created using URL.create()

### ISSUE THREAD

**Issue by Shandeika** [sqlalchemy/sqlalchemy#8534]
### Describe the bug

When creating a connection URL using `URL.create()`, I get an incomplete string with the URL.
Expected:
`mysql+pymysql://login:pass@hostname.com:3306/database_name`
Receive:
`mysql+pymysql://login:pass@hostname.com:3306`

### To Reproduce

```python
DB_URL = URL.create(drivername="mysql+pymysql", username=Config.DB_LOGIN, password=Config.DB_PASSWORD,
                    host=Config.DB_HOST, port=Config.DB_PORT, database=Config.DB_DATABASE)
```

### Error

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MrSha\Documents\Projects\GamingBot\main.py", line 5, in <module>
    import bot.models.database as database
  File "C:\Users\MrSha\Documents\Projects\GamingBot\bot\models\database.py", line 71, in <module>
    create_tables(engine)
  File "C:\Users\MrSha\Documents\Projects\GamingBot\bot\models\db_models.py", line 42, in create_tables
    Base.metadata.create_all(engine)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\schema.py", line 4917, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\ddl.py", line 851, in visit_metadata
    self.traverse_single(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\ddl.py", line 895, in visit_table
    self.connection.execute(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\sql\ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\MrSha\.virtualenvs\GamingBot-WZuoFyRn\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1046, 'No database selected')
``` 

### Versions

- OS: Windows 10 Pro
- Python: 3.10.2
- SQLAlchemy: 1.4.40
- Database: MySQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql

**Comment by CaselIT** [comment]
Hi,

Can't reproduce. Try
```py
from sqlalchemy.engine import URL

u = URL.create(
    drivername="mysql+pymysql",
    username="DB_LOGIN",
    password="DB_PASSWORD",
    host="DB_HOST",
    port="1234",
    database="DB_DATABASE",
)
print(u)
```
this prints `mysql+pymysql://DB_LOGIN:DB_PASSWORD@DB_HOST:1234/DB_DATABASE`

Please provide a runnable MCVE. Take a look at these for examples https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22+is%3Aclosed

**Comment by Shandeika** [comment]
I double-checked everything, it turned out I'm stupid :) Sorry for the false issue

**Comment by CaselIT** [comment]
No problem! The important thing is that it's now resolved!
