### ISSUE TITLE
select(A).join(B).with_only_columns(A.c.id) breaks filter_by()

### ISSUE THREAD

**Issue by groner** [sqlalchemy/sqlalchemy#8601]
### Describe the bug

Doing `select(A).join(B).with_only_columns(A.c.id).filter_by(other=X)`
produces `InvalidRequestError: Entity namespace for "A.id" has no property "other"`.

But

Doing `select(A).with_only_columns(A.c.id).join(B).filter_by(other=X)`
produces a working query.

### To Reproduce

```python
import sqlalchemy as sa


md = sa.MetaData()

A = sa.Table(
    'A', md,
    sa.Column('id'))

B = sa.Table(
    'B', md,
    sa.Column('id'),
    sa.Column('A_id', sa.ForeignKey(A.c.id)),
    sa.Column('other'))

q = sa.select(A)
q = q.join(B)
# Moving q.join() below q.with_only_columns() results in a working query.
q = q.with_only_columns(A.c.id)
q = q.filter_by(other=1)
```

### Error

```
Traceback (most recent call last):
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 1223, in __getattr__
    return self._index[key]
KeyError: 'other'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 1694, in _entity_namespace_key
    return getattr(ns, key)
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 1225, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
AttributeError: other

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqlalchemy-with-entities-bug.py", line 20, in <module>
    q = q.filter_by(other=1)
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/selectable.py", line 5348, in filter_by
    for key, value in kwargs.items()
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/selectable.py", line 5348, in <listcomp>
    for key, value in kwargs.items()
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 1701, in _entity_namespace_key
    replace_context=err,
  File "/home/kai/MN/sterling/nixd/opt/python3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Entity namespace for "A.id" has no property "other"
``` 

### Versions

- OS: linux
- Python: 3.6
- SQLAlchemy: 1.4.40
- Database: none required for MCVE
- DBAPI: none required for MCVE

### Additional context

This happens with legacy ORM queries also, substituting a `with_entities()` method call for the `with_only_columns()` method call.

The code I'm seeing this in worked with SQLAlchemy 0.9, 1.1, and 1.3. I haven't tested other releases of 1.4.

**Comment by CaselIT** [comment]
Hi,

Also setting `maintain_column_froms=True` in `with_only_columns` changes the message but does not fixes the error. since `filter_by` needs to decide which from item to use to obtain the column "other".
Looking at the implementation `with_only_columns` resets the join information even when maintain_column_froms is specified. cc @zzzeek 

In the mean time you can use `filter` (or `where`) specifying condition explicly: `where(B.c.other == 1)`

**Comment by zzzeek** [comment]
filter_by() works from the last entity set up, and the behavior is the same using ORM Query with ORM entities also.     However, within the realm of ORM Query, this is a behavioral change from SQLAlchemy 1.3.  the difference is whether or not "with_only_columns()" as well as "with_entities()" resets the "joinpoint" or not.  in 1.3 it apparently did not.  in 1.4 it is consistent w/ core and ORM.

the ORM example would be:

```py
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    other = Column(String)

s = Session()


q = s.query(A).join(B).with_entities(A.id).filter_by(other='x')
print(q)
```

the docs for ORM query.filter_by() say:

> The keyword expressions are extracted from the primary
> entity of the query, or the last entity that was the
 >  target of a call to :meth:`_query.Query.join`.

if you do query(A).join(B).with_entities(A.id), the primary entity is now "A".   The joinpoint is reset here.

so here what I would expect to work would be:

```py
q = sa.select(A)
q = q.join(B)
q = q.filter_by(other=1)
q = q.with_only_columns(A.c.id)

```

Which way is more "correct" would appear to be very subjective here and I would not recommend using filter_by() for a multi-entity query like this that is changing often.   Like, if there were just way to tell filter_by() we want to use "B"...there is!  use filter().  so, i dont know that I want to change things here except maybe documenting it and adding test support so that this one doesnt keep flipping back and forth behaviorally.

**Comment by CaselIT** [comment]
I guess select filter_by docs could be improved a bit too: https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=filter_by#sqlalchemy.sql.expression.Select.filter_by

**Comment by groner** [comment]
Thanks for the feedback. Your explanations make sense. I'm a little dismayed that I need to review about 330 calls to filter_by in the codebase I'm upgrading, but I will manage.

Thanks for providing a great tool (I mean that sincerely).

**Comment by groner** [comment]
> ```
> Entity namespace for "A.id" has no property "other"
> ```

This error was a bit confusing to me. I now understand this to mean `A` (the entity namespace for `A.id`) has no property `other`, but my first impression was that sqlalchemy is trying to look for `A.id.other`. I probably would have dug a little deeper to find a problem in my code if I had understood the error initially.

**Comment by zzzeek** [comment]
I didnt rule out changing it, it just seems like we didnt have a consistent story here before, because otherwise tests would have caught this changing when i changed the behavior.   im personally not really sure which way is better, it might be the way it was, was better.

**Comment by zzzeek** [comment]
its just everyone who's adjusted to it the way it is now, then they'd all have a surprise again.   thats the main reason im hesitant to switch it again.  (though technically there is no "again" on the select() side since select().filter_by() is new).    

that is, if you are using select().filter_by() here originally, this was probably not a "regression" (though I havent checked early 1.4 versions), unless you migrated code from the ORM Query that used filter_by() with with_entities().

**Comment by groner** [comment]
I'm happy to provide some of my thoughts on select().filter_by().

In SQL an unqualified column name is allowable as long as it can be resolved unambiguously. I think if select().filter_by() followed same or similar rules for resolving its argument names, it would minimize surprises (for SQL users anyway).

The scoping rules select().with_only_columns() seem out of place because they don't really model how SQL works.

**Comment by zzzeek** [comment]
> > ```
> > Entity namespace for "A.id" has no property "other"
> > ```
> 
> This error was a bit confusing to me. I now understand this to mean `A` (the entity namespace for `A.id`) has no property `other`, but my first impression was that sqlalchemy is trying to look for `A.id.other`. I probably would have dug a little deeper to find a problem in my code if I had understood the error initially.

yes that error message is bad also, we should fix that, becuase it looked at "A" overall for "other".  the error message is not reporting the actual entity correctly.

**Comment by CaselIT** [comment]
> > I'm happy to provide some of my thoughts on select().filter_by().
> > In SQL an unqualified column name is allowable as long as it can be resolved unambiguously. I think if select().filter_by() followed same or similar rules for resolving its argument names, it would minimize surprises (for SQL users anyway).
> 
> agree, filter_by() would be even better, and we wouldn't have to worry about this problem, if it just did that. I'd be happy to scope that for 2.1.

how would this work? search on all froms and raise if no match is found or more than one is found?

**Comment by zzzeek** [comment]
yeah it would have to raise if the name is ambiguous

**Comment by Subilan** [comment]
Just now encountered `sqlalchemy.exc.InvalidRequestError: Entity namespace for "***" has no property "***"` type of error without any column names left ambiguous, using `filter_by`. Seemingly it doesn't work as I assumed (just like `filter`).

It's been nearly 3 years. Any update on this?

**Comment by CaselIT** [comment]
The update is that there are no updates on this

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: new filter_by implementation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6463

**Comment by zzzeek** [comment]
this is going to make filter_by() do more work to complete.   not any kind of huge deal but it will be measurably (like in ns or low ms) slower


```py
from __future__ import annotations

import timeit

from sqlalchemy import ForeignKey
from sqlalchemy import select
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship


class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]
    bs: Mapped[list[B]] = relationship("B")


class B(Base):
    __tablename__ = "b"
    id: Mapped[int] = mapped_column(primary_key=True)
    a_id: Mapped[int] = mapped_column(ForeignKey("a.id"))
    data: Mapped[str]
    cs: Mapped[list[C]] = relationship()


class C(Base):
    __tablename__ = "c"
    id: Mapped[int] = mapped_column(primary_key=True)
    b_id: Mapped[int] = mapped_column(ForeignKey("b.id"))
    data: Mapped[str]
    ds: Mapped[list[D]] = relationship()

class D(Base):
    __tablename__ = "d"
    id: Mapped[int] = mapped_column(primary_key=True)
    c_id: Mapped[int] = mapped_column(ForeignKey("c.id"))
    data: Mapped[str]


stmt = select(A, B, C, D).join(A.bs).join(B.cs).join(C.ds)

print(timeit.timeit("stmt.filter_by(c_id=5)", "from __main__ import stmt", number=100000))
```

main:  0.9565060680033639
the change:  1.5048343079979531

**Comment by CaselIT** [comment]
It doesn't seem too bad, about 50% slower. 
For reference, how long does `where` take? If the difference is significant we could document that in the `filter_by` docs
