### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10: character maps to <undefined>

### ISSUE THREAD

**Issue by chongjing001** [sqlalchemy/sqlalchemy#8617]
### Describe the bug

 Traceback (most recent call last):
  File "./utils/result_push_tool.py", line 187, in deal_callback_data
    task_obj = task_media_obj.task
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 682, in get
    value = self.callable_(state, passive)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 722, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 812, in _emit_lazyload
    session.query(self.mapper), primary_key_identity
  File "/venv/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 602, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "/venv/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 434, in __iter__
    return q._execute_and_instances(context)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 321, in _query
    self._post_get_result()
  File "/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 355, in _post_get_result
    self._rows = self._fetch_row(0)
  File "/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 328, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
  File "/usr/local/python37/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10: character maps to <undefined>

### To Reproduce

```python
file_id = results[0]['fileId']
file_obj = session.query(TaskMediaFiles).filter_by(file_id=file_id).first()
task_media_obj = file_obj.task_media
task_obj = task_media_obj.task
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
``` 

### Versions

- OS: docker-Linux centos7
- Python: 3.7.4
- SQLAlchemy:1.3.0
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by CaselIT** [comment]
Hi,

There is not enough information to help. What's the table sql definition and sqlalchemy type for the column?

**Comment by chongjing001** [comment]
> Hi,
> 
> There is not enough information to help. What's the table sql definition and sqlalchemy type for the column?

sorry，

**Comment by CaselIT** [comment]
Thanks for updating the example.

I'm not overly familiar with mysql (pinging @zzzeek since he is more familiar), but it seems the error is trying to store unicode in a `String` type (that's equivalent to varchar in SQL).
Try using the `Unicode` sqlalchemy type that will use nvarchar in SQL.
