### ISSUE TITLE
Wrong SQL generated when polymorphic identity is on computed field

### ISSUE THREAD

**Issue by jakubman1** [sqlalchemy/sqlalchemy#8622]
### Describe the bug

If you have a table with polymorphic identity using static computed fields, the generated INSERT statement, when creating new rows, incorrectly tries to insert into the computed field instead of ignoring it.

### To Reproduce

```python
from enum import Enum

import sqlalchemy
import sqlalchemy.orm
from sqlalchemy import create_engine

meta = sqlalchemy.MetaData()
Base = sqlalchemy.orm.declarative_base(metadata=meta)


class Options(str, Enum):
    a = "a"
    b = "b"


class BaseTable(Base):
    __tablename__ = "base"
    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True, autoincrement=True)
    issue = sqlalchemy.Column(sqlalchemy.Enum(Options))
    __mapper_args__ = {"polymorphic_on": issue}


class TestObject(BaseTable):
    __tablename__ = "test"
    id = sqlalchemy.Column(sqlalchemy.Integer, sqlalchemy.ForeignKey("base.id"), primary_key=True)
    issue = sqlalchemy.Column(
        sqlalchemy.String,
        sqlalchemy.Computed(sqlalchemy.text("'a'"), persisted=True),
    )
    __mapper_args__ = {"polymorphic_identity": Options.a}


if __name__ == "__main__":
    engine = create_engine('sqlite://', echo=True)
    meta.create_all(engine)
    session = sqlalchemy.orm.scoped_session(sqlalchemy.orm.sessionmaker(bind=engine))

    obj = TestObject()
    session.add(obj)
    session.commit() # error
```

### Error

```
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: cannot INSERT into generated column "issue"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 40, in <module>
    session.commit()
  File "<string>", line 2, in commit
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot INSERT into generated column "issue"
[SQL: INSERT INTO test (id, issue) VALUES (?, ?)]
[parameters: (1, <Options.A: 'a'>)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
``` 

### Versions

- OS: Ubuntu 20
- Python: 3.8
- SQLAlchemy: 1.4.41
- Database: sqlite and postgresql 14
- DBAPI: sqlite3 and psycopg2

### Additional context

Generated SQL for reproduce code example:
```
INSERT INTO base (issue) VALUES ('a')
INSERT INTO test (id, issue) VALUES (1, 'a')
```

Expected:
```
INSERT INTO base (issue) VALUES ('a')
INSERT INTO test (id) VALUES (1)
```

**Comment by zzzeek** [comment]
hey there -

this mapping as given is invalid.  the polymorphic discriminator column can only be on the base table, as far as the ORM is concerned, and something has to be in that column.  the ORM will also only SELECT from that base column, it would never select from polymorphic discriminator on a sub-table like that.  the ORM also wouldn't know how to "copy" the data from the computed column to the base column, it's always going to want to write the value from the Python mapping.

that said, you can have this column on the TestObject class within the schema, you just have to map it to a different python attribute name so that it's ignored for this operation, such as:

```py
class TestObject(BaseTable):
    __tablename__ = "test"
    id = sqlalchemy.Column(sqlalchemy.Integer, sqlalchemy.ForeignKey("base.id"), primary_key=True)
    _issue_computed = sqlalchemy.Column(
        "issue",
        sqlalchemy.String,
        sqlalchemy.Computed(sqlalchemy.text("'a'"), persisted=True),
    )
    __mapper_args__ = {"polymorphic_identity": Options.a}

```

then you get the identical schema in your database but the column is not used for the ORM mapping side of it, since it can't anyway.

**Comment by zzzeek** [comment]
note there's a warning generated that would be the first indicator that the mapping needs correction:

    SAWarning: Implicitly combining column base.issue with column test.issue under attribute 'issue'.  Please configure one or more attributes for these same-named columns explicitly.

background on this warning's meaning is at https://docs.sqlalchemy.org/en/14/faq/ormconfiguration.html?highlight=implicitly+combining#i-m-getting-a-warning-or-error-about-implicitly-combining-column-x-under-attribute-y
