### ISSUE TITLE
1.4.42 broke my Snowflake code

### ISSUE THREAD

**Issue by scastria** [sqlalchemy/sqlalchemy#8647]
### Describe the bug

I ran my unit test that has always worked with the latest 1.4.42 release of sqlalchemy and it failed

### To Reproduce

```python
import sqlalchemy
import snowflake.connector
from urllib.parse import quote

dialect = "snowflake"
user = "snowflake_user"
password = "snowflake_password"
host = "snowflake_host"
db = "snowflake_db"
options = "warehouse=snowflake_wh"
con_string = f"{dialect}://{user}:{quote(password)}@{host}/{db}?{options}"
dbcon = sqlalchemy.create_engine(con_string, pool_pre_ping=True)
with dbcon.connect() as sql:
    results = sql.execute("SELECT count(*) FROM TBL_DATA")
    assert results.rowcount > 0
```

### Error

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    dbcon = sqlalchemy.create_engine(con_string, pool_pre_ping=True)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 656, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 341, in load
    return impl.load()
  File "/usr/local/lib/python3.8/dist-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/snowflake/sqlalchemy/__init__.py", line 63, in <module>
    from .util import _url as URL
  File "/usr/local/lib/python3.8/dist-packages/snowflake/sqlalchemy/util.py", line 8, in <module>
    from sqlalchemy.engine.url import _rfc_1738_quote
ImportError: cannot import name '_rfc_1738_quote' from 'sqlalchemy.engine.url' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py)``` 

### Versions

- OS: MacOS 12.6
- Python: 3.8.10
- SQLAlchemy: 1.4.42
- Database: Snowflake
- snowflake-sqlalchemy: 1.4.1
- snowflake-connector-python: 2.7.12


### Additional context

If I switch to 1.4.41, everything works

**Comment by zzzeek** [comment]
hi -

this is a bug in sqlalchemy-snowflake, they are importing a private name that has changed.    

I would report this at https://github.com/snowflakedb/snowflake-sqlalchemy

**Comment by zzzeek** [comment]
looks like you got this at https://github.com/snowflakedb/snowflake-sqlalchemy/issues/350
