### ISSUE TITLE
`Invalid precision value` when inserting long string on varchar column in SQLAlchemy 2.0.0b1

### ISSUE THREAD

**Issue by harupy** [sqlalchemy/sqlalchemy#8661]
### Describe the bug

`Invalid precision value` when inserting long string on varchar column in SQLAlchemy 2.0.0b1.

### To Reproduce

I created https://github.com/harupy/invalid-precision-value-sqlalchemy-2.0 to reproduce the error.

```bash
git clone https://github.com/harupy/invalid-precision-value-sqlalchemy-2.0
cd invalid-precision-value-sqlalchemy-2.0
docker compose build
docker compose run sa-20
```

Python code:

```python
import sqlalchemy as sa

import os
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, VARCHAR

print(sa.__version__)

engine = create_engine(os.getenv("DB_URI"), echo=True)
meta = MetaData()

students = Table(
    "students",
    meta,
    Column("id", Integer, primary_key=True),
    Column("name", VARCHAR(5000)),
)
meta.create_all(engine)

# Insert a row to the table
with  engine.connect() as conn:
    conn.execute(students.insert().values(name="x" * 5000))

print("SUCCESS")
```

### Error

```
2.0.0b1
2022-10-18 08:51:31,639 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2022-10-18 08:51:31,639 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 08:51:31,640 INFO sqlalchemy.engine.Engine SELECT schema_name()
2022-10-18 08:51:31,640 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
2022-10-18 08:51:31,642 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2022-10-18 08:51:31,642 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
2022-10-18 08:51:31,642 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-18 08:51:31,644 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE ([INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) OR [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max))) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2022-10-18 08:51:31,645 INFO sqlalchemy.engine.Engine [generated in 0.00018s] ('BASE TABLE', 'VIEW', 'students', 'dbo')
2022-10-18 08:51:31,651 INFO sqlalchemy.engine.Engine COMMIT
2022-10-18 08:51:31,652 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-18 08:51:31,652 INFO sqlalchemy.engine.Engine INSERT INTO students (name) OUTPUT inserted.id VALUES (?)
2022-10-18 08:51:31,652 INFO sqlalchemy.engine.Engine [generated in 0.00017s] ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ... (4702 characters truncated) ... xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',)
2022-10-18 08:51:31,652 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1943, in _exec_single_context
    cursor, str_statement, effective_parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 744, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('HY104', '[HY104] [Microsoft][ODBC Driver 17 for SQL Server]Invalid precision value (0) (SQLBindParameter)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    conn.execute(students.insert().values(name="x" * 5000))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1395, in execute
    execution_options or NO_OPTIONS,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 488, in _execute_on_connection
    self, distilled_params, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1626, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1821, in _execute_context
    dialect, context, statement, parameters
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1962, in _exec_single_context
    e, str_statement, effective_parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2303, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1943, in _exec_single_context
    cursor, str_statement, effective_parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 744, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY104', '[HY104] [Microsoft][ODBC Driver 17 for SQL Server]Invalid precision value (0) (SQLBindParameter)')
[SQL: INSERT INTO students (name) OUTPUT inserted.id VALUES (?)]
[parameters: ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ... (4702 characters truncated) ... xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
``` 

### Versions

- OS: Debian
- Python: 3.7
- SQLAlchemy: 2.0.0b1
- Database: SQL Server
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc 4.0.34

### Additional context

The attached python code worked in SQLAlchemy 1.4.

```
docker compose run sa-14
```

```
1.4.42
2022-10-18 08:55:47,812 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2022-10-18 08:55:47,813 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 08:55:47,813 INFO sqlalchemy.engine.Engine SELECT schema_name()
2022-10-18 08:55:47,813 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
2022-10-18 08:55:47,841 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2022-10-18 08:55:47,841 INFO sqlalchemy.engine.Engine [generated in 0.00011s] ()
2022-10-18 08:55:47,842 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-18 08:55:47,844 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2022-10-18 08:55:47,844 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ('BASE TABLE', 'students', 'dbo')
2022-10-18 08:55:47,864 INFO sqlalchemy.engine.Engine 
CREATE TABLE students (
        id INTEGER NOT NULL IDENTITY, 
        name VARCHAR(5000) NULL, 
        PRIMARY KEY (id)
)


2022-10-18 08:55:47,864 INFO sqlalchemy.engine.Engine [no key 0.00009s] ()
2022-10-18 08:55:47,865 INFO sqlalchemy.engine.Engine COMMIT
2022-10-18 08:55:47,867 INFO sqlalchemy.engine.Engine INSERT INTO students (name) OUTPUT inserted.id VALUES (?)
2022-10-18 08:55:47,867 INFO sqlalchemy.engine.Engine [generated in 0.00011s] ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ... (4702 characters truncated) ... xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',)
2022-10-18 08:55:47,869 INFO sqlalchemy.engine.Engine COMMIT
SUCCESS
```

**Comment by zzzeek** [comment]
okey doke, @gordthompson I will handle but FYI this is because setinputsizes binds the value as NVARCHAR (I assume) and NVARCHAR [only goes to 4000 characters](https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16), something I've certainly seen and forgotten many times by now.    setinputsizes can't take place for larger char values I will have to add some hooks.

**Comment by zzzeek** [comment]
per https://github.com/mkleehammer/pyodbc/issues/835 we can do something like:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/pyodbc.py b/lib/sqlalchemy/dialects/mssql/pyodbc.py
index 5eb6b95282..9696e625c9 100644
--- a/lib/sqlalchemy/dialects/mssql/pyodbc.py
+++ b/lib/sqlalchemy/dialects/mssql/pyodbc.py
@@ -516,7 +516,10 @@ class _BINARY_pyodbc(_ms_binary_pyodbc, BINARY):
 
 class _String_pyodbc(sqltypes.String):
     def get_dbapi_type(self, dbapi):
-        return dbapi.SQL_VARCHAR
+        if self.length > 4000:
+            return (dbapi.SQL_VARCHAR, 0, 0)
+        else:
+            return dbapi.SQL_VARCHAR
 
 
 class _Unicode_pyodbc(_MSUnicode):

```

let me see what that means and if we can clean it up

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**further qualify pyodbc setinputsizes types for long stirngs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4135

**Comment by zzzeek** [comment]
OK that should keep the water out for awhile

**Comment by CaselIT** [comment]
thanks for testing the beta!

**Comment by harupy** [comment]
@zzzeek @CaselIT Thanks for quickly solving this issue!

**Comment by Mansitos** [comment]
Had a similar issue with SQLalchemy 2.0.9

Rollback to 1.4.36 fixed the problem

**Comment by CaselIT** [comment]
@Mansitos this issue should be resolved, so if you are still encountering the problem please open a new issue with the details.

Thaks
