### ISSUE TITLE
Pydantic Schema Validation Error 

### ISSUE THREAD

**Issue by Tamunonengiyeofori** [sqlalchemy/sqlalchemy#8694]
### Describe the bug

When I try to create a new Userprofile and validate the response of the POST request with a validation schema for the UserProfile, I get a dialect validation error.
When I try to test a get request to return all the users and validate with a schema, the dialect validation still occurs.

### To Reproduce

```python
# ORM modelsfrom sqlalchemy import TIME, Column, String, Integer, Boolean, ForeignKey
from sqlalchemy.sql.sqltypes import TIMESTAMP
from sqlalchemy.sql.expression import text
from sqlalchemy_utils.types import ChoiceType
from sqlalchemy.orm import relationship
from .database import Base
from enum import IntFlag

class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True, nullable=False)
    email =  Column(String(80), nullable=False, unique=True)
    password = Column(String(100), nullable=False)   
    is_active = Column(Boolean, server_default="False", nullable=False)
    is_admin = Column(Boolean, server_default="False", nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True), nullable=True, onupdate=text("now()"))
    profile = relationship("UserProfile", back_populates="owner", uselist=False)
    
    def __repr__(self):
        return f"{self.email}"
    
class UserProfile(Base):
    __tablename__ = "user_profile"
    id = Column(Integer, primary_key=True, nullable=False)
    name = Column(String(80), nullable=False)
    gender = Column(String(80), nullable=False)
    address = Column(String(250), nullable=False)
    mobile = Column(String(80), nullable=False)
    loans = relationship("Loan", back_populates="owner")
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text("now()"))
    updated_at = Column(TIMESTAMP(timezone=True), nullable=True, onupdate=text("now()"))
    owner_id = Column(Integer, ForeignKey("user.id", ondelete="CASCADE"), nullable=False)
    owner = relationship("User", back_populates="profile")
    
class LoanType(IntFlag):
    QUATERLY = 1
    BIANNUALL = 2
    ANNUAL = 3
    
class DurationType(IntFlag):
    THREE_MONTHS = 1
    SIX_MONTHS = 2
    TWELVE_MONTHS = 3
    

class PaymentStatus(IntFlag):
    PAID = 1
    DEBT = 2
    PAYING = 3
    
class Loan(Base):
    __tablename__ = "loan"
    id = Column(Integer, primary_key=True, nullable=False)
    amount = Column(Integer, default=0, nullable=False)
    type = Column(ChoiceType(LoanType, impl=Integer), nullable=False)
    payment_status = Column(ChoiceType(PaymentStatus, impl=Integer()), default=PaymentStatus.DEBT.value, nullable=False)
    # duration = Column(ChoiceType(DurationType, impl=Integer()))
    duration = Column(Integer, default=0, nullable=False)
    date_taken = Column(TIMESTAMP(timezone=True), server_default=text("now()"), nullable=False)
    description = Column(String(255), nullable=False)
    date_paid = Column(TIMESTAMP(timezone=True), nullable=True, onupdate=text("now()"))
    owner_id = Column(Integer, ForeignKey("user_profile.id", ondelete="CASCADE"))
    owner = relationship("UserProfile", back_populates="loans")
    
    def __repr__(self):
        return f"{self.id} {self.type}"

# PYDANTIC VALIDATION SCHEMAS
from pydantic import BaseModel, EmailStr, constr
from typing import Optional, List
from datetime import datetime
# from app.models import LoanType
from .config import settings

class UserProfileBase(BaseModel):
    loans: Optional[List["LoanResponse"]] = None
    class Config:
        orm_mode = True
    
class UserProfileCreate(BaseModel):
    name: str
    gender: str
    address: str
    mobile: constr(min_length=11)

class UserProfileOut(UserProfileBase):
    id: int
    created_at: datetime
    updated_at: Optional[datetime]
    owner_id: int
    owner: "UserOut"
    
    

class UserBase(BaseModel):
    email : EmailStr
    is_active: bool = False
    is_admin: bool = False
    profile: Optional[UserProfileOut] = None
    
    class Config:
        orm_mode = True    

# class UserOut(BaseModel):
#     id: Optional[int]

class UserCreate(UserBase):
    password: str
    
class UserLogin(BaseModel):
    email: EmailStr
    password: str
    
class UserOut(UserBase):
    id : int
    is_admin: bool 
    created_at: datetime
    profile: Optional[UserProfileOut]

# HTTP ROUTES 
from .. import models, schemas
from fastapi import FastAPI, status, HTTPException, Depends, APIRouter
from ..database import get_db
from .. import models, utils, Oauth2
from sqlalchemy.orm import Session
from typing import List


user_router = APIRouter(
    prefix="/users",
    tags = ["Users"]
)

# Create a User
@user_router.post("/signup", status_code=status.HTTP_201_CREATED, response_model=schemas.UserOut)
def create_user(user:schemas.UserCreate, db:Session = Depends(get_db)):
    user_email = db.query(models.User).filter(models.User.email == user.email).first()
    if user_email is not None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail=f"The User with email {user_email} already exists")
    new_password = utils.hash_passowrd(user.password)
    user.password = new_password
    new_user = models.User(**user.dict())
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    return(new_user)


# Get all of the users
@user_router.get("/", response_model=List[schemas.UserOut], status_code=status.HTTP_200_OK)
def get_all_users(db: Session = Depends(get_db), 
                  curent_user: int = Depends(Oauth2.get_current_user)
                  ):
    print(curent_user.id)
    user = db.query(models.User).filter(models.User.id == curent_user.id).first()
    if user.is_admin:
        all_users = db.query(models.User).all()
        return all_users
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="You are not authorized to perform this action"
    )
from .. import models, schemas
from fastapi import FastAPI, status, HTTPException, Depends, APIRouter
from ..database import get_db
from .. import models, utils, schemas
from sqlalchemy.orm import Session
from  .. import Oauth2

profile_router = APIRouter(
    prefix="/users/profile",
    tags = ["UserProfile"]
)

@profile_router.post("/", status_code=status.HTTP_201_CREATED
                    #  response_model=schemas.UserProfileOut
                     )
def create_user_profile(profile:schemas.UserProfileCreate,
                        db: Session = Depends(get_db),
                        current_user: int = Depends(Oauth2.get_current_user)):
    print(current_user.id)
    new_profile = models.UserProfile(owner_id=current_user.id, **profile.dict())
    db.add(new_profile)
    db.commit()
    db.refresh(new_profile)
    return(new_profile)
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
``` INFO:     127.0.0.1:61472 - "GET /users/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    response_data = await serialize_response(
  File "C:\Users\User\Desktop\Coding\LOAN_SERVICE_API\venv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for UserOut
response -> 0 -> profile
  TypeEngine.dialect_impl() missing 1 required positional argument: 'dialect' (type=type_error)

### Versions

- OS: Windows
- Python: 3.10.1
- SQLAlchemy: 14.4.1
- Database:Postgresql 14.5.1
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pgadmin


### Additional context

![image](https://user-images.githubusercontent.com/78642266/197170814-da2b3544-0a7f-41c6-a73b-9d05be03a82c.png)
![image](https://user-images.githubusercontent.com/78642266/197170826-9dbcda56-93df-4167-ad7f-93243c15e8bc.png)
These images are from postmen showing the data used to test the endpoints that throw the errors stated

**Comment by CaselIT** [comment]
Hi,

This seems to be an issue with the configuration of pydantic or fastapi. I would suggest asking for support on the respective support sites. If it turns out to be a sqlalchemy issue please report it with a code snipped that uses only sqlalchemy code
