### ISSUE TITLE
AsyncSession.refresh does not work with attribute names of relationships specified

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/sqlalchemy#8701]
### Describe the bug

`AsyncSession.refresh(obj)` works well but `AsyncSession.refresh(obj, ['attr'])` does not work (if "attr" is relationship).

### To Reproduce

```python
import asyncio

from sqlalchemy import Column, ForeignKey, Integer, select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)


class Group(Base):
    __tablename__ = 'group'
    id = Column(Integer, primary_key=True)
    users = relationship('GroupUser', lazy='selectin')


class GroupUser(Base):
    __tablename__ = 'group_user'
    group_id = Column(Integer, ForeignKey(Group.id), primary_key=True)
    user_id = Column(Integer, ForeignKey(User.id), primary_key=True)


async def main():
    engine = create_async_engine('sqlite+aiosqlite://', echo=False)

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    Session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with Session() as session:
        async with session.begin():
            session.add_all((
                User(id=1),
                User(id=2),
                Group(users=[GroupUser(user_id=1), GroupUser(user_id=2)])
            ))

    async with Session() as session:
        query = select(Group).where(Group.id == 1)
        result = await session.execute(query)
        group = result.scalar()
        print(group, group.users)
        # SUCCESS
        await session.refresh(group)
        print(group, group.users)
        # FAILURE
        await session.refresh(group, ['users'])
        print(group, group.users)


asyncio.run(main())
```

### Error

```
<__main__.Group object at 0x7f30ae3c89d0> [<__main__.GroupUser object at 0x7f30ae3c82b0>, <__main__.GroupUser object at 0x7f30ae3cb7c0>]
<__main__.Group object at 0x7f30ae3c89d0> [<__main__.GroupUser object at 0x7f30ae4349d0>, <__main__.GroupUser object at 0x7f30ae434940>]
Traceback (most recent call last):
  File "/home/decaz/workspace/debug_sa/test.py", line 58, in <module>
    asyncio.run(main())
  File "/home/decaz/.pyenv/versions/3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/decaz/.pyenv/versions/3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/decaz/workspace/debug_sa/test.py", line 54, in main
    await session.refresh(group, ['users'])
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 156, in refresh
    return await greenlet_spawn(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2340, in refresh
    loading.load_on_ident(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 407, in load_on_ident
    return load_on_pk_identity(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1564, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 531, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 804, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3315, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 765, in create_for_statement
    self._setup_for_generate()
  File "/home/decaz/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 889, in _setup_for_generate
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: No column-based properties specified for refresh operation. Use session.expire() to reload collections and related items.
``` 

### Versions

- OS: elementary 6.1 (based on Ubuntu LTS)
- Python: 3.10.8
- SQLAlchemy: 1.4.42
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): aiosqlite==0.17.0

### Additional context

From https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#preventing-implicit-io-when-using-asyncsession:
```
Other guidelines include:

- Methods like `AsyncSession.expire()` should be avoided in favor of `AsyncSession.refresh()`
```

**Comment by zzzeek** [comment]
Hi -

The error message should be clear, no?   right now you need to include column-based attributes for refresh to work:

        await session.refresh(group, ['id', 'users'])

We can open a new issue to improve this in 2.0

**Comment by zzzeek** [comment]
#8703

**Comment by decaz** [comment]
@zzzeek changing `await session.refresh(group, ['users'])` to `session.expire(group, ['users'])` gives the following error:
```
Traceback (most recent call last):
  File "/home/marat/workspace/debug_sa/test.py", line 58, in <module>
    asyncio.run(main())
  File "/home/marat/.pyenv/versions/3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/marat/.pyenv/versions/3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/marat/workspace/debug_sa/test.py", line 55, in main
    print(group, group.users)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
    return self.impl.get(state, dict_)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
    return self._emit_lazyload(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1046, in _emit_lazyload
    result = session.execute(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in _handle_exception
    raise error
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 85, in execute
    _cursor = self.await_(self._connection.cursor())
  File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 59, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
sys:1: RuntimeWarning: coroutine 'Connection.cursor' was never awaited
```

**Comment by zzzeek** [comment]
> @zzzeek changing `await session.refresh(group, ['users'])` to `session.expire(group, ['users'])` gives the following error:

correct because you can't lazy load in asyncio.  As mentioned in my previous comment, add at least one primary key column to the call to refresh:

    await session.refresh(group, ['id', 'users'])

however overall, you shouldn't need to refresh if the collection were already loaded up front, which is what that `lazy='selectin'` will accomplish.


> 
> ```
> Traceback (most recent call last):
>   File "/home/marat/workspace/debug_sa/test.py", line 58, in <module>
>     asyncio.run(main())
>   File "/home/marat/.pyenv/versions/3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/home/marat/.pyenv/versions/3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/home/marat/workspace/debug_sa/test.py", line 55, in main
>     print(group, group.users)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
>     return self.impl.get(state, dict_)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
>     value = self._fire_loader_callables(state, key, passive)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
>     return self.callable_(state, passive)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
>     return self._emit_lazyload(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1046, in _emit_lazyload
>     result = session.execute(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
>     result = conn._execute_20(statement, params or {}, execution_options)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
>     return meth(self, args_10style, kwargs_10style, execution_options)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
>     return connection._execute_clauseelement(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
>     self._handle_dbapi_exception(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception
>     util.raise_(exc_info[1], with_traceback=exc_info[2])
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
>     raise exception
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
>     self.dialect.do_execute(
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
>     cursor.execute(statement, parameters)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in execute
>     self._adapt_connection._handle_exception(error)
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in _handle_exception
>     raise error
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 85, in execute
>     _cursor = self.await_(self._connection.cursor())
>   File "/home/marat/workspace/debug_sa/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 59, in await_only
>     raise exc.MissingGreenlet(
> sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
> sys:1: RuntimeWarning: coroutine 'Connection.cursor' was never awaited
> ```

**Comment by decaz** [comment]
@zzzeek the need to use the `refresh` method appeared due to the use of `on_conflict_do_update` dialect feature for relationship data insertion bypassing the ORM.

**Comment by decaz** [comment]
Considering the error message I always read it as there should be _only_ column-based attributes 😀 Also what is the reason for needing to specify PK when calling these methods?

**Comment by zzzeek** [comment]
this method historically was only for column-based attributes.  the ability for it to also affect relationship-based attributes was added in 1.4.   however this was mostly considered to be an extension of the generic "refresh()" feature that also refreshes the primary column attributes.      A refresh feature that bypasses the primary row entirely and hits just the relationship loaders would not fit well into the current behavioral and internal architectural assumptions, including that refresh is generally expected to confirm that the primary row hasn't been deleted.   therefore we will just have it refresh for PK cols if no col arguments were given.
