### ISSUE TITLE
Postgresql+asyncpg+inheritance: `INSERT INTO table` errors by referencing the same table (`There is an entry for table "price_entries", but it cannot be referenced from this part of the query.`) 

### ISSUE THREAD

**Issue by ramarivera** [sqlalchemy/sqlalchemy#8718]
### Describe the bug

When trying to use inhertiance on a single table, for some reason I get errors when trying to insert elements.
The `INSERT INTO` statement is trying to reference it's own table id, as per: 

```
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: invalid reference to FROM-clause entry for table "price_entries"
HINT:  There is an entry for table "price_entries", but it cannot be referenced from this part of the query.
[SQL: INSERT INTO price_entries (price_type, currency_name, currency_symbol, value_in_usd, method_name, **id**, related_hash) VALUES (%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::FLOAT, %s::VARCHAR, **price_entries.id**, %s::VARCHAR) RETURNING price_entries.id]
[parameters: ('some value', 'some value', 'some value', 42, 'some value', None)]
```

I really don't know if I'm doing something wrong. I tried to reduce my code to this example, and it still happens. I created a new DB. I tried to follow the docs for v2 as close as possible, but maybe I am missing something.

### To Reproduce

```python
import asyncio
from typing import Optional

from sqlalchemy import Float, Integer, String
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class BaseEntity(MappedAsDataclass, DeclarativeBase):
    id: Mapped[int] = mapped_column(Integer, primary_key=True, init=False)

    __mapper_args__ = {"eager_defaults": True}


class PriceEntry(BaseEntity):
    __mapper_args__ = {
        "polymorphic_on": "price_type",
        "polymorphic_identity": "PE",
    }

    __tablename__ = "price_entries"

    price_type: Mapped[str] = mapped_column(String, init=False)

    currency_name: Mapped[str] = mapped_column(
        String,
        init=False,
    )
    currency_symbol: Mapped[str] = mapped_column(
        String,
        init=False,
    )

    value_in_usd: Mapped[float] = mapped_column(Float, init=False, default=0)

    method_name: Mapped[Optional[str]] = mapped_column(String, init=False, default=None)


class ApproximatePrice(PriceEntry):
    __mapper_args__ = {
        "polymorphic_identity": "AP",
    }

    related_hash: Mapped[Optional[str]] = mapped_column(String, init=False, default=None)


class ExactPrice(PriceEntry):
    __mapper_args__ = {
        "polymorphic_identity": "EP",
    }

    data_source: Mapped[Optional[str]] = mapped_column(String, init=False, default=None)


async def create():
    engine = create_async_engine(
        "postgresql+asyncpg://ramiro:admin@localhost:16000/liquidity2", echo=True
    )

    async with engine.begin() as connection:
        await connection.run_sync(BaseEntity.metadata.drop_all)
        await connection.run_sync(BaseEntity.metadata.create_all)

    return engine


async def insert(engine: AsyncEngine):
    ap_price = ApproximatePrice()

    ap_price.currency_name = "some value"
    ap_price.currency_symbol = "some value"
    ap_price.value_in_usd = 42
    ap_price.method_name = "some value"

    async with AsyncSession(engine, expire_on_commit=False) as session:
        session.add(ap_price)
        await session.commit()


async def do_work():
    engine = await create()
    await insert(engine)


if __name__ == "__main__":
    asyncio.run(do_work())
```

### Error

```
PS C:\DEV\liquidity> poetry run python .\example\example2.py
2022-10-26 16:16:17,691 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-10-26 16:16:17,692 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-26 16:16:17,697 INFO sqlalchemy.engine.Engine select current_schema()
2022-10-26 16:16:17,697 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-26 16:16:17,701 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-10-26 16:16:17,701 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-26 16:16:17,704 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-26 16:16:17,707 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %s::VARCHAR(64) COLLATE "C" AND pg_catalog.pg_class.relkind = ANY (ARRAY[%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %s::VARCHAR(64) COLLATE "C"
2022-10-26 16:16:17,707 INFO sqlalchemy.engine.Engine [generated in 0.00024s] ('price_entries', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2022-10-26 16:16:17,712 INFO sqlalchemy.engine.Engine
DROP TABLE price_entries
2022-10-26 16:16:17,712 INFO sqlalchemy.engine.Engine [no key 0.00017s] ()
2022-10-26 16:16:17,716 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %s::VARCHAR(64) COLLATE "C" AND pg_catalog.pg_class.relkind = ANY (ARRAY[%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %s::VARCHAR(64) COLLATE "C"
2022-10-26 16:16:17,716 INFO sqlalchemy.engine.Engine [cached since 0.009189s ago] ('price_entries', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2022-10-26 16:16:17,719 INFO sqlalchemy.engine.Engine
CREATE TABLE price_entries (
        price_type VARCHAR NOT NULL,
        currency_name VARCHAR NOT NULL,
        currency_symbol VARCHAR NOT NULL,
        value_in_usd FLOAT NOT NULL,
        method_name VARCHAR,
        id SERIAL NOT NULL,
        related_hash VARCHAR,
        data_source VARCHAR,
        PRIMARY KEY (id)
)


2022-10-26 16:16:17,719 INFO sqlalchemy.engine.Engine [no key 0.00027s] ()
2022-10-26 16:16:17,730 INFO sqlalchemy.engine.Engine COMMIT
2022-10-26 16:16:17,738 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-26 16:16:17,739 INFO sqlalchemy.engine.Engine INSERT INTO price_entries (price_type, currency_name, currency_symbol, value_in_usd, method_name, id, related_hash) VALUES (%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::FLOAT, %s::VARCHAR, price_entries.id, %s::VARCHAR) RETURNING price_entries.id
2022-10-26 16:16:17,739 INFO sqlalchemy.engine.Engine [generated in 0.00025s] ('AP', 'some value', 'some value', 42, 'some value', None)
2022-10-26 16:16:17,743 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 462, in _prepare_and_execute
    prepared_stmt, attributes = await adapt_connection._prepare(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 703, in _prepare
    prepared_stmt = await self._connection.prepare(operation)
  File "C:\DEV\liquidity\.venv\lib\site-packages\asyncpg\connection.py", line 566, in prepare
    return await self._prepare(
  File "C:\DEV\liquidity\.venv\lib\site-packages\asyncpg\connection.py", line 584, in _prepare
    stmt = await self._get_statement(
  File "C:\DEV\liquidity\.venv\lib\site-packages\asyncpg\connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedTableError: invalid reference to FROM-clause entry for table "price_entries"
HINT:  There is an entry for table "price_entries", but it cannot be referenced from this part of the query.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1942, in _exec_single_context
    self.dialect.do_execute(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 744, in do_execute
    cursor.execute(statement, parameters)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 523, in execute
    self._adapt_connection.await_(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 498, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 441, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 725, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedTableError'>: invalid reference to FROM-clause entry for table "price_entries"
HINT:  There is an entry for table "price_entries", but it cannot be referenced from this part of the query.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DEV\liquidity\example\example2.py", line 86, in <module>
    asyncio.run(do_work())
  File "C:\Users\ramar\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ramar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\DEV\liquidity\example\example2.py", line 82, in do_work
    await insert(engine)
  File "C:\DEV\liquidity\example\example2.py", line 77, in insert
    await session.commit()
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 806, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1775, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1182, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1157, in _prepare_impl
    self.session.flush()
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 3939, in flush
    self._flush(objects)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 4075, in _flush
    with util.safe_reraise():
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 4036, in _flush
    flush_context.execute()
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1167, in _emit_insert_statements
    result = connection.execute(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1392, in execute
    return meth(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 487, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1616, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1820, in _execute_context
    return self._exec_single_context(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1961, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2303, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1942, in _exec_single_context
    self.dialect.do_execute(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 744, in do_execute
    cursor.execute(statement, parameters)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 523, in execute
    self._adapt_connection.await_(
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 498, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 441, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\DEV\liquidity\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 725, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: invalid reference to FROM-clause entry for table "price_entries"
HINT:  There is an entry for table "price_entries", but it cannot be referenced from this part of the query.
[SQL: INSERT INTO price_entries (price_type, currency_name, currency_symbol, value_in_usd, method_name, id, related_hash) VALUES (%s::VARCHAR, %s::VARCHAR, %s::VARCHAR, %s::FLOAT, %s::VARCHAR, price_entries.id, %s::VARCHAR) RETURNING price_entries.id]
[parameters: ('AP', 'some value', 'some value', 42, 'some value', None)]
(Background on this error at: https://sqlalche.me/e/20/f405)

``` 

### Versions

- OS: Win 11
- Python: 3.10.8
- SQLAlchemy: 2.0.0b1
- Database: postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg

**Comment by zzzeek** [comment]
well it's the combination of the dataclasses thing and the usage of base cols, not getting along.

**Comment by zzzeek** [comment]
and only with the inheritance, not the base class, interesting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure inherited mapper attrs not interpreted as plain dataclass fields** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4159

**Comment by zzzeek** [comment]
OK with this one, there were at least three places I could intercept the incorrect attribute being added to the dataclass, and I opted for one of them, and a second point I put just an assertion.

So if you get the assertion, come on back and we will add that case as well.

**Comment by ramarivera** [comment]
Dumb question, how do I try it out? building from source?

**Comment by zzzeek** [comment]
ah well, I didnt commit the change yet.   so...if you wanted to get teh exact version of the code with the not-yet-committed change you could get it from a link like https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~4159/revisions/1/archive?format=tgz , then you would unzip it and use "python setup.py install" in the source distro
