### ISSUE TITLE
Unexpected exception rendering a statement with two literal_columns

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#8724]
### Describe the bug

When a SQL statement contains two `literal_columns()` with the same value, and that value contains a _parenthesis_, an exception is raised when SA computes the anonymous label for the two columns: adding an explicit `.label("foo")` to one column the problem disappears.

As a bit of context, I got the error writing a parametrized test that exercises PG ranges, so one actual value is `'(1,2]'::int4range`, that I simplified below removing the type cast, that does not make any difference.

This happens both under SA 1.4 and SA 2.0.

### To Reproduce

```python
from sqlalchemy import literal_column, select

q = select(literal_column("'(1,2]'"), literal_column("'(1,2]'"))
print(str(q))
```

### Error

# SA 1.4.42

```
Traceback (most recent call last):
  File "/tmp/e14/../e/p.py", line 4, in <module>
    print(str(q))
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 570, in __str__
    return str(self.compile())
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 502, in compile
    return self._compiler(dialect, **kw)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 804, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3315, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 508, in create_for_statement
    return cls(statement, compiler, **kw)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 4395, in __init__
    self.columns_plus_names = statement._generate_columns_plus_names(True)
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 6343, in _generate_columns_plus_names
    key_naming_convention(c),
  File "/tmp/e14/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 4462, in go
    else c._anon_key_label % pa
ValueError: incomplete format key
``` 

# SA 2.0.0b2
```
Traceback (most recent call last):
  File "/tmp/e/p.py", line 4, in <module>
    print(str(q))
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 291, in __str__
    return str(self.compile())
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1075, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 639, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 671, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3949, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 638, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 636, in create_for_statement
    return cls(statement, compiler, **kw)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 4419, in __init__
    self.columns_plus_names = statement._generate_columns_plus_names(True)
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 2350, in _generate_columns_plus_names
    key_naming_convention(c),
  File "/tmp/e/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 4494, in go
    else c._anon_key_label % pa
ValueError: incomplete format key
```

### Versions

- OS: NixOS
- Python: 3.10
- SQLAlchemy: 1.4.42 and 2.0.0b2
- Database: any (but the original problem happened testing against PG)
- DBAPI: any

**Comment by lelit** [comment]
Putting a breakpoint at the failing line in `selectable.py`, I see that `c._anon_key_label` contains the string `"%(8730051441743 '(1,2]')s"`.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply basic escaping to anon_labels unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4163

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**apply basic escaping to anon_labels unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4164
