### ISSUE TITLE
NameError resolving forward ref when non-builtin type is mapped on base class in different module

### ISSUE THREAD

**Issue by peterschutt** [sqlalchemy/sqlalchemy#8742]
### Describe the bug

Given a base class that defines a column with a forward ref type defined in one module, and a subclass defined in another module, resolution of the base class forward ref annotation occurs with the subclass module globals. This is an issue if the mapped type on the base class isn't a builtin, or if the annotation name is defined in the subclass module with a different type to the name in the base class module.

### To Reproduce

Given project layout:

- `app/lib/orm.py`
- `app/lib/domain.py`
- `app/main.py`

```python
# app/lib/orm.py

"""Application ORM configuration."""
from __future__ import annotations

from uuid import UUID, uuid4

from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql as pg
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declared_attr,
    mapped_column,
    registry,
)

convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
"""
Templates for automated constraint name generation.
"""


class Base(DeclarativeBase):
    """Base for all SQLAlchemy declarative models."""

    registry = registry(
        metadata=MetaData(naming_convention=convention),
        type_annotation_map={UUID: pg.UUID, dict: pg.JSONB},
    )

    id: Mapped[UUID] = mapped_column(default=uuid4, primary_key=True)

    # noinspection PyMethodParameters
    @declared_attr.directive
    def __tablename__(cls) -> str:
        return cls.__name__.lower()
```

```python
# app/lib/domain.py
from sqlalchemy.orm import Mapped

from lib.orm import Base


class Author(Base):
    name: Mapped[str]
```

```python
# app/main.py
from lib.domain import Author
```

### Error

```python-traceback
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 118, in de_stringify_annotation
    annotation = eval(annotation, base_globals, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'UUID' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/sqla-test/main.py", line 1, in <module>
    from lib.domain import Author
  File "/home/peter/PycharmProjects/sqla-test/lib/domain.py", line 6, in <module>
    class Author(Base):
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 701, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 207, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 288, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 523, in __init__
    self._extract_mappable_attributes()
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1278, in _extract_mappable_attributes
    value.declarative_scan(
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 660, in declarative_scan
    self._init_column_for_annotation(
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 686, in _init_column_for_annotation
    argument = de_stringify_annotation(cls, argument)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 120, in de_stringify_annotation
    raise NameError(
NameError: Could not de-stringify annotation UUID
```

### Versions

- OS: ubuntu 20.04
- Python: 3.11.0
- SQLAlchemy: 2.0.0b2
- Database: pg (but not getting that far)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

MVCE available as repo [here](https://github.com/peterschutt/sqla-mvce).

I've got a quick and dirty fix in the README that works for this case that relies on traversing the MRO and pulling globals from the module of any class that has `__annotations__`, but it isn't correct.

**Comment by zzzeek** [comment]
was just talking to the typing folks about this kind of thing.  we might have to use python internals for this the way I think pydantic might be doing now.

**Comment by peterschutt** [comment]
Sounds interesting. I'd be happy to do any grunt work @zzzeek but might be above my head. Just looked over `pydantic/typing.py` - first 3/4 of the module is special casing for different python versions! LMK how/if I can help.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**evaluate types in terms of the class in which they appear** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4169

**Comment by peterschutt** [comment]
> OK should be good for beta3, or latest main branch if you want to try it out

All passing at my end on main. Too good Mike, thanks!
