### ISSUE TITLE
`Mapper[aliased_class]` imports do not behave

### ISSUE THREAD

**Issue by zacharyrs** [sqlalchemy/sqlalchemy#8755]
### Describe the bug

When using the SQLAlchemy 2 declarative API with models split across multiple files, it seems `import as` is broken.
I use this to `import x as _x` to keep my exports tidy without resorting to defining `__all__`.

### To Reproduce

```python
# See the repo at https://github.com/zacharyrs/sqlalc2-8755
```

### Error

```
Traceback (most recent call last):
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 492, in _resolve_name
    rval = d[token]
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 347, in __missing__
    self[key] = val = self.creator(key)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 460, in _access_cls
    return self.fallback[key]
KeyError: 'A_alias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zach/dev/sqlalc2_test/main.py", line 15, in <module>
    test_a1 = A()
  File "<string>", line 4, in __init__
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 570, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3986, in _event_on_init
    instrumenting_mapper._check_configure()
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2121, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3795, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3836, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 2138, in _post_configure_properties
    prop.init()
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 500, in init
    self.do_init()
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1617, in do_init
    self._setup_entity()
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1808, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 496, in _resolve_name
    self._raise_for_name(name, err)
  File "/home/zach/pipeline/env/pyenv/versions/test-db/lib/python3.10/site-packages/sqlalchemy/orm/clsregistry.py", line 477, in _raise_for_name
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[B(B)], expression 'A_alias' failed to locate a name ('A_alias'). If this is a class name, consider adding this relationship() to the <class 'models.b.B'> class after both dependent classes have been defined.
``` 

### Versions

- OS: Ubuntu 22.04 (WSL)
- Python: 3.10.5
- SQLAlchemy: 2.0.0b2
- Database: SQLite in memory
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

**Comment by zzzeek** [comment]
this is almost certainly #8742, which is fixed.   try out the main branch from github.  reopen if this still occurs with main.   i will try to release 2.0b3 tomorrow.

**Comment by zzzeek** [comment]
oh or maybe it's

**Comment by zzzeek** [comment]
oh, this is not a 2.0 thing, you're writing "from mymodel import MyClass as SomeOtherClass".  Is that the case?  if so, you would need to use that class directly in your model like this:

```py
class Foo:
    bars = relationship(lambda: SomeOtherClass)
```

that is, you can't use the string name, which is always going to match up on `cls.__name__`.

this seems like  a usage issue so moving to discussion.
