### ISSUE TITLE
1.4.43 test regression on PyPy3.9 7.3.9: test/orm/test_query.py::YieldTest_sqlite+pysqlite_3_39_4::test_yield_per_close_on_interrupted_iteration_legacy

### ISSUE THREAD

**Issue by mgorny** [sqlalchemy/sqlalchemy#8762]
### Describe the bug

The following test of SQLAlchemy 1.4.43 fails on PyPy3.9 7.3.9:

```
============================================================== FAILURES ===============================================================
________________________ YieldTest_sqlite+pysqlite_3_39_4.test_yield_per_close_on_interrupted_iteration_legacy ________________________
Traceback (most recent call last):
  File "/tmp/portage/dev-python/sqlalchemy-1.4.43/work/SQLAlchemy-1.4.43/test/orm/test_query.py", line 5442, in test_yield_per_close_on
_interrupted_iteration_legacy
    assert asserted_result[0]._soft_closed
AssertionError: assert False
 +  where False = <sqlalchemy.engine.result.ScalarResult object at 0x00007f0c4c45cc28>._soft_closed
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
b'hi'
```

### To Reproduce

```python
tox -e pypy3
```

### Error

```
============================================================== FAILURES ===============================================================
________________________ YieldTest_sqlite+pysqlite_3_39_4.test_yield_per_close_on_interrupted_iteration_legacy ________________________
Traceback (most recent call last):
  File "/tmp/portage/dev-python/sqlalchemy-1.4.43/work/SQLAlchemy-1.4.43/test/orm/test_query.py", line 5442, in test_yield_per_close_on
_interrupted_iteration_legacy
    assert asserted_result[0]._soft_closed
AssertionError: assert False
 +  where False = <sqlalchemy.engine.result.ScalarResult object at 0x00007f0c4c45cc28>._soft_closed
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
b'hi'
```

### Versions

- OS: Gentoo Linux
- Python: PyPy3.9 7.3.9
- SQLAlchemy: 1.4.43
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

This can be a bug in PyPy3's sqlite implementation. If you believe it is, I can pass it on upstream.

**Comment by zzzeek** [comment]
who knew that exceptions handled in generators only emit GeneratorExit as a result of gc.  

try this program out on pypy and cpython:

```py
import gc

def go():
    try:
        for i in range(10):
            yield i
    except GeneratorExit:
        print("generator exit")


try:
    for num in go():
        print(num)
        if num > 3:
            raise Exception("hi")
except:
    print("exception raised")

    print("about to call gc collect")
    # GeneratorExit on pypy doesn't occur until gc collect
    gc.collect()
```

**Comment by mgorny** [comment]
Thanks!

**Comment by zzzeek** [comment]
I raised this with them, this is more of an egregious bug:  https://foss.heptapod.net/pypy/pypy/-/issues/3840 

affects sqlalchemy 2.0 only
