### ISSUE TITLE
Using `Mapping[dict[str, str] | None]` throws `sqlalchemy.exc.ArgumentError

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8777]
First, using `Mapping[dict[str, str] | None]` throws `sqlalchemy.exc.ArgumentError` (but using `Mapping[dict[str, str]]` does not):

```python
from __future__ import annotations

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase):
    ...


class A(Base):
    __tablename__ = 'a'

    id: Mapped[int] = mapped_column(primary_key=True)
    has_something: Mapped[bool | None]
    json: Mapped[dict[str, str] | None] = mapped_column(JSONB(none_as_null=True))
```

_Originally posted by @bryanforbes in https://github.com/sqlalchemy/sqlalchemy/issues/8631#issuecomment-1307681443_

**Comment by zzzeek** [comment]
I would assume using `Optional[]` works also  ?  or ?    feel free to paste the stack trace as I'm just collecting issues for tomorrow.

**Comment by bryanforbes** [comment]
Yes, `Optional[dict[str, str]]` works. Here's the stack trace:

```
Traceback (most recent call last):
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 665, in __init__
    code = compile(arg, '<string>', 'eval')
  File "<string>", line 1
    dict[str
        ^
SyntaxError: '[' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 127, in eval_expression
    annotation = eval(expression, base_globals, None)
  File "<string>", line 1, in <module>
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 308, in inner
    return cached(*args, **kwds)
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 1308, in __class_getitem__
    params = tuple(_type_convert(p) for p in params)
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 1308, in <genexpr>
    params = tuple(_type_convert(p) for p in params)
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 142, in _type_convert
    return ForwardRef(arg, module=module)
  File "/Users/bryan/.local/share/asdf/installs/python/3.10.2/lib/python3.10/typing.py", line 667, in __init__
    raise SyntaxError(f"Forward reference must be an expression -- got {arg!r}")
SyntaxError: Forward reference must be an expression -- got 'dict[str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2139, in _extract_mapped_subtype
    annotated = de_stringify_annotation(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 114, in de_stringify_annotation
    annotation = eval_expression(annotation, originating_module)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 129, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation Mapped["dict[str", "str] | None"]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryan/Projects/Erasmus/foo.py", line 11, in <module>
    class A(Base):
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 606, in __init_subclass__
    super().__init_subclass__()
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 701, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 209, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 290, in setup_mapping
    return _ClassScanMapperConfig(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 525, in __init__
    self._scan_attributes()
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 968, in _scan_attributes
    generated_obj = self._collect_annotation(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1105, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2153, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not interpret annotation Mapped[dict[str, str] | None].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.
```

**Comment by zzzeek** [comment]
OK yes we do some string manipulation on the annotations
