### ISSUE TITLE
snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx', port=443): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by adityakumar1990** [sqlalchemy/sqlalchemy#8781]
### Describe the use case

snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx', port=443): Read timed out. (read timeout=60)
 I am making one connection or each row present in input file & all connections are made at the same time or parallelly 

### Databases / Backends / Drivers targeted

snowflake 
I am making concurrently multiple connection with host , sometimes it is working as expected ,but seems like when actual data operation happening for huge data for some customers(For each customer generating separate connection) I am getting below error
ERROR|2022-11-09 09:16:31,520: HTTPSConnectionPool(host='xxxxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 332, in recv_into
raise timeout("The read operation timed out")
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
snowflake.connector.vendored.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
raw_ret = session.request(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
snowflake.connector.vendored.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 837, in _request_exec_wrapper
return_object = self._request_exec(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1105, in _request_exec
raise RetryRequest(err)
snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx.xxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)

### Example Use

I am making concurrently multiple connection with host , sometimes it is working as expected ,but seems like when actual data operation happening for huge data for some customers(For each customer generating separate connection) I am getting below error
ERROR|2022-11-09 09:16:31,520: HTTPSConnectionPool(host='xxxxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 449, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 444, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 332, in recv_into
raise timeout("The read operation timed out")
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 451, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
snowflake.connector.vendored.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
raw_ret = session.request(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
snowflake.connector.vendored.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 837, in _request_exec_wrapper
return_object = self._request_exec(
File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1105, in _request_exec
raise RetryRequest(err)
snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx.xxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)

### Additional context

can you help me understand the main reason and any way we can increase the timeout period or any other mean to fix this issue

**Comment by CaselIT** [comment]
Hi,

I don't see how this is connected to sqlalchemy. You probably wanted to report to the snowflake people.
