### ISSUE TITLE
annotations dictionary caching does not re-use anon_map, can cause memory explosion

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8790]
it's hard to demonstrate this but we have a user case that has a cache key that can't be printed or even dumped to a file; the file hits 200G or so and I just break the program.  with the fix, the file goes to 2 M.

annotations dictionaries that point to `AliasedInsp` will re-cache-key the entire contents of `AliasedInsp` over and over again because we don't transfer anon map.

this demo shows a large cache key

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.ext.declarative import ConcreteBase
from sqlalchemy.orm import aliased
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Employee(ConcreteBase, Base):
    __tablename__ = "employee"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))

    __mapper_args__ = {
        "polymorphic_identity": "employee",
        "concrete": True,
    }


class Manager(Employee):
    __tablename__ = "manager"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    manager_data = Column(String(40))

    __mapper_args__ = {
        "polymorphic_identity": "manager",
        "concrete": True,
    }


class Engineer(Employee):
    __tablename__ = "engineer"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    engineer_info = Column(String(40))

    __mapper_args__ = {
        "polymorphic_identity": "engineer",
        "concrete": True,
    }


e1 = aliased(Employee)
e2 = aliased(Employee)


subq = select(e1).union_all(select(e2)).subquery()

anno = aliased(Employee, subq)

stmt = select(anno)

ck = stmt._generate_cache_key()


def count_tuples(tup):
    stack = [tup]

    sentinel = object()
    indent = -1
    num_elements = 0

    while stack:
        elem = stack.pop(0)
        if elem is sentinel:
            num_elements += 1
            indent -= 1
        elif isinstance(elem, tuple):
            if not elem:
                indent -= 1
            else:
                indent += 1
                stack = list(elem) + [sentinel] + stack
                indent -= 1
    return num_elements

print(count_tuples(ck))

```

the output is 778 tuples.   with the fix:

```diff
diff --git a/lib/sqlalchemy/sql/annotation.py b/lib/sqlalchemy/sql/annotation.py
index 262048bd1d..eda34c39be 100644
--- a/lib/sqlalchemy/sql/annotation.py
+++ b/lib/sqlalchemy/sql/annotation.py
@@ -94,12 +94,16 @@ class SupportsAnnotations(ExternallyTraversible):
     @util.memoized_property
     def _annotations_cache_key(self) -> Tuple[Any, ...]:
         anon_map_ = anon_map()
+
+        return self._gen_annotations_cache_key(anon_map_)
+
+    def _gen_annotations_cache_key(self, anon_map):
         return (
             "_annotations",
             tuple(
                 (
                     key,
-                    value._gen_cache_key(anon_map_, [])
+                    value._gen_cache_key(anon_map, [])
                     if isinstance(value, HasCacheKey)
                     else value,
                 )
diff --git a/lib/sqlalchemy/sql/cache_key.py b/lib/sqlalchemy/sql/cache_key.py
index 88148285c5..3fb8821c78 100644
--- a/lib/sqlalchemy/sql/cache_key.py
+++ b/lib/sqlalchemy/sql/cache_key.py
@@ -297,12 +297,14 @@ class HasCacheKey:
                             else None,
                         )
                     elif meth is InternalTraversal.dp_annotations_key:
-                        # obj is here is the _annotations dict.   however, we
-                        # want to use the memoized cache key version of it. for
-                        # Columns, this should be long lived.   For select()
-                        # statements, not so much, but they usually won't have
-                        # annotations.
-                        result += self._annotations_cache_key  # type: ignore
+                        # obj is here is the _annotations dict.  Table uses
+                        # a memoized version of it.  however in other cases,
+                        # we generate it given anon_map as we may be from a
+                        # Join, Aliased, etc.
+                        result += self._gen_annotations_cache_key(   # type: ignore
+                            anon_map
+                        )
+
                     elif (
                         meth is InternalTraversal.dp_clauseelement_list
                         or meth is InternalTraversal.dp_clauseelement_tuple

```

it becomes 170.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure anon_map is passed for most annotated traversals** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4188

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**ensure anon_map is passed for most annotated traversals** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4189

**Comment by zzzeek** [comment]
OK also removed some other elements here and there that aren't necessary for the caching.

keeping the new tests in place and reverting the changes shows how much the numbers changed:

```
AssertionError: Given int value 54986 is not within 5% of expected value 29796
assert 25190 < 1489
 +  where 25190 = abs((54986 - 29796))
_______________________________________________________________ EmbeddedSubqTest.test_cache_key_gen[tuples] _______________________________________________________________
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/test_cache_key.py", line 1107, in test_cache_key_gen
    int_within_variance(142, count_cache_key_tuples(ck), 0.05)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/testing/assertions.py", line 248, in int_within_variance
    assert (
AssertionError: Given int value 778 is not within 5% of expected value 142

```

**Comment by zzzeek** [comment]
it's important to note that the big "exponentiality" here is in number of columns.    Each column added to the query, adds the whole annotations thing all over again, which in turn they all have the larger number of columns within.     I'm doing some htop tests and you need to add a few dozen columns to these models to see the bigger memory differences.

just for posterity here's a mem test I'm running

```py
from sqlalchemy import Column, literal_column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String, create_engine
from sqlalchemy.ext.declarative import ConcreteBase
from sqlalchemy.orm import aliased, Session
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Employee(ConcreteBase, Base):
    __tablename__ = "employee"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))

    x1 = Column(Integer)
    x2 = Column(Integer)
    x3 = Column(Integer)
    x4 = Column(Integer)
    x5 = Column(Integer)
    x6 = Column(Integer)
    x7 = Column(Integer)
    x8 = Column(Integer)
    x9 = Column(Integer)
    x10 = Column(Integer)
    x11 = Column(Integer)
    x12 = Column(Integer)
    x13 = Column(Integer)
    x14 = Column(Integer)
    x15 = Column(Integer)
    x16 = Column(Integer)

    __mapper_args__ = {
        "polymorphic_identity": "employee",
        "concrete": True,
    }


class Manager(Employee):
    __tablename__ = "manager"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    manager_data = Column(String(40))

    m1 = Column(Integer)
    m2 = Column(Integer)
    m3 = Column(Integer)
    m4 = Column(Integer)
    m5 = Column(Integer)
    m6 = Column(Integer)
    m7 = Column(Integer)
    m8 = Column(Integer)
    m9 = Column(Integer)
    m10 = Column(Integer)
    m11 = Column(Integer)
    m12 = Column(Integer)
    m13 = Column(Integer)
    m14 = Column(Integer)
    m15 = Column(Integer)
    m16 = Column(Integer)

    __mapper_args__ = {
        "polymorphic_identity": "manager",
        "concrete": True,
    }


class Engineer(Employee):
    __tablename__ = "engineer"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    engineer_info = Column(String(40))

    e1 = Column(Integer)
    e2 = Column(Integer)
    e3 = Column(Integer)
    e4 = Column(Integer)
    e5 = Column(Integer)
    e6 = Column(Integer)
    e7 = Column(Integer)
    e8 = Column(Integer)
    e9 = Column(Integer)
    e10 = Column(Integer)
    e11 = Column(Integer)
    e12 = Column(Integer)
    e13 = Column(Integer)
    e14 = Column(Integer)
    e15 = Column(Integer)
    e16 = Column(Integer)

    __mapper_args__ = {
        "polymorphic_identity": "engineer",
        "concrete": True,
    }

Base.registry.configure()

e = create_engine("sqlite://")
Base.metadata.create_all(e)

session = Session(e)

while True:
    for i in range(100):
        e1 = aliased(Employee)
        e2 = aliased(Employee)

        subq = select(e1).union_all(select(e2)).subquery()

        anno = aliased(Employee, subq)

        stmt = select(anno)
        stmt = stmt.where(anno.name == literal_column("'harcoded name %d'" % i))

        session.execute(stmt)
```

using htop, i have data like this for different numbers of columns (above is 56 cols):

```
8 columns

1.4.43 w cache:   283M  67Mres
1.4.43 no cache:  255M  38Mres

1.4.44 w cache:  277M  61Mres   .02 variance 
1.4.44 no cache:  255M  38Mres   




24 columns

1.4.43 w cache:   336M  118M res  
1.4.43 no cache:  265M  49M res

1.4.44 w cache:  323M  105M res    .03 variance
1.4.44 no cache:  265M  48M res


56 columns

1.4.43 w cache:  416M 193M   
1.4.43 no cache: 

1.4.44 w cache:  384M 154M  .07 variance
1.4.44 no cache:  
```
