### ISSUE TITLE
Mapped detection does not work with module-qualified names

### ISSUE THREAD

**Issue by jbaudisch** [sqlalchemy/sqlalchemy#8853]
### Describe the bug

**2.0.0b2**

```
import sqlalchemy.orm

class Base(sqlalchemy.orm.DeclarativeBase):
    pass

class XYZ(Base):
    # [...]
    id: sqlalchemy.orm.Mapped[int] = sqlalchemy.orm.mapped_column(primary_key=True)
    # [...]

```
Works!

**2.0.0b3**
sqlalchemy.exc.ArgumentError: Could not interpret annotation sqlalchemy.orm.Mapped[int].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.

Adding a 'from ... import' solves this problem but is unwanted cause we always load external libs with the import xyz stmt in our project.

Was it intended to break such declaration or is it (hopefully) just a bug?

Greets

### To Reproduce

```python
import sqlalchemy.orm

class Base(sqlalchemy.orm.DeclarativeBase):
    pass

class XYZ(Base):
    # [...]
    id: sqlalchemy.orm.Mapped[int] = sqlalchemy.orm.mapped_column(primary_key=True)
    # [...]
```

### Error

Traceback (most recent call last):
  File "W:\sharly\core\main.py", line 117, in <module>
    main()
  File "W:\sharly\core\main.py", line 79, in main
    from sharly.components.persistence.orm import ORMPersistenceComponent
  File "W:\sharly\core\sharly\components\persistence\orm.py", line 21, in <module>
    from sharly.components.persistence.orm_model import *
  File "W:\sharly\core\sharly\components\persistence\orm_model.py", line 47, in <module>
    class ORM_Owner(ORM_Base):
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 701, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 209, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 290, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 525, in __init__
    self._scan_attributes()
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 968, in _scan_attributes
    generated_obj = self._collect_annotation(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 1105, in _collect_annotation
    extracted = _extract_mapped_subtype(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\sharly\core\.venv\Lib\site-packages\sqlalchemy\orm\util.py", line 2146, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not interpret annotation sqlalchemy.orm.Mapped[int].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.

### Versions

- OS: Windows
- Python: 3.11
- SQLAlchemy: 2.0.0b3
- Database: MySQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysqlclient

**Comment by CaselIT** [comment]
Hi

Thanks for reporting. I think it's just a bug. Sadly some parsing of the typing string is required internally by sqlalchemy, and it seems this case was not covered

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fall back to eval() for names that have dots** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4226

**Comment by zzzeek** [comment]
this did not get fixed.    the above case fails if you add `from __future__ import annotations`, which is in the test suite, which means the test is failing to test the bug.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply a fixed locals w/ Mapped to all de-stringify** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4458

**Comment by pamelafox** [comment]
I ran into a few more cases of this in my Flask-SQLAlchemy branch tests, I don't know if they're intended to work or not:

Using sa.orm.Mapped:

```
from __future__ import annotations

from typing import List

import sqlalchemy as sa
import sqlalchemy.orm as sa_orm

class Base(sa_orm.DeclarativeBase, sa_orm.MappedAsDataclass):
    pass

class Todo(Base):
      __tablename__ = "todos"
      id:sa.orm.Mapped[int] = sa_orm.mapped_column(sa.Integer, primary_key=True)
      title:sa.orm.Mapped[str] = sa_orm.mapped_column(sa.String, nullable=True)

# Set up a database connection and create tables
engine = sa.create_engine("sqlite:///my_database.db", echo=True)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
```

Using sa_orm.Mapped:

```
from __future__ import annotations

from typing import List

import sqlalchemy as sa
import sqlalchemy.orm as sa_orm

class Base(sa_orm.DeclarativeBase, sa_orm.MappedAsDataclass):
    pass

class Todo(Base):
      __tablename__ = "todos"
      id:sa_orm.Mapped[int] = sa_orm.mapped_column(sa.Integer, primary_key=True)
      title:sa_orm.Mapped[str] = sa_orm.mapped_column(sa.String, nullable=True)

# Set up a database connection and create tables
engine = sa.create_engine("sqlite:///my_database.db", echo=True)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
```

There's definitely a workaround here, to not use aliasing, but the current repo uses aliasing so that's why I ran into the issue.

**Comment by CaselIT** [comment]
using `sa.orm.things` usually fails typecheck since there is no orm package exported by the global sqlalchemy module, even if python module resolution adds it at runtime once `sqlalchemy.orm` is imported at least once.

the second `sa_orm` should probably work. cc @zzzeek

**Comment by pamelafox** [comment]
Yeah, there's a PR in Flask-SQLAlchemy to move from sa.orm to sa_orm, so it'd be nice if at least sa_orm could work.

**Comment by zzzeek** [comment]
the two cases above seem to work for me at runtime?  are we talking about a runtime failure?

**Comment by pamelafox** [comment]
Ah, I was getting this error at runtime:

```
(flask-sqlalchemy-3.9) ?1flask-sqlalchemy % pdm run python mapped.py  
Traceback (most recent call last):
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 189, in eval_expression
    annotation = eval(expression, base_globals, None)
  File "<string>", line 1, in <module>
NameError: name 'Mapped' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 2270, in _extract_mapped_subtype
    annotated = de_stringify_annotation(
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 151, in de_stringify_annotation
    annotation = eval_expression(annotation, originating_module)
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 191, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'Mapped["int"]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pamelafox/flask-sqlalchemy/mapped.py", line 11, in <module>
    class Todo(Base):
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_api.py", line 768, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 246, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 327, in setup_mapping
    return _ClassScanMapperConfig(
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 558, in __init__
    self._scan_attributes()
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1000, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1142, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/Users/pamelafox/flask-sqlalchemy/.venv/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 2284, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not interpret annotation sa_orm.Mapped[int].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.
```

But I just updated to 2.0.15 and am no longer getting the error! Even sa.orm.Mapped is working now. Thanks for the fix!

**Comment by CaselIT** [comment]
ok, great, so it was fixed correctly. thanks for confirming
