### ISSUE TITLE
unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed

### ISSUE THREAD

**Issue by floydljy** [sqlalchemy/sqlalchemy#8871]
### Describe the bug

got error in following code, not very complicated:
```
 async with getDbSession() as session:
    async with session.begin():
        logger.info("try to check message id: {}", request.headers.get("MSGID"))
        exist_api = await AsyncApiMapper.get_by_message_id(session, request.headers.get("MSGID"))
```
The asyncApiMapper:
```
class AsyncApiMapper(BaseMapper):
    __tablename__ = "t_async"
    msg_id = Column(String(50), index=True)
    method = Column(String(10))
    trans_id = Column(String(50))
    callback_url = Column(String(500))
    job_id = Column(String(50))
    request_url = Column(String(1000))
    status = Column(Enum(AysncApiStatus))

    @classmethod
    async def get_by_message_id(cls, session, message_id) -> 'AsyncApiMapper':
        stmt = select(cls).where(cls.msg_id == message_id)
        result = await session.scalars(stmt)
        return result.first()
```
it got error :
```
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 341, in write
    self._transport.write(data)
    │    │          │     └ b'\x01\x00\x00\x00\x0e'
    │    │          └ <method 'write' of 'uvloop.loop.UVStream' objects>
    │    └ <TCPTransport closed=True reading=False 0x7f846b618920>
    └ <StreamWriter transport=<TCPTransport closed=True reading=False 0x7f846b618920> reader=<StreamReader exception=TimeoutError(1...
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
    self._ensure_alive()
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
    raise RuntimeError(

RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed
2022-11-25 16:14:55.910|INFO | ctweb.handlers.async_north_handler:set_resp_header:142 |JT202000008788-2|`cat /proc/sys/kernel/random/uuid`| SNC Response: 
Headers: <Header('MSGID': '`cat /proc/sys/kernel/random/uuid`', 'TRANSID': 'JT202000008788-2', 'JOBID': '11111111-2eba-5aab-aa74-d4d1a8f94962', 'Content-Type': 'application/json; charset=utf-8')>
Body compressed: {"resultCode":"1111","resultMsg":"unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed"}
2022-11-25 16:14:55,911 ERROR sqlalchemy.pool.impl.AsyncAdaptedQueuePool The garbage collector is trying to clean up connection <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
2022-11-25 16:14:55.911|ERROR| sqlalchemy.log:log:179 ||| The garbage collector is trying to clean up connection <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
2022-11-25 16:15:20.972|DEBUG| libs.service_discovery:update_mapping_cache:61 ||| Mapping server scaned: {'mapping-0.mapping:15003', 'mapping-1.mapping:15003'}

```
full trace, please check the "Error" parts

### To Reproduce

```python
Not very easy to reproduce, it did not happen all the time. 
I feel it often occurs at following situation:
1. first call runs well
2. wait for some while
3. send call failed.
```

### Error

```
2022-11-25 16:14:55.901|ERROR| handlers.exception_handler:default:33 ||| unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed
Traceback (most recent call last):

  File "service_main.py", line 90, in <module>
    app.run(port=listen_port, debug=False)
    │   │        └ 1337
    │   └ <function WebApp.run at 0x7f846df84ee0>
    └ <ctweb.app.WebApp object at 0x7f846df6d9a0>

  File "/usr/local/lib/python3.8/site-packages/ctweb/app.py", line 43, in run
    self._app.run(host='0.0.0.0', port=port, access_log=False,
    │    │    │                        └ 1337
    │    │    └ <function RunnerMixin.run at 0x7f8470b92ee0>
    │    └ Sanic(name="CT-SNC")
    └ <ctweb.app.WebApp object at 0x7f846df6d9a0>
  File "/usr/local/lib/python3.8/site-packages/sanic/mixins/runner.py", line 168, in run
    self.__class__.serve(primary=self)  # type: ignore
    │    │                       └ Sanic(name="CT-SNC")
    │    └ <attribute '__class__' of 'object' objects>
    └ Sanic(name="CT-SNC")
  File "/usr/local/lib/python3.8/site-packages/sanic/mixins/runner.py", line 667, in serve
    serve_single(primary_server_info.settings)
    │            │                   └ {'protocol': <class 'sanic.server.protocols.http_protocol.HttpProtocol'>, 'host': '0.0.0.0', 'port': 1337, 'version': <HTTP.V...
    │            └ ApplicationServerInfo(settings={'protocol': <class 'sanic.server.protocols.http_protocol.HttpProtocol'>, 'host': '0.0.0.0', '...
    └ <function serve_single at 0x7f84710d4ca0>
  File "/usr/local/lib/python3.8/site-packages/sanic/server/runners.py", line 324, in serve_single
    serve(**server_settings)
    │       └ {'protocol': <class 'sanic.server.protocols.http_protocol.HttpProtocol'>, 'host': '0.0.0.0', 'port': 1337, 'version': <HTTP.V...
    └ <function serve at 0x7f84710bd5e0>
  File "/usr/local/lib/python3.8/site-packages/sanic/server/runners.py", line 106, in serve
    return _serve_http_1(
           └ <function _serve_http_1 at 0x7f84710d4b80>
  File "/usr/local/lib/python3.8/site-packages/sanic/server/runners.py", line 265, in _serve_http_1
    _run_server_forever(
    └ <function _run_server_forever at 0x7f84710d4af0>
  File "/usr/local/lib/python3.8/site-packages/sanic/server/runners.py", line 151, in _run_server_forever
    loop.run_forever()
    │    └ <method 'run_forever' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
  File "connection_task", line 15, in connection_task
  File "/usr/local/lib/python3.8/site-packages/sanic/http/http1.py", line 127, in http1
    await self.protocol.request_handler(self.request)
          │    │                        │    └ <member 'request' of 'Http' objects>
          │    │                        └ <sanic.http.http1.Http object at 0x7f847128a1e0>
          │    └ <member 'protocol' of 'Http' objects>
          └ <sanic.http.http1.Http object at 0x7f847128a1e0>
> File "handle_request", line 62, in handle_request
  File "_run_request_middleware", line 28, in _run_request_middleware
  File "/usr/local/lib/python3.8/site-packages/ctweb/handlers/async_north_handler.py", line 75, in set_req_header
    exist_api = await AsyncApiMapper.get_by_message_id(session, request.headers.get("MSGID"))
                      │              │                 │        │       └ <member 'headers' of 'Request' objects>
                      │              │                 │        └ <Request: POST /serviceAgent/rest/B/data/srv6_l3_evpn_all>
                      │              │                 └ <sqlalchemy.orm.session.AsyncSession object at 0x7f846d9cfa90>
                      │              └ <classmethod object at 0x7f846faa59a0>
                      └ <class 'ctweb.mapper.async_api_mapper.AsyncApiMapper'>
  File "/usr/local/lib/python3.8/site-packages/ctweb/mapper/async_api_mapper.py", line 27, in get_by_message_id
    result = await session.scalars(stmt)
                   │       │       └ <sqlalchemy.sql.selectable.Select object at 0x7f846daf7ee0>
                   │       └ <function AsyncSession.scalars at 0x7f846feb7700>
                   └ <sqlalchemy.orm.session.AsyncSession object at 0x7f846d9cfa90>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 269, in scalars
    result = await self.execute(
                   │    └ <function AsyncSession.execute at 0x7f846feb75e0>
                   └ <sqlalchemy.orm.session.AsyncSession object at 0x7f846d9cfa90>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
    result = await greenlet_spawn(
                   └ <function greenlet_spawn at 0x7f8470ac00d0>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             │       │      │   └ <built-in function exc_info>
             │       │      └ <module 'sys' (built-in)>
             │       └ <method 'throw' of 'greenlet.greenlet' objects>
             └ <_AsyncIoGreenlet object at 0x7f846ddfa700 (otid=0x7f8470b38b10) dead>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
           │    └ <function Session._connection_for_bind at 0x7f846ff92790>
           └ <sqlalchemy.orm.session.Session object at 0x7f846d9cfac0>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    └ None
           └ <sqlalchemy.orm.session.Session object at 0x7f846d9cfac0>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f84702b2280>
           └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
                 │       └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
                 └ <class 'sqlalchemy.future.engine.Engine'>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
           │    └ <class 'sqlalchemy.future.engine.Connection'>
           └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f84703d0700>
         └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f84703f6a60>
           │    │                  │    └ <sqlalchemy.pool.impl.AsyncAdaptedQueuePool object at 0x7f846dfa6430>
           │    │                  └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
           │    └ <function Engine._wrap_pool_connect at 0x7f84703d0310>
           └ Engine(mysql+aiomysql://ipsdn_app:***@10.145.158.226:8801/ipsdndb?charset=utf8mb4)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.AsyncAdaptedQueuePool object at 0x7f846dfa6430>>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.AsyncAdaptedQueuePool object at 0x7f846dfa6430>
           │                └ <classmethod object at 0x7f84703f2cd0>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
             │    │        │       │     └ <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>
             │    │        │       └ <sqlalchemy.pool.base._ConnectionFairy object at 0x7f846daf7790>
             │    │        └ <function MySQLDialect_mysqldb.do_ping at 0x7f846de41af0>
             │    └ <sqlalchemy.dialects.mysql.aiomysql.MySQLDialect_aiomysql object at 0x7f846df6d3d0>
             └ <sqlalchemy.pool.impl.AsyncAdaptedQueuePool object at 0x7f846dfa6430>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 183, in do_ping
    dbapi_connection.ping(False)
    │                └ <function AsyncAdapt_aiomysql_connection.ping at 0x7f846e03f0d0>
    └ <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 190, in ping
    return self.await_(self._connection.ping(reconnect))
           │    │      │    │                └ False
           │    │      │    └ <member '_connection' of 'AsyncAdapt_aiomysql_connection' objects>
           │    │      └ <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>
           │    └ <staticmethod object at 0x7f846e035760>
           └ <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
           │                     └ <coroutine object Connection.ping at 0x7f846b5b5440>
           └ <_AsyncIoGreenlet object at 0x7f846ddfa700 (otid=0x7f8470b38b10) dead>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
                  └ <coroutine object Connection.ping at 0x7f846b5b5440>
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 493, in ping
    await self._execute_command(COMMAND.COM_PING, "")
          │    │                │       └ 14
          │    │                └ <module 'pymysql.constants.COMMAND' from '/usr/local/lib/python3.8/site-packages/pymysql/constants/COMMAND.py'>
          │    └ <function Connection._execute_command at 0x7f846debc9d0>
          └ <aiomysql.connection.Connection object at 0x7f846d9d1340>
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 713, in _execute_command
    self._write_bytes(prelude + sql[:chunk_size - 1])
    │    │            │         │    └ 1
    │    │            │         └ b''
    │    │            └ b'\x01\x00\x00\x00\x0e'
    │    └ <function Connection._write_bytes at 0x7f846debc700>
    └ <aiomysql.connection.Connection object at 0x7f846d9d1340>
  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 658, in _write_bytes
    return self._writer.write(data)
           │    │       │     └ b'\x01\x00\x00\x00\x0e'
           │    │       └ <function StreamWriter.write at 0x7f8472a7b3a0>
           │    └ <StreamWriter transport=<TCPTransport closed=True reading=False 0x7f846b618920> reader=<StreamReader exception=TimeoutError(1...
           └ <aiomysql.connection.Connection object at 0x7f846d9d1340>
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 341, in write
    self._transport.write(data)
    │    │          │     └ b'\x01\x00\x00\x00\x0e'
    │    │          └ <method 'write' of 'uvloop.loop.UVStream' objects>
    │    └ <TCPTransport closed=True reading=False 0x7f846b618920>
    └ <StreamWriter transport=<TCPTransport closed=True reading=False 0x7f846b618920> reader=<StreamReader exception=TimeoutError(1...
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
    self._ensure_alive()
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
    raise RuntimeError(

RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed
2022-11-25 16:14:55.910|INFO | ctweb.handlers.async_north_handler:set_resp_header:142 |JT202000008788-2|`cat /proc/sys/kernel/random/uuid`| SNC Response: 
Headers: <Header('MSGID': '`cat /proc/sys/kernel/random/uuid`', 'TRANSID': 'JT202000008788-2', 'JOBID': '11111111-2eba-5aab-aa74-d4d1a8f94962', 'Content-Type': 'application/json; charset=utf-8')>
Body compressed: {"resultCode":"1111","resultMsg":"unable to perform operation on <TCPTransport closed=True reading=False 0x7f846b618920>; the handler is closed"}
2022-11-25 16:14:55,911 ERROR sqlalchemy.pool.impl.AsyncAdaptedQueuePool The garbage collector is trying to clean up connection <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
2022-11-25 16:14:55.911|ERROR| sqlalchemy.log:log:179 ||| The garbage collector is trying to clean up connection <AdaptedConnection <aiomysql.connection.Connection object at 0x7f846d9d1340>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
2022-11-25 16:15:20.972|DEBUG| libs.service_discovery:update_mapping_cache:61 ||| Mapping server scaned: {'mapping-0.mapping:15003', 'mapping-1.mapping:15003'}

``` 

### Versions

- OS: Linux Ubuntu 20.04
- Python: 3.8.10
- SQLAlchemy: 1.4.42
- Database: mysql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

### Additional context

None

**Comment by zzzeek** [comment]
this is an error raised by your web framework. SQLAlchemy does not make any use of HTTP nor does aiomysql (which BTW is a buggy driver in any case).  The "ERROR" you see regarding the pool cleanup is normal and occurs when an asyncio connection is discarded without being cleanly closed, which in this case is happening because your web framework is crashing.

**Comment by zzzeek** [comment]
specifically it looks like aiomysql's "ping" is raising a RuntimeError and not a DBAPI error of some kind.   that would be a bug.

**Comment by zzzeek** [comment]
if by "some while" you mean "eight hours", which is MySQL's default client timeout, set [pool_recycle](https://docs.sqlalchemy.org/en/14/core/pooling.html#pool-setting-recycle).  but also report to aiomysql their ping is broken

**Comment by floydljy** [comment]
> if by "some while" you mean "eight hours", which is MySQL's default client timeout, set [pool_recycle](https://docs.sqlalchemy.org/en/14/core/pooling.html#pool-setting-recycle). but also report to aiomysql their ping is broken

Dear Mike:
Thanks for your update. the "some while" is only a couple of minutes. so that's should not be related to pool recycle thing. I have already set pre_ping to avoid the pool recycle after 8 hours. actually, there's no eight hours to close, most of the time, it close very soon, and i think it depends on the database settings. and I can see the pre_ping works well. 
 I use the "async with" syntax, and I think that will help me clean the connection after excuting the query inside it. is my understanding right about it?
```
async with getDbSession() as session:
    async with session.begin():
        logger.info("try to check message id: {}", request.headers.get("MSGID"))
        exist_api = await AsyncApiMapper.get_by_message_id(session, request.headers.get("MSGID"))
```
and about the aiomysql, you refered that ping is broken and it is a buggy driver.  Cause I don't have any preference about which DBAPI to choose. so may i ask which DBAPI is more stable? I'm using mysql as the database. 
Thansk for you help again.
Jason.
