### ISSUE TITLE
add dataclass args + intercept to assocaition proxy

### ISSUE THREAD

**Issue by daemonkeeper** [sqlalchemy/sqlalchemy#8876]
### Describe the bug

When using the DataclassMixin as a declarative base (https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.MappedAsDataclass) one can extend relationship/mapped_column functions with with dataclass.Field arguments within reason. For instance, one can do

```python
class BaseModel(MappedAsDataclass, DeclarativeBase, kw_only=True):
    pass


class MyModel(MappedAsDataclass):
   attribute: Mapped[int] = mapped_column(init=False, repr=True)
```

cf. https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#attribute-configuration

However, this does not work for attributes declared with association_proxy() as per the doc

```python
class BaseModel(MappedAsDataclass, DeclarativeBase, kw_only=True):
    pass


class MyModel(MappedAsDataclass):
   attribute: Mapped[int] = association_proxy("some_ref", "keyword", repr=True)
```

This gives 

```
/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/ext/associationproxy.py:132: in association_proxy
    return AssociationProxy(target_collection, attr, **kw)
E   TypeError: AssociationProxy.__init__() got an unexpected keyword argument 'repr'
```

Presumably, the association_proxy helper hasn't been updated to support dataclass mixins. 

### To Reproduce

```python
# simply use https://docs.sqlalchemy.org/en/20/orm/extensions/associationproxy.html#simplifying-association-objects
# and declare User as 

class User(Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(primary_key=True, repr=True, init=False)
    name: Mapped[str] = mapped_column(repr=True, init=True)

    user_keyword_associations = relationship(
        "UserKeywordAssociation",
        back_populates="user",
        cascade="all, delete-orphan",
        init=False
    )
    # association proxy of "user_keyword_associations" collection
    # to "keyword" attribute
    keywords = association_proxy("user_keyword_associations", "keyword", repr=True)
```

### Error

```
/opt/homebrew/bin/python3 /Users/me/Library/Application Support/JetBrains/PyCharmCE2022.2/scratches/scratch_1.py 
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/JetBrains/PyCharmCE2022.2/scratches/scratch_1.py", line 14, in <module>
    class User(Base):
  File "/Users/me/Library/Application Support/JetBrains/PyCharmCE2022.2/scratches/scratch_1.py", line 28, in User
    keywords = association_proxy("user_keyword_associations", "keyword", repr=True)
  File "/opt/homebrew/lib/python3.10/site-packages/sqlalchemy/ext/associationproxy.py", line 132, in association_proxy
    return AssociationProxy(target_collection, attr, **kw)
TypeError: AssociationProxy.__init__() got an unexpected keyword argument 'repr'``` 

### Versions

- OS: OSX 12.6.1
- Python: 3.10.6
- SQLAlchemy: 2.0.0b2
- Database: N/A
- DBAPI N/A

### Additional context

_No response_

**Comment by zzzeek** [comment]
well there's no doc for this, association_proxy is not part of the declarative mapping process at all, it's just a descriptor class that is added.    same for hybrid.    Both of these aren't even yet documented for how they would be explicitly annotated (and it would not be Mapped[], since they are not Mapped).  as for dataclasses, there's not a good way for this to happen right now without a good deal of thinking.

**Comment by zzzeek** [comment]
it looks like associationproxy works completely fine w/ the dataclass support right now, with the exception of the extra arguments.

correct form is:

```py
class User(MappedAsDataclass, Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(primary_key=True, repr=True, init=False)
    name: Mapped[str] = mapped_column(repr=True, init=True)

    user_keyword_associations: Mapped[UserKeywordAssociation] = relationship(
        "UserKeywordAssociation",
        back_populates="user",
        cascade="all, delete-orphan",
        init=False
    )

    keywords: AssociationProxy[list[str]] = association_proxy("user_keyword_associations", "keyword")

```

what doesnt work is using the descriptor as the default for a `dataclasses.field`, which seems to work for a plain descriptor.  there's some other reasons for that I will fix also

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: annotated / DC forms for association proxy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4240
