### ISSUE TITLE
Missing support for 'compare' on dataclass field

### ISSUE THREAD

**Issue by simonschiele** [sqlalchemy/sqlalchemy#8905]
### Describe the bug

I'm playing around with the annotated declarative setups for my Models and realized that we are missing support for the `compare` argument for `dataclasses.field()`.

Support for the general `eq` parameter (the toggle to build `__eq__` on dataclass generation) on class-level is available, what I'm missing is the corresponding `compare` boolean-argument on field-level that defines if a field should be used for comparison by `__eq__`.

It would be really helpful to have that one supported, since we often have some kind of dynamic data on initialization of database models ('created/changed timestamp', 'UUID as primary key', ...) that might not be desired/relevant for comparison.

Proposal for adding support for the compare argument attached as PR.

### To Reproduce

```python
import uuid

class A(dc_decl_base):
    __tablename__ = "a"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default_factory=uuid.uuid4,
        init=False,
        compare=False)
    data: Mapped[str]


a1 = A(data='foo')
a2 = A(data='foo')
assert a1 == a2
```

### Error

```
Traceback (most recent call last):
  File "/home/simon/repos/thirdparty/sqlalchemy/test/orm/declarative/test_dc_transforms.py", line 570, in test_compare
    class A(dc_decl_base):
  File "/home/simon/repos/thirdparty/sqlalchemy/test/orm/declarative/test_dc_transforms.py", line 573, in A
    id: Mapped[int] = mapped_column(primary_key=True, compare=False)
  File "/home/simon/repos/thirdparty/sqlalchemy/.tox/py/lib/python3.10/site-packages/sqlalchemy/orm/_orm_constructors.py", line 256, in mapped_column
    return MappedColumn(
  File "/home/simon/repos/thirdparty/sqlalchemy/.tox/py/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 577, in __init__
    self.column = cast("Column[_T]", Column(*arg, **kw))
  File "/home/simon/repos/thirdparty/sqlalchemy/.tox/py/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 1977, in __init__
    self._extra_kwargs(**dialect_kwargs)
  File "/home/simon/repos/thirdparty/sqlalchemy/.tox/py/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 2038, in _extra_kwargs
    self._validate_dialect_kwargs(kwargs)
  File "/home/simon/repos/thirdparty/sqlalchemy/.tox/py/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 547, in _validate_dialect_kwargs
    raise TypeError(
TypeError: Additional arguments should be named <dialectname>_<argument>, got 'compare'

``` 

### Versions

- OS: Linux (Debian, testing)
- Python: 3.10
- SQLAlchemy: 2.0.0b4
- Database: sqlite (memory)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): -

**Comment by CaselIT** [comment]
Hi,

thanks for reporting

**Comment by sqla-tester** [comment]
**Simon Schiele** has proposed a fix for this issue in the **main** branch:

**Add "compare" on dataclass fields** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4254
