### ISSUE TITLE
add fast_executemany deprecation to 2.0 changelog notes; investigate possible API mis-use when it's enabled w/ bulk (add tests?)

### ISSUE THREAD

**Issue by phofl** [sqlalchemy/sqlalchemy#8917]
### Describe the bug

When using ``fast_executemany`` and doing effectively a bulk_insert t we get an error for 2.0.0b3. This works on the 1.4.x branch. 

It seems that this happens because it runs through ``do_execute`` instead of ``do_execute_many`` now. (not sure if this is a bug in pyodbc)

https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#optimized-orm-bulk-insert-now-implemented-for-all-backends-other-than-mysql

Is this expected in 2.0?

### To Reproduce

```python
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, MetaData, Column, Integer, Unicode

con_str = "mssql+pyodbc://your_connection_string"

meta = MetaData()
Base = declarative_base(metadata=meta)


class User(Base):
    __tablename__ = "user"
    user_id = Column("user_id", Integer, primary_key=True)
    test = Column("test", Integer, nullable=False)
    user_name = Column("user_name", Unicode(50), nullable=False)


engine = create_engine(con_str, fast_executemany=True)
meta.create_all(engine)

data = [{"user_id": 1, "test": 1, "user_name": "a"}, {"user_id": 2, "test": 1, "user_name": 5}]

with Session(engine) as session:
    session.bulk_insert_mappings(User, data)
    session.commit()
```

### Error

```
/Users/patrick/mambaforge/envs/random/bin/python /Users/patrick/Library/Application Support/JetBrains/PyCharm2022.2/scratches/scratch.py 
Traceback (most recent call last):
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2100, in _exec_insertmany_context
    dialect.do_execute(cursor, sub_stmt, sub_params, context)
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 743, in do_execute
    cursor.execute(statement, parameters)
pyodbc.DataError: ('22018', "[22018] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'a' to data type int. (245) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patrick/Library/Application Support/JetBrains/PyCharm2022.2/scratches/scratch.py", line 353, in <module>
    session.bulk_insert_mappings(User, data)
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4271, in bulk_insert_mappings
    self._bulk_save_mappings(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4358, in _bulk_save_mappings
    with util.safe_reraise():
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4347, in _bulk_save_mappings
    bulk_persistence._bulk_insert(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 176, in _bulk_insert
    result = persistence._emit_insert_statements(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1011, in _emit_insert_statements
    result = connection.execute(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 487, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1837, in _execute_context
    return self._exec_insertmany_context(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2103, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2100, in _exec_insertmany_context
    dialect.do_execute(cursor, sub_stmt, sub_params, context)
  File "/Users/patrick/mambaforge/envs/random/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 743, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (pyodbc.DataError) ('22018', "[22018] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'a' to data type int. (245) (SQLExecDirectW)")
[SQL: INSERT INTO [user] (user_id, test, user_name) VALUES (?, ?, ?), (?, ?, ?)]
[parameters: (1, 1, 'a', 2, 1, 5)]
(Background on this error at: https://sqlalche.me/e/20/9h9h)``` 
```
### Versions

- OS: MacOs and Ubuntu
- Python: 3.10.5
- SQLAlchemy: 2.0.0b3
- Database: MS SQL 2019
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

### Additional context

This errors too if using 2.0.0b3 syntax with 

```
with Session(engine) as session:
    session.execute(insert(User), data)
    session.commit()
```

**Comment by CaselIT** [comment]
On second look it seems that pyodbc is trying to the opposite, so string to int, even if the type is a string.

> Conversion failed when converting the nvarchar value 'a' to data type int.

Not sure why it's trying to do that

**Comment by zzzeek** [comment]
> ### Describe the bug
> 
> When using `fast_executemany` and doing effectively a bulk_insert t we get an error for 2.0.0b3. This works on the 1.4.x branch.

Yes I would recommend not using fast_executemany.  See https://docs.sqlalchemy.org/en/20/dialects/mssql.html#fast-executemany-mode

> 
> ### Error

the stack trace here is not totally expected, but fast_executemany highly modifies how things work so this may be because we aren't turning off setinputsizes().    

For the issue here, we should add more notes to the migration log and maybe see if we can fix this trace, however, I would advise walking away from fast_executemany overall as SQLAlchemy's feature is expected to be much more robust.

**Comment by zzzeek** [comment]
OK here is what happens.

The statement that SQL server wont do without extra steps is this:

```py
conn = engine.raw_connection()
cursor = conn.cursor()
cursor.execute("SET IDENTITY_INSERT [user] ON")

cursor.execute("""
     INSERT INTO [user] (user_id, test, user_name) VALUES (?, ?, ?), (?, ?, ?)
""", (1, 1, 'a', 2, 1, 5))
```

any other version of this statement succeeds - if you put 5 for the string as just one row, it succeeds or use executemany(), etc.    so in 1.4 there's no way to reproduce the error without just running the exact statement above.

in 2.0, the above statement is what insertmanyvalues does.     however, in 2.0 we also turn on use_setinputsizes by default now also.  so using setinputsizes allows the above statement to work:

```py
conn = engine.raw_connection()
cursor = conn.cursor()
cursor.execute("SET IDENTITY_INSERT [user] ON")

cursor.setinputsizes([
    (pyodbc.SQL_INTEGER, None, None),
    (pyodbc.SQL_INTEGER, None, None),
    (pyodbc.SQL_VARCHAR, None, None),
    (pyodbc.SQL_INTEGER, None, None),
    (pyodbc.SQL_INTEGER, None, None),
    (pyodbc.SQL_VARCHAR, None, None),
])

cursor.execute("""
     INSERT INTO [user] (user_id, test, user_name) VALUES (?, ?, ?), (?, ?, ?)
""", (1, 1, 'a', 2, 1, 5))
```

SQLAlchemy 2.0 will fail if we turn off the setinputsizes step as well:

```py
engine = create_engine(
    con_str,
    use_setinputsizes=False,
    echo=True)
```

Where there is in fact a slight bug, is that in 2.0 we also made it so that if fast_executemany is on, we automatically skip "setinputsizes" for an executemany(), since this is known to be buggy in pyodbc.    The bug is, that check is not honoring that we are in fact going to do an insertmanyvalues, not a real "executemany". 

this is the fix

```diff
diff --git a/lib/sqlalchemy/connectors/pyodbc.py b/lib/sqlalchemy/connectors/pyodbc.py
index f920860cd8..e8fbed18eb 100644
--- a/lib/sqlalchemy/connectors/pyodbc.py
+++ b/lib/sqlalchemy/connectors/pyodbc.py
@@ -209,7 +209,10 @@ class PyODBCConnector(Connector):
         # omit the setinputsizes calls for .executemany() with
         # fast_executemany=True
 
-        if context.executemany and self.fast_executemany:
+        if (
+            context.execute_style is interfaces.ExecuteStyle.EXECUTEMANY
+            and self.fast_executemany
+        ):
             return
 
         cursor.setinputsizes(
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**disable setinputsizes only for true DBAPI executemany** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4257

**Comment by zzzeek** [comment]
sorta fun sorta not really.
