### ISSUE TITLE
Using `text("generated by default as identity")` as server default generates a syntax error in SQL with postgres database.

### ISSUE THREAD

**Issue by liuuuk311** [sqlalchemy/sqlalchemy#8946]
### Describe the bug

Using `text("generated by default as identity")` as server default generates a syntax error in SQL with a postgres database.

```py
class MyModel(Base):
    id = Column(Integer, primary_key=True, server_default=text(f"generated by default as identity"))
```

Generates the following error:
```
    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       psycopg2.errors.SyntaxError: syntax error at or near "by"
E       LINE 5:  id INTEGER DEFAULT generated by default as identity NOT NULL [...]
```

**Expected behavior**
No errors and the SQL command should be `id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL`.

### To Reproduce

```python
# Run the following code.

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine("postgresql+psycopg2://postgres:root@127.0.0.1:5432/postgres")
Base = declarative_base()

class MyModel(Base):
     __tablename__ = "my_table"
     id = Column(Integer, primary_key=True, server_default=text("generated by default as identity"))

Base.metadata.create_all(engine)
```

### Error

```
Traceback (most recent call last):
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "by"
LINE 3:  id INTEGER DEFAULT generated by default as identity NOT NUL...
                                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 849, in visit_metadata
    self.traverse_single(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
    self.connection.execute(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/luca/.venvs/cedar/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "by"
LINE 3:  id INTEGER DEFAULT generated by default as identity NOT NUL...
                                      ^

[SQL: 
CREATE TABLE my_table (
        id INTEGER DEFAULT generated by default as identity NOT NULL, 
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
``` 

### Versions

 - OS: macOS 13.0.1
 - Python: 3.9
 - Alembic: 1.8.1
 - SQLAlchemy: 1.4.31
 - Database: Postgres 14.1
 - DBAPI: psycopg2

**Comment by CaselIT** [comment]
Hi,

Identity columns or generated are not default and they cannot be set as server_default text.
Please use the Identity or Computed constructs
