### ISSUE TITLE
regression: immedaiteload fallback fails

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8996]
regression from #8126 

```py

from sqlalchemy import *
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import *
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    bs = relationship("B", lazy="selectin")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)



s = Session(e)

a1 = A(bs=[B()])
s.add(a1)
s.commit()

s.expire(a1, ["name"])
s.refresh(a1, ["name", 'bs'])


```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test4.py", line 34, in <module>
    s.refresh(a1, ["name", 'bs'])
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 2696, in refresh
    loading.load_on_ident(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 478, in load_on_ident
    return load_on_pk_identity(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 613, in load_on_pk_identity
    return result.one()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1673, in one
    return self._only_one_row(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 715, in _only_one_row
    row: Optional[_InterimRowType[Any]] = onerow(hard_close=True)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 1531, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/result.py", line 2125, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 216, in chunks
    post_load.invoke(context, path)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 1410, in invoke
    loader(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/strategies.py", line 1414, in _load_for_path
    state.get_impl(key).set_committed_value(state, dict_, value)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 1975, in set_committed_value
    collection.append_multiple_without_event(value)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/collections.py", line 567, in append_multiple_without_event
    for item in items:
TypeError: 'LoaderCallableStatus' object is not iterable
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include pk cols in refresh() operations unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4311
