### ISSUE TITLE
figure out some way to gracefully handle fks that are placed on "invisible" columns

### ISSUE THREAD

**Issue by josefondrej** [sqlalchemy/sqlalchemy#9059]
### Describe the bug

When trying to reflect metadata for table that contains column that is both invisible and foreign key the reflection fails creating the ForeignKeyConstraint because it can't find the invisible column. 

### To Reproduce

```python
engine = create_engine('oracle://...')

sql = 'create table table_b (id number(3) primary key)'
engine.execute(sql)

sql = 'create table table_a (id number(3) primary key, a_col1 number(3))'
engine.execute(sql)

sql = 'alter table table_a modify (a_col1 invisible)'
engine.execute(sql)

sql = 'alter table table_a add constraint FK$table_a$a_col1 foreign key(a_col1) references table_b'
engine.execute(sql)

metadata = MetaData()
metadata = metadata.reflect(bind=engine)
```

### Error

```
Traceback (most recent call last):
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3887, in _set_parent
    ColumnCollectionConstraint._set_parent(self, table)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3476, in _set_parent
    ColumnCollectionMixin._set_parent(self, table)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3433, in _set_parent
    for col in self._col_expressions(table):
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3427, in _col_expressions
    return [
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3428, in <listcomp>
    table.c[col] if isinstance(col, util.string_types) else col
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\base.py", line 1214, in __getitem__
    return self._index[key]
KeyError: 'a_col1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Josef.ondrej\projects\ts-ml-oracle-to-postgres\ts_ml_oracle_to_postgres\example.py", line 27, in <module>
    metadata = metadata.reflect(bind=engine)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 4901, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\util\deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 689, in _init
    self._autoload(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\engine\reflection.py", line 795, in reflect_table
    self._reflect_fk(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\engine\reflection.py", line 1007, in _reflect_fk
    table.append_constraint(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 925, in append_constraint
    constraint._set_parent_with_dispatch(self)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\base.py", line 1047, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\sql\schema.py", line 3889, in _set_parent
    util.raise_(
  File "C:\Users\Josef.ondrej\Anaconda3\envs\ts-ml-oracle-to-postgres\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Can't create ForeignKeyConstraint on table 'table_a': no column named 'a_col1' is present.

Process finished with exit code 1
``` 

### Versions

- OS: Windows
- Python: 3.8
- SQLAlchemy: 1.4.45
- Database: Oracle
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): oracledb

**Comment by josefondrej** [comment]
Thanks for the suggestion @CaselIT. `resolve_fks=False` does not resolve the problem for me, but creating the table in the metadata before calling reflect works. 
One might however argue, that since the hidden columns are not reflected by design, perhaps constraints referencing those should also be ignored.

**Comment by zzzeek** [comment]
from https://oracle-base.com/articles/12c/invisible-columns-12cr1

> Invisible columns can be useful during application migrations. Making new columns invisible means they won't be seen by any existing applications, but can still be referenced by any new applications, making the online migration of applications much simpler.

clearly not the case!   It would be nice if the Oracle engineers tried to get their database to not use 1.2 gigawatts of power rather than adding new "conveniences" like this...

anyway.    resolve_fks was added exactly for this use case, looks like in #4517 it was added for permission reasons.    Certainly this qualifies as a database-specific reason to not resolve the FK.

that likely makes this a bug that can be backported to 1.4 so far, lets start with that.

**Comment by zzzeek** [comment]
well this is why resolve_fks doesn't help this case at the moment:

```
Note that if a related table is already present
            in the :class:`_schema.MetaData` collection, or becomes present later,
            a
            :class:`_schema.ForeignKey` object associated with this
            :class:`_schema.Table` will
            resolve to that table normally.
```

so this would be a behavioral change

**Comment by zzzeek** [comment]
this is the local column, not the remote table.    so this looks less and less like resolve_fks, theres no "resolution" here.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**warn and skip for FKs that refer to invisible cols for Oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4345
