### ISSUE TITLE
2.0: Mapping generics with typing.Annotated does not work if "from __future__ import annotations" is included

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#9099]
### Describe the bug

When `from __future__ import annotation` is included, then it's not possible to map generic collections to SQL types.
Mapping process throws the exception. If we change `list[X]` to `list`, then it works, but won't be fully correct from typing point of view.
My use case is I'm trying to map `list[str]` or `Sequence[str]` or `Sequence[SomeEnum]` to `JSONB` field in PostgreSQL, resulting in JSON array stored in this field.

### To Reproduce

```python
from __future__ import annotations
from typing import Annotated
from sqlalchemy.orm import DeclarativeBase, registry, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import JSONB
from uuid import UUID

TestType = Annotated[list[str], 0]

class Base(DeclarativeBase):
    registry = registry(
        type_annotation_map={
            TestType: JSONB()
        }
    )

class Test(Base):
    __tablename__ = 'test'

    id: Mapped[UUID] = mapped_column(primary_key=True)
    data: Mapped[TestType] = mapped_column()
```

### Error
```
Traceback (most recent call last):
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 981, in on_stacktrace_request
    self.api.request_stack(py_db, request.seq, thread_id, fmt=fmt, start_frame=start_frame, levels=levels)
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 207, in request_stack
    if internal_get_thread_stack.can_be_executed_by(get_current_thread_id(threading.current_thread())):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 655, in can_be_executed_by
    self._cmd = py_db.cmd_factory.make_get_thread_stack_message(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py", line 278, in make_get_thread_stack_message
    colno, endcolno = line_col_info.map_columns_to_line(line_text)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame_utils.py", line 101, in map_columns_to_line
    colno = _utf8_byte_offset_to_character_offset(original_line, self.colno)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame_utils.py", line 143, in _utf8_byte_offset_to_character_offset
    if byte_offset > offset:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "***/.venv/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "***/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "***/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "***/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "***/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "***/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "***/main.py", line 3, in <module>
    from api import create_api
  File "***/api/__init__.py", line 13, in <module>
    from api.routers import GetCurrentToken
  File "***/api/routers/__init__.py", line 22, in <module>
    from models import (
  File "***/models.py", line 61, in <module>
    class Test(Base):
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 764, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 234, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 315, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 557, in __init__
    self._extract_mappable_attributes()
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1376, in _extract_mappable_attributes
    value.declarative_scan(
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 681, in declarative_scan
    self._init_column_for_annotation(
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 717, in _init_column_for_annotation
    argument = de_stringify_annotation(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 150, in de_stringify_annotation
    elements = tuple(
               ^^^^^^
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 151, in <genexpr>
    de_stringify_annotation(
  File "***/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 161, in de_stringify_annotation
    return annotation.copy_with(elements)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'list' has no attribute 'copy_with'
```
### Versions

- OS: MacOS
- Python: 3.11.1
- SQLAlchemy: 2.0.0rc3.dev0
- Database: Postgres 14.0
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg

**Comment by zzzeek** [comment]
use `typing.List` for now in this case.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont assume copy_with() on builtins list, dict, etc.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4364

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by AlexanderPodorov** [comment]
You're welcome, thank you! I will keep `typing.List` for now.
Can we also support `collections.abc.Sequence` and `collection.abc.MutableSequence`?
First would valuable if one wants to prevent appending new items to the field. Could also play nice with `relationship`s with `viewonly=True`.

**Comment by zzzeek** [comment]
it's the same issue so this fixes them.  I'll add to the test cases

**Comment by AlexanderPodorov** [comment]
Yes, at the moment we can't do:
`some_relationship: Mapped[Sequence[SomeModel]] = relationship(...)`
`some_relationship: Mapped[MutableSequence[SomeModel]] = relationship(...)`
Just `list[SomeModel]` works, but this is not related to `from __future__ import annotations`.
Trying to do above things result in:
```
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers
```
`Sequence` would be great for read-only relationships
`MutableSequence` would be great for relationships where we can `append`.
As far as I understand, actual type to what SQLAlchemy maps those relationships is not `list`, but some internal type that supports `Sequence` or `MutableSequence` interfaces. Thanks!

**Comment by zzzeek** [comment]
> Yes, at the moment we can't do: `some_relationship: Mapped[Sequence[SomeModel]] = relationship(...)` `some_relationship: Mapped[MutableSequence[SomeModel]] = relationship(...)` Just `list[SomeModel]` works, but this is not related to `from __future__ import annotations`. Trying to do above things result in:

you can do these without issue, you just need to tell it what kind of collection to *instantiate*, since it doesn't know that:

```py
from __future__ import annotations

from collections.abc import Sequence

from sqlalchemy import ForeignKey
from sqlalchemy import select
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship


class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]
    bs: Mapped[Sequence[B]] = relationship("B", collection_class=list)


class B(Base):
    __tablename__ = "b"
    id: Mapped[int] = mapped_column(primary_key=True)
    a_id: Mapped[int] = mapped_column(ForeignKey("a.id"))
    data: Mapped[str]


print(select(A).join(A.bs))
```

needs a better error message that's all

**Comment by AlexanderPodorov** [comment]
Oh, yes, it works, sorry for bringing this up. Yes, better error message would be great.
It would be nicer if we could use `list` by default here, if not, current approach is good as well.

**Comment by zzzeek** [comment]
that's #9100

**Comment by zzzeek** [comment]
the thing is you know this is a list so you can use list[] directly.   If you're trying to imply non-mutability, then having to express the type and the instantiation seems fairly reasonable.   we'd have to make a type map for relationships to automate this, that can be later on.

**Comment by AlexanderPodorov** [comment]
Yes, I totally agree. Automation here would be nice, but generally not required. Later on sounds great, thank you!

**Comment by AlexanderPodorov** [comment]
@zzzeek , I have pulled down the recent changes, and see the same error:
```
AttributeError: type object 'Sequence' has no attribute 'copy_with'
```

**Comment by zzzeek** [comment]
Here's your original test case running against main in a console, from clean slate

https://gist.github.com/zzzeek/049466dc506170f881c112235cbdcc4b

works with "collections.abc.Sequence" also 

```py
from collections.abc import Sequence

TestType = Annotated[Sequence[str], 0]

```
