### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_extra_criteria'

### ISSUE THREAD

**Issue by jdieter** [sqlalchemy/sqlalchemy#9118]
### Describe the bug

In `sqlalchemy.orm.strategies.LazyLoader.create_row_processor`, there is a traceback if `loadopt` is None and `self.is_class_level` is False.  This can happen if a relationship is manually initialized with `do_init` (which I realize may not be supported, but the traceback can be easily fixed by making the checks in `create_row_processor` consistent).  

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()

class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)

rel_a = relationship(A)

class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(Integer, ForeignKey('a.id'), nullable=False)
    a = rel_a

rel_a.do_init()

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

a = A(id=1)
b = B(id=2, a_id=1)

s = Session(e)
s.add(a)
s.add(b)
s.commit()

assert s.query(B).filter(B.id == 2).one().id == 2
```

### Error

```
2023-01-19 08:25:44,415 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-19 08:25:44,415 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("a")
2023-01-19 08:25:44,415 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("a")
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("b")
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("b")
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine 
CREATE TABLE a (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2023-01-19 08:25:44,416 INFO sqlalchemy.engine.Engine 
CREATE TABLE b (
	id INTEGER NOT NULL, 
	a_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(a_id) REFERENCES a (id)
)


2023-01-19 08:25:44,417 INFO sqlalchemy.engine.Engine [no key 0.00005s] ()
2023-01-19 08:25:44,417 INFO sqlalchemy.engine.Engine COMMIT
2023-01-19 08:25:44,417 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-19 08:25:44,418 INFO sqlalchemy.engine.Engine INSERT INTO a (id) VALUES (?)
2023-01-19 08:25:44,418 INFO sqlalchemy.engine.Engine [generated in 0.00008s] (1,)
2023-01-19 08:25:44,418 INFO sqlalchemy.engine.Engine INSERT INTO b (id, a_id) VALUES (?, ?)
2023-01-19 08:25:44,418 INFO sqlalchemy.engine.Engine [generated in 0.00008s] (2, 1)
2023-01-19 08:25:44,419 INFO sqlalchemy.engine.Engine COMMIT
2023-01-19 08:25:44,419 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-19 08:25:44,420 INFO sqlalchemy.engine.Engine SELECT b.id AS b_id, b.a_id AS b_a_id 
FROM b 
WHERE b.id = ?
2023-01-19 08:25:44,420 INFO sqlalchemy.engine.Engine [generated in 0.00008s] (2,)
Traceback (most recent call last):
  File "/tmp/test.py", line 36, in <module>
    assert s.query(B).filter(B.id == 2).one().id == 2
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
           ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = compile_state_cls.orm_setup_cursor_result(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/context.py", line 349, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 88, in instances
    with util.safe_reraise():
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 69, in instances
    *[
     ^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 70, in <listcomp>
    query_entity.row_processor(context, cursor)
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/context.py", line 2631, in row_processor
    _instance = loading._instance_processor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 796, in _instance_processor
    prop.create_row_processor(
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/interfaces.py", line 658, in create_row_processor
    strat.create_row_processor(
  File "/usr/lib64/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 1099, in create_row_processor
    if loadopt._extra_criteria
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_extra_criteria'
``` 

### Versions

- OS: Fedora 37 / Debian
- Python: 3.11 / 3.10 official container
- SQLAlchemy: HEAD / 1.4.46
- Database: Postgresql / SQlite
- DBAPI: psycopg2 / sqlite

**Comment by CaselIT** [comment]
Hi,

do_init is an internal method so it's expected that it will fail if it's called by the outside at the wrong time.
To configure the orm use [`configure_mappers()`](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.configure_mappers)

> but the traceback can be easily fixed by making the checks in create_row_processor consistent

the traceback yes, but logically it may still be wrong, since the fix you proposed may create the wrong thing, since if do_init was called at the right time the `_extra_criteria` may be populated.

overall I'm -1 on this, since it's not something that happen using the public api

let's wait for @zzzeek opinion though

**Comment by jdieter** [comment]
I'm perfectly fine with this issue being rejected, and was on the fence about even submitting the fix, but the reason I ended up reported it and submitted a PR is that the code in `create_row_processor` is actually inconsistent which I figured made it worth a fix.

In the outer `if` statement, we check for `loadopt` existing before checking `loadopt._existing_criteria`, while, when passing it on to `LoadLazyAttribute()`, we only check `loadopt._existing_criteria`, and that's where the traceback happens.

**Comment by zzzeek** [comment]
so the "bug" here is that do_init() is not an underscored method, but as it's part of a common interface `MapperProperty` that's intended to be subclassed by in theory anyone, that's why it's not underscored, though by today's practices I would likely have made it underscored.    Python doesn't have a convention for "protected" methods.

so the case here is not valid.   Separately, the PR would not be the fix for this in any case :)   so unfortunately I have to close that for different reasons
