### ISSUE TITLE
problem with new version (2.0.0) on .execute() 

### ISSUE THREAD

**Issue by agn-7** [sqlalchemy/sqlalchemy#9155]
### Describe the bug

After updating the sqlalchemy I got encountered the following error:

### To Reproduce

```python
with self.engine.connect() as conn:
    conn.execute('DROP TABLE IF EXISTS alembic_version')
```

### Error

```
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute

    raise exc.ObjectNotExecutableError(statement) from err

sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'DROP TABLE IF EXISTS alembic_version'

/service/app/src/components/config.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  self.cfg = yaml.load(ymlfile)

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1410, in execute

    meth = statement._execute_on_connection

AttributeError: 'str' object has no attribute '_execute_on_connection'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/service/app/src/orangeryos.py", line 5, in <module>

    from rest.rest_service import app_service

  File "/service/app/src/rest/rest_service.py", line 10, in <module>

    from rest.routes import login

  File "/service/app/src/rest/routes/login.py", line 2, in <module>

    from functions.login import LoginFunctions

  File "/service/app/src/functions/login.py", line 7, in <module>

    from data.db_manager import db_manager

  File "/service/app/src/data/db_manager.py", line 1359, in <module>

    db_manager = DBManager()

  File "/service/app/src/data/db_manager.py", line 117, in __init__

    self.run_migrations()

  File "/service/app/src/data/db_manager.py", line 132, in run_migrations

    conn.execute('DROP TABLE IF EXISTS alembic_version')

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute

    raise exc.ObjectNotExecutableError(statement) from err

sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'DROP TABLE IF EXISTS alembic_version

``` 

### Versions

- OS: Ubuntu 22.04
- Python: 3.10
- SQLAlchemy: 2.0.0

### Additional context

And it can be solved by reverting to version 1.4.46

**Comment by CaselIT** [comment]
Hi,

That's working as expected. Passing a string to execute is deprecated since 1.4. either use text, or exec_driver_sql. In case of ddl statement you can also use DDL.

I suggest you follow the 1.4 and 2.0 migration guides and also turn on warning (that exertion has warned for the entire 1.4 serie)

**Comment by zzzeek** [comment]
they're still in the midst of it   https://github.com/pandas-dev/pandas/issues/40686

which is strange, the engine.execute() change is the most basic change

**Comment by CaselIT** [comment]
Wrong issue mike?

**Comment by zzzeek** [comment]
yeah
