### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'execute'

### ISSUE THREAD

**Issue by nectario** [sqlalchemy/sqlalchemy#9161]
### Describe the bug

I am getting:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Development/Projects/DeepTradingAI/deeptrading/utils/db.py", line 3050, in <module>
    code = get_day_code(ticker="DJI", day_code_column="TwoDayCode")
  File "C:/Development/Projects/DeepTradingAI/deeptrading/utils/db.py", line 3025, in get_day_code
    record = db_connection.execute(statement)
AttributeError: 'Engine' object has no attribute 'execute'

Process finished with exit code 1

What happened? I can't even run Pandas.to_sql! This happened with latest release!

### To Reproduce

```python
In MySQL:

    sql = f"""Select <column>
                From <table>
   
        """

    statement = text(sql)
    print(sql)
    record = db_connection.execute(statement)
```

### Error

```
C:\Development\Python\Python3104\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2022.1.3/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 50625 --file C:/Development/Projects/DeepTradingAI/deeptrading/utils/db.py 
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Development/Projects/DeepTradingAI/deeptrading/utils/db.py", line 3050, in <module>
    code = get_day_code(ticker="DJI", day_code_column="TwoDayCode")
  File "C:/Development/Projects/DeepTradingAI/deeptrading/utils/db.py", line 3025, in get_day_code
    record = db_connection.execute(statement)
AttributeError: 'Engine' object has no attribute 'execute'

Process finished with exit code 1

``` 

### Versions

- OS: Window 11
- Python: 3.10, 3.9
- SQLAlchemy: 2.0
- Database: MySQL
- DBAPI mysql

### Additional context

This happens also when I use sqlalchemy with Pandas.

**Comment by CaselIT** [comment]
Hi

That's working as expected. Engine no longer offers execute functionalities. This feature has been deprecated for the entire 1.4 release series and has raised warning. 
You will need to usa a connection directly, likely doing
```py
with engine.conect() as conn:
  ... # use conn
```

I suggest turning on warnings and reading the 1.4 and 2.0 migration notes

**Comment by nectario** [comment]
Ok, sure. Will do.

Thank you.

**Comment by zzzeek** [comment]
I believe pandas has upgraded their internals to accommodate for 2.0's API and upgrading to the latest for them would hopefully be working, but I have not confirmed.

Also, we added an unconditional 2.0 migration warning very late in the 1.4 series which you would see in the past month or so on 1.4.46.    Prior to that there was no 2.0 warning emitted without setting `SQLALCHEMY_WARN_20`.

**Comment by nectario** [comment]
It does not seem it is working.
I do: 
```
db_connection = create_engine(db_url, pool_recycle=3600, pool_size=100).connect()
table_df = pd.read_sql(query, con=db_connection)
```

And I get:
```
Traceback (most recent call last):
  File "C:\Development\Python\Python3104\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 354, in generate_validation_model_data
    result = generate_model_data(ticker, data_url=data_url, validation_start_date=validation_start_date, validation_end_date=validation_end_date, validation_num_days=validation_num_days,
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 216, in generate_model_data
    ticker_data_df, intraday_data_df, vix_data_df = load_train_data(ticker=ticker, intraday_interval=intraday_interval, run_date=run_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 491, in load_train_data
    ticker_data_df, intraday_data_df = load_ticker_data_df(ticker, intraday=True, intraday_interval=intraday_interval, to_date=run_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\utils\common.py", line 589, in load_ticker_data_df
    ticker_daily = get_ticker_daily_return_data(ticker=ticker, from_date=from_date, to_date=to_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\utils\db.py", line 1310, in get_ticker_daily_return_data
    table_df = pd.read_sql(query+ " " + condition, con=db_connection)
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 590, in read_sql
    return pandas_sql.read_query(
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Development\Python\Python3104\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "select * from StockReturnData where Ticker = 'AMC'  and Date <='2023-01-27'"
Traceback (most recent call last):
  File "C:\Development\Python\Python3104\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 354, in generate_validation_model_data
    result = generate_model_data(ticker, data_url=data_url, validation_start_date=validation_start_date, validation_end_date=validation_end_date, validation_num_days=validation_num_days,
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 216, in generate_model_data
    ticker_data_df, intraday_data_df, vix_data_df = load_train_data(ticker=ticker, intraday_interval=intraday_interval, run_date=run_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\DataGeneration.py", line 491, in load_train_data
    ticker_data_df, intraday_data_df = load_ticker_data_df(ticker, intraday=True, intraday_interval=intraday_interval, to_date=run_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\utils\common.py", line 589, in load_ticker_data_df
    ticker_daily = get_ticker_daily_return_data(ticker=ticker, from_date=from_date, to_date=to_date, ticker_type=ticker_type)
  File "C:\Development\Projects\DeepTradingAI\deeptrading\utils\db.py", line 1310, in get_ticker_daily_return_data
    table_df = pd.read_sql(query+ " " + condition, con=db_connection)
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 590, in read_sql
    return pandas_sql.read_query(
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Development\Python\Python3104\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Development\Python\Python3104\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "select * from.....'"


Process finished with exit code 1
```

**Comment by zzzeek** [comment]
yeah they should be using text() or exec_driver_sql(), I'd go over to them and see where they're at

**Comment by zzzeek** [comment]
pandas ongoing work w this is https://github.com/pandas-dev/pandas/issues/40686
