### ISSUE TITLE
unusual regression w/ declarative inherits using composite foreign key

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9164]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9163

pretty weird we dont have a test for this

```py
from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy import ForeignKey, String, ForeignKeyConstraint
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


class Ecommerce_Order_Item(Base):
    __tablename__ = "ecommerce_order_items"

    order_id: Mapped[str] = mapped_column(String, primary_key=True)
    _sku: Mapped[str] = mapped_column(String, primary_key=True)

    __mapper_args__ = {
        "polymorphic_identity": "ecommerce_order_item",
        "polymorphic_on": "type",
    }

    type: Mapped[str] = mapped_column(String)

    def __init__(self, order_id, sku):
        self.order_id = order_id
        self._sku = sku


class Magento_Order_Item(Ecommerce_Order_Item):
    __tablename__ = "magento_order_items"

    _increment_id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        autoincrement=False,
    )
    _sku: Mapped[str] = mapped_column(
        String,
        # primary_key=True,
        autoincrement=False,
    )

    __table_args__ = (
        ForeignKeyConstraint(
            ["_increment_id", "_sku"],
            ["ecommerce_order_items.order_id", "ecommerce_order_items._sku"],
        ),
    )

    __mapper_args__ = {"polymorphic_identity": "magento_order_item"}

    def __init__(self, iid, sku):
        self._increment_id = iid
        self._sku = sku
        super().__init__(iid, sku)


e = create_engine("sqlite://")
Base.metadata.create_all(e)
Base.registry.configure()

session = Session(e)
session.add(Magento_Order_Item("lol", "funi"))
session.commit()

```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 69, in <module>
    session.commit()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 4140, in flush
    self._flush(objects)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 4276, in _flush
    with util.safe_reraise():
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 4237, in _flush
    flush_context.execute()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/persistence.py", line 1042, in _emit_insert_statements
    _postfetch(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/persistence.py", line 1664, in _postfetch
    for m, equated_pairs in mapper._table_to_equated[table]:
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/mapper.py", line 3927, in _table_to_equated
    reduce(
TypeError: descriptor 'union' for 'set' objects doesn't apply to a 'frozenset' object

```

**Comment by zzzeek** [comment]
kind of a silly problem

```diff
diff --git a/lib/sqlalchemy/orm/mapper.py b/lib/sqlalchemy/orm/mapper.py
index dd3aef8d69..a3b209e4a6 100644
--- a/lib/sqlalchemy/orm/mapper.py
+++ b/lib/sqlalchemy/orm/mapper.py
@@ -3920,12 +3920,16 @@ class Mapper(
             ],
         ] = util.defaultdict(list)
 
+        def set_union(x, y):
+            return x.union(y)
+
         for table in self._sorted_tables:
             cols = set(table.c)
+
             for m in self.iterate_to_root():
                 if m._inherits_equated_pairs and cols.intersection(
                     reduce(
-                        set.union,  # type: ignore
+                        set_union,
                         [l.proxy_set for l, r in m._inherits_equated_pairs],
                     )
                 ):

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix regression based on mis-match of set/frozenset** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4397
