### ISSUE TITLE
declarative regression: DeclarativeBase does not have __init__ where declarative_base does

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9171]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9169

The code below will error out on 2.0 so it should be safe to restore the 1.4 behavior to DeclarativeBase

```py

from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

Base = declarative_base()

class Foo(Base):
    __tablename__ = "foo"
    id: Mapped[int] = mapped_column(primary_key=True)

    def __init__(self, **kw):
        super().__init__(**kw)

class Base(DeclarativeBase):
    pass

    # workaround
    # def __init__(self, **kw):
    #    self.registry.constructor(self, **kw)

class Bar(Base):
    __tablename__ = "foo"
    id: Mapped[int] = mapped_column(primary_key=True)

    def __init__(self, **kw):
        super().__init__(**kw)

Foo(id=5)

Bar(id=5)
```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 29, in <module>
    Bar(id=5)
  File "<string>", line 4, in __init__
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/state.py", line 575, in _initialize_instance
    with util.safe_reraise():
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/state.py", line 573, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/classic/dev/sqlalchemy/test3.py", line 25, in __init__
    super().__init__(**kw)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add __init__ to DeclarativeBase directly** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4400
