### ISSUE TITLE
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database` in SQLAlchemy 2.0.0

### ISSUE THREAD

**Issue by harupy** [sqlalchemy/sqlalchemy#9186]
### Describe the bug

We're investigating a test failure caused by `sqlalchemy==2.0.0` in our repository (https://github.com/mlflow/mlflow). The failed test passes with `sqlalchemy==1.4.46`, but doesn't with `sqlalchemy==2.0.0`.

### To Reproduce

Save the following code in `a.py`:

```python
# This code replicates what's happening in the failed test:

# a.py

import os
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

Base = declarative_base()


class Student(Base):
    __tablename__ = "students"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Integer)


engine = create_engine("sqlite:///test.db", echo=True)
Base.metadata.create_all(engine)

sess = Session(engine)

with sess:
    sess.add(Student(name="1", age=1))
    sess.add(Student(name="2", age=2))
    sess.commit()

# Reset the database
os.unlink("test.db")
engine = create_engine("sqlite:///test.db")
Base.metadata.create_all(engine)

with sess:
    sess.add(Student(name="3", age=3))
    sess.add(Student(name="4", age=4))
    sess.commit()
```

Then, run it with `sqlalchemy==1.4.46` and `sqlalchemy==2.0.0` using Docker:

```
# works
docker run --rm -v $(pwd)/a.py:/a.py python:3.8 bash -c "pip install 'sqlalchemy<2.0' && python a.py"
```

```
# throws
docker run --rm -v $(pwd)/a.py:/a.py python:3.8 bash -c "pip install 'sqlalchemy' && python a.py"
```

### Error

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "a.py", line 34, in <module>
    sess.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4140, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4277, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4237, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1188, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO students (name, age) VALUES (?, ?)]
[parameters: ('3', 3)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
``` 

### Versions

- OS: Debian
- Python: 3.8
- SQLAlchemy: 2.0
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by harupy** [comment]
We found the following change can fix the issue:

```diff
diff --git a/a.py b/b.py
index 7ccaeb544..6b1d3d045 100644
--- a/a.py
+++ b/b.py
@@ -26,6 +26,7 @@ with sess:
 os.unlink("test.db")
 engine = create_engine("sqlite:///test.db")
 Base.metadata.create_all(engine)
+sess = Session(engine)
 
 with sess:
     sess.add(Student(name="3", age=3))
```

**Comment by CaselIT** [comment]
Hi,

This is expected, since sqlalchemy v2 uses QueuePool in sqlite, so it will keep the connection open.
On windows you would get an error on the `unlink` call, since the file is still open at that point. On linux you can remove the file, but I guess that becomes read-only.

To solve you can call `engine.dispose()` to close all connections or using a `NullPool` in `create_engine`

**Comment by CaselIT** [comment]
Was also discussed in #9167
