### ISSUE TITLE
"Invalid string or buffer length" error when inserting more than 2000 characters

### ISSUE THREAD

**Issue by SimeonStoykovQC** [sqlalchemy/sqlalchemy#9193]
### Describe the bug

"Invalid string or buffer length" error when inserting more than 2000 characters in a `VARCHAR` column in SQL Server (ran in a container, with the FreeTDS driver). The error is only observed in SQLAlchemy 2.0; it works fine in version 1.4. It occurs both in ORM and Core style.

### To Reproduce

```python
from sqlalchemy import Engine
from sqlalchemy.orm import declarative_base, Session

import sqlalchemy as sa

Base = declarative_base()


class MyModel(Base):
    __tablename__ = "my_dummy_test_table"

    the_pk = sa.Column(sa.Integer, primary_key=True)
    a_big_text = sa.Column(sa.String(4000))


engine_prod_database: Engine = ...
Base.metadata.create_all(bind=engine_prod_database)

with Session(engine_prod_database) as transaction, transaction.begin():
    transaction.add(MyModel(
        the_pk=0,
        a_big_text="a" * 2000,
    ))  # Runs through

with Session(engine_prod_database) as transaction, transaction.begin():
    transaction.add(MyModel(
        the_pk=1,
        a_big_text="a" * 2001,
    ))  # Fails
```

### Error
```
/Users/user/mambaforge/envs/repo/bin/python "/Users/user/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_5.py"
Traceback (most recent call last):
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('HY090', '[HY090] [FreeTDS][SQL Server]Invalid string or buffer length (0) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_5.py", line 27, in <module>
    with Session(engine_prod_database) as transaction, transaction.begin():
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/util.py", line 146, in __exit__
    with util.safe_reraise():
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/util.py", line 144, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4140, in flush
    self._flush(objects)
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4276, in _flush
    with util.safe_reraise():
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4237, in _flush
    flush_context.execute()
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1024, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/user/mambaforge/envs/repo/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY090', '[HY090] [FreeTDS][SQL Server]Invalid string or buffer length (0) (SQLExecDirectW)')
[SQL: INSERT INTO my_dummy_test_table (the_pk, a_big_text) VALUES (?, ?)]
[parameters: (1, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ... (1703 characters truncated) ... aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')]
(Background on this error at: https://sqlalche.me/e/20/dbapi)

Process finished with exit code 1

```
### Versions

- OS: MacOS 12.0.1
- Python: 3.11.0
- SQLAlchemy: 2.0
- Database: SQL Server (container image: `docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=..." -e "MSSQL_USER=sa" -p 1433:1433 --name=mssql --rm -it mcr.microsoft.com/azure-sql-edge`) + `FreeTDS` driver version 1.3.16
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): `pyodbc`

**Comment by zzzeek** [comment]
there was a lot of work done on this 2000 characters issue so im surprised it's being seen here, but this might be part of tds, which we dont support as much as pyodbc right now

**Comment by zzzeek** [comment]
no error in pyodbc.  we made an adjustment for this specific use case in pyodbc in f4214975a7d , which itself was adjusting #8177 that was also a pyodbc-only change.   

however it also passes for me in freetds (non-odbc):

```
2023-01-30 11:58:12,603 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-30 11:58:12,604 INFO sqlalchemy.engine.Engine SET IDENTITY_INSERT my_dummy_test_table ON
2023-01-30 11:58:12,604 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-30 11:58:12,607 INFO sqlalchemy.engine.Engine INSERT INTO my_dummy_test_table (the_pk, a_big_text) VALUES (%(the_pk)s, %(a_big_text)s)
2023-01-30 11:58:12,607 INFO sqlalchemy.engine.Engine [generated in 0.00271s] {'the_pk': 0, 'a_big_text': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ... (1702 characters truncated) ... aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
2023-01-30 11:58:12,610 INFO sqlalchemy.engine.Engine SET IDENTITY_INSERT my_dummy_test_table OFF
2023-01-30 11:58:12,610 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-30 11:58:12,612 INFO sqlalchemy.engine.Engine COMMIT
2023-01-30 11:58:12,625 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-30 11:58:12,625 INFO sqlalchemy.engine.Engine SET IDENTITY_INSERT my_dummy_test_table ON
2023-01-30 11:58:12,625 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-30 11:58:12,626 INFO sqlalchemy.engine.Engine INSERT INTO my_dummy_test_table (the_pk, a_big_text) VALUES (%(the_pk)s, %(a_big_text)s)
2023-01-30 11:58:12,626 INFO sqlalchemy.engine.Engine [cached since 0.02221s ago] {'the_pk': 1, 'a_big_text': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ... (1703 characters truncated) ... aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
2023-01-30 11:58:12,628 INFO sqlalchemy.engine.Engine SET IDENTITY_INSERT my_dummy_test_table OFF
2023-01-30 11:58:12,628 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-30 11:58:12,630 INFO sqlalchemy.engine.Engine COMMIT

```

are you using freetds with ODBC?    our ODBC settings are optimized for the MSFT drivers, so if you are using ODBC I would strongly recommend using the MSFT drivers.    this is mentioned at https://docs.sqlalchemy.org/en/20/dialects/mssql.html#driver-unicode-support

**Comment by zzzeek** [comment]
can't reproduce here.  feel free to open a [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions)

**Comment by SimeonStoykovQC** [comment]
> but this might be part of tds, which we dont support as much as pyodbc right now

> are you using freetds with ODBC? our ODBC settings are optimized for the MSFT drivers

I can confirm it works fine with MSFT ODBC drivers, but it fails with FreeTDS (+ ODBC, I believe).


> can't reproduce here

I tried it on Ubuntu 22.04.1 LTS, and I observed the behavior described above.

**Comment by zzzeek** [comment]
we dont have the resources to support freetds+odbc at this time.  we support pyodbc + msft drivers right now.    SQL Server is a commercial database and their ODBC driver is available on all platforms.
