### ISSUE TITLE
change for 9058 seems to not work with mysql 8

### ISSUE THREAD

**Issue by DanCardin** [sqlalchemy/sqlalchemy#9251]
### Describe the bug

All releases after 2.0.0rc2 appear to have the behavior described, while the releases i tested before it (2.0.0rc1, all the betas, 1.4.X, 1.3X) work fine.

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'fooschema'")
[SQL: DESCRIBE `fooschema`.`foo`]
```
You'll see the reproduction code below but essentially `event.listen(metadata, "before_create", CreateSchema("fooschema"))` appears to fail to execute the `before_create` event.

Replacing that line with `conn.execute(CreateSchema("fooschema"))` works just fine.

### To Reproduce

```python
docker run -d -e MYSQL_DATABASE=database -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 -it mysql:8
```

```python
from sqlalchemy import engine, MetaData, event, types, Column
from sqlalchemy.orm import declarative_base
from sqlalchemy.schema import CreateSchema

metadata = MetaData()
Base = declarative_base(metadata=metadata)


class Foo(Base):
    __tablename__ = "foo"
    __table_args__ = {"schema": "fooschema"}

    id = Column(types.Integer(), primary_key=True)


engine = engine.create_engine("mysql+pymysql://root:password@localhost:3306/database")
with engine.connect() as conn:
    event.listen(metadata, "before_create", CreateSchema("fooschema"))
    metadata.create_all(conn)
```

### Error

```
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 746, in do_execute
    cursor.execute(statement, parameters)
  File "/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/.venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/.venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'fooschema'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/meow.py", line 27, in <module>
    metadata.create_all(conn)
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5558, in create_all
    bind._run_ddl_visitor(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2427, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 677, in traverse_single
    return meth(obj, **kw)
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 905, in visit_metadata
    [t for t in tables if self._can_create_table(t)]
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 905, in <listcomp>
    [t for t in tables if self._can_create_table(t)]
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 870, in _can_create_table
    return not self.checkfirst or not self.dialect.has_table(
  File "<string>", line 2, in has_table
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 88, in cache
    return fn(self, con, *args, **kw)
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 2687, in has_table
    with connection.exec_driver_sql(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1772, in exec_driver_sql
    ret = self._execute_context(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 746, in do_execute
    cursor.execute(statement, parameters)
  File "/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/.venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/.venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'fooschema'")
[SQL: DESCRIBE `fooschema`.`foo`]
``` 

### Versions

- OS: macos monteray
- Python: 3.10
- SQLAlchemy: 2.0.0rc2+
- Database: mysql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql

**Comment by zzzeek** [comment]
hey there -

not working here (in that it succeeds).  Can you please set echo='debug' on your create_engine and provide the complete log.

We would suspect 7505cc5db44f2d3a84827519d3a7 as being related here since that's right where we changed something here right for 2.0.0rc2.  But we reverted it to exactly what we had in SQLAlchemy 1.3.

so we need to see here if your CreateSchema is not happening or if your DESCRIBE is not working.

the test can be run repeatedly as

```py
engine = engine.create_engine(
    "mysql+pymysql://scott:tiger@localhost/test", echo=True
)
with engine.begin() as conn:
    conn.exec_driver_sql("DROP SCHEMA IF EXISTS fooschema")

with engine.connect() as conn:
    event.listen(metadata, "before_create", CreateSchema("fooschema"))
    metadata.create_all(conn)

```

my output

```sql
$ python test3.py 
2023-02-06 13:47:55,096 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-02-06 13:47:55,096 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-06 13:47:55,097 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-02-06 13:47:55,097 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-06 13:47:55,098 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-02-06 13:47:55,098 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-06 13:47:55,098 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-02-06 13:47:55,098 INFO sqlalchemy.engine.Engine DROP SCHEMA IF EXISTS fooschema
2023-02-06 13:47:55,098 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-06 13:47:55,107 INFO sqlalchemy.engine.Engine COMMIT
2023-02-06 13:47:55,108 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-02-06 13:47:55,108 INFO sqlalchemy.engine.Engine DESCRIBE `fooschema`.`foo`
2023-02-06 13:47:55,108 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-06 13:47:55,110 INFO sqlalchemy.engine.Engine CREATE SCHEMA fooschema
2023-02-06 13:47:55,110 INFO sqlalchemy.engine.Engine [no key 0.00007s] {}
2023-02-06 13:47:55,110 INFO sqlalchemy.engine.Engine 
CREATE TABLE fooschema.foo (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY (id)
)


2023-02-06 13:47:55,110 INFO sqlalchemy.engine.Engine [no key 0.00005s] {}
2023-02-06 13:47:55,118 INFO sqlalchemy.engine.Engine ROLLBACK
```

**Comment by zzzeek** [comment]
ah, it happens on mysql 8.  success

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add error code 1049 for mysql has_table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4430

**Comment by zzzeek** [comment]
just got it in for 2.0.2 , which is very soon
