### ISSUE TITLE
module qualified names don't work with `from __future__ import annotations`

### ISSUE THREAD

**Issue by JohnVillalovos** [sqlalchemy/sqlalchemy#9335]
### Describe the bug

When using `from __future__ import annotations` and module qualified names it raises an exception. Sort of like issue #8853 which was already fixed. Using their same reproducer but adding `from __future__ import annotations`

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.10.9

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

import sqlalchemy.orm

class Base(sqlalchemy.orm.DeclarativeBase):
    pass


class XYZ(Base):
    __tablename__ = "xyz"

    id: sqlalchemy.orm.Mapped[int] = sqlalchemy.orm.mapped_column(primary_key=True)
```

### Error

```
$ python3 reproducer.py
Traceback (most recent call last):
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 195, in eval_expression
    annotation = eval(expression, base_globals, None)
  File "<string>", line 1, in <module>
NameError: name 'Mapped' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2270, in _extract_mapped_subtype
    annotated = de_stringify_annotation(
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 153, in de_stringify_annotation
    annotation = eval_expression(annotation, originating_module)
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 197, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'Mapped["int"]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tester/sources/github-mine/python-gitlab/reproducer.py", line 9, in <module>
    class XYZ(Base):
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 838, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1005, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1233, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "/home/tester/.local/lib/python3.10/site-packages/sqlalchemy/orm/util.py", line 2284, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not interpret annotation sqlalchemy.orm.Mapped[int].  Check that it uses names that are correctly imported at the module level. See chained stack trace for more hints.
```

**Comment by CaselIT** [comment]
Hi,

thanks for reporting.
I guess this should work since without the future import is working so it's a bug.

@zzzeek do you remember why we had not checked this case when fixing the other issue?

**Comment by zzzeek** [comment]
I cant imagine why this doesnt work since most certainly when we fixed the issue we added the test to test_typed_mapping.py.

**Comment by zzzeek** [comment]
#8853

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply a fixed locals w/ Mapped to all de-stringify** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4458
