### ISSUE TITLE
documentation for legacy dataclass mapping erroneously refers to mapped_column

### ISSUE THREAD

**Issue by PaleNeutron** [sqlalchemy/sqlalchemy#9361]
### Describe the bug

Can not declare dataclass table column using `mapped_column`.

The test code is copied from document added one necessary import.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

None

### Database Vendor and Major Version

None

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.orm import registry, relationship, mapped_column

mapper_registry = registry()


@mapper_registry.mapped
@dataclass
class User:
    __tablename__ = "user"

    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": mapped_column(Integer, primary_key=True)}
    )
    name: str = field(default=None, metadata={"sa": mapped_column(String(50))})
    fullname: str = field(default=None, metadata={"sa": mapped_column(String(50))})
    nickname: str = field(default=None, metadata={"sa": mapped_column(String(12))})
    addresses: List[Address] = field(
        default_factory=list, metadata={"sa": relationship("Address")}
    )


@mapper_registry.mapped
@dataclass
class Address:
    __tablename__ = "address"
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": mapped_column(Integer, primary_key=True)}
    )
    user_id: int = field(
        init=False, metadata={"sa": mapped_column(ForeignKey("user.id"))}
    )
    email_address: str = field(default=None, metadata={"sa": mapped_column(String(50))})
```

### Error

```
SAWarning: On class 'User', Column object None named directly multiple times, only one will be used: fullname, id, name, nickname. Consider using orm.synonym instead
  class User:
Traceback (most recent call last):
  File "/home/john/projects/urban_invest/test_irmmodel.py", line 14, in <module>
    class User:
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 1669, in mapped
    _as_declarative(self, cls, cls.__dict__)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 578, in __init__
    self._setup_table(table)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1663, in _setup_table
    table_cls(
  File "<string>", line 2, in __new__
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 428, in __new__
    return cls._new(*args, **kw)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 482, in _new
    with util.safe_reraise():
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 478, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 866, in __init__
    self._init_items(
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 225, in _init_items
    spwd(self, **kw)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1300, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/home/john/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 2146, in _set_parent
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.
```

**Comment by zzzeek** [comment]
hi, apparently the docs were inadvertently changed here.  Please use Column for this legacy use case.


```py
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.orm import registry, relationship

mapper_registry = registry()


@mapper_registry.mapped
@dataclass
class User:
    __tablename__ = "user"

    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
    name: str = field(default=None, metadata={"sa": Column(String(50))})
    fullname: str = field(
        default=None, metadata={"sa": Column(String(50))}
    )
    nickname: str = field(
        default=None, metadata={"sa": Column(String(12))}
    )
    addresses: List[Address] = field(
        default_factory=list, metadata={"sa": relationship("Address")}
    )


@mapper_registry.mapped
@dataclass
class Address:
    __tablename__ = "address"
    __sa_dataclass_metadata_key__ = "sa"
    id: int = field(
        init=False, metadata={"sa": Column(Integer, primary_key=True)}
    )
    user_id: int = field(
        init=False, metadata={"sa": Column(ForeignKey("user.id"))}
    )
    email_address: str = field(
        default=None, metadata={"sa": Column(String(50))}
    )

```
