### ISSUE TITLE
Regression: MutableDict.pop(..., None) throws an exception

### ISSUE THREAD

**Issue by nphilipp** [sqlalchemy/sqlalchemy#9380]
### Describe the bug

Using `MutableDict.pop(..., None)` worked with versions 1.4.x, but throws an exception if the key is missing with version 2.0.4. I tripped over this when attempting to upgrade a project using `asyncpg` but this also works with the sync API and the `sqlite` driver (see reproducer).

I’ll submit a PR which should fix this.

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

asyncpg, sqlite

### Database Vendor and Major Version

PostgreSQL 14.3, sqlite 3.40

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
#!/usr/bin/env python

# sqla20_mutabledict_regression.py

from sqlalchemy import JSON, Column, Integer, MetaData, create_engine, select
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import declarative_base, sessionmaker

engine = create_engine('sqlite://', echo=False)
metadata = MetaData()
Base = declarative_base(metadata=metadata)


class Test(Base):

    __tablename__ = "test"

    id = Column(Integer, primary_key=True)
    data = Column(MutableDict.as_mutable(JSON))


metadata.drop_all(bind=engine)
metadata.create_all(bind=engine)

Session = sessionmaker(bind=engine)
session = Session()
session.add(Test(data={"foo": "bar"}))
session.commit()

test = session.execute(select(Test)).scalars().first()
print(test.data.pop("foo", None))  # -> "bar"
print(test.data.pop("foo", None))  # should be `None` but errors
```

### Error

```
Traceback (most recent call last):
  File "/home/nils/src/fedora-infra/duffy/./sqla20_mutabledict_regression.py", line 30, in <module>
    print(test.data.pop("foo", None))  # should be `None` but errors
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nils/.virtualenvs/duffy/lib64/python3.11/site-packages/sqlalchemy/ext/mutable.py", line 827, in pop
    result = super().pop(__key)
             ^^^^^^^^^^^^^^^^^^
KeyError: 'foo'
```

**Comment by sqla-tester** [comment]
**Nils Philippsen** has proposed a fix for this issue in the **main** branch:

**restore old *args approach for MutableDict.pop()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4479
