### ISSUE TITLE
TypeError _MKeyfuncMapped.__init__() when calling type() on mapped dict-field in a dataclass

### ISSUE THREAD

**Issue by cschroeer** [sqlalchemy/sqlalchemy#9418]
### Describe the bug

Having a dataclass like 

``` 
@dataclass
class DataclassParent:
    id: UUID = field(default_factory=uuid7, init=False)
    name: str

    childs: dict[str, DataclassChild] = field(default_factory=dict, init=False)
``` 

and the corresponding child class as 

``` 
@dataclass
class DataclassChild:
    id: UUID = field(default_factory=uuid7, init=False)
    name: str
``` 

with a imperative mapping like: 
``` 
...
mapper_registry.map_imperatively(
      DataclassParent,
      dataclass_parent_table,
      properties={
          "childs": relationship(
              DataclassChild,
              collection_class=attribute_keyed_dict("name"),
          )
      },
...
``` 

leads to the following behavior:

Without mapping (only dataclasses), the following code works:
``` 
childs = {"child1": DataclassChild("child1"), "child2": DataclassChild("child2")}

parent = DataclassParent("parent1")
parent.childs = childs

type(parent.childs)(((k), (v)) for k, v in parent.childs.items())
``` 

However, with SqlAlchemy Mapping, the following code leads to an error: 
``` 
map_entities()
childs = {"child1": DataclassChild("child1"), "child2": DataclassChild("child2")}

parent = DataclassParent("parent1")
parent.childs = childs

type(parent.childs)(((k), (v)) for k, v in parent.childs.items())
``` 

The following code works: 
``` 
map_entities()
childs = {"child1": DataclassChild("child1"), "child2": DataclassChild("child2")}

parent = DataclassParent("parent1")
parent.childs = childs

dict(((k), (v)) for k, v in parent.childs.items())
``` 

No database connection needed to reproduce this error. 

The code of 
```
type(parent.childs)(((k), (v)) for k, v in parent.childs.items())
```
is used e. b. in asdict function of dataclasses (see. 
https://github.com/python/cpython/blob/0a7936a38f0bab1619ee9fe257880a51c9d839d5/Lib/dataclasses.py#L1388 

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/collection_api.html

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

n.a.

### Database Vendor and Major Version

n.a.

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
see. https://github.com/cschroeer/dataclasses-asdict-core
```

### Error

```
TypeError: _mapped_collection_cls.<locals>._MKeyfuncMapped.__init__() takes 1 positional argument but 2 were given
```

**Comment by zzzeek** [comment]
hi there -

there are two elements to this bug report that make our job much harder:

1. test case is a github repo with lots of extraneous code
2. no actual stack trace given
3. unnecessary third-party dependency "uuid6"


What we can work with **much** more quickly is:

1. single-"file" MCVE inline in the bug report.  as indicated in the [new issue template](https://github.com/sqlalchemy/sqlalchemy/issues/new?assignees=&labels=requires+triage&template=bug_report.yaml), we have a tag where you can see [many examples of MCVEs](https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22great+mcve%22) - we tag them so people can get a good sense what we are looking for.   
2. always provide complete stack trace with any error message.

I'm sorry you went through all the effort to make a whole repo, below I've prepared the basic elements of a test case using your components, no error is reproduced.    

If you can illustrate the stack trace as well as additional modifications to the script below to produce your stack, we will move forward.  thanks!

```py
from dataclasses import dataclass
from dataclasses import field

from uuid import UUID
from uuid import uuid4

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import MetaData
from sqlalchemy import String
from sqlalchemy import Table
from sqlalchemy import Uuid
from sqlalchemy.orm import attribute_keyed_dict
from sqlalchemy.orm import registry
from sqlalchemy.orm import relationship


@dataclass
class DataclassChild:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str


@dataclass
class DataclassParent:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str

    childs: dict[str, DataclassChild] = field(default_factory=dict, init=False)


metadata: MetaData = MetaData()
mapper_registry: registry = registry(metadata=metadata)

dataclass_parent_table: Table = Table(
    "dataclass_parent",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
)

mapper_registry.map_imperatively(
    DataclassParent,
    dataclass_parent_table,
    properties={
        "childs": relationship(
            DataclassChild,
            collection_class=attribute_keyed_dict("name"),
        )
    },
)

dataclass_child_table: Table = Table(
    "dataclass_child",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
    Column(
        "dataclass_parent_id",
        Uuid,
        ForeignKey("dataclass_parent.id"),
    ),
)

mapper_registry.map_imperatively(DataclassChild, dataclass_child_table)

# added this just to check
mapper_registry.configure()
```

**Comment by cschroeer** [comment]
Hi Mike,

thanks and sorry for that. 

I added a few lines to the end of the script to reproduce the error, so you can see the entire script below. 

Thanks in advance and best regards, 

### Reproduce the error
```
from dataclasses import dataclass
from dataclasses import field

from uuid import UUID
from uuid import uuid4

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import MetaData
from sqlalchemy import String
from sqlalchemy import Table
from sqlalchemy import Uuid
from sqlalchemy.orm import attribute_keyed_dict
from sqlalchemy.orm import registry
from sqlalchemy.orm import relationship


@dataclass
class DataclassChild:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str


@dataclass
class DataclassParent:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str

    childs: dict[str, DataclassChild] = field(default_factory=dict, init=False)


metadata: MetaData = MetaData()
mapper_registry: registry = registry(metadata=metadata)

dataclass_parent_table: Table = Table(
    "dataclass_parent",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
)

mapper_registry.map_imperatively(
    DataclassParent,
    dataclass_parent_table,
    properties={
        "childs": relationship(
            DataclassChild,
            collection_class=attribute_keyed_dict("name"),
        )
    },
)

dataclass_child_table: Table = Table(
    "dataclass_child",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
    Column(
        "dataclass_parent_id",
        Uuid,
        ForeignKey("dataclass_parent.id"),
    ),
)

mapper_registry.map_imperatively(DataclassChild, dataclass_child_table)

# added this just to check
mapper_registry.configure()


# Added from cschroeer: 
childs = {"child1": DataclassChild("child1"), "child2": DataclassChild("child2")}

parent = DataclassParent("parent1")
parent.childs = childs


test_dict = dict(((k), (v)) for k, v in parent.childs.items()) # => works
test_type = type(parent.childs)(((k), (v)) for k, v in parent.childs.items()) # => error
#Traceback (most recent call last):
#  File "/home/cschroeer/python-projects/dataclasses-asdict-core/main_zzzeek.py", line 81, in <module>
#    test_type = type(parent.childs)(((k), (v)) for k, v in parent.childs.items())
#TypeError: _mapped_collection_cls.<locals>._MKeyfuncMapped.__init__() takes 1 positional argument but 2 were given
```

### Error
```
Traceback (most recent call last):
  File "/home/cschroeer/python-projects/dataclasses-asdict-core/main_zzzeek.py", line 81, in <module>
    test_type = type(parent.childs)(((k), (v)) for k, v in parent.childs.items())
TypeError: _mapped_collection_cls.<locals>._MKeyfuncMapped.__init__() takes 1 positional argument but 2 were given
```

### Versions: 
- OS: Ubuntu 20.04.5 LTS
- Python: 3.10.9
- SQLAlchemy: 2.0.4

**Comment by zzzeek** [comment]
OK, this has nothing to do with dataclasses, you are using SQLAlchemy's internal collection type in an unusual way that is unnecessary and not expected.

the mapped collection type you are extracting doesn't take any arguments and it is only populated after construction:

```py
test_type = type(parent.childs)
new_dict = test_type()
new_dict.update(
    ((k, v) for k, v in parent.childs.items())
)
```

in 1.4, the code would not work either, it has a different calling signature.

There should be no reason that you need to extract the type of the instrumented collection.  you can assign a plain dictionary to the attribute and it's translated as needed.

**Comment by cschroeer** [comment]
I understand the occurring behavior better and better. 

By itself it may look like a contrived example, but in a similar way this is done in the asdict method of dataclasses. 

Attached is the example with the difference that asdict is called. 

# Reproduce the error
```
from dataclasses import dataclass
from dataclasses import field
from dataclasses import asdict

from uuid import UUID
from uuid import uuid4

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import MetaData
from sqlalchemy import String
from sqlalchemy import Table
from sqlalchemy import Uuid
from sqlalchemy.orm import attribute_keyed_dict
from sqlalchemy.orm import registry
from sqlalchemy.orm import relationship


@dataclass
class DataclassChild:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str


@dataclass
class DataclassParent:
    id: UUID = field(default_factory=uuid4, init=False)
    name: str

    childs: dict[str, DataclassChild] = field(default_factory=dict, init=False)


metadata: MetaData = MetaData()
mapper_registry: registry = registry(metadata=metadata)

dataclass_parent_table: Table = Table(
    "dataclass_parent",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
)

mapper_registry.map_imperatively(
    DataclassParent,
    dataclass_parent_table,
    properties={
        "childs": relationship(
            DataclassChild,
            collection_class=attribute_keyed_dict("name"),
        )
    },
)

dataclass_child_table: Table = Table(
    "dataclass_child",
    mapper_registry.metadata,
    Column("id", Uuid, primary_key=True),
    Column("name", String),
    Column(
        "dataclass_parent_id",
        Uuid,
        ForeignKey("dataclass_parent.id"),
    ),
)

mapper_registry.map_imperatively(DataclassChild, dataclass_child_table)

# added this just to check
mapper_registry.configure()


# Added from cschroeer: 
childs = {"child1": DataclassChild("child1"), "child2": DataclassChild("child2")}

parent = DataclassParent("parent1")
parent.childs = childs

# new compard to previous

asdict(parent)

```

# Error

```
Traceback (most recent call last):
  File "/home/cschroeer/python-projects/dataclasses-asdict-core/main_zzzeek.py", line 78, in <module>
    asdict(parent)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: _mapped_collection_cls.<locals>._MKeyfuncMapped.__init__() takes 1 positional argument but 2 were given

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**KeyFuncDict regression fixes and dataclass fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4489
