### ISSUE TITLE
Enum validate_strings is not working on select

### ISSUE THREAD

**Issue by bfaust-baxter** [sqlalchemy/sqlalchemy#9457]
### Describe the bug

I'm using postgres ENUM and the values for this enum are updated directly on the database.

Using the "validate_strings=False" I can insert rows in the table using sqlalchemy, but, the select raises a LookupError.

The result expected is the SQLAlchemy won't validate the select result against the enum values (because these values are changed directly on the database without update the enum class).

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.validate_strings

### SQLAlchemy Version in Use

2.0.5.post1

### DBAPI (i.e. the database driver)

psycopg2 = "2.9.5", asyncpg = "0.27.0"

### Database Vendor and Major Version

PostgreSQL 15.2 on aarch64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.102), 64-bit

### Python Version

3.11.1

### Operating system

macOS-13.2.1-arm64-arm-64bit Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023

### To Reproduce

```python
from sqlalchemy import Select, Enum, create_engine, SmallInteger, Insert, DDL
from sqlalchemy.orm import DeclarativeBase, mapped_column
from sqlalchemy import __version__
import enum
import platform

print("Python version:", platform.python_version())
print("SQLAlchemy version:", __version__)
print("OS:", platform.platform(), platform.version().split(";")[0])

# connect to database
engine = create_engine(
    url="postgresql+psycopg2://postgres@localhost:5432/postgres", echo=True
)


class Base(DeclarativeBase):
    pass


class _Test_Code(enum.Enum):
    ONE = 1


class Test(Base):
    __tablename__ = "test"
    id = mapped_column(SmallInteger, primary_key=True, nullable=False)
    code = mapped_column(
        Enum(
            _Test_Code,
            name="_Test_Code",
            validate_strings=False,
        ),
        nullable=False,
    )


print(Test.code.__dict__)

# Get the metadata
base = Base()
metadata = base.metadata
# Recreate the database
metadata.drop_all(engine)
metadata.create_all(engine)

# change enum direct on database
ddl = DDL("ALTER TYPE \"_Test_Code\" ADD VALUE 'TWO'")
with engine.begin() as conn:
    result1 = conn.execute(ddl)
    print(result1)
    conn.commit()
    conn.close()

# insert
ins1 = Insert(Test).values([1, "ONE"])
ins2 = Insert(Test).values([2, "TWO"])
with engine.begin() as conn:
    result1 = conn.execute(ins1)
    print(result1)
    result2 = conn.execute(ins2)
    print(result2)
    conn.commit()
    conn.close()

# select table
sel1 = Select(Test).where(Test.code == "TWO")
with engine.begin() as conn:
    result = conn.execute(sel1).mappings().all()
    print(result)
    conn.close()
```

### Error

Python version: 3.11.1
SQLAlchemy version: 2.0.5.post1
OS: macOS-13.2.1-arm64-arm-64bit Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023
{'key': 'code', 'name': 'code', 'table': Table('test', MetaData(), Column('id', SmallInteger(), table=<test>, primary_key=True, nullable=False), Column('code', Enum('ONE', name='_Test_Code'), table=<test>, nullable=False), schema=None), 'type': Enum('ONE', name='_Test_Code'), 'is_literal': False, 'primary_key': False, '_user_defined_nullable': False, 'nullable': False, 'index': None, 'unique': None, 'system': False, 'doc': None, 'autoincrement': 'auto', 'constraints': set(), 'foreign_keys': set(), 'comment': None, 'computed': None, 'identity': None, 'dispatch': <sqlalchemy.event.base.DDLEventsDispatch object at 0x102099910>, 'default': None, 'onpudate': None, 'server_default': None, 'server_onupdate': None, '_creation_order': 160, '_proxies': [], 'proxy_set': frozenset({Column('code', Enum('ONE', name='_Test_Code'), table=<test>, nullable=False)}), '_Annotated__element': Column('code', Enum('ONE', name='_Test_Code'), table=<test>, nullable=False), '_annotations': immutabledict({'entity_namespace': <Mapper at 0x102205c50; Test>, 'parententity': <Mapper at 0x102205c50; Test>, 'parentmapper': <Mapper at 0x102205c50; Test>, 'proxy_key': 'code'}), '_hash': 270665005, '_propagate_attrs': immutabledict({'compile_state_plugin': 'orm', 'plugin_subject': <Mapper at 0x102205c50; Test>})}
2023-03-09 12:30:55,614 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-03-09 12:30:55,614 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-03-09 12:30:55,615 INFO sqlalchemy.engine.Engine select current_schema()
2023-03-09 12:30:55,615 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-03-09 12:30:55,616 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-03-09 12:30:55,616 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-03-09 12:30:55,617 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-09 12:30:55,619 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2023-03-09 12:30:55,619 INFO sqlalchemy.engine.Engine [generated in 0.00012s] {'table_name': 'test', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2023-03-09 12:30:55,626 INFO sqlalchemy.engine.Engine 
DROP TABLE test
2023-03-09 12:30:55,626 INFO sqlalchemy.engine.Engine [no key 0.00005s] {}
2023-03-09 12:30:55,629 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname 
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace 
WHERE pg_catalog.pg_type.typname = %(typname_1)s AND pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2023-03-09 12:30:55,629 INFO sqlalchemy.engine.Engine [generated in 0.00007s] {'typname_1': '_Test_Code', 'nspname_1': 'pg_catalog'}
2023-03-09 12:30:55,630 INFO sqlalchemy.engine.Engine DROP TYPE "_Test_Code"
2023-03-09 12:30:55,630 INFO sqlalchemy.engine.Engine [no key 0.00004s] {}
2023-03-09 12:30:55,630 INFO sqlalchemy.engine.Engine COMMIT
2023-03-09 12:30:55,634 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-09 12:30:55,634 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2023-03-09 12:30:55,634 INFO sqlalchemy.engine.Engine [cached since 0.01455s ago] {'table_name': 'test', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2023-03-09 12:30:55,634 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname 
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace 
WHERE pg_catalog.pg_type.typname = %(typname_1)s AND pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2023-03-09 12:30:55,634 INFO sqlalchemy.engine.Engine [cached since 0.005133s ago] {'typname_1': '_Test_Code', 'nspname_1': 'pg_catalog'}
2023-03-09 12:30:55,635 INFO sqlalchemy.engine.Engine CREATE TYPE "_Test_Code" AS ENUM ('ONE')
2023-03-09 12:30:55,635 INFO sqlalchemy.engine.Engine [no key 0.00003s] {}
2023-03-09 12:30:55,636 INFO sqlalchemy.engine.Engine 
CREATE TABLE test (
	id SMALLSERIAL NOT NULL, 
	code "_Test_Code" NOT NULL, 
	PRIMARY KEY (id)
)

2023-03-09 12:30:55,636 INFO sqlalchemy.engine.Engine [no key 0.00003s] {}
2023-03-09 12:30:55,639 INFO sqlalchemy.engine.Engine COMMIT
2023-03-09 12:30:55,639 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-09 12:30:55,639 INFO sqlalchemy.engine.Engine ALTER TYPE "_Test_Code" ADD VALUE 'TWO'
2023-03-09 12:30:55,639 INFO sqlalchemy.engine.Engine [no key 0.00002s] {}
<sqlalchemy.engine.cursor.CursorResult object at 0x1020eb2a0>
2023-03-09 12:30:55,640 INFO sqlalchemy.engine.Engine COMMIT
2023-03-09 12:30:55,640 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-09 12:30:55,641 INFO sqlalchemy.engine.Engine INSERT INTO test (id, code) VALUES (%(id)s, %(code)s)
2023-03-09 12:30:55,641 INFO sqlalchemy.engine.Engine [generated in 0.00007s] {'id': 1, 'code': 'ONE'}
<sqlalchemy.engine.cursor.CursorResult object at 0x1020eb3f0>
2023-03-09 12:30:55,641 INFO sqlalchemy.engine.Engine INSERT INTO test (id, code) VALUES (%(id)s, %(code)s)
2023-03-09 12:30:55,641 INFO sqlalchemy.engine.Engine [cached since 0.00064s ago] {'id': 2, 'code': 'TWO'}
<sqlalchemy.engine.cursor.CursorResult object at 0x1020eb460>
2023-03-09 12:30:55,642 INFO sqlalchemy.engine.Engine COMMIT
SELECT test.id, test.code 
FROM test 
WHERE test.code = :code_1
2023-03-09 12:30:55,642 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-09 12:30:55,643 INFO sqlalchemy.engine.Engine SELECT test.id, test.code 
FROM test 
WHERE test.code = %(code_1)s
2023-03-09 12:30:55,643 INFO sqlalchemy.engine.Engine [generated in 0.00005s] {'code_1': 'TWO'}
2023-03-09 12:30:55,643 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    return self._object_lookup[elem]
           ~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'TWO'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/*****/api/test.py", line 74, in <module>
    result = conn.execute(sel1).mappings().all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 2067, in all
    return self._allrows()
           ^^^^^^^^^^^^^^^
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 532, in _allrows
    made_rows = [make_row(row) for row in rows]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 532, in <listcomp>
    made_rows = [make_row(row) for row in rows]
                 ^^^^^^^^^^^^^
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 25, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1772, in process
    value = self._object_value_for_elem(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*****/Library/Caches/pypoetry/virtualenvs/api-QkoW9Ihp-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1655, in _object_value_for_elem
    raise LookupError(
**LookupError: 'TWO' is not among the defined enum values. Enum name: _Test_Code. Possible values: ONE**

### Additional context

None

**Comment by CaselIT** [comment]
Hi,

I think this is the expected behaviour, since otherwise the returned value is undefined.

I'm not sure what you would expect that select to return

**Comment by bfaust-baxter** [comment]
I expected the same behavior as the update, to pass the validation when the "validate_strings=False".
Because there is no logic to passing the validation on inserts and not for inserts.
If I had inserted the value, I would select this value too.

**Comment by CaselIT** [comment]
That does not really answer the question though. `Enum(_Test_Code, name="_Test_Code", validate_strings=False)` behaviour is to return instances of `_Test_Code`. If there is no `_Test_Code` connected to a value what should be the returned value here?

**Comment by bfaust-baxter** [comment]
OK, I understand your point.
But validate_strings=False is to bypass this behavior, right?

Also, following your logic, we need to apply the same rule for the inserts, right?
So, why can I insert values that aren't in the enum but not select them?

In my business need, how can I use the enum type if the values are changed directly on the database?
Can I add values to the enum programmatically?
SQLAlchemy can update the enum from the database - inspect or autoload?

**Comment by CaselIT** [comment]
I agree with you that `validate_strings` is a bit inconsistent here, but it's working as documented https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum

> When reading a value from the database in a result set, the string value is always checked against the list of possible values and a LookupError is raised if no match is found. When passing a value to the database as a plain string within a SQL statement, if the [Enum.validate_strings](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.validate_strings) parameter is set to True, a LookupError is raised for any string value that’s not located in the given list of possible values

I'm not sure why it was implemented that way, probably it was so it could work when passed a python Enum. @zzzeek do you remember?

> Can I add values to the enum programmatically? SQLAlchemy can update the enum from the database - inspect or autoload?

I don't think you can, I think Enum classes are immutable once defined.

I think for your use case a type decorator is probably more appropriate. You can make it compile to an enum on postgres, but act like a string otherwise from python point of view. Something along these lines

```py
import sqlalchemy as sa
from sqlalchemy.ext import compiler
import enum

e = sa.create_engine("postgresql+psycopg2://scott:tiger@127.0.0.1:5432/test", echo=True)
m = sa.MetaData()

class TextEnum(sa.TypeDecorator):
    impl = sa.Text()
    cache_ok = True

    def __init__(self, enum_name: str):
        self.enum_name = enum_name

    def bind_processor(self, dialect):
        def fn(value):
            return getattr(value, "name", value)
        return fn

class MyEnum(str, enum.Enum):
    A = 'A'
    B = 'B'

@compiler.compiles(TextEnum, "postgresql")
def compileTextEnum(element, compiler, **kw):
    return compiler.dialect.identifier_preparer.quote(element.enum_name)

t = sa.Table("t1", m, sa.Column("x", sa.Integer), sa.Column("y", TextEnum("my_enum")))

# Optionally create the enum. Can also be created differently
make_enum = sa.DDL("CREATE TYPE my_enum AS ENUM ('A', 'B', 'C')")
sa.event.listen(t, "before_create", make_enum)

with e.connect() as conn:
    m.create_all(conn)
    conn.execute(t.insert(), [{'y': MyEnum.A}, {'y': MyEnum.B}, {'y': 'C'}])
    val = conn.scalars(sa.select(t.c.y).order_by(t.c.y)).all()
    print(val)
    assert val[0] == MyEnum.A
    assert val[1] == MyEnum.B
    assert val[2] == 'C'
```
