### ISSUE TITLE
active_history is not implemetned for composites

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9460]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9458

this is not really mainstream public API but the property seems to not be set up

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy.orm import composite
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Model(Base):
    __tablename__ = 'model'

    id = Column(Integer, primary_key=True)
    composite = composite(tuple, Column('value_1', Integer), Column('value_2', Integer))

Model.registry.configure()

# this of course should be on the composite
Model.composite.impl.active_history = True

```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 15, in <module>
    Model.composite.impl.active_history = True
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 925, in _set_active_history
    self.dispatch._active_history = value
AttributeError: '_ProxyImpl' object has no attribute 'dispatch'

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement active_history for composites** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4501
