### ISSUE TITLE
regression: Proxy(QueryableAttribute) raiseerr=False removed for ._parententity

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9519]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9518

the stack can be illustrated as of b56494ba64f858a60a3314 as follows:

```py
from sqlalchemy import Column
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import column_property
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import declared_attr

Base = declarative_base()


class DnsRecord(Base):
    __tablename__ = 'dnsrecord'
    id = Column(Integer, primary_key=True)
    name = Column(String, unique=False, nullable=False)

    @declared_attr
    def thing(cls):
        return column_property(cls.ip_value)

    @hybrid_property
    def ip_value(self):
        return self.name[1:3]

    @ip_value.expression
    def ip_value(cls):
        return func.substring(cls.name, 1, 3)

```

stack:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test4.py", line 14, in <module>
    class DnsRecord(Base):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_api.py", line 199, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 574, in __init__
    self._extract_mappable_attributes()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 1406, in _extract_mappable_attributes
    value = getattr(cls, k)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_api.py", line 304, in __get__
    reg[self] = obj = self.fget(cls)
  File "/home/classic/dev/sqlalchemy/test4.py", line 21, in thing
    return column_property(cls.ip_value)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/_orm_constructors.py", line 423, in column_property
    return MappedSQLExpression(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/properties.py", line 157, in __init__
    self.columns = [
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/properties.py", line 158, in <listcomp>
    coercions.expect(roles.LabeledColumnExprRole, c) for c in columns
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/coercions.py", line 397, in expect
    element = element.__clause_element__()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 372, in __clause_element__
    return self.expression
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 698, in __getattr__
    return util.MemoizedSlots.__getattr__(self, attribute)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 1309, in __getattr__
    value = getattr(self, f"_memoized_attr_{key}")()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 334, in _memoized_attr_expression
    "proxy_owner": self._parententity,
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 614, in _parententity
    return inspection.inspect(self.class_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/inspection.py", line 118, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'sqlalchemy.orm.decl_api.DeclarativeMeta'>
```

issue is this:

```diff
diff --git a/lib/sqlalchemy/orm/attributes.py b/lib/sqlalchemy/orm/attributes.py
index f33364c624..3a60eda4f2 100644
--- a/lib/sqlalchemy/orm/attributes.py
+++ b/lib/sqlalchemy/orm/attributes.py
@@ -611,11 +611,11 @@ def create_proxied_attribute(
 
         @property
         def _parententity(self):
-            return inspection.inspect(self.class_)
+            return inspection.inspect(self.class_, raiseerr=False)
 
         @property
         def parent(self):
-            return inspection.inspect(self.class_)
+            return inspection.inspect(self.class_, raiseerr=False)
 
         _is_internal_proxy = True
 

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**return None for no parententity on Proxy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4524

**Comment by ikus060** [comment]
Big Thank You for the Quick Fix. It's very much appreciated !
