### ISSUE TITLE
error msg:: mojibake

### ISSUE THREAD

**Issue by linpan** [sqlalchemy/sqlalchemy#9524]
### Describe the bug

psycopg2.OperationalError: ������������������������������: Operation timed out

### SQLAlchemy Version in Use

sqlalchemy==1.4.46

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL15

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
Exception during reset or similar
Traceback (most recent call last):
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy
    fairy._reset(pool, transaction_was_reset)
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: ������������������������������: Operation timed out
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 

### Additional context

`Exception during reset or similar
Traceback (most recent call last):
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy
    fairy._reset(pool, transaction_was_reset)
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/hiro/Library/Caches/pypoetry/virtualenvs/argon-QwkX3TcS-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: ������������������������������: Operation timed out
`

**Comment by CaselIT** [comment]
Hi,

No information is provided and what little was provided appears to be incorrect.
> DBAPI (i.e. the database driver)
> asyncpg

> psycopg2.OperationalError

sorry but there is no issue here at the moment.

If you can provide more information please feel free to reopen
