### ISSUE TITLE
MsSQL Query incorrectly generated when using Column.collate

### ISSUE THREAD

**Issue by hdmoreland** [sqlalchemy/sqlalchemy#9535]
### Describe the bug

When performing a join between two tables that share an identical column name (password), I receive a join error from my database driver itself (pyodbc) that there is an ambiguous column name. The join error is accurate and expected on behalf of the driver, because the command generated by sqlalchemy is missing a critical component. When I specify collation in my ORM/Schema/Class, SQLAlchemy is no longer defining the table table before the column name.

SQLAlchemy is generating this query:
```
SELECT users.email AS users_email, users.[AgencyID] AS [users_AgencyID], [Agency].[AgencyName] AS [Agency_AgencyName] 
FROM users JOIN [Agency] ON users.[AgencyID] = [Agency].[AgencyID] 
WHERE lower(users.email) = ? AND (password COLLATE SQL_Latin1_General_CP1_CS_AS) = ?
```

SQLAlchemy should be generating this query, where "password" becomes "users.password" in the bottom line:
```
SELECT users.email AS users_email, users.[AgencyID] AS [users_AgencyID], [Agency].[AgencyName] AS [Agency_AgencyName] 
FROM users JOIN [Agency] ON users.[AgencyID] = [Agency].[AgencyID] 
WHERE lower(users.email) = ? AND (users.password COLLATE SQL_Latin1_General_CP1_CS_AS) = ?
```

This is how I am defining my query in the code. I am clearly defining DatabaseUsers.password in my filter, which can be seen on the bottom line.
```
    # Define the join for the SQL query
    query = db.query(DatabaseUsers.email, DatabaseUsers.agency_id, DatabaseAgency.agency_name) \
              .join(DatabaseAgency, DatabaseUsers.agency_id == DatabaseAgency.agency_id) \
              .filter(func.lower(DatabaseUsers.email) == username.lower(),
                      DatabaseUsers.password == password)
```

Here is my ORM for the DatabaseUsers table:
```
class DatabaseUsers(Base):
    __tablename__ = 'users'
    
    user_id = Column('UserID', Integer, primary_key=True)
    agency_id = Column('AgencyID', Integer)
    email = Column('email', String, nullable=True)
    password = Column('Password', String).collate('SQL_Latin1_General_CP1_CS_AS') # This does not work and throws an error
    #password = Column('Password', String) # This works fine
```

Here is my ORM for the DatabaseAgency table:
```
class DatabaseAgency(declarative_base()):
    __tablename__ = 'Agency'
    agency_id = Column('AgencyID', Integer, primary_key=True)
    agency_name = Column('AgencyName', String)
    password = Column('Password', String)
```

When I run the same query in the code, without the collation defined in my ORM/Schema this is the query that is correctly generated:

```
SELECT users.email AS users_email, users.[AgencyID] AS [users_AgencyID], [Agency].[AgencyName] AS [Agency_AgencyName] 
FROM users JOIN [Agency] ON users.[AgencyID] = [Agency].[AgencyID] 
WHERE lower(users.email) = ? AND users.password = ?
```

### SQLAlchemy Version in Use

2.0.7

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

Microsoft SQL Server Standard 15.0.4280.7

### Python Version

3.9.6

### Operating system

OSX Ventura 13.2.1 (22D68)

### To Reproduce

```python
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from .config import DATABASE_SERVER, DATABASE_NAME, DATABASE_USERNAME, DATABASE_PASSWORD

username = 'test'
password = 'pass'

class DatabaseUsers(declarative_base()):
    __tablename__ = 'users'
    
    user_id = Column('UserID', Integer, primary_key=True)
    agency_id = Column('AgencyID', Integer)
    email = Column('email', String, nullable=True)
    password = Column('password', String).collate('SQL_Latin1_General_CP1_CS_AS') # This does not work and throws an error
    #password = Column('password', String) # This works fine

class DatabaseAgency(declarative_base()):
    __tablename__ = 'Agency'
    agency_id = Column('AgencyID', Integer, primary_key=True)
    agency_name = Column('AgencyName', String)
    password = Column('Password', String)

engine = create_engine(f'mssql+pyodbc://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_SERVER}/{DATABASE_NAME}?driver=ODBC Driver 17 for SQL Server')
SessionLocal = sessionmaker(bind=engine)
with SessionLocal() as db:
   # Define the join for the SQL query
   query = db.query(DatabaseUsers.email, DatabaseUsers.agency_id, DatabaseAgency.agency_name) \
                  .join(DatabaseAgency, DatabaseUsers.agency_id == DatabaseAgency.agency_id) \
                  .filter(func.lower(DatabaseUsers.email) == username.lower(),
                          DatabaseUsers.password == password)
        
   print(query)

   users = query.all()
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```
Traceback (most recent call last):
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Ambiguous column name 'password'. (209) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/holden/Desktop/visual_studio/rtc-connect-api/./app/authenticaton/routes.py", line 68, in authenticate_user_from_username_password
    user = await authenticate_user_in_database(username=form_data.username, password=form_data.password, agency_name=agency_name, db=db)
  File "/Users/holden/Desktop/visual_studio/rtc-connect-api/./app/authenticaton/routes.py", line 109, in authenticate_user_in_database
    users = query.all()
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2697, in all
    return self._iter().all()  # type: ignore
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2855, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/holden/Desktop/visual_studio/azureaks/azureapi/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
**sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Ambiguous column name 'password'. (209) (SQLExecDirectW)")**
[SQL: SELECT users.email AS users_email, users.[AgencyID] AS [users_AgencyID], [Agency].[AgencyName] AS [Agency_AgencyName] 
FROM users JOIN [Agency] ON users.[AgencyID] = [Agency].[AgencyID] 
WHERE lower(users.email) = ? **AND (password COLLATE SQL_Latin1_General_CP1_CS_AS) = ?]**
[parameters: ('_removed_', '_removed_')]
(Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. Not sure if this is limited to sql server or if the bug is in the default compiler too

**Comment by hdmoreland** [comment]
I found a work around -- specify the collate in the query build out instead of in the ORM class.

New code:
 ```
   # Define the join for the SQL query
    query = db.query(DatabaseUsers.email, DatabaseUsers.agency_id, DatabaseAgency.agency_name) \
              .join(DatabaseAgency, DatabaseUsers.agency_id == DatabaseAgency.agency_id) \
              .filter(func.lower(DatabaseUsers.email) == username.lower(),
                      collate(DatabaseUsers.password, 'SQL_Latin1_General_CP1_CS_AS') == password)

```

Output, which is correct:
```
SELECT users.email AS users_email, users.[AgencyID] AS [users_AgencyID], [Agency].[AgencyName] AS [Agency_AgencyName] 
FROM users JOIN [Agency] ON users.[AgencyID] = [Agency].[AgencyID] 
WHERE lower(users.email) = ? AND (users.password COLLATE SQL_Latin1_General_CP1_CS_AS) = ?
```

**Comment by zzzeek** [comment]
hi -

the mapping is incorrect.  If you are trying to indicate a collation on your table as created, you add that as part of the `String` datatype:

```py
class DatabaseUsers(Base):
    __tablename__ = 'users'

    user_id = Column('UserID', Integer, primary_key=True)
    agency_id = Column('AgencyID', Integer)
    email = Column('email', String, nullable=True)
    password = Column('Password', String(collation='SQL_Latin1_General_CP1_CS_AS'))

```

This OTOH is not a correct mapping, "password" is not associated with any table:

```py
class DatabaseUsers(Base):
    __tablename__ = 'users'

    user_id = Column('UserID', Integer, primary_key=True)
    agency_id = Column('AgencyID', Integer)
    email = Column('email', String, nullable=True)
    password = Column('Password', String).collate('SQL_Latin1_General_CP1_CS_AS')
```

a CREATE TABLE for the above does not include "password".  If you wanted the collation to be present as an explicit operator each time automatically, you would use column_property() for that:


```py
class DatabaseUsers(Base):
    __tablename__ = "users"

    user_id = Column("UserID", Integer, primary_key=True)
    agency_id = Column("AgencyID", Integer)
    email = Column("email", String, nullable=True)
    _password = Column("Password", String)
    password = column_property(
        _password.collate("SQL_Latin1_General_CP1_CS_AS")
    )

```

therefore I dont see any bug here, other than the possibility of Declarative detecting that a free-standing SQL expression that includes `Column` within it might be incorrect intent, but that would be very tricky to detect.

**Comment by CaselIT** [comment]
> the mapping is incorrect

did not notice that part.

> sitting in the class dictionary

not sure if it's something sqlalchemy should do something about, since it may very well be what you want

**Comment by zzzeek** [comment]
looks really like something that should warn.    You can make that attribute deferred() instead.  I guess if you wanted to use it at the instance level as an expression also but that seems quite strange.

**Comment by zzzeek** [comment]
this warning will be added in #9537
