### ISSUE TITLE
deferred_group attributed is not copied across in orm.properties.MappedColumn

### ISSUE THREAD

**Issue by arabidopsis** [sqlalchemy/sqlalchemy#9550]
### Describe the bug

https://github.com/sqlalchemy/sqlalchemy/blob/c7ce7ff0225fe0ddaf63f0706429b885410de365/lib/sqlalchemy/orm/properties.py#L593

`deferred_group` attribute is not copied across in `orm.properties.MappedColumn._copy` method

### SQLAlchemy Version in Use

2.0.7

### DBAPI (i.e. the database driver)

mysqlclient

### Database Vendor and Major Version

MySQL 8

### Python Version

3.11.0

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import Text
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class PaperBase(DeclarativeBase):
    __abstract__ = True
    id: Mapped[int] = mapped_column(primary_key=True)
    abstract: Mapped[str] = mapped_column(Text, deferred=True)


class Paper(PaperBase):
    __tablename__ = "ttt"
```

### Error

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/arabidopsis/github/sqla2-test/sqla2_test/models2.py", line 15, in <module>
    class Paper(PaperBase):
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 838, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 576, in __init__
    self._extract_declared_columns()
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1569, in _extract_declared_columns
    mp_to_assign = c.mapper_property_to_assign
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arabidopsis/github/sqla2-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 618, in mapper_property_to_assign
    group=self.deferred_group,
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MappedColumn' object has no attribute 'deferred_group'
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting

**Comment by arabidopsis** [comment]
No problem. Amazing work people!

**Comment by zzzeek** [comment]
this is the patch

```diff
diff --git a/lib/sqlalchemy/orm/properties.py b/lib/sqlalchemy/orm/properties.py
index 4c07bad235..2f7b85d88f 100644
--- a/lib/sqlalchemy/orm/properties.py
+++ b/lib/sqlalchemy/orm/properties.py
@@ -594,6 +594,8 @@ class MappedColumn(
         new = self.__class__.__new__(self.__class__)
         new.column = self.column._copy(**kw)
         new.deferred = self.deferred
+        new.deferred_group = self.deferred_group
+        new.deferred_raiseload = self.deferred_raiseload
         new.foreign_keys = new.column.foreign_keys
         new._has_nullable = self._has_nullable
         new._attribute_options = self._attribute_options

```

**Comment by CaselIT** [comment]
is there a way we could test that relevant bits are copied over? IIRC it's not the first issue of the type "we forgot to copy over some things"

**Comment by zzzeek** [comment]
we have a copy test for MappedColumn somewhere we jut have to add the "deferred=True" case.   I think to test the "relevant bits" we should just be looking at coverage

**Comment by zzzeek** [comment]
i guess coverage doenwt work here because it's the "deferred" case plus the mixin case

can't generalize every problem

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**copy deferred attributes for mapped_column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4538
