### ISSUE TITLE
Recursive type definitions result in recursion error if used in a mapped dataclass

### ISSUE THREAD

**Issue by buehlefs** [sqlalchemy/sqlalchemy#9553]
### Describe the bug

If a recursive type definition is used in `Mapped[]` in a dataclass a recursion error is raised. (A recursive type definition might be needed to type the values of a JSON column)

### SQLAlchemy Version in Use

2.0.6, 2.0.7

### DBAPI (i.e. the database driver)

-

### Database Vendor and Major Version

-

### Python Version

3.10

### Operating system

Linux (on WSL2)

### To Reproduce

```python
from typing import Optional
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    mapped_column,
)
from sqlalchemy.sql import sqltypes as sql


class Base(MappedAsDataclass, DeclarativeBase):
    pass


# This produces an error
T = dict[str, Optional["T"]]

# This works:
# T = dict[str, Optional[list]]


class TypeTest(Base):
    __tablename__ = "TypeTest"

    id: Mapped[int] = mapped_column(primary_key=True)
    type_test: Mapped[T] = mapped_column(sql.JSON())
```

### Error

<details><summary>Stacktrace (click to expand)</summary>

```
Traceback (most recent call last):
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 207, in eval_expression
annotation = eval(expression, base_globals, locals_)
RecursionError: maximum recursion depth exceeded during compilation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1479, in _extract_mappable_attributes
value.declarative_scan(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 684, in declarative_scan
self._init_column_for_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 720, in _init_column_for_annotation
argument = de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>

... (shortened stacktrace as this hit the maximum allowed characters limit of github) ...

de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 165, in de_stringify_annotation
elements = tuple(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 166, in <genexpr>
de_stringify_annotation(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 156, in de_stringify_annotation
annotation = eval_expression(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 209, in eval_expression
raise NameError(
NameError: Could not de-stringify annotation 'T'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<repository_path>/test.py", line 22, in <module>
class TypeTest(Base):
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 627, in __init_subclass__
super().__init_subclass__()
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 838, in __init_subclass__
_as_declarative(cls._sa_registry, cls, cls.__dict__)
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
return _ClassScanMapperConfig(
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 574, in __init__
self._extract_mappable_attributes()
File "<venv_path>/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1491, in _extract_mappable_attributes
raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not resolve all types within mapped annotation: "sqlalchemy.orm.base.Mapped[dict[str, typing.Optional[ForwardRef('T')]]]".  Ensure all types are written correctly and are imported within the module in use.
``` 

</details>

**Comment by zzzeek** [comment]
OK, thanks for reporting, I'm not sure how we're going to fix this because it basically means we need to completely ignore types that aren't parseable if there's a type given in the column, which might not be possible to tell when we take in the annotations, have to check.

as always this can be worked around for now using a TYPE_CHECKING block.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**check for recursion with container types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4533
