### ISSUE TITLE
Annotated column mixin for single table inheritance causes column conflict

### ISSUE THREAD

**Issue by jamie-chang-globality** [sqlalchemy/sqlalchemy#9564]
### Describe the bug

Using annotated mapped columns in a mixin class with single table inheritance raises an exception during class creation.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#new-pep-484-type-annotated-mapping-support-for-dynamic-relationships

### SQLAlchemy Version in Use

2.0.8

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
from typing import Annotated, TypeAlias
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

# https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#new-pep-484-type-annotated-mapping-support-for-dynamic-relationships
intpk = Annotated[int, mapped_column(primary_key=True)]


class Base(DeclarativeBase):
    pass


class PKMixin:
    id: Mapped[intpk]


# https://docs.sqlalchemy.org/en/20/orm/inheritance.html#single-table-inheritance
class Employee(PKMixin, Base):
    __tablename__ = "employee"
    name: Mapped[str]
    type: Mapped[str]

    __mapper_args__ = {
        "polymorphic_on": "type",
        "polymorphic_identity": "employee",
    }


class Manager(Employee):
    manager_data: Mapped[str] = mapped_column(nullable=True)

    __mapper_args__ = {
        "polymorphic_identity": "manager",
    }


class Engineer(Employee):
    engineer_info: Mapped[str] = mapped_column(nullable=True)

    __mapper_args__ = {
        "polymorphic_identity": "engineer",
    }
```

### Error

```
Traceback (most recent call last):
  File "/Users/jamie.chang/.pyenv/versions/3.11.2/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamie.chang/.pyenv/versions/3.11.2/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jamie.chang/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/jamie.chang/personal-projects/sa2/main.py", line 31, in <module>
    class Manager(Employee):
  File "/Users/jamie.chang/personal-projects/sa2/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 838, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/Users/jamie.chang/personal-projects/sa2/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamie.chang/personal-projects/sa2/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamie.chang/personal-projects/sa2/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 580, in __init__
    self._setup_inheriting_columns(mapper_kw)
  File "/Users/jamie.chang/personal-projects/sa2/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1767, in _setup_inheriting_columns
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column 'id' on class Manager conflicts with existing column 'employee.id'.  If using Declarative, consider using the use_existing_column parameter of mapped_column() to resolve conflicts.
``` 

### Additional context

I'm trying to combine a few concepts here:
- [Annotated types](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#new-pep-484-type-annotated-mapping-support-for-dynamic-relationships)
- [Mixins](https://docs.sqlalchemy.org/en/20/orm/declarative_mixins.html)
- [Single table inheritance](https://docs.sqlalchemy.org/en/20/orm/inheritance.html#single-table-inheritance)

I've already found a workaround: 

The Mixin will work if the class is not a pure annotation
```python
class PKMixin:
    id: Mapped[intpk] = mapped_column()
```

But would be nice if we could get it working with only annotations

**Comment by zzzeek** [comment]
thanks for reporting, not clear what's happening here yet
