### ISSUE TITLE
assertion error w/ mapped_col compared to Column for dupe col via column_property

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9630]
```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.orm import column_property
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import mapped_column
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = mapped_column(String)
    d2 = column_property(data)
```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 10, in <module>
    class A(Base):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_api.py", line 199, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 248, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 329, in setup_mapping
    return _ClassScanMapperConfig(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 577, in __init__
    self._extract_declared_columns()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/decl_base.py", line 1647, in _extract_declared_columns
    assert col not in column_ordering
AssertionError

```

when using legacy Column, correct error generated:

```py
class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    d2 = column_property(data)
```

```
$ python test3.py 
/home/classic/dev/sqlalchemy/test3.py:10: SAWarning: On class 'A', Column object 'data' named directly multiple times, only one will be used: d2, data. Consider using orm.synonym instead
  class A(Base):

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow column named twice warning to take effect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4603
