### ISSUE TITLE
sqlalchemy after 1.4.47 version occurs error in fastapi encoders.py 

### ISSUE THREAD

**Issue by Uwanggood** [sqlalchemy/sqlalchemy#9642]
### Describe the bug

fastapi\encoders.py
def jsonable_encoder(
    obj: Any,
    include: Optional[Union[SetIntStr, DictIntStrAny]] = None,
    exclude: Optional[Union[SetIntStr, DictIntStrAny]] = None,
    by_alias: bool = True,
    exclude_unset: bool = False,
    exclude_defaults: bool = False,
    exclude_none: bool = False,
    custom_encoder: Optional[Dict[Any, Callable[[Any], Any]]] = None,
    sqlalchemy_safe: bool = True,
) -> Any: 

..........
..........
..........
 try:
        data = dict(obj)
    except Exception as e:
        errors: List[Exception] = []
        errors.append(e)
        try:
           ---------> data = vars(obj) <---- in this place if return type is odd tuple like ('a','b','c') then occurs error 
        except Exception as e:
            errors.append(e)
            raise ValueError(errors) from e
    return jsonable_encoder(
        data,
        include=include,
        exclude=exclude,
        by_alias=by_alias,
        exclude_unset=exclude_unset,
        exclude_defaults=exclude_defaults,
        exclude_none=exclude_none,
        custom_encoder=custom_encoder,
        sqlalchemy_safe=sqlalchemy_safe,
    )
    
    
    after downgrade to 1.4.47  then error disappear 

erorr code is below 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\thdwotkd\IdeaProjects\ais_project\ais_backend\app\api\middleware\middleware.py", line 44, in add_process_time_header_middleware
    response = await call_next(request)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\thdwotkd\IdeaProjects\ais_project\ais_backend\app\api\middleware\middleware.py", line 37, in middleware_verify_token_middleware
    response = await call_next(request)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\thdwotkd\IdeaProjects\ais_project\ais_backend\app\api\middleware\middleware.py", line 62, in case_change_middleware
    response = await call_next(request)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "C:\ProgramData\Anaconda3\envs\ais\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 4; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]

### SQLAlchemy Version in Use

SQLAlchemy 2.0.9

### DBAPI (i.e. the database driver)

postgre

### Database Vendor and Major Version

postgre 14.6

### Python Version

python version 3.8

### Operating system

windows

### To Reproduce

```python
@router.post("/getMenu")
async def login_access_token(
        db: Session = Depends(get_db)
):
    return db.execute(get_query(kwargs)).fetchall() <- success
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by zzzeek** [comment]
hi -

this is not really a bug report, it looks like you're having problems with fastAPI.   I'd suggest getting some help from fastAPI people first with this stack trace and they can perhaps illustrate where the program is going wrong.      not that changes in SQLAlchemy aren't involved, but things [change](https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html) in SQLAlchemy and if your program is relying on some incorrect assumptions, these things can happen.
