### ISSUE TITLE
2.0.10: pytest is failing in `test/ext/mypy/test_mypy_plugin_py3k.py::MypyPluginTest::test_files[plain-dataclass_transforms_one.py` unit

### ISSUE THREAD

**Issue by kloczek** [sqlalchemy/sqlalchemy#9691]
### Describe the bug

Looks like new version is failing in `test/ext/mypy/test_mypy_plugin_py3k.py::MypyPluginTest::test_files[plain-dataclass_transforms_one.py` unit.

### SQLAlchemy Version in Use

2.0.10

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.8.16

### Operating system

Linux/x86_64

### To Reproduce

```python
N/A
```

### Error

Here is pytest output:
<details>

```console
=================================== FAILURES ===================================
_________ MypyPluginTest.test_files[plain-dataclass_transforms_one.py] _________
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/test/ext/mypy/test_mypy_plugin_py3k.py", line 343, in test_files
    assert False, "errors and/or notes remain, see stdout"
AssertionError: errors and/or notes remain, see stdout
assert False
----------------------------- Captured stdout call -----------------------------
1 messages from mypy were not consumed:
/tmp/tmpe7_paoaw/dataclass_transforms_one.py:50: error: Argument "data" to "TestTicket9628" has incompatible type "str"; expected "Mapped[str]"  [arg-type]
=============================== warnings summary ===============================
test/orm/test_deprecations.py::DeprecatedQueryTest::test_deprecated_select_coercion_join_target
  /home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/sql/visitors.py:143: UserWarning: An alias is being generated automatically against joined entity Mapper[Address(addresses)] for raw clauseelement, which is deprecated and will be removed in a later release. Use the aliased() construct explicitly, see the linked example. (Background on this error at: https://sqlalche.me/e/20/xaj1)
    return meth(self, **kw)  # type: ignore  # noqa: E501

test/ext/test_deprecations.py::HorizontalShardTest::test_query_chooser
  /home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/ext/horizontal_shard.py:197: UserWarning: The ``id_chooser`` parameter is deprecated; please use ``identity_chooser``.
    util.warn_deprecated(

test/orm/test_deprecations.py::ImmediateTest::test_value
test/orm/test_deprecations.py::ImmediateTest::test_value_cancels_loader_opts
  <string>:2: UserWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)

test/orm/test_deprecations.py::InstancesTest::test_contains_eager
  <string>:2: UserWarning: The Query.instances() method is deprecated and will be removed in a future release. Use the Select.from_statement() method or aliased() construct in conjunction with Session.execute() instead. (deprecated since: 2.0)

test/orm/test_deprecations.py::InstancesTest::test_from_alias_two_old_way
  <string>:2: UserWarning: The AliasOption is not necessary for entities to be matched up to a query that is established via Query.from_statement() and now does nothing. (deprecated since: 1.4)

test/base/test_examples.py: 17 warnings
  /home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/examples/versioned_history/test_versioning.py:54: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    self.Base = declarative_base()

test/engine/test_pool.py::QueuePoolTest::test_userspace_disconnectionerror_weakref_finalizer[True]
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f39e25de940>

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/pool/base.py", line 732, in <lambda>
      lambda ref: _finalize_fairy(
    File "/home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/pool/base.py", line 1034, in _finalize_fairy
      util.warn(message)
    File "/home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/util/langhelpers.py", line 1819, in warn
      _warnings_warn(msg, exc.SAWarning)
    File "/home/tkloczko/rpmbuild/BUILD/sqlalchemy-rel_2_0_10/lib/sqlalchemy/util/langhelpers.py", line 1895, in _warnings_warn
      warnings.warn(message, category, stacklevel=stacklevel + 1)
  sqlalchemy.exc.SAWarning: The garbage collector is trying to clean up non-checked-in connection <Mock id='139887022500736'>, which will be dropped, as it cannot be safely terminated.  Please ensure that SQLAlchemy pooled connections are returned to the pool explicitly, either by calling ``close()`` or by using appropriate context managers to manage their lifecycle.

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
```
</details>

**Comment by zzzeek** [comment]
Tomasz -

this is not your first bug report here :)   the test passes for us - we dont do releases with tests not failing and these tests we run on many architectures and platforms, using **both** Github Actions and my own Jenkins CI environment.

 Please share some details, how you are running the suite, try removing all those pytest plugins you have, etc.   

Here's that test

```
$ tox -e mypy -- -k plain-dataclass_transforms_one
mypy: install_deps> python -I -m pip install 'greenlet!=0.4.17' 'importlib_metadata; python_version < "3.8"' 'mypy>=1.2.0' 'patch==1.*' pytest-xdist 'pytest<8,>=7.0.0rc1'
.pkg: _optional_hooks> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_editable> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_wheel> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
mypy: install_package_deps> python -I -m pip install 'greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))' 'importlib-metadata; python_version < "3.8"' 'typing-extensions>=4.2.0'
mypy: install_package> python -I -m pip install --force-reinstall --no-deps /home/classic/dev/zzzcomputing/release_scripts/_release_work/SQLAlchemy-2.0.10/.tox/.tmp/package/2/SQLAlchemy-2.0.10.tar.gz
mypy: commands[0]> pytest --color=yes -m mypy -k plain-dataclass_transforms_one
=================================================================================== sqlalchemy installation ====================================================================================
SQLAlchemy 2.0.10 (no user site)
Path: /home/classic/dev/zzzcomputing/release_scripts/_release_work/SQLAlchemy-2.0.10/.tox/mypy/lib/python3.10/site-packages/sqlalchemy/__init__.py
compiled extension enabled, e.g. /home/classic/dev/zzzcomputing/release_scripts/_release_work/SQLAlchemy-2.0.10/.tox/mypy/lib/python3.10/site-packages/sqlalchemy/cyextension/util.cpython-310-x86_64-linux-gnu.so 
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.10.0, pytest-7.3.1, pluggy-1.0.0 -- /home/classic/dev/zzzcomputing/release_scripts/_release_work/SQLAlchemy-2.0.10/.tox/mypy/bin/python
cachedir: .tox/mypy/.pytest_cache
rootdir: /home/classic/dev/zzzcomputing/release_scripts/_release_work/SQLAlchemy-2.0.10
configfile: pyproject.toml
plugins: xdist-3.2.1
collected 29773 items / 29772 deselected / 1 selected                                                                                                                                          

test/ext/mypy/test_mypy_plugin_py3k.py::MypyPluginTest::test_files[plain-dataclass_transforms_one.py] PASSED                                                                             [100%]

============================================================================= 1 passed, 29772 deselected in 27.39s =============================================================================
.pkg: _exit> python /home/classic/.venv3/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  mypy: OK (54.49=setup[23.99]+cmd[30.49] seconds)
  congratulations :) (55.05 seconds)

```


note it requires the latest mypy 1.2.0 to work correctly.  Using tox will make sure that's what's installed.

**Comment by CaselIT** [comment]
This seems the error seen in mypy1.1.x

Please update mypy.

Feel free to reopen if the error persist

**Comment by kloczek** [comment]
Indeed after upgrade 'mypy' test suite is OK now 😄 
Thank you very much 👍
