### ISSUE TITLE
Text type columns using schema qualified collations compile a quoted DDL statement on Postgres 

### ISSUE THREAD

**Issue by matt-mclaughlin-quantum-si** [sqlalchemy/sqlalchemy#9693]
### Describe the bug

If you use a `Text` type that includes a fully schema qualified collation (ie. `Text(collation="my_schema.my_collation")`), the DDL statement created when running `metadata.create_all()` is incorrect for Postgres.

The statement created presently is:
`TEXT COLLATE "my_schema.my_collation"`
Which is a reference to a collation called "my_schema.my_collation" in the default/public namespace.  

What we actually want is to reference the collation "my_collation" that resides in "my_schema" schema.  The correct statement to use the schema qualified collation instead needs to be unquoted:
`TEXT COLLATE my_schema.my_collation`

It seems, however, that the implementation in `sqlalchemy.sql.compiler.GenericTypeCompiler::_render_string_type` always builds a quoted collation name in the DDL statement, which isn't want we want in the case of schema qualified collations.

### SQLAlchemy Version in Use

2.0.10

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14.1

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
from sqlalchemy import Column, DDL, event, Integer, Text, create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base

schema_name = "my_schema"
metadata = MetaData(schema=schema_name)
Base = declarative_base(metadata=metadata)


class MyClass(Base):
    __tablename__ = "my_table"
    id = Column(Integer, primary_key=True)
    column_with_schema_qualified_collation = Column(Text(collation="my_schema.my_collation"))


# This builds our schema-qualified collation when we run metadata.create_all
event.listen(
    metadata.tables["my_schema.my_table"],
    "before_create",
    DDL(
        """
        CREATE COLLATION my_schema.my_collation (
            provider = icu,
            locale = 'en-US-u-kn-true'
        )
    """
    ),
)

engine = create_engine("postgresql+psycopg2://localhost/<my_db>")
metadata.create_all(engine)
```

### Error

```
Traceback (most recent call last):
  File "/Users/user/repos/sqlalchemy_bug_repro/main.py", line 30, in <module>
    metadata.create_all(engine)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5796, in create_all
    bind._run_ddl_visitor(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 922, in visit_metadata
    self.traverse_single(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 961, in visit_table
    )._invoke_with(self.connection)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1525, in _execute_ddl
    ret = self._execute_context(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1841, in _execute_context
    return self._exec_single_context(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/user/repos/sqlalchemy_bug_repro/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 918, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) collation "my_schema.my_collation" for encoding "UTF8" does not exist
LINE 4:  column_with_schema_qualified_collation TEXT COLLATE "my_sch...
                                                     ^

[SQL: 
CREATE TABLE my_schema.my_table (
        id SERIAL NOT NULL, 
        column_with_schema_qualified_collation TEXT COLLATE "my_schema.my_collation", 
        PRIMARY KEY (id)
)

]
``` 

### Additional context

I was able to get around this issue by adding a new Text type that has a custom compiler when using postgresql.  The custom compiler is a re-implementation of `_render_string_type`, where we build the unquoted DDL when the collation is schema qualified.

The example below is the same as the reproduction code, just with the new custom type added.  No error when running the below:

```
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.types import Text, TypeDecorator
from sqlalchemy import Column, DDL, event, Integer, Text, create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base


class SchemaQualifiedCollationText(TypeDecorator):
    """
    This gets around a limitation/bug in SQLAlchemy where schema-qualified collations applied to the Text type produce
    the wrong CREATE/ALTER statements in Postgres

    eg:
    Text(collation='my_custom_schema.my_custom_collation') produces statement:
        'COLLATE "my_custom_schema.my_custom_collation"'
    But the proper statement to use a schema-qualified collation in Postgres is actually:
        'COLLATE my_custom_schema.my_custom_collation'
    """

    impl = Text


@compiles(SchemaQualifiedCollationText, "postgresql")
def postgresql_text(type_, compiler, **kw):
    """
    This is a reimplementation of sqlalchemy.sql.compiler.GenericTypeCompiler::_render_string_type function
    When we're using postgresql, it'll build the correct unquoted collation name when supplying a schema-qualified
    collation (ie. my_custom_schema.my_custom_collation).
    """

    text = "TEXT"

    if type_.length:
        text += "(%d)" % type_.length
    if type_.collation:
        if len(type_.collation.split(".")) > 1:
            collation_str = type_.collation
        else:
            collation_str = '"%s"' % type_.collation
        text += " COLLATE %s" % collation_str
    return text

schema_name = "my_schema"
metadata = MetaData(schema=schema_name)
Base = declarative_base(metadata=metadata)


class MyClass(Base):
    __tablename__ = "my_table"
    id = Column(Integer, primary_key=True)
    column_with_schema_qualified_collation = Column(SchemaQualifiedCollationText(collation="my_schema.my_collation"))


# This builds our schema-qualified collation when we run metadata.create_all
event.listen(
    metadata.tables["my_schema.my_table"],
    "before_create",
    DDL(
        """
        CREATE COLLATION my_schema.my_collation (
            provider = icu,
            locale = 'en-US-u-kn-true'
        )
    """
    ),
)

engine = create_engine("postgresql+psycopg2://localhost/<my_db>")
metadata.create_all(engine)
```

**Comment by zzzeek** [comment]
I've never heard of a schema-qualified collation before.   PostgreSQL never ceases to reveal strange new syntaxes.

We are not really big on putting "x.y" inside of identifiers because it leads to ambiguity; someone will have a collation name with a dot inside of it.

therefore I think this has to be a new feature called "collation_schema", since we use "schema" for such qualifiers elsewhere.

**Comment by CaselIT** [comment]
As an alternative maybe we can document (and support if we don't already) placing a `text()` there for these kind of things?

**Comment by zzzeek** [comment]
for...collation?   like collation=text("foo.bar") ?   I'm not sure I would want SQL constructs there (Assuming we dont support that right now already...)

**Comment by CaselIT** [comment]
> for...collation? like collation=text("foo.bar") ? 

yes, that was the suggestion

> I'm not sure I would want SQL constructs there (Assuming we dont support that right now already...)

we do not, but it fails while compiling, not because of an explicit error.

Let's go with a collation_schema. Should it be PG only? so postgresql_collation_schema?

**Comment by zzzeek** [comment]
the type objects dont have the dialect-specific qualifiers right now, we would have to add that system in which I wouild be concerned would get in the way with the lots of cloning/copying of objects the type system does.    if other DBs ahve some kind of namespace for collations it would be useful there also so leaning towards collation_schema

**Comment by CaselIT** [comment]
ok, makes sense

**Comment by zzzeek** [comment]
> the type objects dont have the dialect-specific qualifiers right now, we would have to add that system in which I wouild be concerned would get in the way with the lots of cloning/copying of objects the type system does. if other DBs ahve some kind of namespace for collations it would be useful there also so leaning towards collation_schema

correction, after seeing how extensive the changes to compiler.py are for this, I am now leaning *away* from collation_schema, correct me if I'm wrong but this is yet another wacky PG only concept.

Proposals for how to do this would be:

1. fully traditional, which is create `sqlalchemy.dialects.postgresql.VARCHAR`, `sqlalchemy.dialects.postgresql.CHAR`, etc. and add `collation_schema` to that
2. new SQL construct - the type annotation for `collation` changes from `collation: Optional[str]` to `collation: Optional[str | Collation]`, adding new object `Collation` for which users would use a `PGCollation` instance to set up this schema
3. we support and document this:
```
class MyClass(Base):
    __tablename__ = "my_table"
    id = Column(Integer, primary_key=True)
    column_with_schema_qualified_collation = Column(
        Text(collation=quoted_name("test_schema.my_collation", quote=False))
    )

```

requires this patch:

```
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 0cd866b96..dcaf960d0 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -7325,7 +7325,9 @@ class GenericTypeCompiler(TypeCompiler):
         if length:
             text += f"({length})"
         if collation:
-            text += f' COLLATE "{collation}"'
+            text += (
+                f" COLLATE {self.dialect.identifier_preparer.quote(collation)}"
+            )
         return text
 
     def visit_CHAR(self, type_: sqltypes.CHAR, **kw: Any) -> str:

```

**Comment by zzzeek** [comment]
I think we should do 3 above and we can also have an alias in the PG dialect:

```

# sqlalchemy/dialects/postgresql/ext.py

def collation_identifier(collation_name, schema=None):
    if schema:
        preparer = PGDialect().identifier_preparer
        quoted_schema = preparer.quote(schema)
        quoted_collation_name = preparer.quote(collation_name)
        return quoted_name("{quoted_schema}.{quoted_collation_name}", quote=False)
   else:
        return collation_name
```

**Comment by sqla-tester** [comment]
**cjc0013** has proposed a fix for this issue in the **main** branch:

**Use identifier preparer for string type collations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6825

**Comment by sqla-tester** [comment]
**cjc0013** has proposed a fix for this issue in the **main** branch:

**Use identifier preparer for string type collations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6825

**Comment by zzzeek** [comment]
quoted_name() goes out of control when we talk about reflecting name/schema as a crafted quoted_name(), and another idea to use a new object like `multipart_name()` just invents a new way to do things in the middle of a system that uses a separate schema argument.

so that change will be reverted

**Comment by zzzeek** [comment]
after more looking at the larger problem I've created #13447 that will supersede this as well as #6511

@cjc0013 I apologize for my fickleness, I've reverted what we did with your PR.   
@dlax i've reorganized the scope here and will be proposing gerrits soon.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Add collation_schema parameter for schema-qualified PostgreSQL collations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/6841
