### ISSUE TITLE
In async context `run_sync()` method with additional args/kwargs raises TypeError

### ISSUE THREAD

**Issue by am1ter** [sqlalchemy/sqlalchemy#9705]
### Describe the bug

When attempting to use the `AsyncConnection.run_sync()` or `AsyncSession.run_sync()` with positional/keyword arguments in an async enivronment, the run_sync() method is passing an extra argument to the underlying function, causing a TypeError to be raised.

It is unclear whether this is a bug in the SQLAlchemy library or a result of my misunderstanding in how to use the library correctly. The expected behavior is for the run_sync() method to correctly pass the specified arguments to the underlying function.

At first glance, for me, it looks like the bug in the function `greenlet_spawn` in `_concurrency_py3k.py` . Look below.
Function call:
```
return await greenlet_spawn(fn, self._proxied, *arg, **kw)
```
Function defenition:
```
async def greenlet_spawn(
    fn: Callable[..., _T],
    *args: Any,
    _require_await: bool = False,
    **kwargs: Any,
) -> _T:
```
And inside `greenlet_spawn` function it calls the given function with all args, but not only related the given function.
```
result = context.switch(*args, **kwargs)
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncConnection.run_sync

### SQLAlchemy Version in Use

2.0.10

### DBAPI (i.e. the database driver)

asyncpg 0.27.0, aiosqlite 0.19.0

### Database Vendor and Major Version

Postgres 15.2, SQLLite

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import asyncio

from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import declarative_base

metadata = MetaData()
engine = create_async_engine("sqlite+aiosqlite:///test.db")
Base = declarative_base(metadata=metadata)


async def test(arg1, arg2):
    print(arg1, arg2)


async def test_metadata() -> None:
    async with engine.begin() as conn:
        arg1, arg2 = "test1", "test2"
        await conn.run_sync(test, arg1, arg2)


async def main():
    await test_metadata()


if __name__ == "__main__":
    asyncio.run(main())
```

### Error

Traceback (most recent call last):
  File "/home/amiter/coding/flash_decision/tests/integration/test.py", line 26, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/amiter/coding/flash_decision/tests/integration/test.py", line 22, in main
    await test_metadata()
  File "/home/amiter/coding/flash_decision/tests/integration/test.py", line 18, in test_metadata
    await conn.run_sync(test, arg1, arg2)
  File "/home/amiter/coding/flash_decision/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 802, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amiter/coding/flash_decision/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 154, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: test() takes 2 positional arguments but 3 were given

### Additional context

If I am right and it is really the bug, I would like to try to fix it and suggest my PR for it.

**Comment by zzzeek** [comment]
here's the doc:  

https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncConnection.run_sync

"Invoke the given **sync** callable **passing self** as the **first argument**."

now there are two problem with that doc; the phrase "passing self as the first argument" is a little bit vague, and also it's not accurate as it passes the **sync connection** as the first argument.  will update these now.

so your callable is not async (it's sync, which is why the method is called "run_sync") and receives the connection or session as first argument:

```py
def test(connection, arg1, arg2):
    print(arg1, arg2)


async def test_metadata() -> None:
    async with engine.begin() as conn:
        arg1, arg2 = "test1", "test2"
        await conn.run_sync(test, arg1, arg2)
```

if you want more open ended "run sync methods under SQLAlchemy's async adapter" there is a less publicized API for that, however we assume under normal use passing the Connection or ORM Session to the methods that are "sync" will usually be pretty useful.

**Comment by zzzeek** [comment]
yes please add another argument to your function that receives the "connection":

```py
def test(conneciton, arg1, arg2):
    print(arg1, arg2)
```

**Comment by am1ter** [comment]
> yes please add another argument to your function that receives the "connection":
> 
> ```python
> def test(conneciton, arg1, arg2):
>     print(arg1, arg2)
> ```

Oh, I understand now. Thank you very much!
If I am using a synchronous function from a third-party library, how can I handle this issue? Would I need to perform some sort of monkeypatching in this case?

**Comment by am1ter** [comment]
> I'm not sure why you would want to run a 3rd party function that does not require a connection using that function from the connection. It seems strange

This function I would like to run requires connection, but it recieves it as inside one of the additional arguments that I have to provide it.

**Comment by zzzeek** [comment]
you can adapt the receiving function to the run_sync method using an intermediary function

**Comment by CaselIT** [comment]
> > I'm not sure why you would want to run a 3rd party function that does not require a connection using that function from the connection. It seems strange
> 
> The function I would like to run requires connection, but it recieves it inside one of the additional arguments which I have to provide.

note that the connection passed to the `run_sync` function is not the same object you used to call `run_sync`.

I mean if you where to run `async_conn.run_sync(lambda conn: pass)` `conn` is not `async_conn`, but it's a sync version that you use without await.
