### ISSUE TITLE
Missing literal processor for datetime.timedelta in postgresql

### ISSUE THREAD

**Issue by web4u2qd** [sqlalchemy/sqlalchemy#9737]
### Describe the bug

According to the documentation (https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Interval), Interval type is "a type for datetime.timedelta() objects". When I bind a datetime.timedelta parameter and compile a statement I get the following error:
`sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "datetime.timedelta(seconds=60)" with datatype DATETIME`

I would expect it to work since other types (e.g. datetime.datetime) seem to work.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Interval

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.10.4

### Operating system

linux

### To Reproduce

```python
import datetime
import sqlalchemy
from sqlalchemy import create_mock_engine


def main():
    def dump(sql, *multiparams, **params):
        stmt = str(sql.compile(dialect=engine.dialect))
        print(stmt)

    engine = create_mock_engine("postgresql+psycopg2://", dump)

    sql = 'SELECT :parameter'
    params = {'parameter': datetime.timedelta(minutes=1)}

    stmt = sqlalchemy.text(sql).bindparams(**params)

    print(str(stmt.compile(dialect=engine.dialect, compile_kwargs={'literal_binds': True})))


if __name__ == '__main__':
    main()
```

### Error

```
Traceback (most recent call last):
  File "/home/project/src/tools/test.py", line 22, in <module>
    main()
  File "/home/project/src/tools/test.py", line 18, in main
    print(str(stmt.compile(dialect=engine.dialect, compile_kwargs={'literal_binds': True})))
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1424, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 865, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 910, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 2624, in visit_textclause
    BIND_PARAMS.sub(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 2608, in do_bindparam
    return self.process(textclause._bindparams[name], **kw)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 910, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3620, in visit_bindparam
    ret = self.render_literal_bindparam(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3759, in render_literal_bindparam
    return self.render_literal_value(value, bindparam.type)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1864, in render_literal_value
    value = super().render_literal_value(value, type_)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 3786, in render_literal_value
    raise exc.CompileError(
sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "datetime.timedelta(seconds=60)" with datatype DATETIME
```

**Comment by CaselIT** [comment]
Hi,

This is more of an use-case than a bug, since not all types support literal compilations on.
Feel free to send a PR if you can

**Comment by web4u2qd** [comment]
I am not that familiar with sqlalchemy internals, but I could try to implement it, if you gave me some pointers, e.g. show how is it done for other types.

**Comment by Gamrix** [comment]
This is implemented in psycopg3 (aka the `psycopg` engine / package). See the Date/time types adaptation in this doc. I recommend that you update your database engine.

https://www.psycopg.org/psycopg3/docs/basic/adapt.html#date-time-types-adaptation

**Comment by Gamrix** [comment]
@CaselIT I think we can close this issue.

**Comment by CaselIT** [comment]
I don't think changing drivers will have an impact on the sqlalchemy compilation

**Comment by web4u2qd** [comment]
With psycopg==3.1.9 the error is still there.

**Comment by indiVar0508** [comment]
Hi can i work on this issue if no one is working on it?

**Comment by CaselIT** [comment]
Sure, go ahead!

**Comment by indiVar0508** [comment]
Hi @CaselIT , 

Tried to address this issue in #10383 , you can review once,
added my doubt queries in commit message

**Comment by sqla-tester** [comment]
**indivar** has proposed a fix for this issue in the **main** branch:

**fixes: #9737, add literal_processors for interval** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4873

**Comment by sqla-tester** [comment]
**indivar** has proposed a fix for this issue in the **main** branch:

**add literal_processors for interval, PG and Oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4873

**Comment by zzzeek** [comment]
need to remove errant `@no_type_check` decorators

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove type check decorators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4938
