### ISSUE TITLE
session.dirty fails in after_flush event hook if a many to many relation via association table is typed and back_populates

### ISSUE THREAD

**Issue by dourvaris** [sqlalchemy/sqlalchemy#9744]
### Describe the bug

Removing a child from a parent many to many relationship that back_populates raises a `ValueError: list.remove(x): x not in list` error when accessing `session.dirty` from within `after_flush` event hook.

```python
parent = Parent(children=[Child()])
session.commit()
parent.children = []
session.commit()
```

If the attribute does *not* have the type annotation then no error occurs, though mypy complains about typing:

```diff
45c45
<     parents: Mapped[list[Parent]] = relationship(
---
>     parents = relationship(
```

If back_populates on parents is not set the issue does not occur either:

```diff
35c35
<         back_populates="parents",
---
>         # back_populates="parents",
```

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.10.4

### Operating system

Linux

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import Column, ForeignKey, Table, create_engine, event
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    Session,
    mapped_column,
    relationship,
)


class Base(MappedAsDataclass, DeclarativeBase, kw_only=True):
    pass


association_table = Table(
    "association",
    Base.metadata,
    Column("parent_id", ForeignKey("parents.id")),
    Column("child_id", ForeignKey("children.id")),
)


class Parent(Base):
    __tablename__ = "parents"

    id: Mapped[int] = mapped_column(
        primary_key=True,
        default=None,
    )
    children: Mapped[list[Child]] = relationship(
        secondary=association_table,
        back_populates="parents",
        default_factory=list,
    )


class Child(Base):
    __tablename__ = "children"

    id: Mapped[int] = mapped_column(primary_key=True, default=None)

    parents: Mapped[list[Parent]] = relationship(
        Parent,
        secondary=association_table,
        back_populates="children",
        default_factory=list,
    )


engine = create_engine("sqlite://")
Base.metadata.create_all(engine)


@event.listens_for(Session, "after_flush")
def receive_after_flush(session: Session, flush_context):
    print(session.dirty)


session = Session(engine)

child = Child()
parent = Parent(children=[child])
session.add(parent)
session.commit()
parent.children = []
session.commit()
```

### Error

```
Traceback (most recent call last):
  File "/tmp/sqlalchemy_fail_test_case.py", line 69, in <module>
    session.commit()
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4155, in flush
    self._flush(objects)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4291, in _flush
    with util.safe_reraise():
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4256, in _flush
    self.dispatch.after_flush(self, flush_context)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 378, in __call__
    fn(*args, **kw)
  File "/tmp/sqlalchemy_fail_test_case.py", line 59, in receive_after_flush
    print(session.dirty)
  File "lib/sqlalchemy/cyextension/collections.pyx", line 404, in sqlalchemy.cyextension.collections.IdentitySet.__repr__
  File "/home/dan/.pyenv/versions/3.10.4/lib/python3.10/dataclasses.py", line 405, in wrapper
    result = user_function(self)
  File "<string>", line 3, in __repr__
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 557, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1085, in get
    return self.set_committed_value(state, dict_, value)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 2015, in set_committed_value
    collection.remove_without_event(item)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 585, in remove_without_event
    self._data()._sa_remover(item, _sa_initiator=False)
  File "/tmp/.venv/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 1077, in remove
    fn(self, value)
ValueError: list.remove(x): x not in list
```

**Comment by CaselIT** [comment]
out of curiosity, what was the problem?
