### ISSUE TITLE
Rows returned from query do not behave correctly with the `in` keyword

### ISSUE THREAD

**Issue by skarfie123** [sqlalchemy/sqlalchemy#9761]
### Describe the bug

Rows returned from query do not behave correctly with the `in` keyword, after upgrade.

Given a query: `SELECT id, name FROM users`, and executing like so:
```python
rows = session.execute("SELECT id, name FROM users").fetchall()
```
then doing:
```python
"name" in rows[0]
```
you would expect it to return true.

with SQLAlchemy==1.3.18, it returns true.
with SQLAlchemy==1.4.47, it returns false.

### SQLAlchemy Version in Use

1.4.47

### DBAPI (i.e. the database driver)

psycopg2-binary==2.9.5

### Database Vendor and Major Version

PostgreSQL (docker latest)

### Python Version

3.10, 3.11

### Operating system

Windows, OSX, Linux

### To Reproduce

```python
1. start database

docker run -p 5432:5432 -e POSTGRES_PASSWORD=password postgres


2. create `main.py`
```python
from sqlalchemy import Column, Integer, Text, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(Integer(), primary_key=True)
    name = Column(Text)


def main():
    url = "postgresql://postgres:password@localhost:5432/postgres"

    engine = create_engine(url)
    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    session = Session()

    if not session.query(User).count():
        session.add(User(id=1, name="rahul"))
        session.commit()

    rows = session.execute("SELECT id, name FROM users").fetchall()
    print(rows)

    assert len(rows) == 1

    assert rows[0]["name"] == "rahul"

    assert "name" in rows[0] # this fails in the newer version


if __name__ == "__main__":
    main()
```

3. run with SQLAlchemy==1.4.47 and psycopg2-binary==2.9.5
this gives AssertionError

4. run with SQLAlchemy==1.3.18 and psycopg2-binary==2.9.5
this gives no error

### Error

```
❯ python main.py
C:\Users\rahul\GitHub\skarfie123\sqltest\main.py:7: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()
[(1, 'rahul')]
Traceback (most recent call last):
  File "C:\Users\rahul\GitHub\skarfie123\sqltest\main.py", line 49, in <module>
    main()
  File "C:\Users\rahul\GitHub\skarfie123\sqltest\main.py", line 45, in main
    assert "name" in rows[0]
           ^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by skarfie123** [comment]
according to the docstring in 1.3.18:

```
        """Return True if this :class:`.RowProxy` contains the given key.

        Through the SQLAlchemy 1.x series, the ``__contains__()`` method
        of :class:`.RowProxy` also links to :meth:`.RowProxy.has_key`, in that
        an expression such as ::

            "some_col" in row

        Will return True if the row contains a column named ``"some_col"``,
        in the way that a Python mapping works.

        However, it is planned that the 2.0 series of SQLAlchemy will reverse
        this behavior so that ``__contains__()`` will refer to a value being
        present in the row, in the way that a Python tuple works.

        """
```

so I would have expected 1.4.47 to continue the behaviour

**Comment by skarfie123** [comment]
Ah I see, thank you
