### ISSUE TITLE
`DELETE RETURNING` and `UPDATE RETURNING` CTEs no longer compile with ORM API in SQLAlchemy 2.0

### ISSUE THREAD

**Issue by optimalstrategy** [sqlalchemy/sqlalchemy#9767]
### Describe the bug

After upgrading to SQLAlchemy 2.0 from 1.4 according to the [Major Migration Guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html), all my queries that `select` from CTEs consisting of `update().returning()` and `delete().returning()` no longer compile. At the same time, `insert().returning()` and `select()` CTEs continue to work as expected.

The compile failure can be triggered both using `print(query)` and `.execute(query)`, and the database driver does not appear to be relevant.

I'm using the ORM API to define my tables. The bug does not occur with the Core API.

### SQLAlchemy Version in Use

2.0.13

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import (
    delete,
    Column,
    Integer,
    MetaData,
)
from sqlalchemy.orm import declarative_base

meta = MetaData()
Base = declarative_base(metadata=meta)


class T1(Base):
    __tablename__ = "t1"
    id = Column("id", Integer, primary_key=True)


cte_delete = delete(T1).returning(T1.id).cte("delete_t1")
query = cte_delete.select()
print(query)

```

### Error

```
Traceback (most recent call last):
  File "/home/user/test/sqlalchemy-repro/repro.py", line 20, in <module>
    print(query)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 291, in __str__
    return str(self.compile())
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 4738, in visit_select
    text = self._compose_select_body(
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 4886, in _compose_select_body
    [
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 4887, in <listcomp>
    f._compiler_dispatch(
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 4080, in visit_cte
    inner = cte.element._compiler_dispatch(
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6003, in visit_update
    compile_state = update_stmt._compile_state_factory(
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 678, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1403, in create_for_statement
    self._setup_for_orm_update(statement, compiler)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1489, in _setup_for_orm_update
    new_stmt = self._setup_orm_returning(
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 535, in _setup_orm_returning
    ) = ORMFromStatementCompileState.create_for_statement(fs, compiler)
  File "/home/user/.cache/pypoetry/virtualenvs/venv-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 665, in create_for_statement
    raise sa_exc.CompileError(
sqlalchemy.exc.CompileError: The ORM FromStatement construct only supports being invoked as the topmost statement, as it is only intended to define how result rows should be returned.

```

### Additional context

The snippet below provides more examples and a comparison with the Core API behavior:

<details>
<summary>orm_vs_core.py</summary>

```py
import sqlalchemy.exc
from sqlalchemy import (
    insert,
    select,
    update,
    delete,
    Column,
    Integer,
    MetaData,
    Table,
)
from sqlalchemy.orm import declarative_base

meta = MetaData()
Base = declarative_base(metadata=meta)

print("=== ORM API ===")


class T1(Base):
    __tablename__ = "t1"
    id = Column("id", Integer, primary_key=True)


cte_delete = delete(T1).returning(T1.id).cte("delete_t1")
query1 = cte_delete.select()
try:
    print(query1)
except sqlalchemy.exc.CompileError as e:
    print("1. CTEs with DELETE RETURNING don't work")
    print("Error:", e)
    print()

cte_update = update(T1).returning(T1.id).cte("update_t1")
query2 = cte_update.select()
try:
    print(query2)
except sqlalchemy.exc.CompileError as e:
    print("2. CTEs with UPDATE RETURNING don't work")
    print("Error:", e)
    print()

print("3. CTEs with INSERT RETURNING work")
cte_insert = insert(T1).returning(T1.id).cte("insert_t1")
query3 = cte_insert.select()
print(query3)
print()

print("4. CTEs with SELECT work")
cte_select = select(T1.id).cte("delete_t1")
query4 = cte_select.select()
print(query4)
print()

print("=== Core API ===")
T2 = Table(
    "t2",
    meta,
    Column("id", Integer, primary_key=True),
)

print("1. Core CTEs with DELETE RETURNING work")
cte_delete = delete(T2).returning(T2.c.id).cte("delete_t2")
query1 = cte_delete.select()
print(query1)
print()

print("2. Core CTEs with UPDATE RETURNING work")
cte_update = update(T2).returning(T2.c.id).cte("update_t2")
query2 = cte_update.select()
print(query2)
print()

print("3. CORE CTEs with INSERT RETURNING work")
cte_insert = insert(T2).returning(T2.c.id).cte("insert_t2")
query3 = cte_insert.select()
print(query3)
print()

print("4. CORE CTEs with SELECT work")
cte_select = select(T2.c.id).cte("select_t2")
query4 = cte_select.select()
print(query4)
```

</details>

**Comment by zzzeek** [comment]
wow that's a big one.  will have a look soon

**Comment by optimalstrategy** [comment]
Thank you for the quick response and resolution!
