### ISSUE TITLE
Using `Values` element in a scalar subquery triggers an error

### ISSUE THREAD

**Issue by evansd** [sqlalchemy/sqlalchemy#9772]
### Describe the bug

We are trying to work around the absence of the `GREATEST()` function in SQL Server using the Table Value Constructor approach described here:
https://stackoverflow.com/questions/71022/sql-max-of-multiple-columns/6871572#6871572

That is, given a table `t` like this:

pk | i1 | i2 | i3
-- | -- | -- | --
100 | 1 | 2 | 3
200 | 6 | 5 | 4
300 | 7 | 8 | 9

We would like to generate SQL like this:
```sql
SELECT
  t.pk,
  (SELECT max(tvc.v1) FROM (VALUES (t.i1), (t.i2), (t.i3)) AS tvc (v1)) AS max_i 
FROM
  t
```

To get these results:
pk | max_i
-- | --
100 | 3
200 | 6
300 | 9

We are able to construct the appropriate query (see reproducing example), but when we try to compile it we get an error in `visit_values` here:
https://github.com/sqlalchemy/sqlalchemy/blob/e0bf5ba169975d879c22bc61b1aaf4261ac0559f/lib/sqlalchemy/sql/compiler.py#L4284-L4286

```
TypeError: sqlalchemy.sql.visitors.Visitable._generate_compiler_dispatch.<locals>._compiler_dispatch()
got multiple values for keyword argument 'include_table'
```

Because `kw` contains the entry `{"include_table": True}`.

Editing the SQLAlchemy code to remove the entry from the passed keywords is enough to make the code run and produce the expected output in our case:
```py
kw.pop("include_table", None)
```

But I'm afraid I don't know enough about why `include_table` is being passed through here to know if this only addresses the symptom of a deeper issue. Or indeed, whether we're not constructing the query in the right way.

Thanks!

### SQLAlchemy Version in Use

2.0.13

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.11.3

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy as sa

table = sa.Table(
    "t",
    sa.MetaData(),
    sa.Column("pk", sa.Integer),
    sa.Column("i1", sa.Integer),
    sa.Column("i2", sa.Integer),
    sa.Column("i3", sa.Integer),
)

table_value_constructor = sa.values(sa.Column("v1", sa.Integer), name="tvc").data(
    [
        (table.c.i1,),
        (table.c.i2,),
        (table.c.i3,),
    ]
)

maximum = sa.select(sa.func.max(table_value_constructor.c.v1))
maximum_subquery = maximum.scalar_subquery()
query = sa.select(table.c.pk, maximum_subquery)

print("-- Select maximum clause")
print(maximum)
print()

print("-- Select maximum clause as scalar subquery")
print(query)
```

### Error

```
-- Select maximum clause
SELECT max(tvc.v1) AS max_1 
FROM (VALUES (t.i1), (t.i2), (t.i3)) AS tvc (v1)

-- Select maximum clause as scalar subquery
Traceback (most recent call last):
  File "/home/dave/projects/ebmdatalab/ehrql/repro.py", line 30, in <module>
    print(query.compile(dialect=MSDialect_pymssql()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 288, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/dialects/mssql/base.py", line 2046, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 1426, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4678, in visit_select
    for c in [
             ^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4679, in <listcomp>
    self._label_select_column(
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4504, in _label_select_column
    return result_expr._compiler_dispatch(self, **column_clause_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 2496, in visit_label
    label.element._compiler_dispatch(
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 2366, in visit_grouping
    return "(" + grouping.element._compiler_dispatch(self, **kwargs) + ")"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4738, in visit_select
    text = self._compose_select_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4886, in _compose_select_body
    [
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4887, in <listcomp>
    f._compiler_dispatch(
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4283, in visit_values
    ", ".join(
  File "/home/dave/.virtualenvs/ebm-ehrql/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 4284, in <genexpr>
    c._compiler_dispatch(
TypeError: sqlalchemy.sql.visitors.Visitable._generate_compiler_dispatch.<locals>._compiler_dispatch() got multiple values for keyword argument 'include_table'
```

**Comment by zzzeek** [comment]
thanks for reporting
