### ISSUE TITLE
Using back_populates with MappedAsDataclass and asdict causing RecursionError

### ISSUE THREAD

**Issue by gam-phon** [sqlalchemy/sqlalchemy#9785]
### Describe the bug

Using ```back_populates``` with ```MappedAsDataclass``` and ```asdict``` causing error ```RecursionError: maximum recursion depth exceeded while calling a Python object``` using ```backref``` avoid this error, however ```backref``` is considered as legacy and should be avoided

So is this an expected behaviour or this should be handled?

### Optional link from https://docs.sqlalchemy.org which documents the relationship in dataclass

https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#relationship-configuration
https://docs.sqlalchemy.org/en/20/orm/backref.html

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

dataclass error without connecting to db

### Database Vendor and Major Version

dataclass error without connecting to db

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
from dataclasses import asdict
from sqlalchemy import (
    PrimaryKeyConstraint,
    ForeignKeyConstraint,
    String,
)
from sqlalchemy.orm import (
    MappedAsDataclass,
    DeclarativeBase,
    Mapped,
    backref,
    mapped_column,
    relationship,
)

class Base(MappedAsDataclass, DeclarativeBase):
    pass

class A(Base):
    __tablename__ = "as"
    id: Mapped[str] = mapped_column(String, nullable=False)
    bs: Mapped[list["B"]] = relationship(
        lazy="raise",
        default_factory=list,
        back_populates="a",
        repr=False,
    )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
    )


class B(Base):
    __tablename__ = "bs"
    id: Mapped[str]  = mapped_column(String, nullable=False)
    a: Mapped["A"] = relationship(
        lazy="raise",
        default=None,
        back_populates="bs",
        # backref="bs",
        uselist=False,
    )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
        ForeignKeyConstraint(["id"], ["as.id"]),
    )


if __name__ == "__main__":
    a = A(id="1")
    b = B(id="2", a=a)
    print(asdict(a))
```

### Error

```
Traceback (most recent call last):
  File "/path_to_file/sqlalchemy_try.py", line 55, in <module>
    print(asdict(a))
          ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1277, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1284, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1312, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
...
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1318, in _asdict_inner
    return copy.deepcopy(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 137, in deepcopy
    d = id(x)
        ^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
``` 

### Additional context

avoiding ```back_populates``` by ```backref``` let you avoid the issue

```python

from dataclasses import asdict
from sqlalchemy import (
    PrimaryKeyConstraint,
    ForeignKeyConstraint,
    String,
)
from sqlalchemy.orm import (
    MappedAsDataclass,
    DeclarativeBase,
    Mapped,
    backref,
    mapped_column,
    relationship,
)

class Base(MappedAsDataclass, DeclarativeBase):
    pass

class A(Base):
    __tablename__ = "as"
    id: Mapped[str] = mapped_column(String, nullable=False)
    # bs: Mapped[list["B"]] = relationship(
    #     lazy="raise",
    #     default_factory=list,
    #     back_populates="a",
    #     repr=False,
    # )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
    )


class B(Base):
    __tablename__ = "bs"
    id: Mapped[str]  = mapped_column(String, nullable=False)
    a: Mapped["A"] = relationship(
        lazy="raise",
        default=None,
        # back_populates="bs",
        backref="bs",
        uselist=False,
    )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
        ForeignKeyConstraint(["id"], ["as.id"]),
    )


if __name__ == "__main__":
    a = A(id="1")
    b = B(id="2", a=a)
    print(asdict(a))

```

**Comment by zzzeek** [comment]
hi - 

this can trivially be demonstrated with plain dataclasses and is a bug in the Python stdllib dataclasses.asdict() function, if you want to report it.   They might leave it as a "wontfix" though.


```py
from __future__ import annotations

import dataclasses

@dataclasses.dataclass
class A:

    id: str
    bs: list[B] = dataclasses.field(default_factory=list)


@dataclasses.dataclass
class B:

    id: str
    a: A

if __name__ == "__main__":
    a = A(id="1")
    b = B(id="2", a=a)
    a.bs.append(b)

    print(dataclasses.asdict(a))
```

same stack trace

**Comment by zzzeek** [comment]
also no, bi-directional relationships are not deprecated.  back_populates is preferred over backref because it works better with typing and it's clearer what's going on, but runtime there is no difference between back_populates and backref.  What's happening with "backref" here is that the A.bs relationship is not being considered as part of the dataclass because it's implicit.   

you can get the same effect by omitting the a.bs relationship from the dataclass def by not giving it an annotation:

```py
class A(Base):
    __tablename__ = "as"
    id: Mapped[str] = mapped_column(String, nullable=False)

    if not TYPE_CHECKING:
        bs = relationship(
            "B",
            lazy="raise",
            back_populates="a",
            repr=False,
        )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
    )
```

or assigning it after the fact.    overall though this seems like a dataclasses bug, as deepcopy() would not have this problem directly, it does recursion checking.

**Comment by zzzeek** [comment]
ah well, there you go, seems someone familiar posted the bug: https://github.com/python/cpython/issues/94345

**Comment by gam-phon** [comment]
Thank you @zzzeek for your detail explanation.

I like using ```if not TYPE_CHECKING``` approach than using ```backref``` even if I do not get autocompletion for it. 
Also this is a good way to exclude some fields that I do not want to be included in dataclass as well. I hope that ```asdict``` had an option to explicit specified fields or exclude them. Anyway, thank you again Mike.

**Comment by CaselIT** [comment]
> even if I do not get autocompletion for it.

You can do something like this:
```py
class A(Base):
    __tablename__ = "as"
    id: Mapped[str] = mapped_column(String, nullable=False)

    if TYPE_CHECKING:
        bs: Mapped[list[B]]
    else:
        bs = relationship(
            "B",
            lazy="raise",
            back_populates="a",
            repr=False,
        )

    __table_args__ = (
        PrimaryKeyConstraint("id"),
    )
```

**Comment by gam-phon** [comment]
Thank you @CaselIT with this trick now it looks near perfect. Thank you so much
