### ISSUE TITLE
Can not use ORM model with multiprocessing

### ISSUE THREAD

**Issue by PaleNeutron** [sqlalchemy/sqlalchemy#9788]
### Describe the bug

`AttributeError: Can't pickle local object 'create_engine.<locals>.connect'`

Multiprocessing code example in document works, but ORM model created by `declarative_base` breaks it.

Replace text sql with code below will cause this issue.

```
sql = (
    select(t)
    .where(t.S_INFO_WINDCODE == "801019.SI")
    .order_by(t.REPORT_PERIOD)
    .where(t.REPORT_PERIOD >= "20090101")
    .where(t.REPORT_PERIOD <= "20221231")
)
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/pooling.html#using-connection-pools-with-multiprocessing-or-os-fork

### SQLAlchemy Version in Use

2.0.13

### DBAPI (i.e. the database driver)

cx_oracle

### Database Vendor and Major Version

Oracle 11g

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from multiprocessing import Pool
from sqlalchemy import create_engine, text
import os
# from pathos.multiprocessing import ProcessPool as Pool
import pandas as pd

from amdb.client.wind.models.AIndexFinancialderivative import (
    AIndexFinancialderivative as t,
)
from sqlalchemy import select

sql = (
    select(t)
    .where(t.S_INFO_WINDCODE == "801019.SI")
    .order_by(t.REPORT_PERIOD)
    .where(t.REPORT_PERIOD >= "20090101")
    .where(t.REPORT_PERIOD <= "20221231")
)


class Foo:
    def __init__(self) -> None:
        self.engine = create_engine(os.environ["WINDDB_HOST"], pool_pre_ping=True)

    def run_in_process(self, some_data_record):
        print(some_data_record)
        self.engine.dispose(close=False)
        with self.engine.connect() as conn:
            # options = {"index_col": "REPORT_PERIOD", "parse_dates": ["REPORT_PERIOD"]}
            ret = pd.read_sql(sql, conn)
            print(ret)
            # time.sleep(1)


foo = Foo()
# foo.run_in_process(1)
# foo.engine.dispose()

with Pool() as p:
    p.map(foo.run_in_process, range(30))
```

### Error

```
Traceback (most recent call last):
  File "/home/john/projects/amdb/s2.py", line 40, in <module>
    p.map(foo.run_in_process, range(30))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'create_engine.<locals>.connect'
```

**Comment by zzzeek** [comment]
hi -

your program is by definition attempting to send the entire "engine" as an argument to a multiprocessing pool worker.   The engine is not compatible with being passed as an argument with Python's multiprocessing as it requires serialiaztion.

how is "engine" passed as an argument?    it's part of the "self" that's inherent to the "foo.run_in_process" bound method you are sending:

```
>>> foo.run_in_process
<bound method Foo.run_in_process of <__main__.Foo object at 0x7f0526ece2d0>>
>>> foo.run_in_process.__self__
<__main__.Foo object at 0x7f0526ece2d0>
>>> foo.run_in_process.__self__.engine
Engine(oracle://scott:***@oracle18c)
```

correct code - always keep engines global:

```py
from multiprocessing import Pool

from sqlalchemy import create_engine
from sqlalchemy import text


engine = create_engine(
    "oracle://scott:tiger@oracle18c", pool_pre_ping=True
)

class Foo:

    def run_in_process(self, some_data_record):
        print(some_data_record)
        engine.dispose(close=False)
        with engine.connect() as conn:
            ret = conn.execute(text("select 1 from dual"))
            print(ret)


foo = Foo()

with Pool() as p:
    p.map(foo.run_in_process, range(30))

```
