### ISSUE TITLE
getsizeof() raises TypeError on PyPy3.10 7.3.12rc1

### ISSUE THREAD

**Issue by mgorny** [sqlalchemy/sqlalchemy#9789]
### Describe the bug

While doing some initial testing of PyPy3.10 7.3.12rc1, I've noticed the following test regression in SQLAlchemy:

```
FAILED test/orm/test_cache_key.py::EmbeddedSubqTest::test_cache_key_gen[memory-_exclusions_01] - TypeError: getsizeof(...)
```

I'm somewhat surprised it didn't fail for me before but from the description you shouldn't be calling it.

### SQLAlchemy Version in Use

2.0.13

### DBAPI (i.e. the database driver)

n/a

### Database Vendor and Major Version

n/a

### Python Version

PyPy3.10 7.3.12rc1

### Operating system

Gentoo Linux

### To Reproduce

```python
pypy3 -m pytest # ;-)
```

### Error

```
_____________________________________ EmbeddedSubqTest.test_cache_key_gen[memory-_exclusions_01] ______________________________________
Traceback (most recent call last):
  File "<string>", line 2, in test_cache_key_gen
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 797, in check_exclusions
    return fn(*args[:-1], **kw)
  File "<string>", line 2, in test_cache_key_gen
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/lib/sqlalchemy/testing/exclusions.py", line 93, in decorate
    return self._do(config._current, fn, *args, **kw)
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/lib/sqlalchemy/testing/exclusions.py", line 123, in _do
    self._expect_failure(cfg, ex, name=fn.__name__)
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/lib/sqlalchemy/testing/exclusions.py", line 137, in _expect_failure
    raise ex.with_traceback(sys.exc_info()[2])
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/lib/sqlalchemy/testing/exclusions.py", line 121, in _do
    return_value = fn(*args, **kw)
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/test/orm/test_cache_key.py", line 1174, in test_cache_key_gen
    int_within_variance(29796, total_size(ck), 0.05)
  File "/tmp/portage/dev-python/sqlalchemy-2.0.13/work/SQLAlchemy-2.0.13/lib/sqlalchemy/testing/util.py", line 488, in total_size
    default_size = getsizeof(0)  # estimate sizeof object without __sizeof__
TypeError: getsizeof(...)
    getsizeof(object, default) -> int

    Return the size of object in bytes.

sys.getsizeof(object, default) will always return default on PyPy, and
raise a TypeError if default is not provided.

First note that the CPython documentation says that this function may
raise a TypeError, so if you are seeing it, it means that the program
you are using is not correctly handling this case.

On PyPy, though, it always raises TypeError.  Before looking for
alternatives, please take a moment to read the following explanation as
to why it is the case.  What you are looking for may not be possible.

A memory profiler using this function is most likely to give results
inconsistent with reality on PyPy.  It would be possible to have
sys.getsizeof() return a number (with enough work), but that may or
may not represent how much memory the object uses.  It doesn't even
make really sense to ask how much *one* object uses, in isolation
with the rest of the system.  For example, instances have maps,
which are often shared across many instances; in this case the maps
would probably be ignored by an implementation of sys.getsizeof(),
but their overhead is important in some cases if they are many
instances with unique maps.  Conversely, equal strings may share
their internal string data even if they are different objects---or
empty containers may share parts of their internals as long as they
are empty.  Even stranger, some lists create objects as you read
them; if you try to estimate the size in memory of range(10**6) as
the sum of all items' size, that operation will by itself create one
million integer objects that never existed in the first place.
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**omit pypy from sizeof tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4617

**Comment by zzzeek** [comment]
OK, that one test is omitted from pypy in latest main and will be next release.  that's all that was going wrong?
