### ISSUE TITLE
InterfaceError for column_property with inferred Enum

### ISSUE THREAD

**Issue by phy1729** [sqlalchemy/sqlalchemy#9909]
### Describe the bug

Column properties that use an inferred Enum column with a expression that binds a parameter raises an InterfaceError.

### SQLAlchemy Version in Use

2.0.15

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.10.11

### Operating system

Linux

### To Reproduce

```python
from enum import Enum
from enum import auto
from sqlalchemy import create_engine
from sqlalchemy import select
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import Session
from sqlalchemy.orm import column_property
from sqlalchemy.orm import mapped_column


class Alignment(Enum):
    Good = auto()
    Neutral = auto()
    Evil = auto()


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = 'user'

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    alignment: Mapped[Alignment] = mapped_column()

    is_good = column_property(alignment == Alignment.Good)


engine = create_engine('sqlite://')
Base.metadata.create_all(engine)


with Session(engine) as session:
    session.execute(select(User)).scalars().all()
```

### Error

```
Traceback (most recent call last):
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phy1729/sqla-demo/demo.py", line 37, in <module>
    session.execute(select(User)).scalars().all()
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/phy1729/sqla-demo/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT user.alignment = ? AS anon_1, user.id, user.name, user.alignment 
FROM user]
[parameters: (<Alignment.Good: 1>,)]
(Background on this error at: https://sqlalche.me/e/20/rvf5)
```

### Additional context

The exception does not occur if the type is explicit in mapped_column i.e. `alignment: Mapped[Alignment] = mapped_column(sqlalchemy.Enum(Alignment))`.

The exception also does not occur if the value of the enum is used in the column_property i.e. `is_good = column_property(alignment == Alignment.Good.value)`.

**Comment by CaselIT** [comment]
Hi,

I don't think this issue is fixable at the moment, since when the column property is processed the `alignment` has no type assigned (the type is `NullType`).
SQLAlchemy can process the left side types only after the class definition, so to work around this issue column property should add support to lambdas. That's tracked by #6120

@zzzeek I don't know if you have other suggestion here. If not I guess we can close

**Comment by zzzeek** [comment]
there's no fix for this as given, workaround is to ensure the type is assigned when the expression is created

```py
from enum import Enum
from enum import auto
from sqlalchemy import create_engine, type_coerce
from sqlalchemy import types
from sqlalchemy import select
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import Session
from sqlalchemy.orm import column_property
from sqlalchemy.orm import mapped_column


class Alignment(Enum):
    Good = auto()
    Neutral = auto()
    Evil = auto()


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    alignment: Mapped[Alignment] = mapped_column()

    is_good = column_property(
        type_coerce(alignment, types.Enum(Alignment)) == Alignment.Good
    )


engine = create_engine("sqlite://")
Base.metadata.create_all(engine)


with Session(engine) as session:
    session.execute(select(User)).scalars().all()

```
